### ISSUE TITLE
The "From" attribute don't work.

### ISSUE THREAD

**Issue by luffyZh** [nodemailer/nodemailer#1003]
os: mac
node: v8.14.0
nodemailer: latest
```
const transporter = nodemailer.createTransport({
    service: "126",
    port: 465,
    secure: true, // true for 465, false for other ports
    auth: {
      user: "zhoudeyou945@126.com", // generated ethereal user
      pass: "xxx" // generated ethereal password
    }
  });
  const info = await transporter.sendMail({
    from:'"zhoudy" <zhoudeyou945@126.com>', // sender address
    to: "zhoudeyou945@163.com, luffyzh@163.com", // list of receivers
    subject: title, // Subject line
    text: content, // plain text body
    html: content
  });
```
but the received emails the from user is converted the fixed time format.
<img width="673" alt="图片" src="https://user-images.githubusercontent.com/17840558/56345360-20190000-61f2-11e9-9aab-306860a6394d.png">

**Comment by andris9** [comment]
Can you provide the raw email in RFC822 format? In some email clients it can be found from "Show original" or "Save as ->Raw Message Source" etc.

**Comment by luffyZh** [comment]
@andris9 sorry, I don't know much about email. I don't know if you mean the following：
```
Date: Thu, 18 Apr 2019 15:42:23 +0800
From: =?utf-8?B?0JzQsNC50LvQtdGALCDQndC+0LTQtQ==?= <zhoudeyou945@126.com>
To:  <zhoudeyou945@163.com>,  <luffyzh@163.com>
Message-ID: <b4988053-a8e8-10ab-acd1-1f963cf2bdd4@126.com>
Subject: =?utf-8?B?5o+S5YWl5raI5oGvLTA4?=
MIME-Version: 1.0
Content-Type: multipart/alternative; 
 boundary="mailmaster-5cb83029_4f068571_44d4"

--mailmaster-5cb83029_4f068571_44d4
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

fsfsdfsfsdf
--mailmaster-5cb83029_4f068571_44d4
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64

ZnNmc2Rmc2ZzZGY=

--mailmaster-5cb83029_4f068571_44d4--

```

**Comment by andris9** [comment]
This message seems to be altered during delivery. Nodemailer uses different format for node boundaries, so this is not the exact message Nodemailer sent out. Otherwise everything seems totally fine. If your mail client is not able to display the From name correctly (in this case the From name seems to be 'Майлер, Ноде') then it is a bug in the mail client.
