### ISSUE TITLE
Sendmail transport doesn't handle CC and BCC with envelope

### ISSUE THREAD

**Issue by akhudushin** [nodemailer/nodemailer#1004]
Seems that the following code:
`mail.data.envelope || mail.message.getEnvelope()`
[here](https://github.com/nodemailer/nodemailer/blob/9f08832c9a54e676e08a888339353156dc60f779/lib/sendmail-transport/index.js#L66) and [here](https://github.com/nodemailer/nodemailer/blob/9f08832c9a54e676e08a888339353156dc60f779/lib/sendmail-transport/index.js#L91)

Causing Sendmail to handle only original TO field in envelope (without merged CC and BCC).

For instance, the following envelope object:
`{
            "from": "foo@localhost",
            "to": "bar@localhost",
            "cc": "baz1@localhost",
            "bcc": "baz2@localhost"
}`
will be saved in `mail.data.envelope` as is and cause Sendmail to send email only to `bar@localhost`.

But using `mail.message.getEnvelope()` will provide us with correct object for Sendmail:
`{
            "from": "foo@localhost",
            "to": [ "bar@localhost", "baz1@localhost",  "baz2@localhost" ]
}`

The question is: can we use `mail.message.getEnvelope() || mail.data.envelope` instead of the original code or remove `mail.data.envelope` at all?

**Comment by andris9** [comment]
`mail.data.envelope` is the optional `envelope` object provided  by mail options. `mail.message.getEnvelope()` is generated from the `from`, `to`, `cc` and `bcc` headers. So in your case - do not set the `envelope` object, only use the regular mail headers. The `envelope` object only exists to override normal delivery configuration, it is not required. 

Use it if you need to use VERP address as `from` but in that case you are responsible for setting all the correct `to` addresses in the envelope as well. `envelope` object does not take header addresses, it requires `from` for SMTP `MAIL FROM` and `to` for SMTP `RCPT TO`. This is not the same as `to`, `cc`, `bcc` in message headers.

**Comment by VividVisions** [comment]
We encountered the same problem. 

The documentation states, that ”addresses from this value get added to RCPT TO list” for to, cc and bcc fields. When using an SMTP transport the envelope gets parsed and converted accordingly. When using a sendmail transport, this doesn't happen. Why? It shouldn't matter which transport is used in this case.
