### ISSUE TITLE
Ethereal Certificate Expired

### ISSUE THREAD

**Issue by cdunford** [nodemailer/nodemailer#1006]
Nodemailer: 4.7.0

I am using `createTestAccount` to generate a test account for my e2e tests. Everything was working 5 days ago or so, however now, when I try to send a mail using smtp.ethereal.email, I am now receiving error: "Error: certificate has expired". Here is how I am creating the transport (in line with what is described here: https://nodemailer.com/smtp/testing/):

``` javascript
  const transport = createTransport({
      host: 'smtp.ethereal.email',
      port: 587,
      secure: false,
      auth: {
        user: testAccount.user,
        pass: testAccount.pass,
      },
    });

    return transport.sendMail({
      from: 'test@test.local',
      to,
      cc,
      subject,
      html: body,
    })
```

I've changed nothing and it has just stopped working. I've also tried setting `secure:true`, however this results in the error: "Error: 140593138587520:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:332"

**Comment by jaulz** [comment]
Quick workaround: add `tls: { rejectUnauthorized: false }`

**Comment by andris9** [comment]
Certificate was updated but SMTP service was not restarted and it continued to use the old certificate.

**Comment by mingxin-yang** [comment]
@andris9 Hi, I also encountered this problem
