### ISSUE TITLE
The recipients are all displayed

### ISSUE THREAD

**Issue by MarxZhou** [nodemailer/nodemailer#1007]
I have a problem with the recipient display exception.When I tested the group messaging feature, I found that all the recipients were listed in the email.
Here is my mailOptions:
From: ` services < ${Config. ALI_MAIL_SMTP_USER} > `, // '123456@test.com,123456@test02.com'
To: ` ${JSON.Parse(receversArray).toString ()} `,
Subject: 'title',
HTML: mailTmp.mkTmp (type, the action, url)
![微信图片_20190429183309](https://user-images.githubusercontent.com/39861054/56890866-3efa7a80-6aad-11e9-95ca-c0587a8e2da4.jpg)

**Comment by andris9** [comment]
This is how email works. If you want to show only one recipient in the To: field, then send emails out one by one - one email for each recipient.
