### ISSUE TITLE
Encoding option enumerable values

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#1009]
Documentation at https://nodemailer.com/message/ may need updated enumerable values for `encoding` option (e.g. mention this value can also be `ISO-2022-JP`, etc)

Related to https://github.com/niftylettuce/forward-email/issues/85

**Comment by andris9** [comment]
`encoding` in nodemailer mail settings is not charset configuration but specifies the input encoding of the element. Eg. if you want to provide mail content as valid JSON and want to use binary attachments then you can set a base64 string as the attachment content and set `encoding` to "base64". The conversion is performed like this: `actualValue = Buffer.from(content, encoding)`. `encoding` in top level configuration applies to `text`, `html` etc.

**Comment by niftylettuce** [comment]
ty
