### ISSUE TITLE
textEncoding option documentation needs updated

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#1010]
The value of `textEncoding` should be one of the possible per https://www.w3.org/Protocols/rfc1341/5_Content-Transfer-Encoding.html.

> Content-Transfer-Encoding := "BASE64" / "QUOTED-PRINTABLE" / 
                             "8BIT"   / "7BIT" / 
                             "BINARY" / x-token
 
> These values are not case sensitive. That is, Base64 and BASE64 and bAsE64 are all equivalent. An encoding type of 7BIT requires that the body is already in a seven-bit mail- ready representation. This is the default value -- that is, "Content-Transfer-Encoding: 7BIT" is assumed if the Content-Transfer-Encoding header field is not present.

The current docs only list the following:

> textEncoding - force content-transfer-encoding for text values (either quoted-printable or base64). By default the best option is detected (for lots of ascii use quoted-printable, otherwise base64)

**Comment by andris9** [comment]
`textEncoding` is a configuration option for encoded mime words. Nodemailer takes mail subject as an unicode string and converts it to encoded-word if the string contains any special characters. Encoded words can only use base64 or quoted-printable encodings (see [here](https://tools.ietf.org/html/rfc2047#section-4))

**Comment by niftylettuce** [comment]
ty
