### ISSUE TITLE
'"encoding" must be a valid string encoding' when using attachment from Buffer (created from multer)

### ISSUE THREAD

**Issue by Ncifra** [nodemailer/nodemailer#1013]
Hi,

We were trying to set up the mail sending service as part of one microservice. The setup/scenario is like this:
1. Server A sends a `form-data` request through the `request` module to Server B (text + file).
2. Server B receives it through `multer` for the interpretation of the `form-data`

After this we try and send an email with the received file as an attachment using the following code (a bit incorrect since it was shortened but to give the idea):

```javascript
const nodemailer = require('nodemailer');
const AWS = require('aws-sdk');
const ses = new AWS.SES();
let transport = nodemailer.createTransport({
                SES: ses
            });
            let mailOptions = {
                from: sender,
                to: emailStructure.to,
                subject: emailStructure.subject,
                html: emailStructure.html,
                attachments: emailStructure.attachments
            };
            transport.sendMail(mailOptions);
```

Now, if we send the attachments above by first saving the file in storage and then forwarding multer's array `req.files` where each element has this structure:

```json
{
  "fieldname": "attachments",
  "originalname": "report-1557223111148.pdf",
  "encoding": "7bit",
  "mimetype": "application/pdf",
  "destination": "./uploads",
  "filename": "attachments-1557223117432",
  "path": "uploads\\attachments-1557223117432",
  "size": 87477
}
```

Multer's config:

```javascript
var storage = multer.diskStorage({
    destination: function (req, file, callback) {
        callback(null, './uploads');
    },
    filename: function (req, file, callback) {
        callback(null, file.fieldname + '-' + Date.now());
    }
});
var upload = multer({storage: storage}).array('attachments', 10);
```

Everything works correctly, and the email is sent.

If we configure multer to use the memory storage like so:

```javascript
var storage = multer.memoryStorage();
var upload = multer({storage: storage}).array('attachments', 10);
```

and each `req.files` element has this structure:

```javascript
{
  "fieldname": "attachments",
  "originalname": "report-1557223231274.pdf",
  "encoding": "7bit",
  "mimetype": "application/pdf",
  "buffer": {
    "type": "Buffer",
    "data": [
    .....too much in here......
    ]
  },
  "size": 87422
}
```
(notice also the smaller size)

we get the message:

> "encoding" must be a valid string encoding

We are trying to not save the files locally since we don't need them, and it makes sense to use them directly from memory, considering they shouldn't be very big in size. The above configurations may not be all necessary but I added them just in case. I think the important part is the difference between the Buffer from the memory and the file from the disk.

Thank you

**Comment by Ncifra** [comment]
Am I supposed to write something to keep it alive?

**Comment by andris9** [comment]
You should convert your multer in-memory file to Nodemailer attachment structure as described in the docs [here](https://nodemailer.com/message/attachments/).

If you just provide whatever data multer has then you run into errors. For example the encoding error you have comes from the fact that multer gives you an object where `encoding` defines the `Content-Transfer-Encoding` provided by uploading client which is 7bit (or binary or 8bit or whatever).

For Nodemailer the same key means Buffer encoding string (possible values are defined [here](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings)).

**Comment by Ncifra** [comment]
Yes, I will look into this, thank you. But considering this:

```
{
  "fieldname": "attachments",
  "originalname": "report-1557223111148.pdf",
  "encoding": "7bit",
  "mimetype": "application/pdf",
  "destination": "./uploads",
  "filename": "attachments-1557223117432",
  "path": "uploads\\attachments-1557223117432",
  "size": 87477
}
```

How come it works? Is the "not allowed" 7bit encoding just overlooked and it reverts to a default? 

I think our error comes from the fact that the Buffer is on the "buffer" key, while it seems that it should be inside the "content" key of the Nodemailer object. An overlook of this due to the fact that it worked with the default multer file saved locally, and its object, so that structure was taken as some sort generic shared type of object between multer, Nodemailer and other packages dealing with files.
