### ISSUE TITLE
6.2.1 was published to npm, but isn't in the git repo?

### ISSUE THREAD

**Issue by papandreou** [nodemailer/nodemailer#1019]
nodemailer 6.2.1 was published:

```
$ npm info nodemailer

nodemailer@6.2.1 | MIT | deps: none | versions: 218
Easy as cake e-mail sending from your Node.js applications
https://nodemailer.com/

keywords: Nodemailer

dist
.tarball: https://registry.npmjs.org/nodemailer/-/nodemailer-6.2.1.tgz
.shasum: 20d773925eb8f7a06166a0b62c751dc8290429f3
.integrity: sha512-TagB7iuIi9uyNgHExo8lUDq3VK5/B0BpbkcjIgNvxbtVrjNqq0DwAOTuzALPVkK76kMhTSzIgHqg8X1uklVs6g==
.unpackedSize: 478.1 kB

maintainers:
- andris <andris@node.ee>

dist-tags:
beta: 2.4.0-beta.0  latest: 6.2.1       

published 3 days ago by andris <andris@kreata.ee>
```

But there's no v6.2.1 tag in the repo here? @andris9, did you forget to push?

**Comment by andris9** [comment]
It’s a typo. I wanted to release 6.2.0 but accidentally the version nr in package.json was set to 6.2.1 (changed from 6.1.1)

**Comment by papandreou** [comment]
Ah, okay, `npm version minor` is your friend :)

Would you mind tagging 7b2ec1d977dbaa74072dbe7fba734e62e39a9965 with `v6.2.1` as well, then? Some automated tools depend on that.

**Comment by andris9** [comment]
https://github.com/nodemailer/nodemailer/releases/tag/v6.2.1

**Comment by papandreou** [comment]
Thanks a lot! :hugs:
