### ISSUE TITLE
unable to get mail in gmail inbox

### ISSUE THREAD

**Issue by surabhiv** [nodemailer/nodemailer#1020]
Hello sir,

i am using nodemailer for sending mail.but i am facing issue that mail is not coming in gmail inbox.
i am using Ubuntu 16.04 x64 LTS ,
 Node version -8.16.0,
NPM version - 6.4.1
Also Please check Attachment here is the response after sending mail in this i got one error i.e. ehlo not implemented.
![Screenshot from 2019-05-30 18-02-41](https://user-images.githubusercontent.com/24150492/58688516-4fe72600-83a2-11e9-846e-8e4bf27553be.png)

**Comment by andris9** [comment]
Nodemailer is just a SMTP client. Once it gets message delivered to MTA then Nodemailer does not know how the message is routed or does it ends up in Spam etc.
