### ISSUE TITLE
Receiving Mails in Spam Folder

### ISSUE THREAD

**Issue by AhmadRaza786** [nodemailer/nodemailer#1022]
I have a major module in project that sends emails periodically to 10 email at a time. and it repeats again and again after 1-2 minutes. in fact I am sending too many email. and these all emails are landing in spam folder. I need to make them land into the inbox. what can be the reasons behind and what can be its solution ?

**Comment by andris9** [comment]
Nodemailer generates valid emails and passes these to a MTA for delivery. Getting emails to Inbox is out of scope for Nodemailer.
