### ISSUE TITLE
Shared Logger is Unusable

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#1031]
Related to #730, it would be great to have a better, more usable logger that doesn't adhere to the odd shared logger setup.

For example, when I'm using `signale` or even the widely used `pino`, and I get the odd unformatted strings in my output:

```sh
ℹ  info      { component: 'smtp-server',
  tnx: 'listen',
  host: '::',
  port: 49488,
  secure: false,
  protocol: 'SMTP' } { value: '[object Object]%s Server listening on %s:%s' } '' 'SMTP' '[::]' 49488
ℹ  info      { component: 'smtp-server',
  tnx: 'connection',
  cid: 'mvuuek25e6yto4ea',
  host: '127.0.0.1',
  hostname: '[127.0.0.1]' } { value: 'Connection from [object Object]' } '[127.0.0.1]'
```

Is there an example as to how to use `pino` or `signale` properly?

Ref:
- https://github.com/pinojs/pino
- https://github.com/klaussinani/signale

**Comment by niftylettuce** [comment]
@andris9 could we re-open?

**Comment by andris9** [comment]
Yeah, sure. The logger is a mess, I know, I just haven't had any time to work on it.

**Comment by niftylettuce** [comment]
Did you just want to integrate Cabin?  And people can plug in their own loggers into it (via Axe)?

**Comment by dex4er** [comment]
Currently Nodemailer is compatible with Bunyan. I see that Cabin has reverted arguments: first message then meta. Bunyan has first meta then message. It doesn't look like it is difficult to switch from one to another but changing it in Nodemailer will make it not compatible with previous API.

**Comment by niftylettuce** [comment]
Perhaps what I can do is make Cabin compatible with Bunyan users, and thus compatible with this lib, and have a case check where first arg is obj and second is a string.

**Comment by niftylettuce** [comment]
I have released `axe@5.0.0` and `cabin@6.0.0` which adds Bunyan compatibility to both [Axe][] and [Cabin][]; which make them a great drop-in alternative/replacement to Bunyan as well.  This solves my issue here... but I would suggest to still incorporate something like Cabin (or just pass a `logger` option defaulting to `console`) in the future to make things easier for future developers to debug.

[axe]: https://github.com/cabinjs/axe
[cabin]: https://cabinjs.com

**Comment by niftylettuce** [comment]
@andris9 	you may want to re-open this if you plan on incorporating a different approach.  my advice is to do a major version bump, default the logger to `console`, and allow users to override default `logger` option by passing their own.  and in the docs you could suggest Cabin or Bunyan. 👍

**Comment by freshgiammi** [comment]
For those wandering here: `pino` works line, but if you use typescript you might want to set the type as `any`, as nodemailer does not expect an object of type `pino.Logger`.
