### ISSUE TITLE
Sent Mails are not coming up in the sent folder

### ISSUE THREAD

**Issue by SaravananMB** [nodemailer/nodemailer#1032]
when I send mail from Nodemailer (test@vivantcorp.com) it works fine also the recipient is getting the mail in their INBOX.
But when I login to the Email Client application (https://apps.rackspace.com/index.php), The mails which I sent from Nodemailer (test@vivantcorp.com) are not showing in the sent folder.

let transporter = nodemailer.createTransport({
    host: "secure.emailsrvr.com",
    port: 465,
    secure: true,
    auth: {
      user: "test@vivantcorp.com"
      pass: password
    }
  });

I have used the above configuration for nodemailer.
we are using nodemailer version 6.2.1

can you please help us to figure out the issue.

**Comment by SaravananMB** [comment]
Please let me know If there is any option to set mail folder path

**Comment by andris9** [comment]
Nodemailer is a SMTP client. If you want to get messages also to the Sent Mail folder then you need to upload the same message using IMAP which is out of scope for Nodemailer. Gmail does this automatically (anything sent via SMTP is copied to IMAP) but this is non-standard.

**Comment by SaravananMB** [comment]
Got It @andris9 . Thanks for your information

**Comment by BarryRufer** [comment]
> Nodemailer is a SMTP client. If you want to get messages also to the Sent Mail folder then you need to upload the same message using IMAP which is out of scope for Nodemailer. Gmail does this automatically (anything sent via SMTP is copied to IMAP) but this is non-standard.
Could you give an example of a solution?
