### ISSUE TITLE
Error: 4412364224:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:  code: 'ESOCKET', command: 'CONN' }

### ISSUE THREAD

**Issue by liyinchigithub** [nodemailer/nodemailer#1037]
`   it('发送邮件2', function () {
        var transport = nodemailer.createTransport({
            service: 'smtp.xxx.com',
            host: "smtp.xxx.com",
            secure: true,
            port: 587,
            auth: {
                user: "xxx@xxx.com",//邮箱账号
                pass: "xxx@2018"//授权码
            },

        });

        var mailOptions = {
            from: "xxx@xxx.com",
            to: "yinchi.li@xxx.com",
            subject: "测试报告",//标题
            text: "这是正文",
            html: "<h1>测试</h1>",
        }

        transport.sendMail(mailOptions, function (err, response) {
            if (err) {
                console.log(err);
            } else {
                console.log(response);
            }
        })
    })`

`{ Error: 4412364224:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
 code: 'ESOCKET', command: 'CONN' }`

**Comment by andris9** [comment]
Set `secure` to false for port 587

**Comment by liyinchigithub** [comment]
Thank you very much for your answer
According to your suggestion, this error appears
![image](https://user-images.githubusercontent.com/19643260/61283223-5e24c080-a7ef-11e9-97ce-2b8221f5be9f.png)

**Comment by liyinchigithub** [comment]
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'ESOCKET', command: 'CONN' }

**Comment by liyinchigithub** [comment]
@andris9  
On behalf of my team, thank you again

**Comment by liyinchigithub** [comment]
The problem was solved perfectly.
`
secure: false,
port: 587,
tls: {
                rejectUnauthorized: false
            },
`

**Comment by ahsanlakhani** [comment]
Hi @andris9, nodemailer was working perfectly fine for me and I was receiving emails but suddenly it stopped sending emails and I am receiving a similar error.

Error: 68924277868352:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
 code: 'ESOCKET', command: 'CONN'

My port is 465 and secure is set to true.
