### ISSUE TITLE
Error: Missing credentials for "PLAIN"  at SMTPConnection._formatError

### ISSUE THREAD

**Issue by zbisj** [nodemailer/nodemailer#1039]
Hi I am trying to setup nodemailer with gmail and so far I have been following this [video:](https://www.youtube.com/watch?v=JJ44WA_eV8E&list=PLYIjD89S7D3PnScBCD9Xv8_l2fC_P0RxX&index=3&t=32s)

**Here is my code:** 
` 
const nodemailer = require("nodemailer"); 
const xoauth2 = require('xoauth2');

    // create reusable transporter object using the default SMTP transport
    let transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        xoauth2:  xoauth2.createXOAuth2Generator({
          user: "myemail@gmail.com",
          clientId: 'xxxxxxxxxxxxxxxxx',
          clientSecret: 'xxxxxxxxxxxxxxxxx',
          refreshToken: 'xxxxxxxxxxxxxxxxx'
        })
      }
    });

    // send mail with defined transport object
    let mailOptions = {
      from: '"Fred Foo 👻" <sender@email.com>', // sender address
      to: "receiver@email.com", // receiver address
      subject: "Hello ✔", // Subject line
      text: "Hello world?", // plain text body
      html: "<b>Hello world?</b>" // html body
    };

    transporter.sendMail(mailOptions, (error, res) => {
      if (error) {
        console.log(error);
      }else {
        console.log("email is sent");
      }
    })
`

**I am getting this error:** 
`{ Error: Missing credentials for "PLAIN"
    at SMTPConnection._formatError (/home/xxxxxx/projects/my-projects/test/node_modules/nodemailer/lib/smtp-connection/index.js:781:19)
    at SMTPConnection.login (/home/xxxxxx/projects/my-projects/test/node_modules/nodemailer/lib/smtp-connection/index.js:452:38)
    at connection.connect (/home/xxxxx/projects/my-projects/test/node_modules/nodemailer/lib/smtp-transport/index.js:271:32)
    at SMTPConnection.once (/home/xxxxx/projects/my-projects/test/node_modules/nodemailer/lib/smtp-connection/index.js:209:17)
    at Object.onceWrapper (events.js:286:20)
    at SMTPConnection.emit (events.js:198:13)
    at SMTPConnection._actionEHLO (/home/xxxxxxx/projects/my-projects/test/node_modules/nodemailer/lib/smtp-connection/index.js:1309:14)
    at SMTPConnection._processResponse (/home/xxxxxxxx/projects/my-projects/test/node_modules/nodemailer/lib/smtp-connection/index.js:940:20
)
    at SMTPConnection._onData (/home/xxxxxxxxx/projects/my-projects/test/node_modules/nodemailer/lib/smtp-connection/index.js:746:14)
    at TLSSocket.SMTPConnection._onSocketData (/home/xxxxxxxxx/projects/my-projects/test/node_modules/nodemailer/lib/smtp-connection/index.js
:189:46) code: 'EAUTH', command: 'API' }`

**Version Numbers**

os: ubuntu 19.04
node 10.16.0
nodemailer 6.3.0

I do not understand which credentials are missing as I have provided them. I have looked on almost all the articles on this issue and none have helped.

Also a quick question: Is it possible to use nodemailer on just a create-react-app without having to setup a backend for it? 

Thanks in advance

**Comment by tdj03001** [comment]
Did you ever figure this out? I'm on a deadline and this error has all of a sudden crept into my project. It was running fine and I think the only thing I may have changed between when it was running and now is my google account authentication. Any ideas would be very welcomed!

**Comment by dankore** [comment]
For me, it was due to not adding my Gmail password to the .env file.

**Comment by ajj-siraj** [comment]
> For me, it was due to not adding my Gmail password to the .env file.

I can't believe I just spent 4 hours trying to debug this when this was all it was. I was using a private mail server though not Gmail, but same issue.

**Comment by MrFarhan** [comment]
@zbisj try running it locally with NGROK server... it is working fine.

I am also facing same issue, my code is working fine and sending emails, but showing error on heroku.

I am using zoho email server

**Comment by Kamrulhasan12345** [comment]
For me, it was occuring while adding no text field in message object

**Comment by berenia** [comment]
Hi guys,
I was able to fix this issue on my end. What I did was this:

- log the transporter object 
- check the properties and values if its there
- then I discovered pass value was showing undefined.
- then I discovered I didn't add it to my environment variable on the server

I hope this is helpful to someone

**Comment by kushagra9999** [comment]
Thanks it worked for me .

**Comment by killshot13** [comment]
Same issue here. I had rebuilt the `dotenv-vault` and provided the decryption key to the server, but I had forgotten to update the mail server password in the `.env` file first. Oops!🤦🏼‍♂️

**Comment by devashishroychowdhury** [comment]
Try to use your _email password_ in **.env** file and **run** the program again it might fix your issue

**Comment by rohitkashyaprk** [comment]
Hi, In the first go try to use pass instead of password in auth field.

**Comment by wariszargardev** [comment]
const transporter = nodemailer.createTransport({
        host: process.env.EMAIL_HOST,
        port: process.env.EMAIL_PORT,
        auth: {
            user: process.env.EMAIL_USERNAME,
            pass: process.env.EMAIL_PASSWORD
        }
    });
    
    try this one

**Comment by AdrianoLMRS** [comment]
Yeah my .env wasn't loading ...
