### ISSUE TITLE
Sending emails in node js using nodemailer  tls issues coming

### ISSUE THREAD

**Issue by dinesh2907** [nodemailer/nodemailer#1040]
Please report only real bugs here.

If you have trouble setting up Nodemailer then the best place to look for help would be the documentation https://nodemailer.com/
var mailer = require("nodemailer");
 
// Use Smtp Protocol to send Email
var smtpTransport = mailer.createTransport({
    service: "Gmail",
    auth: {
        user: "myuser",
        pass: "mypassword"
    }
});
 
var mail = {
    from: "Dinesh <myuser>",
    to: "some@gmail.com",
    subject: "Send Email Using Node.js",
    text: "Node.js New world for me",
    html: "<b>Node.js New world for me</b>"
}
 
smtpTransport.sendMail(mail, function(error, response){
    if(error){
        console.log(error);
    }else{
        console.log("Message sent: " + response.message);
    }
    
    smtpTransport.close();
});
 
and the error is

{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'ESOCKET', command: 'CONN' }

**Comment by ryokartawijaya** [comment]
have u solved the problem? im having the same problem here. I need help omg

**Comment by andris9** [comment]
You have a MITM somewhere. Usually it is antivirus program that listens on TLS traffic.
