### ISSUE TITLE
Question about shared.resolveHostname logic

### ISSUE THREAD

**Issue by madarche** [nodemailer/nodemailer#1041]
Hello,

This is not a bug report, nor a PR so far.

From the README one reads:
> Nodemailer changed from dns.lookup() to dns.resolve for resolving SMTP hostnames which might be backwards incompatible and thus the version bump. Nodemailer tries first resolve4() and if no match is found then resolve6() and finally reverts back to lookup()

And I find it a good and safe logic.

But the implementation logic in [lib/shared/index.js](/nodemailer/nodemailer/blob/master/lib/shared/index.js) seems to be more like:

1. try `resolve(4 …)`
2. f error or no match is found then return.

So this seems to have the effect that `resolver(6 …)` and `dns.lookup` below never have the chance to be called.

Or am I missing something?

If not, shouldn't the implementation logic described above be modified to follow the logic presented in the README? If so, I'll gladly submit a PR to this end.

Cheers

**Comment by andris9** [comment]
Was this something that happened to you (no IPv6 resolving) or did you figure this by reading the code?

The logic should go like this

1. try [resolver(4...](https://github.com/nodemailer/nodemailer/blob/5e1a1af0d1af48f4d1a6e87244965560d76e00f3/lib/shared/index.js#L55) If nothing is found then it returns an empty array
2. If resolve result array [has any elements](https://github.com/nodemailer/nodemailer/blob/5e1a1af0d1af48f4d1a6e87244965560d76e00f3/lib/shared/index.js#L63) then use it as the return value
3. If the resolve result array was empty, then continue to [resolver(6...](https://github.com/nodemailer/nodemailer/blob/5e1a1af0d1af48f4d1a6e87244965560d76e00f3/lib/shared/index.js#L75)

**Comment by madarche** [comment]
Hello @andris9,

The logic you are describing just above is **indeed correct**, thank you for the clarification! Sorry! My understanding has missed the cases of the empty arrays.

I've been reading the code, and the README and the [SMTP Transport doc about "If you are using a non-resolvable hostname (eg. something listed in */etc/hosts*)"](https://nodemailer.com/smtp/), because I'm interested in still using hostnames from `/etc/hosts` with recent versions of nodemailer (5+).


Still I'm wondering, wouldn't it be possible/desirable to have the following logic?

1. Try `resolver(4...`
2. If resolve result array has any elements then use it as the return value
3. Else (error or empty array) then continue to `resolver(6...`
4. Try `resolver(6...`
5. If resolve result array has any elements then use it as the return value
6. Else (error or empty array) then continue to `dns.lookup`
7. Try `dns.lookup`

What cases would it not accommodate?

Thank you

**Comment by andris9** [comment]
The logic you described is exactly what happens there. After resolve6 returns 0 results, then the resolver moves on to [dns.lookup](https://github.com/nodemailer/nodemailer/blob/5e1a1af0d1af48f4d1a6e87244965560d76e00f3/lib/shared/index.js#L96)

**Comment by andris9** [comment]
Usually Nodemailer should work fine with `/etc/hosts` but in some server configurations there might be issues resolving DNS queries. If you can not use Nodemailer because it fails DNS lookups then you have to use `host` property as IP and `tls.servername` as the hostname for certificate checks. If Nodemailer works for you then you do not have to worry about DNS lookups.

**Comment by madarche** [comment]
I'm well aware of this part from the documentation (but thanks again for taking the time to mention it):
> If you can not use Nodemailer because it fails DNS lookups then you have to use host property as IP and tls.servername as the hostname for certificate checks. 

I confirm that the DNS servers I'm using are responding with errors when they are requested with hostnames from `/etc/hosts`, those DNS servers are not responding with empty arrays. Thus the `resolveHostname` function never gets far enough to reach the `dns.lookup` call.

The logic I'm proposing in the [above comment](https://github.com/nodemailer/nodemailer/issues/1041#issuecomment-515042745) is to move to the next resolver in case of error. That should help with this situation with DNS servers throwing errors with (rightfully) unknown hostnames.

I'm bothering you with this because specifying hostnames in configurations is often a very desirable setting when servers and IP are changed, but hostnames don't.

Are you interested in changing the actual logic with what I'm proposing? Are there any side effects I might have missed? And I won't be bothering you anymore with this ticket if you don't!

**Comment by andris9** [comment]
Not-found error codes should be added to [this list](https://github.com/nodemailer/nodemailer/blob/5e1a1af0d1af48f4d1a6e87244965560d76e00f3/lib/shared/index.js#L18-L20) and it should start working.

**Comment by madarche** [comment]
OK!

In the beginning the actual error I was receiving when specifying an hostname (`smtp_host` for that matter) was the following:

```
{ Error: queryA ESERVFAIL smtp_host
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:197:19)
  errno: 'ESERVFAIL',
  code: 'EDNS',
  syscall: 'queryA',
  hostname: 'smtp_host',
  command: 'CONN' } Error: queryA ESERVFAIL smtp_host
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:197:19)
```

And if I add `dns.SERVFAIL` to the error list you are mentioning just above, the error changes to:

```
{ Error: getaddrinfo EAI_AGAIN smtp_host
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'EAI_AGAIN',
  code: 'EDNS',
  syscall: 'getaddrinfo',
  hostname: 'smtp_host',
  command: 'CONN' } Error: getaddrinfo EAI_AGAIN smtp_host
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
```

But what's strange is that the DNS server doesn't choke when I'm querying it with `dig` on the command line for the `smtp_host` hostname. This doesn't look like an `ESERVFAIL` at all …

```shellsession
$ dig smtp_host @192.168.1.111

; <<>> DiG 9.10.3-P4-Debian <<>> smtp_host @192.168.1.111
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 55876
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;smtp_host.                     IN      A

;; Query time: 0 msec
;; SERVER: 192.168.1.111#53(192.168.1.111)
;; WHEN: Thu Jul 25 16:23:10 CEST 2019
;; MSG SIZE  rcvd: 38
```

To give you all needed information this is happening with a Node.js 10.15.0 instance.

**Comment by madarche** [comment]
I must add that I've never used the Node.js `dns` module so far. And thus I might be missing something very obvious… I hope not

**Comment by andris9** [comment]
DNS implementations are weird. You get `ESERVFAIL` for the missing A record and `EAI_AGAIN` (which should be a timeout error) for the missing AAAA record. Adding these error codes to the list should fix it for you.

**Comment by andris9** [comment]
You could try adding these codes locally and if it works then make a Pull Request against this repo

**Comment by madarche** [comment]
OK! 

This works with the following modified code:
```javascript
        if (err) {
            switch (err.code) {
                case dns.NODATA:
                case dns.NOTFOUND:
                case dns.NOTIMP:
                case dns.SERVFAIL:
                case 'EAI_AGAIN':
                    return callback(null, []);
            }
            return callback(err);
        }
```

I'm doing a PR right now. Thanks a lot for your very great help.

**Comment by madarche** [comment]
@andris9 thank you very much for nodemailer@6.3.1 that includes this fix.
