### ISSUE TITLE
sending emails with the wrong adress doesn't return on rejected 

### ISSUE THREAD

**Issue by yonjuukyuu** [nodemailer/nodemailer#1042]
So i'm sending emails with on nodejs with nodemailer and so far so good, but when there is a wrong email address the transporter.sendMail() info doesn't return on rejected but as accepted.
Shouldn't it return a error or as rejected ? 

On the following image, the first email is correct and second one is incorrect
![nodemailer_bug](https://user-images.githubusercontent.com/11752587/61870589-60190e80-aed6-11e9-9276-328d89c2a814.png)

**Comment by andris9** [comment]
Nodemailer passes emails over to your MTA. MTA server does not know if an address is valid or not and accepts everything. If the address turns out to be invalid then MTA generates a bounce response and sends it to the address of the sender (whatever is listed in `envelope.from`)
