### ISSUE TITLE
net.isIP

### ISSUE THREAD

**Issue by christiantigre** [nodemailer/nodemailer#1049]
I just installed this library but at the moment of sending an email the error message returns 

My SO MOJAVE

**Uncaught TypeError: net.isIP is not a function
    at Object.push../node_modules/nodemailer/lib/shared/index.js.module.exports.resolveHostname (index.js:42)
    at SMTPConnection.connect**

Mi code 
`const nodemailer = require("nodemailer");
const config = require("../../../config/main");

class Login extends Component {

  constructor(props) {
    super(props);

let transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 587,
  secure: false,
  auth: {
    user: config.email.EMAIL,
    pass: config.email.PASSWORD
  }
});

const mailOptions = {
  from: 'from@gmail.com', // sender address
  to: "tomail@gmail.com", // list of receivers 
  subject: "Hello ✔", // Subject line
  text: "Hello world?", // plain text body
  html: "<b>Hello world?</b>" // html body
}

transporter.sendMail(mailOptions, function (error, response) {
  if (error) {
      console.log(error);
  }
  else {
      console.log("mail sent");
      console.log(response);
  }
});

}
}
`
helpme !!!

**Comment by rk173238** [comment]
I  have the Same issue.

Please update if it is resolved.

**Comment by rk173238** [comment]
I believe ,nodemailer is meant to be run in node environment, but not browser.

I tried this code to merge in react app ,that is why it was not working. Now I am using it as backend service.

**Comment by knoxcard** [comment]
@christiantigre - what version of nodeJS are you on?
https://nodejs.org/api/net.html#net_net_isip_input

I am assuming all of you are running outdated versions of nodeJS. Upgrade to the very latest and retry, use NVM as well to make it easy...

https://github.com/nvm-sh/nvm

**Comment by andris9** [comment]
Nodemailer does not work in browser env

**Comment by CPATRICK321** [comment]
ok but where should the code go instead?

**Comment by ThePlatinum** [comment]
the code should go in server-side, create an express server and call send the mail from the server. Check [this article](https://codeforgeek.com/send-e-mail-node-js/) to help better.
