### ISSUE TITLE
Addressparser should be its own module

### ISSUE THREAD

**Issue by DavidIAm** [nodemailer/nodemailer#1058]
mailerparser depends on nodemailer just so it can use addressparser.  Ouch. This should be broken out of nodemailer so the addressparser functionality can be utilized more modularly.  Referenced in pull request 1057

https://github.com/nodemailer/nodemailer/pull/1057

**Comment by andris9** [comment]
Not extracting any modules from Nodemailer into external modules. This is by design as Nodemailer is supposed to be self-contained.
