### ISSUE TITLE
Getting  "Invalid login: 504 5.7.4 Unrecognized authentication type" when sending emails from custom SMTP Server

### ISSUE THREAD

**Issue by rahul2739** [nodemailer/nodemailer#1060]
Following Error Occurred when Try to send Mails From Nondemailer

code:"EAUTH"
command:"AUTH PLAIN"
message:"Invalid login: 504 5.7.4 Unrecognized authentication type"
response:"504 5.7.4 Unrecognized authentication type"
responseCode:504
stack:"Error: Invalid login: 504 5.7.4 Unrecognized authentication type\n    at SMTPConnection._formatError

**Comment by Miksyuk** [comment]
Did you find solve? I have same issue.

**Comment by andris9** [comment]
This happens when SMTP server does not support standard authentication mechanisms. For example if O365 admin has disabled password auth for accounts.

**Comment by bauchetmax** [comment]
I have the same issue when trying to send about 65 mails one after another. I have the same message for the first 10 mails and then it works well for the next ones. Any ideas?
