### ISSUE TITLE
Why not send CC copy mail?

### ISSUE THREAD

**Issue by XIIIcool** [nodemailer/nodemailer#1064]
let RFC822Message = await SMTPFacade.buildMail({
            from: process.env.EMAIL,
            sender: process.env.EMAIL,
            to: recipients,
            cc: recipientsCC,
            subject: subject,
            html: html,
            inReplyTo: messageId,
            references: references
        });

      // this envelope
        let sendingResult = await SMTPFacade.send(SMTPConnection, {
            from: process.env.EMAIL,
            to: recipients,
            cc: recipientsCC,
        }, RFC822Message);

in the sent letter in headers there is a cc: email field but copies are not sent

**Comment by andris9** [comment]
You probably have to merge to and cc addresses in the SMTP envelope
