### ISSUE TITLE
Error: 7288:error:1408F10B:SSL routines:ssl3_get_record:wrong version 

### ISSUE THREAD

**Issue by renanbastos93** [nodemailer/nodemailer#1074]
Can you help me?

[Error: 7288:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
] {
library: 'SSL routines',
function: 'ssl3_get_record',
reason: 'wrong version number',
code: 'ESOCKET',
command: 'CONN'
}

**Comment by andris9** [comment]
You are either trying to use TLS on a non-TLS port or the openssl version you use is not compatible with the server.

**Comment by funkenstrahlen** [comment]
I have exactly the same issue.

**Comment by renanbastos93** [comment]
@funkenstrahlen I changed approach to use an email address from Gmail.

**Comment by gabrielmaximo** [comment]
Oh god i have the same problem, somebody help me!

**Comment by urltrn13** [comment]
\ws\deps\openssl\openssl\ssl\record

**Comment by Durgaa-G** [comment]
@renanbastos93 What you have changed? I am facing same issue

**Comment by renanbastos93** [comment]
> @renanbastos93 What you have changed? I am facing same issue

@Durgaa-G 

I had used an email private example `renan@bastos.com` so I changed to use the email from Gmail then I have succeeded. But I don't understand why it.

**Comment by Durgaa-G** [comment]
I was using business gmail, even though I changed to personal Gmail, Its not working for me. :(

**Comment by renanbastos93** [comment]
> I was using business Gmail, even though I changed to personal Gmail, It's not working for me. :(

You need to change the permission of the email for can using

**Comment by Durgaa-G** [comment]
@renanbastos93 Thanks for help.

**Comment by renanbastos93** [comment]
> @renanbastos93 Thanks for help.

anytime, see ya

**Comment by carvalholeo** [comment]
Heys guys, do you have some update about this issue?

I'm using Umbler (Brazilian hosting and email provider) as Email provider, for sending emails from my private, corp email from Nodemailer, and I'm getting this same error right now.

**Comment by jodeperezlo** [comment]
I configured my transporter like this:

```javascript
export const transporter = nodemailer.createTransport({
	host: Config.EMAIL_HOST,
	port: Config.EMAIL_PORT,
	auth: {
		user: Config.EMAIL_USER, 
		pass: Config.EMAIL_PASSWORD,
	},
	secureConnection: false,
});
```

With that is working.
