### ISSUE TITLE
Well known service "Mailgun" not working

### ISSUE THREAD

**Issue by bertolla** [nodemailer/nodemailer#1078]
Tried to use Mailgun as well knwon service, by setting `service: 'Mailgun'`, but got login failed as response. 
I noticed that the configured mailserver is https://github.com/nodemailer/nodemailer/blob/505c3f9ae06658ba80720f6b49a659588bb82b70/lib/well-known/services.json#L96

but Mailgun gave me this endpoint  "smtp.eu.mailgun.org" for the smtp-server   
I guess that mailgun uses different subdomains for each regions now and nodemailer is not considering this.

**Comment by andris9** [comment]
Mailgun used to have a single domain for all customers. There is no way to know which server is assigned to which user so if the built in service description does not work then you have to set the server configuration values yourself and not use the "well known service" info.

**Comment by bertolla** [comment]
In Mailgun's documentation page they state that currently there are just two regions ¹.
The domain "smtp.mailgun.org" is still used for the US, so it will still work there.

¹ https://documentation.mailgun.com/en/latest/api-intro.html#mailgun-regions
