### ISSUE TITLE
Cannot send email from verified address via AWS SES when its domain includes upper case characters

### ISSUE THREAD

**Issue by Kuchitama** [nodemailer/nodemailer#1080]
Then the verified email includes upper case characters in its domain, sending email is failed.

For example:

The email `xxxxx@EXAMPLE.com` is verified in AWS SES.

But `sendEmail` returns below error.

```
MessageRejected: Email address is not verified. The following identities failed the check in region US-EAST-1: xxxx@example.com
```

The cause is address normalization.
https://github.com/nodemailer/nodemailer/blob/master/lib/mime-node/index.js#L1187

To avoid this problem, we need some ways to skip `domain.toLowerCase()` or to set `Source` or `SourceArn` directory.

**Comment by andris9** [comment]
You should be able to override from address by using `envelope` property. This would mean though that you would have to list all recipients as well

```
{
    "from": "xxxxx@example.com",
    "to": "xxxxx@test.com",
    "cc": "some.other@test.com",
    "envelope": {
        "from": "xxxx@EXAMPLE.com", // single address without name, will be used as "Source"
        "to": ["xxxxx@test.com", "some.other@test.com"] // all recipients from "to", "cc" and "bcc" fields as an array of addresses
    }
}
```

**Comment by Kuchitama** [comment]
Thank you so much!
