### ISSUE TITLE
Attachment filename and contentType are removed upon normalization

### ISSUE THREAD

**Issue by ericduvon** [nodemailer/nodemailer#1084]
Packages used:
`nodemailer-sendgrid v.1.0.3`
`nodemailer v.4.7.0`

I understand that using `mail.normalize` is setup such that all attachments are normalized to base64 strings.

The issue I am running into is that after this [normalization](https://github.com/nodemailer/nodemailer/blob/master/lib/mailer/mail-message.js#L144) happens, it removes the `filename` and `contentType` fields from the attachments, only returning the base64 string in the `content` field.

This causes SendGrid API to respond with this error message:
```
{ errors: 
  [ { message: 'The attachment filename parameter is required.',
      field: 'attachments.0.filename',
      help: 'http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.attachments.filename' } ] }
```
Does anyone have feedback as to why `filename` and `contentType` aren't surviving the normalization?

Let me know if you need any additional info.

Thanks!

**Comment by andris9** [comment]
normalize does not remote filename or contentType. See the test output for JSON-transport [here for an example](https://github.com/nodemailer/nodemailer/blob/533b94593f133cf353bca4b2648c1fb8326b7d0e/test/json-transport/json-transport-test.js#L68-L83).
