### ISSUE TITLE
Cannot send mail when in production. Using localhost it works fine. 

### ISSUE THREAD

**Issue by RohitGalgali** [nodemailer/nodemailer#1085]
Hi, I have a lightsail production enviornment. On local enviornment i could send the mail but not in production environment.

var smtpTransport = nodemailer.createTransport({
    service: "gmail",
    host: "abcds",
    auth: {
        user: "**************",
        pass: "************"
    }
});

var mailOptions = {
                //from: req.query.from,
                to: "***************",
                subject: "Query for " + req.query.type,
                html: data,
            }
            //console.log(data);
            smtpTransport.sendMail(mailOptions, function (error, response) {
                if (error) {
                    console.log(error);
                    res.end("error");
                } else {
                    console.log("Sent");
                    res.end("sent");
                }
            })

**Comment by shanhuiyang** [comment]
Please read [USING GMAIL
](https://nodemailer.com/usage/using-gmail/)
