### ISSUE TITLE
BUG - E-mails are sent but never received

### ISSUE THREAD

**Issue by athilams** [nodemailer/nodemailer#1090]
I copied the example code in the nodemailer page (https://nodemailer.com/about/), and it ran as expected, giving a success callback, but the e-mail never reached my Inbox. After spending some time trying multiple solutions here for the same problem, without success, I accidentally discovered that 'Hello' as the subject was the problem. Anything different works perfectly. I don't know if this is really a Nodemailer bug, or something wrong with my email provider, so I'm sharing it here anyways.

**Comment by andris9** [comment]
Nothing to do with Nodemailer. You are probably triggering some spam rules with your email.
