### ISSUE TITLE
It gets stuck on RCPT TO:

### ISSUE THREAD

**Issue by snehil2112** [nodemailer/nodemailer#1092]
let transporter = mailer.createTransport({
            host: "domain-com.mail.protection.outlook.com", // hostname
            secureConnection: false,
            port: 25, // port for secure SMTP
            auth: {
                user: "user@domain.com",
                pass: "xxxxxx" 
            },
            debug: true,
            logger: true,
            ignoreTLS: true,
        });
    
        let info = await transporter.sendMail({
            from: 'user@domain.com',
            to: 'user2@domain.com',
            subject: "Registration Confirmation",
            text: "Registration Confirmation",
            html: 
        }

It gets stuck after this:

 EHLO [127.0.0.1]
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250-HK2APC01FT020.mail.protection.outlook.com Hello [115.110.155.29]
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250-SIZE 157286400
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250-PIPELINING
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250-DSN
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250-ENHANCEDSTATUSCODES
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250-STARTTLS
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250-8BITMIME
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250-BINARYMIME
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250-CHUNKING
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250 SMTPUTF8
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] SMTP handshake finished
[server] [2020-01-10 07:15:38] INFO  Sending message 
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] C: MAIL FROM:<user@domain.com>
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] S: 250 2.1.0 Sender OK
[server] [2020-01-10 07:15:38] DEBUG [nt6W0tdhYoA] C: RCPT TO:<user2@domain.com>

**Comment by snehil2112** [comment]
Getting timeout after a long time

**Comment by hinalshah91** [comment]
getting the following error:
TypeError: Cannot read property 'login' of undefined

**Comment by andris9** [comment]
Server is not responding. You could be tarpitted or there is a security device somewhere that scans your SMTP connections.
