### ISSUE TITLE
Getting `Unexpected socket close` when using Ethereal

### ISSUE THREAD

**Issue by TNuzzi** [nodemailer/nodemailer#1096]
Been running into this issue all day.  I am able to create the `ethereal.mail` account just fine and configure the transport however when I send I am getting the following error.  I was on nodemail 6.3.x and have since updated to the latest `6.4.2` with no luck.  Sorry to the ambiguous error let me know if there is some debug mode I can run it in to get more logs.

```
api          |   Error: Unexpected socket close
api          |       at Timeout.setTimeout (/app/node_modules/nodemailer/lib/smtp-transport/index.js:189:31)
api          |       at ontimeout (timers.js:436:11)
api          |       at tryOnTimeout (timers.js:300:5)
api          |       at unrefdHandle (timers.js:520:7)
api          |       at Timer.processTimers (timers.js:222:12)
```

Here is how I am initializing.  I have not changed this code in about a year.
```
nodemailer.createTestAccount()).then((account) => {
                this.testAccount = account;
                this.transport = nodemailer.createTransport({
                    host: account.smtp.host,
                    port: account.smtp.port,
                    secure: account.smtp.secure,
                    auth: {
                        user: account.user,
                        pass: account.pass
                    }
                });
```

Here is my latest NPM version.
```
➜  api git:(master) npm ls nodemailer
api@1.0.0 /api
└── nodemailer@6.4.2 
```

**Comment by rblaszynski** [comment]
I have the same problem. I checked on two different computers and got same error. It worked fine until yesterday.

`node v12.13.0`
`nodemailer v6.4.2`

**Comment by andris9** [comment]
This usually means that the ethereal.email MTA server is not working properly. As a free service it is not 100% reliable.  Should be ok by now.

**Comment by TNuzzi** [comment]
@andris9 Thanks.  Totally understand and appreciate it as a service.  Keep up the awesome work!

**Comment by DashBarkHuss** [comment]
Having the same issue. Wondering how frequently this happens. This wasn't happening to me until recently and this post looks recent too. Has it been more of an issue recently? When this is a problem, about how should I give it before I test again? Thanks for the service.

**Comment by andris9** [comment]
Testing load has gone up considerably recently while it’s still the same small VPS server doing all the processing.

**Comment by rojobuffalo** [comment]
i'm getting the same issue and `https://status.ethereal.mail/` is not working. is there another way to verify that ethereal is the breaking point?

**Comment by mshiyamsam** [comment]
Facing the same issue! Is there any alternate way to connect to an SMTP server?
Also is it possible to setup our own local SMTP server instance?

**Comment by rojobuffalo** [comment]
i got it working, but don't have a ton of confidence in explaining what exactly did the trick.

i'm on macos and have firewall enabled. i went to system preferences > security and privacy > firewall > unlock to make changes > firewall options > and then deleted a couple old exceptions for apps i no longer used, didn't change anything else, locked to prevent changes. i don't think that did anything but who know, it might have reset something.

next thing i did was run `sudo pfctl -vnf /etc/pf.conf - sudo pfctl -vnf /etc/pf.conf` in terminal. and as I understand it that command is meant to reload the firewall rules. but i didn't change anything specific to port 587. i got that command from this https://www.macworld.co.uk/how-to/how-open-specific-ports-in-os-x-1010-firewall-3616405/ .

before seeing if that worked, I changed the port option from 587 to 25 in `nodemailer.createTransport({` with `secure: false`, just bc i saw that somewhere else. that didn't work, the connection timed out. then I changed back to port 587 and it worked.

not a great hint but maybe somebody else who is stuck will find that useful.

some other things I was preparing to try but didn't end up needing to:

- https://stackoverflow.com/questions/38024428/error-connect-econnrefused-127-0-0-1465-nodemailer/62319129#62319129 
- ignoreTLS: true option inside `createTransport()`
- similar issue https://github.com/nodemailer/nodemailer/issues/438 
    - recommends sudo ufw allow 587
- https://stackoverflow.com/questions/20336126/need-to-reboot-mac-after-running-pfctl-e 
  - i haven't needed this. i restarted my computer and it still works but i didn't do anything to tell it to run on startup.

**Comment by mshiyamsam** [comment]
@rojobuffalo Thanks for your explanation.
I face this issue only when trying to call the application within my docker container, however when I try to hit the node js api running in docker container from postman it works. i.e react js ui running in docker when it tries to connect to node js in docker trying to trigger the mail throws this:

/home/node_modules/nodemailer/lib/smtp-connection/index.js:784
            err = new Error(message);
                  ^

Error: Data command failed: 421 Domain sandbox9a7997dd70324f71bcb79336ab4c82ec.mailgun.org is not allowed to send: Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings.
    at SMTPConnection._formatError (/home/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionDATA (/home/node_modules/nodemailer/lib/smtp-connection/index.js:1650:34)
    at SMTPConnection.<anonymous> (/home/node_modules/nodemailer/lib/smtp-connection/index.js:1622:26)
    at SMTPConnection._processResponse (/home/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/home/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at Socket.SMTPConnection._onSocketData (/home/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)

Thanks for ur help.

**Comment by ianmateusES** [comment]
I have the same problem.
