### ISSUE TITLE
“TypeError: Cannot read property ‘login’ of undefined”

### ISSUE THREAD

**Issue by hinalshah91** [nodemailer/nodemailer#1097]
I am getting this error from index.js file “TypeError: Cannot read property ‘login’ of undefined” on running firebase serve. I have already configured my gmail id and pwd.

**Comment by KameronKales** [comment]
can you paste the code here? Without seeing it Im not sure how to help

**Comment by andris9** [comment]
For Firebase and Nodemailer you probably can find help from StackOverflow. Please report here verifiable Nodemailer bugs only.
