### ISSUE TITLE
types for nodemailer-html-to-text

### ISSUE THREAD

**Issue by francoisromain** [nodemailer/nodemailer#1100]
Hello and thank you for this great module. 

I try to use `nodemailer-html-to-text` in a typescript project and I have this error: `Could not find a declaration file for module 'nodemailer-html-to-text'.`

How can is it possible to fix it? 

Thank you

**Comment by andris9** [comment]
Nodemailer does not have any official support for TypeScript. You have to write your own typings.

**Comment by francoisromain** [comment]
here is how I solved it: https://stackoverflow.com/a/60227962/2112538
