### ISSUE TITLE
Core bug with address parser

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#1102]
The email address of `"test@test.test"@example.com` is a valid email address, however the exported address parser function incorrectly parses it:

```sh
node -i
```

```sh
> const addressParser = require('nodemailer/lib/addressparser');
> addressParser('"test@test.test"@example.com')[0];
{ address: 'test@test.test', name: '@example.com' }
```

**Comment by niftylettuce** [comment]
FYI this is based off research here <https://webmasters.stackexchange.com/questions/104811/is-there-any-list-of-email-addresses-reserved-because-of-security-concerns-for-a/127447#comment173697_127447>

**Comment by niftylettuce** [comment]
FWIW this package seems to parse all addresses correctly, and also lists.

<https://www.npmjs.com/package/email-addresses>

BUT there are edge case bugs, such as this one: https://github.com/jackbearheart/email-addresses/issues/12

**Comment by niftylettuce** [comment]
```js
> addressParser('Kysen Vogel <kysen.vogel@gmail.com>,')
[ { address: 'kysen.vogel@gmail.com', name: 'Kysen Vogel' } ]
> email.parseAddressList('Kysen Vogel <kysen.vogel@gmail.com>,')
null
>
```

This package DOES properly parse that edge case, but it does not parse the one mentioned above.

**Comment by andris9** [comment]
addressparser module has never been RFC compliant. Instead it has been tuned to be able to process real-world addresses, including stuff that is not compatible with RFCs, like using semicolons instead of commas as list separator etc. If someone really is using something like `"test@test.test"@example.com` as an email address then not being compatible with addressparser is the least of their problems, you can't even post a comment to a WordPress blog using such address.

**Comment by niftylettuce** [comment]
Thanks, I actually forgot to comment and close this.  I mainly just wanted to file an issue stating my research/findings and that this was not RFC compliant to all specs (not that it was advertised other than a tag `rfc822` in repo's description.

**Comment by andris9** [comment]
Btw `email-addresses` is handling `'Kysen Vogel <kysen.vogel@gmail.com>,'` correctly. That is if you want to validate address list syntax. As defined in [RFC5322#3.4](https://tools.ietf.org/html/rfc5322#section-3.4):

```
address-list    =   (address *("," address)) / obs-addr-list
```

By this definition comma at the end of address list is not allowed. This is why addressparser is not RFC compliant but "real world" compliant - these things happen a lot. Even though it should fail validation and return nothing as `email-addresses` does, there are badly behaving mail clients or users typing address lists manually etc. so there is no point following this syntax.
