### ISSUE TITLE
DKIM - error hiding

### ISSUE THREAD

**Issue by sla100** [nodemailer/nodemailer#1103]
Related to issue https://github.com/nodemailer/nodemailer/issues/995#issuecomment-480509205_

There is misleading code inside `nodemailer/lib/dkim/sign.js` (line 42):
```js
try {
        signature = signer.sign(options.privateKey, 'base64');
    } catch (E) {
        return false;
    }
```
It seems to me, that program should thow error when private key is broken.

**Comment by andris9** [comment]
Signing (as most things that are handled at delivery time) is best effort. If it fails, then no signature is added.
