### ISSUE TITLE
linux server timeout error

### ISSUE THREAD

**Issue by lidor-castor** [nodemailer/nodemailer#1104]
I'm using nodemailer in sails.js app, I'm sending emails with private SMTP server (not Gmail). the SMTP have auth with password and username, and tls, when I'm trying to send mails from my local computer(windows) all work fine, but in production env (Linux server, AWS EC2, KB8 worker) the first or second mail sent and then the transport disconnect from the SMTP server, and blocked for a long time. the SMTP provider check his logs and responds to me that he sees errors in the recipient format, I also try to connect the SMTP with open_ssl and I succeed to send emails without any disconnect. I looked at all StackOverflow related issues but noting help to resolve that.

node -v: v8.3.0

linux: "Debian GNU/Linux 8 (jessie)" "Debian GNU/Linux" VERSION_ID "8" VERSION "8 (jessie)"

nodemailer version: "^6.4.2"

**Comment by andris9** [comment]
Most probably related to your own application logic, does not seem like a bug in Nodemailer. if you have any more details, then re-open this ticket.
