### ISSUE TITLE
Missing rabbit-queue example

### ISSUE THREAD

**Issue by kwisatz** [nodemailer/nodemailer#1107]
The docs at https://community.nodemailer.com/delivering-bulk-mail/ mention a rabbit-queue example that does however not exist on the master branch, only on the 2.3 branch (https://github.com/nodemailer/nodemailer/tree/v2.3/examples/rabbit-queue)

Does this mean the example has been deprecated?

**Comment by andris9** [comment]
That example was refactored into a standalone project https://github.com/nodemailer/nodemailer-amqp-example

**Comment by kwisatz** [comment]
Thanks
