### ISSUE TITLE
Sending with Bcc not working

### ISSUE THREAD

**Issue by AndreaFranchini** [nodemailer/nodemailer#1110]
I have a SMTP server builded with the `smtp-server` module.
I've created a pooled transport in order to send email to the server.

When sending the email i specify:
```
  await transporter.sendMail({
      from: 'from@something.com',
      to: ['to_1@something.com', 'to_2@something.com'],
      cc: ['cc@something.com'],
      bcc: ['bcc@something.com'],
      subject: 'A message',
      text: 'A random text',
  })
```

The server logs the Bcc as a To:
```
S: 235 Authentication successful
C: MAIL FROM:<from@something.com>
S: 250 Accepted
C: RCPT TO:<to_1@something.com>
S: 250 Accepted
C: RCPT TO:<to_2@something.com>
S: 250 Accepted
C: RCPT TO:<cc@something.com>
S: 250 Accepted
C: RCPT TO:<bcc@something.com>
S: 250 Accepted
C: DATA
S: 354 End data with <CR><LF>.<CR><LF>
```

But in the data reveived by the server there isn't:
```
Content-Type: text/plain; charset=utf-8
From: from@something.com
To: to_1@something.com, to_2@something.com
Cc: cc@something.com
Subject: A message
Message-ID: <e74a584c-3fdb-1a52-8417-b01093e1ed2e@rdcom.com>
Content-Transfer-Encoding: quoted-printable
Date: Wed, 04 Mar 2020 09:41:29 +0000
MIME-Version: 1.0

A random text
```

**Comment by carmenates09** [comment]
@AndreaFranchini  Finally I found the solution, I don't sure if will work for you.

By default, MailComposer drops the BCC header when built. If you need to BCC header to be shown when built, you’ll need to include the keepBcc option like so. [See Here](https://nodemailer.com/extras/mailcomposer/#bcc)

```
var mailOptions = {
   ...
   bcc: 'bcc@example.com'
}

var mail = new MailComposer(mailOptions).compile()
mail.keepBcc = true
mail.build(function(err, message){
    process.stdout.write(message);
});
```

See if you resolve with that.
Jose Carlos Ramos Carmenates

**Comment by ThePiyushAggarwal** [comment]
Hey @carmenates09 
Do you know the reason for dropping the BCC header? Just curious.

**Comment by ThePiyushAggarwal** [comment]
> To be honest no idea. Maybe we need to ping directly to the developers or maybe GPT could give us the right answer.
> 
> For emails Im using AWS SES, I dont use nodemail for many years.

I found in some discussion that it was done to be backwards compatible. Old code should work the same as it were before update.
