### ISSUE TITLE
send mail

### ISSUE THREAD

**Issue by ghostxbh** [nodemailer/nodemailer#1112]
Error: Invalid login: 535 5.7.0 (#AUTH005) Too many bad auth attempts.

**Comment by andris9** [comment]
Your Yahoo account probably does not allow password based authentication. Check your credentials and account settings.

**Comment by CHOQUEANO11** [comment]
é só vc ir nas configuração e ir na opção "criar senha para aplicativo", daí vc dá um nome ao app e gera um senha, depois é só colar no campo senha nas configurações do seu email para enviar.
