### ISSUE TITLE
 the letter is not sent, error - EREFUSED

### ISSUE THREAD

**Issue by eeeman1** [nodemailer/nodemailer#1113]
"nodemailer": "^6.4.4",

{ Error: queryA EREFUSED smtp.
yandex.ru
    at QueryReqWrap.onresolve [as oncom
plete] (dns.js:196:19)
  errno: 'EREFUSED',
  code: 'EDNS',
  syscall: 'queryA',
  hostname: 'smtp.yandex.ru',
  command: 'CONN' }

**Comment by andris9** [comment]
Seems like a DNS resolving issue. Make sure DNS is working properly in your system.

**Comment by eeeman1** [comment]
made sure dns is working correctly
