### ISSUE TITLE
About send Gmail

### ISSUE THREAD

**Issue by ghostxbh** [nodemailer/nodemailer#1118]
I use simple SMTP connection to send Gmail mailbox.
When I send by email, the sender's name is different from the sender's name using nodemailer.

This my code:
```
nodemailer.createTransport({
        service: 'Gmail',
        auth: {
            user: mailParam.from,
            pass: mailParam.pass,
        },
        connectionTimeout: 5000,
    });
```

This send result:
![image](https://user-images.githubusercontent.com/35413734/76423516-e5a7eb00-63e1-11ea-95c0-126f83923a14.png)

They are all from the same mailbox. The results are different.
Is there any good solution！

**Comment by andris9** [comment]
There might be two issues:

* If you are trying to send an email from a different email address than the account owner address, then Gmail overrides it
* If Gmail UI is showing different values than the ones you used then Gmail might be using some older value it has seen before and thinks is more correct

In either cases there's nothing Nodemailer can help.
