### ISSUE TITLE
Nodemailer is not respecting rateDelta and rateLimit

### ISSUE THREAD

**Issue by RecoX** [nodemailer/nodemailer#1120]
Here you can go to the original topic:
https://stackoverflow.com/questions/60926579/nodemailer-is-not-respecting-ratedelta-and-ratelimit

**Comment by andris9** [comment]
`rateLimit` and `rateDelta` are [deprecated options](https://nodemailer.com/smtp/pooled/#deprecated-options) and any bugs related to these will not be fixed.

**Comment by blankstar85** [comment]
@andris9  Do you know why this was deprecated?

**Comment by sriram-kailasam** [comment]
Can someone please suggest an alternative method now that `rateLimit` and `rateDelta` are deprecated?

**Comment by f-w** [comment]
I use Bottleneck with [clustering](https://github.com/SGrondin/bottleneck#clustering) to enforce rate limit across entire cluster, which Nodemailer's rateLimit cannot achieve.
