### ISSUE TITLE
SMTP not sending mail

### ISSUE THREAD

**Issue by junedlanja** [nodemailer/nodemailer#1125]
Here is my transporter config.

```
const transporter = nodemailer.createTransport({
      host: 'mail.rapiddatalabs.com',
      port: 465,
      secure: true,
      auth: {
        user: '*****',
        pass: '****'
      }
    });
```

 I have SMTP sever. I have tested is with online tool https://www.gmass.co/smtp-test and I'm receiving the email means server is working fine.

But mail is not sent using nodemailer, I'm not getting any error but main is not received (also checking in spam). Am i missing something ?

Verify is also firing success callback but email is not received. 

```
transporter.verify(function(error, success) {
  if (error) {
    console.log(error);
  } else {
    console.log("Server is ready to take our messages");
  }
}); 
```

**Comment by ericgoe** [comment]
Do you invoke `transporter.sendMail()` ? This could be the missing part

**Comment by andris9** [comment]
Routing issues are out of scope for Nodemailer. Nodemailer passes the email to next hop via `sendMail` and that's it. What happens afterwards is not related to Nodemailer.
