### ISSUE TITLE
Email sends locally, but not remotely

### ISSUE THREAD

**Issue by edersonfaccin** [nodemailer/nodemailer#1127]
I'm using nodemailer to send e-mails, my e-mail is from GoDaddy, on my local machine, the e-mail works perfectly, but on AWS it doesn't work, on my machine on AWS it's released all right on firewal and inbound rules.

**Tests I've done.**

**I disabled firewal
I released all traffic in the inbound rules and outbound rules**

Both to no avail.

**I'm using the latest version of nodemailer**

Any solution?

**Comment by melotek** [comment]
I have the similar problem. edersonfaccin maybe You found solution?

**Comment by edersonfaccin** [comment]
Hello, i don't found a soluction to this issue, but i changed of the component. Now i started using the emailjs

npm i emailjs

**Comment by mobilfid** [comment]
I am having the same issue here. From a locally running project, I can send emails (from localhost) to anywhere and they are received by the recipient immediately. Recipients are gmail/yahoo/hotmail etc. --  but when I deploy to a remote server, mails: 

1) either never get received by the recipient 
2) arrive after several minutes or hours 
3) or randomly, sometimes arrive immediately.

I have been searching for a while now, and seems like there are lots of issues with "mails are sent on localhost but not server" and all without a solution. I am not using AWS, so I doubt it's an AWS issue.

All emails return
`accepted: [ 'mail@mail.com' ],
  rejected: [],
  response: '250 OK id=someShortId',
  envelope:
   { from: 'some-email@email.com',
     to: [ mail@mail.com' ] },
  messageId: 'someLongId@mail.com' }`

**Comment by melotek** [comment]
the solution in my case was just remove domain from ajax request in form, for example
`  axios({
      method: "post",
      url: "/api/order",
      headers: { "content-type": "application/json" },
      data: {... },
    })`

**Comment by andris9** [comment]
Routing issues are out of scope for Nodemailer. Nodemailer passes the email to next hop via `sendMail` and that's it. What happens afterwards is not related to Nodemailer.
