### ISSUE TITLE
Not all emails are getting send

### ISSUE THREAD

**Issue by adityay-perpetualny** [nodemailer/nodemailer#1133]
For some of the emails, I am getting below error message,

Error while sending email Error: Data command failed: 421 4.3.0 Temporary System Problem.  Try again later (10). c124sm10820896qke.13 - gsmtp.

Can anybody help me with this.

Thanks

**Comment by andris9** [comment]
Interesting error response but not related to Nodemailer. If email fails to send try again after a while.

**Comment by adityay-perpetualny** [comment]
Yes. You are right , the issue was with Gmail. Now I am using Nodemailer with AWS SES.
