### ISSUE TITLE
Nodemailer v6.4.6 fails with: 'The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Promise'

### ISSUE THREAD

**Issue by calebpitan** [nodemailer/nodemailer#1134]
1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I'm using nodemailer with netlify functions to send confirmation emails. Every time the function is triggered this error appears from node mailer; here:
```
Failed to send mail TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Promise
    at validChunk (_stream_writable.js:280:10)
    at PassThrough.Writable.write (_stream_writable.js:315:21)
    at PassThrough.Writable.end (_stream_writable.js:624:10)
    at Immediate._onImmediate (/var/task/src/node_modules/nodemailer/lib/mime-node/index.js:969:46)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ESTREAM',
  command: 'API'
}
```

**Comment by calebpitan** [comment]
This was actually a problem from me. I was compiling a `.ejs` file with `ejs.renderFile` which actually returns a `Promise`. I then passed the `Promise` to the `html` of `transport.sendMail`'s message object, without resolving the promise. 

What I am saying is: resolving the promise of `ejs.renderFile` and passing the resolved string to the `html` field actually resolved the issue (pun intended).

**Comment by Kritish58** [comment]
In my case ,  was trying to send otp code in Number format, converted it to string to resolve the error
