### ISSUE TITLE
Move advertising to npm funding

### ISSUE THREAD

**Issue by jpike88** [nodemailer/nodemailer#1135]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
My server output since updating node mailer looks like this :

```
joshua@Joshs-MBP server % npm i
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> nodemailer@6.4.6 postinstall /Users/joshua/Projects/aquipa/server/node_modules/nodemailer
> node -e "try{require('./postinstall')}catch(e){}"

=== Nodemailer 6.4.6 ===

Thank you for using Nodemailer for your email sending needs! While Nodemailer
itself is mostly meant to be a SMTP client there are other related projects in
the Nodemailer project as well.

For example:
> IMAP API (  https://imapapi.com  ) is a server application to easily access
IMAP accounts via REST API
> NodemailerApp (  https://nodemailer.com/app/  ) is a cross platform GUI app to
debug emails

added 7 packages from 22 contributors, removed 3 packages and updated 52 packages in 32.347s

9 packages are looking for funding
  run `npm fund` for details
```

I'd rather not have my server logs needlessly spammed, while it's nice to know that info I don't think it's the appropriate place to send this. I like to think that logs for errors and warnings, not for marketing campaigns. Please move it so it appears under 'npm fund' or something

**Comment by andris9** [comment]
emailjs is another alternative to Nodemailer that does not does not output text to console on install: https://github.com/eleith/emailjs

**Comment by jpike88** [comment]
Thanks I’ll switch to that
