### ISSUE TITLE
net::ERROR_CONNECTION_RESET 400 When Trying to Send DataUri Attachment

### ISSUE THREAD

**Issue by RTIMichael** [nodemailer/nodemailer#1136]
I'm trying to send a PDF attachment through nodemailer, but receiving an error while doing so.  I saw that nodemailer had the option to send an attachment with a datauri so I used the jsPDF and html2canvas packages to generate one.  The datauri that is generated creates the PDF just fine, because I can paste it into the URL bar and hit enter and it appears.  The problem is when I try and attach this datauri to send through nodemailer.  Once I try and send that as an attachment I receive this error:  `net::ERROR_CONNECTION_RESET 400 (Bad Request)`.  I can send emails without attachments just fine, and I can also send a blank PDF just fine (which I think is super odd).

Here is the code I'm using to create the PDF attachment:
`
 AcceptContract(){
        let curr = this.state.CurrentContract;
        let stores = this.state.StoresSelected;
        let list = this.state.PDFs;

        if(this.state.CurrentContract <= this.state.TotalContracts){
            if(this.state.CurrentContract != this.state.TotalContracts){
                curr++
            }

            stores[this.state.CurrentContract - 1].ContractStatus = "ACCEPTED"
           this.GeneratePDF(function(result){
                list.push(result);
                this.setState({
                    CurrentContract: curr,
                    StoresSelected: stores,
                    PDFs: list,
                })
           }.bind(this));

        }else if(this.state.CurrentContract == this.state.TotalContracts){
            console.log('render final button')
        }
    }

    GeneratePDF(callback){
        let filename = 'test.pdf'
        let pdf = new jspdf('p', 'mm', 'a4');
        let pdfList = this.state.PDFs;
        let data;

        html2canvas(document.getElementById('inner-container')).then(canvas => {
            data = pdf.addImage(canvas.toDataURL('image/jpeg'), 'JPEG', 0, 0, 211, 298).output('datauri');

            let obj = {
                path: data,
            }

            callback(obj);
        });

    }

    SendRawEmail(){
        let to = 'myeemail@email.com'; // change to accounting email
        let text = 'this is a test'
        let data = this.state.PDFs;
        console.log(data);

        $.get("/sendRaw", { to: to, subject: 'Contract Testing', text: text, data: data }, function (data) { }); 
    }
`

This is where I call the nodemailer API:
`
app.get('/sendRaw', (request, response) => {

    var mailOptions = {
      to: request.query.to,
      bcc: request.query.bcc,
      subject: request.query.subject,
      text: request.query.text,
      attachment: request.query.data
    }

    smtpTransport.sendMail({  //email options
        from: "myemail@email.com", // sender address.  Must be the same as authenticated user if using Gmail.
        to: mailOptions.to, 
        bcc: "myemail@email.com",    // sending to itself
        subject: mailOptions.subject, // subject
        html: mailOptions.text, // body
        attachments: mailOptions.attachment,
      }, function (error, response) {  //callback
        if (error) {
            console.log(error);
        } else {
            console.log("Message sent");
            response.send(200);
        }

        smtpTransport.close();
      });

  })
`

Could it be because the datauri is too large? In this case it's 425kB.  The blank PDF was 2kB, so I'm not sure if this is a size issue or not.  Thanks!

**Comment by andris9** [comment]
Does not seem to be related with Nodemailer, check you application logic and upload limits etc.
