### ISSUE TITLE
User has exceeded its 24-hour sending limit. Messages to 25 recipients out of 25

### ISSUE THREAD

**Issue by iocuydi** [nodemailer/nodemailer#1137]
My email provider has a higher limit, I can still send emails manually through the outlook app. But if I try to send anything with nodemailer I get this error message: 

User me@site.com has exceeded its 24-hour sending limit. Messages to 25 recipients out of 25

**Comment by andris9** [comment]
Not related to Nodemailer. If email fails to send try again after a while.
