### ISSUE TITLE
How to send messages received by SMTPServer ? 

### ISSUE THREAD

**Issue by FredLackeyOfficial** [nodemailer/nodemailer#1138]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x] Yes. Sponsors get priority support
- [ ] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I have had an instance of SMTPServer capturing incoming messages, and writing the stream to disk, for many months now.  I have also saved a JSON.stingify'ed version of the entire object, just in case.  I now need to sort and send those messages to various destinations.  Unfortunately, I cannot find any way to instantiate any of the SmtpTransport or SmtpConnection objects with the contents of those raw messages.  What is the easiest means of reading in each file and sending it to a new destination (similar to what a forwarding service would have done)?

**Comment by andris9** [comment]
If you have a SMTP envelope info (basically from and to addresses) and a raw email source, then you can use Nodemailer to deliver that message. I created a self contained example for sending emails directly to recipients' MX servers that you can [find here](https://gist.github.com/andris9/0d67a1979c9c63b6ecdf678c09db2756).

You can run the example script without any additional configuration or changes, the example script delivers emails to a test account in [Ethereal.email](https://ethereal.email/). You can then use the same approach for your own application.

If you do not want to send emails directly to MX server but your SMTP relay (eg Sendgrid, Mailgun, etc) then change the options for `nodemailer.createTransport(...)` like described [here](https://nodemailer.com/smtp/). Sending emails directly to MX assumes that you have a static IP address that is not in black lists  and also have the port 25 open which some providers close by default.
