### ISSUE TITLE
Is this a bug? Missing credentials for "PLAIN" when using SMTP with password not required.

### ISSUE THREAD

**Issue by travis5491811** [nodemailer/nodemailer#1142]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I don't know if this is a bug or not. I'm using Nodemailer v6.4.6 with G-Suite paid account. One of our hosting companies is sending mail as us (using our domain) using SMTP. All we had to do was follow steps from google set the following in our G-Suite account under SMTP options...

- "Require SMTP Authentication" to No
- "Allowed senders:" Only addresses in my domain
- "Require TLS encryption" Yes
- "Only accept mail from the specified IP addresses:" to Yes
- and then add their IP to the list of allowed addresses.

We didn't have to provide them with any passwords (or any app passwords) or do anything else and they were able to send mail as us and they get delivered to customers inbox (not spam). So i decided to try and use NodeMailer to send mail as us from our office in the same way after adding our IP to G-Suite. 

I confirmed [here](https://support.google.com/a/answer/176600?hl=en) what google's requirements were

> Sending limits | 2,000 messages per day. See: Email sending limits
> -- | --
> Anti-spam filters | Suspicious emails might be filtered or rejected.
> Fully qualified domain name of SMTP service | smtp.gmail.com
> Configuration options | Port 465 (SSL required)Port 587 (TLS required)Dynamic IPs allowedSee: SSL connections overview
> **Authentication requirements** | Your full Gmail or G Suite email address (you@yourdomain.com) is required for authentication.

For authentication requirements it says I only need to provide my g-suite email address. But `nodemailer` throws a format error if i don't provide a password:
`Missing credentials for "PLAIN"`

The following is the base configuration:
```
  const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: 'someuser@mygsuitedomain.com',
      // pass: '',
    },
  });
```

The [oauth2](https://nodemailer.com/smtp/oauth2/) examples are all using SSL and look like they require more setup than I had to do for the hosting company. Obviously they are not using `nodemailer`. How can I send email via SMTP like some hosting companies do and using `nodemailer`? It looks like `nodemailer` may be explicitly blocking anybody from using a auth method that only requires a username (looking at line 440-449 in source `node_modules/nodemailer/lib/smtp-connection/index.js`) is this correct?

**Comment by andris9** [comment]
Set `auth:false` to disable authentication.
