### ISSUE TITLE
Bug in typing of Mail.Options interface

### ISSUE THREAD

**Issue by suyashgulati** [nodemailer/nodemailer#1143]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

There seems to be a bug in Mail.Options type, as it doesnt support auth object to be sent in sendMail function.

<img width="424" alt="Screenshot 2020-05-21 at 4 05 39 AM" src="https://user-images.githubusercontent.com/20201768/82504174-5c671000-9b18-11ea-9245-bd44dd7c227a.png">

But as per this example it says it can:
https://nodemailer.com/smtp/oauth2/#example-5
<img width="607" alt="Screenshot 2020-05-21 at 4 07 23 AM" src="https://user-images.githubusercontent.com/20201768/82504276-96d0ad00-9b18-11ea-9e1f-2815b7530c3a.png">

**Comment by andris9** [comment]
If you are referring to typescript definitions than Nodemailer does not have any official definitions. If something is missing then contact the author of the typings.
