### ISSUE TITLE
Charset not defined for text/plain

### ISSUE THREAD

**Issue by DASPRiD** [nodemailer/nodemailer#1145]
1. What kind of issue are you reporting?
- [X] A bug in Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

In the following line, nodemailer will not append a "charset=utf-8" to the Content-Type header, when the Content-Type is "text/plain":

https://github.com/nodemailer/nodemailer/blob/d277eac87f93445e847e980e8d3e8db6ff8d762e/lib/mail-composer/index.js#L210

This will trigger RSPAMDs `R_MISSING_CHARSET` rule, which has a high chance to flag the message as spam.

https://github.com/rspamd/rspamd/blob/master/rules/regexp/headers.lua#L139-L145

I'm not sure if there is any proper way to force the appending of the charset part through user-land code. Since nodemailer is generally considered a UTF-8 centric library, it might make sense to simply always append the charset, unless that exclusion had any specific reason.

**Comment by andris9** [comment]
Fixed in nodemailer@6.4.7
