### ISSUE TITLE
Postinstall forced timeout

### ISSUE THREAD

**Issue by Luxizzle** [nodemailer/nodemailer#1146]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I'm alright with ads, I get that not everything can be done for free. But I think forcing users to wait 5 seconds while installing is a bit intrusive.

https://github.com/nodemailer/nodemailer/commit/a0cab71272da408afc863b71301a8318d98cf035#diff-551007241ae61889b0f85f47aa764343R77

This was mentioned before (#1135), but the only thing the latest release added was the forced timeout.

**Comment by andris9** [comment]
emailjs is another alternative to Nodemailer that does not output text to console on install: https://github.com/eleith/emailjs
