### ISSUE TITLE
[Question] - Send e-mails with shared email as a sender

### ISSUE THREAD

**Issue by guifm** [nodemailer/nodemailer#1148]
Hi guys

My enterprise area e-mail is shared with my own e-mail (shared mailbox) and I only can get logged on it with my own enterprise email/password.

I am able to send e-mails with my enterprise email as a sender, since I am authenticating with my enterprise credentials, but I can't send e-mail with 
my enterprise area e-mail as a sender using my enterprise credentials to authenticate.

Do you guys know whether it is to possible to set the sender with a shared e-mail. 

Thanks in advance.

**Comment by nimesha95** [comment]
Hi @guifm did you managed to solve this issue?

**Comment by guifm** [comment]
Hi @nimesha95 actually it was about the shared mailbox settings/credentials
