### ISSUE TITLE
Pooled Transport: Closing individual connections

### ISSUE THREAD

**Issue by gavinvangent** [nodemailer/nodemailer#1149]
Hi,

I have a scenario where I'd like to force one connection in a pool to close based on some condition, but I don't want to close all connections in the pool.

I am receiving a `421 SMTP session maximum lifetime has been reached, please reconnect` error from an smtp server. My understanding is that the connection has been open too long, and they are not willing to continue comms over this connection. But I believe the other connections currently in use are still fine to use (until they themselves receive this error).

How can I close a single connection in a transport using pooling?

**Comment by andris9** [comment]
Use a low `socketTimeout` value so the connection is closed automatically if there is no messages to send.

**Comment by gavinvangent** [comment]
The problem is that some smtp servers limit the connection to ie, 10 mins... If we are sending at least 1 email within the `socketTimeout` for the full 10 minute duration, this problem would still persist regardless of how short the `socketTimeout` is. That's really not a solution at all, just a blanket hoping to prevent the problem from showing its face.

On top of that, some smtp servers reject our connections if we connect too frequently. They are promoting longer running connections.

I plead you to reconsider.
