### ISSUE TITLE
Ensure is email delivered or not ?

### ISSUE THREAD

**Issue by vladdius** [nodemailer/nodemailer#1150]
How can we unsure, is email delivered (and that email address is exists or not)?
const message = {
    from: 'from@gmail.com',
    to: 'test22191@yahoo.com',
    subject: 'Message title',
    text: 'Plaintext version of the message',
};

the response always is 
{ accepted: [ 'test22191@yahoo.com' ],
  rejected: [],
  envelopeTime: 427,
  messageTime: 1022,
  messageSize: 603,
  response: '250 2.0.0 OK  1591947479 g3sm1538733lfc.94 - gsmtp',
  envelope: { from: 'from@gmail.com', to: [ 'test22191@yahoo.com' ] },
  messageId: '<a4accb35-cacc-226c-deb4-d36d5c159d8f@gmail.com>' }

but in my email I receive

Your message wasn't delivered to test22191@yahoo.com because the address couldn't be found, or is unable to receive mail.

Please, help !

**Comment by andris9** [comment]
Nodemailer is for transport only. It does not guarantee delivery between different MTA-MX servers.
