### ISSUE TITLE
Feature Request: Pooled connection limits

### ISSUE THREAD

**Issue by gavinvangent** [nodemailer/nodemailer#1151]
## Request

I'm requesting ~two~ one new configurable option~s~ be introduced for pooled transports (you may have better names for ~these two~ this):

~- connectionIdleTimeout: number;~
- connectionTTL: number;

## The Problem

Transports using the `pool: true` option allow for a `maxMessages: number` before the connection is closed and a new one is created. This results in connections being created and terminated proportional to the number of messages you send within a duration of time. In scenarios where only 1 email is being sent per hour (and with the default 100 maxMessages), it would take 100 hours before the connection is closed. (assuming I set the `socketTimeout` to 1 hour + 5 mins)

~### connectionIdleTimeout~

~If the connection is idle for the specified duration, it should be closed.~

### connectionTTL

(aka connection time to live) The connection will be closed after this duration if it is idle, or when next idle.

## The Result

This would allow me to ensure no connection is open for longer than X seconds, and if not used within Y seconds, it will be closed, disposed and resources will be reclaimed until needed, when a new connection can be created.

**Comment by gavinvangent** [comment]
I just discovered `socketTimeout` which does what I wanted `connectionIdleTimeout` to do. Will amend my request

**Comment by andris9** [comment]
Nodemailer is in a frozen state so no plans to add new features.
