### ISSUE TITLE
Using Nodemailer as a Contact Form with file upload

### ISSUE THREAD

**Issue by bernardojb** [nodemailer/nodemailer#1152]
Hey!
I'm using Nodemailer as a contact form for my web-app and i need my users to be able to send uploaded files within the e-mail. 
After spending some time looking for exemples, issues and ways of doing it i was really surprised that i wasn't able to find any useful resource. 

This beeing the closest one of what i was looking for, i tried implementing File System to my project but without any success as well -> https://stackoverflow.com/questions/55470580/select-a-file-and-then-send-it-as-an-attachment-using-nodemailer-nodejs

It is possible to use Nodemailer for this porpouse and there's any issue or resources doing it ?

**Comment by andris9** [comment]
Please report bugs here only.
