### ISSUE TITLE
What is the error when sending email in docker service?

### ISSUE THREAD

**Issue by budarin** [nodemailer/nodemailer#1153]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [X] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I have an account on mail.ru
When I try send an email in IDE - it sends it.

```
const transporter = nodemailer.createTransport({
    host: 'smtp.mail.ru',
    port: 465,
    tls: {
        rejectUnauthorized: false,
    },
    secure: true,
    auth: {
        user: SMTP_USER,
        pass: smtpPassword,
    },
});
```
But when I put my code into docker service - it throws the error:
```
"error": {
    "errno":-3008,
    "code":"EDNS",
    "syscall":"getaddrinfo",
    "hostname":"smtp.mail.ru,",
    "command":"CONN"
}
```
when I attached to the server and run cmd
```
nslookup smtp.mail.ru
```
it resolved the host
```
Server:         127.0.0.11   
Address:        127.0.0.11:53

Non-authoritative answer:    
Name:   smtp.mail.ru
Address: 94.100.180.160      
Name:   smtp.mail.ru
Address: 217.69.139.160      

Non-authoritative answer:    
Name:   smtp.mail.ru
Address: 2a00:1148:db00::8
```

but what is the error about? 
How to solve the problem?

**Comment by budarin** [comment]
I'm sorry - there was my typo in config :(

**Comment by meglio** [comment]
@budarin did you have to expose any port in your Docker container to make it work?
