### ISSUE TITLE
GMail not showing proper preview, with html + text with inline images

### ISSUE THREAD

**Issue by arciisine** [nodemailer/nodemailer#1157]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x] No.

3. State your problem here:
When using `nodemailer`, if you specify `html`, `text`, and `attachment` properties of a message,  they are defined in such a way that the `text` content ends up as the preview in gmail.

[default-email.txt](https://github.com/nodemailer/nodemailer/files/4801942/default-email.txt)

![image](https://user-images.githubusercontent.com/1264175/85085504-0f716a80-b1a6-11ea-90ef-1091d6b36604.png)
Note: the `text` content is in markdown format as is visible in the email preview

By adding attachments for images the content type for the `html` alternative changed from `text/html` to `multipart/related`.  GMail at this point did not seem to recognize this alternative as priority during the preview.

After this I tried to flatten the structure (remove the related nesting) via different means, but the only mechanism I found was setting the `html` alternative content type to ` text/html`, with a leading space.  The `html` body and images were no longer put in a related section, but stored individually.  

[separate-email.txt](https://github.com/nodemailer/nodemailer/files/4801911/separate-email.txt)

Once I did the above, everything is now working appropriately in GMail.  I'm not sure if there is a better way of doing this, but this seems like a potential bug.

**Comment by andris9** [comment]
Nodemailer does not manage email content at all, it only encodes it and transports it. Whatever you provide it as html or plaintext, is used and the receiving end decodes the message and ends up with the same content. So whatever content you use also defines the previews and such.

**Comment by andris9** [comment]
Regarding mime structure

Nodemailer uses

```
multipart/alternative
  - text/plain
  - multipart/related
    - text/html
    - image/png
    - image/png
```

Gmail on the other hand uses
```
multipart/related
  - multipart/alternative
    - text/plain
    - text/html
  - image/png
  - image/png
```

The version Nodemailer uses has been "industry standard" at least for a decade. No idea why Gmail uses different structure. If this is the more general way (eg. other major providers also use this structure) to do things now then it might be considered for Nodemailer as well, otherwise there is no plans to change anything in Nodemailer as Nodemailer is pretty much in a frozen state.
