### ISSUE TITLE
Please expose parseConnectionUrl

### ISSUE THREAD

**Issue by PRR24** [nodemailer/nodemailer#1159]
1. What kind of issue are you reporting?
- [X] Feature request

3. State your problem here:
Please expose parseConnectionUrl() function as part of nodeMailer exports.

Reasoning:
It is very convenient to manage and use different email connection urls like smtps://something.com/ for transport creation. While some of the settings are safe to adjust site by site (like smtp vs smtps, ignoretls, secure etc), some are not (like pool), as it requires different coding pattern.

To avoid such issues it would be great if one could use:
```js
let options = nodeMailer.parseConnectionUrl("smtp://credentials@smtp.somesite.com:25");
options.pool = true;
let transporter = nodeMailer.createTransport(options);
...
```

**Comment by andris9** [comment]
Use it like this:

```
const { parseConnectionUrl } = require('nodemailer/lib/shared');
let options = parseConnectionUrl("smtp://credentials@smtp.somesite.com:25");
options.pool = true;
let transporter = nodeMailer.createTransport(options);
```
