### ISSUE TITLE
setting message options 'replyTo' has no effect

### ISSUE THREAD

**Issue by SvenPatrickMeier** [nodemailer/nodemailer#1161]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I built a simple service that sends Mails with attachments. 
In order to have a different recipient for the Response to the previous sent mail I followed the documentation and tried to set `replyTo` field in my mails `message`-object (see below).

```TypeScript
await this.mailer.sendMail({
	attachments: [
		{
			contentType: "application/pdf",
			filename: "test-file.pdf",
			path: `${basePath}/test-file.pdf`
		}
	],
	from: this.username,
        replyTo: "some.otherMailaddress@domain.com",
	subject: "Test-Subject",
	text: "Test Greeting\n\nThis is some basic content string\n--Best regards",
	to: "some.mailaddress@domain.com"
});
```

Everything works fine, but the `replyTo` field does not have any effect on the mail sent. 
When I want to reply to the mail, the `reply to` field is unset, so I need to manually enter the recipient address which however is undesired.

I opened this Issue because on [StackOverflow](https://stackoverflow.com/q/45846078/10046524) no one answered to this question.

**Comment by andris9** [comment]
Using `replyTo` adds `Reply-To` header to the outbound message. What happens afterwards with that header or does the mail client honour it, is out of control for Nodemailer.
