### ISSUE TITLE
Unable to download the attachment

### ISSUE THREAD

**Issue by RaviAtTTN** [nodemailer/nodemailer#1162]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- A bug in Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I am using these mailOptions for the noemailer mail 
```
let names = pdfFile.split('/');
  let info = await transporter.sendMail({
    from: '"Fred Foo 👻" <foo@example.com>', // sender address
    to: "ravi97garg@gmail.com, baz@example.com", // list of receivers
    subject: "Hello ✔", // Subject line
    text: "Hello world?", // plain text body
    html: "<b>Here is your pdf</b>", // html body
    attachments: [
      {
        filename: names[names.length-1],
        href: pdfFile,
      }
    ]
  });
```
Here pdfFile is a cloudinary url for the pdf file. This file is hosted in cloudinary cloud.
I am unable to download this atttachment from the generated mail. Can you help resolve the issue. It says "Failed - Server Problem"

**Comment by andris9** [comment]
Does not seem to be a bug in Nodemailer but some configuration issue. Verify that your settings are correct and URLs are reachable.
