### ISSUE TITLE
JavaScript module fails to import: import nodemailer from "nodemailer"

### ISSUE THREAD

**Issue by quantuminformation** [nodemailer/nodemailer#1164]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [ x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I am trying to import like so
```js
import nodemailer from "nodemailer"
import mg from "nodemailer-mailgun-transport"

    var nodemailerMailgun = nodemailer.createTransport(mg(auth))
```
but I get
⚠  functions: TypeError: Cannot read property 'createTransport' of undefined

also get same error if I use

const nodemailer = require("nodemailer");

![image](https://user-images.githubusercontent.com/216566/87547011-c3cdb600-c6aa-11ea-9025-e349913693c9.png)

**Comment by arditshala** [comment]
Like this, it should work ...

```
const nodemailer = require('nodemailer') 
const mg = require('nodemailer-mailgun-transport')

const auth = {
  auth: {
    api_key: 'key-1234123412341234',
    domain: 'one of your domain names listed at your https://mailgun.com/app/domains'
  },
  proxy: 'http://user:pass@localhost:8080' // optional proxy, default is false
}

const nodemailerMailgun = nodemailer.createTransport(mg(auth))
```

**Comment by quantuminformation** [comment]
I am doing that, except I don't use require,
![image](https://user-images.githubusercontent.com/216566/87645657-17dda680-c74e-11ea-87d5-c7950f777cdf.png)
If I step in here:

![image](https://user-images.githubusercontent.com/216566/87651042-d7345c00-c752-11ea-8cd5-1799a6a23bb6.png)

**Comment by gavinvangent** [comment]
You could just:

```ts
import { Transporter, createTransport } from 'nodemailer';
import mg from "nodemailer-mailgun-transport";

    const nodemailerMailgun: Transporter = createTransport(mg(auth));
    return nodemailerMailgun.sendMail();
```

**Comment by quantuminformation** [comment]
My above code was working fine when using Google cloud functions but no it's not working when using firebase cloud functions

still get

TypeError: Cannot read property 'createTransport' of undefined at Object.exports.send (/Users/nikos/WebstormProjects/mentorcv/functions/lib/services.js:14:50) 

here is the full code

```js
import { Transporter, createTransport } from "nodemailer"
import mg from "nodemailer-mailgun-transport"

export const send = async (subject, mailBody): Promise<string> => {
    // This is your API key that you retrieve from www.mailgun.com/cp (free up to 10K monthly emails)
    var auth = {
        auth: {
            api_key: process.env.MAILGUN_API_KEY,
            domain: process.env.MAILGUN_DOMAIN,
        },
    }

    const nodemailerMailgun: Transporter = createTransport(mg(auth))

    return new Promise(function (resolve, reject) {
        nodemailerMailgun.sendMail(
            {
                from: "nikos@foo.com",
                to: "nk@foo.com", // An array if you have multiple recipients.
                subject: subject,
                text: mailBody,
            },
            function (err, info) {
                if (err) {
                    console.log("Error: " + err)
                    reject(err)
                } else {
                    resolve(info)
                    console.log("Response: " + info)
                }
            }
        )
    })
}
```

**Comment by gavinvangent** [comment]
The I believe there is something wrong with how the function is invoked.. Does it now fail everytime? or under specific circumstances? ie, only after the first email is sent, or every 5th email fails, etc?

Also, your code could be cleaned up to this:
```ts
import { Transporter, createTransport } from "nodemailer"
import mg from "nodemailer-mailgun-transport"

export const send = (subject, mailBody): Promise<string> => {
    // This is your API key that you retrieve from www.mailgun.com/cp (free up to 10K monthly emails)
    var auth = {
        auth: {
            api_key: process.env.MAILGUN_API_KEY,
            domain: process.env.MAILGUN_DOMAIN,
        },
    }

    const transport: Transporter = createTransport(mg(auth));
    return transporter.sendMail({
            from: "nikos@foo.com",
            to: "nk@foo.com", // An array if you have multiple recipients.
            subject: subject,
            text: mailBody,
        })
       .then(info => {
           console.log("Response: " + info)
           return info;
       }, err => {
           console.log("Error: " + err)
           throw err;
       });
}
```

Notice how .sendMail(...) returns a promise, so there is no need to wrap it in another Promise

**Comment by quantuminformation** [comment]
Same error, function never called.

**Comment by quantuminformation** [comment]
ill try it on production see if it works, might be firebase emulation issue

**Comment by quantuminformation** [comment]
Same error 

![image](https://user-images.githubusercontent.com/216566/87669136-b62d3480-c76d-11ea-832f-49773115e07c.png)

**Comment by quantuminformation** [comment]
Any ideas @grant ?

**Comment by gavinvangent** [comment]
That looks like the result of how you are compiling your typescript ... Are your tsconfig.json settings correct for use with import?

First, lets try using `require()` ... if that works, then you know you need to sort out your `import` related config

**Comment by quantuminformation** [comment]
sorry guys, I made a blunder here, I forgot to run `tsc` and I thought `firebase emulators:start` was doing that for me

**Comment by quantuminformation** [comment]
ok, even with tsc + using require same error

```js
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "strictNullChecks": false,
    "target": "es2017",
    "noImplicitAny": false,
    "noUnusedLocals": false
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

**Comment by quantuminformation** [comment]
also in code I see 
![image](https://user-images.githubusercontent.com/216566/87693868-c0f7c180-c78d-11ea-8180-2680a0c8db67.png)

**Comment by quantuminformation** [comment]
now trying this, same error, require same result

```js
import { Transporter, createTransport } from "nodemailer"
import mg from "nodemailer-mailgun-transport"
import { config } from "dotenv"

const result = config()

if (result.error) {
    throw result.error
}

console.log(result.parsed)

console.log(process.env)

export const send = (subject, mailBody): Promise<string> => {
    // This is your API key that you retrieve from www.mailgun.com/cp (free up to 10K monthly emails)
    var auth = {
        auth: {
            api_key: process.env.MAILGUN_API_KEY,
            domain: process.env.MAILGUN_DOMAIN,
        },
    }

    const transport: Transporter = createTransport(mg(auth))
    return transport
        .sendMail({
            from: "nikos@mv.com",
            to: "nkat@gmail.com", // An array if you have multiple recipients.
            subject: subject,
            text: mailBody,
        })
        .then(
            (info) => {
                console.log("Response: " + info)
                return info
            },
            (err) => {
                console.log("Error: " + err)
                throw err
            }
        )
}
```
ts config should be fine, was working fine without nodemailer with other libs like firebase, whats weird is that in chrome all these vars are defined:

![image](https://user-images.githubusercontent.com/216566/87721363-9ec66980-c7b6-11ea-8d2f-9699f70f3abd.png)

and inspecting:

![image](https://user-images.githubusercontent.com/216566/87721285-7c345080-c7b6-11ea-8c53-d89aa6dc471f.png)
![image](https://user-images.githubusercontent.com/216566/87721297-80f90480-c7b6-11ea-9368-a84ccbda91f0.png)

![image](https://user-images.githubusercontent.com/216566/87721310-87877c00-c7b6-11ea-92f7-bd915b69f8cc.png)

**Comment by quantuminformation** [comment]
sorted  it guys this is what I had to do it to get it to work

```js
import { Transporter, createTransport } from "nodemailer"
import * as mg from "nodemailer-mailgun-transport"
```
