### ISSUE TITLE
Will NodeMailer support AWS SESv2?

### ISSUE THREAD

**Issue by arditshala** [nodemailer/nodemailer#1165]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [X] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I was trying to use AWS SESv2 with NodeMailer to send RAW E-mails, the NodeMailer works for the AWS SES indeed, but not for the SESv2, I guess the difference is that SESv2 does not expose the _sendRawEmail()_ method which NodeMailer uses on the background, but the _RAW_ should be included on the _sendEmail()_ method for SESv2.

Is this something that is going to be supported soon or?

**Comment by andris9** [comment]
Nodemailer is pretty much frozen, so no plans currently to add any new features. If AWS API is no longer compatible with Nodemailer then support for it will be removed from core. There's always the possibility to use external transport module for Nodemailer.
