### ISSUE TITLE
Error: 139755315718016:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332: using port 25 without auth

### ISSUE THREAD

**Issue by hireninnodel** [nodemailer/nodemailer#1172]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [ ] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

Error : When Send Email Using smpt server with port 25 without auth we received below error.

**Error: 139755315718016:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332**

**OS** : Centos 7
**Node Version :** v12.16.2
**NPM Version :** 6.14.4
**nodemailer Version :**  4.6.4

**We use below code in our production server.**

 async sendEmail(toEmail,body,subject) 
    {    
        try 
        {
            var strFromEmailOption = "noreply@test.in";
            var strSMTP_HOST = "smtp.test.in";
            var strSMTP_PORT = "25";
            var strSSMTP_SECURE = "false";
            var strSMTP_AUTH = "false";
           
            nodemailer.createTestAccount((err, account) => 
            {
                
                let transporter = nodemailer.createTransport({
                    host: strSMTP_HOST,
                    port: strSMTP_PORT,
                    secure: strSSMTP_SECURE,
                    secureConnection:strSMTP_AUTH,
                });
               
                let mailOptions = {
                    from: strFromEmailOption, 
                    to: toEmail, 
                    subject: subject,
                    html: body
                };
               
                transporter.sendMail(mailOptions,(error, info) => {
                    if (error) {
                       
                        return console.log(error);
                    }
                    else {
                        console.log('Message sent: %s', info.messageId);
                        console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
                    }
                });
            });
        } catch (ex) {
            return Promise.reject(ex);
        }
    }

**Result :**

**Comment by hireninnodel** [comment]
above code working till 19-Jun-2020.but some how give the "Error: 139755315718016:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:" while sending email.

**Comment by andris9** [comment]
Did you upgrade Node.js in your servers that day?

**Comment by hireninnodel** [comment]
@andris9 Not Yet

**Comment by hireninnodel** [comment]
@andris9 our node api hosted in centos 7 with port 8081.8081 port access via proxy pass.

**Comment by hireninnodel** [comment]
@andris9 me also apply  tls setting but still does't not send any email.so, request to you again look at this issue ASAP.

nodemailer.createTestAccount((err, account) => 
            {
                // create reusable transporter object using the default SMTP transport
                let transporter = nodemailer.createTransport({
                    host: 'smtp.test.in',
                    port: 25,
                    secure: false,
                    secureConnection:false,
		   tls: {
                   rejectUnauthorized: false
                 }
                });
                
                let mailOptions = {
                    from: 'noreply@test.in', // sender address
                    to: 'test@gmail.com', // list of receivers
                    subject: 'Test Email', // Subject line
                    html: 'This is testings Email.' // html body
                };
                //send mail with defined transport object
                transporter.sendMail(mailOptions,(error, info) => {
                    if (error) {
						console.log('Error Occurs'); 
                        return console.log(error);
                    }
                    else {
						console.log('Email sent successfully'); 
                        console.log('Message sent: %s', info.messageId);
                        console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
                    }
                });
            });

**Comment by andris9** [comment]
When opening connections to ports 25 or 587, always use `secure:false` as these are cleartext ports.

If your node version has older TLS/SSL versions disabled by default and your server is some old unpatched relic, force TLS version upgrade by using

```
tls: {
    minVersion: 'TLSv1'
}
```

**Comment by hireninnodel** [comment]
Thanks for quick update.

**Comment by hireninnodel** [comment]
@andris9 still not working in our production server.kindly look this issue again.

**Comment by hireninnodel** [comment]
@andris9 please look at my Apache server conf file setttings

<IfModule mod_ssl.c>

<VirtualHost *:443>
DocumentRoot "/var/www/html/test.in/"
ServerName test.in

Header set Access-Control-Allow-Origin "https://test.in"
Header set Access-Control-Allow-Methods "GET,PUT,POST,DELETE"

ProxyRequests Off
   ProxyPreserveHost On
   ProxyVia Full
   <Proxy *>
      Require all granted
   </Proxy>

   <Location /api>
      ProxyPass http://127.0.0.1:8081
      ProxyPassReverse http://127.0.0.1:8081
   </Location>

<Directory "/var/www/html/test.in/">
	#AllowOverride All
	allow from all
	Options None
	Require all granted
</Directory>

SSLEngine on
SSLProtocol +TLSv1.1 +TLSv1.2

SSLCertificateFile /etc/pki/tls/certs/ServerCertificate.crt
SSLCertificateKeyFile /etc/pki/tls/certs/gujarat_gov_in.key
SSLCACertificateFile /etc/pki/tls/certs/Intermediate.crt
SSLVerifyClient none
</VirtualHost>
</IfModule>
<VirtualHost *:80>
</VirtualHost>

**Comment by hireninnodel** [comment]
@andris9 Please help me for resolve my issue.

**Comment by andris9** [comment]
This has nothing to do with Nodemailer nor email sending. You have to set Nodemailer TLS configuration to allow using old and insecure TLS versions.

**Comment by hireninnodel** [comment]
Me Already set
tls: {
    minVersion: 'TLSv1'
}

but still not send any email look my apache file as well.
