### ISSUE TITLE
Address parser doesn't escape backslash in name

### ISSUE THREAD

**Issue by goraSi** [nodemailer/nodemailer#1173]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [X] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
The email address is incorrectly parsed (i have changed actual value of the sender):

`node -i`

`const addressParser = require('nodemailer/lib/addressparser')`
`addressParser('"Firstname Lastname \(Test\)" test@example.com')[0]`
`{ address: 'test@example.com', name: 'Firstname Lastname (Test\)' }`

Notice the backslash in parsed name.

**Comment by andris9** [comment]
Fixed in v6.4.11

**Comment by goraSi** [comment]
@andris9 thanks for quick fix. My problem is that i'm using [https://github.com/nodemailer/mailparser](url) which has peer dependency of nodemailer v6.4.10. Is it possible to update mailparser package also.
