### ISSUE TITLE
Nodemailer not sending email but is also not logging any error

### ISSUE THREAD

**Issue by zaykhere** [nodemailer/nodemailer#1174]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?

- [ ] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I'm trying to use nodemailer to send email but it's not sending any email and the strange thing is that it's also not logging any error.

Here's the code of my route:

`router.post("/form", async (req, res) => {
  try {
    let { name, email, password } = req.body;
    let user = await User.create({
      name,
      email,
      password,
    });

    if (!user) return res.status(501).send("Something went wrong");
    let token = await user.getSignedToken();
  

    try {
      user.emailToken = await user.verifyEmail();
    } catch (ex) {
      console.log(ex);
    }
    

    try {
      await user.save({ validateBeforeSave: false });
    } catch (ex) {
      console.log(ex);
    }
    
    const options = {
      expires: new Date(
        Date.now() + process.env.JWT_COOKIE_EXPIRE * 24 * 60 * 60 * 1000
      ),
    };

    var smtpTransport = nodemailer.createTransport({
      service: "Gmail",
      auth: {
        user: "myEmail",
        pass: "myPass",
      },
    });
    var mailOptions = {
      from: "myEmail",
      to: req.body.email,
      subject: "Verify Email Token",
      text: `go to the below link\nhttp://localhost:3000/verifyEmail/${emailToken}`,
    };

    smtpTransport.sendMail(mailOptions, function (error, info) {
      if (error) {
        console.log(error);
      } else {
        console.log("Email sent: " + info.response);
      }
    });
    
    res.cookie("token", token, options);
    res.send("Check email for activation");
  } catch (ex) {
    res.send(ex);
  }
});`

So, it's not sending any email and after it, the res.cookie and the res.send line is also not working. But, the server is not logging any error/exceptions. So, what could be the issue? I used nodemailer in another route (with the same gmail account as this one) and it was working. So, what could be the problem that the code here isn't working?

**Comment by xr0master** [comment]
Just try to debug your code.
BTW someday I wrote transport for Gmail, probably it can help you. However it uses oauth2.
https://www.npmjs.com/package/gmail-nodemailer-transport

**Comment by alex-drocks** [comment]
I have this kind of issue while developping with ElectronJS.

What happens is that if the transporter's socketTimeout expires and I have refreshed the html page which triggers the nodemailer sendMail method, nodemailer will reach this debug step: _DEBUG Sending mail using SMTP (pool)/6.4.11[client:6.4.11]_
But it will never return.

Then if I restart the Electron App completely, the sendMail method will work again.
What is wierd is that I dont involve the main Electron process in the way I use it so it should not be related.

This is not very helpful cause I haven't found exactly where to find the problem in my process but atleast can confirm that it MAY happen in some cases that theres no error message and no success message.

**Comment by andris9** [comment]
Probably not caused by Nodemailer but your app.

**Comment by martony38** [comment]
Having the same issue, in my case `sendMail` fails silently if authentication to the smtp server fails. I was able to see the authentication error by setting `logger` and `debug` options to `true`.
