### ISSUE TITLE
Can't generate token. Check your auth options

### ISSUE THREAD

**Issue by saeed-abdul-rahim** [nodemailer/nodemailer#1176]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

### I'm trying to send 2LO mail using gmail in firebase cloud function

Getting Error: `Can't generate token. Check your auth options`
Noticed my exact same problem as posted here in StackOverflow without answer: 
https://stackoverflow.com/questions/62987543/why-am-i-getting-the-error-cant-generate-token-check-your-auth-options-when

**My code:**
`
const mailTransport = createTransport({
  service: 'gmail',
  auth: {
    type: "OAuth2",
    user: gmail, 
    serviceClient: clientId,
    privateKey
  }
});`
`
export async function sendMail(options: {}) {
  try {
    await mailTransport.verify()
    return await mailTransport.sendMail({ from: gmail, ...options })
  } catch (err) {
    throw err
  }
}
`
Tried the documentation as well same result
Followed this tutorial as well: https://medium.com/@imre_7961/nodemailer-with-g-suite-oauth2-4c86049f778a

**Comment by andris9** [comment]
`Can't generate token. Check your auth options` happens when Nodemailer fails to use the provided private key to sign webtoken request.

**Comment by dosomder** [comment]
I have the same issue. Using the following python snippet I verified that the private key is working
```
from google.oauth2 import service_account
import googleapiclient.discovery

SCOPES = ['https://mail.google.com']
SERVICE_ACCOUNT_FILE = 'serviceaccount-key.json'

credentials = service_account.Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES, subject="myaddress@abc.de")
gmail.users().getProfile(userId="myaddress@abc.de").execute()
```

For nodemailer I copy pasted the value of `private_key`.
```
-----BEGIN PRIVATE KEY-----.....\n-----END PRIVATE KEY-----\n
```

@andris9 any idea what's wrong or how to debug this?

**Comment by dosomder** [comment]
I was using the firebase functions config to store the private key. The issue is that the newline characters were interpreted literally. Replacing them with actual newlines fixed the problem and sending mails works.

```
config.nodemailer.service_account.private_key.replace(/\\n/g, "\n");
```

**Comment by brandonwkipp** [comment]
Thank you @dosomder!!!
