### ISSUE TITLE
Nodemailer doesn't follow oauth token provision option

### ISSUE THREAD

**Issue by abir-taheer** [nodemailer/nodemailer#1180]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

In the documentation here: https://nodemailer.com/smtp/oauth2/#example-2 it mentions that if I set a custom function for 'oauth2_provision_cb' nodemailer won't try to generate its own access token. 
> This example requests a new accessToken value from a custom OAuth2 handler. Nodemailer does not attempt to generate the token by itself.

However, when I try to set up my transporter using code very similar to that of the example, my function for 'oauth2_provision_cb' never gets called and nodemailer tries to regenerate the token on its own. My transporter generation code looks like this: 

```javascript
const user = await getOAuthId();
transporter = nodemailer.createTransport(
	{
		host: 'smtp.gmail.com',
		port: 465,
		secure: true,
		auth: {
			type: 'OAuth2',
			user: user.email
		}
	},
	{
		from: `${user.name} <${user.email}>`
	}
);

transporter.set('oauth2_provision_cb', (user, renew, callback) => {
	console.log('getting access token from custom client');

	return callback(null, oAuth2Client.credentials.access_token);
});
```

Now when I try to send an email with the transporter, it never calls the auth token provision function because the `'getting access token from custom client'` string is never logged in the terminal. What does get logged is an error that says: 

> Error: Can't create new access token for user
    at XOAuth2.generateToken (.../node_modules/nodemailer/lib/xoauth2/index.js:184:33)
    at XOAuth2.getToken (.../node_modules/nodemailer/lib/xoauth2/index.js:123:18)
    at SMTPConnection._handleXOauth2Token (.../node_modules/nodemailer/lib/smtp-connection/index.js:1697:27)
    at SMTPConnection.login (.../node_modules/nodemailer/lib/smtp-connection/index.js:540:22)
    at .../node_modules/nodemailer/lib/smtp-transport/index.js:271:32
    at SMTPConnection.<anonymous> (.../node_modules/nodemailer/lib/smtp-connection/index.js:215:17)
    at Object.onceWrapper (events.js:299:28)
    at SMTPConnection.emit (events.js:210:5)
    at SMTPConnection.EventEmitter.emit (domain.js:499:23)
    at SMTPConnection._actionEHLO (.../node_modules/nodemailer/lib/smtp-connection/index.js:1313:14) {
  code: 'EAUTH',
  command: 'AUTH XOAUTH2'
}

**Comment by amitgouda** [comment]
code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. Learn more at\n' +
    '535 5.7.8  https://support.google.com/mail/?p=BadCredentials 70sm3738019pfu.107 - gsmtp',
  responseCode: 535,
  command: 'AUTH XOAUTH2


am getting this error while using google oath2

**Comment by abir-taheer** [comment]
> code: 'EAUTH',
> response: '535-5.7.8 Username and Password not accepted. Learn more at\n' +
> '535 5.7.8 https://support.google.com/mail/?p=BadCredentials 70sm3738019pfu.107 - gsmtp',
> responseCode: 535,
> command: 'AUTH XOAUTH2
> 
> am getting this error while using google oath2

When using oAuth2, you're supposed to pass an access_token or a service account with a private key, not username and password. Your issue is, however, different from the one I originally brought up.

**Comment by ArthurMbraga** [comment]
Maybe that issue will help you 
https://github.com/nodemailer/nodemailer/issues/901

**Comment by abir-taheer** [comment]
> Maybe that issue will help you
> #901

That does seem to work. Thank you, but this is also something I feel should be explicitly mentioned in the documentation.
