### ISSUE TITLE
ETIMEDOUT error occured when authorize OAuth2 of gmail via proxy environment

### ISSUE THREAD

**Issue by Eniwder** [nodemailer/nodemailer#1181]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
ETIMEDOUT error occured when authorize OAuth2 of gmail via proxy environment.
It worked with the following modify but I am looking for a smart solution.
Below is my codes but it may contains typo because I cannot copy&paste from my dev env.

code of minimal
```
const mailer = require('nodemailer');
transporter = mailer.createTransport({
  service: 'gmail',
  proxy: `http://${id}:${pass}@${proxyHost}:${proxyPort}`,
  auth:{
    <myAuthSettings>
  }
});
transporter.sendMail({<myMailSetting>})
```

error
``` 
{ 
  Error: connect ETIMEDOUT 172.217.24.141:443
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
 errno: 'ETIMEDOUT',
 code: 'EAUTH',
 syscall: 'connect',
 address: '172.217.24.141',
 port: 443,
 type: 'FETCH',
 sourceUrl: 'https://accounts.google.com/o/oauth2/token',
 command: 'AUTH XOAUTH2'
}
```
modify at https://github.com/nodemailer/nodemailer/blob/master/lib/fetch/index.js#L126
```
// append start
const tunnel = require('tunnel')
const agent = tunnel.httpsOverHttp({
  proxy: {
    host: proxyHost,
    port: proxyPort,
    proxyAuth: `${id}:${pass}`
  }
})
// append end
let reqOptions = {
    method,
    host: parsed.hostname,
    path: parsed.path,
    port: parsed.port ? parsed.port : parsed.protocol === 'https:' ? 443 : 80,
    headers,
    rejectUnauthorized: false,
    agent: agent // modify here
};
```

env
```
OS: Windows Server 2016 Datacenter
Nodemailer: v6.4.11
```

notes:
I tried the following ideas, but all failed.
* set process.env proxy / http_proxy / https_proxy
* set npm config proxy / http_proxy / https_proxy
* set system env proxy / http_proxy / https_proxy
* set proxy option of Internet ( it also can set from IE option )

**Comment by andris9** [comment]
Nodemailer supports proxies for SMTP connections only. OAuth tokens are fetched directly.
