### ISSUE TITLE
Empty emails

### ISSUE THREAD

**Issue by inoyakaigor** [nodemailer/nodemailer#1182]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
In my project I have this code:
```javascript
process.on('unhandledRejection', (reason, p) => {
    transporter.sendMail({
        from: 'bot@<my domain>',
        to: '<my email>@ya.ru',
        subject: 'Bot is dead: unhandledRejection',
        text: `Бот умер из-за необработанного исключения: ${p}\nreason: ${reason}`
    }, (err, info) => {
        console.log(err, '\n\n=====')
        console.log(info.envelope)
        console.log(info.messageId)
    })
    process.exit(0)
})
```
There I handle rejections and send email with the reason to myself. Emails come to mailbox, but absolutely empty. No email subject or text content.
Inside sendMail method I set console.log and there is result:
```javascript
let mail = new MailMessage(this, data);
console.log(mail)
```
![image](https://user-images.githubusercontent.com/1235286/92251413-7d8c1a80-eed5-11ea-9f07-4b05765c9c4e.png)

```javascript
mail.message = new MailComposer(mail.data).compile();
console.log('\n\nmail message:', mail.message)
```
(also I logged the envelope and sendmail args inside SendmailTransport.send )
![image](https://user-images.githubusercontent.com/1235286/92251622-c6dc6a00-eed5-11ea-894e-493350795280.png)

How to fix it?

**Comment by andris9** [comment]
Your process probably finishes before sendMail
