### ISSUE TITLE
postinstall script is against npms policy but package.json could have a funding field

### ISSUE THREAD

**Issue by fiws** [nodemailer/nodemailer#1183]
It's against [npms policy](https://www.npmjs.com/policies/open-source-terms) to use install scripts that display ads.

> These kinds of commercial content generally aren't acceptable:
> [...] 
>Packages that display ads at runtime, on installation, or at other stages of the software development lifecycle, such as via npm scripts. Packages with code that can be used to display ads are fine. Packages that themselves display ads are not.

I don't mind that much, just informing you. But i do not like that it adds 4+ seconds to every install on my ci.

---

what you can do tho, is put a `funding` section in your package.json: 

https://docs.npmjs.com/configuring-npm/package-json.html#funding

that way npm will tell the user that your package is looking for funding and `npm fund` will also list it.

**Comment by andris9** [comment]
You are free to use any other email sending library if you do not like some aspect of Nodemailer
