### ISSUE TITLE
priority 'high' does not seem to work

### ISSUE THREAD

**Issue by onsightit** [nodemailer/nodemailer#1184]
I'm trying to set email priority to 'high', but it does not show up in gmail as high priority.  Using config:

			var options = {
				priority: 'high',
				from: appEmail,
				to: to,
				cc: (cc ? cc : ""),
				replyTo: appEmailReplyTo,
				subject: subject,
				html: text
			};

**Comment by andris9** [comment]
I don't that Gmail supports this feature.
