### ISSUE TITLE
IcalEvent sends two files

### ISSUE THREAD

**Issue by RicardoDolNL** [nodemailer/nodemailer#1185]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
While adding icalEvent content created by ical-generator works. I do get two ical files instead of one in my mail. One called invite.ics and the other mail-attachment.
I just want to receive one ical file, what am i doing wrong here?

**Comment by andris9** [comment]
This is intentional. Different calendar apps expect the event to be in different format.

**Comment by RicardoDolNL** [comment]
I highly doubt that. When using your native calendar app on pc/mobile to create and invite an event or even your browser calendar (from let's say outlook) it does not send two attachments in one mail. It's also confusing for the receiver.
