### ISSUE TITLE
Connect function crashes the process when ENOTFOUND is received

### ISSUE THREAD

**Issue by kevinmerckx** [nodemailer/nodemailer#1186]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I'm using the connect function to test SMTP credentials before saving them in my DB. When I try to connect with wrong credentials (like a wrong host), it crashes the Node process, no matter all the `try - catch` I've put around.

This is the logged error:

```
[0] Error: getaddrinfo ENOTFOUND a.dummy.host.here
[0]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
[0] Emitted 'error' event on SMTPConnection instance at:
[0]     at SMTPConnection._onError (/home/kmpeach/dev/keyleads/services/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)
[0]     at Immediate.<anonymous> (/home/kmpeach/dev/keyleads/services/node_modules/nodemailer/lib/smtp-connection/index.js:301:52)
[0]     at processImmediate (internal/timers.js:456:21)
[0]     at process.topLevelDomainCallback (domain.js:137:15) {
[0]   errno: 'ENOTFOUND',
[0]   code: 'EDNS',
[0]   syscall: 'getaddrinfo',
[0]   hostname: 'booteeeeas.uberspace.de',
[0]   command: 'CONN'
[0] }
```

**Comment by andris9** [comment]
When using try..catch then make sure to use await. Orherwise make sure to use a callback function.

**Comment by kevinmerckx** [comment]
@andris9 I did put try catch and also tried the callback way. Here is the code we have.

```
private async testSmtpConnection(
    newSmtpTransportConfig: KeyleadsSignupApiSMTPConfig,
  ) {
    let connection: SMTPConnection;
    try {
      connection = new SMTPConnection(newSmtpTransportConfig);
      await promisify(
        connection.connect.bind(connection)
      )();
      this.logger.log('SMTP Connection test: Connected.');
      await promisify(
        connection.login.bind(connection)
      )(newSmtpTransportConfig.auth);
      this.logger.log('SMTP Connection test: Authenticated');
      connection.close();
      return {
        success: true,
      };
    } catch (error) {
      this.logger.log('SMTP Connection test: error', error);
      if (connection) {
        connection.close();
      }
      return {
        success: false,
        error: error.message,
      };
    }
  }
```

We also tried without `promisify`. Our current workaround is to use the SMTPTransport object and actually send an email to test the connection. It fails when calling `connect` and really seems to kill the process. 

When using the SMTPTransport.sendMail method, it fails nicely.

**Comment by andris9** [comment]
If you are using SMTPConnection directly then you need to catch error events from it

```
connection.on('error', err=>{do_something()})
```

otherwise you end up with unhandled exceptions.

**Comment by kevinmerckx** [comment]
Isn't that a bit tedious to have to write two callbacks to handle errors? Wouldn't it be better to simply throw the exception in such a case?
