### ISSUE TITLE
Domains in hosts file are not resolved correctly

### ISSUE THREAD

**Issue by louislebrault** [nodemailer/nodemailer#1187]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

Hello. 

I'm trying to reach a SMTP server from inside a VPN. To do so, i added an entry in the /etc/hosts file of my docker container.
If i ping the smtp domain, the right adress is resolved.
If use nodejs dns.lookup on the smtp domain, the right adress is resolved.

If i use this domain with nodemailer, the right adress is not resolved :

![issue-img-final](https://user-images.githubusercontent.com/28545906/93603716-ae377e00-f9c4-11ea-99bc-532798bfd011.png)

I can make it work by setting the IP adress as host and filling tls.servername with the hostname, but the ip adress is subject to change and i would like to avoid this option.

Any clue about why the domain is not resolved correctly by nodemailer ?

**Comment by andris9** [comment]
See the [manual](https://nodemailer.com/smtp/)

> Hostnames for the **host** field are resolved using `dns.resolve()`. If you are using a non-resolvable hostname (eg. something listed in */etc/hosts* or you are using different resolver for you Node apps) then provide the IP address of the SMTP server as **host** and for the actual hostname user **tls.servername** parameter. This way no hostname resolving is attempted but TLS validation still works.

**Comment by rightaway** [comment]
@andris9 Was it using a different method of resolution about a year ago? I don't provide a value for `host` in the connection options so it uses the default of `localhost`, but I'm getting an error `queryA EREFUSED localhost`. Surely the default value should still work? Do you have any idea why it started giving this error only recently?
