### ISSUE TITLE
Headers case is changed

### ISSUE THREAD

**Issue by armando25723** [nodemailer/nodemailer#1188]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

Short description:

What I have:

const nodemailer = require("nodemailer");
const transporter = nodemailer.createTransport({
    SES: ses
});    

const mailOptions = {
    from: `"${message.fromName}" <${addresses.from}>`,
    subject: message.subject,
    html: html,
    ...        
    textEncoding: "quoted-printable",
    encoding: "utf-8", 
    headers: {
        'X-MailType': message.name,
        'X-Mail-RequestUuid': message.requestUuid            
    }
}

transporter.sendMail(mailOptions);

When the email arrives to the inbox:

X-Mailtype: Test
X-Mail-Requestuuid: xxxxxxx-x-x-xx-x-x-x--x-x-x

Expected:

X-MailType: Test
X-Mail-RequestUuid: xxxxxxx-x-x-xx-x-x-x--x-x-x

It is changing the case of the headers keys.

**Comment by armando25723** [comment]
I have found this param in createTransport: 

```
        // use a normalizer method for header keys
        normalizeHeaderKey: key => key.toUpperCase()
```
I added to my code:

```
const transporter = nodemailer.createTransport({
    SES: ses,
    normalizeHeaderKey: key => key
});
```
Trying to override some default behavior but got the same result in case missmatch:
What I have set configure: X-MailType
What I get in mail: X-Mailtype

Some advice?

**Comment by armando25723** [comment]
This is the only and less cool solution a found:

```
const transporter = nodemailer.createTransport({
    SES: ses,
    normalizeHeaderKey: (key) => {
        if(key === 'X-Mailtype'){
            return 'X-MailType';
        }else if(key === 'X-Mail-Requestuuid'){
            return 'X-Mail-RequestUuid';
        }else{
            return key;
        }
    }
});
```
:/

**Comment by andris9** [comment]
Using `normalizeHeaderKey` method is the correct way for handling this.

**Comment by armando25723** [comment]
But the header transformation is working for me only when sending attachments.
This is my example code:
```
 const transporter = nodemailer.createTransport({
        SES: ses,
        normalizeHeaderKey: (key) => {
            return key.toLocaleLowerCase();            
        }
    });
```

Now when I send a message with attachments:

```
content-type: multipart/mixed; boundary="--_NmP-e7e97aa56012ee8a-Part_1"
x-mailtype: Test
x-mail-requestuuid:xxxxxxxxx-xxxxxx-xxxxx-xx
```

message without attachments:

```
Content-Type: text/html; charset=utf-8
X-Mailtype: Test
X-Mail-Requestuuid: xxxxxxxxx-xxxxxx-xxxxx-xx
```

The normalizeHeaderKey method is not working without attachments, guess is the multipart/mixed part.

Why is that? is that correct? 

Only thing I need is to have "X-MailType" header in that case exactly, NOT "X-Mailtype" or the like.

Is it doable?
