### ISSUE TITLE
attachment works with a .txt file but not a .pdf or .png

### ISSUE THREAD

**Issue by theskillwithin** [nodemailer/nodemailer#1189]
https://gist.github.com/theskillwithin/b7758463beb7896055d3c0cf6370396a 

when sending a .txt file from formData send from frontend form attachment works no problem.

However when sending an image or pdf the file sends, but does not work when opened. and the file size is different than the file uploaded

Thank you

**Comment by andris9** [comment]
Try to come up with a minimal and reproducible example. Currently there is no way of telling where the issue might be. Make sure that the encoding value you use is correct (and if it is even needed)
