### ISSUE TITLE
How to send a bulk, personalized and dynamic emails like newsLetter

### ISSUE THREAD

**Issue by hayanisaid** [nodemailer/nodemailer#1190]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?

- [ ] Looking for help to resolve some kind of problem with Nodemailer

3. State your problem here:
I want to send my newsLetter that has thousands of emails, and I want to customize each emails. I'm looking for best  way to make each email dynamic and personalized. currently this is the method I'm using, but I think this method is not performant when trying sending a newsletter that has thousands of emails.

```js
async function asyncForEach(array, callback) {
  for (let index = 0; index < array.length; index++) {
      await callback(array[index], index, array)
  }
}


const transporter= nodemailer.createTransporter({
  host: "host.smtp.com",
  port: 587,
  secure: false, // true for 465, false for other ports
  maxMessages: 'infinity',
  pool: true,
  auth: {
      user: "USER_NAME", // generated ethereal user
      pass: "PASSWORD" // generated ethereal password
      //user: process.env.AWS_SMTP_USER_NAME, // generated ethereal user
      // pass: process.env.AWS_SMTP_USER_PASSWORD // generated ethereal password
  }
})

const list =[{
  email:"jhon@mail.com",
  name:"jhon"
},
{
  email:"tim@mail.com",
  name:"tim"
}] // imagine this list contains thousands 
await asyncForEach(list, async (item, index) => {
   const htmlTemplate=`
     <html>
       Hi,{item.username}
       </html>
   `
  const result = await transporter.sendMail({
    from: "from@example.com",
    to: item.email,
    //   bcc: userEmail,
    text:"Hello there",
    html: htmlTemplate,
    subject:"Hello",
    
  })

})
```
## Is looping through a huge Mailing list then call `transporter.sendMail()` safe? like the way I'm doing it above?

-The traditional way to send email to many users

```js
const result = await transporter.sendMail({
    from: "from@example.com",
    to: ["mail@example.com","sara@mail.com"],
    //   bcc: userEmail,
    text:"Hello there",
    html: htmlTemplate,
    subject:"Hello",
    
  })
```

## Please if you have a better suggestion that is elegant and performant  because share cus I'm lost D:

**Comment by andris9** [comment]
You could do this and in general it would work. Things would get difficult if your node process is killed mid-sending as there is no way to track which messages were queued and which were not

**Comment by hayanisaid** [comment]
@andris9 Thanks for confirming and your response.
