### ISSUE TITLE
Error: { library: 'SSL routines', function: 'ssl_choose_client_version', reason: 'unsupported protocol', } 

### ISSUE THREAD

**Issue by MadhabaPatra** [nodemailer/nodemailer#1192]
Exactly @daytonlowell  mentioned,  i got error while i am sending emails from bigrock.in email with providing valid credentials and smtp details, but facing same error, please help me

_Originally posted by @MadhabaPatra in https://github.com/nodemailer/nodemailer/issues/1076#issuecomment-699978863_

**Comment by andris9** [comment]
SSL/TLS errors are dependent on your openssl version in the node exectuable and in your server. Nodemailer uses what is available, it does not do any kind of TLS operations itself.
