### ISSUE TITLE
Console spam issue

### ISSUE THREAD

**Issue by dcharbonnier** [nodemailer/nodemailer#1194]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I'm getting spam on the console :+1: I support projets 
   === Nodemailer 6.4.11 ===
```
Thank you for using Nodemailer for your email sending needs! While
Nodemailer itself is mostly meant to be a SMTP client there are
other related projects in the Nodemailer project as well.

> IMAP API (  https://imapapi.com  ) is a server application to
  easily access IMAP accounts via REST API
> ImapFlow (  https://imapflow.com/  ) is an async IMAP client
  library for Node.js
> NodemailerApp (  https://nodemailer.com/app/  ) is a cross platform
  GUI app to debug emails
> Project Pending (  https://projectpending.com/  ) allows you to
  host DNS of your project domains
> Pending DNS (  https://pendingdns.com/  ) is the DNS server used
  that powers Project Pending
> Ethereal Email (  https://ethereal.email/  ) is an email testing
  service that accepts all your test emails

                      Don't like this message?
             There's a Github Sponsors goal to remove it
                  https://github.com/sponsors/andris9 
                                  
........
```
I financially support projects every month. This one is now in my blacklist, will also find a replacement.

**Comment by andris9** [comment]
You are free to use any libraries you like

**Comment by dcharbonnier** [comment]
indeed, just wanted to give you the feeling of people seing this console spam.
For people looking for a spam free alternative that looks even better : https://github.com/eleith/emailjs
