### ISSUE TITLE
normalizeHeaderKey not working in text/html mails

### ISSUE THREAD

**Issue by armando25723** [nodemailer/nodemailer#1195]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I'm passing the normalizeHeaderKey function in createTransport params to customize the headers keys like this:

 ```
const transporter = nodemailer.createTransport(
        {
            SES: ses,
            normalizeHeaderKey: (key) => {
                if (key.toLowerCase() === 'x-mailtype') {
                    return 'X-MailType';
                } else if (key.toLowerCase() === 'x-mail-requestuuid') {
                    return 'X-Mail-RequestUuid';
                } else {
                    return key;
                }
            }
        }
    );

```
On mails with attachments it is working fine:

```
Content-Type: multipart/mixed; boundary="--_NmP-9a45ecf11ee32877-Part_1"
X-MailType: Mail_Company_Client_Invoice
X-Mail-RequestUuid: 747e2954-98b2-41f0-92cb-bf8f90fcaef7
```

But on mails without attachment it is not working:

```
Content-Type: text/html; charset=utf-8
X-Mailtype: PasswordRemember
X-Mail-Requestuuid: bb35967f-5fd3-42ae-b33f-81f309970bc1
```
Expected: "X-MailType" 
Got: "X-Mailtype"

If I console.log keys inside normalizeHeaderKey in the first case with the attachments, can see the iterations on every header. But on the second case, displays none, like it is actually not executing at all.

**Comment by andris9** [comment]
Fixed in v6.4.13
