### ISSUE TITLE
Send email with original message at the bottom

### ISSUE THREAD

**Issue by giacomobartoli** [nodemailer/nodemailer#1199]
I am using the following snippet of code to send an email that must be seen as a reply message:

   ```
const transporter: Transporter = nodemailer.createTransport({
      service: 'outlook',
      auth: {
        user: config.MAIL.USER,
        pass: config.MAIL.PASSWORD
      }
    });

    const mailOptions: MailOptions = {
      from: config.MAIL.USER,
      to: receiver,
      inReplyTo: messageId,
      references: messageId,
      subject: subject,
      text: textMail
    };
    transporter.sendMail(mailOptions, function (error, info)) etc..

```
When the user receives the email is seen as a response (meaning that it is grouped into a conversation thread).
**However I would like to append automatically the original message sent by the user.
Is there any way to do it just by setting a field before sending the email?**

**Comment by andris9** [comment]
Messages are grouped by heuristics applied by the mail client, so you have to figure out the specifics yourself. In most cases you want to keep the same subject (or prefix it with "Re:") as the original in addition to setting In-Reply-To and References headers.

**Comment by giacomobartoli** [comment]
Hi @andris9 and thank you for your support. However, I think the answer you provided is not exactly what I meant.
I am already setting correctly the subject and the field In-Reply-To and even References in the header. In fact, the email sent through nodemailer is grouped as a thread.
However, **I would like to replicate the behaviour of appending the original message at the bottom of the email sent by nodemailer**.

For instance, if you open your email client and reply to any email you will see that the previous message is added at the bottom of your reply (see the attached screenshot). I would like this to be done automatically by Nodemailer? Is it possible or should be manually implemented?

Thank you again for your help,
G
![Screenshot 2020-10-14 at 09 37 54](https://user-images.githubusercontent.com/2913435/95958629-b20ec280-0e01-11eb-8822-24aeb4b74037.png)

**Comment by andris9** [comment]
This is out of scope for Nodemailer. The referenced message goes into the html property and is managed entirely by user, not Nodemailer.

**Comment by giacomobartoli** [comment]
Ok I get it. So if I need this behaviour it has been implemented manually, right?
Thank you again for your help.

**Comment by andris9** [comment]
yes, there is no standard for the quoted message. usually it is blockquoted though, something like that:

```
<div>new message</div>
<blockquote type="cite">
  <div>info block: On 8. Oct 2020, at 10:15, andris@kreata wrote:</div>
  <div>quoted message</div>
</blockquote>
```
