### ISSUE TITLE
Nodemailer icalEvent sends attachment as two parts

### ISSUE THREAD

**Issue by Ragekage** [nodemailer/nodemailer#1202]
return await transport.sendMail({
    from: process.env.EMAIL_FROM
    to,
    subject,
    html: body,
    cc: cc || [],
    icalEvent: { method: 'request', content: content},
  });

This is my current set up for sending mail, all content is, is a base string using isc format, i am sending it to aws which is then sending it out to the correct recipient but i am getting two isc files one is the correct one, the other is a duplicate with no file name, do you know what would be causing this issue.

**Comment by andris9** [comment]
This is intentional. Ical support is copied over from how Google Calendar sends Ical events. Some clients support one of the attachments, some support the other. Result is a bit weird, I agree but until Google Calendar stops doing the same thing, Nodemailer is also going to send 2 attachments.

**Comment by Ragekage** [comment]
> This is intentional. Ical support is copied over from how Google Calendar sends Ical events. Some clients support one of the attachments, some support the other. Result is a bit weird, I agree but until Google Calendar stops doing the same thing, Nodemailer is also going to send 2 attachments.

Completely understand, thank you for clarifying this for me.
