### ISSUE TITLE
ETIMEDOUT error when upgrading message using STARTTLS

### ISSUE THREAD

**Issue by aneezx** [nodemailer/nodemailer#1203]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
STARTTLS command for enabling TLS encryption is not working which causes ETIMEDOUT error and no email triggering

**Comment by aneezx** [comment]
EHLO 127.0.0.1 is present in logs whereas the apps with microsoft.net send EHLO <servername>. not sure what causes the difference.

**Comment by andris9** [comment]
STARTTLS is handled by the tls library in Node. If it is not compatible with your server (or in most cases with some intermediate like a virus scanner or company firewall intercepting encrypted traffic) then there's not much to do in Nodemailer's side
