### ISSUE TITLE
Email domain is being converted to lowercase and it fails to send.

### ISSUE THREAD

**Issue by PrawiraGenestonlia** [nodemailer/nodemailer#1204]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ x ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [ x ] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
Nodemailer converts email domain to lowercase. For instance, if i send to xx@GMAIL.com it will get converted to xx@gmail.com. Some email domain requires case-sensitivity matching and in this case, nodemailer fails to send.

**Comment by andris9** [comment]
can you provide an example of such domain? domain names are case insensitive

**Comment by PrawiraGenestonlia** [comment]
Hi Andris.

I agree. However, I have come across many onmicrosoft.com domain which is case sensitive, eg. username@SENSITIVE.onmicrosoft.com which failed to be handled by nodemailer.

**Comment by andris9** [comment]
Where does the error happen? Does your SMTP server rejects email attempts from Nodemailer (specifically MAIL FROM or RCPT TO calls) or does your SMTP server accept the message but the recipient's MX server responds with a bounce?

**Comment by PrawiraGenestonlia** [comment]
SMTP server accepts the request but since the email domain is converted to lowercase, MX server responds with a bounce saying that address cannot be found.

**Comment by andris9** [comment]
Well, I guess it can't be helped then. Nodemailer normalises all addresses internally and adding exceptions or making it somehow configurable would be too much work to support a few non-compliant servers.

**Comment by PrawiraGenestonlia** [comment]
Thanks!
