### ISSUE TITLE
"Timeout waiting for client input" when using pooled connection to Microsoft Exchange Server

### ISSUE THREAD

**Issue by markb-trustifi** [nodemailer/nodemailer#1205]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
nodemailer version: 6.4.14
I'm using pooled connection through a proxy server:
```
let smtpClient = nodemailer.createTransport({debug: true,
            pool: true, 
            proxy:"HTTPProxyUrl",
            secure: false, 
            requireTLS: true
});
smtpClient.sendMail(mail, (err, data) => {...});
```

A few minutes after the email has been successfully received the following timeout error is thrown. It doesn't affect the email flow but still is annoying. When the pooling is disabled this error disappears. 

```
debug: 2020-10-25 22:28:35: { component: 'smtp-pool', tnx: 'connection', cid: 1, action: 'available' } Connection #%s became available
debug: 2020-10-25 22:33:36: { component: 'smtp-connection', sid: 'C23z0PyPuw', tnx: 'server' } 451 4.7.0 Timeout waiting for client input [xxx.prod.protection.outlook.com]
error: 2020-10-25 22:33:36: { component: 'smtp-connection', sid: 'C23z0PyPuw' } Unexpected Response: 451 4.7.0 Timeout waiting for client input [xxx.prod.protection.outlook.com]
error: 2020-10-25 22:33:36: { component: 'smtp-pool', err: { Error: Unexpected Response: 451 4.7.0 Timeout waiting for client input [xxx.prod.protection.outlook.com]
       at SMTPConnection._processResponse (/xxx/node_modules/nodemailer/lib/smtp-connection/index.js:945:34)
       at SMTPConnection._onData (/xxx/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
       at TLSSocket.SMTPConnection._onSocketData (/xxx/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
       at TLSSocket.emit (events.js:314:20)
       at TLSSocket.EventEmitter.emit (domain.js:483:12)
       at addChunk (_stream_readable.js:298:12)
       at readableAddChunk (_stream_readable.js:273:9)
       at TLSSocket.Readable.push (_stream_readable.js:214:10)
       at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
       at TLSWrap.callbackTrampoline (internal/async_hooks.js:126:14)
     code: 'EPROTOCOL',
     response: '451 4.7.0 Timeout waiting for client input [xxx.prod.protection.outlook.com]',
     responseCode: 451,
     command: 'CONN' }, tnx: 'pool', cid: 1 } Pool Error for #%s: %s
debug: 2020-10-25 22:33:36: { component: 'smtp-connection', sid: 'C23z0PyPuw', tnx: 'smtp' } Closing connection to the server using "%s"
info: 2020-10-25 22:33:36: { component: 'smtp-pool', tnx: 'connection', cid: 1, action: 'closed' } Connection #%s was closed
info: 2020-10-25 22:33:37: { component: 'smtp-connection', sid: 'C23z0PyPuw', tnx: 'network' } Connection closed
```

**Comment by markb-trustifi** [comment]
I see that this error can be avoided if we execute `smtpClient.close()` after sending an email. In this case we receive:
```
debug: { component: 'smtp-pool', tnx: 'connection', cid: 1, action: 'available' } Connection #%s became available
debug: { component: 'smtp-connection', sid: 'mMzSeYiOj1U', tnx: 'smtp' } Closing connection to the server using "%s"
info: { component: 'smtp-pool', tnx: 'connection', cid: 1, action: 'closed' } Connection #%s was closed
info: { component: 'smtp-pool', tnx: 'connection', cid: 1, action: 'removed' } Connection #%s removed
debug: { component: 'smtp-pool', tnx: 'connection' } All connections removed
```

Is it correct to do in pooling environment?

**Comment by andris9** [comment]
Pooled connections are meant for heavy traffic. If your connections time out then you should probably not use pooling at all.

**Comment by markb-trustifi** [comment]
@andris9 I actually have a heavy traffic. So, this is an official information that this timeout exception should always occur when the smtp connection is idle?

**Comment by andris9** [comment]
Timeout happens when there is no emails to process for some time (pooling keeps connections open so that they could be reused). Pooling is needed when you have to somehow limit active connections otherwise you would exchaust your resources, so instead of sending all emails right now you distribute the load over time by using a limited number of sockets. If your sockets are not used enough and time out then you probably do not need to distribute anything, you can just send out the emails normally.

**Comment by markb-trustifi** [comment]
Thank you for your help! Now I see that the timeout occurs after the 10min of the socket inactivity. I still have another issue with this flow on Heroku cloud. I'm wandering if you can drop a look on it before I open a ticket to Heroku support.
This is the valid timeout exception in local machine after the 10 min:
```
{ component: 'smtp-connection', sid: 'cHH7rJsPKGc' } Timeout
{ component: 'smtp-pool', err: { Error: Timeout
       at SMTPConnection._onTimeout (/app/node_modules/nodemailer/lib/smtp-connection/index.js:847:30)
       at TLSSocket.SMTPConnection._onSocketTimeout (/app/node_modules/nodemailer/lib/smtp-connection/index.js:199:44)
       at TLSSocket.emit (events.js:314:20)
       at TLSSocket.EventEmitter.emit (domain.js:483:12)
       at TLSSocket.Socket._onTimeout (net.js:484:8)
       at listOnTimeout (internal/timers.js:554:17)
       at processTimers (internal/timers.js:497:7)
     code: 'ETIMEDOUT',
     command: 'CONN' }, tnx: 'pool', cid: 1 } Pool Error for #%s: %s
{ component: 'smtp-connection', sid: 'cHH7rJsPKGc', tnx: 'smtp' } Closing connection to the server using "%s"
{ component: 'smtp-pool', tnx: 'connection', cid: 1, action: 'closed' } Connection #%s was closed
```

and this is the exception in the Heroku cloud environment, after the 5min:
```
{ component: 'smtp-pool', err: { Error: Unexpected Response: 451 4.7.0 Timeout waiting for client input [SN1NAM04FT061.eop-NAM04.prod.protection.outlook.com]
        at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:945:34)
        at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
        at TLSSocket.SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
        at TLSSocket.emit (events.js:314:20)
        at TLSSocket.EventEmitter.emit (domain.js:483:12)
        at addChunk (_stream_readable.js:298:12)
        at readableAddChunk (_stream_readable.js:273:9)
        at TLSSocket.Readable.push (_stream_readable.js:214:10)
        at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
      code: 'EPROTOCOL',
      response: '451 4.7.0 Timeout waiting for client input [xxx.prod.protection.outlook.com]',
      responseCode: 451,
      command: 'CONN' }, tnx: 'pool', cid: 2 } Pool Error for #%s: %s
{ component: 'smtp-pool', tnx: 'connection', cid: 2, action: 'closed' } Connection #%s was closed
{ component: 'smtp-connection', sid: 'Wabdmex9scE', tnx: 'network' } Connection closed
```

**Comment by andris9** [comment]
The solution is the same - don't use pooling for your use case.

Use pooling when
* you have a lot of emails to send
* you are using a dedicated email delivery service (sendgrid, mailgun etc), not a user grade service (outlook, gmail etc)

**Comment by markb-trustifi** [comment]
> The solution is the same - don't use pooling for your use case.
> 
> Use pooling when
> 
> * you have a lot of emails to send
> * you are using a dedicated email delivery service (sendgrid, mailgun etc), not a user grade service (outlook, gmail etc)

- we have an enterprise application that sends a lot of emails, but sometimes there is a "window" and then the Nodemailer pool timeouts with an exception.  I think, it should timeout without exception, but it is not critical.
- we send emails to the corporate Exchange Server. I think it is good enough for the Nodemailer pool. There is a chance that the source for the Heroku issue is the Node.js bug. We will test it again when the new Node.js version goes out.
