### ISSUE TITLE
Option to allow alternative text/calendar even when there is an attachment

### ISSUE THREAD

**Issue by jcaron23** [nodemailer/nodemailer#1206]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [X] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

When using the icalEvent option, Nodemailer will usually add the content twice:
* once as `multipart/alternative` to the main content, as `text/calendar`, with the given `method`
* once as an attachment, as `application/ics`

This mimics the way Google Calendar does it, and it works quite well.

However, as soon as there is another "regular" attachment, Nodemailer will stop adding the `alternative` version, and this breaks recognition in at least some versions of Outlook.

A comment at https://github.com/nodemailer/nodemailer/blob/master/lib/mail-composer/index.js#L233 states:

        // only include the calendar alternative if there are no attachments
        // otherwise you might end up in a blank screen on some clients

Is there any record of which clients break in this situation? I can't seem to find a trace of this in commits or issues, even in the old mailcomposer archived repo. Hopefully it might be a client with low market share back then and even lower market share now.

As I have a scenario where most, if not all, users will use a limited set of clients (mostly variants of Outlook), and it seems to work with the alternative + attachment in those, I'd like to submit a PR to add an option to force the alternative version even if attachments are present, would that be be acceptable?

Thanks for all the great work and any insights!

**Comment by andris9** [comment]
I guess there's no reason not to allow mixing attachments with calendar events in this way, in the end it's the responsibility of the sender to make sure their recipients can open these emails or not, not Nodemailer's, so I removed the restriction in v6.4.17.
