### ISSUE TITLE
Office 365(Outlook) can't display correct attachment filename which is composed by mail-composer

### ISSUE THREAD

**Issue by chenxiaoba** [nodemailer/nodemailer#1207]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [X] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I use mail-composer to build mail, if the attachment filename is long utf-8 text, it would generate two different string in content-type filename and content-disposition filename. 

For example, this is my attachment array,
```
 attachments: [
     {
       contentType: 'application/pdf',
       filename: '這是一個長檔名的測試檔案.pdf',
     }
],
```
And it would be composed to this header,
```
Content-Type: application/pdf;
 name="=?UTF-8?B?6YCZ5piv5LiA5YCL6ZW35qqU5ZCN55qE5ris6Kmm?=
 =?UTF-8?B?cGRm5qqU5qGILnBkZg==?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename*0*=utf-8''%E9%80%99%E6%98%AF%E4%B8%80%E5%80%8B;
 filename*1*=%E9%95%B7%E6%AA%94%E5%90%8D%E7%9A%84%E6%B8%AC;
 filename*2*=%E8%A9%A6pdf%E6%AA%94%E6%A1%88.pdf
```
This bug happen in Outlook(Microsoft 365), the filename would be display to incorrect string. It can display correct in gmail , thunderbird, outlook 2010 and outlook 2016.
```
這是一個%E9%95%B7%E6%AA%94%E5%90%8D%E7%9A%84%E6%B8%AC%E8%A9%A6pdf%E6%AA%94%E6%A1%88.pdf
```
And then i use gmail to compose the mail. It can display correct in Outlook.
```
Content-Type: application/pdf; 
	name="=?UTF-8?B?6YCZ5piv5LiA5YCL6ZW35qqU5ZCN55qE5ris6Kmm5qqU5qGILnBkZg==?="
Content-Disposition: attachment; 
	filename="=?UTF-8?B?6YCZ5piv5LiA5YCL6ZW35qqU5ZCN55qE5ris6Kmm5qqU5qGILnBkZg==?="
```
After that i trace the code, and found this code. https://github.com/nodemailer/nodemailer/blob/fca2041bdf33e4a6cb61929abb2503fa4e630219/lib/mime-node/index.js#L526-L532
I try to copy code about filename from content-type to content-disposition.
```
    case 'Content-Disposition':
        structured = mimeFuncs.parseHeaderValue(value);
        value = mimeFuncs.buildHeaderValue(structured);
        
        if (this.filename) {
            // add support for non-compliant clients like QQ webmail
            // we can't build the value with buildHeaderValue as the value is non standard and
            // would be converted to parameter continuation encoding that we do not want
            param = this._encodeWords(this.filename);

            if (param !== this.filename || /[\s'"\\;:/=(),<>@[\]?]|^-/.test(param)) {
                // include value in quotes if needed
                param = '"' + param + '"';
            }
            value += '; filename=' + param;
        }    
    break;
```
It can generate the header what outlook can recognize.
```
Content-Type: application/pdf;
 name="=?UTF-8?B?6YCZ5piv5LiA5YCL6ZW35qqU5ZCN55qE5ris6Kmm?=
 =?UTF-8?B?5qqU5qGILnBkZg==?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="=?UTF-8?B?6YCZ5piv5LiA5YCL6ZW35qqU5ZCN55qE5ris6Kmm?=
 =?UTF-8?B?5qqU5qGILnBkZg==?="
```

**Comment by andris9** [comment]
Can not confirm. Maybe it was a bug that is fixed by now? Maybe your intermediate MTA messes up the filename in transit?

Anyway I tested in various clients and all displayed the filename correctly. Here are screenshots from web outlook (365) and from desktop (latest Outlook for Mac)

<img width="522" alt="Screenshot 2020-12-11 at 11 55 42" src="https://user-images.githubusercontent.com/132242/101890430-5bc3c300-3ba9-11eb-95e0-49dda34fc372.png">

<img width="535" alt="Screenshot 2020-12-11 at 12 04 01" src="https://user-images.githubusercontent.com/132242/101890457-61b9a400-3ba9-11eb-9ce4-ba0006c94981.png">

**Comment by chenxiaoba** [comment]
Could you show the the attachment header from your test mail? Thank you!🙏🙏

**Comment by ShinoYasha** [comment]
@chenxiaoba did you solve this problem?

**Comment by Displee** [comment]
```
          attachments: [{
            filename: `invoice-${invoice.id}.pdf`,
            path: invoiceAttachement,
            contentType: 'application/pdf'
          }]
```
I was generating the PDF server sided and I needed to add the `contentType` attribute manually to get the outlook app to properly show it. That fixed it for me.
