### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bipinstha7** [nodemailer/nodemailer#1209]
I'm having a problem with the [RangeError: Maximum call stack size exceeded] . I am using a pool connection with maxMessages: Infinity and maxConnections: 20. I want to send 1000 message reading from CSV using stream. But within the first attempt, it throws an error. 

```
at /node_modules/nodemailer/lib/mailer/index.js:283:17
at TemplateGenerator.render  (/node_modules/nodemailer-express-handlebars/lib/generator.js:17:32)
at /node_modules/nodemailer-express-handlebars/lib/index.js:9:19
at processPlugins (/node_modules/nodemailer/lib/mailer/index.js:279:13)
```

I'm using await as `await poolTransporter.sendMail(mail)` and the nodemailer version is **6.0.0**

**Comment by andris9** [comment]
This is most probably related to nodemailer-express-handlebars plugin
