### ISSUE TITLE
Cannot create property 'mailer' on string 'direct'?

### ISSUE THREAD

**Issue by ssghost** [nodemailer/nodemailer#1211]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I am trying to publish a Ghost blog website (ghost v3.35.0, the source-code was previously dowloaded in the local folder)  on my local machine (MacOSX 10.15) with the command ``npm start`` (npm v6.14.8) but I've got an error message told me 'Cannot create property 'mailer' on string 'direct'.
<img width="560" alt="Screenshot 2020-11-11 at 22 54 52" src="https://user-images.githubusercontent.com/6882971/99146188-cd931480-26b0-11eb-899c-e9c06de32c84.png">

I searched on Ghost forum, a hint is this error may caused by a wrong version of Nodemailer, which is a dependency of Ghost-app. I searched  package.json, currently version 6.4.14 is installed. and version 0.7.1 is suggested by a staff of Ghost-app. But Nodemailer v0.7.1 is too old to be installed by npm.
<img width="565" alt="Screenshot 2020-11-14 at 19 02 49" src="https://user-images.githubusercontent.com/6882971/99146183-b81dea80-26b0-11eb-91d8-a527104ed938.png">

So what should I do now to overcome this error?

**Comment by andris9** [comment]
Ghost uses a really old version of Nodemailer. Can't help you with that.
