### ISSUE TITLE
nodemailer not importing

### ISSUE THREAD

**Issue by jamborghini** [nodemailer/nodemailer#1216]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I cannot import nodemailer in WebStorm to my NestJS project, tried with `require('nodemailer')` too but that doesn't seem to work too, plus tried in VSCode cause I thought maybe WebStorm cached stuff and something but it does not import neither package itself nor methods/functions.

**Comment by andris9** [comment]
No idea what's wrong. Probably something in your local config.
