### ISSUE TITLE
Getting Error: 24232 error:1408F10B - SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by vince7488** [nodemailer/nodemailer#1217]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [X ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X ] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
The code 

```
const transporter = nodemailer.createTransport(transport)

transporter.verify((error, success) => {
  if (error) {
    console.log("Transport Verification Success: " + success) //false
    console.log(error)
  } else {
    console.log("Transport Verification Success: " + success + " \n Server is ready to take and send messages")
  }
})
```

is outputting this error after running `yarn start` (or npm file.js)
```
[Error: 24232:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}
```

nodemailer version info: 

```
"dependencies": {
    "nodemailer": "^6.4.16",
  }
```
`Operating System: Windows 10 Professional v.20H2 build 19042.685`

Please help, thank you!

**Comment by andris9** [comment]
Everything related to TLS is handled by [Node.js tls library](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options). You can use additional tls options in the Nodemailer config like this if there is some kind of a conflict between the client and the server:

```
const options = {
    host: host,
    port: port,
    logger: true,
    debug: true,
    tls: {
        ca: [ ... ],
        ciphers: '...',
        minVersion: 'TLSv1.1',
        ...
    },
};
```
