### ISSUE TITLE
ssl3_get_record:wrong version number when using Office 365

### ISSUE THREAD

**Issue by kloneman** [nodemailer/nodemailer#1219]
Hello,

I've got a simple web form that uses nodemailer to notify some people when the form has been submitted. It will work for the first few emails sent, but eventually, I will get this error:

```
[Error: 11652:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}
```

This is while using the npm package "node-windows" to run the Node app as a Windows Service on a on-site server, I'm not sure if that makes a difference, it'll work perfectly fine if I run the app from command line.  Below is the code i'm using:

```
var transporter = nodemailer.createTransport({
        host: 'outlook.office365.com',
        port: '587',
        secure: false,
        auth: {
          user: 'username@domain.com',
          pass: 'password'
        },
      });

transporter.sendMail(mailOptions, function(error, info){
        if (error) {
            console.log(error);
        } else {
            console.log('Email sent: ' + info.response);
        }
    }); 
```

**Comment by sc85** [comment]
@kloneman Try setting secure to `true`. Port 587 is usually SSL encrypted, but switched off encryption.

**Comment by kloneman** [comment]
> 
> 
> @kloneman Try setting secure to `true`. Port 587 is usually SSL encrypted, but you disabled encryption.

Thanks for your reply.

I tried setting it to true, but now I get the same error message in both my development environment and production environment.

**Comment by dcermak** [comment]
@kloneman This config works for me (had the same issue as you):
``` typescript
const transport = createTransport({
  host: "smtp.office365.com",
  port: 587,
  requireTLS: true,
  secure: false,
  auth: { user: "user@org.xyz", pass: process.env.EMAIL_PASSWORD }
});
```

**Comment by kloneman** [comment]
> 
> 
> @kloneman This config works for me (had the same issue as you):
> 
> ```ts
> const transport = createTransport({
>   host: "smtp.office365.com",
>   port: 587,
>   requireTLS: true,
>   secure: false,
>   auth: { user: "user@org.xyz", pass: process.env.EMAIL_PASSWORD }
> });
> ```

Thanks dcermak.

I tried adding the requireTLS option as well, but got the same error.

In the end i've just used our on-premise mailserver as the host instead.

Perhaps when we move from a hybrid environment to a fully cloud environment i'll revisit this, i'm thinking maybe our physical firewall may be the culprit here, since it will allow me to telnet to port 587 but not port 25, yet my local machine working from home will allow both those ports.

**Comment by dcermak** [comment]
@kloneman note that the host names are different as well

**Comment by kloneman** [comment]
> 
> 
> @kloneman note that the host names are different as well

@dcermak Yeah don't worry, i've tried both smtp and outlook for the hostnames, still get the same result.

**Comment by andris9** [comment]
This happens when there is a conflict between the enabled openssl options in Node and TLS options offered by server. smtp.office365.com should support all modern ciphers so normally it would work fine. Maybe your node version is using a strange default cipher set, or you are behind some kind of a company firewall or antivirus that actively tries to intercept your SMTP traffic, who knows.

One solution would be to explicitly allow weaker TLS options like this (would not recommend to do this in production):

```
let transporter = nodemailer.createTransport({
    host: 'smtp.office365.com',
    port: 587,
    auth: {
        user: 'user@domain',
        pass: 'password',
    },
    tls: {
        minDHSize: 512,
        minVersion: 'TLSv1',
        maxVersion: 'TLSv1.3',
        ciphers: 'ALL',
    },
    logger: true,
    debug: true, // include SMTP traffic in the logs
});
```

Anyway, whatever the cause, there is not much to do in the Nodemailer side because TLS is not handled by Nodemailer but by Node/OpenSSL.

**Comment by scharf** [comment]
I had to use the following settings:

```js
{
    host: "smtp.office365.com",
    port: 587,
    secure: false,
    ignoreTLS: false,
    auth: {
        user: 'user@domain',
        pass: 'password',
    }
}
```

**Comment by jeyashree-n** [comment]
I am also facing the same issue, If i use secure as false it is working other wise it is showing the error. 


[Error: 8668153344:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ECONNECTION',
  command: 'CONN'
} 

```

**Comment by Abd-Ur-Rehman** [comment]
I'm getting the same error

```js
[Error: 140632260122560:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}
```
Here are my settings and using the localhost SMTP credentials, I tested it with port 587 too but the same error message.

<img width="620" alt="image" src="https://user-images.githubusercontent.com/7280837/191308862-580f8495-bcef-46ee-b7b5-da5675086d06.png">

BTW, I'm using this version. 

<img width="298" alt="image" src="https://user-images.githubusercontent.com/7280837/191309803-0119e179-4e86-44cd-82f2-606836d137a3.png">

**Comment by sanjaymogarkarecc** [comment]
Getting same error. 

> This happens when there is a conflict between the enabled openssl options in Node and TLS options offered by server. smtp.office365.com should support all modern ciphers so normally it would work fine. Maybe your node version is using a strange default cipher set, or you are behind some kind of a company firewall or antivirus that actively tries to intercept your SMTP traffic, who knows.
> 
> One solution would be to explicitly allow weaker TLS options like this (would not recommend to do this in production):
> 
> ```
> let transporter = nodemailer.createTransport({
>     host: 'smtp.office365.com',
>     port: 587,
>     auth: {
>         user: 'user@domain',
>         pass: 'password',
>     },
>     tls: {
>         minDHSize: 512,
>         minVersion: 'TLSv1',
>         maxVersion: 'TLSv1.3',
>         ciphers: 'ALL',
>     },
>     logger: true,
>     debug: true, // include SMTP traffic in the logs
> });
> ```
> 
> Anyway, whatever the cause, there is not much to do in the Nodemailer side because TLS is not handled by Nodemailer but by Node/OpenSSL.

The logger: true and debug: true are really useful in understanding what's going on.

What I see is that, it works when secure: false is set. It's the default so not setting it (as in the above example) gives the same effect. In this mode, the library uses STARTTLS to upgrade the connection. We see
STARTTLS
220 Starting TLS [<some code which might be session id>]
Connection upgraded with STARTTLS

At this point, I reckon, we can safely assume that connection is secure this point onwards. It doesn't say which TLS protocol version it is able to use but I reckon that's a minor concern.

All the same config except with secure: true fails. Not sure why. Is there any way to connect using TLS straightaway without using STARTTLS to upgrade the channel?

**Comment by alex-reusables** [comment]
Maybe it helps someone else, this config worked for me just now when previously I was seeing the error mentioned here:

``` javascript
host: 'smtp.office365.com',
port: 587,
requireTLS: true,
tls: { ciphers: 'SSLv3' }
```
