### ISSUE TITLE
Ethereal Certificate Expired

### ISSUE THREAD

**Issue by pelskamp** [nodemailer/nodemailer#1220]
Nodemailer: v6.4.17

Today I read about using Nodemailer with Ethereal for the first time. When using the given example from the [official website]( https://ethereal.email/) I get this error: `Error occurred. certificate has expired`

By checking the certificate of the website I found out that it actually expired today (20.12.2020).
Could someone please check this and update the certificate?

I know that there is a workaround by using `tls: { rejectUnauthorized: false }` as suggested [here](https://github.com/nodemailer/nodemailer/issues/1006#issuecomment-485720991), but I still think that this error should be fixed soon.

Kind regards

**Comment by AlexanderPuhl** [comment]
I'm getting this as well, just started happening to me today. Using tls: { rejectUnauthorized: false } does work, but that's not ideal and agree that it should be fixed soon if possible.

Thanks.

**Comment by andris9** [comment]
This happened because I recently changed my email address in CloudFlare and the Let's Encrypt certificates are generated via CloudFlare DNS API. Cached user account was invalidated and all API calls to validate the certificate failed.
