### ISSUE TITLE
How to Query Sender's Email Address - OAuth2/GMail

### ISSUE THREAD

**Issue by fwiwDev** [nodemailer/nodemailer#1221]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [X] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here: This is a question. I am able to successfully send messages from GMail using OAuth2 and GMail with Nodemailer so thanks for that. How do I find the email address that the user used in allowing access. I would like to save that in my app so I can show a from address. Right now my "from address" is not in any way connected to what they used... it's just what they *told* me they used.

**Comment by andris9** [comment]
Email address is OAuth2 username.

**Comment by fwiwDev** [comment]
Indeed. Let me clarify. The user completes OAuth using an email address. How do I know what email address they used? Is there any way to query it from nodemailer somehow?
