### ISSUE TITLE
HTML file size got increased at runtime

### ISSUE THREAD

**Issue by ankit-virani** [nodemailer/nodemailer#1222]
The actual size of the HTML file is 2.4 KB. That HTML file contains more than 1000 table rows. I am using S3 mail service to send an email with the mentioned HTML file, but in runtime system sends me an error message stating the file size is bigger than 10 MB. Could you please suggest the necessary steps be taken to eliminate such an error?

Hoping for your prompt response.

**Comment by andris9** [comment]
HTML content is encoded using quoted-printable encoding, so the content is always larger than actual input. Instead of including the table in the email HTML send a link to the table or use a different provider that allows larger emails.
