### ISSUE TITLE
Email is sent from G suite but is not received by the recipient through nodemailer

### ISSUE THREAD

**Issue by DanielGorlo** [nodemailer/nodemailer#1223]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [X] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I'm using Nodemailer to send emails from my customer's Gmail account to multiple email addresses.

Everything works smoothly but then one customer have their emails sent, they exist in the 'sent' folder in their G Suite account, but they never reach the end-user.

When composing the email through the Gmail webapp, the email is sent and received by the recipient.

Here's the code snippet I'm using:
`  const transporter = nodemailer.createTransport({
    service: "gmail",
    name: `${email.split('@')[1]}`,
    auth: {
      type: 'oauth2',
      user: email,
      clientId: clientId,
      clientSecret: clientSecret,
      refreshToken: refreshToken,
      accessToken: accessToken
    },
    tls: {
      rejectUnauthorized: false
    },
    debug: true
  });
`

Any help would be appreciated.

**Comment by andris9** [comment]
Often this is caused by some strange local hostname that is rejected by spam checks. Set a custom `name` (must be FQDN) with the `name` argument https://nodemailer.com/smtp/#connection-options

**Comment by DanielGorlo** [comment]
Thanks @andris9 .

The email did not arrive to the spam folder, but never got to the recipient instead.
