### ISSUE TITLE
Is the direct transport still a thing?

### ISSUE THREAD

**Issue by leafac** [nodemailer/nodemailer#1227]
I found some information about it in old repositories and documentation, but the current website doesn’t mention it. The changelog doesn’t say it’s been removed.

1. Should I use the direct transport?
2. How would I use it?
3. If the direct transport isn’t available anymore, what’s the best alternative?

Thanks for this project! I’ve been using it for a while and it works great!

**Comment by andris9** [comment]
It's still a thing though it is unsupported

```
// $ npm install nodemailer nodemailer-direct-transport
const nodemailer = require('nodemailer');
const directTransport = require('nodemailer-direct-transport');
const transporter = nodemailer.createTransport(directTransport(options))

transporter.sendMail(...)
```

**Comment by leafac** [comment]
Thanks for the response. Did you stop supporting this in favor of any other package/solution? Do you have anything anything you’d recommend?
