### ISSUE TITLE
Attachment Getting Corrupted 

### ISSUE THREAD

**Issue by rahuldate8** [nodemailer/nodemailer#1228]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
While sending an attachments, only plain text files are not corrupted, all the other files are getting corrupted. For PDF, page count is same but the content was missing. 
I am attaching the document from lambda storage. I’ve tried all the variety of codes present under nodemailer attachments(https://nodemailer.com/message/attachments/)

Kindly Help

**Comment by gevhambarzumyan93** [comment]
did you find the solution

**Comment by rahuldate8** [comment]
Hi,

This was not an issue from nodemailer framework.
Issue is resolved. Should I close this issue out?

Thanks for the heads up.

Warm regards,
Rahul Date

**Comment by stewstremel** [comment]
@rahuldate8 - I am having the same issue - I am assuming that it has some combination of the encoding / contentType - what did you do to resolve?
