### ISSUE TITLE
Sending email causes 'Unexpected socket close'

### ISSUE THREAD

**Issue by nicholaslam** [nodemailer/nodemailer#1231]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I'm seeing the same error as the one described in https://github.com/nodemailer/nodemailer/issues/1229. Using the code from the nodemailer documentation causes the 'Unexpected socket close' error. I think the problem is with ethereal email

**Comment by robbelroot** [comment]
I just installed nodemailer and i'm getting the same result with the example from [your site](https://nodemailer.com/smtp/testing/)

**Comment by andris9** [comment]
Ethereal email server is currently under heavy load and some connections might fail. Try again after a while if this happens to you right now, should resolve once there are less users sending mail.
