### ISSUE TITLE
Add support for the AWS SDK v3 SES transport

### ISSUE THREAD

**Issue by dmattia** [nodemailer/nodemailer#1232]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [x] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

The AWS-SDK has an official v3 release now, making use of modular npm dependencies, such as this one for SES: https://www.npmjs.com/package/@aws-sdk/client-ses

One change is that instead of the new AWS clients having methods like `sendRawEmail`, they just have a method `send` that would take in a `SendRawEmailCommand` object. Because of this change, this line https://github.com/nodemailer/nodemailer/blob/master/lib/ses-transport/index.js#L242 would not work if a new SESClient object from the v3 sdk was added in.

While I believe that there is a workaround where you could say:

```javascript
import * as AWS from '@aws-sdk/client-ses';
const ses = new AWS.SES({});
const transporter = nodemailer.createTransport({
  SES: ses,
});
```

this approach relies on using the "v2 compatible style" that is deprecated, and may be removed from the next release of the AWS SDK.

**Comment by Milad** [comment]
I second this request!

**Comment by andris9** [comment]
I don't really know about the internals of the AWS SDK so I would need at least some kind of example of how to use the new approach. There are examples for the old SDK but I was not able to find basically anything about SendRawEmailCommand

**Comment by dmattia** [comment]
Of course, here's an example conversion:

```javascript
this.ses.sendRawEmail(sesMessage, (err, data) => {
  ... do something ...
})
```

would convert to:

```javascript
this.ses.send(new SendRawEmailCommand(sesMessage))
  .then((data) => {
      ...
  })
  .catch((err) => {
      ...
  })
```

The big change is that the v3 sdk will have the `send` command always return a promise, similar to `this.ses.sendRawEmail(sesMessage).promise()` in the v2 sdk

**Comment by andris9** [comment]
Added support to v3 as well in v6.5.0. Usage is slightly different (you need to provide the `aws` object as well), see an [example here](https://github.com/nodemailer/nodemailer/blob/master/examples/ses.js)
