### ISSUE TITLE
Works Locally But Connection Timeouts on Heroku (not using Gmail)

### ISSUE THREAD

**Issue by ianbrant** [nodemailer/nodemailer#1236]
Hi everyone,

I'm new to nodemailer, but I managed to make it work locally.

The problem is that when I try to run on Heroku, I'm getting this error:

Error: Connection timeout
at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
at SMTPConnection._onError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)
at Timeout.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
 
Here is my code :  

```
"use strict";
const nodemailer = require("nodemailer");

module.exports = async function main({email,message}) {

  let transporter = nodemailer.createTransport({
    host: "mail.igprive.com",
    port: 587,
    secure: false, // true for 465, false for other ports,
    auth: {
      user: user, // generated ethereal user
      pass: password// generated ethereal password
    },
    tls: {
        rejectUnauthorized: false
    },
    debug: true
  });

  let info = await transporter.sendMail({
    from: '"Suporte CF Márcia Imperator" <contato@igprive.com>', // sender address
    to: email, // list of receivers
    bcc : bcc_email,
    subject: subject, // Subject line
    html: message, // html body
  });

  console.log("Message sent: %s", info.messageId);
  // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>

  // Preview only available when sending through an Ethereal account
  console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
  // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
}
```

Thanks!

**Comment by mohankoppuravuri** [comment]
We got the same error on production but not on local environment. Our cloud provider Linode by default blocks mailing ports. And in-order to send emails using "SMTP" we had to raise a ticket.

**Comment by andris9** [comment]
The rule of thumb is that if you get connection timeouts, then it's a firewall issue. There could a blocking firewall in any part of the tcp chain (iptables in your vps where the app runs, EC2 firewall in AWS, on your ISP side, on the SMTP server blocking your source addresses etc)

**Comment by rafaellkf** [comment]
I had the same problem, it worked locally and in production it didn't. Using Digital Ocean for production, the solution will release port 587, in the outbound rules. By doing this it worked.
