### ISSUE TITLE
SES throttling causes infinite email sending loop

### ISSUE THREAD

**Issue by RoosterH** [nodemailer/nodemailer#1239]
There is a closed issue that reported the same issue been labeled as "wontfix" https://github.com/nodemailer/nodemailer/issues/972.  If there is no plan to fix it, the whole section of supporting SES throttling in documentation needs to be removed.  https://nodemailer.com/transports/ses/#example-2

It's not fun to send emails infinitely!

**Comment by andris9** [comment]
The documentation example was invalid and caused the loop.
