### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by superVoja** [nodemailer/nodemailer#1245]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [x] Looking for help to resolve some kind of problem with Nodemailer

3. State your problem here:
4. My App is built with Nuxt.js and uses Nodemailer to handle form data to email, the app works as intended on localhost but when I deploy the app on Heroku I get Failed to load resource: the server responded with a status of 404 (Not Found)
5. Here is the Github repo for my app https://github.com/superVoja/accommodation-project

**Comment by raulbarriga** [comment]
Same issue here. I'm also on heroku with next.js, react.js, and express.js. Also works locally but not deployed.
