### ISSUE TITLE
The verify function does not use a proxy for the SMTP transport

### ISSUE THREAD

**Issue by triadium** [nodemailer/nodemailer#1246]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
 I set up proxy for SMTP transport, but the verify function does not use proxy data. 
I fixed the problem by this code:
```typescript
   ...   
   const mailTransport = nodemailer.createTransport({...});
   if (proxy) {
            // The "createTransport" options does not support a proxy field
            mailTransport.setupProxy(proxy);
            mailTransport.set('proxy_socks_module', socks);
            if (typeof mailTransport.getSocket === 'function') {
              mailTransport.transporter.getSocket = mailTransport.getSocket;
              mailTransport.getSocket = false;
            }
            // else { skip }
    }
   // else { noop }
    try {
      await mailTransport.verify();
    }
    catch (err) {
      throw new Error(`Verification failed: ${err.message}`);
    }
  ...
```

**Comment by andris9** [comment]
Using proxies has limited support

**Comment by SteffenLanger** [comment]
In case someone needs this in the future, we solved it by overwriting the transporter's `getSocket()` method with `Mail.getSocket()` before calling `transporter.verify()`. This is not perfect, e.g. because the Socks5 plugin cannot be used, but works for us since we use an HTTP proxy.

Here is an extract from our code base:
```TypeScript
// `meta` is a map which is referenced within `Mail.getSocket()`.
(nodemailerInstance.transporter as any).meta = new Map();
(nodemailerInstance.transporter as any).getSocket = (nodemailerInstance as any).getSocket.bind(
    nodemailerInstance.transporter,
);

nodemailerInstance.transporter.verify((error) => {
    // ...
});

```
