### ISSUE TITLE
The MailComposer is inconsistent with simpleParser

### ISSUE THREAD

**Issue by markb-trustifi** [nodemailer/nodemailer#1249]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [x] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [x] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
The raw mail parsed with `simpleParser` cannot be directly rebuild with `MailComposer` and requires a lot of fixing.

```
const simpleParser = require('mailparser').simpleParser;
const MailComposer = require('nodemailer/lib/mail-composer');
simpleParser(rawmail, (err, mail) => {
   mail.to = mail.to && mail.to.value;
   mail.cc = mail.cc && mail.cc.value;
   mail.bcc = mail.bcc && mail.bcc.value;
   mail.replyTo = mail.replyTo && mail.replyTo.value;
   mail.from = mail.from && mail.from.value && mail.from.value[0];
   //fix attachments...
   //fix headers...

   let composer = new MailComposer(mail);
   composer.compile().build((err, rawmail2) => {
      //rawmail !== rawmail2
   })
})
```

**Comment by andris9** [comment]
These are separate projects and not meant to be compatible.
