### ISSUE TITLE
Mail sending behind proxy

### ISSUE THREAD

**Issue by radum** [nodemailer/nodemailer#125]
Hi guys,

I'm trying to send emails with gmail and what I get is:
{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'co
nnect' }

I bet is because I'm behind a proxy and this is blocking my calls. I've tested the same code outside a proxy and works perfectly. Is there a way I can set nodemailer to use a proxy? Or is there something that I'm missing?

**Comment by mahmed0715** [comment]
I am using smtp, nodemailer says it sent mail, but not delivered to inbox or even spam!!!
what is the solution? Can anyone help me out...
Thanks in advance...

**Comment by leesah** [comment]
Is there a workaround to this? Is there a way of setting up something like a transparent proxy on the server?

**Comment by kauegimenes** [comment]
+1

**Comment by lucasmenezes** [comment]
+1

**Comment by srihari-sridharan** [comment]
+1

**Comment by vagrant1991** [comment]
+1

**Comment by hanishsingh311** [comment]
+1

**Comment by andris9** [comment]
Nodemailer supports HTTP and SOCKS5 proxies. [Docs](https://nodemailer.com/smtp/proxies/).
