### ISSUE TITLE
Receiving messages | A feature request

### ISSUE THREAD

**Issue by abelardolg** [nodemailer/nodemailer#1250]
Hi there,

Rather an issue, this one is a feature request.

I have read that nodemailer is for sending emails but...it doesn't receive them.

Have you planned to build a module to receive messages?

Best regards.

**Comment by AgnisLV** [comment]
@abelardolg  There already is SMTP server module.
https://nodemailer.com/extras/smtp-server/

**Comment by andris9** [comment]
Nodemailer is for sending only.
