### ISSUE TITLE
Different DSN parameters for multiple RCPT TO recipients

### ISSUE THREAD

**Issue by AgnisLV** [nodemailer/nodemailer#1251]
Per RFC3461 each recipient can have its own notify/orcpt parameters.
https://tools.ietf.org/html/rfc3461#section-10.3

At the moment the DSN format in envelope is based around single recipient and in case of multiple recipients, all would get the same notify/orcpt parameters.
https://nodemailer.com/smtp/dsn/
https://github.com/nodemailer/nodemailer/blob/master/lib/smtp-connection/index.js#L1108

**Comment by andris9** [comment]
Nodemailer is pretty much frozen and there is no plans to extend the API. If you want different DSN values, then send emails individually.
