### ISSUE TITLE
S3 images are not being rendered on html body

### ISSUE THREAD

**Issue by williamsidewalk** [nodemailer/nodemailer#1252]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x ] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I'm trying to display an image on my html body, its a .png photo a logo

`https://my-bucket.s3-us-west-2.amazonaws.com/images/logo.png`

When I send my email I use the following

```
transporter.sendMail({
  from: 'from@hotmail.com',
  to: 'to@hotmail.com',
  subject: 'Test',
  // Mustach to render template
  html: render(templates.VERIFY, {
    name: 'name',
    verificationLink: 'http://localhost:5020',
  }),
});
```

Then on my email I see this on my img tag.

`<img data-imagetype="External" data-imageerror="RelWithoutBase" originalsrc="logo_color_2x.png" alt="sidewalk">`

It seems like an overkill, am I doing something wrong? Many thanks

**Comment by andris9** [comment]
Check aht your `render` method is actually doing, this is not caused by Nodemailer.
