### ISSUE TITLE
nodemailer only sent 1 email when list email are same

### ISSUE THREAD

**Issue by GilangNirwana** [nodemailer/nodemailer#1253]
**when list of receiver has a different email address there is no problem**

`transporter.sendMail({
    from: '"asd 👻" <joshg@impacttest.com>', // sender address
    bcc: ["nirwananabil@yahoo.com","gilangyoganirwana@gmail.com"],  // list of receivers
    subject: "hola ", // Subject line
    text: "Hello world?", // plain text body
    html: "<b>Hello world?</b>", // html body
    encoding:"base64",
    
  }).then(p =>{
      console.log(p)
  }).catch(e =>console.log(e))`

**result** 
`{
  accepted: [ 'nirwananabil@yahoo.com', 'gilangyoganirwana@gmail.com' ],
  rejected: [],
  envelopeTime: 1094,
  messageTime: 811,
  messageSize: 642,
  response: '250 2.0.0 Ok: queued as A3051A009A',
  envelope: {
    from: 'joshg@impacttest.com',
    to: [ 'nirwananabil@yahoo.com', 'gilangyoganirwana@gmail.com' ]
  },
  messageId: '<5b2f6436-5f3d-1723-cd72-ece2e01194f3@impacttest.com>'
}`

**but when list of receiver has the same emails, nodemailer only sent 1 emails**

`transporter.sendMail({
    from: '"asd 👻" <joshg@impacttest.com>', // sender address
    bcc: ["nirwananabil@yahoo.com","nirwananabil@yahoo.com"],  // list of receivers
    subject: "jancok kabeh ", // Subject line
    text: "Hello world?", // plain text body
    html: "<b>Hello world?</b>", // html body
    encoding:"base64",
    
  }).then(p =>{
      console.log(p)
  }).catch(e =>console.log(e))`

**result**
`{
  accepted: [ 'nirwananabil@yahoo.com' ],
  rejected: [],
  envelopeTime: 768,
  messageTime: 589,
  messageSize: 602,
  response: '250 2.0.0 Ok: queued as 73E28C0148',
  envelope: { from: 'joshg@impacttest.com', to: [ 'nirwananabil@yahoo.com' ] },
  messageId: '<f99cef7d-4e17-ae57-4e48-80205ff154e5@impacttest.com>'
}`

i dont know why, please help me to solve this problem 
thanks in advance

**Comment by andris9** [comment]
This is what is supposed to happen. Send multiple emails if you want to send to the same address.
