### ISSUE TITLE
Verify throws an error with the SES v3 transport

### ISSUE THREAD

**Issue by emanuelet** [nodemailer/nodemailer#1254]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I'm getting 
```
TypeError: this.ses.sendRawEmail is not a function
    at SESTransport.verify (/var/app/current/node_modules/nodemailer/lib/ses-transport/index.js:319:18)
```

When I try to verify the conneciton before a sending an email with the SES transport.

Looking at the code, is trying to call directly the `this.ses.sendRawEmail` function without the if statement that has been added at line 262 

```
if (typeof ses.send === 'function' && aws.SendRawEmailCommand) {
                        // v3 API
                        sendPromise = ses.send(new aws.SendRawEmailCommand(sesMessage));
                    } else {
                        // v2 API
                        sendPromise = ses.sendRawEmail(sesMessage).promise();
                    }
```

Would it be possible to push a correction? Thanks

**Comment by doomsy** [comment]
I second this issue.

verify(callback) calls this.ses.sendRawEmail().
This does not work when this.ses contains the v3 syntax {ses: ... aws: ...}.

The _send function has the required code:
                let ses = (this.ses.aws ? this.ses.ses : this.ses) || {};
                let aws = this.ses.aws || {};

**Comment by doomsy** [comment]
Thanks!
