### ISSUE TITLE
Subjects with Re: ... get reported as RE

### ISSUE THREAD

**Issue by BobFrankston** [nodemailer/nodemailer#1259]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x ] Yes. Sponsors get priority support
- [ ] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

When I look at the subject field in the parse form, any subject that starts "Re:" is shows as simply "RE".

**Comment by andris9** [comment]
Nodemailer does not modify subject line, it uses whatever you give it to
