### ISSUE TITLE
Append the user's GMail signature to the email

### ISSUE THREAD

**Issue by DanielGorlo** [nodemailer/nodemailer#1260]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [X] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I'm trying to append the user's GMail signature to the email, but then receiver doesn't get it.

Is there a better way of doing that rather than just to append it to the HTML?

**Comment by ognjenjevremovic** [comment]
I am not sure if this is supported by `nodemailer`.
Perhaps we can have someone from the team confirm if this is actually the case?

If so, I would like to contribute to the project and work on this feature (if of course this gets approved as a feature, after some sort of a triage).
I would probably need some guidance, as a first time contributor to the project, from someone from the core team / project maintainers.

I'll be glad to provide PR.
Will keep an open eye on the issue.

**Comment by andris9** [comment]
Signatures and other account related setup does not apply when using SMTP as Nodemailer does. Gmail always delivered the exact HTML provided by Nodemailer and does not perform any modifications and thus signatures are not added.
