### ISSUE TITLE
Can't resolve 'child_process'

### ISSUE THREAD

**Issue by DurandSacha** [nodemailer/nodemailer#1262]
1. What kind of issue are you reporting?
- [* ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ *] Looking for help to resolve some kind of problem with Nodemailer

Hello, I have a problem with nodemailer package. I try to send a email with next.js, and this package have a problem:
Here is my bug : 

`./node_modules/nodemailer/lib/sendmail-transport/index.js:3:0
Module not found: Can't resolve 'child_process'
null`

I import this package like 
`import nodemailer from "nodemailer"`

**Comment by andris9** [comment]
Nodemailer only works in a backend program, you are probably building it as a front-end target.
