### ISSUE TITLE
DKIM body hash is incorrect, when using \r in message html (mail with attachments)

### ISSUE THREAD

**Issue by afanasy** [nodemailer/nodemailer#1267]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

Using DKIM on message with attachments with html containing `\r` will produce invalid body hash.
Same email without `\r` in the html works fine.

```js
var message = {
  from: 'sender@server.com',
  to: 'receiver@sender.com',
  subject: 'Message title',
  html: '\r',
  dkim: {
    domainName: 'domain.com',
    keySelector: 'default',
    privateKey: '...'
  }
}
```

**Comment by andris9** [comment]
Using `\r` is ambiguous and might cause a lot of different issues. Make sure you are using proper newlines.
