### ISSUE TITLE
ETIMEDOUT with 'service: "Godaddy"'

### ISSUE THREAD

**Issue by JeffStodd** [nodemailer/nodemailer#1268]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I am sending emails from a Firebase Cloud Function using Godaddy Office 365. The credentials are correct as I do not get Invalid Login errors, however I am getting Timeout errors. I have managed to successfully send a test email using Gmail, so I am guessing there is not a firewall rule blocking this.

Source code:
```
function notifyPatients(emails) {
    let credentials: 
    {
        user: xxxxxxxxx
        pass: xxxxxxxxx
    }
  
    let mailConfig =
    {    
        pool: true,
        maxMessages: Infinity,
        maxConnections: 5,
        auth: credentials,
    
        service: "Godaddy"
    }
    let transporter = nodemailer.createTransport(mailConfig);
    
    let emailPromises = []
    for (email of emails) {
        emailPromises.push(transporter.sendMail({
            from: mailConfig.auth.user,
            to: email,
            subject: "subject",
            text: "content",
            html: "content",
        }));
    }
    functions.logger.log("Sending emails")
    return Promise.all(emailPromises)
        .then((res) => {
            functions.logger.log("Successfully sent all emails: ")
            functions.logger.log(res)
            return { result: res };
        })
        .catch((err) => {
            functions.logger.log(err)
            return { error: err };
         })
}
```
Error:
```
Error: Connection timeout
    at SMTPConnection._formatError (/workspace/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
    at SMTPConnection._onError (/workspace/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)
    at Timeout._connectionTimeout.setTimeout (/workspace/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) code: 'ETIMEDOUT', command: 'CONN'
```

**Comment by JeffStodd** [comment]
Well I have managed to fix this using the settings:

host: "smtpout.secureserver.net",
secure: false,
port: 587

and omitting 'service: "Godaddy" as well as using my regular password instead of app password.

Not sure why though. Would help if someone could explain why.

**Comment by samrat2825** [comment]
> Well I have managed to fix this using the settings:
> 
> host: "smtpout.secureserver.net", secure: false, port: 587
> 
> and omitting 'service: "Godaddy" as well as using my regular password instead of app password.
> 
> Not sure why though. Would help if someone could explain why.

Hey, I am also trying to use nodemailer+  Godaddy email + firebase cloud functions...and it is working absolutely fine. Just one thing I am not able to fix is, I am getting a "Question Mark" in place of my Godaddy email profile pic. Did you figure out how to do it, I was not able to find anything on the internet.
