### ISSUE TITLE
nodemailer-mailgun-transport, netmask npm package vulnerability

### ISSUE THREAD

**Issue by zhyrin** [nodemailer/nodemailer#1269]
As 'nodemailer-mailgun-transport' github page does not seem very active i am posting this here. 

1. What kind of issue are you reporting?
- A bug in a plugin of nodemailer-mailgun-transport ^2.0.2 (netmask plugin)
- High severity vulnerability

2. State your problem here:
Run "npm audit" or "npm install" with nodemailer-mailgun-transport ^2.0.2
gives me: 
  "netmask npm package vulnerable to octal input data"
  "patched in >=2.0.1"

Netmask is used by up to 300k live projects. Vulnerability reported on about two days ago.

**Comment by andris9** [comment]
`nodemailer-mailgun-transport` is a separate project, I have no privileges in Github or NPM to change anything, you have to ask from the owner of that [repo](https://github.com/orliesaurus/nodemailer-mailgun-transport).
