### ISSUE TITLE
NOT SENDING MAIL WHEN DEPLOY TO AWS SERVER BUT SENDING MAIL ON LOCALHOST SERVER

### ISSUE THREAD

**Issue by coolpinkzz** [nodemailer/nodemailer#1277]
Here is the error while server is up on aws host

**Apr 28 14:01:28 ip-172-31-0-210 web: (node:32125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 112)
Apr 28 14:01:31 ip-172-31-0-210 web: (node:32125) UnhandledPromiseRejectionWarning: Error: Invalid login: 535 5.7.3 Authentication unsuccessful [BL1PR13CA0344.namprd13.prod.outlook.com]
Apr 28 14:01:31 ip-172-31-0-210 web: at SMTPConnection._formatError (/var/app/current/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
Apr 28 14:01:31 ip-172-31-0-210 web: at SMTPConnection._actionAUTHComplete (/var/app/current/node_modules/nodemailer/lib/smtp-connection/index.js:1513:34)
Apr 28 14:01:31 ip-172-31-0-210 web: at SMTPConnection.<anonymous> (/var/app/current/node_modules/nodemailer/lib/smtp-connection/index.js:1471:18)
Apr 28 14:01:31 ip-172-31-0-210 web: at SMTPConnection._processResponse (/var/app/current/node_modules/nodemailer/lib/smtp-connection/index.js:932:20)
Apr 28 14:01:31 ip-172-31-0-210 web: at SMTPConnection._onData (/var/app/current/node_modules/nodemailer/lib/smtp-connection/index.js:739:14)
Apr 28 14:01:31 ip-172-31-0-210 web: at TLSSocket.SMTPConnection._onSocketData (/var/app/current/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
Apr 28 14:01:31 ip-172-31-0-210 web: at TLSSocket.emit (events.js:315:20)**

Here is my app.js
````
const express = require("express");
const app = express();
const nodemailer = require("nodemailer");
var cors = require('cors');

app.use(cors())

app.get("/", async (req, res) => {
    res.status(200).send("message sent");

    const transporter = nodemailer.createTransport({
        host: "smtp-mail.outlook.com", // hostname
        secureConnection: false, // TLS requires secureConnection to be false
        port: 587, // port for secure SMTP
        tls: {
            ciphers: 'SSLv3'
        },
        auth: {

            user: "masterpratikyadav@gmail.com", //
            pass: "XXXXXXXXXXXX"
        }
    });

    // send mail with defined transport object
    let info = await transporter.sendMail({
        from: 'masterpratikyadav@gmail.com ', // sender address
        to: "weassist24@gmail.com", // list of receivers
        subject: "aws-nodemailer", // Subject line
        html: "<b>hy i am from aws</b>", // html body
    });

    console.log("Message sent: %s", info.messageId);
    // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>

    // Preview only available when sending through an Ethereal account
    console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));



});

app.listen(process.env.PORT || 3000, () => {
    console.log("server is up")
})

````

**Comment by Red-CS** [comment]
A common issue is forgetting to add the password environment variable to the CDN (place where you deploy). If it can't find that env variable, it is just passed the value of _undefined_ and the promise will be rejected. You can test this by logging to the console in the deployment environment the value of the password, and see what it outputs. Hope this helps!

**Comment by kmiths19** [comment]
I have the same scenario but in my case there is no error message on the AWS EC2 live server. The same application is working fine on my localhost machine.
