### ISSUE TITLE
SES docs not working

### ISSUE THREAD

**Issue by lorensr** [nodemailer/nodemailer#1278]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer docs

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x] Yes. (via GraphQLGuide org)

3. State your problem here:

The SES documentation first example doesn't work (https://nodemailer.com/transports/ses/), as `aws` is undefined:

```
let aws = require("@aws-sdk/client-ses");
```

Here are the valid exports:

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ses/index.html#import

The old v2 `aws-sdk` package did have a default export. Has nodemailer been updated to support v3? (`@aws-sdk/*`)

**Comment by styxlab** [comment]
You can use the following workaround:
```
import * as aws from '@aws-sdk/client-ses'
```
but I also hope `nodemailer` is going to be updated.
