### ISSUE TITLE
multipart/multilingual example

### ISSUE THREAD

**Issue by timothyjeffcoat** [nodemailer/nodemailer#1279]
Could someone provide an example of how to create a message with content-type multipart/multilingual ?

I tried creating one with 

 alternatives: [
        {
            contentType: 'text/x-web-markdown',
            content: '**Hello world!**'
        }

but I was unsuccessful.

**Comment by andris9** [comment]
RFC822 email is quite strict and non-standard body parts are usually completely ignored by email clients. You can pretty much only use HTML and plaintext. If you want to use markdown then you have to compile it to HTML before sending
