### ISSUE TITLE
Sending multiple emails from AWS Lambda

### ISSUE THREAD

**Issue by kabo** [nodemailer/nodemailer#1281]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I have a nodejs14.x AWS Lambda with the following code
```typescript
import { SES } from 'aws-sdk'
import nodemailer from 'nodemailer'
import { MailOptions } from 'nodemailer/lib/ses-transport'

const
  transporter = nodemailer.createTransport({
    SES: new SES({ apiVersion: '2010-12-01' }),
    sendingRate: 5,
  }),
  sendTheEmails = (params: MailOptions[]) =>
    Promise.all(params.map((param) => {
      console.log(param.text)
      return transporter.sendMail(param)
        .then(console.log)
    }))
      .then(() => console.log('done'))

export const handler = () =>
  makeEmails() // generates 10 emails, returns Promise<MailOptions[]>
    .then(sendTheEmails)
```

If I run this I can see the text of the 10 emails in the logs, but I can only see the returned envelopes for the first 5 emails. The other emails are lost, and the `done` log never happens. There is no error logged or anything like that. The Lambda just exits. I don't understand what's going on, how can a Lambda exit when the Promise.all hasn't returned yet? I read this in the docs:

> If callback argument is not set then the method returns a Promise object. Nodemailer itself does not use Promises internally but it wraps the return into a Promise for convenience.

Is NodeMailer doing something funky that doesn't agree with how Lambdas work somehow?

If I increase the `sendingRate` to 7, I see the returned envelopes for the first 7 emails.

**Comment by kabo** [comment]
This works fine, so there's something wonky with the `sendingRate`.

```typescript
import { SES } from 'aws-sdk'
import nodemailer from 'nodemailer'
import { MailOptions } from 'nodemailer/lib/ses-transport'
import PQueue from 'p-queue'

const
  queue = new PQueue({ concurrency: 5, interval: 1000, carryoverConcurrencyCount: true, intervalCap: 5 }),
  transporter = nodemailer.createTransport({ SES: new SES({ apiVersion: '2010-12-01' }) }),
  sendTheEmails = (params: MailOptions[]) =>
    Promise.all(params.map((param) => {
      console.log(param.text)
      return queue.add(() => transporter.sendMail(param))
        .then(console.log)
    }))
      .then(() => console.log('done'))

export const handler = () =>
  makeEmails() // generates 10 emails, returns Promise<MailOptions[]>
    .then(sendTheEmails)
```

**Comment by andris9** [comment]
The built-in rate limiter has its issues and probably will be removed in some future versions. It is much better to use a dedicated sending queue.

**Comment by Charuru** [comment]
> The built-in rate limiter has its issues and probably will be removed in some future versions. It is much better to use a dedicated sending queue.

Any chance you can explain the issue with the built in rate limiter? I would like it to be usable for me.
