### ISSUE TITLE
nodemailer overrides mail body and send mail with same body to everyone

### ISSUE THREAD

**Issue by MustafaAlvi21** [nodemailer/nodemailer#1284]
Hi, I'm using node and express. I'm building an **multi vender ecommerce website** with express.js and when customer checkout, it send _(thanking)_mail to customer and a order mail to vender_(you have an order)_ but nodemailer sends **same order mail** to vender and customer but I have different **apis** for sending mail to both **(customer and vender)**.
How can I resolve this issue it.

**Comment by andris9** [comment]
Nodemailer sends whatever it is given, it does not handle the contents.
