### ISSUE TITLE
Awaitable socket closure?

### ISSUE THREAD

**Issue by NReilingh** [nodemailer/nodemailer#1285]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [x] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I am using Nodemailer in a context that prefers a clean environment post-execution. I am using an SMTP transport to send a single message, and after the message is sent there is still an open TLS socket. I can call `transporter.close()`, but this returns immediately and is not awaitable, so the only way to "block" until the socket is closed is to do a `setTimeout()`, which is technically a race condition.

If it was possible to access the underlying `<net.Socket>`, I could attach a `'close'` event handler to it, which according to node docs is fired only after the socket is fully closed, but I can't figure out a way to access the socket object if I'm having `nodemailer.createTransport()` create the SMTP transport for me.

Is there a way around this? If not, would this kind of thing be accepted as a PR?

**Comment by andris9** [comment]
If you do not use pooling, then transporter.close() does nothing as Nodemailer automatically closes the socket. For a single message connection pooling is not advised.
