### ISSUE TITLE
Exporting the mail-composer class for external usage

### ISSUE THREAD

**Issue by Proeich** [nodemailer/nodemailer#1286]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [x] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I am using nodemailer in a Project at work and needed only a Mail as an EML string. Your Mail builder class was perfect though it was not publicly reachable from just importing the module. So i propose a solution to use the class from outside:
```diff
diff --git a/lib/nodemailer.js b/lib/nodemailer.js
index 85a7fa4..3e45ec6 100644
--- a/lib/nodemailer.js
+++ b/lib/nodemailer.js
@@ -22,6 +22,8 @@ const ETHEREAL_CACHE = ['true', 'yes', 'y', '1'].includes(

 let testAccount = false;

+module.exports.mailComposer = require('./mail-composer');
+
 module.exports.createTransport = function(transporter, defaults) {
     let urlConfig;
     let options;
```

I would love for that to be in a future release so i can stop patching the file via patch -p1 evertime i update the module.

**Comment by andris9** [comment]
Node allows to use sub-parts from modules like this `const MailComposer = require(“nodemailer/lib/mail-composer”);`
