### ISSUE TITLE
Not Accepting Backslash String on User Auth

### ISSUE THREAD

**Issue by rafapetter** [nodemailer/nodemailer#1287]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [X] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here: 

When passing the options, the user auth is not accepting backslash. 

Already tried passing double backslash, but still nothing. 

Any ideas why? 
`
let options = {
      host: 'smtp.office365.com',
      port: 587,
      secure: false,
      auth: {
        user: "something\something",
        pass: "PASSWORD"
      }
    }`

`let transporter = nodemailer.createTransport(options);`

**Comment by robsonrobi** [comment]
I am having exactly the same problem, any progress ?

**Comment by andris9** [comment]
Backslash in javascript is an escape symbol you can’t use it like this. Use double backslash instead

**Comment by robsonrobi** [comment]
That does not work, then \\ is used in the username.
Try user = "smtp\steve"  => smtpsteve
Try user = "smtp\\steve" => smtp\\steve
