### ISSUE TITLE
With alternative application/xml, not able to force contentDisposition: 'inline'

### ISSUE THREAD

**Issue by cbm-fmuracciole** [nodemailer/nodemailer#1288]
Please fill the following questionnaire about your issue:

What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [x] Looking for help to resolve some kind of problem with Nodemailer

Hi,
Great project, it saves me a lot of time.

I want to put a piece of xml in my multipart email (in the first alternative), with also html and text alternatives.
Even with the contentDisposition: 'inline' in the alt, node mailer turns it always into 'attachment' in the email receive
Here is the code :

```
    var mailOptions = {
        from: fromAddr,
        to: toAddress,
        subject: subject,
        alternatives: [
        {
                contentType: 'application/xml; charset=UTF-8',
                content: '<xml>....</xml>',
                contentDisposition: 'inline',
                headers: {
                   ['Content-Transfer-Encoding']: 'quoted-printable'
                }
            }
           {
                contentType: 'text/plain; charset=UTF-8',
                content: 'This is a plain text',
                headers: {
                   ['Content-Transfer-Encoding']: 'quoted-printable'
                }
            },
            {
                contentType: 'text/html'; charset=UTF-8,
                content: '<html>...</html>',
                headers: {
                   ['Content-Transfer-Encoding']: 'quoted-printable'
                }
            }
        ],
```

With the raw way it works but i can't have the benefits of the 7bit encoding and the fold line (76 chars)

How is it possible to force the inline content disposition of the application/xml part ?
PS: i don't want to use base64 (because of spam systems)

Regards,
Fred.

**Comment by andris9** [comment]
Nodemailer is stronly opinionated how an email should look like. If you want to use anything that is non-standard (by Nodemailer) you can build the mime-node yourself: https://nodemailer.com/message/custom-source/#3-set-string-as-attachment-body
