### ISSUE TITLE
How to send email, with modified "from" field

### ISSUE THREAD

**Issue by Mikaka27** [nodemailer/nodemailer#1290]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I'm looking for a way to send email to myself, but with changed "sender" address.
I can successfully do it using MailKit library for C#, but I need to find a way to do the same thing in nodemailer.
MailKit library from here: https://www.nuget.org/packages/MailKit/

I've changed some important information, ie domain, username etc.

Here is C# source code, which successfully does what I want:
```
using System;
using System.Threading.Tasks;
using MailKit.Net.Smtp;
using MimeKit;

namespace NazwaEmailTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var email = "user@mydomain.com";
            var password = "pass";

            var msg = new MimeMessage();
            msg.From.Add(new MailboxAddress("mikaka27@hotmail.com"));
            msg.To.Add(new MailboxAddress(email));
            msg.Sender = new MailboxAddress(email);
            msg.Subject = "test";
            msg.Body = new TextPart
            {
                Text = "test"
            };

            using (var client = new SmtpClient())
            {
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                await client.ConnectAsync("smtp.mydomain.com");
                await client.AuthenticateAsync(email, password);

                await client.SendAsync(msg);
                await client.DisconnectAsync(true);
            }
        }
    }
}
```

This message arrives as follows:
```
X-Virus-Scanned: by amavisd-new using ClamAV (3)
X-Spam-Flag: NO
X-Spam-Score: 0.688
X-Spam-Level: 
X-Spam-Status: No, score=0.688 tagged_above=-10 tests=[ALL_TRUSTED=-1,
    FORGED_HOTMAIL_RCVD2=1.187, FREEMAIL_FORGED_FROMDOMAIN=0.25,
    FREEMAIL_FROM=0.001, HEADER_FROM_DIFFERENT_DOMAINS=0.25]
    autolearn=disabled
Authentication-Results: avas3.cloud.netart (amavisd-new);
    dkim=pass (2048-bit key) header.d=mydomain.com
Received: from [192.168.0.2] (<MY ISP ADDRESS>)
    by serverXXXXXXX.nazwa.pl (Postfix) with ESMTP id <SOME ID>
    for <user@mydomain.com>; Sun, 23 May 2021 17:47:00 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=mydomain.com;
    s=<SOME NUMBER>.internal; t=<SOME NUMBER>;
    bh=<BASE64 DATA>;
    h=From:Date:Subject:To;
    b=<LONG BASE64 DATA>
From: mikaka27@hotmail.com
Date: Sun, 23 May 2021 17:46:56 +0200
Subject: test
Message-Id: <JDA19QW2TDU4.RH2HXVD88T3A1@stacjonarny>
To: user@mydomain.com
Sender: user@mydomain.com
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8

test
```
The email program correctly displays what I want, ie that it arrived from mikaka27@hotmail.com, even though I sent it from user@mydomain.com

Now I would like to replicate it, using nodemailer, but I've been unsuccessful, here is my attempt:
```
import { createTransport } from 'nodemailer';

async function main() {
    const transport = createTransport({
        host: "smtp.mydomain.com",
        port: 465,
        secure: true,
        auth: {
            user: "user@mydomain.com",
            pass: "pass",
        },
        tls: {
            servername: "nazwa.pl"
        }
    });
    const info = await transport.sendMail({
        from: "mikaka27@hotmail.com",
        to: "user@mydomain.com",
        sender: "user@mydomain.com",
        subject: "test",
        text: "test",
    });
    console.log(info);
};

main().catch(console.log);
```

However this doesn't work, server replies:
```
Error: Can't send mail - all recipients were rejected: 553 5.7.1 <mikaka27@hotmail.com>: Sender address rejected: not owned by user user@mydomain.com
    at SMTPConnection._formatError (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
    at SMTPConnection._actionRCPT (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:1603:28)
    at SMTPConnection.<anonymous> (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:1564:26)
    at SMTPConnection._processResponse (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:932:20)
    at SMTPConnection._onData (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:739:14)
    at TLSSocket.SMTPConnection._onSocketData (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9) {
  code: 'EENVELOPE',
  response: '553 5.7.1 <mikaka27@hotmail.com>: Sender address rejected: not owned by user user@mydomain.com',
  responseCode: 553,
  command: 'RCPT TO',
  rejected: [ 'user@mydomain.com' ],
  rejectedErrors: [
    Error: Recipient command failed: 553 5.7.1 <mikaka27@hotmail.com>: Sender address rejected: not owned by user user@mydomain.com
        at SMTPConnection._formatError (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
        at SMTPConnection._actionRCPT (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:1589:24)
        at SMTPConnection.<anonymous> (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:1564:26)
        at SMTPConnection._processResponse (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:932:20)
        at SMTPConnection._onData (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:739:14)
        at TLSSocket.SMTPConnection._onSocketData (/mnt/D/Projects/NazwaTestEmailNode/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
        at TLSSocket.emit (events.js:315:20)
        at TLSSocket.EventEmitter.emit (domain.js:467:12)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9) {
      code: 'EENVELOPE',
      response: '553 5.7.1 <mikaka27@hotmail.com>: Sender address rejected: not owned by user user@mydomain.com',
      responseCode: 553,
      command: 'RCPT TO',
      recipient: 'user@mydomain.com'
    }
  ]
}
```

The question seems to be, why it treats sender and from fields differently, since nodemailer must be doing something else underneath?
Does anyone know how to fix it?

**Comment by andris9** [comment]
You have to use another provider that allows you to use different addresses.

**Comment by Christopher-Stevers** [comment]
Hey @Mikaka27  did you end up finding a email provider that does allow for this? I'm trying to find info on modifying the from field as well and there isn't a lot out there.

**Comment by Mikaka27** [comment]
> Hey @Mikaka27 did you end up finding a email provider that does allow for this? I'm trying to find info on modifying the from field as well and there isn't a lot out there.

Hi, the problem is not with an email provider, but with nodemailer library itself, I don't know why they closed it, but I didn't want to fight with this.

**Comment by andris9** [comment]
Nodemailer allows you to set any email address you like as the sender address. There are not restrictions. If that address is rejected or replced then this happens during transport by email servers (eg Gmail email servers never allow to use any other address as the account email)

**Comment by Mikaka27** [comment]
Then how will you explain that it worked for me using MailKit from .NET with the same email provider, and not with nodemailer?

**Comment by andris9** [comment]
Nodemailer will take whatever address you provide as the “from” option and will provide it to the SMTP server as the sender’s address, there is nothing to change or do differently there. Maybe MailKit sets the original address as the name, not address, so for the recipient it would seem like the “from” address is something else that was actually used.

**Comment by ujwal-setlur** [comment]
Per the [RFC](https://www.rfc-editor.org/rfc/rfc5322#page-22:~:text=The%20%22From%3A%22%20field%20specifies%20the%20author(s)%20of%20the%20message%2C%0A%20%20%20that%20is%2C%20the%20mailbox(es)%20of%20the%20person(s)%20or%20system(s)%20responsible%0A%20%20%20for%20the%20writing%20of%20the%20message.%20%20The%20%22Sender%3A%22%20field%20specifies%20the%0A%20%20%20mailbox%20of%20the%20agent%20responsible%20for%20the%20actual%20transmission%20of%20the%0A%20%20%20message.), shouldn't Nodemailer use the sender, if specified in the SMTP envelope transaction?

sender: user@mydomain.com

```
MAIL FROM user@mydomain.com
250 OK
```
