### ISSUE TITLE
6.6.x is broken for reply-to

### ISSUE THREAD

**Issue by thenitai** [nodemailer/nodemailer#1291]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x] No

3. State your problem here:

6.6.1 messes up the reply-to.

Example:

6.6.1: Reply-To: <"someone
  some"@domain.com>

6.5.0: Reply-To: "someone" <some@domain.com>

As you can see there is a linebreak and the quotation is wrong in 6.6.1. I've read in the release note that you've added a "newline" param. However, I cannot see the documentation for that. Nevertheless, it shouldn't break replying to emails :(

Thank you.

**Comment by andris9** [comment]
How does the `replyTo` argument exactly looks like?

**Comment by thenitai** [comment]
Exactly as I've posted :) Here are screenshots

6.6.1
![image](https://user-images.githubusercontent.com/372121/119545063-5b3a7580-bd60-11eb-9985-7e210d5185ac.png)

6.5.0
![image](https://user-images.githubusercontent.com/372121/119545151-7dcc8e80-bd60-11eb-88bf-8acf9430f567.png)

**Comment by andris9** [comment]
I mean in the Nodemailer message configuration

**Comment by thenitai** [comment]
Not sure what exactly you need as the configuration is the same as with 6.6.1 and 6.5.0.

```
 "reply_to" : {
        "full_address" : "some name <email@domain.com>", 
        "address" : "some name <email@domain.com>"
    }, 
```

**Comment by andris9** [comment]
I'm not sure where did you get that configuration format. The correct config would be

```
replyTo: "some name <email@domain.com>"
```

or

```
replyTo: {
    name: "some name",
    address: "email@domain.com"
}
```

**Comment by thenitai** [comment]
Ah sorry, that is our internal format. Upon sending we use obviously the right format.

The fact remains, reply-to doesn't work anymore as of 6.6.x.

**Comment by andris9** [comment]
If you are using a structure like

```
{
    "address" : "some name <email@domain.com>"
}
```

as the replyTo argument then this was never supposed to work. `address` property can only hold an email address, not address string (eg. it must be `"email@domain.com"` not `"some name <email@domain.com>"`)

**Comment by andris9** [comment]
6.6.1 fixed the bug where you were able to provide random values as the `address` property and it was actually used.

**Comment by thenitai** [comment]
Weird that it works with 6.5.x but not with 6.6.x. In any case, maybe want to put up a "breaking" warning as it sends the email but when the user hits reply it shows a malformatted email.

I wouldn't mind or say anything, but since it's working with 6.5.x and not with 6.6.x it's a change that has quite an effect.
