### ISSUE TITLE
SMTP connection not properly closed (QUIT command missing)

### ISSUE THREAD

**Issue by apinske** [nodemailer/nodemailer#1292]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
    Nodemailer does not terminate a SMTP connection with the QUIT command, but simply drops the TCP connection.
    
    > The sender MUST NOT intentionally close the transmission channel until it sends a QUIT command ...
    https://datatracker.ietf.org/doc/html/rfc2821.html#section-4.1.1.10
    
    Reproducible with this setup: https://github.com/greenmail-mail-test/greenmail/tree/release-1.6.4/greenmail-docker/clients/nodemailer

**Comment by gampu** [comment]
Does this issue still exist in the latest code?

**Comment by andris9** [comment]
Yes, Nodemailer does not issue QUIT and there is no plan to start doing it. Nodemailer used QUIT in the earliest versions but it caused issues (eg some servers did not close the connection after QUIT and Nodemailer was kept hanging forever). Obviously this is non-standard behaviour on Nodemailer's side but there is no difference at all if the QUIT command was sent or not as it does not affect queued emails in any way.

> If the connection is closed prematurely due to violations of the above or system or network failure, the server MUST cancel any pending transaction, but not undo any previously completed transaction
