### ISSUE TITLE
SES v3 - sendRawEmail().promise() is not a function

### ISSUE THREAD

**Issue by maguirekrist** [nodemailer/nodemailer#1293]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
With both the v2 and v3 distributions of AWS SES, I can't seem to get the example provided in the docs to work. Not to mention, within the source code of node mailer, in lib/ses-transport/index.js~267 the if statement that is supposed to check for v3 is not correctly identifying my v3 installation of SES. What can I do? I attempted to look at the source code for a solution but the check is elusive to me. 

Thank you,
Maguire.

**Comment by overtureweb** [comment]
I was having a similar issue but I was able to get it working:
Their example is wrong, you should be using SDK v2, they're referencing v3 in the require statement.
`
const aws = require("aws-sdk");

// you may need to adjust your region
const ses = new aws.SES({
		apiVersion: "2010-12-01",
		region: "us-east-1", 
	});
const transporter = nodemailer.createTransport({ SES: ses, AWS })
`

Also, you need to add your credentials to the .env file (install the dot-env npm package to enable environment variables)
https://www.npmjs.com/package/dotenv

***One important thing to note: the AWS SDK for SES does not authenticate using your SMTP key pair. You'll need to create a separate identity policy (IAM) and use store that access key and secret access key in the .env file:

AWS_ACCESS_KEY_ID=****
AWS_SECRET_ACCESS_KEY=****

**Comment by petrzjunior** [comment]
Confirming the bug. I managed to make this workaround providing the `SendRawEmailCommand` manually:
```javascript
import { SES, SendRawEmailCommand } from '@aws-sdk/client-ses';

const ses = new SES();
nodemailer.createTransport({
	SES: {
		ses: ses,
		aws: { SendRawEmailCommand},
	}
});
```

**Comment by andris9** [comment]
I've been using [this example](https://github.com/nodemailer/nodemailer/blob/master/examples/ses.js) to test AWS SES and it works both with SDK version 2 and 3. Could you try the same example to see if it throws on your case or not?

**Comment by petrzjunior** [comment]
@andris9 I ran the example and it worked just fine. Apperantly the problem were bad imports in my code. This is how I fixed it.
```diff
- import aws from '@aws-sdk/client-ses';
+ import * as aws from '@aws-sdk/client-ses';
```
Now it works like a charm. Thanks!

**Comment by gsusmonzon** [comment]
I had the same problem, luckily the [example in the oficial repo](https://github.com/nodemailer/nodemailer/blob/master/examples/ses.js) works just fine:

The key is to pass `ses` and `aws` variables when creating the transport. Probaly the solution from @petrzjunior works as well

```js
let nodemailer = require('nodemailer');
let aws = require('@aws-sdk/client-ses');

const ses = new aws.SES({
    apiVersion: '2010-12-01',
    region: 'us-east-1',
    credentials: {
        secretAccessKey: AWS_SECRET_ACCESS_KEY,
        accessKeyId: AWS_ACCESS_KEY_ID
    }
});

let transporter = nodemailer.createTransport({
    SES: { ses, aws }
});
```

**Comment by jpike88** [comment]
the typing on this is messed up.

```
/** is an option that expects an instantiated aws.SES object */
        SES: any; // aws-sdk.SES object
```

This advice is wrong, the type should look more like:

```
const SESClientImport = require('@aws-sdk/client-ses')

SES: {
ses: SESClientImport.SES;
aws: SESClientImport
}
```

**Comment by David-Kovich** [comment]
> Confirming the bug. I managed to make this workaround providing the `SendRawEmailCommand` manually:
> 
> ```js
> import { SES, SendRawEmailCommand } from '@aws-sdk/client-ses';
> 
> const ses = new SES();
> nodemailer.createTransport({
> 	SES: {
> 		ses: ses,
> 		aws: { SendRawEmailCommand},
> 	}
> });
> ```

God bless you my friend! You saved my sanity.

**Comment by saachinsiva** [comment]
@petrzjunior @David-Kovich 

I am facing the same issue and use the code you suggested but this time I am getting " **MessageRejected: Email address is not verified. The following identities failed the check in region** " but it works with SES version 1 for the same sender and recipients.

Any idea what might be causing this?

**Comment by david-gress** [comment]
If you are using aws sdk v3 you don't need a transporter object.

**Comment by ShabanRamadani** [comment]
For anyone who might be still encountering - based on the implementation you might have already in place, here's an article from aws itself of how to use both nodemailer with ses client v3 https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_ses_code_examples.html

**Comment by ludgerey** [comment]
I can confirm @David-Kovich approach. This one worked for me:

```typescript
import * as nodemailer from "nodemailer";
import { SES, SendRawEmailCommand } from "@aws-sdk/client-ses";

const transporter = nodemailer.createTransport({
  SES: {
    ses: new SES({
      region: process.env.AWS_SES_REGION,
    }),
    aws: { SendRawEmailCommand },
  },
});
```

**Comment by daywong1119** [comment]
i am using old version of nodemailer, update package and it works.

**Comment by narcisghe** [comment]
This one worked for me aswell, 
```
import { SES, SendRawEmailCommand } from '@aws-sdk/client-ses';

const ses = new SES();
nodemailer.createTransport({
	SES: {
		ses: ses,
		aws: { SendRawEmailCommand},
	}
});
```

I am using "@aws-sdk/client-ses": "^3.556.0", and "@types/nodemailer": "^6.4.0".

**Comment by dhegen-ai** [comment]
Facing similar issues, and after reading the code of nodemailer SES transport here is solution for `@aws-sdk/client-ses v3`:
```import { SES } from "@aws-sdk/client-ses";

import ENV from "@/lib/env";

const ses = new SES({
    region: ENV.AWS_SES_REGION,
    apiVersion: ENV.AWS_SES_API_VERSION,
    credentials: {
        accessKeyId: ENV.AWS_SES_ACESS_KEY_ID!,
        secretAccessKey: ENV.AWS_SES_SECRET_ACCESS_KEY!,
    },
});

const sendMail = async ({ from, to, subject, body }: { from: string, to: string, subject: string, body: string }) => {
    return ses.sendEmail({
        Source: from,
        Destination: {
            ToAddresses: [to]
        },
        Message: {
            Subject: {
                Data: subject,
                Charset: "UTF-8"
            },
            Body: {
                Html: {
                    Data: body,
                    Charset: "UTF-8"
                }
            }
        }
    });
};

export default sendMail;```

**Comment by ramkrishna757575** [comment]
> Confirming the bug. I managed to make this workaround providing the `SendRawEmailCommand` manually:
> 
> ```js
> import { SES, SendRawEmailCommand } from '@aws-sdk/client-ses';
> 
> const ses = new SES();
> nodemailer.createTransport({
> 	SES: {
> 		ses: ses,
> 		aws: { SendRawEmailCommand},
> 	}
> });
> ```

This worked for me as well...you are an angel 😇

**Comment by hardikbotsplash** [comment]
Upgrading nodemailer package to latest (6.9.16) fixed my issue.
