### ISSUE TITLE
Well known linking issue in docs

### ISSUE THREAD

**Issue by cakesoft-chaitanya** [nodemailer/nodemailer#1299]
The well known tab is not visible in the original documentation
https://nodemailer.com/

![Screenshot from 2021-06-17 12-56-34](https://user-images.githubusercontent.com/67996846/122351468-c8aa8200-cf6b-11eb-99f5-14d038eb69cf.png)

But is accessible by directly visiting the site https://nodemailer.com/smtp/well-known/

![Screenshot from 2021-06-17 12-57-15](https://user-images.githubusercontent.com/67996846/122351291-9f89f180-cf6b-11eb-9fe1-1f673844823e.png)

**Comment by andris9** [comment]
The current static website generator updates and creates new pages but does not delete old ones.
