### ISSUE TITLE
Image is attached but cant be seen inside the email

### ISSUE THREAD

**Issue by chaaawles** [nodemailer/nodemailer#1302]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ /] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [ /] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I'm attaching a jpeg/png images in the email im sending following the example
```
let message = {
    ...
    html: 'Embedded image: <img src="cid:unique@nodemailer.com"/>',
    attachments: [{
        filename: 'image.png',
        path: '/path/to/file',
        cid: 'unique@nodemailer.com' //same cid value as in the html img src
    }]
}
```

So far it works as attached but it doesnt show up in the said email. I was wondering what wrong am I doing. Looking forward for your positive response

**Comment by StanislavKharchenko** [comment]
I have the similar question regarding content of pdf.
How to directly send email with pdf-content instead of attach it as file?

**Comment by andris9** [comment]
Nodemailer does not handle the contents of the message or how it is displayed, it passes these values as is.
