### ISSUE TITLE
Nodemailer doesn't work in production whereas  works perfectly fine on the localhost with NEXT Js

### ISSUE THREAD

**Issue by AmanKuvera-Dev** [nodemailer/nodemailer#1304]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ # ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [ # ] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

Nodemailer doesn't work in **production** whereas  works perfectly fine on the **localhost** with **NEXT Js**

Here's the code, Please help me out if you have any solution to this.

export default function (req, res) {
    let nodemailer = require('nodemailer');
    require('dotenv').config();

    const transporter = nodemailer.createTransport({
        port: 465,
        host: "smtp.gmail.com",
        auth: {
            user: process.env.emailID,
            pass: process.env.emailPass,
        },
        secure: true,
    });

    const mailData = {
        from: process.env.emailID,
        to: process.env.toEmail,
        subject: `Message From ${req.body.first} ${" "} ${req.body.last}`,
        text: req.body.message + "Subject: " + req.body.subject + " | Sent from: " + req.body.email,
        html: `<div> Subject: <span style="font-weight:900;text-decoration:underline">${req.body.subject}</span></div> <br/> <p>Message: <span style="font-weight:900;text-decoration:underline">"${req.body.message}"</span></p> <br/> <div>From : ${req.body.first} ${" "} ${req.body.last} (${req.body.email})</div>`
       };

    transporter.sendMail(mailData, function (err, info) {
        if(err)
          console.log(err)
        else
          console.log(info)
      });

    console.log(req.body);
    res.status(200).json({status: "ok"});
  }

Form code:

const formData = {
            first,
            last,
            message,
            email,
            subject
        }

        const config = {
            endpoint: '/api/email'
          }

fetch(config.endpoint, {
            method: 'post',
            headers: {
              'Accept': 'application/json, text/plain, */*',
              'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
          }).then((res) => {
            if (res.status === 200) {
              setEmail('')
              setMessage('')
              setFirst('')
              setLast('')
              setSubject('')
            }else{
                setFail1(true)
            }
    
            }, (error) => {
                console.log("There was an error, please try again later");
                  setFail1(true)
            });

**Comment by theCodingJohn** [comment]
Having the same problem. Found any solution?

**Comment by AmanKuvera-Dev** [comment]
I struggled for a long time and didnt find a solution for this so I was forced to create a server side Nodejs application and host it on heroku and then use axios in my Next Js application to send data to the Api so the server would send the mail for me.

**Comment by theCodingJohn** [comment]
Hey there. I was able to fixed mine by adding OAth to my auth. I followed this instruction https://www.freecodecamp.org/news/use-nodemailer-to-send-emails-from-your-node-js-server/
```js 
 const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      type: "OAuth2",
      user: process.env.MAIL_USERNAME,
      pass: process.env.MAIL_PASSWORD,
      clientId: process.env.OAUTH_CLIENTID,
      clientSecret: process.env.OAUTH_CLIENT_SECRET,
      refreshToken: process.env.OAUTH_REFRESH_TOKEN,
    },
    secure: true,
  });
  
   const info = await transporter.sendMail({
      from: process.env.MAIL_USERNAME,
      to: "codingjohn@outlook.com",
      subject: `Contact form submission from ${name}`,
      html: `<p>You have a new contact form submission</p>
        <p><strong>Name: </strong>${name}</p>
        <p><strong>Email: </strong>${email}</p>
        <p><strong>Subject: </strong>${subject}</p>
        <p><strong>Message: </strong>${message}</p>`,
```

but i think what really solved the problem is when i set the value of from `from: process.env.MAIL_USERNAME` to have the same value as authenticated user ` user: process.env.MAIL_USERNAME,`

**Comment by raulbarriga** [comment]
> I struggled for a long time and didnt find a solution for this so I was forced to create a server side Nodejs application and host it on heroku and then use axios in my Next Js application to send data to the Api so the server would send the mail for me.

I did the same thing, but it only works locally, not when I deploy it to heroku for some reason. I also used OAuth2.

**Comment by AmanKuvera-Dev** [comment]
> > I struggled for a long time and didnt find a solution for this so I was forced to create a server side Nodejs application and host it on heroku and then use axios in my Next Js application to send data to the Api so the server would send the mail for me.
> 
> I did the same thing, but it only works locally, not when I deploy it to heroku for some reason. I also used OAuth2.

Weird, because I hosted it (https://www.amankuvera.tech - Contact Form) and it works fine for me, And yes, OAuth is a more relaible solution.

**Comment by raulbarriga** [comment]
> > > I struggled for a long time and didnt find a solution for this so I was forced to create a server side Nodejs application and host it on heroku and then use axios in my Next Js application to send data to the Api so the server would send the mail for me.
> > 
> > 
> > I did the same thing, but it only works locally, not when I deploy it to heroku for some reason. I also used OAuth2.
> 
> Weird, because I hosted it (https://www.amankuvera.tech - Contact Form) and it works fine for me, And yes, OAuth is a more relaible solution.

I moved my next.js to the vercel platform and did away with the express server I had. I still encountered a production issue there, but I managed to solve it by moving my res.send inside the successfully sent email condition since I had it outside of it and part of the default export function, always sending the email successfully but unable to receive it. Now everything work! I almost gave up on nodemailer lol.
