### ISSUE TITLE
How to send an encrypted message using Office 365 Message Encrytpion

### ISSUE THREAD

**Issue by aravind-25-gopinath** [nodemailer/nodemailer#1305]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ #] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [ #] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
My company supports email encryption for our internal users using Office 365 Message Encryption (OME). The GUI aspect in outlook's perspective is a toggle that allows the email to be encryted. Is there something that nodemailer that allows us to toggle that encrypted feature through nodemailer/code?

**Comment by andris9** [comment]
Nodemailer is transport level only. For any kind of encryption you either need to do this yourself or use an existing plugin, though there are none for OME, the only known one is for PGP: https://github.com/nodemailer/nodemailer-openpgp
