### ISSUE TITLE
Prevent injection of more email recipients in 'to' field!

### ISSUE THREAD

**Issue by mohitatray** [nodemailer/nodemailer#1307]
1. What kind of issue are you reporting?
- A security vulnerability!

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I am using nodemailer to send OTP (one-time password) to my users. The users enter their email and I send OTP to them like this:
```
const nodemailer = require('nodemailer')
const app = require('express')()

const emailTransporter = nodemailer.createTransport({
    host: "localhost",
    port: 25,
    tls: { rejectUnauthorized: false },
    disableFileAccess: true,
    disableUrlAccess: true
})

app.post('/send-otp', (req, res) => {
    const email = req.body.email // Email received from user input

    await emailTransporter.sendMail({
        from: '"OTP" <otp@mydomain.com>',
        to: [email], // User can inject multiple comma separated emails!!
        subject: 'OTP for login',
        text: `Use this OTP to login:\n${otp}`,
        html: `<h3>Use this OTP to login:</h3><br/><h1>${otp}</h1>`
    })
})
```

Now the problem is user can enter multiple comma separated emails and will receive OTP via email on multiple emails!

I know I can validate user input but you must prevent this too. You must do something similar as preventing SQL injection here. You must not allow specifying multiple comma separated recipients in 1 element of array if 'to' is an array! If 'to' is an array, 1 element of array should be strictly considered as 1 email recipient.

You can also add an option, something like `singleToRecipient: true`, so that only 1 recipient can be entered, otherwise error must be thrown.

**Comment by andris9** [comment]
This is documented and expected behavior. Do not trust input from users and aleays validate the valuea before using these for anything.

**Comment by mohitatray** [comment]
Thank you for the response. Actually the problem is it is really hard to validate emails. I was trying to follow [this answer](https://stackoverflow.com/questions/46155/how-to-validate-an-email-address-in-javascript/815232#815232).

> the only way to be absolutely, positively sure that what the user entered is in fact an email is to actually send an email and see what happens. Other than that it's all just guesses.

According to [Email address on wikipedia](https://en.wikipedia.org/wiki/Email_address#Local-part), the email addresses below are valid:
abc@example.com
" "@example.com
"Mohit, Atray@"@example.com
"Mohit, \"Atray\""@example.com
So you can almost put any character in the local part of email address by including them in quotes. So according to some answers (other than the accepted answer) in [this question](https://stackoverflow.com/questions/46155/how-to-validate-an-email-address-in-javascript), we should not try to validate an email address but just simply attempt to send email and see what happens.

So that is why, it would be better if there was a way to tell nodemailer that whatever is entered in 'to' field is just 1 recipient.

**Comment by andris9** [comment]
I suggest using a data validation module like Joi: https://joi.dev/
