### ISSUE TITLE
Nodemailer not sending emails at all (errno: -4039)

### ISSUE THREAD

**Issue by masroorejaz** [nodemailer/nodemailer#1308]
Hello,

When I first start using nodemailer it was working fine and sending emails easily. But now after 3 or 4 month later when I try the same code without any change it is not working and kept throwing the following errors:
**address: "167.86.99.133"
code: "ESOCKET"
command: "CONN"
errno: -4039
port: 587
syscall: "connect"**

This issue is driving me crazy. Kindly help me out.

Thank you

**Comment by apsampaio** [comment]
Are you using typescript? I was having the same issue but after compiling my code the issue disappeared

**Comment by m0j0nz0r** [comment]
I'm having the same issue, and yes we are using TypeScript.

**Comment by apsampaio** [comment]
Compile the code and run the .js

**Comment by m0j0nz0r** [comment]
I don't know that that is a sustainable solution. I think I'd rather just use a different library.

**Comment by masroorejaz** [comment]
Finally figure out the answer. I was first calling username and password from .env file but now it's no longer working. You have to hardcode the credentials now. This is the only way it's working now. Following is my code that's work:

router.post("/sendEmail", auth, async (req, res) => {


    const email = req.body.email;
    const subject = req.body.subject;
    const message = req.body.message;



    let transporter = nodemailer.createTransport(
        {
            host: "mail.myserver.com", // Hardcode It
            port: 587, // Hardcode It
            secure: false, 
            auth: {
                user: "noreply@myserver.com", // Hardcode It
                pass: "mypassword" // Hardcode It
            },
            tls: { rejectUnauthorized: false }
        }
    );


    let mailOptions = {
        from: "noreply@myserver.com", // Hardcode It
        to: email, // list of receivers. This can be done via variable
        subject: subject, // Subject line. This can be done via variable 
        html: message// html text body.  This can be done via variable
    };

    transporter.sendMail(mailOptions, function (error, success) {
        if (error) {
            res.send(error);
            console.log(error);

        }
        else {
            res.send(success);
            console.log("Server is ready to take our messages");
        }

    });



});

**Comment by hazem-saeed** [comment]
I'm facing the same issue, and I tried your solution, but it didn't work.

Here's my code, and beneath it the output of the 'debug' and 'logger'.

```
const sendEmail = async options => {
    const transporter = nodemailer.createTransport({
        host: 'smtp.mailtrap.io',
        port: 2525,
        secure: false,
        ignoreTLS: true,
        secureConnection: false,
        requiresAuth: true,
        auth: {
            user: 'hardcoded username',
            pass: 'hardcoded password'
        },
        tls:{
           rejectUnauthorized: false,
        //    ciphers: "SSLv3"
        },
        debug: true, // show debug output
        logger: true // log information in console
    });

    const mailOptions = {
        from: 'hello@hazem.com',
        to: options.email,
        subject: options.subject,
        text: options.message
    };

    await transporter.sendMail(mailOptions);
};
```

> 
> [2021-09-06 09:28:34] DEBUG Creating transport: nodemailer (6.6.3; +https://nodemailer.com/; SMTP/6.6.3[client:6.6.3])
> [2021-09-06 09:28:34] DEBUG Sending mail using SMTP/6.6.3[client:6.6.3]
> [2021-09-06 09:28:34] DEBUG [XaGREUWVfXQ] Resolved smtp.mailtrap.io as 3.209.246.195 [cache miss]
> [2021-09-06 09:28:55] ERROR [XaGREUWVfXQ] connect ETIMEDOUT 3.209.246.195:2525
> [2021-09-06 09:28:55] DEBUG [XaGREUWVfXQ] Closing connection to the server using "destroy"
> [2021-09-06 09:28:55] ERROR Send Error: connect ETIMEDOUT 3.209.246.195:2525
> Error: connect ETIMEDOUT 3.209.246.195:2525
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
>   errno: -4039,
>   code: 'ESOCKET',
>   syscall: 'connect',
>   address: '3.209.246.195',
>   port: 2525,
>   command: 'CONN'
> }

**Comment by andris9** [comment]
All the ESOCKET errors are network issues, most probably it's your firewall that is blocking you. If I run the same script I get a wrong password error (as expected) instead:

```
[2021-09-06 09:39:20] DEBUG Creating transport: nodemailer (6.6.3; +https://nodemailer.com/; SMTP/6.6.3[client:6.6.3])
[2021-09-06 09:39:20] DEBUG Sending mail using SMTP/6.6.3[client:6.6.3]
[2021-09-06 09:39:20] DEBUG [12NEEtQGwVU] Resolved smtp.mailtrap.io as 3.209.246.195 [cache miss]
[2021-09-06 09:39:20] INFO  [12NEEtQGwVU] Connection established to 3.209.246.195:2525
[2021-09-06 09:39:20] DEBUG [12NEEtQGwVU] S: 220 smtp.mailtrap.io ESMTP ready
[2021-09-06 09:39:20] DEBUG [12NEEtQGwVU] C: EHLO [127.0.0.1]
[2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-smtp.mailtrap.io
[2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-SIZE 5242880
[2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-PIPELINING
[2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-ENHANCEDSTATUSCODES
[2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-8BITMIME
[2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-DSN
[2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-AUTH PLAIN LOGIN CRAM-MD5
[2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250 STARTTLS
[2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] SMTP handshake finished
[2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] C: AUTH PLAIN AGhhcmRjb2RlZCB1c2VybmFtZQAvKiBzZWNyZXQgKi8=
[2021-09-06 09:39:25] DEBUG [12NEEtQGwVU] S: 535 5.7.0 Invalid login or password
[2021-09-06 09:39:25] INFO  [12NEEtQGwVU] User "hardcoded username" failed to authenticate
[2021-09-06 09:39:25] DEBUG [12NEEtQGwVU] Closing connection to the server using "end"
[2021-09-06 09:39:25] ERROR Send Error: Invalid login: 535 5.7.0 Invalid login or password
```

**Comment by hazem-saeed** [comment]
> 
> 
> All the ESOCKET errors are network issues, most probably it's your firewall that is blocking you. If I run the same script I get a wrong password error (as expected) instead:
> 
> ```
> [2021-09-06 09:39:20] DEBUG Creating transport: nodemailer (6.6.3; +https://nodemailer.com/; SMTP/6.6.3[client:6.6.3])
> [2021-09-06 09:39:20] DEBUG Sending mail using SMTP/6.6.3[client:6.6.3]
> [2021-09-06 09:39:20] DEBUG [12NEEtQGwVU] Resolved smtp.mailtrap.io as 3.209.246.195 [cache miss]
> [2021-09-06 09:39:20] INFO  [12NEEtQGwVU] Connection established to 3.209.246.195:2525
> [2021-09-06 09:39:20] DEBUG [12NEEtQGwVU] S: 220 smtp.mailtrap.io ESMTP ready
> [2021-09-06 09:39:20] DEBUG [12NEEtQGwVU] C: EHLO [127.0.0.1]
> [2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-smtp.mailtrap.io
> [2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-SIZE 5242880
> [2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-PIPELINING
> [2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-ENHANCEDSTATUSCODES
> [2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-8BITMIME
> [2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-DSN
> [2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250-AUTH PLAIN LOGIN CRAM-MD5
> [2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] S: 250 STARTTLS
> [2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] SMTP handshake finished
> [2021-09-06 09:39:21] DEBUG [12NEEtQGwVU] C: AUTH PLAIN AGhhcmRjb2RlZCB1c2VybmFtZQAvKiBzZWNyZXQgKi8=
> [2021-09-06 09:39:25] DEBUG [12NEEtQGwVU] S: 535 5.7.0 Invalid login or password
> [2021-09-06 09:39:25] INFO  [12NEEtQGwVU] User "hardcoded username" failed to authenticate
> [2021-09-06 09:39:25] DEBUG [12NEEtQGwVU] Closing connection to the server using "end"
> [2021-09-06 09:39:25] ERROR Send Error: Invalid login: 535 5.7.0 Invalid login or password
> ```

Thanks for your reply. I'm running this locally on my windows machine. And the firewall settings are turned off.

**Comment by andris9** [comment]
There are multiple firewalls between your machine and the email server. For example your ISP might be blocking all email related ports to prevent spamming or your organisation might only allow traffic on whitelisted ports etc.

**Comment by hazem-saeed** [comment]
> 
> 
> There are multiple firewalls between your machine and the email server. For example your ISP might be blocking all email related ports to prevent spamming or your organisation might only allow traffic on whitelisted ports etc.

Ok... Thanks again.. I'll look into it...

**Comment by enriquesalomon** [comment]
I've got the same issue , I just fix it trying to put the secure: false is the transporter.

**Comment by nkmittal** [comment]
I had the same issue. Then I hard-coded username and password into the JS file and it started working. Any clues on reverting it back to reading from file ?

**Comment by rishi-bathija** [comment]
I am encountering the same issue and i have tried so many things to resolve it, but i am not able to fix it. Also, can someone guide me for the services that i can use to send mails from the backend in case this issue is not going to get fixed. 
Here's my code:-


const nodemailer = require("nodemailer");
const mailSender = async (email, title, body) => {
    try {
        let transporter = nodemailer.createTransport({
            host: 'smtp.gmail.com',
            port: 587,
            secure: false,
            auth: {
                user: 'hardcoded-email',
                pass: 'hardcoded-password',
            }
        })

        let info = await transporter.sendMail({
            from: 'StudyNotion',
            to: `${email}`,
            subject: `${title}`,
            html: `${body}`,
        })
        console.log("Info", info);
        return info;
    } catch (error) {
        console.log(error.message);
        throw error;
    }
}

module.exports = mailSender;


Error that i am getting:-

Error: connect ETIMEDOUT 172.253.118.109:587
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -4039,
  code: 'ESOCKET',
  syscall: 'connect',
  address: '172.253.118.109',
  port: 587,
  command: 'CONN'
}

**Comment by andris9** [comment]
All timeout errors are always firewall related. Nodemailer can not do anything about it.

**Comment by rishi-bathija** [comment]
> All timeout errors are always firewall related. Nodemailer can not do anything about it.

But there is no firewall issue from my side. I have configured the inbound and outbound rules for the port 587

**Comment by Chibike-267** [comment]
please someone should help a brother, i also got thesame; who knows solution to this~
Error sending email:  Error: connect ETIMEDOUT 154.38.185.95:587
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -60,
  code: 'ESOCKET',
  syscall: 'connect',
  address: '154.38.185.95',
  port: 587,
  command: 'CONN'
}
Signup error: Error: connect ETIMEDOUT 154.38.185.95:587
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -60,
  code: 'ESOCKET',
  syscall: 'connect',
  address: '154.38.185.95',
  port: 587,
  command: 'CONN'
}

**Comment by Chibike-267** [comment]
this is my email.config setup
export default () => ({
  email: {
    host: process.env.FLUENT_SMTP_HOST,
    port: parseInt(process.env.FLUENT_SMTP_PORT, 10),
    auth: {
      user: process.env.FLUENT_SMTP_USER,
      //pass: process.env.FLUENT_SMTP_PASSWORD,
      pass: process.env.PASSWORD,
    },
    
    my email service/business logic code
    @Injectable()
export class EmailService {
  private transporter: nodemailer.Transporter;

  constructor(private configService: ConfigService) {
    this.transporter = nodemailer.createTransport({
      host: this.configService.get<string>('email.host'),
      port: this.configService.get<number>('email.port'),
      secure: true,
      auth: {
        user: this.configService.get<string>('email.auth.user'),
        pass: this.configService.get<string>('email.auth.pass'),
      },
      //authMethod: 'XOAUTH2',
    });
  }

  async sendVerificationEmail(email: string, token: string): Promise<void> {
    const verificationLink = `http://localhost:5173/verify/${token}`;

    const mailOptions = {
      from: this.configService.get<string>('email.auth.user'),
      to: email,
      subject: 'Verify your Email',
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Verify Email</title>
          <style>
            /* Email styling goes here */
          </style>
        </head>
        <body>
          <p>Click the following link to verify your account:</p>
          <a href="${verificationLink}">Verify Your Account</a>
        </body>
        </html>
      `,
    };

    try {
      console.log('Sending verification email to: ', email);
      const info = await this.transporter.sendMail(mailOptions);
      console.log('Email sent successfully: ', info.response);
    } catch (error) {
      console.error('Error sending email: ', error);
      throw error;
    }
  }
  }
  },
});

**Comment by trasherdk** [comment]
Check firewall rules :smile: 

```sh
# nmap 154.38.185.95
Starting Nmap 7.92 ( https://nmap.org ) at 2024-05-29 04:39 CEST
Nmap scan report for vmi1472999.contaboserver.net (154.38.185.95)
Host is up (0.085s latency).
Not shown: 997 filtered tcp ports (no-response)
PORT    STATE SERVICE
22/tcp  open  ssh
80/tcp  open  http
443/tcp open  https
```

**Comment by Abus00** [comment]
For anyone still having this issue. Just call dotenv.config() at the top of the file again (supposing it is somewhere in the utils or service folder). Even though this may seem repetitive - because it was most likely called in index.js already - this worked perfectly for me and fixed the issue. Hardcoding also works, but it is less beautiful.
