### ISSUE TITLE
Nodemailer is sending emails with the same subject as thread

### ISSUE THREAD

**Issue by DashBarkHuss** [nodemailer/nodemailer#1312]
Nodemailer is sending emails as a thread if the email has the same subject as a previously sent email. But I want to send the emails as separate emails, even if they have the same subject as each other.

I have an application that sends notification emails to users. The emails all have the same subject: _notification_. This is causing the emails to show as a thread, at least in Gmail.

How can I make each *notification email* send separately?

``` javascript
const nodemailer = require('nodemailer');

const logger = require('./logger');

class Email {
  constructor(email, to, pass) {
    this.user = email;
    this.to = to;
    this.pass = pass;
  }

  get mailOptions() {
    return {
      from: this.user,
      to: this.to,
      subject: 'notification',
      html: 'You received a new purchase in your shop.',
    };
  }

  get transporter() {
    const transporter = nodemailer.createTransport({
// for zoho emails
      host: 'smtp.zoho.com',
      port: 587,
      secure: false,
      auth: {
        user: this.user,
        pass: this.pass,
      },
    });

    return transporter;
  }

  send(cb) {
    this.transporter.sendMail(
      this.mailOptions,
      cb ||
        ((error, info) => {
          if (error) console.log(error);
          if (info) logger.log('silly', `message sent: ${info.messageId}`);
          this.transporter.close();
        })
    );
  }

  sendSync() {
    return new Promise((res, rej) =>
      this.transporter.sendMail(this.mailOptions, (error, info) => {
        if (error) rej(error);
        else res(info);
        this.transporter.close();
      })
    );
  }
}

const email = new Email(
  'somesendingemail@gmail.com',
  'somereceivingemail@gmail.com',
  'SendINgEmAIlPassWoRD'
);

email.send();
```

**Comment by andris9** [comment]
Nodemailer does not set an email as part of a thread. This is client side action only. In general you have to use a different subject line than whatever was sent before.

**Comment by DashBarkHuss** [comment]
Thanks. I receive a lot of emails with the same subject that come separate; notifications, weekly digests, newsletters. Is there nothing else on the Nodemailer side you can set to stop the client from interpreting the email as a thread? Or any advice on where I might look to find the answer?

**Comment by andris9** [comment]
Email threading is kind of dark arts, there is no universal standard for it so all clients do it slightly differently. Most common ways for threading are

1. Messages reference to eachother using References and In-Reply-To headers
2. Messages match the following rules:
  a) The same sender or recipients,
  b) The same subject,
  c) And is sent within one week of an earlier message in the thread.

To break out of a thread you must make sure that your message does not meet these conditions.
