### ISSUE TITLE
Is nodemailer compatible with pino logger?

### ISSUE THREAD

**Issue by meglio** [nodemailer/nodemailer#1313]
Please advise if nodemailer is compable with pino? The "officially supported" logger has not been supported for ages and therefore is not a good option. Please advise

**Comment by andris9** [comment]
You can convert log output from Nodemailer to pino like is done [here](https://github.com/postalsys/emailengine/blob/af449c2c806e2fa67e4d0759952b05b82c9db931/lib/connection.js#L1450-L1463) (`smtpLogger ` is the object that is set as the value for `logger` option and `this.logger` is a pino instance)

**Comment by meglio** [comment]
Wait, but you closed the issue without actually answering the question.

**Comment by andris9** [comment]
Sorry for closing, this here is a bug tracker, it was not a bug.

**Comment by meglio** [comment]
Can it be qualified as a "feature request" then? I.e. to support "pino logger" out of the box.
