### ISSUE TITLE
Error "[ERR_TLS_CERT_ALTNAME_INVALID]"

### ISSUE THREAD

**Issue by jganga1841** [nodemailer/nodemailer#1315]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [ ] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

**Comment by jganga1841** [comment]
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: **ip_address** is not in the cert's list:

**Comment by andris9** [comment]
A it says. You are using an IP address as the hostname, it is not included in the certificate and thus certificate validation fails. You can use `tls: {servername: "example.com"}` configuration option to provide a server name for SNI

**Comment by hemant171k** [comment]
> A it says. You are using an IP address as the hostname, it is not included in the certificate and thus certificate validation fails. You can use `tls: {servername: "example.com"}` configuration option to provide a server name for SNI

as you mention where we need to change this setting and i a using this nodemailer on goadday vps server then what the changes you suggest accordingly please help
