### ISSUE TITLE
On Cancel an calendar invite the mail is not getting cancelled.

### ISSUE THREAD

**Issue by santosh279** [nodemailer/nodemailer#1316]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ Y] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

3. State your problem here:
- We are working with the invite of a user using the calendar invite of node-mailer and the cancellation of the email isn't working as expected.

**Comment by andris9** [comment]
Nodemailer passes the calendar event as provided. It does not manage the contents of the events.
