### ISSUE TITLE
SMTPConnection._getHostname: high probability to fall back to localhost

### ISSUE THREAD

**Issue by oxzi** [nodemailer/nodemailer#1317]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

For SMTP's `EHLO` and `HELO`, the machine's hostname will be sent along.
In nodemailer's `SMTPConnection` class the hostname is stored in the `name` variable, defaulting to the result of the class' `_getHostname()` method.

https://github.com/nodemailer/nodemailer/blob/3aca7be0919c6f17b2d18ba8420a6464c7c22be0/lib/smtp-connection/index.js#L1756-L1758

NodeJS's `os.hostname()` function, however, only returns the hostname in a "short" way, not in the FQDN format.
To illustrate this:
```
root@james:~# hostname
james
root@james:~# hostname -f
james.example.org

root@james:~# node
Welcome to Node.js v14.17.4.
Type ".help" for more information.
> os = require('os')
. . .
> os.hostname()
'james'
```

https://github.com/nodemailer/nodemailer/blob/3aca7be0919c6f17b2d18ba8420a6464c7c22be0/lib/smtp-connection/index.js#L1760-L1763

To continue with `_getHostname()`, the next comment also says to ignore the previous result if not being a FQDN.
At least on my GNU/Linux machine, this should never be the case, unless I configure my machine's hostname in a non-default way.

By falling back to using `localhost`, some information goes missing.
But worse, by using the `localhost` in `HELO` some spamfilters might get triggered.
Concretely, this results in 4.5 points for [rspamd's hfilter](https://github.com/rspamd/rspamd/blob/e2c9ea10a36bd2f48d4570123062d8af6dffc513/conf/scores.d/hfilter_group.conf#L25-L28).

__Edit__: Here I have written `localhost` instead of `127.0.0.1`, as used in the code snippet. This might be misleading.

in RFC 5321, section [4.1.1.1](https://datatracker.ietf.org/doc/html/rfc5321#section-4.1.1.1) defines the following ABNF:
> ehlo           = "EHLO" SP ( Domain / address-literal ) CRLF
> helo           = "HELO" SP Domain CRLF

Following the definition of `Domain` in section [4.1.2](https://datatracker.ietf.org/doc/html/rfc5321#section-4.1.2):
> Domain         = sub-domain *("." sub-domain)
> sub-domain     = Let-dig [Ldh-str]
> Let-dig        = ALPHA / DIGIT
> Ldh-str        = *( ALPHA / DIGIT / "-" ) Let-dig

According to my understanding, also a non-FQDN should be RFC compliant.

By the way, I am not quite sure, but I don't think `localhost` itself is even an FQDN.

https://github.com/nodemailer/nodemailer/blob/3aca7be0919c6f17b2d18ba8420a6464c7c22be0/lib/smtp-connection/index.js#L1765-L1770

Finally, this is not related to the previous issue, but closes the method.
Note that the regular expression only takes IPv4 addresses into account and not IPv6 as well.

Thanks for all your work in this library and please keep it up!

**Comment by andris9** [comment]
For all such cases where you have a weird hostname use the `name` option https://nodemailer.com/smtp/#connection-options

**Comment by oxzi** [comment]
Thanks for your fast feedback, @andris9!

I am not using nodemailer directly, but more as a dependency of another software which I just wanna deploy.
My intention was not to touch this software because of reasons. However, I guess I have to.

**Comment by andris9** [comment]
Normally nodemailer is used in web facing servers that have FQDN properly set. For testing/dev environments it might be different (eg hostnames like `Ubuntu_16` that is not FQDN and not even valid as a local hostname due to the underscore). Some SMTP servers don’t care, some reject clients with such HELO hostnames. Also there are cases such in AWS where the local interface IP (and hostname) does not much the public one. In older Nodemailer versions Nodemailer actually “phoned home” to get the resolved public IP/hostname from nodemailer’s own web server but this had even more problems than the current approach where you are supposed to provide the hostname yourself if the default is not suitable.

**Comment by oxzi** [comment]
> Normally nodemailer is used in web facing servers that have FQDN
> properly set.

Just to clearify it, the hostname is configured correctly on this
machine.

It is running Debian, and as the manual says, the hostname should not
contain the FQDN itself [0]. To set the FQDN, the /etc/hosts file should
be configured.

The following (redacted) output shows the correct configuration:

> ***@***.***:~# hostname
> james
> ***@***.***:~# hostname -f
> james.organization.org

By the way, there are multiple posts online [1] regarding this issue, as
NodeJS's os.gethostname does not automatically returns the FQDN version
of the hostname.

> Some SMTP servers don’t care, some reject clients with such HELO
> hostnames.

Of course, that's tricky. However, as I wrote before, for SMTP the
hostname does not need to be a FQDN.

On the other hand, falling back to a private IP address also causes
problems. Here, it triggered an rspamd rule against "private" IP
addresses.

[0] https://www.debian.org/doc/manuals/debian-reference/ch03.en.html#_the_hostname
[1] https://unix.stackexchange.com/questions/259702/node-js-get-fqdn
