### ISSUE TITLE
Does a Docker container need any ports exposed / mapped to make nodemailer SMTP work?

### ISSUE THREAD

**Issue by meglio** [nodemailer/nodemailer#1318]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes.
- [x] No.

3. State your problem here:

Dear team,

Do I need to expose any SMTP ports when sending email through SMTP from within a Docker container? Haven't found it in the documentation.

I'm getting this error and I'm not sure if it is related to Docker port exposure in any way:

> "Send Error: 139997859638072:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"

Please advise. -- Many thanks, Anton

**Comment by andris9** [comment]
port 587 requires `secure` option to be `false`.

**Comment by Baleen-Y** [comment]
@andris9 
secure option has been set to false.But I get the same error occasionally, not always.
Is there a way to find where the problem is?
