### ISSUE TITLE
Typo in website

### ISSUE THREAD

**Issue by RedRozio** [nodemailer/nodemailer#1319]
In the https://nodemailer.com/usage/ page, there is a typo in the documentation, by the comma separating the two arguments

![image](https://user-images.githubusercontent.com/69890033/130356833-e03e1b47-950b-4541-8528-360e9d2169a3.png)

I believe the correct format would be:
`transporter.sendMail(data, [callback])`

**Comment by andris9** [comment]
It’s pseudo code that should mean that callback is an optional argument. I can see how it could be misunderstood though
