### ISSUE TITLE
Security: Please update underscore to latest version

### ISSUE THREAD

**Issue by styxlab** [nodemailer/nodemailer#1320]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A security issue in Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

Nodemailer uses underscore in its dependecies with the following dependency chain:

```
nodemailer-smtp-transport@2.7.4 requires underscore@~1.7.0 via a transitive dependency on httpntlm@1.6.1
```

**Please update underscore to a secure version.**

### Details:
![image](https://user-images.githubusercontent.com/19638263/130594049-f65b6bd7-6f99-47b1-a2d2-c30ac99e74e9.png)

**Comment by andris9** [comment]
Please upgrade to latest version of Nodemailer.

**Comment by styxlab** [comment]
@andris9 Thanks for the quick response. Didn't realize `nodemailer-smtp-transport` is included in `nodemailer`. Maybe adding a deprecation warning in `nodemailer-smtp-transport` would have helped me avoiding confusion. 

Thanks a lot for nodemailer, it's an indispensable package!
