### ISSUE TITLE
How to specify domain for auth user in nodemailer (windows smtp server)

### ISSUE THREAD

**Issue by gsRatti1** [nodemailer/nodemailer#1321]
I am unable to find an option to supply the domain of the user in auth credentials.
In .net, the smtp client takes a NetworkCredentials object, which has user, password and domain fields

But in nodemailer , we dont seem to have 

 const transporter = NodeMailer.createTransport({
        host: '***'
        port: '465'
        secure: true,
        auth: {
          user: settings.userIdForAuth,
          pass: settings.passwordForAuth,
         **domain ?**
        },
      });

**Comment by shalvy** [comment]
I have a same issue, when trying to configure a custom domain smtp host,

**Comment by andris9** [comment]
Nodemailer does not support NTLM out of the box. You can find an example how to use it here: https://github.com/nodemailer/nodemailer-ntlm-auth
