### ISSUE TITLE
Add Deno Support

### ISSUE THREAD

**Issue by NewtTheWolf** [nodemailer/nodemailer#1331]
because i only use deno i always notice that the good things are not yet migrated to deno

it would be very great if I could also offer a deno support because the alternative for deno is not the best

**Comment by BierDav** [comment]
Any updates?

**Comment by andris9** [comment]
Nodemailer is pretty much complete. It supports Node versions starting from Node v6 and is kept updated so it would support the newest Node versions as well. There are no plans to migrate or change anything in this regard. If anyone wants to fork Nodemailer and migrate it to Deno then they are welcome to do so and I would add a note about it to the README.

**Comment by juslin03** [comment]
Hey @NewtTheWolf, you could use nodemailer with deno now by using npm specifier.

Here is my example that works fine.

I created a file called `sendMail.ts` in which I have this.

```
import nodemailer from "npm:nodemailer";

export async function sendMail(mailOptions: Record<string,unknown>) {
    const smtpTransportOptions = {
        host: Deno.env.get('SMTP_HOST'),
        auth: {
            user: Deno.env.get('SMTP_USERNAME'),
            pass: Deno.env.get('SMTP_PASSWORD'),
        },
        tls: {
            ciphers: "SSLv3",
        },
        service: Deno.env.get('SMTP_SERVICE')
    };

    const transporter = nodemailer.createTransport(smtpTransportOptions);

    const info = await transporter.sendMail(mailOptions);

    return info;
}
```

To test this,

```
const mailOptions = {
        from: Deno.env.get('SMTP_SENDER'),
        to: 'mail@example.com',
        subject: 'Test',
        text: "This is a nodemailer test with Deno",
};

const newMail = await sendMail(mailOptions);

console.log(newMail);

```

Result !

![image](https://github.com/nodemailer/nodemailer/assets/36005325/a0a0cb72-2168-420d-8293-cba88a3f292b)

**Comment by edard3v** [comment]
Nodemailer doesn't work for me, I think Deno is blocking port 465 or 587 T.T.

**Comment by ray73864** [comment]
> Nodemailer doesn't work for me, I think Deno is blocking port 465 or 587 T.T.

Did you do the '--allow-net'?

Deno runs with security first in mind, so unless you run your deno project with that, Deno won't allow your project to do network related stuff.

**Comment by edard3v** [comment]
Yes, the detail is that they allegedly abused Deno and blocked nodemailer xD @ray73864
