### ISSUE TITLE
Nodemailer failing at DNS Lookup

### ISSUE THREAD

**Issue by antonstech** [nodemailer/nodemailer#1334]
So i am running a Ghost Installation where i am trying to send some Emails
The Emails are always getting refused so i looked into the Logs and i saw
`Error: queryA EREFUSED smtp.web.de    at QueryReqWrap.onresolve [as oncomplete] (dns.js:210:19)`
but when i do a `nslookup smtp.web.de` on the same machine it works completely fine

**Comment by 1njm** [comment]
@antonstech did you find any solution? As I'm also facing the same error.

**Comment by antonstech** [comment]
@1njm Mine also worked with version 4.13 on my old Server idk
