### ISSUE TITLE
Calling os.networkInterfaces() outside of a function causes an error in non-node environments

### ISSUE THREAD

**Issue by jwmickey** [nodemailer/nodemailer#1341]
In a recent change to [lib/shared/index.js](https://github.com/nodemailer/nodemailer/blob/efc394754571c5986ef6d9c3ed56c1e2d1944531/lib/shared/index.js#L15) the call to os.networkInterfaces() was moved from within the `resolver` function to the root level of the file.  I assume to optimize and only call it once.  

This is an edge-case and I am aware that the intent is to use nodemailer in a node environment (hence the name :)) but this is causing us some trouble.  We are using nodemailer in a custom [cypress](https://www.cypress.io/) command to send some results.  Cypress runs in the browser, but you can use `cy.task()` to run nodejs code outside of the browser.  In nodemailer v6.6.x this was working fine because `os.networkInterfaces()` was only being called in a function, but with this change it is being called as soon as the library is imported, which happens outside of cy.task and thus causes an error.

Would you consider refactoring this file so that networkInterfaces is only called when needed?

**Comment by jwmickey** [comment]
Any consideration for this?

**Comment by newcomer** [comment]
We also have this issue.
