### ISSUE TITLE
Bcc headers are stripped in MailComposer

### ISSUE THREAD

**Issue by danielepolencic** [nodemailer/nodemailer#1342]
This issue is related to `MailComposer` and `MimeNode`.

With `MailComposer` I can create an email with a Bcc header like this:

```ts
const mailcomposer = new MailComposer({
          to,
          cc,
          bcc: ['email@inbcc.com'],
          html: body,
          subject,
          attachments: [],
        })
```

However, when the email is built, the Bcc is removed:

```ts
const payload = await mailcomposer.compile().build()
console.log(payload.toString('ascii'))
// Bcc header is missing in the output
```

Digging in the code reveals that the Bcc header is removed by `MimeNode` unless you set `keepBcc: true` in the constructor. https://github.com/nodemailer/nodemailer/blob/efc394754571c5986ef6d9c3ed56c1e2d1944531/lib/mime-node/index.js#L33

Unfortunately, there is no way to pass an argument to MailComposer that cascades to MimeNode (at least from my initial investigation).

I can think about two options to make this work:
1. If the `bcc` is set in MailComposer, make sure that `keepBcc` is true in MimeNode.
1. Expose the config for MimeNode in MailComposer.

I don't fully grasp the implications of 2) and I suspect it's not straightforward. If 1) is doable, I can raise a PR along the lines of

in https://github.com/nodemailer/nodemailer/blob/efc394754571c5986ef6d9c3ed56c1e2d1944531/lib/mail-composer/index.js#L471-L491

add this one liner:

```ts
node = new MimeNode(element.contentType, {
                filename: element.filename,
                baseBoundary: this.mail.baseBoundary,
                textEncoding: this.mail.textEncoding,
                boundaryPrefix: this.mail.boundaryPrefix,
                disableUrlAccess: this.mail.disableUrlAccess,
                disableFileAccess: this.mail.disableFileAccess,
                normalizeHeaderKey: this.mail.normalizeHeaderKey,
                newline: this.mail.newline
                keepBcc: !!this.mail.bcc // <-- this line
            });
```

I believe the same change has to be extended to the next block too.

**Comment by jkozieronek** [comment]
> I can think about two options to make this work:
> 
> 1. If the `bcc` is set in MailComposer, make sure that `keepBcc` is true in MimeNode.
> 2. Expose the config for MimeNode in MailComposer.

Option 1 is not backwards compatible. 
Option 2 is the correct fix. `MainComposer.compile()` can take optional MineNode options. 

Luckily, `compile()` returns a `MimeNode` which has the property `keepBcc` (it's just not exposed in TS types) so you can set it before calling build. See https://nodemailer.com/extras/mailcomposer/#bcc

```js
var mailOptions = {
   ...
   bcc: 'bcc@example.com'
}

var mail = new MailComposer(mailOptions).compile()
mail.keepBcc = true
mail.build(function(err, message){
    process.stdout.write(message);
});
```

If using TypeScript, just add `// @ts-ignore` above the offending line until types are fixed.

**Comment by danielepolencic** [comment]
I can confirm that the code above fixes it. Thanks!

**Comment by andris9** [comment]
The Bcc field usage has been documented [here](https://nodemailer.com/extras/mailcomposer/#bcc). I agree that this is counterintuitive and bad API design, but it has worked like this for 10+ years already, and I'm not really up to changing Nodemailer's API anymore.

**Comment by AnandChowdhary** [comment]
> The solution above is more of a workaround than an actual solution. I believe this was just an oversight when creating the type definitions and shouldn't be a big deal to fix.

@andris9 I could be wrong, but I think @gojevicmario meant that the type definition in `@types/nodemailer` does not allow `keepBcc`:

![CleanShot 2024-04-22 at 09 16 54@2x](https://github.com/nodemailer/nodemailer/assets/2841780/e70f09ca-21eb-4eb3-acad-d60a56dea6d5)

**Comment by AnandChowdhary** [comment]
Thank you! I have opened a discussion here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69409
