### ISSUE TITLE
im getting Error: connect ETIMEDOUT 13.49.22.0:443 

### ISSUE THREAD

**Issue by ZedanSaheer** [nodemailer/nodemailer#1345]
Can somebody help me fix this error , i dont know why sendmain would not work for me in any manner , i have used the template in website still not able to get anything working

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: connect ETIMEDOUT 13.49.22.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '13.49.22.0',
  port: 443,
  type: 'FETCH',
  sourceUrl: 'https://api.nodemailer.com/user'
}

```

**Comment by shwao** [comment]
You are trying to create a test account, correct?

The Ethereal Email service used for that seems to be down.

**Comment by ZedanSaheer** [comment]
Thank you for your response , it's true i fixed it by using a sample gmail
account.
