### ISSUE TITLE
Does it connect to Ethereal even if I use my own SMTP server?

### ISSUE THREAD

**Issue by brykov** [nodemailer/nodemailer#1354]
I'm using my own local SMTP server. I'm also behind a firewall. My e-mails get delivered ok but from time to time I see this in the logs:
`Error: connect ETIMEDOUT 141.94.68.31:443`

It seems this IP address belongs to Ethereal (although if you try to nslookup it or open it in your browser, it will look very sketchy)

So. Does nodemailer try to connect to Ethereal even if it's not used?

**Comment by andris9** [comment]
This happens when you call `nodemailer.createTestAccount(…)`. Search for your codebase if you use it anywhere or trigger it otherwise (eg. by running Nodemailer’s unit tests or tge example scripts).
