### ISSUE TITLE
Postinstall console advertisement message claims that there is a "Github Sponsors goal to remove it" - which does not exist

### ISSUE THREAD

**Issue by matkoniecz** [nodemailer/nodemailer#1356]
https://github.com/sponsors/andris9 is linked as target and there is no such goal listed there

https://github.com/nodemailer/nodemailer/blob/fcb0d1f5918a89ca5e8ab880134fec07c4e92bc7/postinstall.js#L21

**Comment by andris9** [comment]
That post-install step was removed from Nodemailer a long time ago. The file is still there, but it is not executed.

**Comment by matkoniecz** [comment]
Oh, so I should just update from an ancient version. I though that checking for presence of problematic text would be sufficient, sorry for a noise.
