### ISSUE TITLE
Unable to find the well known services in the docs

### ISSUE THREAD

**Issue by j23schoen** [nodemailer/nodemailer#1359]
This isn't a bug, but an issue with documentation. I'm working on an app that uses node mailer and it creates the transport by specifying a `service` option. I was curious how that was being used but I can't find it anywhere in documentation. Finally a google search brought me directly to the [well-known services page](https://nodemailer.com/smtp/well-known/). The problem is this page is not easily findable and it's not available in the directory on the left hand side of the documentation page. I'd be happy to help and update the website if it's available to, if not that's fine. But I wanted to call this out because it was frustrating trying to track down the source of the `service` option for transports. 

the following screenshot shows the docs directory when you visit the transports section:
![Screen Shot 2021-12-22 at 11 05 29 AM](https://user-images.githubusercontent.com/5719335/147121426-1f5b8ae1-91a6-4d97-9673-6e0bbb40ef12.png)

I found the well-known link on google and this is what the directory looks like if I navigate directly to the page.
![Screen Shot 2021-12-22 at 11 05 21 AM](https://user-images.githubusercontent.com/5719335/147121427-0705e0d1-61a8-4120-9ffe-b7b46e31cdc4.png)

**Comment by popod** [comment]
@andris9 what about this ? How could we help ?

I think that the well known services link should be in the doc too. This is a really useful page.

Thank you

**Comment by popod** [comment]
still not answered. @andris9 could you ? Thanks

**Comment by popod** [comment]
still not..

**Comment by andris9** [comment]
Well-known services have been soft-deprecated for years. It has been removed from the documentation years ago and it is not used in any official examples. The feature itself still works as Nodemailer has extremely long-term backward support.
