### ISSUE TITLE
Suspicious of SPAM

### ISSUE THREAD

**Issue by IHZAQSTORM33** [nodemailer/nodemailer#1360]
I keep getting this error when sending an email, how to fix this?

**Comment by matkoniecz** [comment]
Are you sending spam?

**Comment by IHZAQSTORM33** [comment]
> Are you sending spam?

Actually no and yes?
I'm using nodemailer to basically make an automated email.
And every email that sent are different and unique. (except the subject ofc)
many people use my project and It would end up sent this error.

The only way to fix this is send any email to anyone in gmail.com, and the spam filter will trust it.
But, after it fixed. nodemailer begins to sent up to 5 email. then the error come back

how to fix this? thanks (sorry for grammar)
