### ISSUE TITLE
Problems with function createTestAccount()

### ISSUE THREAD

**Issue by munhoz2k** [nodemailer/nodemailer#1361]
The promises createTestAccount is not being returned. My API gets stuck on the part where the code tries to createTestAccount function, it seens that this function is not answering... How can I fix this???

**Comment by Shadow-Flash** [comment]
I also tried the same function ... but it's not returning anything which eventually failing the promise.

I am using:
- Node.js v17.3.1
- nodemailer v6.7.2
- @types/nodemailer v6.4.4 (I am using TS)

`Error: connect ETIMEDOUT 2001:41d0:304:200::baa9:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '2001:41d0:304:200::baa9',
  port: 443,
  type: 'FETCH',
  sourceUrl: 'https://api.nodemailer.com/user'
}`

**Comment by Mr-warriyo** [comment]
Im facing the same problem getting the following in my console/Terminal.

The code I used is same as one in example.[Just Edited some user details.]

Error:
```js
Error: connect ETIMEDOUT 2001:41d0:304:200::baa9:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '2001:41d0:304:200::baa9',
  port: 443,
  type: 'FETCH',
  sourceUrl: 'https://api.nodemailer.com/user'
}
```

Thanks.
