### ISSUE TITLE
sendMail to cc is not working as expected

### ISSUE THREAD

**Issue by mdsaddam** [nodemailer/nodemailer#1363]
I want to send an email to multiple recipients (cc) & using the below sample code. All the recipients are receiving the emails but as a separate mail but we want all of the users to be copied to the same email.

```
  const data = {
    to: 'xxx@xyz.com',
    cc: 'cc@xyz.com',
    from: 'abc@xyz.com',
    subject: ``,
    html: ``
  };
  SendMail.sendMail(data);
```

Also tried multiple recipients (comma separated string in "to:" field) but still the same issue.

Using following packages (latest versions)
```
    "nodemailer": "^6.7.2",
    "nodemailer-mandrill-transport": "^1.2.0",
```

Using SMTP transport with Mandrill service.

**Comment by andris9** [comment]
Mandrill splits up your message. Nodemailer sends it out to Mandrill as it should.

**Comment by mdsaddam** [comment]
After some research found the solution in Mandrill documentation. Looks like they might have updated their SMTP api. So we've to pass additional header parameter (X-MC-PreserveRecipients) to achieve the requested functionality. Following is the example

```
  const data = {
    to: 'xxx@xyz.com',
    cc: 'cc@xyz.com',
    headers: {
      'X-MC-PreserveRecipients': true // This is required to preserve the above mentioned to: && cc: fields
    },
    from: 'abc@xyz.com',
    subject: ``,
    html: ``
  };
  SendMail.sendMail(data);
```

**Comment by hkhan-dev** [comment]
> After some research found the solution in Mandrill documentation. Looks like they might have updated their SMTP api. So we've to pass additional header parameter (X-MC-PreserveRecipients) to achieve the requested functionality. Following is the example
> 
> ```
>   const data = {
>     to: 'xxx@xyz.com',
>     cc: 'cc@xyz.com',
>     headers: {
>       'X-MC-PreserveRecipients': true // This is required to preserve the above mentioned to: && cc: fields
>     },
>     from: 'abc@xyz.com',
>     subject: ``,
>     html: ``
>   };
>   SendMail.sendMail(data);
> ```

its helpful,
thanks @mdsaddam
