### ISSUE TITLE
get error when trying to send email

### ISSUE THREAD

**Issue by SerzhanHelena** [nodemailer/nodemailer#1366]
I want to add an opportunity to send from my website emails to my Gmail. This is my code:

```
let transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    secure: false, // true for 587, false for other ports
    auth: {
        user: process.env.USER,
        pass: process.env.PASS
    }
});
```
When I test it locally, it works good, but on deployed site, I get an error:

`{"error":{"code":"EAUTH","command":"API"}}`

**Comment by patchlog** [comment]
if your gmail account has 2FA active then you will need to use an "Application specific Password", otherwise you need to enable "Less Secure Apps" https://myaccount.google.com/lesssecureapps
