### ISSUE TITLE
ETIMEDOUT for outlook

### ISSUE THREAD

**Issue by yldrmali** [nodemailer/nodemailer#1367]
_**nodemailer version:6.7.2**_
My daily cron job service stopped working on 30 January 2022. It was working without any problem for months. When I debugged the reason, it was the `host` name.
```js
const transporter = nodemailer.createTransport({
  service: 'outlook',
  auth: {
    user: 'bla@bla.com',
    pass: 'blablabla',
  },
});

transporter.sendMail(
  {
    from: 'bla@bla.com',
    to: 'bla@bla.com',
    subject: 'Connection test',
    html: '<h2>Hello</h2>',
  },
  (err, info) => {
    console.log(err, info);
  },
);
// err
//Error: connect ETIMEDOUT 204.79.197.212:587
//    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
//  errno: -4039,
//  code: 'ESOCKET',
//  syscall: 'connect',
//  address: '204.79.197.212',
//  port: 587,
//  command: 'CONN'
//} undefined
//
```
when service is set to 'outlook' for transporter configuration it uses the service below. But it cannot connect to the specified host and port. It seems `smtp.live.com` is not the right host for `outlook` service.
```js
     //nodemailer/lib/well-known/services.json
    "Hotmail": {
        "aliases": ["Outlook", "Outlook.com", "Hotmail.com"],
        "domains": ["hotmail.com", "outlook.com"],
        "host": "smtp.live.com",
        "port": 587
    },
```
I made a small addition and modification to the same file and it's working now. `host` needs to be `smtp-mail.outlook.com` for outlook mail service.
```js
     //nodemailer/lib/well-known/services.json
    "Hotmail": {
        "aliases": ["Hotmail.com"],
        "domains": ["hotmail.com"],
        "host": "smtp.live.com",
        "port": 587
    },
    "Outlook": {
        "aliases": ["Outlook", "Outlook.com"],
        "domains": [ "outlook.com"],
        "host": "smtp-mail.outlook.com",
        "port": 587
    },
```
I'm not aware of any change for Microsoft Outlook mail configuration. Is this the propery way to fix this issue?

**Comment by popod** [comment]
Having the exact same issue but with an xxx@hotmail.com email address !

It seems that the correct host for Outlook and Hotmail is now `smtp-mail.outlook.com`.

**Comment by victor-gabou** [comment]
Same problem here and the update of outlook smtp host works

**Comment by popod** [comment]
@andris9 could you check this please ? What do you think about that ?

Thanks

**Comment by aortukgp** [comment]
Thanks everyone, I had the same problem and changed the object from this:

```
{
   transporter: {
        service: `Hotmail`,
        auth:     credentials,
        tls: {
            rejectUnauthorized: false
        }
    }
}
```
to this:

```
const config = {
    transporter: {
        host: "smtp-mail.outlook.com",
        port:  587,
        auth:  credentials,
        tls: {
            rejectUnauthorized: false
        }
    }
}
```

555

**Comment by ndukachukz** [comment]
same problem with aws SMTP host.
