### ISSUE TITLE
Error EREFUSED CODE:EDNS while sending an email

### ISSUE THREAD

**Issue by arcogabbo** [nodemailer/nodemailer#1371]
Hi everyone, i tried for several hours checking on issues and internet articles but i can't seem to find a good solution.
The error is the following while trying to send a simple email:
```
Error: queryA EREFUSED smtp.office365.com
at QueryReqWrap.onresolve [as oncomplete] (dns.js:203:19) { 
errno: 'EREFUSED', 
code: 'EDNS',
syscall: 'queryA',
 hostname: 'smtp.office365.com',
command: 'CONN'
}
```

The same code works locally but not on a custom VPS/server. At first i checked my DNS settings and firewall and they were all fine.
After reading some issues i found one guy recommending a downgrade to version 4.7.0 .I did it and it worked, but i don't want to miss the newest updates and npm warns me of a critical vulnerability for versions before 6.6.0 . 

What can i do to prevent this error without changing email provider or nodemailer version?

**Comment by denniscm** [comment]
You were able to found the problem?

I'm getting the same error:

`{
    "code": "EDNS",
    "syscall": "queryA",
    "hostname": "smtps.telium.com.br",
    "command": "CONN"
}`

Even tried with Gmail and get the same error.

**Comment by migperezm** [comment]
{
    "error": {
        "code": "EDNS",
        "syscall": "queryA",
        "hostname": "smtp.gmail.com",
        "command": "CONN"
    }
}

i'm getting the same error when i trying to send mails from my production server ...

**Comment by Rashed360** [comment]
Error: Can not use IPv4 addresses with current network
    at GetAddrInfoReqWrap.callback (~\node_modules\nodemailer\lib\shared\index.js:217:35)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:132:8) {  
  code: 'EDNS',
  command: 'CONN'
}

Same error -_-

**Comment by BartaG512** [comment]
I am also gettings this: Error: Can not use IPv4 addresses with current network

What can we do? It seems. Only switching back from node 18.12.1 to node 16.15.0 helps
