### ISSUE TITLE
DSN Recipient gets ignored

### ISSUE THREAD

**Issue by KornKalle** [nodemailer/nodemailer#1374]
Setting a DSN Recipient gets ignored and the dsn is always sent to the original from address

Sample Code:
```
const nodemailer = require("nodemailer");

let transporter = nodemailer.createTransport({
    host: "localhost",
    port: 1025,
    secure: false, // upgrade later with STARTTLS
});

transporter.sendMail({
    from: 'anaddress@a.domain.net',
    to: 'anaddress@a.domain.net',
    subject: 'Test Receipt',
    text: 'Did you get a failure?',
    envelope: {
        dsn: {
            id: 'messageId',
            return: 'FULL',
            notify: ['failure', 'delay'],
            recipient: 'anotheraddress@a.domain.net',
        },
    },
}, (err, info) => {
    console.log(info.envelope);
    console.log(info.messageId);
});
```

**Comment by rangaraireddy** [comment]
@KornKalle Any update on this? I tried the same but never got a delivery notification to my from/recipient address. Also I am not sure if `envelope` exposes `dsn` object!? As per the documentation, we should just send it as part of the message but that ain't working for me either. I would appreciate some help on this. Thanks!

https://nodemailer.com/smtp/dsn/
