### ISSUE TITLE
Why am I getting req.body as the ternary operator?

### ISSUE THREAD

**Issue by Webdvpv** [nodemailer/nodemailer#1377]
I am using Express and bodyParser. I am getting this result when I submitted form.

`
[Object: null prototype] {
  '{"getName":"John","getSurname":"Doe","getEmail":"kod.aski@outlook.com","getSubject":"New Subject","getMessage":"asdasd","getIsHuman":true}': ''
}
`

Why does this result return as ternary operator? How can I reach the object?

**Comment by andris9** [comment]
That’s not a ternary operator, that’s a JSON string used as an object property key with an empty string as the value.

**Comment by Webdvpv** [comment]
Then why can't I get object values? For example, I'm trying req.body.getName but returns undefined.
