### ISSUE TITLE
Nodemailer doesn't raise an error for internationalized emails when the SMTP server doesn't support SMTPUTF8

### ISSUE THREAD

**Issue by GuillaumeBlanchet** [nodemailer/nodemailer#1378]
# Description

Emails having the local part with non-ASCII characters should not be sent if the remote SMTP server doesn't support the SMTPUTF8 extension. 

Currently, I found a workaround to check it:

```
    async support_SMTPUTF8() {
        let connection = new SMTPConnection(this.nodemailer_transporter.options);
        return new Promise(contains_SMTPUTF8 => {
            connection.connect(() => {
                // wrapper to access _supportedExtensions. Since the maintainers did not
                // make it public API, we cannot guarantee this name won't change in future
                // versions of nodemailer
                contains_SMTPUTF8(connection['_supportedExtensions'].includes('SMTPUTF8'));
                connection.close();
            });
        });
    }
```
but I would hope the "sendMail" function would raise an exception instead.

## Steps to reproduce

First start a mailhog fake SMTP server that doesn't support SMTPUTF8 on your host:

    $ docker run -d --net=host --name=mailhog mailhog/mailhog

Then start a docker with node on your host too (to enable communication with mailhog):

    $ docker run -i -t --net=host node:17.5 bash

Install nodemailer and go in the interactive node console 

    # npm install -g nodemailer
    # node -i
    >  let info = await require("nodemailer").createTransport({
    ...     host: "localhost",
    ...     port: 1025,
    ...     secure: false
    ...   }).sendMail({
    ...     from: 'test@test.com',
    ...     to: "éai@îdn.tld", // internationalized email
    ...     subject: "Hello ✔", // Subject line
    ...     text: "Hello world?", // plain text body
    ...     html: "<b>Hello world?</b>", // html body
    ...   });
    > info
    {
        accepted: [ 'éai@xn--dn-pja.tld' ],
        rejected: [],
        envelopeTime: 3,
        messageTime: 5,
        messageSize: 580,
        response: '250 Ok: queued as ey2_c8nI2eTAk0he_kRj0vdOvWubof3qzGduf8wchzA=@mailhog.example',
        envelope: { from: 'test@test.com', to: [ 'éai@xn--dn-pja.tld' ] },
        messageId: '<078682e8-8ec5-d97e-52ad-0be082e351d4@test.com>'
    }

Or something alike... However if we inspect the logs of mailhog:

     $ docker logs mailhog

We see that STMPUTF8 extension was not exchanged.

I would expect at least to have a public API for that exposing '_supportedExtensions' field or raise an exception during the sending of the email. 

Thanks a lot

**Comment by GuillaumeBlanchet** [comment]
Reopening a new bug since no answer has been provided:
https://github.com/nodemailer/nodemailer/issues/1462

**Comment by andris9** [comment]
There are a lot of non-standard servers that accept unicode addresses without the extension. At this point, if Nodemailer would throw an error in such cases, it would generate more problems than the current behavior where Nodemailer tries to use such an address even if the server does not officially support it.

**Comment by GuillaumeBlanchet** [comment]
Since we know when the user use an internationalized email address (since the lib use punycode), we should verify it only if the email is an internalized email address. We could thus support both cases without compromising anything
