### ISSUE TITLE
Nodemailer Webpack v5 Polyfill Error Fix Needed

### ISSUE THREAD

**Issue by CynthiaBlue** [nodemailer/nodemailer#1380]
I am running an application in Quasar/Electron and am trying to use Nodemailer.  However, there is apparently a change with Webpack v5 has a breaking change and polyfills have been removed.  Therefore, trying to access Nodemailer will throw errors.  

[https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed](https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed)

Is there anything in the works to address these in Nodemailer?

**Comment by Suhaib-Ersan** [comment]
I'm facing the same problem, did you ever find any work around?

**Comment by Jerunnon** [comment]
Got the same problem. You could install all polyfills via npm or yarn and add them to you webpack.config like so:
`resolve: [
    fallback: {
        os: require.resolve('os-browserify/browser'),
        ...
      }
]`

for details, see here: https://webpack.js.org/configuration/resolve/#resolvefallback

Or you can install a npm package for polyfills: https://www.npmjs.com/package/node-polyfill-webpack-plugin. This actually solves most of the errors. Sometimes you have to manually install the needed package. You can do that with the solution above.

But a fix would be very nice.
