### ISSUE TITLE
Not able to view base64 image in html body template in Node.js using nodemailer

### ISSUE THREAD

**Issue by SameerChorge94** [nodemailer/nodemailer#1383]
I have nodejs request which need to embed the image base 64 string in the email html template body using nodemailer

as per the documentation 
https://nodemailer.com/message/embedded-images/#example
```
let message = {
    html: 'Embedded image: <img src="cid:unique@nodemailer.com" alt="Red dot"/>',
    attachments: [{
        filename: 'image.png',
         content:'data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==',
        cid: 'unique@nodemailer.com' //same cid value as in the html img src
    }]
}
```
I tried sending the base64 attachment to nodemailer and htmlbody with image tag and it's cid,

but it shows broken image after receiving mail  
![image](https://user-images.githubusercontent.com/55871576/156164396-762207bc-af71-4d4a-9ec6-1cdcd92f6085.png)

but if i tried same with the, image URL then its that image showing properly in received mail  
```
let message = {
    html: 'Embedded image: <img src="cid:unique@nodemailer.com" alt="Red dot"/>',
    attachments: [{
        filename: 'image.png',
        href:  "https://upload.wikimedia.org/wikipedia/commons/5/57/Cumulus_Clouds_over_Yellow_Prairie2.jpg",
        cid: 'unique@nodemailer.com' //same cid value as in the html img src
    }]
}
```
![image](https://user-images.githubusercontent.com/55871576/156164517-0bdca7df-0d17-475d-80a1-a3d210d7d063.png)

Is there any workaround to handle same or any other syntactical changes needed to display base64 string?

**Comment by SameerChorge94** [comment]
Able to send the mail with base64 embedded image in Html template 

Inside attachments just need to **send** the base64 **in path variable instead of content** and with cid 
```
 "attachments":  [{
        "filename": "image.png",
         "path":"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==",
        "cid": "unique@nodemailer.com"
    }]
```
> Screenshot of embedded image in mail content:
![image](https://user-images.githubusercontent.com/55871576/156313064-e107e97e-abf6-49ad-be35-7ecee89b2fa6.png)

**Comment by Webdragon0125** [comment]
Hi,

> Inside attachments just need to **send** the base64 **in path variable instead of content** and with cid

It means if I dont need to pass cid inside attachments?
but you passed it. If I am wrong, plz kindly let me know
Thanks in advance

**Comment by nbouvrette** [comment]
I know this is old but this would be the correct way to do this:

```ts
attachments: [
      {
        cid: imageCid,
        filename: 'my-image.png',
        content: Buffer.from(imageBase64Content, 'base64'),
        contentDisposition: 'inline',
      },
    ],
```

You can use the `content` property and pass in a `Buffer`
