### ISSUE TITLE
Error: Unexpected socket close

### ISSUE THREAD

**Issue by decoderid** [nodemailer/nodemailer#1385]
I use adonis.js but got Error like this, even i use mailgun, mailtrap, gmail and still same.

```json
{
    "host": "smtp.ethereal.email",
    "port": 587,
    "auth": {
        "user": "username",
        "pass": "password"
    }
}
```

Always error when sending email

```
Error: Unexpected socket close
    at Timeout._onTimeout (E:\app\node_modules\nodemailer\lib\smtp-transport\index.js:189:31)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
undefined
```
**package-lock.json**
```json
{
"nodemailer": "^6.7.2"
}
```

#1261 this problem not resolved

**Comment by AdolfMacro** [comment]
Connection may fail. A firewall or antivirus might block the connection.

Connect to SMTP server with a TCP connection and see what happens

**Comment by decoderid** [comment]
> Connection may fail. A firewall or antivirus might block the connection.
> 
> Connect to SMTP server with a TCP connection and see what happens

nah, its **adonis** config mail problem. it doesn't update **.env** file
