### ISSUE TITLE
Outlook OAuth 2.0 SSL Error

### ISSUE THREAD

**Issue by giacomobartoli** [nodemailer/nodemailer#1390]
I am using Azure api to obtain the token, given tenant ID, client ID and secret (I am not providing the full code but I can clearly print the token).
After that, I create a transporter this way:

```
let transporter = nodemailer.createTransport({
        host: 'smtp.office365.com',
        port: 587,
        secure: true,
        auth: {
            type: 'OAuth2',
            user: 'MY_USER',
            accessToken: response.accessToken //this is the oauth token
        },
        tls: {
            ciphers:'SSLv3'
        }
    });
```
Then:

```
const mailOptions = {
        from: "user@domain.it",
        envelope: {
            from: 'USER <user@domain.it>',
            to: name.surname@domain.it,
        },
        subject: 'This is a test email',
        text: 'This is a test email!'
      };
let info = await transporter.sendMail(mailOptions)
```
The sendMail function throws an error:
`{"library":"SSL routines","function":"ssl3_get_record","reason":"wrong version number","code":"ESOCKET","command":"CONN"}
`
Already tried by changing the parameters into the transporter object but I get unsuccessful login.

**Comment by alblandino** [comment]
This error occurs when there is a misconfiguration in the parameters when created the transport.

If you are going to use TLS, the port should be 587 but you should disable the "secure" parameter and set it to false, if instead, you want to use SSL as a validation method then you should use 465 with the "secure" parameter set to true.

#### TLS (port 587):
````javascript
let transporter = nodemailer.createTransport({
        host: 'smtp.office365.com',
        port: 587,
        secure: false,
        auth: {
            type: 'OAuth2',
            user: 'MY_USER',
            accessToken: response.accessToken //this is the oauth token
        }
});
````

#### SSL (port 465):
````javascript
let transporter = nodemailer.createTransport({
        host: 'smtp.office365.com',
        port: 465,
        secure: true,
        auth: {
            type: 'OAuth2',
            user: 'MY_USER',
            accessToken: response.accessToken //this is the oauth token
        },
        tls: {
            ciphers:'SSLv3'
        }
});
````

**Comment by giacomobartoli** [comment]
@alblandino thanks for the support.
I tried with the first configuration, the one with port 587 and secure = false.

The error changes:
`{"code":"EAUTH","response":"535 5.7.3 Authentication unsuccessful [ZR0P278CA0080.CHEP278.PROD.OUTLOOK.COM]","responseCode":535,"command":"AUTH XOAUTH2"}`

However, this is strange since I can clearly see the token I am using. Do you think has something to do with the mail configuration?

**Comment by NaveenBen** [comment]
having the same issue when using OAuth AccessToken Implementation. Any Solution?

**Comment by giacomobartoli** [comment]
@NaveenBen I solved by using directly the Azure SDK.

**Comment by NaveenBen** [comment]
if possible could you share the resources or examples?

**Comment by giacomobartoli** [comment]
@NaveenBen essentially who is in charge of the Azure Cloud administration must created an associated app. Once this is done, a client id and client secret is given so that you can use it to send emails (using Oauth 2.0) through the Azure SDK.

Here's the reference:
https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?view=graph-rest-1.0&tabs=CS#on-behalf-of-provider

**Comment by dgtllion** [comment]
Hi all,

After long time discovering how to send an email from your server with OAuth2, I end up with this working example.

1. Create an app https://go.microsoft.com/fwlink/?linkid=2083908
2. Add permissions in {Your APP admin panel} > API permissions > Add permission > Microsoft Graph > Application permissions > Mail.Send > Add permissions
3. Create certificate to get client secret {Your APP admin panel} > Certificates & secrets > Client secrets > New client secret (Save the "Value" string somewhere this is your client_secret)
4. Make sure you have installed required node apps
5. Now you can run this code to send any email from your server:

```
   const msal = require('@azure/msal-node');
   const fetch = require('node-fetch');

    const msalConfig = {
      auth: {
        clientId,
        clientSecret,
        authority: aadEndpoint + '/' + tenantId,
      },
    };

    const tokenRequest = {
      scopes: [graphEndpoint + '/.default'],
    };

    const cca = new msal.ConfidentialClientApplication(msalConfig);
    const tokenInfo = await cca.acquireTokenByClientCredential(tokenRequest);

    const mail = {
      subject: 'Microsoft Graph JavaScript Sample',
      //This "from" is optional if you want to send from group email. For this you need to give permissions in that group to send emails from it.
      from: {
        emailAddress: {
          address: 'noreply@company.com',
        },
      },
      toRecipients: [
        {
          emailAddress: {
            address: 'someemail@domain.com',
          },
        },
      ],
      body: {
        content:
          '<h1>MicrosoftGraph JavaScript Sample</h1>This is the email body',
        contentType: 'html',
      },
    };

    const headers = new fetch.Headers();
    const bearer = `Bearer ${tokenInfo.accessToken}`;

    headers.append('Authorization', bearer);
    headers.append('Content-Type', 'application/json');

    const options = {
      method: 'POST',
      headers,
      body: JSON.stringify({ message: mail, saveToSentItems: false }),
    };

    await fetch(
      graphEndpoint + '/v1.0/users/youroutlookemail@company.com/sendMail',
      options
    );
```

Have fun ;)
