### ISSUE TITLE
Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by Losh531** [nodemailer/nodemailer#1391]
Please file only bugs here. Support and feature requests might get closed without a response.
Hello! Here is my transporter:
`const transporter = nodemailer.createTransport({
  pool: false,
  host: "mail.botden.cf",
  port: 25,
  secure: false, // use TLS
  auth: {
    user: process.env.MAIL_USERNAME,
    pass: process.env.MAIL_PASSWORD,
  },
});
`
I just try to send one email and I get:
Hostname/IP does not match certificate's altnames: Host: mail.botden.cf. is not in the cert's altnames: DNS:botden.cf, DNS:www.botden.cf
My mail server runs on postfix.
Hope someone can help!

**Comment by patchlog** [comment]
It looks like your email server is using the same certification you use on the web site. If the web server and email server are both running on the same machine (same ip) you can just use host: botden.cf instead of host: mail.botden.cf in the transport configuration
