### ISSUE TITLE
Typescript Failing to createTransport with dotenv variables

### ISSUE THREAD

**Issue by jared-leddy** [nodemailer/nodemailer#1392]
Raw transport works, but using process.env variables doesn't. I've included an image below of the console error received. For reference, Typescript has already been configured to work with dotenv/process.env variables, and they work in other areas of the project. These are the only ones throwing an error. 

```js
// NOT WORKING
return nodemailer.createTransport({
host: process.env.EMAIL_HOST,
port: process.env.EMAIL_PORT,
auth: {
user: process.env.EMAIL_USERNAME,
pass: process.env.EMAIL_PASSWORD
}
});
// WORKING
return nodemailer.createTransport({
host: 'smtp.mailtrap.io',
port: 2525,
auth: {
user: '5d9266c2853eb3',
pass: '8d8f81df86f16b'
}
});
```

**Comment by jared-leddy** [comment]
Waiting on you guys to review.

**Comment by jared-leddy** [comment]
Still waiting on the @nodemailer team to work this.

**Comment by jared-leddy** [comment]
Still waiting on the @nodemailer team to work this.

**Comment by andris9** [comment]
Typescript is not supported by Nodemailer. What you probably are doing wrong is that you try to use a string variable as the port number, that is supposed to be an integer.
