### ISSUE TITLE
from: `${req.body.email}` not working with all domains.

### ISSUE THREAD

**Issue by acjintrodesigns** [nodemailer/nodemailer#1395]
only some domains will send the email through with the ${req.body.email} in the " from:" section like the below
let mailOptions = {
    from: `${req.body.email`, // sender address
    to: 'info@acjintrodesigns.com, ', // list of receivers'
    subject: `${req.body.subject} Contact Inquiry`, // Subject line
    text: 'Contact Request ', // plain text body
    html: output, // html body
  }

but when i change it to the below , then it works and all domains are accepted and email is sent:

let mailOptions = {
    from: 'test form <info@test.com>', // sender address
    to: 'info@test.com, ', // list of receivers'
    subject: `${req.body.subject} Contact Inquiry`, // Subject line
    text: 'Contact Request ', // plain text body
    html: output, // html body
  }

**Comment by micalevisk** [comment]
we don't know what's the value of that `req.body.email`

**Comment by micalevisk** [comment]
can you proof to us that the value of that `req.body.email` is a valid email address? it could by literally anything. Share screenshots, or some project and steps to reproduce your issue, idk
