### ISSUE TITLE
Nodejs 17.8 TLS

### ISSUE THREAD

**Issue by reangeline** [nodemailer/nodemailer#1399]
Nodemailer does't work with nodejs 17.8.

    const transporter = nodemailer.createTransport({
      host: 'smtp.com',
      pool: true,
      port: 25,
      secure: false,
      auth: {
        user: 'user',
        pass: 'pass',
      },
      tls: {
        rejectUnauthorized: false,
      },
    })

Error messange: Error: Client network socket disconnected before secure TLS connection was established

When I was using nodejs 16 it worked without problem.

**Comment by grit96** [comment]
@reangeline did you find any solution for this on node 17/18?

**Comment by reangeline** [comment]
@grit96 No. I used nvs with version 16.9 for this application. However, I will migrate my apps to golang.

**Comment by powerpuffboys2022** [comment]
It works fine on localhost, but when deployed in Vercel, netlify and other hosting platforms, this happens. :cry:

**Comment by 91labs** [comment]
@powerpuffboys2022  Any workaround on this. I'm using netlify

**Comment by tiYusupov** [comment]
Worked for me on Node 18.19.1:

```
tls: {
  rejectUnauthorized: false,
  ciphers: 'DEFAULT@SECLEVEL=0'
},
```
