### ISSUE TITLE
How can i create mail server to send and recive mails?

### ISSUE THREAD

**Issue by abdooo9** [nodemailer/nodemailer#1404]
Hello friends, I have always wished to have my own domain and my own mail that has nothing to do with [`gmail`](https://gmaill.com) or [`hotmail`](https://hotmail.com), etc.

I bought a domain several months ago, and ran my website on it, but I still need a mail for my website such as: `support@domain.com`, I have tried several things, like [`iredmail`](https://www.iredmail.org/), [`postfix`](https://www.postfix.org/) and others, all of these didn't work for me.

I knew I like nodejs more than anything, so I'm going to build a mail server using nodejs, is there any way I can set up a mail server using [`nodemailer`](https://nodemailer.com/)?

**Comment by WillianAgostini** [comment]
Hi @abdooo9, 
maybe this [https://nodemailer.com/extras/smtp-server/](smtp-server) can be useful.
