### ISSUE TITLE
createTestAccount() method hangs

### ISSUE THREAD

**Issue by GeorgianStan** [nodemailer/nodemailer#1406]
Since 3 May the method `createTestAccount` hangs without completion.

```
import nodemailer from "nodemailer";

const acc = await nodemailer.createTestAccount();
```

Package version: **^6.7.2**

**Comment by kiftio** [comment]
It looks like ethereal.email has been down for a while https://www.saashub.com/ethereal-email-status

**Comment by gcelma** [comment]
We are having timeout issues when trying to connect to imap.ethereal.email since 2 weeks now, no problems before. Will the service be available again or we should look for an alternative? We use it for integration testing purposes.

Nevertheless, big up for the maintainers, super handy packages 🤘

**Comment by andris9** [comment]
I rebooted the server, and it should work again.

**Comment by gcelma** [comment]
Thanks @andris9 ! Btw, is it normal that we still get a Timeout?
![Captura de pantalla 2022-05-04 a las 12 36 29](https://user-images.githubusercontent.com/37138424/166666102-20aaa87a-0eec-48a9-9d90-554d9f5a9a33.png)

**Comment by GeorgianStan** [comment]
It seems that the connection is now successful. If there are no other issues with this, you can close this issue.

**Comment by leungkinghin** [comment]
I attempted to get testing account and credentials by `nodemailer.createTestAccount()`, and then make connection to POP3 with `yapople` v0.4.8. It works all the time until last week. Now it always throws timeout error as below
```
Error: connect ETIMEDOUT 54.36.85.113:995
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.36.85.113',
  port: 995,
  uncaught: true
}
```

It also fails when i execute command` telent pop3.ethereal.email 995`

**Comment by andris9** [comment]
IMAP and POP3 ports are now unblocked
