### ISSUE TITLE
Fail to connect to POP3 server

### ISSUE THREAD

**Issue by leungkinghin** [nodemailer/nodemailer#1414]
I attempted to get testing account and credentials by `nodemailer.createTestAccount()`, and then make connection to POP3 with `yapople` v0.4.8. It works all the time until last week. Now it always throws timeout error as below
```
Error: connect ETIMEDOUT 54.36.85.113:995
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.36.85.113',
  port: 995,
  uncaught: true
}
```

It also fails when i execute command` telent pop3.ethereal.email 995`

**Comment by andris9** [comment]
IMAP and POP3 ports are now unblocked
