### ISSUE TITLE
Issue for queued emails

### ISSUE THREAD

**Issue by iftikharkhan90** [nodemailer/nodemailer#1415]
Hi, 
I am using nodemailer in my node project. node mailer return the status Ok but does not send the email 

its response is "**250 2.0.0 Ok: queued as E8ABB3AD5C**"

i am sending email to **james_bond@resiroc.net**  resiroc.net is valid domain and i am receiving emails from gmail.com correctly 

using following host and port in code 

`name: 'email.active24.com',
	host: 'email.active24.com',
	port: 465,`
	
can anyone please guide me how may i solve this issue 

Note: i am getting emails on Gmail account but not resiroc.net domain accounts

Regards !

**Comment by andris9** [comment]
Nodemailer works as intended. Check how the email is handled by your SMTP server.

**Comment by iftikharkhan90** [comment]
Thanks I'll contact with them 

Regards !
