### ISSUE TITLE
error nodemailer use OS

### ISSUE THREAD

**Issue by julientype** [nodemailer/nodemailer#1418]
On shared hosting the OS module is not available in the run time its on a different server running ports ...
it did work in older version....

"nodemailer": "^6.6.0"

maybe you can add just a config switch with with dummy data....

**Comment by andris9** [comment]
Nodemailer supports standard Node.js and the os module is always present. You might be using a non-standard environment like Cloudflare workers etc what are not uspported.

**Comment by julientype** [comment]
It's on a shared web hosting....
What they is assign aport to the app.js
I ask the admin about to see we can pass the OS object and they can't...   It's runtime is on different IP.  It's just the the way they set it up....
Like I said it did work on the old version.... 

I under stand OS is stander object but when ask for info off the OS object you get a blank and throws an error....     

I do have the server console log. 
 On VPN server box I get full control of inode install where I can get the OS object....

Next week all be working online with good connection  and will show you the return error...

It would be nice to fake it  with env variable file...

**Comment by julientype** [comment]
Like how mush does node mail use the OS object?
If it's just a variable I could modify your code ....
ENV.  File is the best where you check for what you need or ask the OS object....
I simply load the ENV before your nodemail and will retain the variables you need just like an OS object...   Not sure but your the only good mail object for node....
