### ISSUE TITLE
Non domain aliases are not supported due to adriss validator

### ISSUE THREAD

**Issue by Protocol-X** [nodemailer/nodemailer#1420]
This isn't really a bug, but more of a limitation due to the address parser.

My company sends their emails primarily using ad aliases and not addresses.  The mail server translates the alias to an @domain.com address. 

This package will not allow you to send emails to any non xxx@domain.com.

Is there a work around or future plans to add a flag or option to skip the address validation? 

I was able to edit the code in many places just to make it work and validate, but it was a lot of work and very hacky.

All of our aliases are only a name and no @domain.com.

**Comment by andris9** [comment]
No plans to support such addresses
