### ISSUE TITLE
Nodemailer not working (Invalid login: 535-5.7.8)

### ISSUE THREAD

**Issue by Unixcision** [nodemailer/nodemailer#1421]
Hi!
Due to the recent Google update, they are not allowing unsecure applications to connect to GMail accounts. For that reason nodemailer is no longer working. Could you please update the repository to add the new authentication system? 

https://support.google.com/accounts/answer/6010255?hl=en

```
To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use 
of third-party apps or devices which ask you to sign in to your Google Account using only 
your username and password.

Important: This deadline does not apply to Google Workspace or Google Cloud Identity 
customers. The enforcement date for these customers will be announced on the Workspace 
blog at a later date.

For more information, continue to read.
```

Thanks.

**Comment by adityakumar48** [comment]
+1

**Comment by ChaymaBENBRAHIM** [comment]
+1

**Comment by andris9** [comment]
Nodemailer already supports all posaible authentication methods for Google. For example, see the docs for using OAuth: https://nodemailer.com/smtp/oauth2/

**Comment by ProDev4U** [comment]
hi

So Did u solve this issue?

If so could u kindly send method to paishaiming995@gmail.com?
