### ISSUE TITLE
read ECONNRESET at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)

### ISSUE THREAD

**Issue by snells92** [nodemailer/nodemailer#1423]
I am trying to send email using below configuration but I am getting "read ECONNRESET at TLSWrap.onStreamRead " error while sending the email from nodejs application.
But at the same time the openssl command can send the email from linux terminal from the server where the application is installed.

Here's the openssl command which can send the email,
openssl s_client -crlf -quiet -starttls smtp -connect email-smtp.eu-west-1.amazonaws.com:587 < mailinput.txt

Here's the code snippet,
`let transporter = nodemailer.createTransport({
    host: "email-smtp.eu-west-1.amazonaws.com",
    port: 587,
    secure: false,
    auth: {
        user: "companyuser",
        pass: "####"
    },
    logger: true,
    requireTLS: true
});

var mailOptions = {
    from: "email@companydomain.com",
    to: 'receiver@gmail.com',
    subject: 'Test Email',
    text: "Test Message"
};

transporter.sendMail(mailOptions, function (error, info) {
    if (error) {
        console.log(error);
        reject(error);
    } else {
        console.log(`Test email sent`);
        resolve(info.response);
    }
});`

and here's the error,
`DEBUG [rirUyJIsdaQ] Resolved email-smtp.eu-west-1.amazonaws.com as ##.###.###.## [cache miss]`
`ERROR [rirUyJIsdaQ] read ECONNRESET`
`DEBUG [rirUyJIsdaQ] Closing connection to the server using "destroy"`
`transporter.verify error: Error: read ECONNRESET`
`at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {`
`errno: 'ECONNRESET',`
`code: 'ESOCKET',`
`syscall: 'read',`
`command: 'CONN'`
`}`

**Comment by andris9** [comment]
The error is coming from `transporter.verify`, not `transporter.sendMail`. Your code is doing something fishy.
