### ISSUE TITLE
google security setting

### ISSUE THREAD

**Issue by alihamad96** [nodemailer/nodemailer#1424]
As I know we should enable less secured apps access to use gmail, yet google disabled this setting at the end of May. Any idea on how this issue could be solved

**Comment by matheusloures** [comment]
1. Go to https://myaccount.google.com/security
2. Enable 2FA
3. Create App Password for Email
4. Copy that password (16 characters) into the pass parameter in Nodemailer auth.

```
...,
  auth: {
    user: 'yourmail@gmail.com', 
    pass: 'your_new_app_password', 
  },
...
```

Hope it helps.

**Comment by alihamad96** [comment]
Thank you!! it worked

**Comment by krupalimakadiya** [comment]
@matheusloures  
Thank you!. It's working for me

**Comment by abias1122** [comment]
I tried following the instructions from @matheusloures and I'm still running into issues. I'm currently setting up my transporter like so:
```javascript
transporter = nodemailer.createTransport({
	service: 'gmail',
	auth: {
		user: process.env.FROM_EMAIL,
		pass: process.env.EMAIL_PASSWORD
	}
});
```

`FROM_EMAIL` is the address of an account I setup 2FA and created an app password for, and `EMAIL_PASSWORD` is the 16 character password that google generates.

I try to send my email like this:
```javascript
transporter.sendMail(
	{
		from: `"From Address" <${process.env.FROM_EMAIL}>`,
		to: email,
		subject: 'Subject',
		html: renderEmailHtml()
	},
	(error, info) => {
		console.log(
			`Attempted to send to ${process.env.FROM_EMAIL} with password ${process.env.EMAIL_PASSWORD}`
		);
		if (error) {
			console.error('Error sending email');
			console.error(error);
		} else {
			console.info('email sent: ' + info);
		}
	}
);
```

When I try to send an email, I  get the following error:
```
Error sending email
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:526:28)
    at TLSSocket.emit (node:domain:475:12)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'ESOCKET',
  command: 'CONN'
```

Does anyone know how to fix this self signed certificate issue when sending from gmail?

**Comment by ValienX1** [comment]
> 1. Go to https://myaccount.google.com/security
> 2. Enable 2FA
> 3. Create App Password for Email
> 4. Copy that password (16 characters) into the pass parameter in Nodemailer auth.
> 
> ```
> ...,
>   auth: {
>     user: 'yourmail@gmail.com', 
>     pass: 'your_new_app_password', 
>   },
> ...
> ```
> 
> Hope it helps.

April 2023. App password working when i develop app and try to send email from contact form noe js on localhost. But with the same code but when app is launched from google compute engine i get invalid credentials error. Anyone know a solution for this?
