### ISSUE TITLE
Can't Send from Gmail: Self Signed Certificate in certificate chain

### ISSUE THREAD

**Issue by abias1122** [nodemailer/nodemailer#1429]
I tried following the instructions from @matheusloures and I'm still running into issues. I'm currently setting up my transporter like so:
```javascript
transporter = nodemailer.createTransport({
	service: 'gmail',
	auth: {
		user: process.env.FROM_EMAIL,
		pass: process.env.EMAIL_PASSWORD
	}
});
```

`FROM_EMAIL` is the address of an account I setup 2FA and created an app password for, and `EMAIL_PASSWORD` is the 16 character password that google generates.

I try to send my email like this:
```javascript
transporter.sendMail(
	{
		from: `"From Address" <${process.env.FROM_EMAIL}>`,
		to: email,
		subject: 'Subject',
		html: renderEmailHtml()
	},
	(error, info) => {
		console.log(
			`Attempted to send to ${process.env.FROM_EMAIL} with password ${process.env.EMAIL_PASSWORD}`
		);
		if (error) {
			console.error('Error sending email');
			console.error(error);
		} else {
			console.info('email sent: ' + info);
		}
	}
);
```

When I try to send an email, I  get the following error:
```
Error sending email
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:526:28)
    at TLSSocket.emit (node:domain:475:12)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'ESOCKET',
  command: 'CONN'
```

Does anyone know how to fix this self signed certificate issue when sending from gmail?

_Originally posted by @abias1122 in https://github.com/nodemailer/nodemailer/issues/1424#issuecomment-1163063675_

**Comment by abias1122** [comment]
I managed to get the email to send properly by setting the following on the object passed to `createTransport`:
```
tls: {
	rejectUnauthorized: false
}
```

**Comment by matheshyogeswaran** [comment]
> 

it's working for me also

**Comment by ahusicic1** [comment]
what about the app security when setting rejectUnauthorized to false?

**Comment by fernando-lopez** [comment]
Anyone knows why this is happening from time to time? 

I would like to have a better solution than disabling tls when error

**Comment by andris9** [comment]
If you get certificate errors when connecting to Gmail, then the reason usually is that you run Nodemailer locally, and you have an antivirus installed that acts as an MITM to scan sent emails. Nodemailer does not accept the certificate provided by antivirus as a valid one.

**Comment by fernando-lopez** [comment]
In our case, antivirus makes no sense becasue nodemailer.createTransport is used in Google Cloud Run in containers. That's weird. It has been working for months till this issue appears.

**Comment by HarrisonKeeling** [comment]
Popped up today for us, skipping TLS rejection is not an option

**Comment by andris9** [comment]
In any case, this is mit an issue of Nodemailer. Root certificates are managed by Node, so if, for example Gmail uses a newer certificate you might need to check if your Node version is also up to date. Older Node versions contain old root certificates that might not apply anymore.

**Comment by HarrisonKeeling** [comment]
Yeah forgot about that... sadly latest node 18 (LTS) is only on NSS 3.95 which released on 11/16/2023 and I suppose that's too outdated still.

**Comment by watadarkstar** [comment]
Started popping up for me too. Skipping TLS rejection is not an option. Anyone have another solution?

**Comment by rayArternal** [comment]
Never had this issue before, but it started popping up today a couple of hours ago.

**Comment by luiszaelot** [comment]
We're facing same situation on GCP since March 14th. It randomly fails with the same error.
NodeJS 18 LTS

**Comment by miradnan** [comment]
Adding servername to tls config resolves the issue.

```
tls: {
        servername: 'smtp.gmail.com',
      },
```

**Comment by shodanreturned** [comment]
> Adding servername to tls config resolves the issue.
> 
> ```
> tls: {
>         servername: 'smtp.gmail.com',
>       },
> ```

@miradnan : Not working for me
Have you made any other configuration changes?

**Comment by HarrisonKeeling** [comment]
Did a little digging, looks like there's no ssl cert for `smtp-relay.gmail.com`'s 587 port but there is on 456... hmm

**Comment by miradnan** [comment]
@HarrisonKeeling - Below is the config thats working for me.

```
transporter = nodemailer.createTransport({
      pool: true,
      host: 'smtp.gmail.com',
      port: 465,
      secure: true,
      tls: {
        servername: 'smtp.gmail.com',
      },
});
```

**Comment by HarrisonKeeling** [comment]
Just swapping to their ssl port (456) instead of their tls port (587) resolved the errors for me.  My guess is someone at google flubbed up today

**Comment by natoszme** [comment]
Hi there! Same issue here since today at aprox 13 UTC-3. This worked for me, thanks!

> @HarrisonKeeling - Below is the config thats working for me.
> 
> ```
> transporter = nodemailer.createTransport({
>       pool: true,
>       host: 'smtp.gmail.com',
>       port: 465,
>       secure: true,
>       tls: {
>         servername: 'smtp.gmail.com',
>       },
> });
> ```
> 
> Here is the link I followed: https://support.google.com/a/answer/6180220?hl=en

**Comment by muddledluck** [comment]
> Hi there! Same issue here since today at aprox 13 UTC-3. This worked for me, thanks!
> 
> > @HarrisonKeeling - Below is the config thats working for me.
> > ```
> > transporter = nodemailer.createTransport({
> >       pool: true,
> >       host: 'smtp.gmail.com',
> >       port: 465,
> >       secure: true,
> >       tls: {
> >         servername: 'smtp.gmail.com',
> >       },
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here is the link I followed: https://support.google.com/a/answer/6180220?hl=en

Worked for me, thanks :)

**Comment by JayPe69** [comment]
Same problem here ...

**Comment by andris9** [comment]
The current issue seems to depend on where you land with DNS when connecting to smtp.gmail.com (based on geographical region, etc, you might be routed to a different server for the same hostname). You might be routed to a server with a TLS certificate for smtp.gmail.com, and in this case, everything works correctly. You might also end up in a server that _only_ works with SNI, and the common name of the certificate is something else than smtp.gmail.com, for example `invalid2.invalid` and in this case you need the `tls.servername` option to be set to trigger SNI. https://github.com/nodemailer/nodemailer/issues/1429#issuecomment-2007914658

**Comment by MMoizAlvi** [comment]
Same issue even my transporter instance is something like below, I am not using **localSMTP** settings for the transporter instance configuration.

```
transporter = nodemailer.createTransport({
      pool: true,
      maxConnections: 1
      from: 'process.env.FROM_EMAIL,
      service: 'gmail',
	auth: {
		user: process.env.FROM_EMAIL,
		pass: process.env.EMAIL_PASSWORD
	}
});
```

****POV:** Disabling TLS rejection is not an good option plus no AV process running**
