### ISSUE TITLE
Error NoAuth despite smtp-server disabled auth

### ISSUE THREAD

**Issue by BlitzInternet** [nodemailer/nodemailer#1435]
Problem started happening after the upgrade `"6.6.2"` -> `"6.7.6"`

For testing purposes I have a smtp-server running like this:
```js
new SMTPServer({
	authOptional: true,
	secure: false,
	banner: 'test server welcome',
	disableCommands: ['AUTH', 'STARTTLS'],
	authMethods: [],
	logger: false,
```
Listening on localhost:1025

I'm trying to create a transport like this:
```
{
			host: mxRecord,
			port: SMTP_PORT,
			tls: {
				rejectUnauthorized: false
			}
		}
```
Which always worked but now throws this:
```
 message: 'Authentication info was not provided',
    code: 'NoAuth'
```

However, if I initialize with any auth, like this:
```
{
			host: mxRecord,
			port: SMTP_PORT,
			auth: {
				user: 'test',
				pass: 'secure'
			},
			tls: {
				rejectUnauthorized: false
			}
		}
```
it notices correctly that the server does not support auth and instead throws a:
```
    message: 'Invalid login: 535 Authentication not implemented',
    code: 'EAUTH',
    response: '535 Authentication not implemented',
    responseCode: 535,
    command: 'AUTH PLAIN'
```

I can't go back to the old version, since we upgraded to node v18 and v6.6.2 seems incompatible with that.

**Comment by andris9** [comment]
Do you call the `transport.verify()` method instead of `transport.sendMail()`? You should only get that response for a `verify()` call without credentials against a server that has authentication enabled.

**Comment by BlitzInternet** [comment]
yes, `await transporter.verify();` is always called right after createTransport.
this code has been in production for at least a year now, so the old version worked fine, and I didn't change anything but upgrade the lib today.

**Comment by andris9** [comment]
The old `verify()` implementation failed to detect server configurations where you do not provide credentials but the server requires authentication. This was a bug. Obviously, you might end up in a reverse situation like in your case, where you want to verify connection settings against a server that advertises authentication but you do not want to use any credentials.

**Comment by BlitzInternet** [comment]
since you're also the maintainer of smtp-server:
did something change in smtp-server between 3.9.0 and 3.11.0 in how a server without auth is initialized? because that past has also stayed the same. and unless there's another bug how in auth detection, that's the only thing I can think off.

**Comment by sumanth17** [comment]
Facing same issue when doing verify, Is there a way to overcome this ? Also this change should have been a major version if its breaking change, It took good amount of time to figure out what went wrong suddenly as everything was working fine until now.

**Comment by rafipiccolo** [comment]
transporter.verify is now throwing an error when auth is possible on the server (even if auth is optional).
the smtp server may still work without needing auth.
imho verify has become a bit pedantic : i don't know if it's more a fixed bug or a breaking change.

i too, wanted to have a public smtp server. i dont really care about auth, because i want other smtpservers (gmail/ovh/etc) to send me emails, but i didnt find an option for it.
To make it clear, i configured the smtpserver to tell the client that it doesn't want to use auth.
Now this works for me :


```
import nodemailer from 'nodemailer';
import smtpserver from 'smtp-server';
const SMTPServer = smtpserver.SMTPServer;

// the server
const server = new SMTPServer({
    authOptional: true,
    // i added this line
    disabledCommands: ['AUTH'],
    onConnect(session, callback) {
        ....
    },
    onData: async function (stream, session, callback) {
        ...
    })
});
server.listen(25, () => {
    console.log('listen on :25');
});

// the test
const transporter = nodemailer.createTransport({
    host: 'localhost',
    port: 25,
    secure: false,
    ignoreTLS: true,
    tls: {
        rejectUnauthorized: false
    }
});

const success = await transporter.verify();
assert.equal(success, 1);
```
