### ISSUE TITLE
Allow internal network interfaces in host resolution

### ISSUE THREAD

**Issue by marschro** [nodemailer/nodemailer#1437]
BACKGROUND:

- sometimes, virtualized servers or environments, make use of common network interfaces (i.e. FreeBSD jails), provided by the hosting system.
- it is common, to use a cloned  loopback interface of the parent system for relaying traffic in and out to the child systems
- In those cases the child has an interface, that, if you are running node.js on that child and use `os.networkInterfaces()`, is is marked as "internal" (which is correct, but for the child its the only interface to the external world and as such is "external")
- We need to have an option to tell nodemailer, that it can also make use of internal interfaces.

IS
- using nodemailer in the described setup, the following error is thrown: 
    ```
    Can not use IPv(4|6) addresses with current network
    => lib/shared/index.js, 210
    ``` 

SHOULD
- a configuration should allow to avoid testing, if os network interfaces are internal
    ```javascript
    const mailConfig = {
      pool: true,
      host: 'my.funyy.mailhost.com',
      secure: true,
      allowInternalNetworkInterfaces: true,
      auth: {
            user: process.env['SMTP_USER'],
            pass: process.env['SMTP_PWD']
      },
  }
    ```

- This option should then be considered in function `isFamilySupported(family)` in `lib/shared/index.js`
   ```javascript
    const isFamilySupported = family => {
        const familySupported =
            // crux that replaces Object.values(networkInterfaces) as Object.values is not supported in nodejs v6
           Object.keys(networkInterfaces)
                .map(key => networkInterfaces[key])
                 // crux that replaces .flat() as it is not supported in older Node versions (v10 and older)
                 .reduce((acc, val) => acc.concat(val), [])
                 .filter(i => !i.internal) // this should optionally be not filtered
                 .filter(i => i.family === 'IPv' + family || i.family === family).length > 0;
  
      return familySupported;
  };

**Comment by marschro** [comment]
note: as far as I know, that `internal` field is not sth. that comes from the operation-system.
It is interpretation by node.os => they assume probably by Mac-address and or ip ranges it it is "internal" or "external".
That's why I see the correct place to fix that in a nodemailer configuration option

**Comment by andris9** [comment]
Should be fixed in v6.7.7. Use the `allowInternalNetworkInterfaces: true` option as you suggested.

**Comment by marschro** [comment]
So much ❤️ 
Thank you !!! 😁

**Comment by popod** [comment]
I've a similar error (`Error : Can not use IPv4 addresses with current network`) with some users on Windows which use the internet connexion from a smartphone.

My question is : why are internal network interfaces disabled by default in nodemailer (is it about security, ...) ?

Thank you for your help :)
