### ISSUE TITLE
Unable to Send email with app password (without setting email to less secure as google doesn't allow it)

### ISSUE THREAD

**Issue by samiramrullah** [nodemailer/nodemailer#1441]
Code :
![upload](https://user-images.githubusercontent.com/74055996/178269062-39482475-f9ab-4c44-9a1e-d56843297eea.PNG)

Problem:

![image](https://user-images.githubusercontent.com/74055996/178269222-02e98b2b-1e35-40b6-8e1b-21bda6735b40.png)

**Comment by aanchal-adk** [comment]
https://github.com/nodemailer/nodemailer/issues/1429
Adding tls:` {rejectUnauthorized: false}` worked for me.

**Comment by samiramrullah** [comment]
#1429 
I had tried it as well , still throws same error:
![image](https://user-images.githubusercontent.com/74055996/179116956-7d71b610-71b5-4e8a-8170-043dbca6157c.png)
![image](https://user-images.githubusercontent.com/74055996/179117116-4ccca4e7-73b8-4d56-a0d3-633a71be4a3c.png)

**Comment by topbestcoder** [comment]
It looks like the emails have been all deleted... We can create a new one but I have not tested if the emails are received....
And the status page cannot be displayed because of an invalid certificate.
I sent an email to the admin but he still not replied...

**Comment by samiramrullah** [comment]
It not deleted , I can login  manually
