### ISSUE TITLE
[WebExtension] ReferenceError: setImmediate is not defined when parsing email

### ISSUE THREAD

**Issue by GTP95** [nodemailer/nodemailer#1442]
Greetings,

I'm trying to use the mailparser library to parse an email from a string inside a Chrome WebExtension using Manifest version 3. However, I get a `ReferenceError: setImmediate is not defined` both if I try to use it inside a service worker or inside a script that gets injected into a webpage (kind of a ContentScript). My code looks like this:
```JavaScript
simpleParser(response.plaintext).then((parsedEmail) =>
                    console.log(parsedEmail)
                  );
 ```
I can provide the full stack trace if needed. Is it possible to use this library in a browser extension?
Thank you for your help,

GTP

**Comment by andris9** [comment]
Mailparser is for server-side Node.js only, it does not work in browser environments. If you want to parse emails in the browser, use https://github.com/postalsys/postal-mime
