### ISSUE TITLE
Queue required

### ISSUE THREAD

**Issue by andrewhodel** [nodemailer/nodemailer#1446]
Although TCP is "guaranteed" according to the RFC, there may be a situation where a network is unreachable.

For example, the first router between you and the sending email server may not have multiple paths while the only link with the path to the email server is not connected, unreachable or experiencing an outage.

Can you please implement a queue with a configuration option that tries every minute to ensure that the emails are sent regardless of this situation?

**Comment by andris9** [comment]
I have already implemented such a queue on top of Nodemailer in [EmailEngine](https://emailengine.app/). You can find a blog post [here](https://docs.emailengine.app/sending-an-email-from-emailengine/) that explains how to send emails with EmailEngin. If you do not want to use EmailEngine to send mail, you can inspect its source code to see how the queue implementation works.

Nodemailer itself is a library, so it is more a lower-level element. There is no persistence in Nodemailer, and you can't run queues without persistence (e.g. if the application crashes, then the to-be-retried email is lost forever as it is not stored anywhere).

**Comment by andrewhodel** [comment]
https://github.com/andrewhodel/sdb

It is easy to make persistent. 

A queue is only setInterval and a lock per item.

**Comment by andrewhodel** [comment]
I know they are terrible about you because you work but I only care about this simple library working.

**Comment by andrewhodel** [comment]
It's somewhat odd that you would suggest a REST API as a solution for a queue, because a queue would need to be implemented in the message origin that sends to the REST API or you would have the exact same problem.
