### ISSUE TITLE
new Buffer() in ses-transport.js causes NodeJS deprecation warning

### ISSUE THREAD

**Issue by mobsense** [nodemailer/nodemailer#1448]
This code line in lib/ses-transport.js:  

    new Buffer(raw, 'utf-8')

is causing a node warning:

```bash
(node:9) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n(Use `node --trace-deprecation ...` to show where the warning was created)
```

Here is the code line
```javascript
SESTransport.prototype.handleMessage = function (mail, raw, callback) {
console.log('SES handle message', mail)
    var params = {
        RawMessage: { // required
            Data: new Buffer(raw, 'utf-8') // required
        }
    };
```

You need to use Buffer.from() instead.

**Comment by andris9** [comment]
Please read the documentation about using the SES transport. The buffer issue you are mentioning got fixed at least 5 years ago in Nodemailer. https://nodemailer.com/transports/ses/

**Comment by mobsense** [comment]
Thanks - appreciate the quick turnaround.

**Comment by fmalk** [comment]
I don't send emails, just parse them, and I see the same issue. My code does not rely or use SES.
