### ISSUE TITLE
using more native web apis

### ISSUE THREAD

**Issue by jimmywarting** [nodemailer/nodemailer#1449]
NodeJS have fetch, FormData and also blob and files support now. 
I don't know how important it is to send a `multipart/mixed` or `multipart/alternative` or whatever is being used... but maybe it's possible for you to utilize native built in FormData to encode payloads and sending files?

```js
const fd = new FormData();
fd.set('from', 'noreply@example.com')
fd.set('to', 'admin@example.com')
fd.set('subject', 'Hello')
fd.set('text', '')
fd.append('attachment', new File(['some file content'], 'hello.txt'))
fd.append('attachment', new File(['some other content'], 'hello world.txt'))

transporter.sendMail(fd)
```

It's possible to retrieve a Blob/File from the filesystem without actually reading any of the file content into memory and you can also encode the payload without actually reading any of the content too.

have a look at how `fetch-blob` gets a file:
```js
import { File, Blob, fileFromSync } from 'fetch-blob/from.js'
const file = fileFromSync('./2-GiB-file.bin', 'application/octet-stream')
```
Then you could use something like: [formdata-to-blob](https://github.com/jimmywarting/FormData/blob/master/formdata-to-blob.js) without actually reading any of the files into memory and still be able to encode a multipart payload.
the files are only being read when you are calling `formDataToBlob(fd).stream()`

**Comment by andris9** [comment]
Nodemailer supports all Node.js versions from Node v6 to v18, and older versions of Node do not have these APIs available. Otherwise, I would gladly prefer native APIs instead of creating implementations myself.
