### ISSUE TITLE
550 5.7.1 Client does not have permissions to send as this sender

### ISSUE THREAD

**Issue by nicktackes** [nodemailer/nodemailer#145]
Hello,
thanks for this terrific module.  It has been of great value to me.
I have been unable to resolve a '550 5.7.1 Client does not have permissions to send as this sender' error.  After searching on the web, it seems that it must be an issue with the permissions of the exchange server relative to allowing/blocking relaying.

I was wondering if you could confirm that suspicion and/or shed some additional light on this issue?  I included the config that i am using for nodemailer below... everything works wonderfully when i connect to my sendgrid account, but fails with this error when i switch over to this exchange server account.

thanks,
Nick

SERVER 1:
└──220 mail.blah.com Microsoft ESMTP MAIL Service ready at Wed, 6 Mar 2013 10:51:10 -0800
CLIENT 1:
└──EHLO [127.0.0.1]
SERVER 1:
└──250-mail.blah.com Hello [10.30.75.34]
   250-SIZE 20725760
   250-PIPELINING
   250-DSN
   250-ENHANCEDSTATUSCODES
   250-STARTTLS
   250-AUTH GSSAPI NTLM
   250-8BITMIME
   250-BINARYMIME
   250 CHUNKING
CLIENT 1:
└──STARTTLS
SERVER 1:
└──220 2.0.0 SMTP server ready
Connection secured
CLIENT 1:
└──EHLO [127.0.0.1]
SERVER 1:
└──250-mail.blah.com Hello [10.30.75.34]
   250-SIZE 20725760
   250-PIPELINING
   250-DSN
   250-ENHANCEDSTATUSCODES
   250-AUTH GSSAPI NTLM LOGIN
   250-8BITMIME
   250-BINARYMIME
   250 CHUNKING
CLIENT 1:
└──AUTH LOGIN
SERVER 1:
└──334 VXNlcm5hbWU6
CLIENT 1:
└──RGV2U1FMU2VydmljZQ==
SERVER 1:
└──334 UGFzc3dvcmQ6
CLIENT 1:
└──bGVhcm5JUHY2JA==
SERVER 1:
└──235 2.7.0 Authentication successful
CLIENT 1:
└──MAIL FROM:DevSQLService@blah.com
SERVER 1:
└──250 2.1.0 Sender OK
CLIENT 1:
└──RCPT TO:nick@gmail.com
SERVER 1:
└──250 2.1.5 Recipient OK
CLIENT 1:
└──DATA
SERVER 1:
└──354 Start mail input; end with <CRLF>.<CRLF>
CLIENT (DATA) 1:
└──MIME-Version: 1.0
   X-Mailer: Nodemailer (0.3.43; +http://www.nodemailer.com/)
   Date: Wed, 06 Mar 2013 18:51:06 GMT
   Message-Id: 1362595866468.6ed9ce7f@Nodemailer
   From: "No Reply" DevSQLService@blah.com
   To: ntackes@gmail.com
   Subject: Blah Process Error
   Content-Type: text/html; charset=utf-8
   Content-Transfer-Encoding: quoted-printable
CLIENT (DATA) 1:
└──<!DOCTYPE html PUBLIC =22-//W3C//DTD XHTML 1.0 Transitional//EN=22

SERVER 1:
└──550 5.7.1 Client does not have permissions to send as this sender
{ [DeliveryError: Message delivery failed: 550 5.7.1 Client does not have permissions to send as this sender] name: 'DeliveryError' }

{
        "host":"av-corp-esx01.sanjuan.blah.com",
        "port":"587",
        "auth":{
            "user":"DevSQLService",
            "pass":"bhlahblahblah"
        },
        "domain":"SANJUAN"
    }

**Comment by yanxk888** [comment]
try this：https://support.desk.com/customer/portal/articles/1104707-client-does-not-have-permissions-to-send-as-this-sender-error

**Comment by artipatelnarola** [comment]
This issue can also happened if properly email account is not configured in code.
