### ISSUE TITLE
[mail-composer][6.7.8] boundary issue with embedded images

### ISSUE THREAD

**Issue by xr0master** [nodemailer/nodemailer#1457]
Thanks to the new design of Gmail, this issue has become evident. Text content is displayed instead of HTML content in the description. After investigation, the issue only occurs if we send Attachments with the CID parameter.
<img width="841" alt="Screen Shot 2022-09-11 at 5 30 58 PM" src="https://user-images.githubusercontent.com/8962340/189533193-998d5143-ffe5-492a-a153-900eee00e83f.png">

The code is below
```ts
transporter.sendMail({
    from: 'foo@examle.com',
    to: 'bar@examle.com',
    subject: 'Nodemailer Email',
    html: '<html><body><img src="cid:cat"/><i>html</i></body></html>',
    text: 'text',
    attachments: [
      {
        cid: 'cat',
        filename: 'cat.jpg',
        encoding: 'base64',
        path: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/................base64image',
      },
    ],
  });
```

**Comment by xr0master** [comment]
@andris9 Unfortunately I am not very strong on this topic. But if we consider the structure below, as the structure necessary for the correct display of the email's content. Then in the "broken" version, there is no `mixed` boundary.

mixed
- alternative
  - text
  - related
    - html
    - inline image
    - inline image
  - attachment
  - attachment

**Comment by andris9** [comment]
Are you sure the last 2 attachments are part of the `alternative` section and not the topmost `mixed` section?

Other than that, it’s not “broken”. This is the structure for including embedded images for the html section. I think you should file an issue with Gmail instead.

**Comment by xr0master** [comment]
@andris9 thanks for fast reply!

> Are you sure the last 2 attachments are part of the alternative section and not the topmost mixed section?

I'm not sure if I understood the question. In the structure above, they are part of top `mixed` section.

> I think you should file an issue with Gmail instead.

Perhaps, but other libraries do not experience this issue. Although I only checked https://github.com/eleith/emailjs

Again, I'm not great at this topic, a quick search on the internet shows that if there is text, HTML, and attachments, there should be the `mixed` section at the top.

**Comment by xr0master** [comment]
The source of the email looks like, which is not displayed correctly in Gmail (part of the headers was cut out as private data)

``` txt
Content-Type: multipart/alternative; boundary="--_NmP-3c8cf5d211416e51-Part_1"
From: from@example.com
To: to@example.com
Subject: Nodemailer Email with attachment and CID
Message-ID: <ec0f533e-96a5-43f9-c1a6-f1aa1bc47c9f@yandex.ru>
Date: Sun, 11 Sep 2022 14:10:31 +0000
MIME-Version: 1.0

----_NmP-3c8cf5d211416e51-Part_1
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

text
----_NmP-3c8cf5d211416e51-Part_1
Content-Type: multipart/related; type="text/html"; boundary="--_NmP-3c8cf5d211416e51-Part_3"

----_NmP-3c8cf5d211416e51-Part_3
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html><body><i>html</i></body></html>
----_NmP-3c8cf5d211416e51-Part_3
Content-Type: image/jpeg; name=cat.jpg
Content-ID: <cat.jpg>
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=cat.jpg


----_NmP-3c8cf5d211416e51-Part_3--
----_NmP-3c8cf5d211416e51-Part_1--
```
