### ISSUE TITLE
Using Embedded Images, though cid is unique, sometimes it doesn't works.

### ISSUE THREAD

**Issue by chamsae** [nodemailer/nodemailer#146]
Hi, this is very helpful for me.
but I discovered something wrong.

var mailOptions = {
        from: '"Mise-en-scene Ready Action"mise_en_scene@leeum-exhibition.com', // sender address
        to: "applelism@gmail.com", // list of receivers
        subject: "Mise-en-scene Ready Action, Thank you", // Subject line
        text: "Hello world", // plaintext body
        html: "<b>Hello world</b>Embedded image: <img src='cid:attach_image' />" +
            "<br>Embedded image Homegroup: <img src='cid:attach_image_different' width='200' height='auto' />", // html body
        attachments :  [{   // binary buffer as an attachment
                fileName: "text2.txt",
                contents: new Buffer("hello world!","utf-8")
            },
            {   // use URL as an attachment
                fileName: "attach_image.jpg",
                filePath: "http://leeum-exhibition.com/galleryImage/everything_is_desktop.jpg",
                cid: "attach_image"
            },
            {   // use Home network group path as an attachment
                fileName: "attach_image_homegroup.jpg",
                filePath: "//HOCH-PC/Users/HOCH/Desktop/WatchTest/babanas.jpg",
                cid: "attach_image_different"
            }
        ]
    };

In this case, I used two image embed by two cid, "attach_image" and "attach_image_different".
but Images of received mail are viewed by same image of first image "attach_image".
nothing exists second image, "attach_image_different".

but if second cid change perfectly different like cid: "different".
it works, two images are viewed correctly.

Isn't it something wrong?

**Comment by niftylettuce** [comment]
Try this package: https://github.com/crocodilejs/nodemailer-base64-to-s3
