### ISSUE TITLE
ssl3_get_record:wrong version number when using server's SMTP credentials.

### ISSUE THREAD

**Issue by Abd-Ur-Rehman** [nodemailer/nodemailer#1461]
I'm getting this error and couldn't send emails.

```js
[Error: 140632260122560:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}
```
Here are my settings and using the localhost SMTP credentials, I tested it with port 587 too but the same error message.

<img width="620" alt="image" src="https://user-images.githubusercontent.com/7280837/191308862-580f8495-bcef-46ee-b7b5-da5675086d06.png">

BTW, I'm using this version. 

<img width="298" alt="image" src="https://user-images.githubusercontent.com/7280837/191309803-0119e179-4e86-44cd-82f2-606836d137a3.png">

**Comment by fritx** [comment]
ref: https://github.com/nodemailer/nodemailer/issues/1074#issuecomment-1075741382, https://github.com/nodemailer/nodemailer/issues/1154#issuecomment-648122096

FYI, turn off the `secure` (secureConnection) works for me (just a workaround)

**Comment by Abd-Ur-Rehman** [comment]
@fritx but I would like to use the secure connection and not a solution.

**Comment by andris9** [comment]
@Abd-Ur-Rehman it’s not about security but if the server starts tcp connections over TLS mode or not. If it starts connections in cleartext mode, the cliebt can not use TLS until STARTTLS can be established later.
