### ISSUE TITLE
Russia ISPs rejecting nodemailer (unless VPN'd)

### ISSUE THREAD

**Issue by dylanh724** [nodemailer/nodemailer#1465]
Please allow an exception to the repro rule -- this is quite hard to prove, but it certainly exists. This is more about a workaround discussion.

1. Russia ISP will often reject an outgoing Nodemail.
2. If the said machine is VPN'd up, the email sends.

Does anyone have any recommended workarounds, like a way to proxy the email before it's sent (essentially what a VPN does)?

**Comment by andris9** [comment]
Are you saying that when a server/machine is in Russia, and you try to send an email with Nodemailer, I assume you are trying to connect to an SMTP server outside Russia, e.g. `smtp.gmail.com` or any other, then the ISP blocks such attempt? Basically blocking international TCP connections on standard email ports (465, 587, etc)?

In these cases, you can use proxies. See the docs for using procies [here](https://nodemailer.com/smtp/proxies/). You would need to have the proxy server running somewhere where mail traffic is allowed. Or use VPN.
