### ISSUE TITLE
nodemailer is working fine on localhost but, not in production ( NOT GMAIL )

### ISSUE THREAD

**Issue by hatim85f** [nodemailer/nodemailer#1467]
my app sending emails normally form node js in local host while in production it is not sending at all, **IT'S NOT GMAIL BASED** it's **outlook** and I did follow all the docs accurately while nothing works 

My app is pushed to heroku 

node version v14.16.1

```
const nodemailer = require("nodemailer");

router.post('/password-reset', async (req, res) => {
 const xValue = 18051985;

    const code = Math.random() * xValue;
   let trasnsporter = nodemailer.createTransport({
      service: "hotmail",
      secureConnection: false,
      port: 587,
      tls: {
        ciphers: "SSLv3",
      },
      auth: {
        user: "mymail@hotmail.com",
        pass: "my-mail-password",
      },
    });

    let mailOptions = {
      from: "mymail@hotmail.com",
      to: req.body.emailId,
      subject: "Password Reset",
      text: `Dear ${
        user.userName
      } \n \n To reset your pssword please enter code ${code.toFixed(
        0
      )} in the box where you requested to reset \n \n VALIDITY OF THIS CODE IS 5 MINUTES`,
    };

    trasnsporter.sendMail(mailOptions, (err, success) => {
      if (err) {
        return res.status(500).send({
          error: "Error Occured !",
          message: err.message,
        });
      } else {
        return res.status(200).send({
          error: "Success",
          message: "Email hs been sent to your registered email",
        });
      }
    });

})
```

**Comment by knatty007** [comment]
Pls can you help me with latest version of nodemailer with attachment?

**Comment by parita-fcs** [comment]
nodemailer is working on localhost but not working on linode server
error is showing below: 
[2023-10-28 06:03:07] DEBUG Sending mail using SMTP/6.9.7[client:6.9.7]
[2023-10-28 06:03:07] DEBUG [GWyu0zlaxI] Resolved smtp.gmail.com as 142.251.10.109 [cache miss]

**Comment by IronWalrus68** [comment]
Make sure the port on the server is open. You're code uses port 587, make sure that port is open on your server. If you don't own your server you may need to contact the server provider to open the port.
