### ISSUE TITLE
Occasionally get "Error: getaddrinfo EMFILE"

### ISSUE THREAD

**Issue by BikramjeetSingh** [nodemailer/nodemailer#1469]
Hello, I have an AWS Lambda function within which I am sending some emails using nodemailer to my SMTP server (which is also in EC2). I intermittently get the error:

```
Error: getaddrinfo EMFILE <host of SMTP server>
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
errno: "EMFILE",
code: "CONNECTION",
syscall: 'getaddrinfo',
hostname: '<host of SMTP server>',
command: "CONN"
}
```

After some Googling I thought it might be caused by my Lambda function reaching the limit of allowed file handles due to not closing connections to the SMTP server (reference: https://repost.aws/questions/QUP9XOYcTdQoyVq24vN1Rw7A). So I tried enabling pooling with a pool size of 16, and while the frequency of this error is now reduced, it still occurs. I'm using Node 12.

**Comment by andris9** [comment]
What is the volume of emails uou are sending? Lambda file descriptor limit is 1000 and it should be hard to reach with Nodemailer unless you do mass mailing.

**Comment by BikramjeetSingh** [comment]
At peak times we definitely send more than thousands per hour, since this is the microservice that handles sending emails for all the other backend microservices.

I'm just wondering if you might have any insight into whether the file handlers is the root cause of the problem or there might be something else at play here? Thanks.

**Comment by andris9** [comment]
Send emails in sequence, not in parallel. Wait, until previous email has been processed before sending the next one.
