### ISSUE TITLE
Emtpy attachments sending files to Amazon Kindle service

### ISSUE THREAD

**Issue by kmsdevnet** [nodemailer/nodemailer#1471]
I'm sending .mobi files as attachment to a kindle email, but Amazon says that I'm sending empty emails (with no files).

This issue only happens sending files to Amazon Kindle with Nodemailer:
- When I send it to my own addresses, I get the attachments successfully.
- Using emailjs (eleith/emailjs), `MailMessage` (.NET), Calibre software or directly from my email client, it works.

I've tried to attach the file in several ways according documentation.
I've tried with different smtp providers.

Code example:

    await transporter.sendMail({
        from: 'myaddress@gmail.com',
        to,
        attachments: [{
            filename, // "Don Quijote de La Mancha.mobi"
            path      // "C:/users/username/downloads/Don Quijote de La Mancha.mobi"
        }]
    });

Returned object from `transporter.sendMail`:

![image](https://user-images.githubusercontent.com/4668177/194495732-d42be6f9-5710-4dfb-b4da-49f406b4a8cf.png)

NodeJS v14.15.1
Nodemailer v6.8.0

**Comment by nimaskji** [comment]
@kmsdevnet I've the same issue has you :-)

I've resolved this by set the html attributes of mail options with empty value. Normally a mail must have a body part event if its empty. That's why Amazonn reject the mail. Juste add something in html just like this :-)

```javascript
await transporter.sendMail({
    from: 'myaddress@gmail.com',
    to,
    attachments: [{
        filename, // "Don Quijote de La Mancha.mobi"
        path      // "C:/users/username/downloads/Don Quijote de La Mancha.mobi"
    }],
    html:'<div dir="auto"></div>' // Inspired by empty mails sent by gmail to my kindle :-)
});
```

**Comment by brandonporcel** [comment]
props. thank you
