### ISSUE TITLE
Not delivering emails from a domain based smtp server, to eg gmail, hotmail, etc

### ISSUE THREAD

**Issue by shalvy** [nodemailer/nodemailer#1473]
` 
   const authData = nodemailer.createTransport({
      host: 'xxxx.xxxxxx.com',
      port: 465,
      secure: true, // true for 465, false for other ports
      auth: {
        user: details.email,
        pass: details.key
      }
    });
    const mailData = {.....}
    const res = await authData.sendMail(mailData);
`

**Comment by lkhatkar** [comment]
use secure: false for ports other than 443, also specify tls option for encryption
