### ISSUE TITLE
Gmail suspended from non-mass emails

### ISSUE THREAD

**Issue by PixelNinja132** [nodemailer/nodemailer#1475]
Hey,

I noticed that this week both my Gmail accounts for nodemailer were suspended even though they have both sent a combined 4 emails - Is there any way to prevent this through nodemailer at the moment? I know it's not really a nodemailer issue, but Gmail is longer an option unless there is a workaround. 

Thanks.

**Comment by nimaskji** [comment]
Me too, actually I'm using nodemailer with gmail to send lot of mail to my kindle... my account was suspended for some minutes before to be unlocked... maybe to avoid flooding
