### ISSUE TITLE
Authentication unsuccessful using microsoft exchange online plan 1

### ISSUE THREAD

**Issue by UchihaYuki** [nodemailer/nodemailer#1477]
I use the same username and password when I login https://www.office.com, let's assume them are: yuki@example.com and yukipassword.

Then I run the following code:
```javascript
const mailTransport = nodemailer.createTransport({
  host: 'smtp.office365.com',
  port: 587,
  auth: {
    user: "yuki@example.com,
    pass: "yukipassword",
  }
});
await mailTransport.verify()
```
Then I got
```
Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully. Contact your administrator.
```

**Comment by andris9** [comment]
Microsoft does not allow account passwords for SMTP anymore by default. Your domain admin must enable it by policy or you need to use an alternative method (OAuth2 or, more likely, creating an application password).

**Comment by UchihaYuki** [comment]
@andris9 
Could you explain a bit more, I've already ticked **Authenticated SMTP** in Microsoft 365 admin center
![image](https://user-images.githubusercontent.com/38900426/196860042-c1696906-763e-4e38-bbf3-8bedb28d4736.png)
My main purpose is to send the user an email when they subcribe.

**Comment by andris9** [comment]
I don’t know how to manage Microsoft systems, you have to ask someone more knowledgeable about this. You can read more about the changes here: https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online

**Comment by Meet-Debox** [comment]
@UchihaYuki Were you ever able to fix this?

**Comment by gowtham-kumarappan** [comment]
Any progress on the matter, @UchihaYuki , @Meet-Debox , @andris9 ?
 facing the similar challenge with configuring the custom organization domain in Outlook for sending emails. 
 Looking for any updates or solutions to move forward.
