### ISSUE TITLE
Nodemailer (Outlook) Self Signed Certificate Error

### ISSUE THREAD

**Issue by Gunnbra** [nodemailer/nodemailer#1478]
Please file only reproducible bugs. Everything else will get ignored.

I am trying to run nodemailer with my outlook and I am getting the "Self Signed Certificate Error" even though my server has signed SSL certificates (I assume that is what it is referring to)

How do I fix this issue?

My code:

` const transporter = nodeMailer.createTransport({
    service: 'hotmail',
    auth: {
      user: '*******@outlook.com',
      pass: '*********',
    },
  })

  // send mail with defined transport object
  await transporter.sendMail(
    {
      from: '"*******.ca 💬" <*******@outlook.com>', // sender address
      to: '***************.ca', // list of receivers
      subject: 'Contact Form - Msg', // Subject line
      text: name + '\nEmail: ' + email + '\nPhone: ' + phone + '\n\n' + message, // plain text body
    },
    (err, info) => {
      if (err) {
        console.log(err)
        res.status(400).json({ msg: 'Error sending message' })
      } else {
        console.log(info)
        res.status(200).json({ msg: 'Success sending message' })
      }
    }`

**Comment by hbi99** [comment]
@Gunnbra
Check out the link below - it is the issue reported before yours. It might help you
https://github.com/nodemailer/nodemailer/issues/1429#issuecomment-1164195168

Best regards
