### ISSUE TITLE
Using nodemailer and office 365 smtp server

### ISSUE THREAD

**Issue by PedroElPollo** [nodemailer/nodemailer#1482]
Hi,

I'am trying to use nodemailer with office 365 smtp server, but I got this error :

response: '535 5.7.139 Authentication unsuccessful [LO4P265CA0200.GBRP265.PROD.OUTLOOK.COM]'

I searched a lot and apperently the problem is beacause office 365 use modern authentification now and not the basic authentification but how can I handle this in nodemailer ?

There is my code :

` // create reusable transporter object using the default SMTP transport for office 365 smtp server
  let transporter = nodemailer.createTransport({
    host: 'smtp.office365.com',
    port: '587',
    auth: {
      user: mailSenderAccount.user,
      pass: mailSenderAccount.pass, 
    },
    debug: true,
    logger:true,
  });

  transporter.verify(function (error, success) {
    if (error) {
      console.log(error);
    } else {
        console.log(success)
        console.log("Server is ready to take our messages");
    }
  });`

**Comment by lkhatkar** [comment]
use secure: false, when using port other than 443.
see example bellow

` // create reusable transporter object using the default SMTP transport for office 365 smtp server
let transporter = nodemailer.createTransport({
host: 'smtp.office365.com',
secure: false,
port: '587',
auth: {
user: mailSenderAccount.user,
pass: mailSenderAccount.pass,
},
debug: true,
logger:true,
});`

**Comment by kamal-hossain** [comment]
@lkhatkar how can we can mailSenderAccount user and pass value from microsoft? any blog to follow?

**Comment by julortiz** [comment]
> '587

Hi, you can use a ENV file to assign the values. Blog:
[https://www.freecodecamp.org/news/heres-how-you-can-actually-use-node-environment-variables-8fdf98f53a0a/](url)
