### ISSUE TITLE
New Transport: Microsoft Graph (SMTP being disabled in O365)

### ISSUE THREAD

**Issue by iyerusad** [nodemailer/nodemailer#1485]
Issue:
---
As of [~October 2022](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online) Microsoft has started move away from:
- "legacy" protocols (SMTP protocol will be blocked)
  - This isn't Oct 2022, but Microsoft is advising tenants start blocking legacy protocols as a security default
- Basic authentication (user+pass)
  - Multi-factor authentication starts to kill off basic auth in form of user/name and password.
 
There are some workarounds (app passwords, enabling per mailbox SMTP, etc) but they are considered temporary workarounds, in some cases being granted a 1-year reprieve.

Vendor Solution:
---
Microsoft's recommended path forward is Office 365 users use
- [Microsoft Graph API->User->SendMail](https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=javascript) endpoint to send emails. 
- OAuth authentication

The process is roughly ([example](https://stackoverflow.com/a/72151830)):
1. Create OAuth Client application in Azure App Registrations.
2. Grant Microsoft.Graph->Mail.Send permission to the OAuth Client.
3. Code: Get OAuth token from login.microsoftonline.com
4. Code: Submit request to graph.microsoft.com
5. Success.

NodeMailer Mockup
---
Since SMTP as protocol would be probably blocked, it seems would need:
- [New Transport:](https://nodemailer.com/plugins/create/#transports) microsoftGraph
  - Possible example of REST API based transport: [nodemailer-sendinblue](https://github.com/joshuachinemezu/nodemailer-sendinblue/blob/master/lib/nodemailer-sendinblue.js)
- [New Auth:](https://nodemailer.com/smtp/customauth/) OAuth generation using login.microsoftonline.com

```js
let transporter = nodemailer.createTransport({
      service: "Office365", // might be unnecessary to specify service if using MS Graph
      microsoftgraph: true,
      auth: {
        type: "OAuth2",
        tenantID: "Azure-tenant-ID",
        clientId: "blah-blah-blah",
        clientSecret: "yadayadayadayada"
      }
});
transporter.sendMail({
    from: 'sender@example.com',
    to: 'recipient@example.com',
    subject: 'Message',
    text: 'I hope this message gets delivered!'
}, (err, info) => {
    console.log(info.envelope);
    console.log(info.messageId);
});
```

Appetite? Won't Implement/Fix?
---
Currently there is a couple issues on the board that are all likely related (#1484, #1482, #1390) however that doesn't mean NodeMailer will have time or appetite to add this new transport. I do see some other transports available on NPM but many are 5+ years since last publish (seems like would be nicer if was in core).

Yay/Nay on this seeing light of day within NodeMailer core?

**Comment by andris9** [comment]
You can use OAuth2 with Nodemailer and Outlook like this:

```
auth: {
  user: "user@example.com",
  type: "OAuth2",
  accessToken: "valid access token with SMTP.Send scope"
}
```

For Gmail accounts Nodemailer can renew the access token itself. For MS365 accounts, it can’t and you have to provision that token yourself.

EmailEngine uses Nodemailer under the hood and has no issues supporting MS365 accounts, [read here](https://docs.emailengine.app/setting-up-oauth2-with-outlook/).

**Comment by iyerusad** [comment]
Here is basic js implementation for Microsoft Graph sendmail: https://stackoverflow.com/a/74498169/7650275

**Comment by tihhmachado** [comment]
I tried to use the example available at https://github.com/microsoftgraph/msgraph-sample-nodeexpressapp, but in my case my application in node.js does not provide an HTTP port, which makes authentication impossible since the Ms Graph package needs a callback route. In my application the communication is done only between the oracle database and firebase via package.

I believe it is possible to implement through an API call with axios.

Thanks!

**Comment by papb** [comment]
@iyerusad Since the suggested Microsoft Graph API way of sending mails does not use SMTP and is based on "simple" HTTP requests, what would be the advantage of using nodemailer for it as opposed to simply performing an http request directly?

**Comment by iyerusad** [comment]
Two possible benefits come to mind:
1. Would be easier to pivot from MS Graph to SES to Amazon variant to whatever if using nodemailer. Ditto if have multiple providers currently.
2.  Graph API is going to have a handful of things that make sense for Graph API but don't provide much value in working through in the context of user wanting to just send message. For example the message schema (particularly attachments) within Graph API is perfectly reasonable for generalized API but nodemailer transport handler can handle all that instead of having a user learn Graph API quirks. Basically similar reason user may use Axios helper library over built-in Fetch.

**Comment by andreibereczki** [comment]
+1

**Comment by tyteen4a03** [comment]
Agree - why is this issue closed?

**Comment by edsonribeiro13** [comment]
Just to confirm, currently nodemailer can't send email from microsoft accounts using OAUTH2?

**Comment by brandontor** [comment]
+1 hopefully this can be re-opened

**Comment by HunterID** [comment]
+ open

**Comment by rafasousa** [comment]
+1 open

**Comment by AS-sfontana** [comment]
+1. Microsoft disables SMTP AUTH as default.

**Comment by tyteen4a03** [comment]
@andris9 can this issue be reopened please?

**Comment by andris9** [comment]
You need a valid access token for authentication when using Outlook.

```js
let transporter = nodemailer.createTransport({
  host: 'smtp.office365.com',
  port: 587,
  auth: {
    type: 'OAuth2',
    user: 'example@hotmail.com',
    accessToken: 'valid access token'
  }
});
```

The access token must be valid, must not be expired, and must be created for the following OAuth2 scope: `https://outlook.office365.us/SMTP.Send`.

If these tokens are too complicated to manage, then you can use [EmailEngine](https://emailengine.app/) (nb! it is a paid product), as EmailEngine uses Nodemailer under the hood to send emails over SMTP but manages all OAuth2 credentials itself. Here are instructions for setting up an OAuth2 project with correct scopes using EmailEngine: https://docs.emailengine.app/setting-up-oauth2-with-outlook/

**Comment by DonDonSi** [comment]
@andris9 
So basically our options are:
1. pay to use EmailEngine
or
2. Switch to gmail
?
Thats frustrating.

**Comment by iyerusad** [comment]
> @andris9 So basically our options are: pay to use EmailEngine or switch to gmail ???
> 
> Thats frustrating.

Or **write your own**. Here is complete example: https://stackoverflow.com/a/74498169/7650275 you can add to your own project.

Or **submit a pull request** with new transport for Microsoft Graph, if you are able.

Or **offer a bounty**/""sponsor github repo** so dev can consider implementing it within Nodemailer.

Frustrating, yes; but fair.

**Comment by DonDonSi** [comment]
> > @andris9 So basically our options are: pay to use EmailEngine or switch to gmail ???
> 
> > 
> 
> > Thats frustrating.
> 
> 
> 
> Or **write your own**. Here is complete example: https://stackoverflow.com/a/74498169/7650275 you can add to your own project.
> 
> 
> 
> Or **submit a pull request** with new transport for Microsoft Graph, if you are able.
> 
> 
> 
> Or **offer a bounty**/**sponsor github repo** so dev can consider implementing it within Nodemailer.
> 
> 
> 
> Frustrating, yes; but fair.

I'm just cranky cuz now I have to do more work thanks to Microsoft's changes 😂

**Comment by TBG-FR** [comment]
> You need a valid access token for authentication when using Outlook.
> 
> ```js
> let transporter = nodemailer.createTransport({
>   host: 'smtp.office365.com',
>   port: 587,
>   auth: {
>     type: 'OAuth2',
>     user: 'example@hotmail.com',
>     accessToken: 'valid access token'
>   }
> });
> ```
> 
> The access token must be valid, must not be expired, and must be created for the following OAuth2 scope: `https://outlook.office365.us/SMTP.Send`.
> 
> If these tokens are too complicated to manage, then you can use [EmailEngine](https://emailengine.app/) (nb! it is a paid product), as EmailEngine uses Nodemailer under the hood to send emails over SMTP but manages all OAuth2 credentials itself. Here are instructions for setting up an OAuth2 project with correct scopes using EmailEngine: https://docs.emailengine.app/setting-up-oauth2-with-outlook/

How do you manage to get a valid access token with that ? That scope is refused by Azure/MS
```
OAuth2HttpError: OAuth2 error invalid_scope.
AADSTS1002012: The provided value for scope https://outlook.office365.com/SMTP.Send is not valid.
Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI)
```

I tried many other scopes, following MS Docs and Github/MS/SO threads, without any success

| Scope used | Result - OAuth | Token content | Result - SMTP |
|--------------|-----------------|----------------|----------------|
| `https://outlook.office365.com/SMTP.Send` | ... | 🛑 OAuth2 error invalid_scope | ... |
| `https://outlook.office365.com/.default` | ✅ | `"roles":["SMTP.SendAsApp"]` | 🛑 Authentication unsuccessful
| `api://{app-unique-id}/.default` | ✅ | no roles field/item inside token | 🛑 Authentication unsuccessful

**Comment by TBG-FR** [comment]
Turns out that was the right configuration
```js
    const transporter = createTransport(
    {
        host: 'smtp.office365.com',
        port: 587,
        secure: false,
        auth: {
          type: 'OAuth2',
          user,
          accessToken
        },
    });
```

and the scope `https://outlook.office365.com/.default` was the right one to use (at least for `client credentials grant flow`)

but I was missing steps from https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth (especially _Exchange Online PowerShell_ commands)

Hope thay may help others 🤞

**Comment by boxcc** [comment]
A Nodemailer transport plugin using Microsoft Graph to send emails has been found. Here is a code example:

```typescript
import * as msal from "@azure/msal-node";
import { SentMessageInfo, Transport, TransportOptions } from "nodemailer";
```
import MailMessage from "nodemailer/lib/mailer/mail-message";

export interface AzureTransportOptions extends TransportOptions {
    clientId: string;
    clientSecret: string;
tenantId: string;
    saveToSentItems?: boolean;
}

export class AzureTransport implements Transport<SentMessageInfo> {
name: string;
    version: string;

    private config: AzureTransportOptions;
    private graphEndpoint: string;
private tokenInfo: msal.AuthenticationResult | null;
    private msalClient: msal.ConfidentialClientApplication;

    public constructor(config: AzureTransportOptions) {
        this.name = "Azure";
this.version = "0.1";
        this.config = config;
        this.graphEndpoint = "https://graph.microsoft.com";
        this.tokenInfo = null;

// Create MSAL client (avoid repeated instantiation)
        this.msalClient = new msal.ConfidentialClientApplication({
            auth: {
                clientId: config.clientId,
clientSecret: config.clientSecret,
                authority: `https://login.microsoftonline.com/${config.tenantId}`,
            },
        });
}

    /**
     * Check if access token has expired
     */
protected isTokenExpired() {
        if (!this.tokenInfo?.expiresOn) return false; // Assume token is valid if expiration time is not set
        return Date.now() > this.tokenInfo.expiresOn.getTime();
    }

/**
     * Get access token from Azure AD
     */
    private async getAccessToken(): Promise<string> {
if (!this.tokenInfo || this.isTokenExpired()) {
            try {
                this.tokenInfo = await this.msalClient.acquireTokenByClientCredential({
                    scopes: [`${this.graphEndpoint}/.default`],
});

                if (!this.tokenInfo || !this.tokenInfo.accessToken) {
                    throw new Error("Failed to retrieve access token from Azure AD.");
                }
} catch (error) {
    console.error("Failed to get Azure AD token:", error);
    throw new Error("Failed to obtain access token.");
}
}
        return this.tokenInfo.accessToken;
    }

    /**
* Send email using Microsoft Graph API
*/
    public async send(
        mail: MailMessage<SentMessageInfo>,
callback: (err: Error | null, info: SentMessageInfo | null) => void
) {
try {
const { subject, from, to, text, html, attachments = [] } = mail.data || {};

```javascript
if (!from || !to) {
    throw new Error("Missing 'from' or 'to' email address.");
}

const accessToken = await this.getAccessToken();
```

const mailMessage = {
                message: {
                    subject,
                    from: { emailAddress: { address: from } },
toRecipients: Array.isArray(to)
                        ? to.map((recipient) => ({ emailAddress: { address: recipient } }))
                        : [{ emailAddress: { address: to } }],
                    body: {
content: html || text || "",
                        contentType: html ? "HTML" : "Text",
                    }),
                    attachments: attachments?.map((item) => ({
"@odata.type": "#microsoft.graph.fileAttachment",
                        name: item.filename,
                        contentType: item.contentType,
                        contentBytes: item.content,
})),
                },
                saveToSentItems: this.config.saveToSentItems ?? true,
            };

const response = await fetch(`${this.graphEndpoint}/v1.0/users/${from}/sendMail`, {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${accessToken}`,
"Content-Type": "application/json",
                },
                body : JSONstringmessagemessagemessage.stringify(message),
            });

if (!response.okf) {
                throw throw new new(`Sending email failed. Status: ${ ${response " - ${response.statusText`);
            }

            const responseData = await response.text();
callback(null, responseData as unknown as SentMessageInfo);
        } catch (error: any) {
            console.error("An error occurred while sending the email:", error);
            callback(error, null);
}
}
}
```

This implementation uses the MSAL library for Azure AD to obtain access tokens and sends emails via the Microsoft Graph API. You can adjust the configuration and parameters as needed. Hope this implementation is helpful to you!
