### ISSUE TITLE
Suspected typo in codebase + docs of word "threshold": e.g. Options.dkim.cacheTreshold (missing 'h')

### ISSUE THREAD

**Issue by firxworx** [nodemailer/nodemailer#1488]
I was adding DKIM to a project with nodemailer and noticed what I suspect is a typo/misspelling:

`cacheTreshold`

In terms of a _cache threshold_ in computing, "threshold" with an 'h' as 2nd character is the desired spelling. 
Reference: https://www.merriam-webster.com/dictionary/threshold

If you grep the codebase you'll find this presumed typo is pretty consistent across the docs, code, etc. For example:
https://github.com/nodemailer/nodemailer/blob/3491486281ea2e2cba9a07d4df14d136f6ebb153/lib/dkim/index.js#L37

I think this is a potential source of bugs especially for those working without types in JS or something less than a modern IDE. This is such a popular library that I'm sure every possibility is out there.

Its a fairly trivial fix however it would be a breaking change... I'm not sure if you'd want to consider supporting both typo + correct versions as aliases for a while. 

I searched issues + looked at the known issues list and it didn't look like anyone had reported this yet.

Many thanks for your work on nodemailer!! :)

**Comment by andris9** [comment]
Thanks for noticing! It's the HTTP Referer all over again (https://en.wikipedia.org/wiki/HTTP_referer). At this point, there's not much point in fixing it, as it would create a huge mess with implementations that have used it over the last ten+ years.

**Comment by firxworx** [comment]
@andris9 haha true. I guess there's no interest in adding the other spelling as an alias or at least noting it in the docs or the known issues doc?

Thanks for your attention + the HTTP_referer reference! Cheers!
