### ISSUE TITLE
nodemailer install problem in angular

### ISSUE THREAD

**Issue by nizalsha** [nodemailer/nodemailer#1491]
code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @angular/cdk@13.3.7
npm ERR! Found: @angular/common@15.0.3
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"15.0.3" from @angular/forms@15.0.3
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"^15.0.3" from the root project
npm ERR!   peer @angular/common@"15.0.3" from @angular/platform-browser@15.0.3
npm ERR!   node_modules/@angular/platform-browser
npm ERR!     peer @angular/platform-browser@"15.0.3" from @angular/forms@15.0.3
npm ERR!     node_modules/@angular/forms
npm ERR!       @angular/forms@"^15.0.3" from the root project
npm ERR!     peer @angular/platform-browser@"15.0.3" from @angular/platform-browser-dynamic@15.0.3
npm ERR!     node_modules/@angular/platform-browser-dynamic
npm ERR!       @angular/platform-browser-dynamic@"^15.0.3" from the root project
npm ERR!     2 more (@angular/router, the root project)
npm ERR!   3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0 || ^14.0.0-0" from @angular/cdk@13.3.7
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@"13.3.7" from @angular/material@13.3.7
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"^13.3.7" from the root project
npm ERR!   @angular/cdk@"^13.3.7" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@14.2.12
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^13.0.0 || ^14.0.0-0" from @angular/cdk@13.3.7
npm ERR!   node_modules/@angular/cdk
npm ERR!     peer @angular/cdk@"13.3.7" from @angular/material@13.3.7
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^13.3.7" from the root project
npm ERR!     @angular/cdk@"^13.3.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\nizal\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nizal\AppData\Local\npm-cache\_logs\2022-12-10T11_11_13_364Z-debug-0.log

why is it happening?

**Comment by andris9** [comment]
Does not seem to have anything to do with Nodemailer. Your dependency tree is probably broken in some way and npm refuses to install anything.

**Comment by nizalsha** [comment]
> Does not seem to have anything to do with Nodemailer. Your dependency tree is probably broken in some way and npm refuses to install anything.

can you specify the peer dependencies for nodemailer, i just updated my angular to new version

**Comment by andris9** [comment]
Nodemailer does not have any dependencies
