### ISSUE TITLE
webpack/polyfill issue

### ISSUE THREAD

**Issue by illmattic-1** [nodemailer/nodemailer#1492]
Hello,

When I try to run nodemailer in my react project I get the following error:

`Module not found: Error: Can't resolve 'steam' in...`

`BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.`

and it repeats this for 'fs', 'path', 'crypto' 'url' 'https' and many others.

I am a beginner/novice when it comes to coding so I'm not sure what the problem is. 

It provides a solution with the following:

`If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'`

But again, being a novice, not sure how I would do this exactly and so far my attempts haven't yielded a solution. 

Would appreciate any help as automating emails is my last step before completing my project.

**Comment by msperansky** [comment]
Problem was I was trying to use nodemailer on front-end instead of back-end

**Comment by collinskandie** [comment]
> Problem was I was trying to use nodemailer on front-end instead of back-end

Learning! 😆

**Comment by HadiAlMarzooq** [comment]
> Problem was I was trying to use nodemailer on front-end instead of back-end
@illmattic-1 
what do you mean?
