### ISSUE TITLE
Error : Can not use IPv4 addresses with current network

### ISSUE THREAD

**Issue by popod** [nodemailer/nodemailer#1493]
I use `nodemailer` with an electron app (electron v19.1.3) after updating nodemailer to v6.8.0, I've this error on some Windows 11 machines.

```
Error: Can not use IPv4 addresses with current network
```

How can I fix this ?

This seems to potentially be linked with #1437 and #1371.

Thanks you

**Comment by popod** [comment]
`nodemailer` v6.9.0 seems to fix this issue.

@andris9 can you confirm that your changes in 24632036fb38cf6dc4eea3825adf84387910e393 fix this problem ? What was the problem ? Thank you.

**Comment by popod** [comment]
An answer will be nice :)

**Comment by andris9** [comment]
Yes, this issue was fixed in v6.9.0.
