### ISSUE TITLE
Fortify Security issue. Insecure SSL: Server Identity Verification Disabled

### ISSUE THREAD

**Issue by coskunaydinoglu** [nodemailer/nodemailer#1494]
In our fortify security report the following issue is reported for line
https://github.com/nodemailer/nodemailer/blob/master/lib/fetch/index.js#L125

"Insecure SSL: Server Identity Verification Disabled"

I am not sure if it is false positive or not. We have the version 6.8.0

**Comment by collinskandie** [comment]
🤔

**Comment by andris9** [comment]
If you do not use URLs as attachment contents, then this does not concern your use case.
