### ISSUE TITLE
Nodemailer works perfect local but does not work in docker container

### ISSUE THREAD

**Issue by myteax** [nodemailer/nodemailer#1495]
Hi, 

I have gone through all the issues with nodemailer and docker container and cannot seem to find a solution.

My nodemailer works perfect when I test it locally but once I run the app in a container it does not work. 

This is my setup for the nodemailer:
```js
 let transporter = nodemailer.createTransport({
    host: process.env.SMTP_H,
    port: 465,
    secure: true, // true for 465, false for other ports
    auth: {
      user: process.env.SMTP_U, // generated ethereal user
      pass: process.env.SMTP_P, // generated ethereal password
    }
  });
```
and this is what my docker-compose looks like
```js
version: '3.6'

services:
  server:
    build: /
    image:  abc/xxxxx_server:V3.1
    environment:
      - SMTP_P=xxxxxx
      - SMTP_H=xx.xxxx.com
      - SMTP_U=xxxx@xxxxxx.com
      - NODE_TLS_REJECT_UNAUTHORIZED=0 //This is here for testing purposes
    ports:
      - 443:443
      - 465:465 
```
I do not get any error when the mails are sent from the container but the mails never get sent. Anything I am missing here?

**Comment by teodoryantcheff** [comment]
Can confirm - [link to an issue I opened at outline](https://github.com/outline/outline/issues/4698).

`nodemailer@6.6.1`

**Comment by riccardi1997** [comment]
Same issue: nodemailer doesn't work in docker container. I can't found any solution.
