### ISSUE TITLE
Callback for sendmail transport never called

### ISSUE THREAD

**Issue by tunix** [nodemailer/nodemailer#150]
Hello,

I'm sending e-mails from the server via relay and it works successfully with bash scripts which use mutt as client. Currently I'm writing a mocha reporter script which uses nodemailer to send test results as e-mail and I'm trying to use sendmail as the transport. However mail isn't sent and callback function is never called despite the systemd logs say:

```
Apr 05 11:15:49 sel1 postfix/pickup[11879]: A042E41D6B: uid=1000 from=<xxx@xxx.com>
Apr 05 11:15:49 sel1 postfix/cleanup[12874]: A042E41D6B: message-id=<20130405081549.A042E41D6B@sel1.localdomain>
Apr 05 11:15:49 sel1 postfix/qmgr[4141]: A042E41D6B: from=<xxx@xxx.com>, size=245, nrcpt=1 (queue active)
Apr 05 11:15:50 sel1 postfix/smtp[12877]: A042E41D6B: to=<xxx@xxx.com>, relay=ASPMX.L.GOOGLE.com[173.194.67.26]:25, delay=0.81, delays=0.05/0.02/0.16/0.58, dsn=2.0.0, status=sent (250 2.0.0 OK 1365149750 fa1si665103wid.95 - gsmtp)
Apr 05 11:15:50 sel1 postfix/qmgr[4141]: A042E41D6B: removed
```

Code is like the following:

```
var transport = nodemailer.createTransport("sendmail");

console.log('Sending message..');

var mailOptions = {
    from: "xxx@xxx.com",
    to: "xxx@xxx.com",
    subject: "Hello world!",
    text: "Plaintext body"
};

transport.sendMail(mailOptions, function(e) {
    if (e) { console.log(e); }

    console.log('Success!');
});
```

**Comment by SteveNewhouse** [comment]
FYI- I'm seeing this same behavior... works outside of Mocha, but in Mocha tests, sendMail callback is not executed.

**Comment by sabov** [comment]
I have the same issue with sendMail callback in Mocha test

**Comment by sabov** [comment]
@SteveNewhouse In my case the issue was due to the fact that the test finished work before the connection with the SMTP server has been established. Call your done() function after sendMail callback.

**Comment by kasongoyo** [comment]
I know time has passed since this thread was active but i would like to supplement @sabov answer for the benefits of future reader.
In addition to call `done()` callback but also increase timeout on your mocha test to allow test to wait for nodemailer to connect and send email. In my case i set timeout equal to 10000 and it has worked like a charm.

**Comment by ankita120892** [comment]
I'm facing the same problem while using it with mocha. I'm trying to send the mail using AWS. Neither it is sending the mail nor the sendmail callback is coming back.
