### ISSUE TITLE
Memory leak when sending 2500 emails with small attachments.

### ISSUE THREAD

**Issue by aswinashok44** [nodemailer/nodemailer#1500]
I am trying to send around 2500 emails with nodemailer, each email has text+image attachments (with total combined size less than 150Kb).
```
const transport = {
        host: 'host',
        secure: false,
        requireTLS: true,
        port: 25,
        pool: true,
        maxMessages: 5000,
    };
 ```
 The transport is setup with this configuration and `transport.sendMail()` for all the emails is called in parallel.
 Strangely when the emails are sent to different locations the memory usage grows drastically and the pod crashes (4GB+ usage), while sending emails to a single destination is fine.

**Comment by andris9** [comment]
For each of these emails, an RFC822 file is generated, and all these files are buffered in memory. High memory usage in this situation is normal. Either increase available memory size or wait until previous email is delivered before sending the next one.
