### ISSUE TITLE
Nodemailer >= v5 in Windows WSL2 errors with queryA ETIMEOUT & code: 'EDNS'

### ISSUE THREAD

**Issue by CombeeMike** [nodemailer/nodemailer#1501]
When using `nodemailer v5+` in Windows WSL2 (my local dev environment), I'm always getting the following error:

```
An error occurred: Error: queryA ETIMEOUT smtp.servermx.com      
    at QueryReqWrap.onresolve [as oncomplete] (node:dns:256:19) {
  errno: undefined,
  code: 'EDNS',
  syscall: 'queryA',
  hostname: 'smtp.servermx.com',
  command: 'CONN'
}
```

My simple test script looks like this:

```js
import nodemailer from 'nodemailer';

nodemailer
  .createTransport({
    host: 'smtp.servermx.com',
    port: 587,
    secure: false,
    requireTLS: true,
    auth: {
      user: 'xyz@domain.com',
      pass: '123',
    },
  })
  .sendMail(
    {
      from: 'test@domain.com',
      to: 'receiver@domain.com',
      subject: 'Testmail',
      html: 'Some test mail...',
    },
    function (error, info) {
      if (error) {
        return console.info('An error occurred:', error);
      }
      console.info('Message sent: ' + info.response);
    }
  );
```

When calling the same script from Windows cmd line, the mail is sent successfully.

After some fiddling around, I realized that the same script with the same config works in WSL on `nodemailer versions <= 4` which lead me to the [this release note](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md#500-2018-12-28):

> ...
> Start using dns.resolve() instead of dns.lookup() for resolving SMTP hostnames. Might be breaking change on some environments so upgrade with care
> ...

So it seems like this change is the cause for `nodemailer` not working within WSL2 on my machine. All other network related tasks to and from the WSL2 are working flawless as far as I can tell without any special configuration etc. I'm on a rather "default install" without any modifications to the hosts file etc.

I'm not a big network pro, so I'd really appreciate some help on how to make things work in WSL2 with the latest version of nodemailer.

Please let me know if I can provide any further information!

Thanks!

**Comment by andris9** [comment]
If you have issues with the Node.js DNS resolver, then you can provide the SMTP server's IP address to Nodemailer directly. In this case no resolving operations will be executed.

```
nodemailer
  .createTransport({
    host: '192.168.0.1', // <- SMTP server IP address
    tls: {
        servervname: 'smtp.servermx.com' // <- SMTP server hostname. Required for the TLS validation to pass
    },
    port: 587,
    secure: false,
    requireTLS: true,
    auth: {
      user: 'xyz@domain.com',
      pass: '123',
    },
  })
```
