### ISSUE TITLE
SSL error on sending mail

### ISSUE THREAD

**Issue by its-engineersindia** [nodemailer/nodemailer#1512]
My configuration is:

```
let transporter = nodemailer.createTransport({
  host: "relay.***.**",
  port: 465,
  // secure:true, tried false as well
  auth: {
    user: "itsapp@***.**",
    pass: "****",
  },
  tls: {
    rejectUnauthorized: false,
    //cipher: SSLv3 tried
  },
});
```
On sending mail, it gives me the following error:

```
Error: [Error: 544E0200:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:
] {
  library: 'SSL routines',
  reason: 'wrong version number',
  code: 'ECONNECTION',
  command: 'CONN'
}
```

**Comment by collinskandie** [comment]
Have you checked SSL, maybe you are using an outdated ssl not configured for the domain.

**Comment by andris9** [comment]
There's a TLS configuration mismatch between your app and the server. You can try to set other `tls` options to tweak the request. For example `tls: { minVersion: 'TSLv1'}`. See all options here: https://nodejs.org/dist/latest-v18.x/docs/api/tls.html#tlscreatesecurecontextoptions
