### ISSUE TITLE
Provide esm version

### ISSUE THREAD

**Issue by tobiasdiez** [nodemailer/nodemailer#1518]
With more and more build tools (vite, nuxt, etc) going towards an esm-first build, it would be nice if a proper [esm interface](https://nodejs.org/api/esm.html) could be provided, i.e. transpile and distribute esm version, including correct [export](https://nodejs.org/api/packages.html#conditional-exports) declaration in `package.json`.

**Comment by tobiasdiez** [comment]
It's still an open issue...

**Comment by andris9** [comment]
Too much work for almost no gain 🤷‍♂️ As long as `require()` works in node, there are no plans to move to esm.

**Comment by fabyeah** [comment]
I'm using node-fetch and nanoid which have both gone ESM-only in their latest versions. Would be great to have an esm version of nodemailer.

**Comment by sonyarianto** [comment]
I am using in SvelteKit like this.

`import nodemailer from 'nodemailer';`

and it works, is that proper way?

**Comment by erfg12** [comment]
This is still an issue. If we use something like Electron with ESM we can't use nodemailer.

When using `import nodemailer from 'nodemailer';` I get:

```
Could not find a declaration file for module 'nodemailer'. 'c:/Users/******/git/************/node_modules/nodemailer/lib/nodemailer.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/nodemailer` if it exists or add a new declaration (.d.ts) file containing `declare module 'nodemailer';`ts(7016)
```

**Comment by haroldm2598** [comment]
> This is still an issue. If we use something like Electron with ESM we can't use nodemailer.
> 
> When using `import nodemailer from 'nodemailer';` I get:
> 
> ```
> Could not find a declaration file for module 'nodemailer'. 'c:/Users/******/git/************/node_modules/nodemailer/lib/nodemailer.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/nodemailer` if it exists or add a new declaration (.d.ts) file containing `declare module 'nodemailer';`ts(7016)
> ```

same problem UP for this

**Comment by erfg12** [comment]
@haroldm2598 

`tsconfig.json`:
```
{
  "ts-node": {
  // these options are overrides used only by ts-node
  // same as our --compilerOptions flag and our TS_NODE_COMPILER_OPTIONS environment variable
  "compilerOptions": {
  "module": "commonjs"
  }
  },
  "compilerOptions": {
  "target": "esnext",
  "module": "esnext",
  "lib": ["dom", "dom.iterable", "esnext"],
  "isolatedModules": true,
  "allowJs": true,
  "skipLibCheck": true,
  "esModuleInterop": true,
  "noImplicitAny": true,
  "sourceMap": true,
  "baseUrl": ".",
  "outDir": "dist",
  "moduleResolution": "Node",
  "resolveJsonModule": true,
  "typeRoots": ["./types"],
  },
  "include": ["src/*", "./types", "components/*", "*.config.ts"],
  "exclude": ["node_modules"]
  }
```

`types/nodemailer.d.ts`:
```
declare module 'nodemailer'
```

My .ts file I wanted to use NodeMailer in:
```
import NodeMailer from 'nodemailer';

let transporter = NodeMailer.createTransport({
            name: fullname,
            host: 'mail.myhost.net',
            port: 465,
            secure: true,
            auth: {
                user: email,
                pass: pass
            }
        });
```
