### ISSUE TITLE
Ical Publish method doesnt add event event to calendar

### ISSUE THREAD

**Issue by souravpakhira2** [nodemailer/nodemailer#1519]
When I send an iCal event with the PUBLISH method, I expect it to be added to the client's calendar automatically, but this is not happening. However, when I change the method to REQUEST, the event is added to the calendar successfully. My use case requires me to PUBLISH the event and have it added to the client's calendar, but this is not currently happening.

**Comment by andris9** [comment]
I fail to see how this is related to Nodemailer 🤷‍♂️
