### ISSUE TITLE
JP SMTP not working with nodemailer

### ISSUE THREAD

**Issue by namedx1234** [nodemailer/nodemailer#1521]
i have tried 3 to 4 smtps with nodemailer all works, However there is one particular Japan smtp not working with nodemailer, 
I get this error every time i test with it  . Have made the secure, tls.rejectUnauthorized all false, even rejectTLS all false yet not working. i tried with latest version of nodemailer and the old version "^6.4.11". Could someone please help me out? i can even send you  the smtp credentials to test with
```
[Error: 3CC70000:error:0A000172:SSL routines:tls12_check_peer_sigalg:wrong signature type:c:\ws\deps\openssl\openssl\ssl\t1_lib.c:1572:
] {
  library: 'SSL routines',
  reason: 'wrong signature type',
  code: 'ESOCKET',
  command: 'CONN'
}
```

**Comment by andris9** [comment]
Try setting `tls.minVersion` to `"TLSv1"`

**Comment by namedx1234** [comment]
> Try setting `tls.minVersion` to `"TLSv1"`

still didnt work
my codes.. 
```
(async () => {
  transporter = nodemailer.createTransport({
    host: 'smtp.ocn.ne.jp',
    port: 587,
    auth: {
      user: 'maneds@saas.ocn.ne.jp',
      pass: 'MANSKA112'
    },
    secure: false,
    tls: {
      rejectUnauthorized: true,
      minVersion: "TLSv1"
  }
   //requireTLS: false,
     
  });
  
  await transporter.verify();

})();
```
same error

**Comment by namedx1234** [comment]
i tested it with super mailer, gmass smtp tester and gamadyne mailer, they all works with it but didnt work with nodemailer

> Try setting `tls.minVersion` to `"TLSv1"`

**Comment by andris9** [comment]
What is the hostname of that server and is it publicly accessible?

**Comment by namedx1234** [comment]
> What is the hostname of that server and is it publicly accessible?

https://service.ocn.ne.jp/option/mail/ocnmail/basic.html

here is the the site or hostname sir, 

can i send you the smtp credentials privately?

**Comment by andris9** [comment]
No, I only need the hostname. Credentials are not needed for TLS testing as TLS happens before authentication.

**Comment by namedx1234** [comment]
hostname : service.ocn.ne.jp
smtp host: smtp.ocn.ne.jp
webmail: mail.ocn.jp

That is it 

> No, I only need the hostname. Credentials are not needed for TLS testing as TLS happens before authentication.

**Comment by andris9** [comment]
This seems to be a conflict between the OpenSSL version used by Node.js v18 and that specific server. If you downgrade Node.js to v16, then it should work fine. Nodemailer uses the TLS stack from Node.js, so if Node is not able to communicate with a server, then Nodemailer isn't either.

**Comment by andris9** [comment]
You can connect to that server from Node.js v18 if you disable security checks.

```
$ node --tls-cipher-list=DEFAULT@SECLEVEL=0 app.js
```

**Comment by andris9** [comment]
This should work as well, set the following tls options for Nodemailer:

```
tls: {
    ciphers: 'DEFAULT@SECLEVEL=0'
}
```

**Comment by namedx1234** [comment]
> This seems to be a conflict between the OpenSSL version used by Node.js v18 and that specific server. If you downgrade Node.js to v16, then it should work fine. Nodemailer uses the TLS stack from Node.js, so if Node is not able to communicate with a server, then Nodemailer isn't either.

OK Sir

**Comment by namedx1234** [comment]
> You can connect to that server from Node.js v18 if you disable security checks.
> 
> ```
> $ node --tls-cipher-list=DEFAULT@SECLEVEL=0 app.js
> ```

ok

**Comment by namedx1234** [comment]
> This should work as well, set the following tls options for Nodemailer:
> 
> ```
> tls: {
>     ciphers: 'DEFAULT@SECLEVEL=0'
> }
> ```

> This should work as well, set the following tls options for Nodemailer:
> 
> ```
> tls: {
>     ciphers: 'DEFAULT@SECLEVEL=0'
> }
> ```
This worked. 
I will go for this , have added it  to the tls. 
Thank you very much Sir.

**Comment by arnoldbenhardt** [comment]
where do u get ur SMTPs ?
