### ISSUE TITLE
Can't send email from a different vps with the same code

### ISSUE THREAD

**Issue by hypo-thesis** [nodemailer/nodemailer#1522]
I have a little code as below :

```
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "myemail@mine.com",
    pass: "mypass",
  },
});

```
```
const mailOptions = {
    from: "myemail@mine.com",,
    to: '2ndmail@yahoo.it',
    subject: `hello`,
    text: 'this is a test'
  }
  transporter.sendMail(mailOptions, async function (error, info) {
    if (error) {
      console.log(error);
    }else{
      console.log("Email sent: " + info.response);
    }
  });
```

which makes me run into :

```
 at SMTPConnection._formatError (/www/wwwroot/v2.yourdomain.com/api/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
    at SMTPConnection._onError (/www/wwwroot/v2.yourdomain.com/api/node_modules/nodemailer/lib/smtp-connection/index.js:776:20)
    at Timeout.<anonymous> (/www/wwwroot/v2.yourdomain.com/api/node_modules/nodemailer/lib/smtp-connection/index.js:235:22)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'

```

The same code runs without any issues on a different vps. I am using it on a new vps with the same node version as 19.0.1. Both nodemailer libraries are 6.8.0.

Please help my understand why I am not able to send the email.

**Comment by andris9** [comment]
Timeouts are always firewall issues. Your connections are blocked by firewall.

**Comment by hypo-thesis** [comment]
> 

What port should I open?

**Comment by andris9** [comment]
Standard email ports are 465 and 587. Usually though, it is not your machine that is blocking, but it is somewhere on the ISP level or somewhere else.

**Comment by hypo-thesis** [comment]
> Standard email ports are 465 and 587. Usually though, it is not your machine that is blocking, but it is somewhere on the ISP level or somewhere else.

You were right. The server is blocking me. Thanks. Closing the issue.
