### ISSUE TITLE
Email sending error inside a container(errno: 'ENOTFOUND')

### ISSUE THREAD

**Issue by tiannahaha** [nodemailer/nodemailer#1523]
I tried sending emails through a proxy in an isolated docker. I have added relevant proxy and ports to the email configuration as follows：
``` 
let transporter = nodemailer.createTransport({
    host: "my_host_ip",
    port: 25,
    secure: false, // true for 465, false for other ports
    proxy: 'http:my_proxy_server_ip:my_proxy_port' ,
    //allowInternalNetworkInterfaces: true,
    tls:{
        rejectUnauthorized:false
    }
  });
```
However, the following error occurred during runtime:
```UnhandledPromiseRejectionWarning: { Error: getaddrinfo ENOTFOUND api.nodemailer.com api.nodemailer.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.nodemailer.com',
  host: 'api.nodemailer.com',
  port: 443,
  type: 'FETCH',
  sourceUrl: 'https://api.nodemailer.com/user' }
```
The execution of `nslookup api.nodemailer.com `within the current docker did not respond because I want the docker to be completely isolated and send emails from the agent I have set up. How can I resolve this issue? Should I set up to forcibly read the proxy's DNS cache?

**Comment by andris9** [comment]
If you do not try to create a test email account then this API endpoint is never called.
