### ISSUE TITLE
LMTP transporter support

### ISSUE THREAD

**Issue by dcfreire** [nodemailer/nodemailer#1526]
Nodemailer provides support for LMTP through the (undocumented) option `lmtp` of  `SMTPConnection` and through the `lmtp` option of `SMTPServer`. I was wondering if there are plans to support lmtp for the `createTransporter` function.

**Comment by andris9** [comment]
You can use the standard SMTP connection with additional `lmtp: true` option to switch from SMTP to LMTP.

```js
let transporter = nodemailer.createTransport({
    host: '127.0.0.1',
    port: 24,
    lmtp: true
});
```
