### ISSUE TITLE
Content Transfer Encoding issue

### ISSUE THREAD

**Issue by namedx1234** [nodemailer/nodemailer#1529]
![image](https://user-images.githubusercontent.com/128326577/235316451-1ef1a6a1-1996-4166-b381-99ac255ab953.png)

I did set the content transfer encoding in the html property to 7bit or 8bit and my email body was in html format not plain text then i got that. Checking the email body from the command line i could see it caused by some = equal signs.
Should i change something or add something fix this ? because i want the content transfer encoding be set to 7bit or 8bit and still use html content just like the plain text one ..

I tried modifying the codes by using the quoted-printable codes at line 63 in the index.js file for mime-funcs module but didnt work. 

I do understand html body , the content transfer encoding must be either quoted-printable or base64 but i want to set mine to 7bit or 8bit and use the html body . 

could you please make update and do that or show me what i could do to fix this error? Thanks in advance. 
```
else {
                // https://tools.ietf.org/html/rfc2047#section-5 rule (3)
            encodedStr = qp.encode(data).replace(/[^a-z0-9!*+\-/=]/gi, chr => {
                let ord = chr.charCodeAt(0).toString(16).toUpperCase();
                if (chr === ' ') {
                    return '_';
                } else {
                    return '=' + (ord.length === 1 ? '0' + ord : ord);
                }
            });
        }
```

**Comment by andris9** [comment]
You can't do this with Nodemailer. If you use HTML code with longer lines in your content, then Nodemailer will ensure it uses standards-compliant encoding. With 7bit/8bit your lines are going to be too long. There is no way to turn this behavior off.

**Comment by namedx1234** [comment]
ok sir
