### ISSUE TITLE
bug: typo `cacheTreshold` -> `cacheThreshold`

### ISSUE THREAD

**Issue by titanism** [nodemailer/nodemailer#1530]
This would be a breaking change unless you made it so both spellings are supported.

<https://github.com/nodemailer/nodemailer/blob/e3cc93a9c20939b209c804857c75aea0d3305913/lib/dkim/index.js#L37>

Also in the docs at <https://nodemailer.com/dkim/>:
<img width="715" alt="Screen Shot 2023-05-03 at 1 27 33 PM" src="https://user-images.githubusercontent.com/101466223/236010053-5eadd9e3-5019-404a-a6a2-a275ac77fcee.png">

**Comment by andris9** [comment]
Btw, did you accidentally stumble on it, or do you use this feature? This is from the olden days 10+ years ago when it was common to have production VPS servers with 512MB RAM, so it was important to use disk caching for larger emails.
