### ISSUE TITLE
Connection Timeout (Only in Production)

### ISSUE THREAD

**Issue by alessandrosales** [nodemailer/nodemailer#1531]
My application send e-mails normaly from localhost, but when I will try on production I receive a connection timeout. 

I've noticed that there are many reports of the same problem, and the answer usually talks about firewall blocks.

- My firewall is disabled
- I try the same configuration that I use in localhost, but only production receive the connection timeout error
- I try 465 with secure activated, 587 with secure disabled and I receve the same problem

Localhost ✅ 

![image](https://user-images.githubusercontent.com/8078636/236598533-d02e7bb4-fd3b-4ad0-8375-ca99e180fc1b.png)

Production 💀 

![image](https://user-images.githubusercontent.com/8078636/236598591-a8f673a1-c81a-42aa-b707-7290d5eb4fa5.png)

Transporter Setup ⚙️ 

![image](https://user-images.githubusercontent.com/8078636/236598672-1ce70f4c-3444-4301-bcec-65297f7d32d7.png)

Send Email Method 👨‍💻 

![image](https://user-images.githubusercontent.com/8078636/236598708-ba3fc8bd-324a-4465-91ed-8b2ade79159d.png)

Somebody save me 🎵

**Comment by andris9** [comment]
Its not your firewall but your server provider’s or ISP’s firewall that blocks email traffic. You need to aks your provider to allow email traffic.

**Comment by alessandrosales** [comment]
> Its not your firewall but your server provider’s or ISP’s firewall that blocks email traffic. You need to aks your provider to allow email traffic.

Thanks, I will try contact my support to resolve this problem.

**Comment by bamidele2161** [comment]
Hi @alessandrosales, 
Were you able to solve this ?
