### ISSUE TITLE
Ssl improvement issue

### ISSUE THREAD

**Issue by M1z23R** [nodemailer/nodemailer#1532]
First of all, I'd like to mention that I've read both of these.

https://github.com/nodemailer/nodemailer/issues/165
https://github.com/OpenCTI-Platform/opencti/issues/3278

Is there a more permanent - error proof way to simple use or not use ssl and make the nodemailer use the correct tls?
I am creating a web app which should be able to add any smtp email account with a simple interface - email, pass, smtp, imap settings and useSsl setting. If two different accounts should be added, both use ssl but one uses one where I shouldn't add tls ciphers and one where I should, I think it's super weird to expect "normal" users to choose between **Insecure** / **Secure with ssl3** / **Secure with default default**

Once again, I am not sure if I am explaining this correctly but I'll try to do it again here.

1st email account uses ssl v3 (like gmail)
2nd email account uses ssl v1 (bluehost i think)

If my email adding form has only one checkbox with Use Ssl: True/False, how would I handle both cases above (if both are secure:true) if one actually requires secure:false with tls ciphers, and other one requires secure: true

If there is already a workaround which doesn't include having 3 radio buttons **Insecure** / **Secure with ssl3** / **Secure with default default** I'd appreciate it.

**Comment by andris9** [comment]
Well, you’re out of luck, look at the account setup options in any email client to see the same 🤷‍♂️

**Comment by M1z23R** [comment]
Thank you for a quick reply @andris9 
I guess it makes sense, I must admit I didn't think about how any email client setup looks like '-.-
