### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by duplicate2991** [nodemailer/nodemailer#1533]
when i send the mail it says successfully mail sent but mail took 5 to 6 min to send whyy?

please help me

**Comment by akshaykumar12527** [comment]
What generally happens. Nodemailer enqueue the mail to SMTP server and then SMTP server actually sends that mail and take its own time in managing their queue and processing. If you are using Nodemailer as your smtp client.

**Comment by duplicate2991** [comment]
> @duplicate2991 What generally happens. Nodemailer enqueue the mail to SMTP server and then SMTP server actually sends that mail and take its own time in managing their queue and processing mail queue. If you are using Nodemailer as your smtp client.

Okay Thankyou

**Comment by duplicate2991** [comment]
@akshaykumar12527 
i am using this code ↓

 var nodemailer = require('nodemailer');
    
    var transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.Eid,
    pass: process.env.Epass
  }
});

var mailOptions = {
  from: 'danfeofficial5@gmail.com',
  to: req.body.email,
  subject: `${otp}`,
  html: `<h1> use ${otp} to verify your email address</h1><br><a href="#">Danfe Official</a>`
    }
   transporter.sendMail(mailOptions, function(error, info){
  if (error) {
    console.log(error);
  } else {
    console.log('Email sent: ' + info.response);
  }
      });

is this right?

**Comment by duplicate2991** [comment]
...
