### ISSUE TITLE
Bcc Message Attribute Doesn't Work

### ISSUE THREAD

**Issue by Rmutek** [nodemailer/nodemailer#1534]
I am attempting to create a draft email using nodemailer and the gmail api with someone bcc'd on the draft email. Everything is working as expected: the draft creates with the subject, body text, and attachments however the 'Bcc' field is blank.

Set-up:
```
  const options: any = {
    from: `${Name} <${Email}>`,
    subject: 'Draft Email',
    bcc: 'test@email.com',
    text: 'Add your message here ...',
    attachments: fileAttachments,
    textEncoding: 'base64',
  };

const rawMessage = await createMail(options);
  const draftRes = await gmail.users.drafts.create({
    userId: 'me',
    requestBody: {
      message: {
        raw: rawMessage,
      },
    },
  });
```

dependencies:
"@googleapis/gmail": "^2.0.0",
"nodemailer": "^6.9.2",
"@types/nodemailer": "^6.4.7",

**Comment by andris9** [comment]
Nodemailer drops the BCC header by default and moves these addresses to the SMTP envelope. If you want to keep the header, resd the message compilation docs here: https://nodemailer.com/extras/mailcomposer/#bcc

**Comment by drayilara** [comment]
@andris9 Thanks a lot, that was the correct answer in my case. But a weird feature on the part of nodemailer.
