### ISSUE TITLE
Attachment Issue

### ISSUE THREAD

**Issue by namedx1234** [nodemailer/nodemailer#1536]
So i decided to test the addstringattachment() method  in phpmailer library where content of a file is read and modify and attach to the email body, i did same for nodemailer, by using this code `
the stringStream variable contain a value of pdfbyte codes , simply content of pdf file

let  let pdfsac =   Buffer.from(stringStream).toString('base64');

//so above codes indicate that i converted it to base64 codes

attachments.{
                
                filename: 'name',
                content: stringStream,
                encoding: 'base64',
                
              
              };

then i  sent an email test, i realize that in phpmailer, the size of the file is the exactly the same as original and appears fine , no issue 

but with nodemailer , the size of increase by 80% of the original in the email body and it shows blank , so i'm guessing there is something wrong with  how attachment content in base64 is being added to email body

Please kindly cross check to find out ....

**Comment by namedx1234** [comment]
> So i decided to test the addstringattachment() method in phpmailer library where content of a file is read and modify and attach to the email body, i did same for nodemailer, by using this code ` the stringStream variable contain a value of pdfbyte codes , simply content of pdf file
> 
> let let pdfsac = Buffer.from(stringStream).toString('base64');
> 
> //so above codes indicate that i converted it to base64 codes
> 
> attachments.{
> 
> ```
>             filename: 'name',
>             content: stringStream,
>             encoding: 'base64',
>             
>           
>           };
> ```
> 
> then i sent an email test, i realize that in phpmailer, the size of the file is the exactly the same as original and appears fine , no issue
> 
> but with nodemailer , the size of increase by 80% of the original in the email body and it shows blank , so i'm guessing there is something wrong with how attachment content in base64 is being added to email body
> 
> Please kindly cross check to find out ....

I also tested by encoding both in base64 , saving in .pdf file  and checking the content of both files but i realize in node js is larger than php, at least twice as large ,

**Comment by namedx1234** [comment]
oh that was mistake but same issue,

**Comment by andris9** [comment]
Are you 100% sure that the value is what you expect this to be? If you take `Buffer.from(stringStream)` and save it to a file with `require('fs').writeFileSync('example.pdf', Buffer.from(stringStream))` does the resulting file look like what you expect this to be?

**Comment by namedx1234** [comment]
yes sir , 100% you can try it

**Comment by namedx1234** [comment]
with the help of chatgpt i was able to write some simples thats where i was able to achieve the equilibrium and i save both file in .pdf and they all look the same , but when i tested on nodemailer didnt display pdf file so i download it and check the codes through an editor , it was able to decode it well but the size of the file reduced by 60%

**Comment by namedx1234** [comment]
> Nodemailer has been used in the last 13 years by hundreds of thousands of developers. If it wouldn't be able to do such a simple thing as sending an attachment, surely someone would have noticed it already 10 years ago.
> 
> Try to come up with a self-contained test script that I could run and verify that issue. It should be a single script that I can download and run in my terminal with `node test-script.js`. You can generate SMTP credentials for testing here: https://ethereal.email/ Without being able to replicate the issue myself there is no way I believe the problem is in Nodemailer.

Sure sir , let me show you

**Comment by namedx1234** [comment]
Its done, 
There you go 
```

const nodemailer = require('nodemailer');
const fs = require('fs');
const stream = require('stream');
const util = require('util');
const pipeline = util.promisify(stream.pipeline);


//Here is where i read the file pdf byte codes then write it , in a new file name so technically modified using the normal way of writing file and normal of converting any content to base64.

//Size of the file was 25kb 

let stringStream = fileTaach = fs.readFileSync(`testfile.pdf`, 'utf8');

let pdfsac = Buffer.from(stringStream).toString('base64');

fs.writeFileSync('nodejs-modified.pdf', pdfsac, (err) => {
  if (err) throw err;
  console.log('The file has been saved!');
});



// here i with the help of chat gpt i wrote few lines of codes and tested it  to check after writing it , what will be the size of the file.
// SO correct , i got same size of file as that of php 17kb  using my codes.

async function run() {
    const readStream = fs.createReadStream('testfile.pdf');
    const writeStream = fs.createWriteStream('node-pdf-mycodes.pdf');
    
    await pipeline(
        readStream,
        stream.Transform({
            transform(chunk, encoding, callback) {
                this.push(chunk.toString('base64'));
                callback();
            }
        }),
        writeStream
    );

    console.log('Done writing base64-encoded data to node-pdf-mycodes.pdf');
}

run().catch(console.error);



//So now Here i tried to send an email with it using nodemailer, so file was read and it was used as content in nodemailer attachment

async function sendemail() {
    const readStream = fs.createReadStream('testfile.pdf');
    let base64String = '';
    //ignore the encoding variable there.
    await pipeline(
        readStream,
        stream.Transform({
            transform(chunk, encoding, callback) {
                base64String += chunk.toString('base64');
                callback();
            }
        })
    );

    console.log('Done converting PDF to base64');

    // setup email data
    let mailOptions = {
        from: '"Nodemailer Modules" <jamey.dooley91@ethereal.email>', // sender address
        to: 'xuaks12@yahoo.com', // list of receivers
        subject: 'PDF Attachment', // Subject line
        text: 'Hello, here is your PDF.', // plain text body
        attachments: [
            {
                filename: 'testfile.pdf',
                content: Buffer.from(base64String, 'base64'),
                encoding: 'base64'
            }
        ]
  };
  


    // create reusable transporter object using the default SMTP transport
    let transporter = nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false, // true for 465, false for other ports
        auth: {
            user: 'jamey.dooley91@ethereal.email', // your SMTP username
            pass: '3ZzfJ8sT1kFxzHtJbe' // your SMTP password
        }
    });

    // send mail with defined transport object
    transporter.sendMail(mailOptions, (error, info) => {
        if (error) {
            console.log('Error occurred: ' + error.message);
        }
        console.log('Message sent: %s', info.messageId);
    });
}

sendemail().catch(console.error);


```

**Comment by namedx1234** [comment]
> Nodemailer has been used in the last 13 years by hundreds of thousands of developers. If it wouldn't be able to do such a simple thing as sending an attachment, surely someone would have noticed it already 10 years ago.
> 
> Try to come up with a self-contained test script that I could run and verify that issue. It should be a single script that I can download and run in my terminal with `node test-script.js`. You can generate SMTP credentials for testing here: https://ethereal.email/ Without being able to replicate the issue myself there is no way I believe the problem is in Nodemailer.

```

const nodemailer = require('nodemailer');
const fs = require('fs');
const stream = require('stream');
const util = require('util');
const pipeline = util.promisify(stream.pipeline);


//Here is where i read the file pdf byte codes then write it , in a new file name so technically modified using the normal way of writing file and normal of converting any content to base64.

//Size of the file was 25kb 

let stringStream = fileTaach = fs.readFileSync(`testfile.pdf`, 'utf8');

let pdfsac = Buffer.from(stringStream).toString('base64');

fs.writeFileSync('nodejs-modified.pdf', pdfsac, (err) => {
  if (err) throw err;
  console.log('The file has been saved!');
});



// here i with the help of chat gpt i wrote few lines of codes and tested it  to check after writing it , what will be the size of the file.
// SO correct , i got same size of file as that of php 17kb  using my codes.

async function run() {
    const readStream = fs.createReadStream('testfile.pdf');
    const writeStream = fs.createWriteStream('node-pdf-mycodes.pdf');
    
    await pipeline(
        readStream,
        stream.Transform({
            transform(chunk, encoding, callback) {
                this.push(chunk.toString('base64'));
                callback();
            }
        }),
        writeStream
    );

    console.log('Done writing base64-encoded data to node-pdf-mycodes.pdf');
}

run().catch(console.error);



//So now Here i tried to send an email with it using nodemailer, so file was read and it was used as content in nodemailer attachment

async function sendemail() {
    const readStream = fs.createReadStream('testfile.pdf');
    let base64String = '';
    //ignore the encoding variable there.
    await pipeline(
        readStream,
        stream.Transform({
            transform(chunk, encoding, callback) {
                base64String += chunk.toString('base64');
                callback();
            }
        })
    );

    console.log('Done converting PDF to base64');

    // setup email data
    let mailOptions = {
        from: '"Nodemailer Modules" <jamey.dooley91@ethereal.email>', // sender address
        to: 'xuaks12@yahoo.com', // list of receivers
        subject: 'PDF Attachment', // Subject line
        text: 'Hello, here is your PDF.', // plain text body
        attachments: [
            {
                filename: 'testfile.pdf',
                content: Buffer.from(base64String, 'base64'),
                encoding: 'base64'
            }
        ]
  };
  


    // create reusable transporter object using the default SMTP transport
    let transporter = nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false, // true for 465, false for other ports
        auth: {
            user: 'jamey.dooley91@ethereal.email', // your SMTP username
            pass: '3ZzfJ8sT1kFxzHtJbe' // your SMTP password
        }
    });

    // send mail with defined transport object
    transporter.sendMail(mailOptions, (error, info) => {
        if (error) {
            console.log('Error occurred: ' + error.message);
        }
        console.log('Message sent: %s', info.messageId);
    });
}

sendemail().catch(console.error);

```

Thats it , sir

**Comment by namedx1234** [comment]
Incase you're good with php too, u can try it
```
<?php

//So here is that of php 
//First line of codes is to read the file and save it 
//Here this codes was able to save the pdf file modified as that of one i used my codes.
$filetaguser = 'testfile.pdf';
$attahcedfile = file_get_contents($filetaguser);
$attachRandoms = file_put_contents('php-modified.pdf', base64_encode($attahcedfile));


/// The codes below now after saving it i decided to use as an attachement , it did work well and everything appear in the email box very nice
//hence no issue 

require_once 'HOST/src/Exception.php';
require_once 'HOST/src/PHPMailer.php';
require_once 'HOST/src/SMTP.php';


$mail = new PHPMailer\PHPMailer\PHPMailer();

try {
    //Server settings
$mail = new PHPMailer\PHPMailer\PHPMailer();
$mail->IsSMTP();  
$mail->SMTPDebug = 0; // Enable verbose debug output 
$mail->Host       = 'smtp.ethereal.email'; // Set the SMTP server to send through
$mail->SMTPAuth   = true; // Enable SMTP authentication
$mail->Username   = 'jamey.dooley91@ethereal.email'; // SMTP username
$mail->Password   = '3ZzfJ8sT1kFxzHtJbe'; // SMTP password
$mail->SMTPSecure = false; // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged
$mail->Port       = 587; // TCP port to connect to, use 587 for `PHPMailer::ENCRYPTION_STARTTLS` above

//Recipients
$mail->setFrom('jamey.dooley91@ethereal.email', 'John Doe');
$mail->addAddress('xuaks12@yahoo.com', 'Jane Doe');
$mail->addReplyTo('example@gmail.com', 'Information');

// Content
$mail->isHTML(true); // Set email format to HTML
$mail->Subject = 'Subject of the email';
$mail->Body    = 'This is the HTML message body in bold!';
$mail->AltBody = 'This is the plain text version of the email content for non-HTML mail clients';
$mail->addStringAttachment($attachRandoms, 'names.pdf', 'base64');

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}

?>
```

**Comment by namedx1234** [comment]
kindly use any pdf file but one in the pdf byte code

**Comment by namedx1234** [comment]
so should i sent you my attachment file u try that too, ?

> I tested your script and found out that Nodemailer sends the attachment correctly but the generated attachment itself is invalid.
> 
> I modified the script like this:
> 
> ```js
>     fs.writeFileSync('output.pdf', Buffer.from(base64String, 'base64')) // <-- added this line before `sendMail` to see what Nodemailer is actually sending
> 
>     transporter.sendMail(mailOptions, (error, info) => { 
> ```
> 
> and then compared the md5 hash of output.pdf and the file I received as an attachment and it matched. Both output.pdf and the received attachment were invalid PDF files, so your script did something wrong with these as the input PDF was correct.

So should i send you my attachment file you try that too? because its a general issue, same thing , the file appeared invalid and cannot be opened or it doesnt display the attachment file and yes you're correct files appeared invalid

**Comment by namedx1234** [comment]
> 

I think my codes did worked there was little issue in the variable on the first side, thats the writing the file and also instead of passing the base64content variable i did re encode it again, so it didnt as previously however , using the first lines of code you sent me in writing and encoding in base64 didnt work..

**Comment by namedx1234** [comment]
> I tested your script and found out that Nodemailer sends the attachment correctly but the generated attachment itself is invalid.
> 
> I modified the script like this:
> 
> ```js
>     fs.writeFileSync('output.pdf', Buffer.from(base64String, 'base64')) // <-- added this line before `sendMail` to see what Nodemailer is actually sending
> 
>     transporter.sendMail(mailOptions, (error, info) => { 
> ```
> 
> and then compared the md5 hash of output.pdf and the file I received as an attachment and it matched. Both output.pdf and the received attachment were invalid PDF files, so your script did something wrong with these as the input PDF was correct.

If you want to verify , replace the base64String variable with the pdfsac variable coming from the firt block of codes and send email , you will notice that it wont work or display well . However if you use the base64String variable and send an email, it will display well ,

**Comment by andris9** [comment]
From my point of view you are providing invalid input for Nodemailer and thus it sends an invalid attachment. Why this input is invalid etc is out of scope for Nodemailer.

**Comment by namedx1234** [comment]
yes it i realize it isnt nodemailer issue , it rather coming from node js modules,

**Comment by namedx1234** [comment]
> From my point of view you are providing invalid input for Nodemailer and thus it sends an invalid attachment. Why this input is invalid etc is out of scope for Nodemailer.

Thank you very much sir

**Comment by namedx1234** [comment]
> From my point of view you are providing invalid input for Nodemailer and thus it sends an invalid attachment. Why this input is invalid etc is out of scope for Nodemailer.

Sir why dont you add a method like addstringattachment () like that of phpmailer in nodemailer because after reading and modifying the file , the size of the file is affected or there is encoding issue,  so it end not showing well, i hv sample file i can send you to try

**Comment by namedx1234** [comment]
I tested the same logic and file on phpmailer, it did read it well and replace the necessary tags with the value i put there and added it nicely to the email body , but for nodemailer i used content property and passed the modified value as base64 , it didnt work , the size of the file increased or decrease
