### ISSUE TITLE
[bug] `this._remainder` is not being used when connection is closed/ended

### ISSUE THREAD

**Issue by titanism** [nodemailer/nodemailer#1541]
When `_onClose` function is invoked and `this.destroyed` is `false`, then the following logic is performed:

<https://github.com/nodemailer/nodemailer/blob/c77d70f6ed885695e7778f9604591f48f852e817/lib/smtp-connection/index.js#L827-L831>

However there is an error here in that `this._remainder` is not processed, since `this._processResponse()` was not invoked as the return value.  Instead the return value is `return this._onError(new Error('Connection closed unexpectedly'), 'ECONNECTION', false, 'CONN');`.

This poses an error because some large senders like Apple/iCloud have a `this._remainder` value of `'454 4.3.0 Try again later'`.  Because of this, this error is not bubbled up to the client transporter, and therefore the user has no idea the `454 4.3.0 Try again later` error has occurred; just a generic socket "Connection closed unexpectedly" error.

**Comment by andris9** [comment]
That's a great find. Do you have any transaction logs or anything to see when exactly this happens? Like immediately after connecting or as a response to a command or out of normal protocol exchange?

**Comment by andris9** [comment]
Could you check if the last commit fixes this issue for you: https://github.com/nodemailer/nodemailer/commit/707f2b1c6a12ea597f25f14d3f9e0fd8ad07c47a

**Comment by doublee101** [comment]
can mealer-deamon or bounce massages be redirected to a log folder here and not on the smtp mailbox???
