### ISSUE TITLE
legacy sigalg disallowed or unsupported in node 18

### ISSUE THREAD

**Issue by sandipsk-git** [nodemailer/nodemailer#1542]
im migrating code from node 16 to node 18.trying to send mail using nodemailer but showing `SSL routines:tls_process_key_exchange:legacy sigalg disallowed or unsupported:../deps/openssl/openssl/ssl/statem/statem_clnt.c` . its working fine with node 16 . im using 6.9.2  version.

**Comment by andris9** [comment]
Which SMTP server are you connecting to? Most probably the server uses outdated ciphers (or you have a MITM like virus scanner intercepting SMTP connections and using outdated ciphers)

**Comment by sandipsk-git** [comment]
> connecting

I'm using private smtp server .I tested by turning off network scanning.its working fine in node 16 in same environment.just got this error while using  node 18 on ubunut 20.04.

**Comment by andris9** [comment]
In any case, this error is from the Nodejs OpenSSL stack. Nodemailer uses openssl to open a TLS connection to your server, and the upgraded OpenSSL in Node 18 refuses to use the TLS setup your server provides.
