### ISSUE TITLE
Error sending email: Error: Invalid login: 535-5.7.8 Username and Password not accepted

### ISSUE THREAD

**Issue by anoosha503** [nodemailer/nodemailer#1544]
Please file only reproducible bugs. Everything else will get ignored.

When I click Reset button I need to receive the reset link to my email but now I am not receiving

See the FAQ for existing known issues [here](https://github.com/nodemailer/nodemailer#having-an-issue) before you submit a new one.

This my server side configaration in angular

' const express = require('express');
const bodyParser = require('body-parser');
const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const nodemailer = require('nodemailer');
const { Date } = require('core-js');
const cors = require('cors');
const { randomBytes } = require('crypto');

// Connect to MongoDB
mongoose.connect('mongodb://localhost:27017/angular-auth', { useNewUrlParser: true, useUnifiedTopology: true });
mongoose.connection.on('error', console.error.bind(console, 'MongoDB connection error:'));

// Define the user schema
const userSchema = new mongoose.Schema({
  name: String,
  email: String,
  phone: Number,
  dob: { type: Date },
  password: String,
});

// Create the user model
const User = mongoose.model('User', userSchema);

// Create the Express app
const app = express();

// Enable CORS for all routes
app.use(cors());
// Parse incoming JSON requests
app.use(bodyParser.json());

// Create a nodemailer transporter (you need to configure it with your email provider)
const transporter = nodemailer.createTransport({
  service: 'Gmail',
  auth: {
    user: 'abc@gmail.com',
    pass: 'YourPasswordHere',
  },
});

// Function to send the reset password email
function sendResetPasswordEmail(email, resetToken) {
  const mailOptions = {
    from: 'abc@gmail.com',
    to: email,
    subject: 'Reset Password',
    text: `Click the following link to reset your password: http://your-website.com/reset-password?token=${resetToken}`,
  };

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.error('Error sending email:', error);
    } else {
      console.log('Email sent:', info.response);
    }
  });
}

// Handle registration endpoint
app.post('/api/register', async (req, res) => {
  const { name, email, phone, dob, password } = req.body;
  try {
    const hashedPassword = await bcrypt.hash(password, 10);
    const user = new User({ name, email, phone, dob, password: hashedPassword });
    await user.save();
    res.json({ success: true });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Error registering user' });
  }
});

// Handle login endpoint
app.post('/api/login', async (req, res) => {
  const { email, password } = req.body;
  try {
    const user = await User.findOne({ email });
    if (!user) {
      res.status(401).json({ error: 'Invalid email or password' });
      return;
    }
    const isPasswordValid = await bcrypt.compare(password, user.password);
    if (!isPasswordValid) {
      res.status(401).json({ error: 'Invalid email or password' });
      return;
    }
    res.json({ success: true });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Error logging in' });
  }
});

// Handle password reset request
app.post('/api/forgot-password', async (req, res) => {
  const { email } = req.body;
  try {
    const user = await User.findOne({ email });
    if (!user) {
      res.status(404).json({ error: 'User not found' });
      return;
    }

    // Function to generate a random reset token
    function generateResetToken(length = 20) {
      const buffer = randomBytes(Math.ceil(length / 2));
      const resetToken = buffer.toString('hex').slice(0, length);
      return resetToken;
    }

    // Generate a reset token
    const resetToken = generateResetToken();

    // Save the reset token and expiry in the user document
    user.resetToken = resetToken;
    user.resetTokenExpiry = Date.now() + 3600000; // Token expires in 1 hour
    await user.save();

    // Send the reset password email with a link containing the reset token
    sendResetPasswordEmail(user.email, resetToken);

    res.json({ success: true });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Error sending reset password email' });
  }
});

// Start the server
const port = 3000;
app.listen(port, () => {
  console.log(`Server running on http://localhost:${port}`);
});
'
Facing Issue Like 
   
<img width="748" alt="image" src="https://github.com/nodemailer/nodemailer/assets/120091131/eb057d1b-4f2a-4afd-bec9-6f00c42e3dec">

**Comment by Vinyas-S** [comment]
@anoosha503, use a "password" instead of "pass" in your transporter

**Comment by anoosha503** [comment]
Hi,@Vinyas-S I changed that as You said above but still facing issue 

<img width="616" alt="image" src="https://github.com/nodemailer/nodemailer/assets/120091131/e1ab36f0-3ae5-442d-bec0-d9e95f02b3fa">

**Comment by amasoft** [comment]
Hi @anoosha503, kindly check this option;

Since your using Gmail it seems you enabled 2 step authentication on the account so do this:

1 sign in your Gmail account.
2. Create an app password.
3.go to your nodemailer.createTransport({
pass:"your 16 digit app password here"
}) and replace the pass with "16 digit app password"


To generate the app password follow this steps:
a. Sign in your Gmail account
 b. Go to manage account.
c.in the search bar:type app password (select the one under security)
d. you will be directed to app passwords,go to select app and choose other(custom name)
e. give it a name e.g mailapp  and click on generate
f. You will see your password(mainly on pale yellow background and 16 digit in number) copy it and paste as directed above(no 3).
Thanks

**Comment by ShanthiniMM** [comment]
> Hi @anoosha503, kindly check this option;
> 
> Since your using Gmail it seems you enabled 2 step authentication on the account so do this:
> 
> 1 sign in your Gmail account. 2. Create an app password. 3.go to your nodemailer.createTransport({ pass:"your 16 digit app password here" }) and replace the pass with "16 digit app password"
> 
> To generate the app password follow this steps: a. Sign in your Gmail account b. Go to manage account. c.in the search bar:type app password (select the one under security) d. you will be directed to app passwords,go to select app and choose other(custom name) e. give it a name e.g mailapp and click on generate f. You will see your password(mainly on pale yellow background and 16 digit in number) copy it and paste as directed above(no 3). Thanks

Thank you so much. It woked :)

**Comment by anooshaacl** [comment]
> 

Thank you so much. It woked
