### ISSUE TITLE
Nodemailer Not sending mail in cpanel 

### ISSUE THREAD

**Issue by richardebrain** [nodemailer/nodemailer#1545]
So, i hosted my website using cpanel and i used my cpanel email along with nodemailer to send mail but whenever i send the mail i get the error  both using cpanel email and gmail 

**"connect ECONNREFUSED **.49.171.***:465**
`
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";
const nodemailer = require("nodemailer");
const dotenv = require("dotenv");
dotenv.config();
type Data = {
  message: string;
};

const password = process.env.NEXT_PUBLIC_GMAIL_PASS;
const username = process.env.NEXT_PUBLIC_GMAIL_USERNAME;

const handler = async (req: NextApiRequest, res: NextApiResponse<Data>) => {
  let transporter = nodemailer.createTransport({
    host: "mail.****.com.ng",
    secure: true,
    port: 465,
    auth: {
      user: username,
      pass: password,
    },
    tls: {
      rejectUnauthorized: false,
    },
  });
  const message = {
    from: req.body.email,
    to: "enquiries@****.com.ng",
    subject: "New Customer Setup",
    text: `${req.body.email} ${req.body.firstName} ${req.body.lastName}`,
    html: `
    <p>Name: ${req.body.firstName} ${req.body.lastName}</p>
    <p>Email: ${req.body.email}</p>
    <p>Phone Number: ${req.body.mobileNumber}</p>
    <p>Residential Address: ${req.body.residentialAddress}</p>
    <p>Gender: ${req.body.gender?.value}</p>
    <p>Date of Birth: ${req.body.dob}</p>
  `,
  };
  if (
    !req.body.email ||
    !req.body.firstName ||
    !req.body.lastName ||
    !req.body.mobileNumber ||
    !req.body.residentialAddress ||
    !req.body.gender?.value
  ) {
    res.status(400).json({
      message: "Bad Request",
    });
  } else {
    await transporter.sendMail(message, (err: any, info: any) => {
      if (err) {
        console.log(err, "err");
        res.status(500).json({
          message: err.message +' fuck this'|| "An error occurred while sending the email.",
        });
      } else {
        res.status(200).json({
          message: info,
        });
      }
    });
  }
};

export default handler;
`
note: this works locally and even with gmail .
how do i fix this ?

**Comment by richardebrain** [comment]
> So, i hosted my website using cpanel and i used my cpanel email along with nodemailer to send mail but whenever i send the mail i get the error both using cpanel email and gmail
> 
> __"connect ECONNREFUSED **.49.171.**_:465_* ` // Next.js API route support: https://nextjs.org/docs/api-routes/introduction import type { NextApiRequest, NextApiResponse } from "next"; const nodemailer = require("nodemailer"); const dotenv = require("dotenv"); dotenv.config(); type Data = { message: string; };
> 
> const password = process.env.NEXT_PUBLIC_GMAIL_PASS; const username = process.env.NEXT_PUBLIC_GMAIL_USERNAME;
> 
> const handler = async (req: NextApiRequest, res: NextApiResponse) => { let transporter = nodemailer.createTransport({ host: "mail.**.com.ng", secure: true, port: 465, auth: { user: username, pass: password, }, tls: { rejectUnauthorized: false, }, }); const message = { from: req.body.email, to: "enquiries@**.com.ng", subject: "New Customer Setup", text: `${req.body.email} ${req.body.firstName} ${req.body.lastName}`, html: `<p>Name: ${req.body.firstName} ${req.body.lastName}</p> <p>Email: ${req.body.email}</p> <p>Phone Number: ${req.body.mobileNumber}</p> <p>Residential Address: ${req.body.residentialAddress}</p> <p>Gender: ${req.body.gender?.value}</p> <p>Date of Birth: ${req.body.dob}</p>`, }; if ( !req.body.email || !req.body.firstName || !req.body.lastName || !req.body.mobileNumber || !req.body.residentialAddress || !req.body.gender?.value ) { res.status(400).json({ message: "Bad Request", }); } else { await transporter.sendMail(message, (err: any, info: any) => { if (err) { console.log(err, "err"); res.status(500).json({ message: err.message +' fuck this'|| "An error occurred while sending the email.", }); } else { res.status(200).json({ message: info, }); } }); } };
> 
> export default handler; ` note: this works locally and even with gmail . how do i fix this ?

**Comment by andris9** [comment]
As the error states - you can’t connect to that host and port from your server. Maybe the hosting provider blocks email connections? There is nothing that Nodemailer could do to overcone this.

**Comment by richardebrain** [comment]
You have any idea on how to overcome this ?

**Comment by richardebrain** [comment]
> As the error states - you can’t connect to that host and port from your server. Maybe the hosting provider blocks email connections? There is nothing that Nodemailer could do to overcome this.

I have got it working , my hosting provider already configured the host on their end , all i just did was changed the host to 'localhost'
