### ISSUE TITLE
Error: Invalid login: 535-5.7.8 Username and Password not accepted

### ISSUE THREAD

**Issue by AliAsgharRanjbar** [nodemailer/nodemailer#1550]
**I saw the issue alike mine in the issues section.**

Error: 

_code: 'EAUTH',
response: '535-5.7.8 Username and Password not accepted. Learn more at\n' +
  '535 5.7.8  https://support.google.com/mail/?p=BadCredentials e14-20020adfef0e000000b0030c2e3c7fb3sm10043909wro.101 - gsmtp',
responseCode: 535,
command: 'AUTH PLAIN'
}_

**But my problem is different.**

I know and I use the app password to login to my Gmail account, but the problem is when I create a Gmail account and using an existing 
email instead of Gmail address (or simply add an alternative email address to my google account) and trying to sign in with that email address, I get the error.

Note: I can sign in with the alternative email in the accounts.google.com, But can't do this in nodemailer.

**Comment by cardinal-II** [comment]
I have the same issue.
