### ISSUE TITLE
SendinBlue renamed to Brevo

### ISSUE THREAD

**Issue by Melvinvmegen** [nodemailer/nodemailer#1554]
Hello, 

First of all thank you guys for the good work,  please keep doing 👍🏻.

Quick remininder: As of the **30th of august 2023**, Sendinblue's smtp will change to their new domain name : **brevo**.

After a quick scan of the code i noticed one file that's concerned (their might be others) : https://github.com/nodemailer/nodemailer/blob/master/lib/well-known/services.json 

Which should be updated to support the new domain name smtp : **smtp-relay.brevo.com**.

However you want it to be done, please do it before the **30th of august 2023**.

Thanks !

**Comment by andris9** [comment]
Updated in nodemailer@6.9.4
