### ISSUE TITLE
Can’t send mail - all recipients were rejected

### ISSUE THREAD

**Issue by DimaDyachenko** [nodemailer/nodemailer#1555]
**Summary:**
I am encountering an issue while attempting to send a large number of emails, where an error message appears stating, "Can’t send mail - all recipients were rejected: 550-Requested action not taken: mailbox unavailable 550 Failure sending mail. Try again later." However, I have observed that after waiting for approximately 30 minutes, I am able to resend the same number of messages without encountering the error.

**Steps to Reproduce:**

1. Compose a large number of emails (n messages).
2. Attempt to send the emails to multiple recipients.
3. Encounter the error message: "Can’t send mail - all recipients were rejected: 550-Requested action not taken: mailbox unavailable 550 Failure sending mail. Try again later."

**Expected Behavior:**
The emails should be sent successfully without any errors or rejections.

**Actual Behavior:**
Sending a large number of emails results in an error message, and all recipients are rejected with error code 550.

**Comment by andris9** [comment]
The server you are trying to use for sending emails rate limits you and does not allow sending these emails. Get a better provider.
