### ISSUE TITLE
Facing issue while sending AMP email using nodemailer version 6.9.4 

### ISSUE THREAD

**Issue by shubh-am8** [nodemailer/nodemailer#1562]
Hey folks,

i am new to amp emails , and trying to send a valid amp template programatically but unable to achieve this   
i am sharing a simple snippet that i am using for testing having basic example of amp email but still getting html in my gmail inbox. Please help me out to achieve my goal i didn't understand whats wrong here in my code or tell me if i am doing someting wrong in this code

`let mailOptions = {
    from: 'TEST AMP EMAIL <mail@XXXX.com>',
    to: maillist,
    subject: 'AMP4EMAIL message',
    text: 'For clients with plaintext support only',
    html: '<p>For clients that do not support AMP4EMAIL or amp content is not valid</p>',
    amp: <!doctype html>
    <html ⚡4email>
      <head>
        <meta charset="utf-8">
        <style amp4email-boilerplate>body{visibility:hidden}</style>
        <script async src="https://cdn.ampproject.org/v0.js"></script>
        <script async custom-element="amp-anim" src="https://cdn.ampproject.org/v0/amp-anim-0.1.js"></script>
      </head>
      <body>
        <p>Image: <amp-img src="https://cldup.com/P0b1bUmEet.png" width="16" height="16"/></p>
        <p>GIF (requires "amp-anim" script in header):<br/>
          <amp-anim src="https://cldup.com/D72zpdwI-i.gif" width="500" height="350"/></p>
      </body>
    </html>
}`

My trasnpoter code is 

`let transporter = nodemailer.createTransport({
    host: "smtp.xxxx.in",
    secure: true,
    port: 465,
    auth: {
        user: "mail@xxxx.com",
        pass: "PASSSSSSSSS",
    },
    logger: true, // log to console
    debug: true // include SMTP traffic in the logs
});
`
And finally my send email function is 

`async function sendEmail() {
    transporter.sendMail(mailOptions, (error, info) => {
        if (error) {
            console.error('Error:', error);
        } else {
            console.log('Email sent:', info.response);
        }
    });
}`

**Comment by andris9** [comment]
Do you meet the requested requirements to send AMP emails? https://developers.google.com/gmail/ampemail/testing-dynamic-email

**Comment by HariAcharya80** [comment]
@shubh-am8 although it's been a while, was the issue solved or it still exists?
