### ISSUE TITLE
nodemailer with vercel edge runtime fails due to 'stream' dependency

### ISSUE THREAD

**Issue by madhurjain** [nodemailer/nodemailer#1563]
Due to nodemailer's dependency on Node.js 'stream' module, it doesn't work with vercel's edge runtime

```
The edge runtime does not support Node.js 'stream' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
```
https://nextjs.org/docs/messages/node-module-in-edge-runtime

**Comment by andris9** [comment]
Edge functions only work with front end modules. None of the backend Node apis that Nodemailer requires and can’t function without are supported there.

**Comment by MickL** [comment]
> Edge functions only work with front end modules. None of the backend Node apis that Nodemailer requires and can’t function without are supported there.

Thats not entirely true. Servers like H3 (the one that Nuxt uses) are supposed to run on Edge Workers and for example Cloudflare or Deno Deploy doesnt even provide normal serverless functions, only edge worker functions.

Many libraries, like Axios, dont work on workers but this is because of what API they use. In case of Axios they would switch to fetch() it would work on edge workers.

**Comment by sheecegardezi** [comment]
> Edge functions only work with front end modules. None of the backend Node apis that Nodemailer requires and can’t function without are supported there.

can you be a bit specfic please ..

The error that get thrown when you try to install nodemailer on cloudflare worker are so random ... it is hard to figure out exactly which part of code is the issue!

from this file:

https://github.com/nodemailer/nodemailer/blob/master/lib/smtp-connection/http-proxy-client.js

I can confirm that these modules

```
const net = require('net');
const tls = require('tls');
const urllib = require('url');
```

are now available on edge functions. It would be helpful to start a discussion around what modules are actully the issue.

**Comment by willemmulder** [comment]
@andris9 Would it make sense to investigate which modules are and are not supported on the edge runtime? It might turn out that we don't need that many changes to make it work?
