### ISSUE TITLE
nodemailer.com is blocked by Firewall on request from SOC

### ISSUE THREAD

**Issue by Nol-go** [nodemailer/nodemailer#1565]
Problem
---------

Various SOC have detected the ip's 188.114.97.2 & 188.114.96.2 to be unsecure because lot's of suspicious and unsafe websites are hosted there by cloudflare. It's the case for my company which means I cannot access the documentation anymore.  
Could you please check with your hosting service to do something about this.  
You're not the only one to have this problem, pugjs also has the same problem as it's also hosted by cloudflare. 

Reproduce
------------

- be a employe at a company
- have a firewall managed by a SOC
- go to nodemailer.com
- have timeout because 188.114.97.2 & 188.114.96.2 are blocked by firewall

Impact:
---------

- cannot access documentation
- website traffic going down

Proof
------

global traffic rank for nodemailer.com (I couldn't get the traffic graph but that big of a drop is not caused by other website gaining more incomming traffic):

![image](https://github.com/nodemailer/nodemailer/assets/90242082/b9fde18c-d43a-4347-8764-f4787aa49b7e)

**Comment by Nol-go** [comment]
I know this is not a code specific problem, but I didn't know how to notify you of this.

**Comment by andris9** [comment]
Disabled Cloudflare proxying. Could you check if you can access the site now?

**Comment by Nol-go** [comment]
yep it works very well

**Comment by Nol-go** [comment]
Hi @andris9,
We (my team and I) looked into it a bit more and found out the SOC made an error and inverted the domain name and IP fields in their form so we ended up blocking the IP instead of the Domain. It has been fixed on our side. You should turn cloudflare back on as the problem isn't on your/cloudflare's end but on ours.

Still, thanks a lot for the quick hot fix of disableing cloudflare. I managed to get the info I needed thanks to that.
