### ISSUE TITLE
CC emails not working if we specify mutiple emails instead of single.

### ISSUE THREAD

**Issue by that-spy-kid** [nodemailer/nodemailer#1567]
CC emails Woking if:
-> 'cc_recipient1@example.com'
->['cc_recipient1@example.com']

Not working if :
-> 'cc_recipient1@example.com, cc_recipient2@example.com'
-> ['cc_recipient1@example.com', 'cc_recipient2@example.com']

**Comment by that-spy-kid** [comment]
Provide me a fesible soultions for above case, would be appreciated

**Comment by that-spy-kid** [comment]
const transport = nodemailer.createTransport( nodemailerMailjet({}) );
const email = new Email({views: {}, message: {}, preview: false, send: true, transport: transport,});
email.send({});


Using in Email-templates npm package with nodemailer as a mailer.

**Comment by andris9** [comment]
You should probably check it with the email templates project, Nodemailer can send to multiple cc addresses just fine.
