### ISSUE TITLE
Promise for sendMail is not resolved or rejected 

### ISSUE THREAD

**Issue by sreejithag** [nodemailer/nodemailer#1569]
Iam facing an issue with the package sometimes the sendMail  function promise is never resolved or rejected 

To debug the issue i have added the debug mode and found that i am receiving the connection success message like 

``
{
  component: 'smtp-connection',
  sid: 'Everr7uIX30',
  tnx: 'network',
  localAddress: 'x.x.x.x',
  localPort: 56930,
  remoteAddress: 'x.x.x.x',
  remotePort: 587
} %s established to %s:%s Connection x.x.x.x 587
``

and after that the network connection is getting closed within few millisec 

``{ component: 'smtp-connection', sid: 'Everr7uIX30', tnx: 'network' } Connection closed``

in this case the promise is never resolved or rejected 

Iam currently using old version of the package 4.0.1

Is it happening due to any bugs which has been fixed already or any information to debug this 
further ?

**Comment by andris9** [comment]
Please upgrade to the latest version of Nodemailer and try again. If the issue persists, could you let me know about it?

**Comment by sreejithag** [comment]
Thanks 
issue has been resolved with latest version
