### ISSUE TITLE
Documentation needed for using mx-connect with SMTP pooling

### ISSUE THREAD

**Issue by titanism** [nodemailer/nodemailer#1575]
Hi there @andris9 - curious if you can shed light here on how to use `mx-connect` in combination with SMTP pooling.

For example:

```js
const ms = require('ms');
const mxConnect = require('mx-connect');
const pify = require('pify');

const asyncMxConnect = pify(mxConnect);

const mx = await asyncMxConnect({
  target: '...'
});

const transporter = nodemailer.createTransport({
  pool: true,
  connection: mx.socket
});
```

It appears that it won't re-use the connection/socket - and instead it will create a new one.  Do we need to override the `getSocket` method perhaps?

```js
const transporter = nodemailer.createTransport({
  pool: true,
  getSocket: function(options) {
    return mx.socket
  }
});
```

However, this appears as if it would not work, since a new SMTPConnection would still be created:

<https://github.com/nodemailer/nodemailer/blob/fdc7c27bd20d475462c2102de7a820b97e22222d/lib/smtp-pool/pool-resource.js#L97C45-L97C45>

There is the concept of a "proxied" connection here as well that could be better documented: <https://github.com/nodemailer/nodemailer/blob/fdc7c27bd20d475462c2102de7a820b97e22222d/lib/smtp-pool/pool-resource.js#L74-L97>

Ref: https://github.com/nodemailer/nodemailer/issues/1516

**Comment by andris9** [comment]
You can use the `getSocket` method like this:
```js
let transporter = nodemailer.createTransport({
    pool: true,
    maxConnections: 2,
    host: 'ethereal.email',
    port: 25,
    logger: true,
    debug: true,
    getSocket(opts, callback) {
        mxConnect(opts.host, (err, connection) => {
            if (err) {
                return callback(err);
            } else {
                return callback(null, { connection: connection.socket });
            }
        });
    }
});
```

But I would not suggest using it. Nodemailer pooling is designed to run against a static target, e.g. the SMTP host of Gmail. If you are connecting to MX servers, each connection can be against a different server and using Nodemailer's pooling probably causes more issues than it helps. For example, it tries to keep connections open as long as possible. There are also TLS issues (Nodemailer expects the hostname of the connected socket to be whatever is set as the `host` property in the transporter config), etc. This is why I only use mx-connect with the [SMTPConnection](https://nodemailer.com/extras/smtp-connection/) object but not with Nodemailer transporters.
