### ISSUE TITLE
Connect smtp connection through ssh 

### ISSUE THREAD

**Issue by nerdiclan** [nodemailer/nodemailer#1576]
Sir  I'm trying to tunnel smtp connection through ssh using ssh2 module , i want to know if its possible because its not working for me, In other words forward smtp connection through ssh

**Comment by andris9** [comment]
SSH can be used as a SOCKS proxy and Nodemailer can connect to these proxies https://nodemailer.com/smtp/proxies/#1-using-http-proxy

**Comment by nerdiclan** [comment]
please check my codes , it didnt work , uncomnent the proxy and the transport.set('proxy_socks_module', require('socks'))
I use chilkat email library it works but not with nodemailer, i use the ssh2 to create ssh connection and connect to the smtp, it works however the receive header still show the local machine ip but with chilkat it connects fine and show the ssh ip in the receive headers nicely
```
const nodemailer = require('nodemailer');
const { Client } = require('ssh2');

// create an SSH tunnel
const tunnel = new Client();
tunnel.on('ready', () => {
  console.log('SSH tunnel established');
  // create a Nodemailer transport object using the SSH tunnel
  let transport = nodemailer.createTransport({
    host: 'smtp.ethereal.email',
    port: 587,
    secure: false,
    proxy: `http://5.182.39.25:22@root:5fs6vZ7tfR3C`,
    requireTLS: true,
     tls: {
        rejectUnauthorized: false
      },
 auth: {
    user: 'nathaniel61@ethereal.email',
    pass: 'pXHzE83skwPUfXtU2n',
  }
  });
  transport.set('proxy_socks_module', require('socks'))
  // send an email using the transport object
  transport.sendMail({
    from: 'nathaniel61@ethereal.emai',
    to: 'receive@gmail.com',
    subject: 'Test email',
    text: 'This is a test email sent over an SSH tunnel'
  }, function(error, info) {
    if (error) {
      console.log(error);
    } else {
      console.log('Email sent: ' + info.response);
    }
    // close the SSH tunnel
    tunnel.end();
  });
}).connect({
  host: '5.182.39.25',
  port: 22,
  username: 'root',
  password: '5fs6vZ7tfR3CNICE'
});

```

**Comment by nerdiclan** [comment]
> SSH can be used as a SOCKS proxy and Nodemailer can connect to these proxies https://nodemailer.com/smtp/proxies/#1-using-http-proxy

do you think i should make it ssh:// instead?
