### ISSUE TITLE
The available file name length of the attachment is too short

### ISSUE THREAD

**Issue by zhantewei2** [nodemailer/nodemailer#1577]
I found that the file name of the attachment was automatically truncated, causing me not to send the full file name。

And I tried to use raw to pass buffer.
```js
const fileBuf=await fs.readFile(path.resolve(outputPath,file));

attachments.push( {
    raw: Buffer.concat([
      Buffer.from("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\r\n"+
      `Content-Disposition: attachment;filename=${file}\r\n`+
      "\r\n"),
      fileBuf
   ])
```
Buf it not work...
So I can't keep the attachment with the full file name

**Comment by andris9** [comment]
It is probably truncated by the recipient. Try different email clients/targets to see how different mail clients/mail services treat that filename, is it shown fully or is it truncated.

**Comment by zhantewei2** [comment]
@andris9 IThis occurs when the file name contains Chinese。

**Comment by andris9** [comment]
You can't use `..;filename=${file}\r\n` with non-Latin characters. The value in the header needs to be encoded. Nodemailer handles encodings automatically but not if you use the `raw` option.

To try it out, send the same email to different addresses (Gmail, QQ, Outlook, yahoo etc). Do not use the `raw` option, but regular `filename`+`content`. See if all these services fail to properly process the filename or not.

**Comment by zhantewei2** [comment]
I started use `filename` property.
But its name gets truncated when I use  **foxmail** on mac  as a client to view mail。
So I tried to build filename myself with raw..
And `Content-Disposition: attachment; filename*="utf-8''${file}\r\n` can work will.
But raw can only accept string, can you consider accepting buffer? Because someone need to transfer binary files
