### ISSUE TITLE
`Return-Path` is  `<>`

### ISSUE THREAD

**Issue by uwinkler** [nodemailer/nodemailer#1581]
The `Return-Path` header is empty `<>` but should contain an email address

Nodemailer version is 6.9.6.

I tried using envelop:

```js
    envelope: {
      from: 'Johny <johny@gmail.com>', // or '<johny@gmail.com>' or 'johny@gmail.com'
      to: 'somebody@gmail.com'
    },
```

and headers like:

```js
    headers: {
      'Return-Path': 'Johny <johny@gmail.com>' // or '<johny@gmail.com>' or 'johny@gmail.com'
    },
```

**Comment by andris9** [comment]
Return-Path is never set by the client, always by the server. You can not set it using Nodemailer - if you set such a header, the server will most likely just remove it.

**Comment by uwinkler** [comment]
I am using gmail as server. If I send an email using the Apple Mail Desktop app the header `Return Path` is set. So what is Apple Mail doing differently?

**Comment by uwinkler** [comment]
Thxs @andris9  for you input and your help.

I got it. For reference: if you are using gmail as your provider you have to set the `from` field to `Johny <johyn@gmail.com>`, like so: 

```js
transporter.sendMail( {
    to: 'somebody@gmail.com'
    from: 'Johny <johyn@gmail.com>' // 'johny@gmail.com' does not work and the Return-Path is empty
})
```
