### ISSUE TITLE
ssl3_get_record:wrong version number but connection works using openssl 

### ISSUE THREAD

**Issue by rathourarv** [nodemailer/nodemailer#1582]
I am using nodemailer(version - 6.9.6) with email-templates and am able to send an email using secure as false when I try to enable TLS for the same but getting the below error - 

```
SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:355
```

I am using the below openssl command to verify if the SMTP server supports TLS which returns the correct certificate chain with the SSL version and ciphers listed below.

`openssl s_client -starttls smtp  -connect <server_ip>:465`

and the output is - 

```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384

```

and I am trying the same configuration with nodemailer - 

```javascript
const transport: nodemailer.Transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOSTNAME,
        port: 465,
        auth: {},
        requireTLS: true,
        secure: true,
        tls: {
            minDHSize: 512,
            minVersion: "TLSv1.2",
            maxVersion: "TLSv1.2",
            ciphers: "ECDHE-RSA-AES256-GCM-SHA384",
            rejectUnauthorized: false
        },
        debug: true,
        logger: true
    })
``` 
tried with ciphers as `ALL` also but all results in the same error.

**Comment by andris9** [comment]
Nodemailer uses the TLS stack from Node.js. It does not do anything custom with it. So, if the Node's TLS can not handle a connection, Nodemailer can't either.
