### ISSUE TITLE
Inheriting an Arbitrary Code Execution Vulnerability from underscore

### ISSUE THREAD

**Issue by Lonniebiz** [nodemailer/nodemailer#1589]
smtp-connection v2.4.2 transitively depends on a vulnerable version of underscore v1.3.2 via the httpntlm module.

Please consider updating the httpntlm dependency in smtp-connection to a version that does not depend on vulnerable underscore, or provide guidance to users on how to use smtp-connection securely.

    "nodemailer": "^6.9.7",
    "nodemailer-smtp-transport": "^2.4.2"

Both of the packages above have inherited a critical security bug (from their dependencies), and `npm audit fix` doesn't fix the [problem](https://github.com/advisories/GHSA-cf4h-3jhx-xvhq):

```
npm audit report

underscore  1.3.2 - 1.12.0
Severity: critical
Arbitrary Code Execution in underscore - https://github.com/advisories/GHSA-cf4h-3jhx-xvhq
fix available via `npm audit fix`
node_modules/underscore
  httpntlm  1.5.0 - 1.7.6
  Depends on vulnerable versions of underscore
  node_modules/httpntlm
    smtp-connection  2.4.0-beta.0 - 3.2.0
    Depends on vulnerable versions of httpntlm
    node_modules/smtp-connection
      nodemailer-smtp-transport  2.0.0-beta.0 - 2.0.0-beta.1 || >=2.5.0
      Depends on vulnerable versions of smtp-connection
      node_modules/nodemailer-smtp-transport

4 critical severity vulnerabilities
```

**Comment by andris9** [comment]
`nodemailer-smtp-transport` has been deprecated for years. Do not use it. You don't even need it as this feature is already built into Nodemailer.

**Comment by Lonniebiz** [comment]
Thanks for the information!

I was using it like this:

```
import { default as nodemailer } from 'nodemailer';
import { default as smtpTransport } from 'nodemailer-smtp-transport';

//Set transporter object to use smtp server:
const transporter = nodemailer.createTransport(smtpTransport({
	host: '7.7.7.7',
	port: 77
}));
```
I changed that to this:

```
import { default as nodemailer } from 'nodemailer';

// Set transporter object to use smtp server:
const transporter = nodemailer.createTransport({
	host: '7.7.7.7',
	port: 77
});
```

Thanks again.
