### ISSUE TITLE
Envelope doesn't seem to work

### ISSUE THREAD

**Issue by remiconext** [nodemailer/nodemailer#1592]
Maybe the envelope work fine but it's my understanding of the envelope that is wrong. 

const email = await transporter.sendMail({
    envelope:{
        from:`<bounceid=1234-1234-1234-1234@bounce.mydomain.com>`,
        to: "mark@gmail.com"
    },
    from: `bob@outlook.fr`,
    to: "mark@gmail.com",
    subject,
    text,
    html:text,
    messageId:`1234-1234-1234-1234@mydomain.com`,
})

I am expected to receive the bounce message to bounceid=1234-1234-1234-1234@bounce.mydomain.com. However for some reasons it is received on bob@outlook.fr. 

When I read the raw message sent by the servor I can't see any mention about the field in the envelope. 

So, I don't know exactly what happened. What is wrong with the code and/or the underlying logic?

**Comment by andris9** [comment]
You can’t use any envelope from address when sending with public services like Outlook or any other, they will override these addresses.
