### ISSUE TITLE
Error: Greeting never received

### ISSUE THREAD

**Issue by rohitbaisane** [nodemailer/nodemailer#1595]
I am getting following error when using transporter.verify(),

**Error: Greeting never received
    at SMTPConnection._formatError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
    at SMTPConnection._onError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)
    at Timeout.<anonymous> (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:694:22)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}**

### my code:-
  const config = {
        host: smtpEmailSettings.host,
        port: smtpEmailSettings.port,
        auth: false,
      };
      const transporter = nodemailer.createTransport(config);
      await transporter.verify();
      
I am using following host and port:-
**host: smtp.office365.com
port: 587**

**Comment by Dhatchanamoorthi8** [comment]
> I am getting following error when using transporter.verify(),
> 
> **Error: Greeting never received
>     at SMTPConnection._formatError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
>     at SMTPConnection._onError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)
>     at Timeout.<anonymous> (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:694:22)
>     at listOnTimeout (node:internal/timers:559:17)
>     at processTimers (node:internal/timers:502:7) {
>   code: 'ETIMEDOUT',
>   command: 'CONN'
> }**
> 
> ### my code:-
>   const config = {
>         host: smtpEmailSettings.host,
>         port: smtpEmailSettings.port,
>         auth: false,
>       };
>       const transporter = nodemailer.createTransport(config);
>       await transporter.verify();
>       
> I am using following host and port:-
> **host: smtp.office365.com
> port: 587**
> 
> 
> 
Any solution for this error
