### ISSUE TITLE
Nodemailer Not Working on Google Cloud Run

### ISSUE THREAD

**Issue by doguabaris** [nodemailer/nodemailer#1596]
**Description:**
I am experiencing an issue with Nodemailer; the library is not functioning as expected on Google Cloud Run. Interestingly, the same code works flawlessly in my local development environment.

**Details:**

Code: I am using Nodemailer to send emails in my Node.js application deployed on Google Cloud Run.

Issue: The emails are not being sent, and I am receiving the error messages below in the cloud log.

```
{
  "textPayload": "    at SMTPConnection._formatError (/workspace/node_modules/smtp-connection/lib/smtp-connection.js:528:15)",
  "insertId": "656384c9000321e1346f8bcd",
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "configuration_name": "****-****-end-runner",
      "project_id": "evocative-****-*****",
      "location": "us-central1",
      "revision_name": "******-back-****-****-00072-rm8",
      "service_name": "*******-back-****-runner"
    }
  },
  "timestamp": "2023-11-26T17:47:53.205281Z",
  "labels": {
    "commit-sha": "26639f9bf4e276b6a696c1406418d246a3a3bb43",
    "gcb-build-id": "15592293-3e02-4b29-b939-f6c0e2525b3a",
    "gcb-trigger-region": "global",
    "gcb-trigger-id": "23adb7b0-7393-40d4-b754-aac0ce8b4ce3",
    "managed-by": "gcp-cloud-build-deploy-cloud-run",
    "instanceId": "0087599d42fec00dfb612bf9261299920cd70e8bd1de977e09418f3f990bc0e4cf1d960a5e3b4ceeebc5aa5bd441998192417a23d4a20b0690ba8eb9dc222e2e90"
  },
  "logName": "projects/evocative-******-*****/logs/run.googleapis.com%2Fstderr",
  "receiveTimestamp": "2023-11-26T17:47:53.208546907Z"
}
```

Localhost: To verify the issue, I tested the same code on my localhost, and it works correctly, successfully sending emails without any errors.

**Google Cloud Run Setup:**

Environment: I am using Google Cloud Run as my serverless container platform.
Environment Variables: I have configured all necessary environment variables for Nodemailer, including SMTP server settings and credentials.
Network and Firewall: I have reviewed the network and firewall settings to ensure there are no restrictions preventing outgoing email communication.

**Actions Taken:**

I have reviewed the logs and error messages in the Google Cloud Run environment, but I did not find any specific errors related to Nodemailer.
I double-checked the Nodemailer configuration to ensure it is correct and compatible with the Google Cloud Run environment.

**Testing:**

I have thoroughly tested Nodemailer with multiple email services, including Gmail SMTP, Yandex, and my own mail server, to determine if the issue is specific to the email service being used. However, the issue persists across all tested email services.

**Request for Assistance:**
I kindly request assistance in diagnosing and resolving this issue with Nodemailer on Google Cloud Run. As the code functions correctly on my localhost but not on the production environment, I suspect there may be specific considerations for using Nodemailer on Google Cloud Run.

**Comment by ozgurmuraterhan** [comment]
yes, node mailler not working google cloud :(

please help me, i have same problem

**Comment by doguabaris** [comment]
After struggling with this problem for two days, I finally found the solution:

To fix timeout errors caused by dropped packets in **Cloud NAT**, you should do two things:

- Increase the number of ports available for each virtual machine (VM).
- Turn off the "Endpoint Independent Mapping" feature.

If you don't have a Cloud NAT instance, create one. This will make your network connections work better and be more dependable for your apps.
