### ISSUE TITLE
TypeError: ses.sendRawEmail is not a function

### ISSUE THREAD

**Issue by antonioOrtiz** [nodemailer/nodemailer#1597]
Preamble:

Originally I tried `aws-sdk/client-ses`

But got this error:

> [AWS-sdk/client-ses InvalidParameterValue: Message length is more than 10485760 bytes long: '20286031']> (https://stackoverflow.com/questions/77581707/aws-sdk-client-ses-invalidparametervalue-message-length-is-more-than-10485760-b)

So that led me to the following:

Relevant dependencies:
```
"nodemailer": "^6.9.7",
"nodemailer-ses-transport": "^1.5.1",
"@aws-sdk/client-sesv2": "^3.462.0",
```
I checked out this [post](https://github.com/nodemailer/nodemailer/issues/1254), but not understanding why I am getting this error.

> TypeError: ses.sendRawEmail is not a function
>    at /mnt/d/Repos/document-engine/node_modules/nodemailer/lib/ses-transport/index.js:267:43
>    at /mnt/d/Repos/document-engine/node_modules/nodemailer/lib/ses-transport/index.js:251:43
>    at processTicksAndRejections (node:internal/process/task_queues:95:5)
> [ERROR] 17:54:43 TypeError: ses.sendRawEmail is not a function

```
import { Transporter, createTransport } from 'nodemailer';
import { Attachment } from 'nodemailer/lib/mailer';
import { MailOptions } from 'nodemailer/lib/sendmail-transport';

import { SESv2, SESv2ClientConfig, SendEmailCommand } from '@aws-sdk/client-sesv2';
// import { SES, SESClientConfig, SendRawEmailCommand } from '@aws-sdk/client-ses';

/**
 * Utility class to for configuring Node mailer.
 *
 * This class uses Amazon SES to send email.
 *
 * Note : Do not use this class directly instead use IQEmailService class.
 *
 * @export
 * @class DSMailer
 */
@Injectable()
export class DSMailer extends DSAWSConfig {
	private transporter: Transporter;

	/**
	 * Function to configure Node mailer.
	 *
	 * This function throws system error which should be handled by the caller.
	 *
	 * @memberof DSMailer
	 */
	configEmail(options: SESv2ClientConfig): void {
		const ses: any = new SESv2(options);
		this.transporter = createTransport({
			SES: { ses, aws: { SendEmailCommand } }
		});

		this.logService.info('Mailer configured successfully.');
	}
 /* other code */
}
```
I am not understanding why it's throwing that error when I am using `SendEmailCommand`, can anyone please help me?

**Comment by kumboleijo** [comment]
I also had some trouble getting it working - the documentation and examples on AWS were not helpful at all. 

Checkout this example: 
- https://nodemailer.com/transports/ses/#example-1

The following code is working for me:

```ts
import * as aws from '@aws-sdk/client-ses';
import { createTransport } from 'nodemailer';

const config: aws.SESClientConfig = {
      credentials: { accessKeyId: '<KEY>', secretAccessKey: '<SECRET>' },
      region: 'eu-central-1',
};
const ses = new aws.SES(config);
const transport = createTransport({ SES: { ses, aws } });

transport.sendMail({ from: '', to: '', subject: '', text: '' }, (err, info) => {
  console.error(err);
  console.log(info);
});
```

using:

```json
    "@aws-sdk/client-ses": "^3.470.0",
    "nodemailer": "^6.9.7",
```

**Comment by kumboleijo** [comment]
I just figured out that you don't necessarily have to put the credentials inside a `config` object. The AWS SDK is by default looking into certain `ENV` variables.

Simply provide:

```sh
AWS_ACCESS_KEY_ID=<SECRET>
AWS_SECRET_ACCESS_KEY=<SECRET>
AWS_REGION=<REGION>
```

And then call:

```ts
const ses = new aws.SES(); // no config needed
const transport = createTransport({ SES: { ses, aws } });
```

Ref:

- https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-environment.html
- https://docs.aws.amazon.com/sdkref/latest/guide/environment-variables.html

**Comment by hardikbotsplash** [comment]
Upgrading nodemailer package to latest (6.9.16) fixed my issue.
