### ISSUE TITLE
Blocking when trying to verify or sending email

### ISSUE THREAD

**Issue by francois-egner** [nodemailer/nodemailer#1600]
Hello community,
I just found nodemailer and tried to use it immediatly. Sadly I was stopped by some weird bug that I just cannot debug properly. I try running the following code:
```ts
const transporter = nodemailer.createTransport({
        host: 'smtp.ionos.de',
        port: 465,
        secure: true,
        auth: {
            user: 'myemailaddress',
            pass: 'mypassword',
        },
        tls:{
            servername: 'smtp.ionos.de'
        },
        debug: true,
        logger: true
    });
    await transporter.verify()
    console.log("Verified!")
```

I do expect to see "Verified!" in the console but instead the verify call blocks. Adding the debug and logger flag just got me to the point at which I only see the following output:
`[2023-12-10 15:04:21] DEBUG Creating transport: nodemailer (6.9.7; +https://nodemailer.com/; SMTP/6.9.7[client:6.9.7])
`
Nearly the same behavior when trying to send an email without prior verification:
```
[2023-12-10 15:11:29] DEBUG Creating transport: nodemailer (6.9.7; +https://nodemailer.com/; SMTP/6.9.7[client:6.9.7])
[2023-12-10 15:11:29] DEBUG Sending mail using SMTP/6.9.7[client:6.9.7]
```

Nothing more than this. Not even a single debug statement "talking" about a connection at all. I am kinda helpless here because it doesnt even output useful information that helps me to debug.

I checked all credentials and other information like the port and host. All fine. Other SMTP Clients aka. mailing programs can connect to my smtp server using these information flawlessly.

Am I missing something here?

**Comment by rhks** [comment]
Hey been experiencing similar situation while using nodemailer with proxy, my application closes unexpectedly even though I've tried wrapping in a try and catch block and explicitly set a timeout with throw to prevent the whole application from closing, yet nothing has been helpful so far and no transaction log displayed
But this...
[2023-12-10 15:11:29] DEBUG Creating transport: nodemailer (6.9.9; +https://nodemailer.com/; SMTP/6.9.7[client:6.9.9])
[2023-12-10 15:11:29] DEBUG Sending mail using SMTP/6.9.9[client:6.9.9].
Happens only with while sending from my corp proxy, Any help would be appreciated.
