### ISSUE TITLE
Certain hosts connections are ending early than expected

### ISSUE THREAD

**Issue by titanism** [nodemailer/nodemailer#1601]
It looks like this is a true edge case, but some hosts (e.g. `cuiqiu.net`) respond when ready for `DATA` with:

```sh
354 2.0.0 Go ahead. End your data with <CR><LF>.<CR><LF>
```

And Nodemailer interprets that as an error / ended response.

It looks like this affects domains using `cuiqiu.net` for email.

**Comment by andris9** [comment]
Can not verify. There doesn't seem to be anything that prevents processing such a string as a response. Could you provide a better SMTP transaction log that shows the exact failure? Maybe there are some specific bytes in the response that do not survive copy-and-paste? 

Closing for now, until further information as this specific response does not trigger any errors with Nodemailer.
