### ISSUE TITLE
Close previous connections

### ISSUE THREAD

**Issue by antoniomldev** [nodemailer/nodemailer#1613]
Hello everyone, this is not really an issue but I would like to ask here, I apologize to any administrator if this is not allowed here.

Well, due to my oversight, I ended up doing some tests on my machine using my Outlook credentials and instead of using the Pool as 'true', I ended up using it as 'false' and this returned the error:

Error: Message failed: 432 4.3.2 Concurrent connections limit exceeded.

From what I understand, I have exceeded the limit of simultaneous connections with Outlook.

Is there any approach I can take to close these previous connections or have they been lost in my code and unfortunately it will no longer be possible to close them? It's code for testing, I just wanted to be able to close these previous connections and recreate the code in a way that reuses an open connection so that I don't exceed the limit.

Thank you all!

**Comment by andris9** [comment]
Connections are released once your app stops working. You might need to wait a bit, though.
