### ISSUE TITLE
icalEvent option producing incorrect attachment headers

### ISSUE THREAD

**Issue by tazsingh** [nodemailer/nodemailer#1615]
When adding an `icalEvent` with a `method`, that `method` is not added to the `Content-Type` of the attachment.

For example, the following configuration:

```ts
icalEvent: {
  method: 'request',
  content: icsFileAsString,
  filename: 'invite.ics',
}
```

Correctly adds the `method=REQUEST` to the `Content-Type` of the stringified output (I believe):
```
Content-Type: text/calendar; charset=utf-8; method=REQUEST
Content-Transfer-Encoding: 7bit
```

However, I do not believe this to be the correct attachment headers:
```
Content-Type: application/ics; name=invite.ics
Content-Disposition: attachment; filename=invite.ics
Content-Transfer-Encoding: base64
```

Instead, looking at [this gist](https://gist.github.com/flandrade/394d9df95e1be2a584f267ae91505239) and what others are doing, I believe it should look like this (they don't do the stringified output, just the attachment):

```
Content-Type: text/calendar; charset=utf-8; method=REQUEST; name=invite.ics'
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=invite.ics
```

I'm happy to help contribute this, however I can't quite identify how to add that `method=REQUEST` without dropping down to `raw`. Kindly inform me if I can assist in some way here, or if it's just easier for you to add and I can observe the PR to learn 🙏 

Thanks for an awesome library!

**Comment by andris9** [comment]
Nodemailer uses exactly the same MIME structure for sending calendar invites as Google Calendar. There are many ways to structure it, and different email clients do it differently.

This is how both Google Calendar and Nodemailer structure the MIME tree for events

- multipart/mixed
  - multipart/alternative
    - text/plain
    - text/html
    - text/calendar (no content-disposition as this is an alternative, not an attachment
  - application/ics (content-disposition: attachment)

As long as Google does not start using a different MIME structure for their calendar invites, I do not see any reason to change it in Nodemailer either.
