### ISSUE TITLE
Empty email body in Apple/iOS Mail with ical and attachments

### ISSUE THREAD

**Issue by ChristianBoehlke** [nodemailer/nodemailer#1616]
We are sending out emails with attachments and an ical event. The email works well on all email clients except for Apple Mail on iOS (we only tested iPhones, not other Apple products).

Here is a minimal code example:

```typescript
import { SendRawEmailCommand, SES } from '@aws-sdk/client-ses';
import { createTransport } from 'nodemailer';
import type SESTransport from 'nodemailer/lib/ses-transport';

const ses = new SES({
  region: 'eu-central-1',
  credentials: {
    accessKeyId: 'xxx',
    secretAccessKey: 'xxx',
  },
});

const transport = createTransport({
  SES: { ses, aws: { SendRawEmailCommand } },
});

const icalEvent =
  'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//xx//xx//EN\r\nEND:VCALENDAR';

const mailOptions: SESTransport.MailOptions = {
  subject: 'test subject',
  to: 'xxx',
  from: 'xxx',
  html: 'html content',
  icalEvent,
  attachments: [
    {
      filename: 'some.png',
      cid: 'some-attachment',
      path: 'resources/emails/images/customer.png',
    },
  ],
};

transport.sendMail(mailOptions).then(console.log, console.error);
```

As you can see, the `html content` is not displayed.
<img src="https://github.com/nodemailer/nodemailer/assets/483421/ad21be80-29a6-4a6b-929f-b27d5436c723" width="250" />

It sounds like #1206 could have been about this problem as well but I am not sure how it can be solved (other than it's the responsibility of the sender: me).
I don't know if this is caused by #1615, so I decided to open another issue instead.

Please let me know if I'm sending this email incorrectly or if there is any other information you would like. Thank you!

**Comment by popod** [comment]
Not sure if this is a `nodemailer` error or a macOS one.. I've had this bug without using `nodemailer` with some emails sent from the Mail (from Apple) application with a Google mail address.

**Comment by andris9** [comment]
I'm pretty sure that SES mangles the MIME structure of the email. Have you tried the same with some other email sending service?

**Comment by andris9** [comment]
On the other hand, no, it is just Apple Mail. Do not add attachments to the email if you send it as a calendar invite using `icalEvent` as Nodemailer uses a different kind of MIME structure than with regular emails (Nodemailer uses the same MIME structure as Google Calendar). If you want to send both calendar invites and attachments, add the invite as a regular calendar/ics attachment to the message.
