### ISSUE TITLE
email added to my imap sent folder displays symbols instead of Arabic characters

### ISSUE THREAD

**Issue by PPHelios** [nodemailer/nodemailer#1618]
when sending email from node js every thing works fine but email added to my imap sent folder displays symbols instead of Arabic characters "Ø¥Ø´Ø¹Ø§Ø± ÙÙ Ø¨Ø¯ÙÙ ÙØ³ÙØ·".
I tried textEncoding option with "quoted-printable" but got same result.
Is there a solution for this?

The code I use to send the message is:

     const sendMail = async (
        creatorName,
        userEmail,
        lng,
        adName,
        toAdmins = true
      ) => {
        const nodemailer = require("nodemailer");
        const Imap = require("imap");
        // const { simpleParser } = require('mailparser');

        // Email configuration
        const senderEmail = "";
        const senderPassword = process.env.SUPPORT_EMAIL_PASS;
         const recipientEmail =  userEmail;
        const subject =
          lng === "ar" ? "إشعار" : "Notification";
        const body =
          lng === "ar"
            ? `تم تعديل الإعلان ${adName} بنجاح, سيتم نشره بعد المراجعه.`
            : `Your Ad. ${adName} has been successfully submitted. It will be published once it undergoes the review process.`;

        // SMTP (sending) server details
        const smtpServer = "smtp.titan.email";
        const smtpPort = 587;

        // IMAP (receiving) server details
        const imapServer = "imap.titan.email";
        const imapPort = 993;

        async function sendEmailAndAppend() {
          try {
            // Create a nodemailer transporter using SMTP
            const transporter = nodemailer.createTransport({
              host: smtpServer,
              port: smtpPort,
              auth: {
                user: senderEmail,
                pass: senderPassword,
              },
            });
            // Create the email options
            const mailOptions = {
              from: senderEmail,
              to: recipientEmail,
              subject: subject,
              // textEncoding: "base64",
              text: body,
              html:
                lng === "ar"
                  ? 
                <h4  dir="rtl">مرحباً بك ${creatorName},</h4>
                <p  dir="rtl">${body}</p>
                
                  : 
          <h4>Dear ${creatorName},</h4>
          <p>${body}</p>
          <pre>
Regards,
          </pre>
          
            };

            // Send the email
            const info = await transporter.sendMail(mailOptions);
            // console.log("Email sent successfully.");
            // console.log("Info object:", info);

            // Append the sent email to the "Sent" folder using IMAP
            const imap = new Imap({
              user: senderEmail,
              password: senderPassword,
              host: imapServer,
              port: imapPort,
              tls: true,
            });

            imap.once("ready", () => {
              imap.openBox("Sent", true, (err) => {
                if (err) {
                  console.error('Error opening "Sent" folder:', err);
                  imap.end();
                  return;
                }

                // Create the email message as MIMEText
                const emailMessage = `From: ${senderEmail}\r\nTo: ${recipientEmail}\r\nSubject: ${subject}\r\n\r\n${body}`;

                // Append the sent email to the "Sent" folder
                imap.append(emailMessage, { mailbox: "Sent" }, (appendErr) => {
                  if (appendErr) {
                    console.error(
                      'Error appending email to "Sent" folder:',
                      appendErr
                    );
                  } else {
                    // console.log('Email appended to "Sent" folder.');
                  }
                  imap.end();
                });
              });
            });

            imap.once("error", (imapErr) => {
              console.error("IMAP Error:", imapErr);
            });

            imap.connect();
          } catch (error) {
            console.error("Error sending email:", error);
          }
        }

        // Call the function to send the email and append it to the "Sent" folder
        sendEmailAndAppend();
      };

**Comment by andris9** [comment]
This is an issue for node-imap, which handles the mail upload. From your description, it seems that Nodemailer handles it correctly (the sent copy from Nodemailer displays correct symbols, but the uploaded copy from node-imap is invalid)
