### ISSUE TITLE
No Newline Processing with Raw Attachment

### ISSUE THREAD

**Issue by tazsingh** [nodemailer/nodemailer#1619]
Per the docs: https://nodemailer.com/message/custom-source/#3-set-string-as-attachment-body

I am setting a `raw` attachment as a Base 64 encoded string (related to #1615), and I'm noticing there is no newline processing in the source.

I am doing something like (with `stripIndent` from `common-tags`):

```ts
attachments: [
      {
        raw: stripIndent`
    Content-Type: text/calendar; charset=utf-8; method=REQUEST; name=invite.ics
    Content-Transfer-Encoding: base64
    Content-Disposition: attachment; filename=invite.ics

    ${Buffer.from(iCalGeneratorCalendar.toString()).toString('base64')}`,
      },
    ],
```

And I'm receiving the following in the source (note, it's all on 1 line without any newline processing):

```
Content-Type: text/calendar; charset=utf-8; method=REQUEST; name=invite.ics
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=invite.ics

QkVHSU46VkNBTEVOREFSDQpWRVJTSU9OOjIuMA0KUFJPRElEOi0vL0d1aWxkLy9FdmVudCBDYWxlbmRhci8vRU4NClVSTDpodHRwczovL2d1aWxkLmhvc3QNCk1FVEhPRDpSRVFVRVNUDQpOQU1FOkd1aWxkIEV2ZW50IENhbGVuZGFyDQpYLVdSLUNBTE5BTUU6R3VpbGQgRXZlbnQgQ2FsZW5kYXINClgtV1ItQ0FMREVTQzpHdWlsZCAtIEVsZXZhdGUgWW91ciBDb21tdW5pdHkNCkJFR0lOOlZFVkVOVA0KVUlEOjk0ZTNjN2Q1LTQ4NzgtNDJiYy04MjZmLWE3MzM4YTAwNWNjZUBndWlsZC5ob3N0DQpTRVFVRU5DRTowDQpEVFNUQU1QOjIwMjQwMTI4VDEwMzYzOVoNCkRUU1RBUlQ6MjAyMjEyMTZUMTgwMDAwWg0KRFRFTkQ6MjAyMjEyMTZUMjAzMDAwWg0KU1VNTUFSWTpSZWFjdCBCZXJsaW4gR29vZGJ5ZSAyMDIyDQpERVNDUklQVElPTjpSZWFjdCBCZXJsaW4gR29vZGJ5ZSAyMDIyXG5odHRwOi8vbG9jYWxob3N0OjkwMTAvZXZlbnRzL3JlYWN0LQ0KIGJlcmxpbi1nb29kYnllLVJCRURFQw0KT1JHQU5JWkVSO0NOPSJSZWFjdCBCZXJsaW4gTG9uZ2VyIE5hbWUgVGhhbiBVc3VhbCINCkFUVEVOREVFO1JPTEU9UkVRLVBBUlRJQ0lQQU5UO0NVVFlQRT1JTkRJVklEVUFMO1BBUlRTVEFUPU5FRURTLUFDVElPTjtSU1ZQDQogPVRSVUU7Q049IlJvYmVydCBIYXJpdG9ub3YiOk1BSUxUTzplbmdpbmVlcmluZytyb2JlcnRAZ3VpbGQuaG9zdA0KVVJMO1ZBTFVFPVVSSTpodHRwOi8vbG9jYWxob3N0OjkwMTAvZXZlbnRzL3JlYWN0LWJlcmxpbi1nb29kYnllLVJCRURFQw0KU1RBVFVTOkNPTkZJUk1FRA0KRU5EOlZFVkVOVA0KRU5EOlZDQUxFTkRBUg==
```

I would expect that Base 64 encoded string to be broken up into multiple lines

As always, let me know how I can help get this over the line. Many thanks for the awesome library! ❤️

**Comment by andris9** [comment]
This is intentional. You can use any data formatting you like with the raw option. Nodemailer does not change anything, except newline characters from \n to \r\n

**Comment by tazsingh** [comment]
Gotcha, that's a bit ambiguous in the docs as to what "newline processing" means. Would it help to more explicitly say that you're just changing from `\n` to `\r\n` there?

I can't find the docs repo to just send you a PR for this 🙏 Happy to do it if you can point me in that direction! Thanks again! 🙂
