### ISSUE TITLE
DKIM-signing emails in nodemailer can break dkim validation

### ISSUE THREAD

**Issue by binarykitchen** [nodemailer/nodemailer#162]
Hello there

I have an exotic situation which breaks DKIM-validation and flags emails sent out by nodemailer as spam. Let me explain:
1. In my web app www.videomail.io I send out emails via nodemailer. Works fine.
2. I use a DKIM key for the domainName `videomail.io` in `smtpTransport.useDKIM()`
3. When I enter i.E. `michael.heuberger@binarykitchen.com` as the FROM email address in the web app, let nodemailer sign with with the videomail.io DKIM key, then email validation fails when receiving with this explanation from amavis:

`X-Spam-Status: No, score=0.783 tagged_above=-999 required=3
tests=[ALL_TRUSTED=-1, AWL=-0.205, DKIM_SIGNED=0.1, DKIM_VALID=-0.1,
DKIM_VALID_AU=-0.1, HTML_IMAGE_ONLY_24=1.282,
HTML_IMAGE_RATIO_02=0.805, HTML_MESSAGE=0.001] autolearn=no
Authentication-Results: binarykitchen.com (amavisd-new);
dkim=pass (1024-bit key) header.d=binarykitchen.com header.b=YpKGqzV6;
dkim=fail (1024-bit key) reason="fail (body has been altered)"
header.d=videomail.io header.b=iUtcxsOf`

I am aware that anyone can enter any email address and signing that with the videomail.io key is not a 100% working solution. But how can I solve this? I want to sign all outgoing emails from that web app to make sure they appear valid and won't be flagged as spam anywhere else. Gmail is very sensitive here and marks most of all mails as spam.

Any ideas are welcome! Thanks!

Michael

**Comment by knoxcard** [comment]
I am having the exact same issue at the moment...I tried the solution that work for @binarykitchen, then restarted openDKIM and it did not work.

**Comment by knoxcard** [comment]
I got this to work by using sendmail instead of postfix.
```

  const client = require('nodemailer').createTransport({
                    host: 'indospace.io',
                    port: app.nconf.get('mail:port'),
                    secure: false,
                    auth: {
                        user: app.nconf.get('mail:user'),
                        pass: app.nconf.get('mail:pass')
                    },
                    requireTLS: true,
                    sendmail: app.nconf.get('ENV') == 'LIVE' ? true : false,
                    dkim: {
                        domainName: 'indospace.io',
                        keySelector: 'mail',
                        privateKey: privateKey
                    }
                })
```
