### ISSUE TITLE
Unhandled errors in attachements

### ISSUE THREAD

**Issue by kikajanovcik** [nodemailer/nodemailer#1620]
Similarly to https://github.com/nodemailer/nodemailer/issues/1459 I also found some uncaught exceptions for attachments.

In our case the problem is that attachment `path` is an AWS signed url that expires (returning 403) and for unrelated reasons, we were sending the mail much later. This caused an uncaught exception and servers to die. 

I could replicate it also with urls returning 404, example to add [here](https://github.com/nodemailer/nodemailer/blob/5a2e10f454e3a02e0ee48d6a7be04e21cafa76ca/examples/sendmail.js#L35):

```
      attachments: [
        {
          "filename": "Test.pdf",
          "path": `https://stackoverflow.com/x`,
          "contentType": "application/pdf",
          "size": 100
        }
      ]
```

Would it be possible to catch such exceptions?

Thank you!

**Comment by andris9** [comment]
Which Nodemailer version are you using? I seem to catch the error just fine?

**Comment by kikajanovcik** [comment]
Hi @andris9,

Thanks for a fast response! We are on version `6.9.7`, I will test with the latest too

**Comment by andris9** [comment]
6.9.7 should be fine. Could you create a standalone test-case / example that I could run and verify the behavior? If i try to use the attachment info you provided I end up with a caught error object which is expected behavior.

**Comment by kikajanovcik** [comment]
You were right, there was some customisation from 5 years ago that was preventing to catch this on our side, I will close this issue.

Thanks for the help!
