### ISSUE TITLE
Not working on serverless edge functions

### ISSUE THREAD

**Issue by MickL** [nodemailer/nodemailer#1623]
Seems like nodemailer is not working on edge functions like Cloudflare Workers, Vercel Edge Functions or Deno Deploy.

On Vercel I dont see a very detailed error:

```
TypeError: Class extends value #<Object> is not a constructor or null
    at (index.mjs:1:370367)
    at (__nitro:middleware.js:1:17)
```

Probably this is due to Node api being used like 'fs' that does not exist within edge worker functions.

As a workaround instead of nodemailer an external service like resend.com could be used: https://github.com/resend/resend-cloudflare-workers-example/blob/main/worker.js

Related: #1621 #1563

**Comment by MickL** [comment]
Sure you can use it as long as you dont deploy on Edge Workers

**Comment by andris9** [comment]
Nodemailer does not work in any kind of Workers, only in "real" node.js.

**Comment by MickL** [comment]
This is exactly the point of this issue

**Comment by andris9** [comment]
The runtime for workers is not Node.js, it is more similar to a front-end runtime. That runtime lacks support for raw TCP and TLS APIs required by Nodemailer and as such Nodemailer will never work on it.

**Comment by tcurdt** [comment]
For example [the Cloudflare runtime](https://developers.cloudflare.com/workers/runtime-apis/nodejs/) certainly has limitations.

What works is using the APIs (SES, SendGrid, Mailchannels) directly.
I also looked for some abstraction for these APIs. But nodemailer just ain't that.

**Comment by sheecegardezi** [comment]
> The runtime for workers is not Node.js, it is more similar to a front-end runtime. That runtime lacks support for raw TCP and TLS APIs required by Nodemailer and as such Nodemailer will never work on it.

@andris9 net is supported now using the flag:

node_compat = true

in wrangler.toml

**Comment by L422Y** [comment]
If anyone is struggling w/ nodemailer on CloudFlare workers/pages... https://github.com/zou-yu/worker-mailer
