### ISSUE TITLE
Sonatype reports 6.9.9 as vulnerable due to resolveContent() function of the lib/shared/index.js file

### ISSUE THREAD

**Issue by jimguistwite** [nodemailer/nodemailer#1625]
I cannot say for sure if this is a serious issue or not so posting it here for comment.  Close if not an issue.

The sonatype folks report the following in version 6.9.9.   They likely have some scanner running against the code base which spits out an issue from the same RexEx that was fixed in version 6.9.9.  That regex appears to remain but in a different file.  See note below.

From SonaType:
Note: Users of (fixed) versions 6.9.9 and higher are vulnerable if they are using the resolveContent() function of the lib/shared/index.js file, which continues to contain the vulnerable regex.

Note: Fixed version(s) 6.9.9 and higher of this package continue to contain the vulnerable regex in the resolveContent() function of the lib/shared/index.js file. As such, we are treating these versions as vulnerable until the regex pattern is revised in line with the fixes applied to mail-composer/index.js and mailer/index.js files for this vulnerability. Should you not be using lib/shared/index.js file in your environment, you may discretionarily waive this vulnerability.

**Comment by andris9** [comment]
It's a complete nonsense. Security people are pushing their imaginary vulnerabilities to justify their existence at the expense of overburdening maintainers. You can upgrade to v6.9.10 to get the fix that, in reality, fixes nothing but at least does not trigger vulnerability scanners.
