### ISSUE TITLE
Showing Error instead of Log -- >> [Nest] 11912  - 21/03/2024, 12:06:03 pm   ERROR [MailerService] Transporter is ready  

### ISSUE THREAD

**Issue by Mjeevanantham** [nodemailer/nodemailer#1636]
Path:   **lib/mailer.service.ts**  

private verifyTransporter(transporter: Transporter, name?: string): void {
    const transporterName = name ? ` '${name}'` : '';
    transporter.verify()
        .then(() => this.mailerLogger.error(`Transporter${transporterName} is ready`))

- [ ]      ❌ .then(() => this.mailerLogger.error(`Transporter${transporterName} is ready`))
change it to 
- [ ]       ✅.then(() => this.mailerLogger.log(`Transporter${transporterName} is ready`))

![image](https://github.com/nest-modules/mailer/assets/95701479/0612e2ec-094f-4b7f-b727-ab8cc3923c6e)

Output:
![image](https://github.com/nest-modules/mailer/assets/95701479/bf7ec4d5-16ab-48cf-ba3e-432cffbe7543)

**Comment by Mjeevanantham** [comment]
Also attached the solution..

**Comment by andris9** [comment]
This does not seem to be related to Nodemailer but something else.

**Comment by Mjeevanantham** [comment]
Hi there,

Thank you for the mail.

To fix the issue, we recommend making changes to the following file path:


the changes are in this path

***@***.***\mailer\dist\mailer.service.js

It is important to note that this issue seems to be related to the usage of
Nodemailer and might affect those utilizing it within their projects.

We genuinely appreciate your patience and understanding throughout this
process. If you require any further assistance or have any additional
questions, please don't hesitate to reach out to us. We are here to help!

Thank you for using our services.

Best regards, jeevanantham M
