### ISSUE TITLE
MIME: GeoJSON mapping

### ISSUE THREAD

**Issue by mryellow** [nodemailer/nodemailer#1637]
`*.geojson` => `application/geo+json`

**Comment by mryellow** [comment]
Stale? It's simply a reminder of a missing MIME type. 

Nothing ever goes stale. All information is current until dealt with.

**Comment by mryellow** [comment]
Can you please leave us alone. This is an issue and will remain an issue until someone implements it.

**Comment by mryellow** [comment]
Bump.

**Comment by mryellow** [comment]
Bump.

**Comment by andris9** [comment]
Please make a PR
