### ISSUE TITLE
Unhandled error crashes the process within transport.verify()

### ISSUE THREAD

**Issue by rhks** [nodemailer/nodemailer#1638]
I've been experiencing a situation while using nodemailer with corporate proxy, my application closes unexpectedly even though I've tried wrapping in a try and catch block and explicitly set a timeout with throw to prevent the whole application from closing, yet nothing has been helpful so far and no transaction log displayed
But this...
[2023-12-10 15:11:29] DEBUG Creating transport: nodemailer (6.9.9; +https://nodemailer.com/; SMTP/6.9.7[client:6.9.9])
[2024-03-24 15:11:29] DEBUG Sending mail using SMTP/6.9.9[client:6.9.9], then the whole process crashes.
Happens only with while sending from my corp proxy, Any help would be appreciated.

**Comment by rhks** [comment]
Was able to trace where the error originates from and fixed it. with your permission i @andris9 i can share the fix i implemented or more so create a pr for it.

**Comment by mryellow** [comment]
Bump.

**Comment by mryellow** [comment]
Bump.

**Comment by mryellow** [comment]
Bump.

**Comment by andris9** [comment]
PrR please
