### ISSUE TITLE
Missing credentials for "PLAIN"

### ISSUE THREAD

**Issue by zeshan-tech** [nodemailer/nodemailer#1641]
getting this error with gmail SMTP

`Missing credentials for "PLAIN"`

here is my sendMail function:

`import { createTransport } from 'nodemailer';

const transporter = createTransport({
  service: 'gmail',
  host: 'smtp.gmail.com',
  port: 587,
  secure: false,
  auth: {
    user: process.env.SMTP_EMAIL,
    accessToken: '',
    pass: process.env.SMTP_PASS,
  },
});

export const onSendOtpToMail = async (email: string, otp: string): Promise<void> => {
  try {
    const info = await transporter.sendMail({
      from: process.env.SMTP_EMAIL,
      to: email,
      subject: 'Your OTP',
      text: "Your email verification otp is:" + otp,
    });

    console.log('Message sent: %s', info.messageId);
  } catch (error) {
    throw new Error(error);
  }
};`

**Comment by zeshan-tech** [comment]
@krunkosaurus @okhiroyuki @markstos @motdotla

**Comment by markstos** [comment]
@zeshan-tech This is an issue tracker, not a support forum and "@" mentioning people who haven't subscribed to follow new issues is rude.

**Comment by krunkosaurus** [comment]
I agree tho I'm just confused how my name even came up? I have no association with this project except maybe using it once 10 years ago. 👀

**Comment by andris9** [comment]
The error message seems pretty clear, though. There are no credentials set.
