### ISSUE TITLE
I having trouble with import nodemailer from 'nodemailer'

### ISSUE THREAD

**Issue by haroldm2598** [nodemailer/nodemailer#1642]
> Nextjs typescript nodemailer.
> 
> When using `import nodemailer from 'nodemailer';` I get:
> 
> ```
> Could not find a declaration file for module 'nodemailer'. 'c:/*/*/*/*/*/node_modules/nodemailer/lib/nodemailer.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/nodemailer` if it exists or add a new declaration (.d.ts) file containing `declare module 'nodemailer';`ts(7016)
> ```

**Comment by haroldm2598** [comment]
SOLVE i replace 
`**import nodemailer from 'nodemailer'**  `
to 
`**const nodemailer = `require('nodemailer')**`

**Comment by YO-SC** [comment]
It would be cool to have ES6 module support :D

**Comment by mryellow** [comment]
Bump.

**Comment by mryellow** [comment]
Bump.

**Comment by mryellow** [comment]
Bump.

**Comment by andris9** [comment]
Not sure what is going on here but does not seem like an issue with Nodemailer but something else

**Comment by igor-gaiduk** [comment]
npm install --save @types/nodemailer

**Comment by igor-gaiduk** [comment]
npm install nodemailer
npm install --save @types/nodemailer

**Comment by Ankur59** [comment]
install types for nodemailer with this  npm install --save @types/nodemailer

after this if you get error with nodemailer.create transport then use use SMTPtransport like this 

import type SMTPTransport from "nodemailer/lib/smtp-transport";

 const smtpConfig: SMTPTransport.Options = {
    host: process.env.ZEPTO_MAIL_HOST,
    port: parseInt(process.env.ZEPTO_MAIL_PORT ?? "587", 10),
    auth: {
      user: process.env.ZEPTO_MAIL_USER,
      pass: process.env.ZEPTO_MAIL_PASSWORD,
    },
  };

  const transporter = nodemailer.createTransport(smtpConfig);
