### ISSUE TITLE
Nodemailer - Cannot send message - smtp connection socket is already destroyed.

### ISSUE THREAD

**Issue by wguerram** [nodemailer/nodemailer#1644]
Hi, could someone please look into this:

https://github.com/oven-sh/bun/issues/10329

I'll really appreciate it.

**Comment by mryellow** [comment]
Bump.

**Comment by mryellow** [comment]
Bump.

**Comment by mryellow** [comment]
Bump.

**Comment by andris9** [comment]
Nodemailer has guaranteed support only for Node.
