### ISSUE TITLE
SSL3 Errror with outlook.com

### ISSUE THREAD

**Issue by dcbartlett** [nodemailer/nodemailer#165]
Hi I was setting up nodemailer to work with outlook.com and got the following error.

```
Error : 3074565888:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:337: 
```

This is the config i was using.

```
var smtpTransport = nodemailer.createTransport('SMTP', {
    host: 'smtp.live.com', // hostname
    secureConnection: false, // use SSL
    port: 587, // port for secure SMTP
    auth: {
        user: '********@outlook.com',
        pass: '********'
    }
});
```

**Comment by sagar03d** [comment]
setting the port from 587 to 465 solved my problem.
Error while port was 587:
 ```
{ [Error: 140525118728000:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
] code: 'ECONNECTION', command: 'CONN' }
```
After changed the port to 465:
`Email sent: 250 Requested mail action okay, completed: id=0MC4m6-1gvUQI3jdI-008qAi
`

**Comment by AbhimanyuVashisht** [comment]
Please help me with this error 
{ Error: 140456745305920:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
 code: 'ECONNECTION', command: 'CONN' }
while trying to use outlook

**Comment by nimatullah** [comment]
Guys I have the same error 

2019-04-20 10:52 +04:30: { [Error: 140529796826944:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
019-04-20 10:52 +04:30: ] code: 'ECONNECTION', command: 'CONN' }

**Comment by charlottetan** [comment]
ran into this issue, discovered i was using an old version of nodemailer. updating to the latest version and removing a bunch of other outdated code fixed it for me

**Comment by mohaimin95** [comment]
add `secure: (String(config.port)==="465")` to he options.

**Comment by mscbpi** [comment]
live.com a bit different from office365 enterprise.

The smtp relay host with auth (user licence needed) would be smtp.office365.com. We don't use this option.

The other option is direct send to MX server (another DNS record) and a connector to allow relay based on IP of the sender. 

This is what we chose. It used to work with directus. It uses port 25 only.

![image](https://user-images.githubusercontent.com/28528210/105541692-6a4ce080-5cf8-11eb-99a6-ea70648c0ea0.jpeg)

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365
