### ISSUE TITLE
Too long URLs in the List-Unsubscribe header causes the DKIM signature verification to fail

### ISSUE THREAD

**Issue by PlanetIrata** [nodemailer/nodemailer#1654]
When Nodemailer format the `List-Unsubscribe` header on more than one line, it may cause a DKIM signature verification failure. This is the case with my SMTP server. Note that I do NOT use the `dkim` parameters of Nodemailer, the DKIM signature is generated by my own SMTP server, and as soon as the `List-Unsubscribe` header is generated on two lines, the DKIM signature verification is reported as `fail`, but `pass` until the `List-Unsubscribe` is kept on one line. Tested on a Gmail recipient.

This works (one line `List-Unsubscribe` because the url is short):

```
Authentication-Results: mx.google.com;
       dkim=pass (...)
List-Unsubscribe: <http://example.com/campaign/unsubscribe?dummy=short>
```

This fails (two or more lines for the `List-Unsubscribe` because the url is longer):

```
Authentication-Results: mx.google.com;
       dkim=fail (...)
List-Unsubscribe:
 <http://example.com/campaign/unsubscribe?dummy=longer_url_with_several_params>
```

**Workaround**: I generate the `List-Unsubscribe` header myself with the `headers`props of Nodemailer, it is generated on one line and the DKIM verification works again for any URL:

```
  headers: {
      "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
      "List-Unsubscribe": {
        prepared: true,
        value: '<http://example.com/campaign/unsubscribe?dummy=longer_url_with_several_params>',
      },
  },
```

Maybe that this header specific parameter `List-Unsubscribe` should not be [prepared by Nodemailer](https://nodemailer.com/message/custom-headers/#3-prepared-headers)

**Comment by PlanetIrata** [comment]
Bump

**Comment by andris9** [comment]
This sounds more like an issue with your SMTP server doing the signing. This kind of line folding is allowed.

**Comment by PlanetIrata** [comment]
> This sounds more like an issue with your SMTP server doing the signing. This kind of line folding is allowed.

@andris9 My SMTP server is a standard Postfix server, but more importantly, I've checked tons of email sources from several newsletter senders and haven't been able to find one with a `List-Unsubscribe` header folded on several lines. Please check the source of some newsletters in your mailbox,  here's one received today from Apple:

![image](https://github.com/nodemailer/nodemailer/assets/1729529/dbe13e72-0540-42b2-94c7-1918cdff49be)

At least I think that this issue needs more investigations before being closed...

Regards
