### ISSUE TITLE
Invalid login: 535-5.7.8 Username and Password not accepted

### ISSUE THREAD

**Issue by hypo-thesis** [nodemailer/nodemailer#1656]
I am trying to send some email using Google app password that I generated from my google account and the following code :

```
const transporter = nodemailer.createTransport({
  pool: true,
  host: 'smtp.gmail.com',
  priority: 'high',
  from: {
    name: 'my name',
    address: 'info@mydomain.com'
  },
  port: 587,
  secure: false,
  auth: {
    user: "info@mydomain.com",
    pass: "kbpzbvrkrrqvjwfb", // also tried with spaces
  },
  tls: {
    rejectUnauthorized: false
  }
});
```

Which I run into :

```
Error: Invalid login: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 2adb3069b0e04-521f38d7f71sm2899713e87.194 - gsmtp
```

Everything had been working for the past 6 months but suddenly today I can not longer access it. I did generate a new key which didn't change anything.

**Comment by diegocamy** [comment]
having the same issue right now, it was working fine until it stopped

**Comment by shivam30072** [comment]
i am having the same issue, my code works perfectly in my local system but does not work on my server i have deployed it on aws ec2 below is my code

const nodemailer = require("nodemailer");
const fs = require("fs");
const path = require("path");
const handlebars = require("handlebars");

const transporter = nodemailer.createTransport({
  service: "gmail",
  // host: "smtp.gmail.com",
  // port: 587,
  // secure: false,
  // logger: true,
  debug: true,
  port: 465,
  secure: true, // Use `true` for port 465, `false` for all other ports
  secureConnection: false,
  auth: {
    user: process.env.USER || 
    pass: process.env.APP_PASSWORD || 
  },
  tls: {
    rejectUnauthorized: false, // This will ignore the self-signed certificate error
  },
});

**Comment by Recentlystarted** [comment]
I have the Same issue in Nodemailer.

**Comment by alvieridev** [comment]
> I am trying to send some email using Google app password that I generated from my google account and the following code :
> 
> ```
> const transporter = nodemailer.createTransport({
>   pool: true,
>   host: 'smtp.gmail.com',
>   priority: 'high',
>   from: {
>     name: 'my name',
>     address: 'info@mydomain.com'
>   },
>   port: 587,
>   secure: false,
>   auth: {
>     user: "info@mydomain.com",
>     pass: "kbpzbvrkrrqvjwfb", // also tried with spaces
>   },
>   tls: {
>     rejectUnauthorized: false
>   }
> });
> ```
> 
> Which I run into :
> 
> ```
> Error: Invalid login: 535-5.7.8 Username and Password not accepted. For more information, go to
> 535 5.7.8  https://support.google.com/mail/?p=BadCredentials 2adb3069b0e04-521f38d7f71sm2899713e87.194 - gsmtp
> ```
> 
> Everything had been working for the past 6 months but suddenly today I can not longer access it. I did generate a new key which didn't change anything.



> I have the Same issue in Nodemailer.

you found a solution?

**Comment by MaximVanchev** [comment]
> > I am trying to send some email using Google app password that I generated from my google account and the following code :
> > ```
> > const transporter = nodemailer.createTransport({
> >   pool: true,
> >   host: 'smtp.gmail.com',
> >   priority: 'high',
> >   from: {
> >     name: 'my name',
> >     address: 'info@mydomain.com'
> >   },
> >   port: 587,
> >   secure: false,
> >   auth: {
> >     user: "info@mydomain.com",
> >     pass: "kbpzbvrkrrqvjwfb", // also tried with spaces
> >   },
> >   tls: {
> >     rejectUnauthorized: false
> >   }
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Which I run into :
> > ```
> > Error: Invalid login: 535-5.7.8 Username and Password not accepted. For more information, go to
> > 535 5.7.8  https://support.google.com/mail/?p=BadCredentials 2adb3069b0e04-521f38d7f71sm2899713e87.194 - gsmtp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Everything had been working for the past 6 months but suddenly today I can not longer access it. I did generate a new key which didn't change anything.
> 
> > I have the Same issue in Nodemailer.
> 
> you found a solution?

I have the same issue now.

**Comment by andreyquerino** [comment]
You need to create an app password that helps you access your Google Account on older apps and services that don't support modern security standards.

Go to https://security.google.com/settings/security/apppasswords

1. Sign in using your Gmail email address.
2. Enter a name.

![Image](https://github.com/user-attachments/assets/9ab44a33-78f9-4f6d-9fd9-4be4428efeee)

3. Click Create. The Generated App Password window containing an app password is displayed. 

![Image](https://github.com/user-attachments/assets/12b45615-1aa1-4413-a131-1a14695a5109)

4. Copy the generated app password to the Clipboard. This is your STMP Password to use in the Mail tab.

**Comment by vivekjpatel** [comment]
Suddenly it stopped worked using App password,till now it was working fine.

Hi @andreyquerino , Even after using new APP password, it's not working. Any help ?

Thanks

**Comment by andreyquerino** [comment]
@vivekjpatel I've always done it this way using a new account with 2-factor authentication. It never stopped, I would try to authenticate, update the packages, and I always used `port: 465, secure: true`.

**Comment by MaximVanchev** [comment]
> App passwords are reset when the user changes their account password.

I did changed the acc password and its still not working.I am useing the latest version 10.9.0.

**Comment by andreyquerino** [comment]
Test without env!

```js
// my cofig

nodemailer: {
    from: '<mail@gmail.com>',
    host: 'smtp.gmail.com',
    port: 465,
    secure: true,
    auth: {
      user: 'mail@gmail.com',
      pass: 'ldbdevnpudsefjtg',
    }
  },
```

**Comment by MaximVanchev** [comment]
WTF it worked.Why its not working with the env file tf.

**Comment by hilmarch-dev** [comment]
> Test without env!
> 
> // my cofig
> 
> nodemailer: {
>     from: '<mail@gmail.com>',
>     host: 'smtp.gmail.com',
>     port: 465,
>     secure: true,
>     auth: {
>       user: 'mail@gmail.com',
>       pass: 'ldbdevnpudsefjtg',
>     }
>   },

WTF it worked for me wkwkwkwk
