### ISSUE TITLE
Allow usage of `https://www.googleapis.com/auth/gmail.modify` Gmail OAuth scope

### ISSUE THREAD

**Issue by antonioorct** [nodemailer/nodemailer#1666]
I've been banging my head for hours trying to figure out why I couldn't send out emails using the above scope.

The Nodemailer API suggests to use the `https://mail.google.com/` scope but the above scope offers the exact same functionality according to the [Gmail API scopes docs](https://developers.google.com/gmail/api/auth/scopes#:~:text=The%20Gmail%20API%20supports%20the%20following%20scopes%3A) - the difference being that the scope Nodemailer suggests to use also allows permanent deletion of emails.

The app I'm currently creating does not offer any email deletion thus I don't require the full scope. An issue could arise as my app is currently pending verification with the full scope and I'm afraid the app might not get approved due to that since Google would be stricter to offer me the scope and I'm not offering email deletion.

I've tested sending out emails using the Gmail API and it worked with both scopes.

**Comment by andris9** [comment]
Only `https://mail.google.com/` provides access to SMTP. See [this](https://developers.google.com/gmail/imap/xoauth2-protocol#:~:text=The%20scope%20for%20IMAP%2C%20POP%2C%20and%20SMTP%20access%20is%20https%3A//mail.google.com/)
