### ISSUE TITLE
Problem sending emails to gmail

### ISSUE THREAD

**Issue by GenLoya** [nodemailer/nodemailer#1671]
#Problem

I am a problem sending emails from my enterprise domain to gmail, when i use it the send is rejected and launch a email in the screenshot.
![image](https://github.com/user-attachments/assets/dcf3266b-bb5a-4732-9fd4-05e9f1666652)

# Code
```js
const transporter = createTransport({
	host: 'smtp.office365.com',
	service: 'Outlook365',
	port: 587,
	sender: false,
	auth: {
		user: process.env.EMAIL_USER,
		pass: process.env.EMAIL_PASSWORD,
	},
	tls: {ciphers: 'SSLv3'},
})

transporter.sendMail(
	{
		from: process.env.EMAIL_USER,
		to: ['genarodour2104@gmail.com', backupEmail],
		subject: `4T Ranch Register ${nowPdf}`,
		attachments: [
			{
				filename: `Hola.pdf`,
				content: pdfBuffer,
			},
		],
	},
	(error, info) => {
		console.log(error, info)
	},
)
```

**Comment by adarshmadrecha** [comment]
You have to enable `less secure apps` for this.
However, this option is also no longer supported.

> Starting in Fall of 2024, Google Workspace accounts will no longer support [less secure apps](https://support.google.com/accounts/answer/6010255), third-party apps or devices that ask you to sign in to your Google Account using only your username and password. For exact dates, visit [Google Workspace Updates](https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html). To access apps, you must use OAuth. To prepare for this change, review the details in [Transition from less secure apps to OAuth](https://support.google.com/a/answer/14114704).

Ref: https://support.google.com/a/answer/6260879?hl=en
