### ISSUE TITLE
Not able to receive .eml files from nodemailer in outlook. Working fine in gmail 

### ISSUE THREAD

**Issue by ShahswatJha** [nodemailer/nodemailer#1673]
Not able to receive .eml files from nodemailer in outlook. Working fine in gmail 

Below are the results that I got trying out multiple different scenarios (Also tried with Sg Mail and some scenarios seem to be working fine) :
 
1. Node Mailer
    subject : EML V-1 Node Mailer
    ext : eml , type : message/rfc822 , content : Non Base64 
    // Outlook : eml.eml getting added automatically when downloading the attachment from outlook; File 47 B only ; No subject body ;
    // Gmail : Working perfectly fine; 
2. Node Mailer
    subject : EML V-2 Node Mailer
    ext : eml , type : message/rfc822 , content : Base64 
    // Outlook : eml.eml getting added automatically when downloading the attachment from outlook; File 47 B only (empty file)
    // Gmail : Working perfectly fine;
3. Node Mailer
    subject : EML V-3 Node Mailer
    ext : eml , type : text/plain , content : Non Base64 
    // Outlook : eml.eml getting added automatically when downloading the attachment from outlook; File 47 B only ; No subject body ;
    // Gmail : Working perfectly fine; 
4. Node Mailer
    subject : EML V-4 Node Mailer
    ext : txt , type : text/plain , content : Non Base64 
    // Outlook : Working but needs to be downloaded and change the extension to eml 
    // Gmail : Working but needs to be downloaded and change the extension to eml 
5. Node Mailer
    subject : EML V-5 Node Mailer
    ext : empty , type : message/rfc822 , content : Non Base64 
    // Outlook : Content going and preview not available ; getting auto-downloaded ; Needs to be renamed with .eml extension
    // Gmail : Content going and preview not available ; getting auto-downloaded ; Needs to be renamed with .eml extension
6. Node Mailer
    subject : EML V-6 Node Mailer
    ext : eml , type : application/octet-stream , content : Non Base64 
    // Outlook : eml.eml getting added automatically when downloading the attachment from outlook; File 47 B only ; No subject body ;
    // Gmail : Working perfectly fine;
7. Node Mailer
    subject : EML V-7 Node Mailer
    ext : eml , type : application/octet-stream , content : Base64 
    // Outlook : eml.eml getting added automatically when downloading the attachment from outlook; File 47 B only ; No subject body ;
    // Gmail : Working perfectly fine;
8. Node Mailer
    subject : EML V-8 Node Mailer
    ext : eml , type : application/octet-stream , content : Base64 
    // Outlook : eml.eml getting added automatically when downloading the attachment from outlook; File 47 B only ; No subject body ;
    // Gmail : Working perfectly fine;

Not sure if this is a outlook issue but as some of them are working fine in another library raised it as an issue for nodemailer. Please look into this. Really need this for an implementation. 

Code that I have tried out : 

``
import  nodemailer  from "nodemailer";
import fs from 'fs/promises';

const apiKey = 'API_KEY'

async function readFileAndEncode(filePath) {
    try {

      let fileContent = await fs.readFile(filePath);
     // fileContent = fileContent.toString('base64');
     return fileContent;
    } catch (error) {
      console.error("Failed to read and encode file:", error);
      return null;
    }
}

const sendGridCallout = () =>{
    return new Promise(async(resolve,reject) =>{
        try{

            let email = {
                to: ['outlook-email','gmail-email'],
                from: 'outlook-email',
                subject: 'EML V-8 Node Mailer',
                text: 'Hello from SendGrid! Not B64 content , ext:eml , type: message/rfc822.',
                html: '<strong>Hello from SendGrid! Not B64 content , ext:eml , type: message/rfc822 </strong>',
            };
            let fileReadContent = await readFileAndEncode('testfile.eml')
            console.log("File encoded :", fileReadContent);
            let emailAttachment = [
                {
                    content: fileReadContent,
                    filename: 'testfile.eml',
                    type: 'message/rfc822',
                    disposition: 'attachment',
                    // encoding: 'base64',
                },
            ];   
            email['attachments'] = emailAttachment;

            console.log('Printing email body:', (email))
            let transporter = nodemailer.createTransport({
                host: "smtp.sendgrid.net",
                port: 587,
                secure: false,
                auth: {
                    user: "apikey",
                    pass: apiKey
                },
                tls: {
                    rejectUnauthorized: false
                },
                attachDataUrls: true
            });
            transporter.sendMail(email).then((res) => {
                resolve(res);
            }).catch((err) => {
                console.error('Error sending email:', err);
                console.error('Error response status:', err.code);
                let error = {
                    statusCode: 500,
                    messageList : ["Error while Sending Email.", err.message],
                }
                reject(error);
            });
        }catch(err){
            let error = {
                statusCode: 500,
                messageList : ["Error while Sending Email.", err],
            }
            reject(error)
        }
    })
}

sendGridCallout().then((res) => {
    console.log('Email sent successfully:', res);
}).catch((err) => {
    console.error('Error sending email:', err);
});
``

also attached image for readability... 

![carbon](https://github.com/user-attachments/assets/4ba80702-becb-4a0f-b572-f516db3a5163)

**Comment by NaumZakletskiy** [comment]
Have you resolved it? I have the same problem

**Comment by mercmobily** [comment]
I think I found a solution. For now, I have to change nodemailer's code to make it work. However, I am hoping to make it always work. Did you get anywhere with this @NaumZakletskiy?

**Comment by mercmobily** [comment]
Yep there is a solution.

     contentTransferEncoding: filename.endsWith('.eml') ? '7bit' : false

Voila' -- the file will be displayed properly in Outlook
