### ISSUE TITLE
DKIM signature failure

### ISSUE THREAD

**Issue by titanism** [nodemailer/nodemailer#1674]
Hi there @andris9 we are reporting an issue with `nodemailer/lib/dkim` exported `DKIM` classes' `sign` function.

Specifically you can see we had to swap for `mailauth` at <https://github.com/forwardemail/forwardemail.net/commit/90b5c922dc8c4b236700fa1454e00725a17764b8#diff-f62d991af164d67de8a1d609aa8f823796130f483f59036b87902165924a46a3> due to this issue as reported in recent comments of <https://github.com/postalsys/mailauth/issues/58>.

Perhaps `nodemailer` itself should switch to use `mailauth` for signing; that way we don't need to maintain two separate codebases.

The two sign methods are here:

nodemailer: <https://github.com/nodemailer/nodemailer/blob/master/lib/dkim/sign.js>

mailauth: <https://github.com/postalsys/mailauth/blob/master/lib/dkim/dkim-signer.js>

This is most likely due to `toASCII` conversions not being present in the `nodemailer` version, while the `mailauth` code has them <https://github.com/postalsys/mailauth/blob/4a88d8fcd1a65b8277ba307462bcd55c726723fe/lib/tools.js#L203-L218>.

It's way easier for us moving forward to simply use `mailauth` instead directly as a dependency of `nodemailer`, rather than try to maintain two separate codebases for signing.  Though that would be against <https://docs.emailengine.app/nodemailer-has-zero-dependencies/>.

Perhaps you can spot the issue @andris9?

**Comment by andris9** [comment]
Yes, Nodemailer can only sign messages reliably if you use the Nodemailer's API to compose messages. If you want to provide raw messages with unknown structures, use mailauth.
