### ISSUE TITLE
Whitespace on attachment's filename is being url encoded

### ISSUE THREAD

**Issue by gamier-lester** [nodemailer/nodemailer#1675]
Let's say that my attachment is structured as

`
attachments: [
    { filename: 'white spaces.pdf', content: content }
]
`

Upon receving the mail, the attachment will show as "white%20spaces.pdf"

Here's some content from the gmail:
Content-Type: application/pdf; name=white%20spaces.pdf
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=white%20spaces.pdf

Thank you

**Comment by andris9** [comment]
I’m pretty sure that the headers are modified by 3rd party, for example your SMTP server. Nodemailer generates and uses different headers than shown
