### ISSUE TITLE
`Mail.Options` missing `auth` field in TypeScript definition

### ISSUE THREAD

**Issue by weitude** [nodemailer/nodemailer#1676]
# Description

I'm encountering an issue where the `Mail.Options` interface doesn't include the `auth` field when using the TypeScript
definitions
from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5070fbeeeaf3a98fd4a1075b0821ca7fe0c7485f/types/nodemailer/lib/mailer/index.d.ts#L98).

# Steps to Reproduce

1. I followed the example on the [Nodemailer OAuth2 documentation](https://nodemailer.com/smtp/oauth2/#example-5), which
   shows using the `auth` field inside the `sendMail` method like this:

    ```javascript
    transporter.sendMail({
      from: "sender@example.com",
      to: "recipient@example.com",
      subject: "Message",
      text: "I hope this message gets through!",
      auth: {
        user: "user@example.com",
      },
    });
    ```

2. However, when using TypeScript, the `Mail.Options` interface does not include the `auth` field, causing a type error.

    https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5070fbeeeaf3a98fd4a1075b0821ca7fe0c7485f/types/nodemailer/lib/mailer/index.d.ts#L98

3. This causes a problem because it leads to an error at this line in the Nodemailer codebase:

    https://github.com/nodemailer/nodemailer/blob/79b8293ad557d36f066b4675e649dd80362fd45b/lib/smtp-transport/index.js#L269
    
    Since `mail.data` doesn’t have the `auth` field, it results in an unexpected behavior when trying to follow the official documentation examples.

**Comment by andris9** [comment]
Nodemailer does not have official typings. You need to contact the authors who provided the community typings.
