### ISSUE TITLE
Circular structure constructing the transporter via createTransporter [version: 6.9.15]

### ISSUE THREAD

**Issue by tim-reuten** [nodemailer/nodemailer#1678]
![image](https://github.com/user-attachments/assets/06d14ee9-72b6-4c1e-80a8-0455e9083047)

As you see the Mail class has a transporter property of type Transporter<T>

```typescript
import Mail = require("./lib/mailer");

export type Transporter<T = any> = Mail<T>;
```

But the Transporter type is the same as the Mail object.

My jest tests are failing, describing the exact problem: 
```console
Converting circular structure to JSON
        --> starting at object with constructor 'Mail'
        |     property 'transporter' -> object with constructor 'SMTPTransport'
        --- property 'mailer' closes the circle
        at stringify (<anonymous>)
```

From what i've understood is that the expect function of Jest doesn't really like complex object (Mail or SMTPTransport in this case) to be passed directly into methods (like expect() for instance) since this does not play well with its serialization process. Nonetheless, the implementation of the structure does not seem right to me.

**Comment by andris9** [comment]
Not sure how this is an issue of Nodemailer 🤔

**Comment by tim-reuten** [comment]
Oh god yeah, its for the lads who made a wrapper around this. Excuse me for the inconvenience :)
