### ISSUE TITLE
After encoding all `=` symbol replaced with `&#x3D;`

### ISSUE THREAD

**Issue by richardgloris** [nodemailer/nodemailer#1681]
Please file only reproducible bugs. Everything else will get ignored.

See the FAQ for existing known issues [here](https://github.com/nodemailer/nodemailer#having-an-issue) before you submit a new one.

Redirect link is showing like this after sending emails: `auth/activation?mail&#x3D;aaa@gmail.com`

Original link should be `auth/activation?mail&#x3D;aaa@gmail.com`

```
 [template.email.html, template.email.subject, template.email.text] = await Promise.all([
      await new EmailTemplate().render(path.join(__dirname, '../templates', templateName, '/html.hbs'), context),
      await new EmailTemplate().render(path.join(__dirname, '../templates', templateName, '/subject.hbs'), context),
      await new EmailTemplate().render(path.join(__dirname, '../templates', templateName, '/text.hbs'), context)
    ]);
    
  ```
  
  Here is the code, I confirmed conext.assetlink is correct by console.log but sent email template is not correct

**Comment by andris9** [comment]
This is not a Nodemailer issue.
