### ISSUE TITLE
giving Error: Invalid status code 500

### ISSUE THREAD

**Issue by praaly-dev** [nodemailer/nodemailer#1683]
Hello, we received the same error two years ago, 
https://github.com/nodemailer/nodemailer/issues/1140

0|server  | Error: Invalid status code 500
0|server  |     at ClientRequest.<anonymous> (************/node_modules/nodemailer/lib/fetch/index.js:218:23)
0|server  |     at ClientRequest.emit (node:events:513:28)
0|server  |     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
0|server  |     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
0|server  |     at TLSSocket.socketOnData (node:_http_client:534:22)
0|server  |     at TLSSocket.emit (node:events:513:28)
0|server  |     at addChunk (node:internal/streams/readable:315:12)
0|server  |     at readableAddChunk (node:internal/streams/readable:289:9)
0|server  |     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
0|server  |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
0|server  |   type: 'FETCH',
0|server  |   sourceUrl: 'https://api.nodemailer.com/user'
0|server  | }

**Comment by andris9** [comment]
Support for Ethereal.email is only available for paid Postal Systems subscribers. For free users, the service is provided "as is," meaning that it might work or might not work at any given time.

**Comment by praaly-dev** [comment]
If it's repaired in time, I don't see the problem !
Thanks for quick support.
