### ISSUE TITLE
Where can I find the definition of all error object nodemailer can return?

### ISSUE THREAD

**Issue by jeevankk** [nodemailer/nodemailer#169]
I need to take different actions based on the type of Error object. Like if there is an AUTHENTICATION failure perform some action or if there is a Network/ Connection error do something else.

We need to detect all kinds of error.

**Comment by EthanThatOneKid** [comment]
I was thrown this error: `{"err":{"code":"ESOCKET","command":"CONN"}}`
What does that mean?

**Comment by Giadissima** [comment]
This is the list given by chatGPT that could help solve many doubts:

EENVELOPE: Unable to determine the sender or recipient of the message.
EENVELOPEFORMAT: The format of the sender or recipient email address is invalid.
EENCODE: Unable to encode the message content correctly.
EMESSAGEID: Unable to generate a unique message ID.
ETXTBSY: The message file is locked by another process.
EFILE: Unable to access the message file.
ECONNECTION: Unable to establish a connection to the email server.
EAUTH: Authentication failed during the attempt to connect to the email server.
ENOAUTH: No authentication credentials were provided for the connection to the email server.
ETLS: Unable to start a TLS connection with the email server.
ESTARTTLS: Unable to start STARTTLS during the connection to the email server.
EUPGRADE: Unable to upgrade the TLS connection to a secure connection.
EENOTFOUND: Unable to find the specified email server.
EENOTEMPTY: Unable to send an empty message.
EMSGBIG: The message is too large to be sent.
EINVALIDDATE: The message date is not valid or not in the correct format.
ETOOMANYTOS: Too many recipients specified in the message.
ETOOMANYMSGS: Too many messages sent in a single call to Nodemailer.

**Comment by akhrarovsaid** [comment]
And here's chatGPT turning the above list into some quick ts:

```
type EmailError =
  | 'EENVELOPE'
  | 'EENVELOPEFORMAT'
  | 'EENCODE'
  | 'EMESSAGEID'
  | 'ETXTBSY'
  | 'EFILE'
  | 'ECONNECTION'
  | 'EAUTH'
  | 'ENOAUTH'
  | 'ETLS'
  | 'ESTARTTLS'
  | 'EUPGRADE'
  | 'EENOTFOUND'
  | 'EENOTEMPTY'
  | 'EMSGBIG'
  | 'EINVALIDDATE'
  | 'ETOOMANYTOS'
  | 'ETOOMANYMSGS';

type EmailErrorMessages = {
  [key in EmailError]: string;
};

const emailErrorMessages: EmailErrorMessages = {
  EENVELOPE: 'Unable to determine the sender or recipient of the message.',
  EENVELOPEFORMAT: 'The format of the sender or recipient email address is invalid.',
  EENCODE: 'Unable to encode the message content correctly.',
  EMESSAGEID: 'Unable to generate a unique message ID.',
  ETXTBSY: 'The message file is locked by another process.',
  EFILE: 'Unable to access the message file.',
  ECONNECTION: 'Unable to establish a connection to the email server.',
  EAUTH: 'Authentication failed during the attempt to connect to the email server.',
  ENOAUTH: 'No authentication credentials were provided for the connection to the email server.',
  ETLS: 'Unable to start a TLS connection with the email server.',
  ESTARTTLS: 'Unable to start STARTTLS during the connection to the email server.',
  EUPGRADE: 'Unable to upgrade the TLS connection to a secure connection.',
  EENOTFOUND: 'Unable to find the specified email server.',
  EENOTEMPTY: 'Unable to send an empty message.',
  EMSGBIG: 'The message is too large to be sent.',
  EINVALIDDATE: 'The message date is not valid or not in the correct format.',
  ETOOMANYTOS: 'Too many recipients specified in the message.',
  ETOOMANYMSGS: 'Too many messages sent in a single call to Nodemailer.',
};
```
