### ISSUE TITLE
Here is a working fix to use Proton Mail via the well-known services property

### ISSUE THREAD

**Issue by jeremykentbgross** [nodemailer/nodemailer#1691]
Hello,

Your nodemailer/lib/well-known/services.json list does not currently include Proton Mail.  I already have the solution for this locally, and have tested it.   It works great!

Since I currently do not have my GitHub keys setup for pushing changes, I will just inline my fix here:

Add to nodemailer/lib/well-known/services.json
```
	"Proton": {
		"aliases": ["ProtonMail", "Proton.me", "Protonmail.com", "Protonmail.ch"],
		"domains": ["proton.me", "protonmail.com", "pm.me", "protonmail.ch"],
		"host": "smtp.protonmail.ch",
		"port": 587,
		"requireTLS": true
	},
```

For reference, Proton requires a paid Business account as well as manual application and approval to use their SMTP interface.  If you do not feel like going through their requirements to test this change yourself and don't want to take my word for it, you can verify the configuration information that I used to create the patch above (in combination with your documentation and other working examples) here:

https://proton.me/support/smtp-submission

(Relevant information from the link):

SMTP host: smtp.protonmail.ch
Port: 587
Authentication method: PLAIN
Encryption: STARTTLS

https://proton.me/support/what-is-difference-between-proton-domains

(Relevant information from the link):

Proton has four different email domains that you can use to create email addresses:

* @proton.me is the default domain for Proton Mail.
* @protonmail.com is an alternative domain that you can choose when you sign up or use to create additional addresses.
* @pm.me is our short domain.
* @protonmail.ch is our original Proton Mail domain.

Please let me know if/when this change is live via `npm` so that I can sync the real version instead of either using a local hack in my node_modules folder, or breaking my nodemailer calling code with a temp hack that hard codes the values above instead of relying on proper environment configuration information to populate the values I pass to `createTransport()` via the `service`, `auth.user`, and `auth.pass` properties.

Thanks for your time, and I hope this change is as useful for others as it is for myself.

**Comment by andris9** [comment]
I wonder how you found out about the services.json? It hasn’t been included in the documention for at least five years. I wanted to remove it completely but too many old apps use this feature.

**Comment by jeremykentbgross** [comment]
@andris9 

> I wonder how you found out about the services.json? It hasn’t been included in the documention for at least five years. I wanted to remove it completely but too many old apps use this feature.

I started using nodemailer somewhere around a decade ago, maybe even longer.  I don't remember precisely.  Anyway, while the usage of it on my current project isn't nearly that old, I just knew it was there from the old days.  I thought it was odd that it was no longer documented, and thought about submitting another ticket reporting it's absence in the documentation, but for whatever reason I did not.

It seems like a pretty good/useful feature, except maybe for the fact that Microsoft recently got rid of their SMTP support on Outlook/Hotmail/Live, and I believe GMail already didn't support it anymore, if memory serves, which are a couple of pretty big providers.  But why would you want to get rid of the feature?  It seems pretty useful.

Should I take your reply to mean that I cannot expect my fix to go in?

If you do put it in, it occurred to me to mention that maybe I should have also included PM.me as an alias, which is missing above but easy enough to add in.

**Comment by andris9** [comment]
If you create a PR for this, I'll take it in.

In general, this feature became a source of constant user complaints since large providers like AWS SES, Godaddy, etc, started segregating users into different mail backends. So, suddenly, using "ses" as the provider did not work anymore. And the users had a hard time figuring out what the exact provider identifier would be for their account. Instead of dealing with these complaints, I hid the feature. If anyone uses it, it works, but there is no official documentation.

**Comment by jeremykentbgross** [comment]
@andris9 Hey, I had some time to focus on various outstanding cleanup tasks, and so I created a patch for this since you said you would take a PR if I made one.  However it seems that for some reason I am blocked from making any PRs to your project:

```
git clone git@github.com:nodemailer/nodemailer.git
...
(made fix on a new branch and committed it.)
...

~/Projects/nodemailer$ git push origin proton-mail-fix
ERROR: Permission to nodemailer/nodemailer.git denied to jeremykentbgross.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

(Note that proton-mail-fix is the name of the branch containing the change.)

I thought maybe my ssh key was setup wrong, as I just added it, however github shows the new key as: `Last used within the last week`, and since I literally just uploaded the key, cloned the project with it, and then tried to submit the PR, I assume that it's not the key that is at fault as it appears to have successfully been used by either the clone, or the subsequent denied push, or likely both since it added github to known hosts during the clone.

Is there something else that I need to do in order to make a PR with you?  Or am I mistaken and this is somehow an issue with my ssh key afterall?
=>
Note that if memory serves, without a registered ssh key, I have to clone projects via the https link instead of the git protocol, ie via: `git clone https://github.com/nodemailer/nodemailer.git`, which cannot then push obviously.  I don't think I would have even been able to clone via `git clone git@github.com:nodemailer/nodemailer.git` without the key working properly, if past experience/memory is correct, which makes me think maybe I somehow need permission with your project to push a branch for the pull request and my ssh key should be fine.

**Comment by andris9** [comment]
???

PRs in Github are never made by pushing to origin

**Comment by jeremykentbgross** [comment]
@andris9 Indeed.  Well it seems then that the tutorial I read was completely wrong then.  (I have only ever committed to my own code bases before--and not on github for many years, and to Jenkins for work.  Thus I had to look up how to do it.)

It also appears that the github documentation is wrong about it's own functionality, or at least is misleading.  Another tutorial indicates I need to fork the project and submit my branches to that, but when I go to do that, github appears to recommend creating branches of your project instead, but the link it gives to it's docs on how to do that shows interfaces I don't have for your project.  Probably I still have to fork it despite their misleading branching suggestion, THEN create the branches on my own fork, and then somehow request pulling my branch from my fork to your repo.  It's late night here though, and I was about to turn in, so I guess I will look into it tomorrow.  Sorry to trouble you with what is probably n00b questions for people use this site much more regularly than I.

**Comment by andris9** [comment]
Yeah, no problems. In short, click on the fork button. Then git clone your fork from Github, not the nodemailer/nodemailer repo. Then make changes locally, commit and push to your fork. Then click on the "make pull request" button.

**Comment by jeremykentbgross** [comment]
I don't know if I right boned this, or if it's OK.

I forked, cloned, branched, applied the change, committed the change, pushed back to github, and requested the PR (https://github.com/nodemailer/nodemailer/pull/1706)

However it looks like it might block it from going through for not being signed in addition to needing manual approval.  So I looked up docs on signing, added my existing ssh key to githubs for signing in addition to it already being there for authentication, and then also added it to my local global .gitconfig.  Then I amended the commit (since that fixed a lack of jenkins hooks if memory serves and I figured it would probably do the same here), but it won't let me push the amended commit.

```
git push origin proton-mail-fix
To github.com:jeremykentbgross/nodemailer.git
 ! [rejected]        proton-mail-fix -> proton-mail-fix (non-fast-forward)
error: failed to push some refs to 'github.com:jeremykentbgross/nodemailer.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

My local branch should NOT behind the target though, as on the same branch I did the following after setting up the signing:

```
git commit --amend
[proton-mail-fix 60d6818] Proton mail fix, issue: https://github.com/nodemailer/nodemailer/issues/1691#issuecomment-2452939892
 Date: Fri Jan 3 18:05:42 2025 -0800
 1 file changed, 8 insertions(+)
```

Do I need to do the whole thing over again from scratch to get a signed version through?  Or can it be accepted without it?  Or is there some shorter step.

**Comment by jeremykentbgross** [comment]
@andris9 I forget to explicitly tag you. Don't know if that is needed or not, but added it here as it's better safe than sorry.

**Comment by jeremykentbgross** [comment]
Awesome! Thanks @andris9
