### ISSUE TITLE
Getting error: read ECONNRESET when trying to use nodemailer with Hover.com email

### ISSUE THREAD

**Issue by gcatto** [nodemailer/nodemailer#170]
I'm relatively new to node.js for server development and definitely new to nodemailer, but it seems like a great option for my needs. I have it working with a gmail account as a test, but I've been trying to convert it to use an email address through Hover.com, but I'm getting an error: read ECONNRESET. I've triple-checked all of my parameters (host, port, user, pass, etc.) and everything looks okay and their help hasn't been able to help me yet either, so I thought I'd ask here.

My coffeescript for creating the transport is below:

transport = nodemailer.createTransport("SMTP", {
host: "mail.hover.com"
secureConnection: true
port: 465
auth: {
user:
pass:
}})

Thanks!

**Comment by EstherStarry** [comment]
I still get this error while running my code:

const Email = require('email-templates');
const nodemailer = require('nodemailer');
const transporter = nodemailer.createTransport({
    host: 'smtp.qq.com',
    port: 587,
    // secure: true,
    auth: {
        user: `${user}`,
        pass: `${password}`
    },
    // secureConnection: 'false',
    tls:{
        secureProtocol: "TLSv1_method"
    }
});

// mailOptions.to= destination
// mailOptions.from= user;

const email = new Email({
  message: {
    from: `${user}`
  },
  // uncomment below to send emails in development/test env:
  send: true,
  transport: transporter,
  views: {
            root: './emails'
        }
});
 
email
  .send({
    template: 'mars',
    message: {
      to: '1459714629@qq.com'
    },
    locals: {
      name: 'WHY'
    }
  })
  .then(res => {
    console.log('res.originalMessage', res.originalMessage
  )})
  .catch(console.error);


this is the error info:

{ Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
  code: 'ECONNECTION',
  errno: 'ECONNRESET',
  syscall: 'read',
  command: 'CONN' }

**Comment by liangwenzhong** [comment]
> I still get this error while running my code:
> 
> ```
> const Email = require('email-templates');
> const nodemailer = require('nodemailer');
> const transporter = nodemailer.createTransport({
>     host: 'smtp.qq.com',
>     port: 587,
>     // secure: true,
>     auth: {
>         user: `${user}`,
>         pass: `${password}`
>     },
>     // secureConnection: 'false',
>     tls:{
>         secureProtocol: "TLSv1_method"
>     }
> });
> 
> // mailOptions.to= destination
> // mailOptions.from= user;
> 
> const email = new Email({
>   message: {
>     from: `${user}`
>   },
>   // uncomment below to send emails in development/test env:
>   send: true,
>   transport: transporter,
>   views: {
>             root: './emails'
>         }
> });
>  
> email
>   .send({
>     template: 'mars',
>     message: {
>       to: '1459714629@qq.com'
>     },
>     locals: {
>       name: 'WHY'
>     }
>   })
>   .then(res => {
>     console.log('res.originalMessage', res.originalMessage
>   )})
>   .catch(console.error);
> ```
> 
> this is the error info:
> 
> ```
> { Error: read ECONNRESET
>     at _errnoException (util.js:992:11)
>     at TCP.onread (net.js:618:25)
>   code: 'ECONNECTION',
>   errno: 'ECONNRESET',
>   syscall: 'read',
>   command: 'CONN' }
> ```

have you resolve the problem ?

**Comment by nur1208** [comment]
i have the same problem, i'm using proxy, can please someone help me out?

my source code: 
const nodemailer = require("nodemailer");


let transporter = nodemailer.createTransport({
  service: "yahoo",
  secure: true,
  auth: {
    user: "medo1208@yahoo.com",
    pass: "wrvvkigxyittunfd",
  },
  tls: {
    secureProtocol: "TLSv1_method",
  },
});


let message = {
  from: "medo1208@yahoo.com",
  to: "medo0o6665@gmail.com",
  subject: "signup successful",
  text: "hello there",
};

transporter
  .sendMail(message)
  .then(() => {
    console.log("you should receive an email from us");
    // return res.status(200).json({ msg: "you should receive an email from us" });
  })
  .catch((error) => console.error(error));

error:
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ESOCKET',
  syscall: 'read',
  command: 'CONN'
}
