### ISSUE TITLE
sending a reply mail using nodemailer

### ISSUE THREAD

**Issue by chirag04** [nodemailer/nodemailer#172]
I need to send reply mails to each email i get. I am using gmail.

I am using node-imap to process mails.

I have set the inReplyTo header while sending auto response however the reply mail shows as a separate mail in the receivers mailbox.

**Comment by AndyBoat** [comment]
> The in-reply-to and references headers seem correct. But you are using different subjects and Gmail needs the subjects be the same or match partially (eg "final test" and "Re: final test"). If you change the subject, then a new thread will be created by Gmail.

I came across a similar problem  and spent quit a lot of time on testing and finding out the reason. Maybe better specify clearly on the advanced configuration part of the document?https://nodemailer.com/message/#more-advanced-fields

**Comment by logesh2496** [comment]
am facing the same issue: my _inReplyTo_ and _references_ has same message-id. and i have also added threadId in **send** api. still no use. Could you please help me out here? my query in detail below:
https://stackoverflow.com/questions/61105983/replying-in-a-thread-using-gmail-api-users-messages-send-is-not-working
