### ISSUE TITLE
Return-Path header dissapears

### ISSUE THREAD

**Issue by runk** [nodemailer/nodemailer#174]
First of all thanks for the great module! :+1: 

I'm trying to send a message with `Return-Path` header, but it literally disappears, I can't find it when I check raw email. After few hours of debugging of my smtp server I found out that the problem in client actually..

``` javascript
var nodemailer = require("nodemailer");

var smtpTransport = nodemailer.createTransport("SMTP", {
    host: 'example.com',
    secureConnection: true,
    port: 25,
    auth: {
        user: "mailer",
        pass: "*****"
    }
});

var mailOptions = {
    headers: {
      'Return-Path': 'bounce+b8184f.8697-deadrunk=gmail.com@example.com'
    },
    from: "Info <foo@example.com>",
    to: "deadrunk@gmail.com",
    subject: "testing nodemailer",
    text: "Hello world",
    html: "<b>Hello world ✔</b>",
}

smtpTransport.sendMail(mailOptions, function(error, response){
   console.log(error, response);
});
```

This code sends the message and everything is great except the `Return-Path` header.  Other headers pass in nicely.

This ruby script I used for testing, which is correctly sends my _header_.

``` ruby
require 'mail'

options = { :address              => "example.com",
            :port                 => 25,
            :user_name            => 'mailer',
            :password             => '****',
            :authentication       => 'plain',
            :enable_starttls_auto => true,
            :openssl_verify_mode  => 'none'
          }

Mail.defaults do
  delivery_method :smtp, options
end

h = Hash.new
h['Return-Path'] = 'bounce+b8184f.8697-deadrunk=gmail.com@example.com'

Mail.deliver do
       to 'deadrunk@gmail.com'
     from 'foo@example.com'
  subject 'testing sendmail'
     body 'testing sendmail'
  headers h
end
```

Any ideas? Or it's somewhere in my code?

**Comment by liesislukas** [comment]
fyi, this is old thread, and it didn't worked with sending email from gmail smtp to another gmail address.

**Comment by cod1ingcoding** [comment]
First, the Return-Path MIME header is added to the email by the destination MTA. 
Additionally, the value of Return-Path originates from the first SMTP request’s MAIL FROM command.
