### ISSUE TITLE
{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }

### ISSUE THREAD

**Issue by m4a1fox** [nodemailer/nodemailer#176]
Hello all. I want create a simple sending email. My code is:

var smtpTransposrt = nodemailer.createTransport('SMTP', {
    service: 'Gmail',
    auth: {
        user: 'mymail@gmail.com',
        pass: 'mypass'
    }
});

var text = '<strong>Hello</strong>';
text = text + 'some big text here';

var mailOptions = {
    from: 'max',
    to: 'm4a1fox@gmail.com',
    subject: 'Text',
    text: 'Text sdfgsfgsdf gsdf gsdfg s',
    html: text
}
app.get('/sendmail', function (req, res) {

```
smtpTransposrt.sendMail(mailOptions, function(error, request){
    if(error){
        console.log(error);
    }else{
        req.send('Good');
    }
})
```

});

When I go /sendmail in consol I have a error:
{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
{ [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }

What I do wrong?

**Comment by amirlarco** [comment]
var smtpConfig = nodemailer.createTransport("SMTP",{
    host: "smtp.gmail.com",
    secureConnection: false,
    port: 587,
    requiresAuth: true,
    domains: ["gmail.com", "googlemail.com"],
    auth: {
        user: "amir.fragrance@gmail.com",
        pass: "mypass"
    }
});

This worked for me. Its amazing

**Comment by gsmtamil** [comment]
Some times it may problem:
https://support.google.com/accounts/answer/6010255?hl=en
Use this link and try to turn off less security

**Comment by LaNa215** [comment]
{ [Error: connect ETIMEDOUT 216.58.197.37:587]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '216.58.197.37',
  port: 587,
  stage: 'init' }
hello i want to perform a simple sending emails,i m using a nodemailer ..above is the error which i m facing
and my  code is
			if(user.Role[0].AcessPermission == 3 || user.Role[0].AcessPermission == forgotpasswordRequest.body.sourceApp){
		var smtpTransport = nodemailer.createTransport("SMTP",{
   	 		host :'smtp.googlemail.com',
   	 		auth : true,
    		startTLS :true,
    		port : 587,
    		auth: {
        	       user: '*******@gmail.com',
       		       pass: '*********'
       	    }	
        });

**Comment by amitdubey8888** [comment]
I'm having the same issue, Someone can help

Here is my code

                     var transporter = nodemailer.createTransport({
			  service: "Gmail",
			  port: 587,
			  auth: {
			    user: 'myemail',
			    pass: 'mypassword'
			  }
			});
			
			var mailOptions = {
			  from: 'from@gmail.com',
			  to: 'to@gmail,
			  subject: 'Sending Email using Node.js',
			  text: 'That was easy!'
			};
			
			transporter.sendMail(mailOptions, function(error, info){
			  if(error){
			      res.status(400);
			      return res.json({
			  	success:false,
			  	message:'Unable to send email',
			  	error:error
			      });
			  } 
			 else 
			 {
		     	    res.status(200);
		  	    return res.json({
		  		success:true,
		  		message:'Email Sent',
		  		data: info.response
		            });
			 }
			});

And here is my error

{
      "code": "ECONNECTION",
      "errno": "ECONNREFUSED",
      "syscall": "connect",
      "address": "173.194.68.108",
      "port": 587,
       "command": "CONN"
}

**Comment by amirlarco** [comment]
in mailoption recipient address is wrong

**Comment by amitdubey8888** [comment]
Here is my working solution, You can try this
        
      const nodemailer = require('nodemailer');
      const smtpTransport = require('nodemailer-smtp-transport');

      function sendEmail(to, subject, html){
        nodemailer.createTestAccount((err, account) => {
            var transporter = nodemailer.createTransport(smtpTransport({
                host: 'smtp.mail.us-east-1.awsapps.com', 
                port:465,
                auth: {
                    user: 'example@email.com',
                    pass: 'password'
                }
                }));
            let mailOptions = {
                from: '"Admin" <admin@email.com>',
                to: to,
                subject: subject,
                html: html 
            };

            transporter.sendMail(mailOptions, (error, info) => {
                if (error) {
                    console.log('Error', error);
                }
                else{
                    console.log('Success', info);
                }
            });
        });
     }

**Comment by Ekutarn** [comment]
for host:'hostname', are you using smtp.gmail.com?
