### ISSUE TITLE
ECONNREFUSED - works locally but on prod server I get ECONNREFUSED

### ISSUE THREAD

**Issue by hughht5** [nodemailer/nodemailer#192]
Hi

I've used the following code to connect to my mandrill SMTP account. When I run the server code locally on my mac it works, but on my production box (ubuntu) it doesn't. I also tried on a debian Raspberri Pi with the same issue.

Code: 

//nodemailer
var smtpTransport = nodemailer.createTransport("SMTP",{
    service: "Mandrill",
    auth: {
        user: "xxx@gmail.com",
        pass: smtppassword
    }
});

var send = function(recipient, subject, text) {

```
smtpTransport.sendMail({
   from: "NAME <xxx@gmail.com>", // sender address
   to: recipient, //recipient
   subject: subject, // Subject line
   text: text // plaintext body
}, function(error, response){
   if(error){
       console.log(error);
   }else{
       console.log("Emailer.js - message sent: " + response.message);
   }
});
```

};

Running locally works fine. Running on ubuntu I get the following bug every time:
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

anyone know how to fix this? I've been googling all morning. I don't think it's a port issue. Is it postfix?

**Comment by SamGJohn** [comment]
this forum might have some insights into your [econnrefused](https://discuss.circleci.com/t/errno-econnrefused-connection-refused-connect-2-for-0-0-0-0-port-80/612) problem

**Comment by alpellario** [comment]
This worked for me.

```
const transporter = nodemailer.createTransport({
        host: "smtp.gmail.com",
        port: 587, 
        secure: false,  // true for 465, false for other ports
        auth: {
          //
        },
      });
```
