### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by hippich** [nodemailer/nodemailer#203]
Getting this from time to time in long running server. I am using gmail.com for sending emails and it works very well, except when this excption kills process.

I installed longjohn to get slightly better tracebacks:

```
/app/node_modules/longjohn/dist/longjohn.js:181
        throw e;
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at onread (net.js:556:19)
---------------------------------------------
    at Readable.on (_stream_readable.js:689:33)
    at SMTPClient.connect (/app/node_modules/nodemailer/node_modules/simplesmtp/lib/client.js:207:17)
    at process._tickCallback (node.js:415:13)
---------------------------------------------
    at module.exports (/app/node_modules/nodemailer/node_modules/simplesmtp/lib/client.js:15:13)
    at SMTPConnectionPool._createConnection (/app/node_modules/nodemailer/node_modules/simplesmtp/lib/pool.js:163:33)
    at SMTPConnectionPool.sendMail (/app/node_modules/nodemailer/node_modules/simplesmtp/lib/pool.js:116:18)
    at SMTPTransport.sendMail (/app/node_modules/nodemailer/lib/engines/smtp.js:121:15)
    at Transport.sendMailWithTransport (/app/node_modules/nodemailer/lib/transport.js:66:20)
    at Nodemailer.sendMail (/app/node_modules/nodemailer/lib/nodemailer.js:193:20)
    at /app/node_modules/nodemailer/lib/nodemailer.js:76:20
    at Nodemailer.validateSettings (/app/node_modules/nodemailer/lib/nodemailer.js:180:5)
---------------------------------------------
    at enqueue (/app/node_modules/bookshelf/node_modules/when/when.js:807:4)
    at scheduleConsumers (/app/node_modules/bookshelf/node_modules/when/when.js:493:3)
    at promiseResolve (/app/node_modules/bookshelf/node_modules/when/when.js:325:4)
    at deferred.resolve.deferred.resolver.resolve (/app/node_modules/bookshelf/node_modules/when/when.js:233:5)
    at [object Object].callback (/app/node_modules/bookshelf/node_modules/when/node/function.js:178:14)
    at Query.handleReadyForQuery (/app/node_modules/pg/lib/query.js:80:10)
    at [object Object].<anonymous> (/app/node_modules/pg/lib/client.js:151:26)
```

I am using nodemailer v0.5.3 and simplesmtp v0.3.10

Here is my mailing module I am using in my server:

```
var nodemailer = require("nodemailer");

// create reusable transport method (opens pool of SMTP connections)
var smtpTransport = nodemailer.createTransport("SMTP", {
    service: "Gmail",
    auth: {
        user: "email@gmail.com",
        pass: "password"
    }
});

module.exports = function(options) {
    // send mail with defined transport object
    smtpTransport.sendMail(options, function(error, response) {
        if (error) {
            console.log(error);
        }
        else {
            console.log("Message sent: " + response.message);
        }
    });
};
```

I am using it like this:

```
var mail = require("./mailer");
...
mail(options);
```

It looks like error happens somewhere inside in simplesmtp and not handled by nodemailer. But if it is something I could work around in my code - I am very interested to hear about possible solution.

**Comment by BenDavidJamin** [comment]
I know this is an old dead thread, but I'm having the same issue. 

Using nodemailer v1.4.0

can connect with command line openssl

      openssl s_client -starttls smtp -host 172.16.204.200 -port 25 -debug

However, when I attempt to connect with nodemailer given these credentials I get the error above. 

    {
      host: '172.16.204.200',
      port: 25,
      debug: true,
      tls: {
        rejectUnauthorized: false
      }
    }


Nodemailer connection. 

            transport = nodemailer.createTransport(config.mail);


Actual error message. 

     [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read'

**Comment by live-wire** [comment]
Even I'm getting this error:
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

I'm trying to use use service : 'gmail' in the transport object.
nodemailer version - 1.11.0

**Comment by SeunMatt** [comment]
I found this answer herer https://github.com/nodemailer/nodemailer/issues/170 and it worked. 

{
    host: "mail.hover.com",
    secureConnection: true,
    port: 465,
    auth:{
        user: "---",
        pass: "---"
    },
    tls:{
        secureProtocol: "TLSv1_method"
    }
}

**Comment by 12btcse1108** [comment]
{
  "name": "DayThirteenSignUpForm",
  "version": "1.0.0",
  "dependencies": {
    "accepts": {
      "version": "1.3.5",
      "from": "accepts@>=1.3.5 <1.4.0",
      "resolved": "https://registry.npmjs.org/accepts/-/accepts-1.3.5.tgz"
    },
    "array-flatten": {
      "version": "1.1.1",
      "from": "array-flatten@1.1.1",
      "resolved": "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz"
    },
    "body-parser": {
      "version": "1.18.3",
      "from": "body-parser@1.18.3",
      "resolved": "https://registry.npmjs.org/body-parser/-/body-parser-1.18.3.tgz"
    },
    "bson": {
      "version": "1.1.0",
      "from": "bson@>=1.1.0 <2.0.0",
      "resolved": "https://registry.npmjs.org/bson/-/bson-1.1.0.tgz"
    },
    "bytes": {
      "version": "3.0.0",
      "from": "bytes@3.0.0",
      "resolved": "https://registry.npmjs.org/bytes/-/bytes-3.0.0.tgz"
    },
    "content-disposition": {
      "version": "0.5.2",
      "from": "content-disposition@0.5.2",
      "resolved": "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.2.tgz"
    },
    "content-type": {
      "version": "1.0.4",
      "from": "content-type@>=1.0.4 <1.1.0",
      "resolved": "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz"
    },
    "cookie": {
      "version": "0.3.1",
      "from": "cookie@0.3.1",
      "resolved": "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz"
    },
    "cookie-signature": {
      "version": "1.0.6",
      "from": "cookie-signature@1.0.6",
      "resolved": "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz"
    },
    "debug": {
      "version": "2.6.9",
      "from": "debug@2.6.9",
      "resolved": "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz"
    },
    "depd": {
      "version": "1.1.2",
      "from": "depd@>=1.1.2 <1.2.0",
      "resolved": "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz"
    },
    "destroy": {
      "version": "1.0.4",
      "from": "destroy@>=1.0.4 <1.1.0",
      "resolved": "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz"
    },
    "ee-first": {
      "version": "1.1.1",
      "from": "ee-first@1.1.1",
      "resolved": "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz"
    },
    "encodeurl": {
      "version": "1.0.2",
      "from": "encodeurl@>=1.0.2 <1.1.0",
      "resolved": "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz"
    },
    "escape-html": {
      "version": "1.0.3",
      "from": "escape-html@>=1.0.3 <1.1.0",
      "resolved": "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz"
    },
    "etag": {
      "version": "1.8.1",
      "from": "etag@>=1.8.1 <1.9.0",
      "resolved": "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz"
    },
    "express": {
      "version": "4.16.4",
      "from": "express@latest",
      "resolved": "https://registry.npmjs.org/express/-/express-4.16.4.tgz"
    },
    "finalhandler": {
      "version": "1.1.1",
      "from": "finalhandler@1.1.1",
      "resolved": "https://registry.npmjs.org/finalhandler/-/finalhandler-1.1.1.tgz"
    },
    "forwarded": {
      "version": "0.1.2",
      "from": "forwarded@>=0.1.2 <0.2.0",
      "resolved": "https://registry.npmjs.org/forwarded/-/forwarded-0.1.2.tgz"
    },
    "fresh": {
      "version": "0.5.2",
      "from": "fresh@0.5.2",
      "resolved": "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz"
    },
    "http-errors": {
      "version": "1.6.3",
      "from": "http-errors@>=1.6.3 <1.7.0",
      "resolved": "https://registry.npmjs.org/http-errors/-/http-errors-1.6.3.tgz"
    },
    "iconv-lite": {
      "version": "0.4.23",
      "from": "iconv-lite@0.4.23",
      "resolved": "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.23.tgz"
    },
    "inherits": {
      "version": "2.0.3",
      "from": "inherits@2.0.3",
      "resolved": "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz"
    },
    "ipaddr.js": {
      "version": "1.8.0",
      "from": "ipaddr.js@1.8.0",
      "resolved": "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.8.0.tgz"
    },
    "media-typer": {
      "version": "0.3.0",
      "from": "media-typer@0.3.0",
      "resolved": "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz"
    },
    "memory-pager": {
      "version": "1.1.0",
      "from": "memory-pager@>=1.0.2 <2.0.0",
      "resolved": "https://registry.npmjs.org/memory-pager/-/memory-pager-1.1.0.tgz",
      "optional": true
    },
    "merge-descriptors": {
      "version": "1.0.1",
      "from": "merge-descriptors@1.0.1",
      "resolved": "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz"
    },
    "methods": {
      "version": "1.1.2",
      "from": "methods@>=1.1.2 <1.2.0",
      "resolved": "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz"
    },
    "mime": {
      "version": "1.4.1",
      "from": "mime@1.4.1",
      "resolved": "https://registry.npmjs.org/mime/-/mime-1.4.1.tgz"
    },
    "mime-db": {
      "version": "1.37.0",
      "from": "mime-db@>=1.37.0 <1.38.0",
      "resolved": "https://registry.npmjs.org/mime-db/-/mime-db-1.37.0.tgz"
    },
    "mime-types": {
      "version": "2.1.21",
      "from": "mime-types@>=2.1.18 <2.2.0",
      "resolved": "https://registry.npmjs.org/mime-types/-/mime-types-2.1.21.tgz"
    },
    "mongodb": {
      "version": "3.1.9",
      "from": "mongodb@latest",
      "resolved": "https://registry.npmjs.org/mongodb/-/mongodb-3.1.9.tgz"
    },
    "mongodb-core": {
      "version": "3.1.8",
      "from": "mongodb-core@3.1.8",
      "resolved": "https://registry.npmjs.org/mongodb-core/-/mongodb-core-3.1.8.tgz"
    },
    "ms": {
      "version": "2.0.0",
      "from": "ms@2.0.0",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz"
    },
    "negotiator": {
      "version": "0.6.1",
      "from": "negotiator@0.6.1",
      "resolved": "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz"
    },
    "nodemailer": {
      "version": "4.7.0",
      "from": "nodemailer@latest",
      "resolved": "https://registry.npmjs.org/nodemailer/-/nodemailer-4.7.0.tgz"
    },
    "on-finished": {
      "version": "2.3.0",
      "from": "on-finished@>=2.3.0 <2.4.0",
      "resolved": "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz"
    },
    "parseurl": {
      "version": "1.3.2",
      "from": "parseurl@>=1.3.2 <1.4.0",
      "resolved": "https://registry.npmjs.org/parseurl/-/parseurl-1.3.2.tgz"
    },
    "path-to-regexp": {
      "version": "0.1.7",
      "from": "path-to-regexp@0.1.7",
      "resolved": "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz"
    },
    "proxy-addr": {
      "version": "2.0.4",
      "from": "proxy-addr@>=2.0.4 <2.1.0",
      "resolved": "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.4.tgz"
    },
    "qs": {
      "version": "6.5.2",
      "from": "qs@6.5.2",
      "resolved": "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz"
    },
    "range-parser": {
      "version": "1.2.0",
      "from": "range-parser@>=1.2.0 <1.3.0",
      "resolved": "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz"
    },
    "raw-body": {
      "version": "2.3.3",
      "from": "raw-body@2.3.3",
      "resolved": "https://registry.npmjs.org/raw-body/-/raw-body-2.3.3.tgz"
    },
    "require_optional": {
      "version": "1.0.1",
      "from": "require_optional@>=1.0.1 <2.0.0",
      "resolved": "https://registry.npmjs.org/require_optional/-/require_optional-1.0.1.tgz"
    },
    "resolve-from": {
      "version": "2.0.0",
      "from": "resolve-from@>=2.0.0 <3.0.0",
      "resolved": "https://registry.npmjs.org/resolve-from/-/resolve-from-2.0.0.tgz"
    },
    "safe-buffer": {
      "version": "5.1.2",
      "from": "safe-buffer@5.1.2",
      "resolved": "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz"
    },
    "safer-buffer": {
      "version": "2.1.2",
      "from": "safer-buffer@>=2.1.2 <3.0.0",
      "resolved": "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz"
    },
    "saslprep": {
      "version": "1.0.2",
      "from": "saslprep@>=1.0.0 <2.0.0",
      "resolved": "https://registry.npmjs.org/saslprep/-/saslprep-1.0.2.tgz",
      "optional": true
    },
    "semver": {
      "version": "5.6.0",
      "from": "semver@>=5.1.0 <6.0.0",
      "resolved": "https://registry.npmjs.org/semver/-/semver-5.6.0.tgz"
    },
    "send": {
      "version": "0.16.2",
      "from": "send@0.16.2",
      "resolved": "https://registry.npmjs.org/send/-/send-0.16.2.tgz"
    },
    "serve-static": {
      "version": "1.13.2",
      "from": "serve-static@1.13.2",
      "resolved": "https://registry.npmjs.org/serve-static/-/serve-static-1.13.2.tgz"
    },
    "setprototypeof": {
      "version": "1.1.0",
      "from": "setprototypeof@1.1.0",
      "resolved": "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.0.tgz"
    },
    "sparse-bitfield": {
      "version": "3.0.3",
      "from": "sparse-bitfield@>=3.0.3 <4.0.0",
      "resolved": "https://registry.npmjs.org/sparse-bitfield/-/sparse-bitfield-3.0.3.tgz",
      "optional": true
    },
    "statuses": {
      "version": "1.4.0",
      "from": "statuses@>=1.4.0 <1.5.0",
      "resolved": "https://registry.npmjs.org/statuses/-/statuses-1.4.0.tgz"
    },
    "type-is": {
      "version": "1.6.16",
      "from": "type-is@>=1.6.16 <1.7.0",
      "resolved": "https://registry.npmjs.org/type-is/-/type-is-1.6.16.tgz"
    },
    "unpipe": {
      "version": "1.0.0",
      "from": "unpipe@1.0.0",
      "resolved": "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz"
    },
    "utils-merge": {
      "version": "1.0.1",
      "from": "utils-merge@1.0.1",
      "resolved": "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz"
    },
    "vary": {
      "version": "1.1.2",
      "from": "vary@>=1.1.2 <1.2.0",
      "resolved": "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz"
    }
  }
}

**Comment by 12btcse1108** [comment]
> Could you state the related version numbers for the used modules as well? The line numbers usually do not match with the latest in the repository, so the error messages aren't very useful. Run `npm shrinkwrap` and copy nodemailer block with dependencies from npm-shrinkwrap.json to here (remember to remove the shrinkwrap file afterwards if you do need it).



> The versions used are somewhat outdated. Could you reinstall nodemailer (remove it completely to get rid of the dependencies and then install again) and see if the error is still present.

facing the same issue, even having nodemailer@latest version
