### ISSUE TITLE
Error when connecting to Outlook.com SMTP

### ISSUE THREAD

**Issue by jeevankk** [nodemailer/nodemailer#204]
I am creating the transport object like this.

``` javascript
var transport = nodemailer.createTransport("SMTP", {
        host: "smtp-mail.outlook.com", // hostname
        secureConnection: false, // use SSL
        port: 587, // port for secure SMTP
        auth: {
            user: "user@outlook.com",
            pass: "password"
        }
    });
```

This is the error which I am getting.

```
[Error: 139668100495168:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:337:
]
```

When I tried setting ignoreTLS as true. This is what I am getting

```
{ [AuthError: Invalid login - 530 5.7.0 Must issue a STARTTLS command first]
  name: 'AuthError',
  data: '530 5.7.0 Must issue a STARTTLS command first' }

```

Am I doing something wrong? Please help.

**Comment by curlynux** [comment]
@andris9  hi, the link in your reply doesn't work got 404 github page

**Comment by ThorrStevens** [comment]
What is the recommended 'service' to use for an Exchange Outlook email address?

Anything I've tried (smtp-mail.outlook.com, outlook.office365.com, ...) always attempts to start the login process with AUTH START after EHLO and STARTTLS, but then fails with:

"Authentication unsuccessfull. User 'theuser@domain' failed to authenticate"

I've more than quadruple checked the user and password given in auth by using them to login to outlook and exchange. + setup an exchange connector for both incoming and outgoing mail.

Also, as @curlynux said, the link pointing towards the Hotmail predefined service returns a 404.

**Comment by shalltalk** [comment]
@curlynux  @ThorrStevens 
Not sure if you guys have figured it out, but I am guessing that the "Hotmail predefined service" looks like this:
`var transporter = nodemailer.createTransport({
    service: 'hotmail',
    auth: {
        user: config.alertEmail,
        pass: config.alertEmailPassword
    }
});`
I am able to send email from and to outlook email.

**Comment by Onyeriri** [comment]
before
```
const transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST,
    port: 587,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
    tls: {
      rejectUnauthorized: false,
    },
  });
```

after

```
const transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST,
    port: 587,
    service: "hotmail",
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
    tls: {
      rejectUnauthorized: false,
    },
  });
```
adding service: "hotmail" worked.
