### ISSUE TITLE
ETIMEDOUT read error occasionally

### ISSUE THREAD

**Issue by kiranbeing** [nodemailer/nodemailer#250]
I am using node mailer wrapped by express mailer with gmail smtp service (paid). 

Occasionally it fails with out getting control back to callback function which listens to the email send process. It waits for 20 minutes (which is equal to socket connect timeout period set by the http server) and then dies with the exception thrown ETIMEDOUT - read error. 

There is no pattern as when it works and when not. Only thing I could trace out is when the node server which creates the mailer object is restarted it starts working again. After the server being idle for 5 to 10 minutes, it might time out again.

I tried setting up connectionTimeout parameter, but the timeout error was not caught.

**Comment by VikramTiwari** [comment]
How to counter this problem? I tried opening all the possible ports [465, 587, 2525]. Does not work.

**Comment by DeepzSandra** [comment]
Please show your code!!!

**Comment by VikramTiwari** [comment]
@DeepzSandra Standard code as from the documentation.

```
var nodemailer = require('nodemailer');

// create reusable transporter object using SMTP transport
var transporter = nodemailer.createTransport({
    service: 'Mailgun',
    auth: {
        api_key: 'key-12311213121231212312',
        domain: 'sandbox1231212312312312312.mailgun.org',,
        user: 'postmaster@sandbox1231212312312312312.mailgun.org',
        pass: 'userpass'
    }
});

// NB! No need to recreate the transporter object. You can use
// the same transporter object for all e-mails

// setup e-mail data with unicode symbols
var mailOptions = {
    from: 'Fred Foo ✔ <foo@blurdybloop.com>', // sender address
    to: 'bar@blurdybloop.com, baz@blurdybloop.com', // list of receivers
    subject: 'Hello ✔', // Subject line
    text: 'Hello world ✔', // plaintext body
    html: '<b>Hello world ✔</b>' // html body
};

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    console.log('Message sent: ' + info.response);

});
```

**Comment by DeepzSandra** [comment]
var smtpTransport = nodemailer.createTransport("SMTP", {
 
    host: "mail.xxxxxx.com",
    secureConnection: false,
    port: 25,
    auth: {
            user: "user@gmail.com",
            pass: "user"
    },
    tls: {

            ciphers:'SSLv3'
    }
});
