### ISSUE TITLE
Cannot work on heroku

### ISSUE THREAD

**Issue by xueli-zhang** [nodemailer/nodemailer#251]
I have test it on the local host, it works, when I git my app to heroku, I waitted for long time, but didn't get the email

**Comment by NyanNaingTun** [comment]
I have same problems. Run in local but not in Heroku.  The error is 
" Error: Invalid login: 534-5.7.14.... 
responseCode: 534" Error
I configure the following that

> var smtpTransport = nodemailer.createTransport({
    service: "gmail",
    auth: {
        user: "xx@gmail.com",
        pass: "xxx"
    }
});
  var mailOptions={
        from:"xxx@gmail.com",
        to : req.query.to,
        subject : req.query.subject,
        text : req.query.text
    };

Pls instruction to me. :)

**Comment by Mr-emeka** [comment]
Login in into the gmail account then go to settings and allow other app access to the account.

Check your account alerts for unknown sign in.

This can be temporally resolved by: https://accounts.google.com/DisplayUnlockCaptcha

More permanent resolution would be to change your password to a stronger level:

upper case letter + lower case letter + special symbols + numbers
