### ISSUE TITLE
XOAuth2 returns "unauthorized_client"

### ISSUE THREAD

**Issue by maggialejandro** [nodemailer/nodemailer#266]
I want to send an email from the Google account currently logged,  so I'm trying to send mail through XOAuth2 option.

I'm setting these parameters:

```
XOAuth2: {
  user: <application's email account which I login using oauth> (not the account i'm trying to send the mail),
  clientId: <Client ID for web application>,
  clientSecret: <Client secret from web application>,
  refreshToken: <the one I get in OAuth 2.0 Playground>
}
```

Also I'm using [hello.js](https://github.com/MrSwitch/hello.js) for authenticating with OAuth2.

Is this configuration correct?
Thanks in advance!

**Comment by AnupKumarPanwar** [comment]
Check the following things :- 
1.  The Redirect URI is set to "https://developers.google.com/oauthplayground" in your Google Developer Console Project.
2. Enter the values of "pass" parameters too. Something like 
`XOAuth2: {
	      user: "username@gmail.com", // Your gmail address.
	       pass: "XXXXXXXXXXXXXXX",                                     // Not @developer.gserviceaccount.com
	      clientId: "XXXXXXXXXXXXX",
	      clientSecret: "XXXXXXXXXXXXX",
	      refreshToken: "XXXXXXXXXXXXX"
	    }`

**Comment by AdamCraven** [comment]
For anyone having "unauthorized_client" issues whilst the following apply:

* Using a service account 
* Have a google suite account attached
* Have followed all the 2 leg instructions at: https://nodemailer.com/smtp/oauth2/#oauth-2lo

I finally solved it following the documentation here: https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority

In essence going to
https://admin.google.com/**yourgsuitedomain.com**/ManageOauthClients
Adding a client id (from service account) and scope: https://mail.google.com/ (final slash important)

Everything finally started working 🎉
