### ISSUE TITLE
Gmail ECONNREFUSED

### ISSUE THREAD

**Issue by klimashkin** [nodemailer/nodemailer#292]
Hello, after update to 1.0.1, sendMail with gmail service always returns

```
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

tried with nodemailer-smtp-transport and nodemailer-smtp-pool

**Comment by bhaveshbhatkar** [comment]
Hi 
klimashkin, 
I am also getting the following error whiel sending /dispatching the emails from node usimng nodemailer 
****** ERROR  EMAIL  { Error: connect ECONNREFUSED 74.125.28.109:465
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ECONNECTION',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '74.125.28.109',
  port: 465,
  command: 'CONN'
Do I need to change any setting on Google Mail , or  is something wrong with Nodemailer ?
Any idea.
Thanks,
