### ISSUE TITLE
No transport method defined

### ISSUE THREAD

**Issue by zacharynevin** [nodemailer/nodemailer#295]
I am using nodemailer `0.7.1`. I have copied the Gmail transport code in the following way, but I get a `No transport method defined` error:

```
var transporter = nodemailer.createTransport("SMTP", {
    service: "Gmail",
    auth: {
        user: "***@gmail.com",
        pass: "***"
    }
});

transporter.sendMail(email, function(err, response) {
})
```

**Comment by anuvratashu** [comment]
Hi Andris,

I am also using your gmail code. However, there is no error message displayed. Moreover there is no message of success also.

 transporter.sendMail(mailOptions, function (error, info) {
            
            if (error) {
                return console.log(error);
            }
            console.log('Message sent: ' + info.response);

        });

it should have displayed Message sent: ' + info.response
but it didn't displayed any.

**Comment by pixelgrid** [comment]
Just for a reference, 
for anyone still having this problem, i found it was caused by a newer version of nodemailer.

Going back to ^1.10.0 for nodemailer and ^1.0.0 for nodemailer-smpt-transport solved the problem for me.

**Comment by faizmh** [comment]
New version of node mailer has the following transports (defined in transport.js)
`Transport.transports = {
    "SMTP": SMTPTransport,
    "SES": SESTransport,
    "SENDMAIL": SendmailTransport,
    "STUB": StubTransport,
    "DIRECT": DirectTransport,
    "PICKUP": PickupTransport
};`

`var transport = {
            service: 'SendGrid',
            auth: {
              user: 'X',
              pass: 'X'
            }
          }`

So change your code into below format (its not officially documented yet)
`var transporter = nodemailer.createTransport('SMTP', transport);`
where transport is your transport object

note - nodemailer could have built there package backwards compatible
