### ISSUE TITLE
gmail doesnt work 

### ISSUE THREAD

**Issue by pociej** [nodemailer/nodemailer#311]
when i try to use with gmail adress google blocks login..

**Comment by BirgitPohl** [comment]
Can you be more specific on that, @jualoppaz ? Thank you.

**Comment by morwalz** [comment]
we are having same issue.. It works from local but doesnt work from server.

**Comment by jualoppaz** [comment]
@BirgitPohl I remember that I received an email asking me if the login in my deployed app was made by me. I clicked in the url at the bottom of the email and I verified the remote server as a trusted device.

Other thing you can do is follow the steps of this article: https://support.google.com/accounts/answer/6010255?hl=en

Maybe enabling the insecure apps login in your account you can do the login successfully in your server.
