### ISSUE TITLE
Unable to send email from custom smtp server 

### ISSUE THREAD

**Issue by jesusrw** [nodemailer/nodemailer#314]
This is the conf that works for me in thunderbird client:
**Authentication method:NTLM**
**Connection Security: STARTTLS**
 so I've try to set this params in my configuration below but still no luck.

``` javascript
var transporter = nodemailer.createTransport(smtpTransport('SMTP',{
            host: 'mail.mysmtpserver.com',
            port: 587,
            auth: {
                user: 'username@mysmtpserver.com',
                pass: 'mypasswd'
            },            
            authMethod:'NTLM',
            secure:false,
            ignoreTLS:false,
            debug:true
        })
    );
```

I'm getting :**{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }**  

I'm able to get a response by doing this from a console(Im using linux)
    openssl s_client -starttls smtp -connect mail.mysmtpserver.com:587 -crlf  

Any ideas on how to fix this...

**Comment by m0nkey** [comment]
Last update on this was Oct 2014 and the issue is closed, and I am sure I know the answer, but is NTLM support in the future a realistic expectation?

**Comment by andris9** [comment]
I have nothing against NTLM *per se*. I just have no clue how to test it as It seems to be Microsoft specific and I know nothing about Windows based systems.

**Comment by tamilselvank** [comment]
Go This error
{ Error: connect ECONNREFUSED 127.0.0.1:25
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNECTION',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 25,
  command: 'CONN' }

**Comment by nguyenminhtuanfit** [comment]
@andris9 after creating transport, can we do verify transport transport.verify before sending email?

**Comment by bilal68** [comment]
I am trying creating the transport as
service: 'mail.hkd-consulting.com',
    auth: {
        user: 'no-reply@**********.com',
        pass: '*********'
    },
    tls: {rejectUnauthorized: false},
    logger: false, // log to console
    debug: true 

it gives me no error give me success message but i received no email.

**Comment by sathishchandran97** [comment]
unable to send email to user1:  testa@prodapt.com
{ RecipientError: Can't send mail - all recipients were rejected
    at SMTPClient._actionRCPT (/ATOM_PROD_PORTAL/New_Prod_Portal/node_modules/simplesmtp/lib/client.js:1054:27)
    at SMTPClient._onData (/ATOM_PROD_PORTAL/New_Prod_Portal/node_modules/simplesmtp/lib/client.js:354:29)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20)
  name: 'RecipientError',
  data: '550 relay not permitted',
  stage: 'rcpt' }
Executing (default): SELECT 1+1 AS result
GET 304 - 1.854 ms /@lgi-atom/atom-base/latest/assets/atom/css/lgi-atom-base.css
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: 140200002385792:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:365:

I'm getting this error while sending mail from node mailer on centos 7

**Comment by Friat-Gaim** [comment]
and please helpm with fix this
C:\Users\USER\Angineers\nilejobs-BE\node_modules\nodemailer\lib\mailer\index.js:45
        this.transporter.mailer = this;
                                ^

TypeError: Cannot set property 'mailer' of undefined
