### ISSUE TITLE
Error SELF_SIGNED_CERT_IN_CHAIN - Fixed.

### ISSUE THREAD

**Issue by aaronpcz** [nodemailer/nodemailer#330]
I'd like to say this node module looks great, and is ideal for my current project.

Firstly, I'm trying to use the Google SMTP server(this will ultimately be replaced with the companies SMTP server but for now it is sufficient)

How ever, following the most basic usage, I'm stuck with the famous "Error: SELF_SIGNED_CERT_IN_CHAIN".  Only when using nodemailer do I see this error.

I've also tried using the smtp transport same issue.

Any recommendations for fixes? I've done the standard cert fixes (updated node etc)

Thanks,
Aaron

FIXED - Avast was the issue.

**Comment by pswai** [comment]
@aaronpcz Thanks so much!

**Comment by EduardoRG** [comment]
You were right! If I disable Avast security, mail is correctly sent. 
Did you find any way to get it working with Avast enabled?

Thanks

**Comment by aaronpcz** [comment]
I unfortunately did not.

I moved away from Avast in general so never needed to work out a solution.
