### ISSUE TITLE
Cannot find module 'nodemailer-smtp-transport'

### ISSUE THREAD

**Issue by angel1st** [nodemailer/nodemailer#350]
Hi there,
I am migrating from 0.7.0 to current version.
I am using smtp trasport so far and I would like to switch to `nodemailer-smtp-transport`.
The issue I have got is following:

```
var mailer = require("nodemailer");
var smtpTransport = require('nodemailer-smtp-transport');
var options = {}; // some smtp options
mailer.mailer.createTransport(smtpTransport(options));
```

What I have got received is `Cannot find module 'nodemailer-smtp-transport'` error during the runtime execution. I clearly see that `nodemailer-smtp-transport` is installed in `node_modules` nodemailer folder. 
So my question is - how to change `smtpTransport = require('nodemailer-smtp-transport')` reference and allow the module to be found?

**Comment by enraiser** [comment]
If I follow above suggestion I get this error 

    Errors while sending mail.
    { state: 'rejected',
      reason: [Error: Unsupported configuration, downgrade Nodemailer to v0.7.1 to use it] }
    { from: 'Email.send',
      key: 'send error',
      message: 'Email transport encountered an error and did not send the emails.',
      info: [ undefined ] }
