### ISSUE TITLE
Intermittent crash "TypeError: Invalid non-string/buffer chunk"

### ISSUE THREAD

**Issue by bradvogel** [nodemailer/nodemailer#366]
I'm currently getting the following error around 1% of the time when sending emails:

```
TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:152:14)
    at PassThrough.Writable.write (_stream_writable.js:181:12)
    at PassThrough.Writable.end (_stream_writable.js:340:10)
    at MimeNode._getStream (/mnt/data/1/node_modules/buildmail/src/buildmail.js:702:23)
    at Object.sendContent [as _onImmediate] (/mnt/data/1/node_modules/buildmail/src/buildmail.js:556:37)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

The code to send is very straightforward:

```
  var nodemailer = Meteor.npmRequire('nodemailer');
  var smtpPool = Meteor.npmRequire('nodemailer-smtp-pool');
  var transport = nodemailer.createTransport(smtpPool({
    service: 'gmail',
    auth: {
      xoauth2: generator
    }
  }));

  var emailMessage = {
    from: from,
    to: to,
    cc: cc,
    bcc: bcc,
    subject: subject,
    html: wrappedBody,
    encoding: 'quoted-printable'
  };

  transport.sendMail(emailMessage, done);
```

Any quick guidance on where I can debug this or get the stream to handle the 'error' event? Thanks!

**Comment by niftylettuce** [comment]
Same issue here

**Comment by andris9** [comment]
Could you provide an example of a payload that triggers such issue?

**Comment by niftylettuce** [comment]
It was due to attachments, nvm

**Comment by niftylettuce** [comment]
Actually, this might be a bug in core nodemailer...

```
attachments:
   [ { filename: '1451589427-035187-qr.gif',
       cid: 'qr',
       content: <Buffer 47 49 46 38 37 61 f6 00 f6 00 80 00 00 00 00 00 ff ff ff 2c 00 00 00 00 f6 00 f6 00 00 02 ff 84 8f a9 cb 1a 0f e3 73 b2 35 19 ac 3e 98 e2 b8 6d 5f 95 ... > } ] }
```

That's my attachments array - it contains a buffered base64 encoded gif image.

**Comment by niftylettuce** [comment]
More of the source:

```js
          attachments: [
            {
              filename: order.reference + '-qr.gif',
              cid: 'qr',
              content: lib.dataUriToBuffer(qr(orderURL, { type: 6, size: 6, level: 'L' }))
            }
          ]
```

`lib.dataUriToBuffer` is a helper function that looks like this:

```js
module.exports = function(dataURI) {
  return new Buffer(dataURI.split('base64,')[1], 'base64');
}
```

And `qr` is `var qr = require('qr-encode');`

`orderURL` is simply a URL like http://github.com/123123123123

**Comment by niftylettuce** [comment]
Looks like we can pass data URI as an attachment... from the docs:

```md

        {   // data uri as an attachment
            path: 'data:text/plain;base64,aGVsbG8gd29ybGQ='
        }
```

**Comment by niftylettuce** [comment]
Okay so the reason it wasn't working is because I was stringifying it with `JSON.stringify` haha, ignore these comments

**Comment by mujawar** [comment]
POST /personnelwebsite 200 42.474 ms - 127
asasasasas { to: 'arifmr91@gmail.com',
  subject: 'Email from my personnel website',
  data: 
   { name: 'arif',
     email: 'arifmr1991@gmail.com',
     phone: '8147401060',
     message: 'aaaaaaaaaaaaaa' } }
mailOptions: {"from":"dev.medibox@gmail.com","to":"arifmr91@gmail.com","subject":"Email from my personnel website","text":{"name":"arif","email":"arifmr1991@gmail.com","phone":"8147401060","message":"aaaaaaaaaaaaaa"}}
............ { [TypeError: Invalid non-string/buffer chunk] code: 'ESTREAM', command: 'API' }

i am getting this error can someone help pls

**Comment by mgarciadash** [comment]
@mujawar 
Im stuck here too.
My attachment looks like:

[{
   "filename":"FT Soil Remediation.pdf",
   "contentType":"application/pdf",
   "href":"http://greenhousemexico.com/biologicsFiles2/Agricultura/Soil%20Remediation/FT%20Soil%20Remediation.pdf"
}]

And, Im getting {"code":"ESTREAM","command":"API"}    as Response

How did you solved this??

**Comment by andris9** [comment]
@mgarciadash what version of Nodemailer are you using? Could you try the latest version (v3.1.2) and see if your problem still exists?

**Comment by mgarciadash** [comment]
@andris9  im using 2.2.0  version, i realize ...  

I declare my attachment as:

`[{
"filename":"FT Soil Remediation.pdf",
"contentType":"application/pdf",
"**path**":"http://greenhousemexico.com/biologicsFiles2/Agricultura/Soil%20Remediation/FT%20Soil%20Remediation.pdf"
}]`

And after execute sendMail it looks like 

`[{
"filename":"FT Soil Remediation.pdf",
"contentType":"application/pdf",
"**href**":"http://greenhousemexico.com/biologicsFiles2/Agricultura/Soil%20Remediation/FT%20Soil%20Remediation.pdf"
}]`

I tried using path and filePath, without success.

Thanks in advance.

**Comment by andris9** [comment]
@mgarciadash I can't help with v2.2.0 as it's deprecated. It should work with the latest version though like this:

```javascript
var message = {
    ...,
    attachments: [{
        filename: 'FT Soil Remediation.pdf',
        contentType: 'application/pdf',
        href: 'http://greenhousemexico.com/biologicsFiles2/Agricultura/Soil%20Remediation/FT%20Soil%20Remediation.pdf'
    }]
};
```

**Comment by mgarciadash** [comment]
@andris9 So sorry !
I updated to last version, and problem fixed.
Thank you very much !!!!

**Comment by teddis** [comment]
I'm getting this too, but I'm only sending html without attachments. I'm sending html from https://mjml.io/try-it-live/templates/racoon (I'm trying to send html email to my server). And get the following after simply trying to send the html. The mailer as is works great for other html until now. 

Here's my code:
```
import {sendEmail} from "../util/email";
import * as fs from "fs";
import {mjml2html} from "mjml";
const mjml = fs.readFileSync(process.cwd() + '/data/mjml/racoon.mjml').toString('utf-8');
const html = mjml2html(mjml);
sendEmail({to: "ted@tedcohn.com", subject: "Racoon", html: html, text: ""});
```

It calls my function:

```
import * as Promise from "bluebird";
const nodemailer = require('nodemailer');

export function sendEmail({to, subject, html, text}: {to: string, subject: string, html?: string, text?: string}): Promise<any> {
    console.log(`user: ${process.env.SENDGRID_USER}, password: ${process.env.SENDGRID_PASSWORD}`);
    return new Promise((resolve, reject) => {
        const transporter = nodemailer.createTransport({
            service: 'SendGrid',
            auth: {
                user: process.env.SENDGRID_USER,
                pass: process.env.SENDGRID_PASSWORD
            }
        });
        const mailOptions = {
            to: to,
            from: process.env.FROM_EMAIL,
            subject: subject,
            html: html,
            text: text
        };
        transporter.sendMail(mailOptions, (err, info) => {
            if (err)
                return reject(err);
            resolve(info);
        });
    });
}
```

Here's the error/backtrace:

```
Unhandled rejection TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:215:10)
    at PassThrough.Writable.write (_stream_writable.js:244:12)
    at PassThrough.Writable.end (_stream_writable.js:479:10)
    at Immediate.setImmediate (/Users/ted/src/orderscape/foodiebot/node_modules/nodemailer/lib/mime-node/index.js:934:46)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

The html being sent is probably too big to post, but whomever checks can grab it from that url above. Thanks for any thoughts. Nodemailer bug or source error?

**Comment by isuvorov** [comment]
+1

**Comment by isuvorov** [comment]
@teddis 
```
const html = mjml2html(mjml).html;
```

**Comment by phpmydev** [comment]
Greetings!
I am now getting for only a few emails (without attachments??) the following backtrace:
ERROR IN SENDING MAIL :  { TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:254:10)
    at PassThrough.Writable.write (_stream_writable.js:288:21)
    at PassThrough.Writable.end (_stream_writable.js:562:10)
    at Immediate.setImmediate (/home/pi/Public/ktc_ems/node_modules/nodemailer/lib/mime-node/index.js:934:46)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5) code: 'ESTREAM', command: 'API' }

here is what is in the mailOptions:
  cc: '',
  bcc: '',
  subject: 'ENTITY RELIEF REQUEST - DOCUMENT HEADING 4',
  html: 
   { ENTITY: '                        DOCUMENT HEADING 4',
     ID: '                            8',
     NAME: '                          asd',
     addImgArea: '                    ADD IMAGE',
     ACTIVE: '                        on',
     HEADING_3ID: '                   ghj',
     ORDERBY: '                       0' },
  attachments: [] } // started with undefined, then '', maybe {} next?
Thanks if you can help?? :)

**Comment by andris9** [comment]
html property needs to be a string or a buffer
