### ISSUE TITLE
Why SMTP response is 250 even if recipient doesn't exist?

### ISSUE THREAD

**Issue by mehdi-loup** [nodemailer/nodemailer#373]
Hi,

When i  send a mail to a fake email address with a working transporter, the response returned by SMTP transports that keeps saying:

"250 Message received". 

This doesn't make sens to me, so i double check and i log into my sender mail account, and i have the mail delivery failure notice saying:

"Invalid Address, ERROR_CODE :550, ERROR_CODE :5.1.1 The email account that you tried to reach does not exist."

Can anybody give me an explanation on this?

**Comment by Milounas** [comment]
Thank you Andris, i didnt know that

**Comment by Shubham560098** [comment]
Hi @andris9 
What do you mean by "then drop the messages or deliver these to catch-all addresses."

does the sender id receive an email id list ?
