### ISSUE TITLE
Errors of streams are not being handled correctly.

### ISSUE THREAD

**Issue by satazor** [nodemailer/nodemailer#474]
Hi,

Streams are supported on attachments but they currently have a weird behaviour when a stream emits an `error` event. Before proceeding, note that we are using `quoted-printable`. Considering the following code:

```js
'use strict';

var nodemailer = require('nodemailer');
var ReadableStream = require('stream').Readable;
var stream = new ReadableStream();
var transporter;

transporter = nodemailer.createTransport({
    service: 'Gmail',
    auth: {
        user: 'your_email@gmail.com',
        pass: 'password'
    }
});

transporter.sendMail({
    from: 'your_email@gmail.com',
    to: 'your_email@gmail.com',
    subject: 'test',
    text: 'test',
    attachments: [
        {
            filename: 'test.txt',
            content: stream
        }
    ]
}, function (err) {
    console.log('finish', err);
});

setTimeout(function () {
    stream.emit('error', new Error('foo bar'));
}, 100);
```

I would expect the `sendMail` function to callback with an `error` because the stream of one of the attachments actually failed. Instead, the email is sent and the attachment itself is filled with the error message. This doesn't make much sense, specially for attachments that are not text based (images, etc). In other words, they will be corrupted.

Now, if you change the `setTimeout` from `100` to `3000` you got a different error that actually crashes the process with:

```
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at Encoder.Writable.write (_stream_writable.js:214:5)
    at Encoder.Writable.end (_stream_writable.js:449:10)
   ...
```

This happens because in [here](https://github.com/andris9/buildmail/blob/master/src/buildmail.js#L540) the `error` event of the stream is being again translated to a normal `write+end` and [later](https://github.com/andris9/buildmail/blob/master/src/buildmail.js#L562) the same `error` originates another `end` but the stream already ended..

After this explanation some questions arise:

- Why are errors on attachments not being exposed to the outside? Why are they being "swalled" and printed into the attachment themselves?
- Why are streams you do not own being manipulated [here](https://github.com/andris9/buildmail/blob/master/src/buildmail.js#L579)? The local stream there is the stream I've passed..

Lets discuss these issues and find a solution. I'm willing to do a PR with a solution we all agree.

Thanks!

**Comment by tnunes** [comment]
:+1:

**Comment by pmarques** [comment]
:+1:

**Comment by andris9** [comment]
The main reason for swallowing stream errors is the fact that the message is generated while it is already in transit. You have started a SMTP session and delivered some data and there is no easy way to back off if an error occurs at this point. This is similar to HTTP where you might have an error after you have sent the headers and some data, in which case you can either stop sending additional data or send an error message but you can't tell the client to ignore the data that was already delivered.

One option would be to kill the tcp connection and hope that the server ignores the message.

**Comment by satazor** [comment]
Thanks for the quick response. I'm unable to access my desktop at the moment but if I remember correctly there is a sequence of chars that signal the end of the mail, so clients should discard a mail if it ended prematurely without sendind that sequence. Poor implentations would indeed not discard the email but, with the current behaviour, we are penalizing good amd bad clients.

With the current implementation node mailer is sensing corrupt attachments + end of mail signal.
If we were not sending the end of mail in case of erros, good clients would ignore the mail and bad clients would receive a corrupt email which is what we already have.

**Comment by andris9** [comment]
If you do not send the stream terminator (a single dot in its own line) then the stream never ends. You can only cancel the stream by killing the tcp connection entirely.

**Comment by satazor** [comment]
Yes, so if we kill the connection without the dot in its own line good clients should ignore the email. In your experience the most important clients out there respect this?

Note: Ive updated my comment above

**Comment by pmarques** [comment]
I not 100% sure and my knowledge of smtp is already outdated, but if you kill the tcp connection it will cover the issue in almost all the servers, otherwise MTAs could also send duplicated emails in case of network issues that drop connections or in case of any timeout.

In my honest opinion sending a message with the error to the client is not also a good behaviour by default.

**Comment by spruce** [comment]
Also had this behavior. Maybe an option would be to send the email as it is send now. But also set the error of the callback to the same error. I've got some [ENOENT: ...] errors which I only found out through requesting the mail with attachement from the person who recieved it.

**Comment by satazor** [comment]
@andris9 I think we should address this somehow, this is causing a lot of "silent" failures. Can we converge into a solution? What you propose?

**Comment by pmarques** [comment]
Hi @andris9, any update on this?

**Comment by andris9** [comment]
I agree that the current behavior is not a good one. I've been working with an update for the underlying buildmail library to emit failures (see [the Error Handling section in updated docs](https://github.com/andris9/buildmail/tree/emit-failures#error-handling)) but I havent had time to actually finish it and include in nodemailer

**Comment by andrewtamura** [comment]
How do I prevent this exception from crashing my process? I've try to wrapping the the stream in a domain and also listening to the `error` event, but neither approach works and @satazor's sample code still results in an uncaught exception.

**Comment by bradvogel** [comment]
ping @satazor @andris9. Also blocked on this.

**Comment by pmarques** [comment]
@andrewtamura @bradvogel As far as I remember this is inside the module and hard to solve from outside, but I think that there were some developments in the module, have you tried the last version? 

The problem about sent the error to the client is even harder, that was discussed above and @andris9 was also pointed to a WIP branch. If you are trying to attach some resource from a network stream or other problematic stream I suggest to buffer it in memory before (it it fits in the memory, etc)

**Comment by andris9** [comment]
Should be fixed in the [beta channel](https://github.com/nodemailer/nodemailer/tree/v2). Install with `npm install nodemailer@beta` or wait until v2.0.0 gets released. Stream errors are now silently swallowed anymore, instead any arror interrupts the sending and the callback is invoked with the error argument.

**Comment by satazor** [comment]
Thanks for solving this @andris9 
Looking forward to 2.0.0.
