### ISSUE TITLE
how can I send a image as attachment

### ISSUE THREAD

**Issue by wahyd4** [nodemailer/nodemailer#49]
As the title said,I can't send a image as attachement. and my code is like this:
var attachment = [
   {
       'filename':'cat.jpg',
       'contents': new Buffer('img',encoding='ascii'),
     }
];

mail.send_mail(
  {
      sender:'wahyxxxx@qq.com',
      to:'wahydxxxx@gmail.com',
      subject:'none',
      attachments: attachment,
      body:'a attachment'
    },

I tried every kind of encoding,and all failed.
please help me to figure out this problem.

**Comment by SabriSnipy** [comment]
sddd
