### ISSUE TITLE
Error: Unsupported configuration....

### ISSUE THREAD

**Issue by ryanrolds** [nodemailer/nodemailer#503]
"Error: Unsupported configuration, downgrade Nodemailer to v0.7.1 or see the migration guide https://github.com/andris9/Nodemailer#migration-guide"

Helpful error, but that link isn't useful. Where is the migration guide?

**Comment by trainerbill** [comment]
Yeah what is going on here... I copied the example right off the README.  Even tried downgrading and nothing.  @ryanrolds Did you figure anything out?

**Comment by trainerbill** [comment]
Ok.  I got it working by following the directions here:

https://www.npmjs.com/package/nodemailer-smtp-transport

pretty bad documentation....  In case someone else needs it

```js
var options = {
    service: 'gmail',
    auth: {
        user: '',
        pass: ''
    }
  };
  var transporter = nodemailer.createTransport(smtpTransport(options))


  // setup e-mail data with unicode symbols
  var mailOptions = {
    from: '', // sender address
    to: '', // list of receivers
    subject: '', // Subject line
    text: '', // plaintext body
    html: '' // html body
  }

  // send mail with defined transport object
  transporter.sendMail(mailOptions, function(error, response){
      if(error){
          console.log(error);
      }else{
          console.log("Message sent: " + response.message);
      }

      // if you don't want to use this transport object anymore, uncomment following line
      //smtpTransport.close(); // shut down the connection pool, no more messages
  });

```

**Comment by andris9** [comment]
Migration guide is not available anymore as my blog exploded wtogether with the db. You can still access it from http://web.archive.org/web/20150317063407/http://www.andrisreinman.com/nodemailer-v1-0/#migrationguide

**Comment by ryanrolds** [comment]
@trainerbill Got if figured out a while ago.

@andris9 <something something backups>
