### ISSUE TITLE
Nodemailer not sending occasional email when using a pool-transport

### ISSUE THREAD

**Issue by animesh1987** [nodemailer/nodemailer#511]
Hi, 
We have been using nodemailer for handling emails in our application and had no issues, but since we have updated to node v 0.12, there have been issues where occasionally emails were lost when I used a "pooled connection". 

On further investigation we found that the "pooled connection" when establishing a connection works fine (We leave the SMTP connection open). The open connection worked fine if we keep using the connection and not let it sit idle for a long time. But if we have a break for few mins between 2 emails, then the second email is not delivered and neither there is an error callback. On digging further we found that the SMTP Connection in the pool receives the request and behaves as expected till we get to the "SMTPConnection.prototype._sendCommand " in "smtp-connection.js". The connection is destroyed (where the socket in connection has a write method) after line 540. 

We tried this with 0.7.1 branch of nodemailer. Also with v1.8.0 of nodemailer + v1.1.3 of nodemailer-smtp-pool. This issue could potentially relate to https://github.com/andris9/Nodemailer/issues/474 .

We have solved this issue for now by just using a SMTP Transport but will be good to get the SMTP-pool working.

Thanks for your great work!!

**Comment by andris9** [comment]
Thanks for the report. Does the write method on line 540 succeed or fail? Eg. is the connection already destroyed at this point or will be destroyed immediately after it?

**Comment by andris9** [comment]
One quick fix you could try is to lower connection timeout limit `socketTimeout` which is 10 minutes by default. If you say that you have problems after a connection has been idle for 2 minutes (maybe you have a load balancer somewhere that does not allow long idling connections?) then set `socketTimeout` to 60000 ms (eg. 1min). If you send several messages at once, then same connection is reused but once you stop sending, the connection times out after 1 min.

**Comment by andris9** [comment]
Should be fixed in the [beta channel](https://github.com/nodemailer/nodemailer/tree/v2). Install with `npm install nodemailer@beta` or wait until v2.0.0 gets released

**Comment by animesh1987** [comment]
Thanks for the updates :+1:
