### ISSUE TITLE
Attachment file path from function alongside of string, stream or buffer

### ISSUE THREAD

**Issue by Tzaphkiel** [nodemailer/nodemailer#521]
I am thinking of something similar to the below example:

```javascript
attachments:[{
  filename: 'MeaningfulName-20151018.zip',
  filePath : function() {
    var now = new Date();
    return "dist/MeaningfulName-" + now.getFullYear() + now.getMonth() + now.getDate() + ".tar.gz";
  }
}]
```

This would allow to send a file that is generated on the fly with a Grunt compress task for example.

**Comment by andris9** [comment]
I don't really get it. Does the file exist that is returned by the filePath function or what?

**Comment by Tzaphkiel** [comment]
Yes the file would exist, the name would be built for example in a previously running task (Grunt) and its name would be built in a similar fashion. Not knowing the name of the file when the task is executed on schedule, the filename would have to be re-constructed using the above method: using a function to concatenate the 'dynamic' parts of the filename. Here a Date is given as an example.

Another example could be a configuration variable set in a previous task depending on the passing or not of tests for example...

Hoping this helps clarify.

**Comment by andris9** [comment]
I'm still puzzling, I don't really see the advantage here. Is there a reason you can't achieve the same with already existing options? I mean that you can't send the mail before you have an attachment (even if the attachment is a stream object that hasn't started streaming yet). Maybe provide an actual example where this could be useful?

**Comment by Tzaphkiel** [comment]
You are right, you cannot send a mail without having first an attachment available.

The above I was describing was in the context of running Grunt tasks one after another.
  - The first one being a task of assemble, minifying, etc.
  - The second a compression task of the target folder (containing the assembled files).
  - The third being the nodemailer task mailing the created compressed file.

Since the compressed file was created in a previous task and with a built-up name (date, target environments, etc.), I wanted to re-build the name of the file using a function instead of a stream, or string to the filePath kiey of nodemailer.

```javascript
nodemailer: {
      all: {
        options: {
          transport: {
            type: 'SMTP',
            options: {
              host: 'mymailhost.net',
              ignoreTLS : true
            }
          },
          message: {
            from: "grunt@myhost.net",
            subject: 'whatever subject here',
            text: 'New deployment archive available and attached to this email.',
            html: '<body>New deployment archive ready !</body>',
            attachments:[{
              filename: 'HelpPages-' + target + '-<%= grunt.template.today("yyyymmdd") %>.tar.gz',
              filePath : 'dist/HelpPages-' + target + '-<%= grunt.template.today("yyyymmdd") %>.tar.gz',
              contentType: 'application/tar+gzip'
            }]
          },
          recipients: [
            {
              email: 'me@there.com',
              name: 'Just me'
            }
          ]
        }
      }
    }
```

In the mean time and as seen above, I've resorted to other means of building the file name.
