### ISSUE TITLE
1.0.0 migration document link is broken

### ISSUE THREAD

**Issue by callmevlad** [nodemailer/nodemailer#529]
The [changelog](https://github.com/andris9/Nodemailer/blob/master/CHANGELOG.md) currently links to http://www.andrisreinman.com/nodemailer-v1-0/#migrationguide for `v0.7.1 -> v1.0.0` migration, but the link leads to a blank page. 

Any chance it can be updated?

**Comment by alielgar** [comment]
I had the same problem and used achive.org. Not sure if it's the last version, but sill helps:

http://web.archive.org/web/20150317063407/http://www.andrisreinman.com/nodemailer-v1-0/

**Comment by migg24** [comment]
I think this here is the best URL to look for the migration guide:
https://nodemailer.com/readme/migration-from-0-7-to-1-0/
