### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by robinshields** [nodemailer/nodemailer#537]
Hi, I'm having an issue where nodemailer raises an unhandled error when sending a large number of emails (~1000). The code is:

```
transport = nodemailer.createTransport(smtpPool({
    host: 'localhost',
    port: 25,
    maxConnections:10
}));

var mailOptions = {
        from: (sender address),
        to: '',
        subject: subject, 
        text: txt,
        html: html,
    } 

async.eachSeries(users, function(user, cb){
			mailOptions.to = user.email;

            transport.sendMail(mailOptions, function(err, info){ 
            	if(err)
                  console.log(err);
            	cb();
            });
          },
          function(){
            console.log("JOB COMPLETE")
          }
);
```
It gets through about about 500 messages and then issues the following:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write ECONNRESET
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

Any ideas? I'm using exim4 to send the messages, I'm using nodemailer 1.0 and nodemailer-smtp-pool 1.0 on node 0.10.30. Thanks for your great package!

**Comment by andris9** [comment]
Could you try using the upcoming nodemailer v2.0.0 beta and see if the same issue happens with it as well?

    npm install nodemailer@beta

and then

```javascript
transport = nodemailer.createTransport({
    pool: true,
    host: 'localhost',
    port: 25,
    maxConnections:10
});
```

**Comment by robinshields** [comment]
Hi,
Thanks for the quick response. I installed the beta, but unfortunately it still happens (same error, line numbers). I also dropped maxConnections to 3, does the beta support rate limiting? If so, I'll try that, too.

**Comment by andris9** [comment]
It's kind of difficult to understand where's the issue as the line numbers point to nodejs internal code and thus aren't really useful. I can't reproduce it myself (i tried sending 10k messages to exim4, no errors) and no one else has also complained about it. Is your test script self contained or does the code run inside something else, eg. in an express.js app?

**Comment by robinshields** [comment]
Hi Andris,

Yes, it is inside an express app. I take the point about the line numbers and difficulty reproducing. I could try isolating inside a standalone script? Any other tips for troubleshooting gratefully received!

**Comment by andris9** [comment]
If you could get the same error with an isolated script then it would be great, otherwise it is hard to tell if the error actually came from nodemailer or maybe some express request was not finished properly

**Comment by robinshields** [comment]
I think you are right, it is probably in how I handled this in express (sent the response, then sent the emails). If you can leave open for a couple of days I can confirm this and it may help someone who makes a similar mistake!

**Comment by andris9** [comment]
Ok, let me know how it goes.

**Comment by robinshields** [comment]
Thanks for waiting, I've moved everything to a standalone script and yes, I
can send 2K emails with no hiccups or errors. I didn't uncover anything
that might help someone experiencing similar issues, other than the general
advice to move everything to a standalone if possible.

**Comment by andris9** [comment]
Usually what happens is that the express `res` socket gets closed somehow (maybe there's a load balancer or some max timeout or something) but the app still tries to write to it. For example if you write to the `res` after every email "message nr X sent" and it takes about the same amount of time for the `res` to get closed than sending 500 hundred messages, then trying to write "message nr 501 sent" is going to fail. Not sure if this is the case with your issue but this occurs quite often
