### ISSUE TITLE
Nodemailer, sent from field and signed by

### ISSUE THREAD

**Issue by mshref17** [nodemailer/nodemailer#539]
Hi,

I have a problem with nodemailer where the user receive the email with sent from my google account used to authenticate gmail instead of the alias used in mail options.

Below is my code:
```
var smtpTransport = nodemailer.createTransport({
    service: config.mailer.options.service,
    auth: {
        user: "xxxx@gmail.com",
        pass: "password"
    }
});


var mailOptions = {
       to: user.email,
       from: 'Test Email <aaa@aaa.com>',
       subject: subject,
       html: emailHTML
};

smtpTransport.sendMail(mailOptions);
```
 
Now when the user receive an email the email mentions that
from: Test Email <xxxx@gmail.com>
Instead of showing 
from: Test Email <aaa@aaa.com>

Any help please

**Comment by andris9** [comment]
This is because Gmail always sends messages as the authenticated user. If you want to use custom address then use some other service, for example Sendgrid or Mailgun or Postmark
