### ISSUE TITLE
Migration guide from v1 to v2

### ISSUE THREAD

**Issue by binarykitchen** [nodemailer/nodemailer#545]
Would be good to know what needs to be updated. Thanks!

**Comment by sahat** [comment]
It would be nice to have release notes and migration guide somewhere in Git releases similar to react and react-router projects. Meanwhile you can find a migration guide here: https://nodemailer.com/2-0-0-beta/migration-from-1-0-to-2-0/

**Comment by binarykitchen** [comment]
cool, thanks

**Comment by TrejGun** [comment]
:+1:

**Comment by andris9** [comment]
https://nodemailer.com/2-0-0-beta/migration-from-1-0-to-2-0/ is the official guide
