### ISSUE TITLE
Add "Go-To Actions"  in gmail subjects

### ISSUE THREAD

**Issue by mimani** [nodemailer/nodemailer#546]
Hi,

How can we add "[Go-To Actions](https://developers.google.com/gmail/markup/reference/go-to-action)" in subjects for gmail using this library?

**Comment by andris9** [comment]
Insert go-to code into the html content, there's nothing nodemailer specific in it

```javascript
var mail = {
    from: 'sender@example.com',
    to: 'receiver@example.com',
    subject: 'Message with Go-To Actions',
    html: '<p>this message uses go-to actions</p> <script type="application/ld+json">....</script>'
}
```
