### ISSUE TITLE
 Mailbox unavailable

### ISSUE THREAD

**Issue by gaurav113** [nodemailer/nodemailer#548]
I am using "nodemailer": "0.7.1", trying to send mail and it's giving me 550 error.

SERVER 1:
└──220 gmx.com (mrgmxus001) Nemesis ESMTP Service ready
CLIENT 1:
└──EHLO [127.0.0.1]
SERVER 2:
└──220 gmx.com (mrgmxus002) Nemesis ESMTP Service ready
CLIENT 2:
└──EHLO [127.0.0.1]
SERVER 1:
└──250-gmx.com Hello [127.0.0.1] [54.149.120.24]
   250-SIZE 69920427
   250-AUTH LOGIN PLAIN
   250 STARTTLS
CLIENT 1:
└──STARTTLS
SERVER 2:
└──250-gmx.com Hello [127.0.0.1] [54.149.120.24]
   250-SIZE 69920427
   250-AUTH LOGIN PLAIN
   250 STARTTLS
CLIENT 2:
└──STARTTLS
SERVER 1:
└──220 OK
SERVER 2:
└──220 OK
Connection secured
CLIENT 1:
└──EHLO [127.0.0.1]
Connection secured
CLIENT 2:
└──EHLO [127.0.0.1]
SERVER 1:
└──250-gmx.com Hello [127.0.0.1] [54.149.120.24]
   250-SIZE 69920427
   250 AUTH LOGIN PLAIN
CLIENT 1:
└──AUTH PLAIN XXXXXX
SERVER 2:
└──250-gmx.com Hello [127.0.0.1] [54.149.120.24]
   250-SIZE 69920427
   250 AUTH LOGIN PLAIN
CLIENT 2:
└──AUTH PLAIN XXXXXX
SERVER 2:
└──235 Authentication succeeded
CLIENT 2:
└──MAIL FROM:<abc@xxx.com>
SERVER 1:
└──235 Authentication succeeded
CLIENT 1:
└──MAIL FROM:<abc@xxx.com>
SERVER 2:
└──250 Requested mail action okay, completed
CLIENT 2:
└──RCPT TO:<gaurav@yopmail.com>
SERVER 1:
└──250 Requested mail action okay, completed
CLIENT 1:
└──RCPT TO:<client@mailiantor.com>
SERVER 2:
└──550-Requested action not taken: mailbox unavailable
   550 Failure sending mail. Try again later
{ [RecipientError: Can't send mail - all recipients were rejected]
  name: 'RecipientError',
  data: '550-Requested action not taken: mailbox unavailable\r\n550 Failure sending mail. Try again later',
  stage: 'rcpt' }
Closing connection to the server
SERVER 1:
└──550-Requested action not taken: mailbox unavailable
   550 Failure sending mail. Try again later
{ [RecipientError: Can't send mail - all recipients were rejected]
  name: 'RecipientError',
  data: '550-Requested action not taken: mailbox unavailable\r\n550 Failure sending mail. Try again later',
  stage: 'rcpt' }

**Comment by andris9** [comment]
Nodemailer 0.7 is deprecated and is not updated anymore (except for security issues), so I'd suggest you to upgrade to Nodemailer 2.0.

**Comment by gaurav113** [comment]
Yes, I have upgraded it to v2.0 and getting this error.
[Error: Unsupported configuration, downgrade Nodemailer to v0.7.1 to use it]
I am sending mail through SMTP only.

**Comment by andris9** [comment]
You can find the migration guide [here](http://nodemailer.com/readme/migration-from-0-7-to-1-0/). 

I looked at your SMTP transaction log and I do not see anything wrong with it. You try to send mail to some recipients and the server rejects these recipient addresses. Nodemailer can not change server behaviour – if the server does not want to deliver mail to these addresses for whatever reason then there's nothing Nodemailer could do. You can check gmx.com docs for the meaning of the error message [here](http://postmaster.gmx.com/en/error-messages/): "550 Requested action not taken: mailbox unavailable"

**Comment by gaurav113** [comment]
Thanks for the update.
