### ISSUE TITLE
Inline images not working in Mac Outlook

### ISSUE THREAD

**Issue by tomalex0** [nodemailer/nodemailer#552]
I'm trying to implement inline image attaching and it works fine in windows outlook, But in MacOs  Outlook, images appear as part of attachment and inline images are empty. Below is my code

I'm i missing any config options?

```

 var mailData = {
        from: 'ourmail@gmail.com',
        to: 'youremail@gmail.com',
        subject: 'Subject',
        attachments: [{
           filename: 'icon.gif',
           path : './images/icon.gif',
           cid: 'cid:icon.gif' 
       }],
        html:'<div>Test <br><img class="fix" src="cid:icon.gif" width="70" height="70" border="0" alt="" /></div>'
    };
```

**Comment by andris9** [comment]
What version of Outlook are you using? I can't really confirm this bug (Outlook for Mac 15.14.2).

I sent [full.js](https://github.com/nodemailer/nodemailer/blob/master/examples/full.js) from the Nodemailer examples to my Outlook account and this is what I see (images are displayed just as expected):

![](https://cldup.com/ZlWJ4Y9UM6.png)

**Comment by tomalex0** [comment]
thanks @andris9 it worked perfectly

Looks like i was doing wrong here `cid: 'cid:icon.gif' `

**Comment by niftylettuce** [comment]
Try this package: https://github.com/crocodilejs/nodemailer-base64-to-s3
