### ISSUE TITLE
Limit of bcc list

### ISSUE THREAD

**Issue by aralroca** [nodemailer/nodemailer#557]
Is not a issue, is a question.

**How many emails is posible to include to the bcc list? Is it possible for newsletters to send to all my users (around 2000) including all of them in the bcc list?**

Thank you very much!

**Comment by andris9** [comment]
The amount of recipients allowed (all *to*, *cc*, *bcc* addresses share the same limits) always depends on your SMTP provider. For example Gmail [allows](https://support.google.com/a/answer/166852?hl=en) max 100 recipients per message. Other providers might allow other limits, so you need to check your provider.
