### ISSUE TITLE
Add new transport type: IMAP

### ISSUE THREAD

**Issue by andris9** [nodemailer/nodemailer#561]
IMAP as a transport type would be mainly useful for uploading messages to users' Sent folder in the IMAP server. This would require a minimal IMAP client with support for the following IMAP features:
- Authentication
- LIST command to see if a folder exists or not and what flags does the folder have
- SELECT command to select the mailbox
- APPEND command to actually upload the message
- Potentially COMPRESS to leverage data compression (not required though)
- Either UIDPLUS or FETCH UID (or better yet, _UID SEARCH HEADER "message-id" "..."_ instead of FETCH) to find out the UID of the uploaded message

This issue is not related to v2.2 milestone anymore as transport plugins do not depend on the exact Nodemailer version. Could be used with Nodemailer v1.x just as well

**Comment by simonhochrein** [comment]
would it be posible to use node-imap for that?
