### ISSUE TITLE
Space character is being lost in subject of the mail

### ISSUE THREAD

**Issue by titarenko** [nodemailer/nodemailer#562]
Hi!

Sometimes, we got emails with broken subject, like:

sent: ```var mail = { subject: 'Бета-продакшн: платежка 2422750 от 2015-07-20' };```
received: ```Бета-продакшн: платежка2422750 от 2015-07-20```

Details are here: https://github.com/nodemailer/buildmail/issues/11 (technically it's related to `buildmail` module).

**Comment by andris9** [comment]
This is a bug in Mandrill, I'm not sure if or how fast can they handle this, regarding their current situation where they are merging Mandrill with MailChimp.

As a workaround you can use the following construct to ensure the folding issue does not occur:

```javascript
var subject = 'Бета-продакшн: платежка 2422750 от 2015-07-20';
var mail = {
    ...,
    subject: {
        prepared: true,
        value: '=?UTF-8?B?'+new Buffer(subject).toString('base64')+'?='
    },
    ...
};
```
