### ISSUE TITLE
oauth gmail error: { [Error: unauthorized_client] code: 'EAUTH' }

### ISSUE THREAD

**Issue by cleechtech** [nodemailer/nodemailer#564]
I have login with google oauth set up. I pasted in the  `accessToken` field from what got returned from login with google. I cannot get past this error `{ [Error: unauthorized_client] code: 'EAUTH' }`.

```
var express = require('express'),
	nodemailer = require('nodemailer'),
	xoauth2 = require('xoauth2'),
	router = express.Router();

// create reusable transporter object using the default SMTP transport
var transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        xoauth2: xoauth2.createXOAuth2Generator({
            user: "connorleech@gmail.com",
            clientId: '925......4cui6indku1jgr7g7kpg6.apps.googleusercontent.com',
            clientSecret: "Y1l..........N7xkKd1x",
            refreshToken: "1/LFVq94wxy6uWMP............QqEWxIgOrJDtdun6zK6XiATCKT",
            accessToken: 'eyJ0eXAiOiJKV....................Zxd4uAPJlZqAdJwcHO3prmVSOtTo4PvEXkzhFJJo'
        })
    }
});

/*

 |--------------------------------------------------------------------------
 | POST /sendEmails
 |--------------------------------------------------------------------------
 */
 router.post('/sendToList', function(req, res){
 	console.log(req.body);

 	// setup e-mail data with unicode symbols
	var mailOptions = {
	    from: 'connorleech@gmail.com', // sender address
	    to: 'connorleech@gmail.com, baz@blurdybloop.com', // list of receivers
	    subject: 'Hello ✔', // Subject line
	    text: 'Hello world 🐴', // plaintext body
	    html: '<b>Hello world 🐴</b>' // html body
	};

	// send mail with defined transport object
	transporter.sendMail(mailOptions, function(error, info){
	    if(error){
	        return console.log(error);
	    }
	    console.log('Message sent: ' + info.response);
	});

 });

 module.exports = router;
```

**Comment by andris9** [comment]
Can't help much here, Gmail is really picky. Sometimes the client needs to be re-authorized, sometimes the correct scope (`"https://mail.google.com/"`) is missing. Nodemailer just passes on the access token to Gmail as it is, or generates next one using the refresh token but does not modify any permissions etc.

**Comment by cleechtech** [comment]
Mixed blessing, glad gmail has such good security but a pain for developers!

**Comment by ferchichi01** [comment]
Hi @connor11528 did you fix the issue

**Comment by AdamCraven** [comment]
For anyone having "unauthorized_client" issues whilst the following apply:

Using a service account
Have a google suite account attached
Have followed all the 2 leg instructions at: https://nodemailer.com/smtp/oauth2/#oauth-2lo
I finally solved it following the documentation here: https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority

In essence going to
https://admin.google.com/**yourgsuitedomain.com**/ManageOauthClients
Adding a client id (from service account) and scope: https://mail.google.com/ (final slash important)

Everything finally started working 🎉

**Comment by yoo-gyoon** [comment]
@AdamCraven 

Thank you for the message above.
I have been trouble shooting the crap out of the `2LO` OAuth method for sending gmail through nodemailer. (the less secure, and `3LO` methods work, but for easiest replication, I am trying to get the `2LO` method to work)

I noticed that you have a G Suite account attached - my setup is through Firebase (and I am running the nodemailer code on Firebase Cloud Functions with a service account attached to a Firebase project) and am wondering if my woes are due to the fact that I do not have a G Suite account.

Thanks for any additional info you might have!

**Comment by yoo-gyoon** [comment]
I was able to try signing up for G Suite for the domain linked to our Firebase web project and this seems to solve the issue.
Thank you again for the tip above!

**Comment by FlacorLopes** [comment]
I forget to click on the gear icon at oauth2 playground and insert my OAuth Client ID and OAuth Client Secret.
Once i did it, it worked fine

![image](https://user-images.githubusercontent.com/1523957/105229664-0b923600-5b43-11eb-9694-3991235316f8.png)

**Comment by vnvyvu** [comment]
another case, make sure you have published the application:
![image](https://github.com/nodemailer/nodemailer/assets/22812601/d7db6587-da27-4edc-8c13-d1066eec6273)
then, do `Step1: authorize APIs` and `Step 2: exchange authorization code for tokens` again
