### ISSUE TITLE
replyTo field not passing the message header

### ISSUE THREAD

**Issue by epitaphmike** [nodemailer/nodemailer#571]
Include the following information with your issue:

nodemailer: ^2.1.0
nodemailer-mailgun-transport: ^1.0.1
Node - 4.2.6
Ubuntu 14.04

I am not 100% if this should be here or the nodemailer-mailgun-transport repo. The issue I am coming across on the mailgun side is messages are being blocked when I set the from from email as the users email who is filling out our form when they have an AOL email address. I know I know... AOL, that aside. 

I tried setting the from to an email address on my domain and set the replyTo field to the users AOL address so when we replied to the user in our email, it would reply to them and not our from address.

Unfortunately the replyTo field is never getting sent with the message header. Even when I send is in the mailOptions object.

I get this in the mailgun logs.

"headers": {
      "to": "info@DOMAIN.com",
      "message-id": "20160223031159.1950.79977@DOMAIN.com",
      "from": "postmaster@DOMAIN.com",
      "subject": "Email Subject Line"
    },

This is the error I get in the logs from mailgun.

Failed: postmaster@DOMAIN.com → info@DOMAIN.com 'Email Subject Line-8XU096659W0815542K3F4U7I' Server response: 550 550 5.7.1 Unauthenticated email from aol.com is not accepted due to domain's 5.7.1 DMARC policy. Please contact administrator of aol.com domain if this 5.7.1 was a legitimate mail. Please visit 5.7.1 https://support.google.com/mail/answer/2451690 to learn about DMARC 5.7.1 initiative. 95si11803781qgi.45 - gsmtp

Any help on the matter would be greatly appreciated.

Thank you.

**Comment by andris9** [comment]
This does not affect only AOL, a lot of large mail providers have struct DMARC rules set. 

nodemailer-mailgun-transport does not use the "normal" mime-message creation but maps message options to Mailgun's HTTP API. I don't know if replyTo field is also mapped or not.

**Comment by epitaphmike** [comment]
I posted a message on that repo as well. Thank you for the very quick reply.

**Comment by epitaphmike** [comment]
From the looks of it, replyTo is not mapped. https://github.com/orliesaurus/nodemailer-mailgun-transport/blob/master/src/mailgun-transport.js

I am going to map it myself locally, test and if it works, I'll submit a pull request to that repo.

Thanks again.

**Comment by epitaphmike** [comment]
Seems as if this is already a pull request that was added back in October. https://github.com/orliesaurus/nodemailer-mailgun-transport/pull/19
Tested and works.
