### ISSUE TITLE
The "slash" character in SMTP password causes transporter to fail when using connection URL

### ISSUE THREAD

**Issue by chetanvaity** [nodemailer/nodemailer#572]
Nodemailer version: 2.1.0
Node version: 4.2.2
OS: Ubuntu 14.04

The problem manifests as
Unhandled rejection Error: getaddrinfo ENOTFOUND blah blah:465
    at errnoException (dns.js:26:10)

The problem is the host it is trying to connect to: "blah" is actually part of the username specified in the connection Url.

On further digging, found that this is a problem in parseConnectionUrl in the nodemailer-shared project (again in the way urllib is being used)

Reproduce:
Try creating a transport with something like this:
var connUrl = 'smtps://ABCD:PQRS/WXYZ@some-smtp-host.com';

Then the host used for connecting is "abcd" instead of "some-smtp-host.cpm"

**Comment by andris9** [comment]
username and password must be urlencoded as defined in the URL [standard](https://url.spec.whatwg.org/) if you need to use any special characters

**Comment by chetanvaity** [comment]
Oops! My bad.
