### ISSUE TITLE
Getting error when ever i try to use nodemailer

### ISSUE THREAD

**Issue by ashutoshdev** [nodemailer/nodemailer#573]
Server up: http://localhost:3300
{ [Error: getaddrinfo ENOTFOUND 1234 1234:465]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '1234',
  host: '1234',
  port: 465 }

**Comment by andris9** [comment]
It seems like you are using 1234 as the hostname of your smtp server. Check your configuration, you have probably something invalidly set up
