### ISSUE TITLE
Unexpected token ILLEGAL?

### ISSUE THREAD

**Issue by caboosesw** [nodemailer/nodemailer#574]
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/srv/quigley-be/www/node_modules/nodemailer/lib/nodemailer.js:3:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

I will admit I am a nodejs and even a Linux newbie (well, maybe newbie++) but I can't even add the module ... might not even be a nodemailer issue ... but any help would be great

var nodemailer = require('nodemailer');

nodemailer 2.2.1
node 4.2.3
redhat under vagrant (4.2.6-201.fc22.x86_64)

**Comment by andris9** [comment]
No idea. This could mean almost anything - from a faulty Nodemailer installation to an invalid node installation.

From the error I would assume that node fails to load `mailcomposer` module for whatever reason. You could try to locate where mailcompose files are located (most probably under the same node_modules folder where nodemailer itself can be found) and then run `node lib/mailcomposer.js` to see if node can run it without errors (normally there shouldn't be any output)

**Comment by andris9** [comment]
I'll close this issue for now. Feel free to re-open it if you find any additional information, for now it seems more like an issue with incorrect environment.

**Comment by johnny88** [comment]
So I received this error also when I ran node 4. I think it is an incompatibility with node 4 because when I moved to node 6 things seemed to work. I would recommend people either move to a newer version of node (since node 4 will only be supported for a few more months) or try an older version of node mailer.

I also don't think this should be reopened, just hoping to add some more context to the issue and a potential way of solving this if other find themselves in a similar position.

**Comment by andris9** [comment]
The latest version of Nodemailer (eg v3+) requires Nodejs v6 and does not work with older versions of node (mostly because of the spread operator which is not supported in Node v4). Nodemailer v2.7.2 and lower support Nodejs 0.10

**Comment by johnny88** [comment]
That's what was breaking it. I had the exact same stack as @caboosesw but instead of "ILLEGAL" I got "...". Thanks for the clarification!

**Comment by cagarweyne** [comment]
@andris9 spot on. Installing the latest version of node should resolve the issue.
