### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by xiujiang** [nodemailer/nodemailer#575]
When sending large mail context, it will appear as below:
"node_modules/nodemailer/node_modules/libmime/src/libmime.js:40
        return new RegExp('^.{' + (lineLength + 1) + ',}', 'm').test(str);
                                                                ^
RangeError: Maximum call stack size exceeded

It seems "str" is too big and RegExp().test get statck size exceeded.

1) Nodemailer version 1.3.0
2) Node.js version 0.10.33
3) Linux 64 bits

**Comment by andris9** [comment]
If your content is very large, then use Buffers instead of Strings.

```javascript
var mailData = {
    ...,
    html: new Buffer('<html>..... very large string', 'utf-8')
};
```
