### ISSUE TITLE
ndemailer hangs in pooled mode and ignores socket timeout

### ISSUE THREAD

**Issue by kurevo1996** [nodemailer/nodemailer#576]
Im using nodemailer 2.2.0-rc.9 and nodejs 0.10.40, and im using proxified socket for nodemailer connection. I also did set the `pool: true` option. Then i do `transport.sendEmail` per some timeout, about 3-5 minutes. So basically first time the send is ok, but then, after the timeout it seems that the socket is hanging up:

```
I20160226-09:10:40.973(2)? [2016-02-26 07:10:40] INFO: [e5fslMNgaMU] C: <13667 bytes encoded mime message (source size 13505 bytes)>
I20160226-09:10:41.277(2)? [2016-02-26 07:10:41] DEBUG: [e5fslMNgaMU] S: 250 OK id=1sdfgew-0006AS-LP
I20160226-09:10:41.281(2)? [2016-02-26 07:10:41] DEBUG: Connection #1 became available
I20160226-09:14:01.322(2)? >>>>>>>>>>>Timeout passed<<<<<<<<<<<<<<<
I20160226-09:14:01.328(2)? [2016-02-26 07:14:01] INFO: Sending mail using SMTP (pool)/2.3.1[client:2.2.5]
I20160226-09:14:01.330(2)? [2016-02-26 07:14:01] DEBUG: Assigned message <1456470841329-37c37263-432afadf-59b4dsad@mail.ru> to #1 (2)
I20160226-09:14:01.331(2)? [2016-02-26 07:14:01] INFO: Sending message <1456470841329-37c37263-432afadf-59b4d5fd@mail.ru> using #1 to <someone@mail.ru>
I20160226-09:14:01.335(2)? [2016-02-26 07:14:01] DEBUG: [e5fslMNgaMU] C: MAIL FROM:<myemail@mail.ru>
```

So as you can see there is a 4 minute gap, after which my code is getting stuck on this line 

`I20160226-09:14:01.335(2)? [2016-02-26 07:14:01] DEBUG: [e5fslMNgaMU] C: MAIL FROM:<myemail@mail.ru>`

I did set the timeout for the transport:

 ```
this.transporter = nodemailer.createTransport({
            pool : true,
            host: 'smtp.' + this.server,
            port: this.port,
            auth: {
                user: this.login,
                pass: this.password
            },
            logger: true, // log to console
            debug: true, // include SMTP traffic in the logs
            secure: true,
            socketTimeout : 120 * 1000
        });


```

I did set the socket timeout for 2 minutes here, but it looks like its beign ignored, i was waiting like 30 minutes or so, code still was stuck with that message in console. How do you overcome this issue?

**Comment by andris9** [comment]
It seems really strange. I tried to replicate this (btw are you using mail.ru to send mail?) but was not able to. Seems like something is keeping the socket alive, at least from your side, so the timeout doesn't kick in (maybe some proxy in between?). Could you try using even lower timeut value, eg 10 sec.?

**Comment by kurevo1996** [comment]
Yes im using mail.ru with socks proxy. If i set the timeout for 10secs i get in the logs:

```
 [2016-03-04 21:44:37] ERROR: Pool Error for #1: Timeout
I20160304-23:44:37.663(2)? [2016-03-04 21:44:37] DEBUG: [PhKKDfQID5U] Closing connection to the server using "end"
```

If you want to replicate it just try to set some public proxy from hideme.ru  with really bad ping, and set the socket timeout bigger , than the sleep timeout in which you send the letters. So i think in between the connection to the proxy gets aborted, and nodemailer gets hanged on the sending

**Comment by andris9** [comment]
I think it's an issue with the proxy module. If proxy module does not inform Nodemailer that the connection is lost then there's not much Nodemailer can do about it, at least I haven't figured out a solution.
