### ISSUE TITLE
Filename of attachments with dashes in filename are sometimes truncuated in gmail

### ISSUE THREAD

**Issue by tepez** [nodemailer/nodemailer#579]
I'm sending emails with attachment using nodemailer 2.2.1.

I recently started getting complaints that attachments names are sometimes truncated.

This seems to happen only when dashes Unicode characters are involved, e.g. for the filename `Ɣ------Ɣ------Ɣ------Ɣ------Ɣ------Ɣ------Ɣ------.pdf`, the user would see this attachment:

![image](https://cloud.githubusercontent.com/assets/3265649/13402677/0e60d5a8-df1a-11e5-9a83-f1e8a5781a15.png)

This is ofcourse not a real filename, but all the filenames that shows this issue has dashes and unicode characters.

```
Content-Type: application/pdf;
 name="=?UTF-8?B?xpQtLS0tLS3GlC0tLS0tLcaULS0tLS0txpQtLS0t?=
 =?UTF-8?B?LS3GlC0tLS0tLcaULS0tLS0txpQtLS0tLS0ucGRm?="
Content-Disposition: attachment;
 filename*0*=utf-8''%C6%94------%C6%94------%C6%94------%C6%94;
 filename*1*="------%C6%94------%C6%94------%C6%94------.pdf"
Content-Transfer-Encoding: base64
```

When I sent the same file using game it came just fine:

![image](https://cloud.githubusercontent.com/assets/3265649/13402642/e27fdefc-df19-11e5-8d1b-32ffd0164da8.png)

```
Content-Type: application/pdf; 
	name="=?UTF-8?B?xpQtLS0tLS3GlC0tLS0tLcaULS0tLS0txpQtLS0tLS3GlC0tLS0tLcaULS0tLS0txpQtLS0tLS0ucA==?=
	=?UTF-8?B?ZGY=?="
Content-Disposition: attachment; 
	filename="=?UTF-8?B?xpQtLS0tLS3GlC0tLS0tLcaULS0tLS0txpQtLS0tLS3GlC0tLS0tLcaULS0tLS0txpQtLS0tLS0ucA==?=
	=?UTF-8?B?ZGY=?="
Content-Transfer-Encoding: base64
```

Is this a gmail bug or a nodeemail bug?

**Comment by andris9** [comment]
Seems like a bug in Nodemailer, the quote after `filename*1*=` is extraneous. I'll look into it

**Comment by andris9** [comment]
I added the patch to the current beta release (v2.3.0) of Nodemailer. You can try it out by installing:

    npm install nodemailer@beta

or waiting until to the end of this week when the beta should be released as stable

**Comment by tepez** [comment]
Thanks @andris9 !
I checked my code with the beta version and it worked.
