### ISSUE TITLE
Very high memory usage?

### ISSUE THREAD

**Issue by ralphmason** [nodemailer/nodemailer#582]
Sending an email with a 3mb attachment causes 300mb of ram usage.  Sample application and output below that recreate the issue.

Nodemailer V2.3.0
Node Version V.5.5.0
OSX v10.11.3, & Linux

**Application output in the format - Text,  Total Mem,  Delta**
start 20 20
string created 26 6
loader mailer 33 6
created transport 33 0
sending 137 104 <-  +104mb when we call Sendmail
sent mail 332 195 <- +195mb when we are done

**Simple App**
```

var last=0;

function mem(s){
  var mem=process.memoryUsage().rss/1000000;

    console.log(s,Math.round(mem),Math.round(mem-last));
    last=mem;
}
mem('start');

var b=new Buffer(3000000);
b.fill(65);
var str=b.toString();

mem('string created')

var mailer=require('nodemailer');

mem('loader mailer');

var transporter = mailer.createTransport('smtps://user:pass@smtp.mailgun.org');

mem('created transport');

var mailOptions = {
    from: '"Fred Foo 👥" <foo@blurdybloop.com>', // sender address
    to: 'user@domain.com', // list of receivers
    subject: 'Hello ✔', // Subject line
    text: 'Hello world 🐴', // plaintext body
    html: '<b>Hello world 🐴</b>', // html body
    attachments:[{
       filename:'report.csv',
       content:str,
        contentType: 'text/csv'
       }]
   };

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    mem('sent mail');
});

mem('sending');


```

**Comment by andris9** [comment]
Do not use large attachments as buffers or strings, use a file path to process it as a stream. High memory usage for such a script is normal – as long as the used memory gets cleared after the garbage collector kicks in after a while.
