### ISSUE TITLE
Umm...

### ISSUE THREAD

**Issue by JimTheMan** [nodemailer/nodemailer#583]
Hi. This documentation doesn't make any sense at all to me. I wanted to use the TL;DR, but I guess it doesn't actually work? Seems like it's pretty dumb to even put it there then. 

Also, you don't explain at all what the parameters to "createXOAuth2Generator" are so I'm not sure how anyone is actually able to use this library..

var transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        xoauth2: xoauth2.createXOAuth2Generator({
            user: '{username}',
            clientId: '{Client ID}',
            clientSecret: '{Client Secret}',
            refreshToken: '{refresh-token}',
            accessToken: '{cached access token}'
        })
    }
});

**Comment by andris9** [comment]
This is standard OAUTH2 and out of scope to be explained in Nodemailer docs. Check the documentation of your OAUTH provider of what these values stand for and how to retrieve these. https://developers.google.com/identity/protocols/OAuth2
