### ISSUE TITLE
Econnrefused no matter what I do

### ISSUE THREAD

**Issue by NicoYUE** [nodemailer/nodemailer#588]
Hello,

I'm on Centos 6.6, with node 4.4 and Nodemailer 2.3

I've been trying to send a mail with Gmail service with no success. Everytime I get:

```
code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',

```
I googled this for some time already, at first I thought it'd be Firewall issue but even after running 

`iptables stop`

I still encounter this problem.

Here's the code: (as example, gmail account=NY and password=NY@2016)

```
var nodemailer = require('nodemailer');

// create reusable transporter object using the default SMTP transport
var transporter = nodemailer.createTransport('smtps://NY@gmail.com:NY@2016@smtp.gmail.com');

// setup e-mail data with unicode symbols
var mailOptions = {
    from: '"Fred Foo" <NY@gmail.com>', // sender address
    to: 'NY@gmail.com', // list of receivers
    subject: 'Hello ✔', // Subject line
    text: 'Hello world ', // plaintext body
    html: '<b>Hello world </b>' // html body
};

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    console.log('Message sent: ' + info.response);
});
```

I tried many syntaxes and even downgrading to 0.7.1 but it's always the same things, Econnrefused.

**Comment by andris9** [comment]
Is it possible to connect using command line?

    $ openssl s_client -crlf -connect smtp.gmail.com:465
    > ....
    > 220 smtp.gmail.com ESMTP mi9sm4352472lbc.27 - gsmtp

**Comment by NicoYUE** [comment]
No, I'm getting this:

```
WARNING: can't open config file: /opt/anaconda1anaconda2anaconda3/ssl/openssl.cnf
connect: Connection refused
connect:errno=111
```

**Comment by andris9** [comment]
Maybe the following SO thread helps: http://stackoverflow.com/questions/27312068/openssl-socket-connection-refused-connecterrno-111

**Comment by NicoYUE** [comment]
I think maybe I can't access to the SMTP server because I'm under company proxy ?

How do you actually set Auth Proxy within nodemailer ?

**Comment by andris9** [comment]
See [using proxies](http://nodemailer.com/2-0-0-beta/setup-smtp/using-proxies-with-smtp/) from the Nodemailer homepage for the documentation of setting up proxy usage
