### ISSUE TITLE
Greeting never received

### ISSUE THREAD

**Issue by sandromartis** [nodemailer/nodemailer#590]
Hello

I have the problem that I get the occasional error message:
```
error:  Error: Greeting never received 
    at SMTPConnection._formatError (/app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:388:15) 
    at SMTPConnection._onError (/app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:378:29) 
    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:322:18) 
    at Timer.listOnTimeout (timers.js:89:15) 
``` 

I'm using Mandrill email service with the following setup:
```
var smtpTransport = nodemailer.createTransport({
    service: mandrill',
        auth: {
            user: 'MANDRILL_EMAIL_ID',
            pass: 'MANDRILL_PASSWORD'
    }
});
```
This error seems to pop up pretty randomly. Sometimes the email gets sent despite receiving the error message, but sometimes the email does not get sent at all.

Is this an issue with Nodemailer or with Mandrill itself? I only had the error maybe 5-10 times the past couple of weeks.
I don't think it's an issue with SSL, since usually email sending works fine. (I'm sending about 70 emails per week)

The strange thing is that this error only started to pop up maybe 2 months ago.
I have the same setup since more than a year and never had the issue before.

Thanks and kind regards
Sandro

**Comment by andris9** [comment]
If this happens occasionally then you could try to increase the greeting timeout by changing `greetingTimeout` option (defaults to 10000)

**Comment by sandromartis** [comment]
I haven't seen this issue in the last couple of weeks. So I assume it was just some temporary problem with Mandrill itself. Probably just some delay on their side that triggered the error message.

I'm gonna close this for now.

**Comment by sheppyc** [comment]
@sandromartis We get this intermittently as well and I'm currently investigating. We're using nodemailer 1.5, mandrill, and not using SSL.

We send 2 emails in reasonably quick succession, and sometimes 1 gets sent, and not the other..

**Comment by sandromartis** [comment]
@sheppyc I haven't seen this error message anymore since I closed this issue.
I also currently don't see anything in my logs. Thus I suspect that this is some problem with Mandrill itself and not with nodemailer.
I don't really understand how nodemailer works internally, but I suspect that this error message pops up when nodemailer does not receive a response from Mandrill within `greetingTimeout`.
If the Mandrill servers don't send any response at all (due to overload or whatever reason) then of course increasing `greetingTimeout` does not help.
I guess the best solution here is to contact Mandrill and check if there's an issue on their side.

**Comment by sheppyc** [comment]
@sandromartis The strange thing is that everything worked fine with mandrill, then we switched to sparkpost, started to hit these issues, went back to mandrill, and still had these issues.

We may have changed something in the initial switch so will go back through our history to diagnose. If we sort, will update this issue (even though it's closed)
