### ISSUE TITLE
Allow transport to specify a function to modify any messages sent through it

### ISSUE THREAD

**Issue by rightaway** [nodemailer/nodemailer#591]
Would be great if transports allowed you to specify a function that can modify messages passing through it. This could have many uses.

For example, let's say you want to prefix every email subject with the name of your site. So instead of 'Here is a subject' it would be '[Website name] Here is a subject'. Instead of needing to add that prefix to each subject scattered throughout your application code in the many places you're sending mail from, you can do it in one place.

Other use cases could be things like filtering out certain words from the message body (spammy or swear words), internationalization, etc. Or replacing certain words with another. Or logging what goes through the transport.

**Comment by andris9** [comment]
You can achieve something like this with plugins.

```javascript
var nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport(require('nodemailer-stub-transport')());

var plugin = function (mail, callback) {
    mail.data.subject = '[Website name] ' + mail.data.subject;
    return callback(null);
};

transporter.use('compile', plugin);

transporter.sendMail({
    subject: 'test'
}, function (err, info) {
    console.log(info.response.toString());
});
```

And the output of such a script would be:

```
Content-Type: text/plain
Subject: [Website name] test
Message-Id: <1460424796727-2a56b827-db14908e-a63d921f@localhost>
…
```
