### ISSUE TITLE
encryption:	zoho.com didn't encrypt this message

### ISSUE THREAD

**Issue by oviliz** [nodemailer/nodemailer#592]
Hi guys,
I'm using ghost.org installed in a cleaned Ubuntu 14.04. Node.js is v4.4.2 while the Nodemailer version must be 0.7.1 (judging from the CHANGELOG).

I'm using the service Zoho without anything else except for auth and pass; the emails are going trough, but Gmail is showing a Lock icon saying 

> encryption: zoho.com didn't encrypt this message (with a link to https://support.google.com/mail/answer/6330403 )

Any idea?

**Comment by andris9** [comment]
This means that the message delivered from Zoho to Gmail was not encrypted while the connection between your server and Zoho probably was. There's nothing you can do besides complaining to Zoho about it.
