### ISSUE TITLE
Throw error if trying to render token that hasn't been provided

### ISSUE THREAD

**Issue by rightaway** [nodemailer/nodemailer#593]
Using the templating built-in renderer functionality, if you have a token like `{{ user }}` in the message but it hasn't been provided, a literal `{{ user }}` will appear in the produced message. Instead an error should be thrown as it's a developer error that a token wasn't provided.

**Comment by andris9** [comment]
The built-in renderer is really basic. If you need special features then you should probably use a custom renderer or roll your own. Here's an example of setting up custom renderer: [template/custom.js](https://github.com/nodemailer/nodemailer/blob/master/examples/template/custom.js)
