### ISSUE TITLE
Mail not sent and callback not called

### ISSUE THREAD

**Issue by daarond** [nodemailer/nodemailer#594]
1) Nodemailer version: 2.3.0
2) Node.js version: 5.2.0
3) OS: windows 7

My problem is that mail doesn't seem to get sent and the callback is never called.
Here's the basic code

var mail = {
      from: "daarond@gmail.com",
      to: "daarond@gmail.com",
      subject: "Sending "+new Date().getMilliseconds(),
      text: "Node.js New world for me",
      html: "<b>Node.js New world for me</b>"
    };

    // Use Smtp Protocol to send Email
    var gmail_transport = nodemailer.createTransport({
      service: 'Gmail',
      auth: {
        user: "daarond@gmail.com",
        pass: '[my pass]'
      },
      logger: true, // log to console
      debug: true
    });

    gmail_transport.sendMail(mail, function(error, info){
      if(error){
        return console.log(error);
      }
      console.log('Message sent: ' + info.response);
    });

The only thing showing in the console is:
[2016-04-04 19:41:20] INFO: Sending mail using SMTP/2.4.1[client:2.3.1]

If I change to another provider on smtp with a transport of:
var stringtrans = nodemailer.createTransport('smtp://daarontest%40wrightfortexas.com:mypassword@mail.wrightfortexas.com');

...then nothing shows in the console and the email is still not sent.

The more verbose version has the same effect:
    var smtp_transport = nodemailer.createTransport(smtpTransport({
      host: "mail.wrightfortexas.com",
      port: 25,
      secure: false,
      auth: {
        user:"daarontest@wrightfortexas.com",
        pass:"mypass"
      },
      logger: true, // log to console
      debug: true
    }));

I also signed up for debugmail.io to try to understand what's going on, and this transport fails similarly.
var debugio_trans = nodemailer.createTransport({
      service: 'DebugMail.io',
      auth: {
        user: "daarond@gmail.com",
        pass: 'project pass'
      },
      logger: true, // log to console
      debug: true
    });

I must be doing something very basic wrong to have the same effect.
Any help would be appreciated.

**Comment by daarond** [comment]
More Info:
The method containing nodemailer was being called from Mocha/Chai. After frustration in email, I went on to another part of the application, attempted another library (unirest), and encountered the same issue. Not sure how mocha is jacking the callback up, but it is.

Sorry for the ping, I'll close this.

**Comment by okabamac** [comment]
I am having the same issue. Can I know how you managed to solve it?
