### ISSUE TITLE
gmail recieves malformed text

### ISSUE THREAD

**Issue by raistlinthewiz** [nodemailer/nodemailer#597]
nodemailer: 2.3.2
node.js: 5.10
os: windows 10

I'm sending mails through mailjet and checking them with gmail but gmail doesn't render them correctly.

I see that my spaces are encoded as '3D'

original text;
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\r\n  <meta name="viewport" content="width=device-width, initial-scale=1" />\r\n
```

gmail recieves the text;
```
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www=
=2Ew3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns=3D"http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DUTF-8" =
/>
  <meta name=3D"viewport" content=3D"width=3Ddevice-width, initial-scale=3D=
1" />
```

any ideas?

**Comment by andris9** [comment]
This is called quoted-printable encoding, I don't see anything wrong with it. "=3D" gets decoded to "=". You should try a service like [Litmus](http://litmus.com/) to test how your messages look like in Gmail or in any other email client since there are a lots of quirks how these clients actually render the original HTML input.

**Comment by raistlinthewiz** [comment]
I've tested with litmus now, everything seems okay but gmail seems to garbage up my email somehow.
