### ISSUE TITLE
Not sending full picture

### ISSUE THREAD

**Issue by NicoYUE** [nodemailer/nodemailer#599]
Hello,

I'm using Node 5.10.1 with the latest version of nodemailer on Centos 6.7.

I met a problem when sending an attachment picture to a fastmail adress:

The picture is not being fully loaded before being sent, I end up with only the heading of the picture I'm willing to attach.

Used to work perfectly so no idea why it's doing this. Do I need to set a timeout ?

**Comment by andris9** [comment]
Reopen if you still have this problem
