### ISSUE TITLE
Is SMTP required?

### ISSUE THREAD

**Issue by xeoncross** [nodemailer/nodemailer#6]
I'm wondering if I have to setup SMTP just to send mail using the default server postfix setup. I'm trying to move from mailing use bash or PHP to node.js. Can this package call a command-line `mail -s "something" -m "message" email@example.com` or something and skip the SMTP stuff?

Or am I thinking about this wrong?

**Comment by knoxcard** [comment]
Wow, this worked for me.  I have openDKIM attached to postfix, so every message I send attaches the DKIM header.  For some reason, nodemailer does not play nice with it.  Switching over to sendmail and including the DKIM info as such did the trick!
```

                    sendmail: app.nconf.get('ENV') == 'LIVE' ? true : false,
                    dkim: {
                        domainName: 'indospace.io',
                        keySelector: 'mail',
                        privateKey: require('fs').readFileSync('data/mail.private')
                    }

```
