### ISSUE TITLE
Sendgrid Category

### ISSUE THREAD

**Issue by thenitai** [nodemailer/nodemailer#600]
Hi there,

Using the latest nodemailer.

Having issues setting the category header so they show up in Sendgrid. This is my code:
```
mailoptions.headers = {
"category": "product_plugin"
};
```
Despite this and the sendgrid doc it doesn't show. The header is being sent and shows up. 

Maybe someone has an idea? Thank you.

**Comment by andris9** [comment]
Are you using [nodemailer-sendgrid-transport](https://github.com/sendgrid/nodemailer-sendgrid-transport) or the regular SMTP based transport?

**Comment by thenitai** [comment]
I'm using the standard smtp transport.
On Wed, Apr 13, 2016 at 6:56 PM Andris Reinman <notifications@github.com>
wrote:

> Are you using nodemailer-sendgrid-transport
> <https://github.com/sendgrid/nodemailer-sendgrid-transport> or the
> regular SMTP based transport?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nodemailer/nodemailer/issues/600#issuecomment-209704138>
>
-- 
See for yourself how easy it is to manage files today. Join the revolution!

Razuna - Hosted Digital Asset Management Solution
http://www.razuna.com/

Razuna - Open Source Digital Asset Management
http://www.razuna.org/

Twitter - http://twitter.com/razunahq
Support Platform - http://help.razuna.com

**Comment by thenitai** [comment]
Not sure if you received my last comment on here!?! Do I need to change to sendgrid transporter in order to make category work? I mean it should be about the same, as I simply include headers...

**Comment by andris9** [comment]
You need to do something like this:

```
mailoptions.headers = {
    "X-SMTPAPI": JSON.stringify({
        category: "product_plugin"
    })
}
```

**Comment by thenitai** [comment]
Whoa... awesome. Thank you.
