### ISSUE TITLE
How to attach pdf from url

### ISSUE THREAD

**Issue by besla** [nodemailer/nodemailer#601]
Include the following information with your issue:

1) Nodemailer version v2.3.2
2) Node.js version v4.4.2
3) OS Windows 8.1
4) So, I received mail but with corrupted pdf file.
Bellow you can see my scriptcode but you should to change SMTP attributes. PDF example file is internet public document so you can use it.

CODE

```javascript
var nodemailer = require('nodemailer');
// create reusable transporter object using the default SMTP transport
var transporter = nodemailer.createTransport({
    pool: true,
    host: 'mail.test.hr',
	port: 25 ,
	ignoreTLS: true,
	secure: false,
    logger: true, // log to console
    debug: true // include SMTP traffic in the logs
}, {
    // default message fields
    // sender info
    from: 'test <test@test.hr>',
    headers: {
        'X-Laziness-level': 1000 // just an example header, no need to use this
    }
});
// setup e-mail data with unicode symbols
var mailOptions = {
        from: '"test" <test@test.hr>', // sender address
    to: 'test2@test.hr', // list of receivers
    subject: 'Hello', // Subject line
    text: 'Hello world', // plaintext body
	attachments: [{
		filename:'GlasIstre.pdf', 
                contentType: 'application/pdf',
		path: 'http://files.glasistre.hr/GlasIstre.pdf'
	}]
};
// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    console.log('Message sent: ' + info.response);
});
```

**Comment by besla** [comment]
Anyone?

**Comment by andris9** [comment]
I was able to use the same code to successfully send the PDF attachment. The file is quite large though so I'd suggest you to not fetch it from an URL but store it to a file first and then send that file from a disk.

Could you store and upload the raw source of the corrupt message so it would be possible to check how the message is corrupt?

**Comment by besla** [comment]
I should to fetch PDF file to attachment just from URL and not from disk. 
Could you try run my script code and give me any idea how to fix.
Where and how I should to upload corrupted PDF file?

**Comment by besla** [comment]
True, when I first saved PDF file on disk and run changed script ( used attaching as file from disk) then I got correct pdf file. Second, my first example file was too large so I try to attach smaller file via URL methode using path:'url' but again I got corrupted pdf file.
Please can you try my source code with new extra small file http://www.axmag.com/download/pdfurl-guide.pdf

**Comment by andris9** [comment]
The corrupted file seems to be a HTML error response from a proxy server. Nodemailer does not support fetching URLs through proxies so you have to prefetch the file first if you want to send it.

**Comment by rishab-yumist** [comment]
Hello,

I tried running the same code using a PDF locally. Though the PDF appears in the email, it's corrupted (even though pdf opens on local system).

```
  attachments: 
   [ { filename: 'Random',
       contentType: 'application/pdf',
       path: 'assets/stickers/pdf/upch25-Jul-20160.pdf' } ] }
```

**Comment by vdraceil** [comment]
This happens to me too! A valid local PDF when sent as an attachment gets delivered corrupted.
I checked the contents of the file - it is no error or text.

**Comment by scipper** [comment]
This is still a problem to me. Exactly like @vdraceil described.

**Comment by gowthambl** [comment]
Hi,
I also getting same error.

**Comment by XingyuGuUCSD** [comment]
I have the same problem, any solution?

**Comment by CloudBranch** [comment]
Has anyone solved this? It is still an issue.

**Comment by josco007** [comment]
Hi I solve this in this way thanks to Ilya Khadykin 

[https://stackoverflow.com/questions/34077507/how-can-i-attach-an-image-to-an-email-from-an-url-using-nodemailer-and-request-m/34095094#34095094](https://stackoverflow.com/questions/34077507/how-can-i-attach-an-image-to-an-email-from-an-url-using-nodemailer-and-request-m/34095094#34095094)

in my case i was sending an excel file

**Comment by limweebeng** [comment]
Hi josco007,

I have use your code however I didn't put in any proxy. The output also failed due to security issue. The action is blocked by the CORS. May I now have other alternative?
