### ISSUE TITLE
Mail sending behind Firewall

### ISSUE THREAD

**Issue by jochenonline** [nodemailer/nodemailer#604]
nodemailer: V2.2
noidejs: V4.2.3
OS: Debian Jessie

When trying to send emails from behind a firewall which disallows allocation of additional ports besides the named smtp port, nodemailer fails with a timeout. When we we allow the the allocation nodemailer works fine.

Is there any possibility to prevent nodemailer from allocating other ports than the named smtp port?

**Comment by andris9** [comment]
Nodemailer should not try to open any other ports than the one that is provided with the `port` option
