### ISSUE TITLE
Is it possible to send attachment whitout file name?

### ISSUE THREAD

**Issue by ricardopolo** [nodemailer/nodemailer#605]
We take an email, parse it with mailpariser, and then send it with nodemailer.
We try to keep the email as equal as possible.

We have an email that comes with this attachment
````js
 [ { contentType: 'message/disposition-notification',
    generatedFileName: 'attachment',
    contentId: '44290cefe42924d04a92d99428a95f27@mailparser',
    checksum: 'a90c167164de2a9e64ffa6edc774fd72',
    length: 199,
    content: <Buffer 46 69 6e 61 6c 2d 72 65 63 69 70 69 65 6e 74 3a 20 52 46 43 38 32 32 3b 20 72 69 63 61 72 64 6f 2e 70 6f 6c 6f 40 74 75 6c 70 65 70 2e 63 6f 6d 0d 0a ... > } ]
````

This a message read confirmation.
It looks like an attachment but I can see it does not have `fileName`.

When I send that attachment using nodemailer and dont send a filename, as it comes, it generates a file name like `attachment-1.bin` which generates unfortunate behaviors like some servers rejecting the email becasue the `bin` extension. 
So, any advice about how can we send an email like this, whituout generating this new filename?

Thanks in advance!

**Comment by ricardopolo** [comment]
By the way, this is the stream of the type of the message that I am talking about https://gist.githubusercontent.com/ricardopolo/3f530d5b15cbd0b1c7b07f3be9071a5f/raw/38e509ce0aec381e07117df2352fb824f442574e/Content%2520disposition%2520stream

**Comment by ricardopolo** [comment]
I also can confirm that if you not pass filename you  modifiy the content-type to add the filename `attachment-1.bin` and adds a content-disposition. This behavior is not the desired in the case of disposition notification

````js
Content-Type: message/disposition-notification; name="attachment-1.bin"
Content-Disposition: attachment; filename="attachment-1.bin"
`````

**Comment by ricardopolo** [comment]
@andris9 i found this commit in mailcomposer
https://github.com/nodemailer/mailcomposer/commit/abe1310f4fd99f1bc5099bd9643ca44f16f68698

This may be the solution?
How can I test that version of mailcomposer inside nodemailer?

**Comment by andris9** [comment]
Have you tried upgrading Nodemailer? The referenced mailcomposer code is already included in Nodemailer

**Comment by ricardopolo** [comment]
@andris9 i Can confirm with latest version of the code that the issue persist, when you dont send a file name nodemailer creates a `.bin` filename.

I used this code for replicating the issue. `foo.txt` is the stream I uploaded before

````js
var MailParser = require("mailparser").MailParser;
var nodemailer = require('nodemailer');
var mailparser = new MailParser();
var fs = require('fs');
var transporter = nodemailer.createTransport('smtps://rapoloj%40gmail.com:password@smtp.gmail.com');


function get_attachments_array(attachments) {
  var result = [];
  if(attachments){
    attachments.map(function(attachment){
      var new_attachment = {
        filename: attachment.fileName,
        content: attachment.content,
        contentType: attachment.contentType,
        contentDisposition: attachment.contentDisposition,
        encoding: attachment.transferEncoding
      };
      result.push(new_attachment);
    });
  }
  return result;
}

mailparser.on("end", function(mail){
  console.log("From Mailparser");
  console.log(mail.attachments);
  var attach2 = get_attachments_array(mail.attachments);
  console.log("To NodeMailer");
  console.log(attach2);

  var mailOptions = {
      from: 'rapoloj@gmail.com', // sender address
      to: 'ricardo@tulpep.com', // list of receivers
      subject: 'Hello ✔', // Subject line
      text: 'Hello world 🐴', // plaintext body
      html: '<b>Hello world 🐴</b>', // html body
      attachments: attach2
  };

transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    console.log('Message sent: ' + info.response);
});

});

var text = fs.readFileSync('foo.txt', 'utf8');
mailparser.write(text);
mailparser.end();
````

**Comment by ricardopolo** [comment]
@andris9 any comment about this?

Thanks

**Comment by andris9** [comment]
You can try the beta version on Nodemailer:

    npm install nodemailer@beta

and then set `false` as the attachment filename

**Comment by ricardopolo** [comment]
I get it, but... whats the point to have to specify `false` in the filename. If not filename was provided, it dev probably dont want a filename :)

Regards and thanks! :)
