### ISSUE TITLE
Examples of implementing captcha test questions

### ISSUE THREAD

**Issue by DJviolin** [nodemailer/nodemailer#607]
Can you share an example how to implement captcha test questions? Sending the message should be halted when the captcha question didn't met. For example:

```html
<form action="" method="post">
  How much is 2 * 2, with letters?<br />
  <input type="text" name="captcha"><br />
  <input type="submit" value="Submit">
</form> 
```

```javascript
router.post('/', (req, res) => {
  ...
  transporter.sendMail(mailOptions, (err, info) => {
    if(req.body.captcha === 'four') {
      // Only send the message if 'req.body.captcha' is true
      console.log('Message sent successfully!');
      console.log('Server responded with "%s"', info.response);
    } else {
      console.log('Error occurred');
      console.log(err.message);
    }
  });
});
```

Is there a way to achieve this?

**Comment by andris9** [comment]
I'd suggest looking into existing captcha solutions available from [npm](https://www.npmjs.com/search?q=captcha). It's kind of out of scope for Nodemailer and I don't know much about captcas.

**Comment by DJviolin** [comment]
So there's no way to rejecting message sending in an `if else` statement in `transporter.sendMail`? You can log `error`. What I want is to only send the mail when `if` statement is met. This is not the question about captchas, it is a question about nodemailer's API, which I found undocumented. This code can be far more useful dozen of other staff than captchas, to only sending the mail when the trigger code is presented, like inside an `if else`.

**Comment by andris9** [comment]
You have to check the captcha before you call sendMail. There is no way to abort already running email transaction in Nodemailer

**Comment by DJviolin** [comment]
Thank You the idea. This is works:

```javascript
if(req.body.captcha === 'négy' ||
   req.body.captcha === 'negy' ||
   req.body.captcha === 'Négy' ||
   req.body.captcha === 'Negy' ||
   req.body.captcha === 'NÉGY' ||
   req.body.captcha === 'NEGY' ||
   req.body.captcha === 'four' ||
   req.body.captcha === 'Four' ||
   req.body.captcha === 'FOUR') {
  // send mail with defined transport object
  transporter.sendMail(mailOptions, (err, info) => {
    if(err) {
      console.log('Error occurred');
      console.log(err.message);
    }
    console.log('Message sent successfully!');
    console.log('Server responded with "%s"', info.response);
  });
};
```
