### ISSUE TITLE
emoji plugin transform compiler

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#618]
Could you make a package called `nodemailer-gemoji-to-emoji`?

That way we could write `:smile:` in our emails and it'd convert to :smile: automatically.

e.g. https://github.com/andris9/nodemailer-html-to-text

using https://github.com/wooorm/gemoji

Thanks!

**Comment by andris9** [comment]
Sorry for the long delay. I like the idea but I don't have time for this for now, sorry

**Comment by niftylettuce** [comment]
Please don't close this, I'll do it
