### ISSUE TITLE
Callback not being called

### ISSUE THREAD

**Issue by KieronWiltshire** [nodemailer/nodemailer#622]
Node: v4.3.1
NodeMailer: 2.4.1
Operating system: windows 10

I'm using NodeMailer to send an email to the specified address. I'm using the sendMail function, and I'm not getting the callback so I can never determine the error being thrown, if one is even being thrown. 

The callback is not being called here:
https://gist.github.com/KieronWiltshire/a86ad6e9ba7c084f80eb855604d92e39#file-callbacknotbeingcalled-js-L42

The options are being loaded, here are the options:
https://gist.github.com/KieronWiltshire/3f7fd75b31c689a84f6370efe06551c9

Here is the log to console:
https://gist.github.com/KieronWiltshire/fea16bd097098b6f3a11019d67c237c6

**Comment by ErinsMatthew** [comment]
Just FYI. I'm facing the same issue, and had to go back to 2.3.1 to get around it.

    npm install nodemailer@2.3.1

**Comment by KieronWiltshire** [comment]
@ErinsMatthew backdating doesn't even work for me..

**Comment by KieronWiltshire** [comment]
@ErinsMatthew Okay the issue is the fact it's wrapped within a Promise. If I take the promise out, it works perfectly fine.
