### ISSUE TITLE
nodemailer >=v2.3.2 does not install when using sinopia as the npm registry/proxy in a closed dev environment

### ISSUE THREAD

**Issue by reedog117** [nodemailer/nodemailer#623]
Versions 2.3.2 and greater of nodemailer do not install correctly when using sinopia for the npm registry in a closed development environment. Tried on both Fedora 22 and CentOS 7 in environments with no direct internet access (but the sinopia server has access to the NPM registry and acts as a passthrough).

About 15 dependencies fail to install with errors that it cannot get to registry.npmjs.org to download the package.  A colleague is thinking that npm-shrinkwrap.json is to blame, although we aren't too familiar with that package to come up with a fix.

**Comment by andris9** [comment]
The shrinkwrap file caused more harm that helped so I removed it in v2.4.2. Could you check if you can install the latest version?

**Comment by reedog117** [comment]
Looks like v2.4.2 fixed my problem. Thanks!
