### ISSUE TITLE
sendMail not being called within function

### ISSUE THREAD

**Issue by KieronWiltshire** [nodemailer/nodemailer#624]
In ref to #622 

Calling transport#sendMail within a Promise, just doesn't work at all.

**Comment by andris9** [comment]
I removed unrelated parts and ended up with this script: https://gist.github.com/andris9/9b85c04450363ada79dd11b57debb3af

I tried it with different versions of node and it worked fine. Can you check if you can also run the stripped down version of the sending script and what is different between your version and mine

**Comment by KieronWiltshire** [comment]
It's possibly just an issue with my code, but I don't see how.
I've made my repository public for a while if you wish to clone it and attempt to diagnose the problem.

1. Here I'm listening for an event, which calls the next function.
https://github.com/KieronWiltshire/dracade-backend/blob/develop/api/listeners/user.js#L13

2. Here I'm calling the mailer (which in-fact, does work)
https://github.com/KieronWiltshire/dracade-backend/blob/develop/api/user.js#L148

3. If I place a `console.log(options);` here, then it will display the options as intended.
https://github.com/KieronWiltshire/dracade-backend/blob/develop/mailer.js#L44

4. The issue is, sendMail will never return an error/response.

I have no clue why that is happening.

**Comment by KieronWiltshire** [comment]
@andris9 Okay after some careful debugging, logging the sendMail seems to show that the promise is "pending"

**Comment by KieronWiltshire** [comment]
Okay, so I think this is actually something on my part :/
https://github.com/KieronWiltshire/dracade-backend/blob/develop/api/user.js#L119

By removing that line, the email is sent. I think for some weird reason though, by sending the HTTP response, it's cancelling the email stuff.

**Comment by KieronWiltshire** [comment]
Okay, it was an issue with mocha haha, my apologies. Mocha was moving onto the next test case before the event listener could finish processing.
