### ISSUE TITLE
is not working for me 

### ISSUE THREAD

**Issue by arezki1990** [nodemailer/nodemailer#626]
Include the following information with your issue:
{ [Error: getaddrinfo ENOTFOUND a_lebdiri a_lebdiri:465]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'a_lebdiri',
  host: 'a_lebdiri',
  port: 465 }

1) Nodemailer version you are having problems with (eg. v2.4.2)
2) Node.js version you are using (run `node -v` to see it, eg v5.5.0)
3) Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
4) If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)

If you are having problems with Gmail, then make sure you have
read this post before filing your issue: http://nodemailer.com/using-gmail/

**Comment by andris9** [comment]
I hope you already got that fixed. Anyway, it seems that you are using a suspicious hostname "a_lebdiri" which probably is not a correct one.
