### ISSUE TITLE
Dont fail when wrong url in attachment

### ISSUE THREAD

**Issue by ricardopolo** [nodemailer/nodemailer#627]
Hi.
We have a setup where we take an email, parse it using mailparser, modify the body, and resend it using nodemailer.

We want  to put as attachment (inline with CID) all images in the body.
So we parse the HTML, read the SRC of imgs, and add the url as the path in the attachment. 

It works ok.
But.... if the url of one src is not assesible the whole email fails.
Are there any way we can allow a fail path, simply dont download that file, dont include that attachment, but continue sending the email? Right now, if one path fails, the whole mail fails.

Thanks :)

**Comment by ricardopolo** [comment]
@andris9 any comment about this please?

**Comment by andris9** [comment]
Actually, this used to be the default behavior in the older versions of Nodemailer. If a file or url failed, then the attachment got an error message as its content but the message itself was still sent. Sending out invalid attachments is generally a bad thing, so this behavior was changed.

The most common use case for Nodemailer is to use trusted input (eg. you know what the contents are and that the contents exist) and if something fails with it then the entire message can be considered as failed. You do not want to send out an invoice pdf that the client is unable to open.

Your use case is different, you try to use untrusted input and that does not match well with the current failure strategy. You should probably not use urls but download these first to see if the data exists or not.

**Comment by ricardopolo** [comment]
@andris9 what do you think about offering a parameter for this behavior?
Would you accept a PR?

**Comment by andris9** [comment]
It would probably be quite difficult to change, errors can happen in a lot of different places and right now whenever an error occurs, it breaks the message generating stream.

The url download is initiated [here](https://github.com/nodemailer/buildmail/blob/master/lib/buildmail.js#L869) if you want to see how it works.
