### ISSUE TITLE
Using nodemailer with .edu address rather than gmail

### ISSUE THREAD

**Issue by sjkelleyjr** [nodemailer/nodemailer#628]
I'm trying to set up a transporter object for a .edu email address, and can't seem to find any documentation as to how to go about doing this.  I've tried the following test case, as well as abtracting out to objects as in previous versions of nodemailer with no success.  I can send email using a @gmail address though with no issues using the same format of function call as the test case supplied.

1) nodemailer version: v2.3.0
2) node version: v0.10.25
3) Ubuntu 14.04
4) test case: var transporter = nodemailer.createTransport('smtp://user.name%40sdl.usu.edu:PASS@smtp.sdl.usu.edu');

Thanks!

**Comment by andris9** [comment]
You need to find out the correct connection details. For example smtp.sdl.usu.edu does not seem to be a valid hostname, at least there is no DNS record for it (or maybe it is an intranet address only available from a specific network?). Anyway you can find all possible configuration options to set up the connection from the docs [here](https://github.com/nodemailer/nodemailer#set-up-smtp)
