### ISSUE TITLE
Character issue

### ISSUE THREAD

**Issue by efkan** [nodemailer/nodemailer#629]
```
Nodemailer : v2.4.2
Nodemailer-ses-transport: v1.3.1
Node.js: v5.3.0
OS: Windows 10
Client OS: Android 4.3 in English
```

Hello,

I've been using `nodemailer` and `nodemailer-ses-transport` to send email via `AWS-SES`.

If I'm not wrong the following expected text should be shown properly. However I get the result text on sender area.

The sender address I use is `"arı <ari@testing.com>"`. I've also tried out `'"arı" <ari@testing.com>'` and `{ name: 'arı', address: 'ari@testing.com' }`.

![unknown](https://cloud.githubusercontent.com/assets/6974198/16083932/7d3d68a2-331f-11e6-8b22-bc2c0dc57377.png)

I used built-in browser of Android when testing. Then I tried in yahoo mail app considering the browser encoding problem but unfortunately. I couldn't be succeed.

Is there any chance to overcome this issue?

**Comment by andris9** [comment]
Are you sure that your code editor is using UTF-8 for your js source code and not UTF-16 or something else?

**Comment by andris9** [comment]
Let me know if you still have this issue and that your code files are utf-8

**Comment by efkan** [comment]
Hi @andris9 ,

Sorry for late response. I use Atom Editor and the all code in UTF-8.
