### ISSUE TITLE
[Error: Unsupported configuration, downgrade Nodemailer to v0.7.1 to use it]

### ISSUE THREAD

**Issue by gcfabri** [nodemailer/nodemailer#631]
I am working on an angular HotTowell project + nodemailer.

- Downgrade to 0.7.1 and is still throwing the same error;
- Use of nodemailer-smtp-transport did not work;

1) Nodemailer v2.4.2
2) Node.js v5.11.1
3) elementary OS 0.3.2 Freya (64-bit) built on Ubuntu 14.04
4) [gist](https://gist.github.com/gcfabri/6ef8a6c2a5c845f9edbc8a457c2b6025)
5) [stackoverflow](http://stackoverflow.com/questions/37860116/nodemailer-error-error-unsupported-configuration-downgrade-nodemailer-to-v0)

**Comment by isiban** [comment]
Hi @gcfabri,

I was on the same issue in the sendMail callback with Nodemailer v2.4.2 until the downgrade to v0.7.1. 
It's working right now.
Unfortunately Your gist and stackoverflow links are going on 404 pages...

Conf:
- Nodemailer v0.7.1
- Node.js v5.6.0
- OSX 10.11.5

**Comment by gcfabri** [comment]
Links updated. I tried to downgrade to 0.7.1 and the same error was shown.

**Comment by gauravgupta90** [comment]
Hey @gcfabri have to tried to remove node_modules folder and then do fresh npm install after downgrading to 0.7.1 It will work

Cheers!!

**Comment by gcfabri** [comment]
Hello, thanks for your attention. I did not figure out the error. I reviewed my project and made some changes on [gist](https://gist.github.com/gcfabri/6ef8a6c2a5c845f9edbc8a457c2b6025). Now nodemailer is working fine with angular and express.

**Comment by OmprakashAmarwal** [comment]
@gcfabri Thanks it works!!! 👍
