### ISSUE TITLE
Unsupported configuration using Mailgun, no response from verify

### ISSUE THREAD

**Issue by cfjedimaster** [nodemailer/nodemailer#633]
I'm using Nodemailer 2.4.2, Node 5.11.0 and OSX.

I'm trying to use Nodemailer with Mailgun. I've set up my transport like so:

	var mailTransport = nodemailer.createTransport('smtp', { service: 'mailgun',
		auth: {
			username: credentials.mailgun.username,
			password: credentials.mailgun.password
		} 
	});

I tried to email like so:

	var message = {	
		from: 'postmaster@raymondcamden.mailgun.org',
		to: '"Raymond Camden" <raymondcamden@gmail.com>',
		subject: 'Daily Reddit Email', 
		html: html
	};	

	mailTransport.sendMail(message, function(error){
		if(error){
			console.log('Error occured');
			console.log(error.message);
			return;
		}
	console.log('Message sent successfully!');

	});

When run, I get: Unsupported configuration, downgrade Nodemailer to v0.7.1 to use it

Question is - what exactly is unsupported? Also - I tried running verify:

	mailTransport.verify(function(error, success) {
		if (error) {
				console.log(error);
		} else {
				console.log('Server is ready to take our messages');
		}
	});

and nothing is returned. No error, no success.

**Comment by ultrazgq** [comment]
I use this setting:
var transporter = nodemailer.createTransport(smtpTransport({
	host: 'smtp.XX.com'
	, port: 25
	, auth: {
		user: '**@email.com'
		, pass: '*****'
	}
	, tls: {rejectUnauthorized: false}, debug:true
}));

**Comment by cfjedimaster** [comment]
Is this syntax documented?

**Comment by ultrazgq** [comment]
like this
nodemailer/examples/rabbit-queue/sender.js
var smtpHost = {
    host: 'localhost',
    port: 2525,
    // NB! Must be pooled connection, otherwise 'idle' is never fired and nothing gets sent
    pool: true,
    auth: {
        user: 'testuser',
        pass: 'testpass'
    },
    tls:{
        // testserver uses self signed certificate, so we need to lax a bit
        rejectUnauthorized: false
    },
    logger: false
};

// array of prefetched messages waiting for delivery
var waiting = [];

// Create a SMTP transporter object
var transporter = nodemailer.createTransport(smtpHost, {
    // default message fields
    from: 'Sender Name <sender@example.com>'
});

**Comment by andris9** [comment]
Remove the first 'smtp' argument, this is extranous

**Comment by cfjedimaster** [comment]
Ok, this works in terms of removing that error, however I still can't use mailgun w/ Nodemailer. If I use mailgun-js, I can connect and send email, so I know my credentials are right. I tried passing in:
```
var mailTransport = nodemailer.createTransport({ service: 'mailgun',
    auth: {
        username: credentials.mailgun.username,
        password: credentials.mailgun.password,
		apiKey:credentials.mailgun.apikey,
		domain:credentials.mailgun.domain
    } 
});
```

and it didn't help. (Just so it is clear, the credentials are definitely right.)

**Comment by andris9** [comment]
Use 'user' and 'pass' instead of 'username' and 'password' (the values for these must be SMTP credentials and not your account credentials). apiKey and domain are not used, you can drop these

**Comment by cfjedimaster** [comment]
Thanks.
