### ISSUE TITLE
nodemailer presenting attachments as alternatives?

### ISSUE THREAD

**Issue by psifertex** [nodemailer/nodemailer#642]
Include the following information with your issue:

1) Nodemailer version you are having problems with (2.4.2 2016-05-25)
2) Node.js version you are using (v6.1.0)
3) Your operating system (OS X 10.10)

I'm troubleshooting some attachments being hidden by mail.app compared to gmail when receiving HTML emails with attachments generated by nodemailer. Specifically, the attachments show up as if they were all attachments used in an HTML email and not below the bottom of the email the way most attachments of the contentType attachment do. I've tried manually specifying HTML in the alternatives section to force /only/ the HTML being included in the alternatives mime type, but that doesn't appear to take effect. 

Short summary: I have some images that are supposed to be referenced from the HTML email as cid: urls (which works great) and now show up as attachments in the default attachment download area. But the testfile /should/ show up. This is exactly how gmail parses the email, but I can't seem to generate it in a way that Mail.App will properly parse the email. In mail.app I have to click the very small paperclip icon at the top which is a huge usability problem. 

Sample code:
```
	var mailOptions	= {
		from: fromAddr,
		to: toAddress,
		subject: subject,
		text: body,
		text: body,
		alternatives: [
			{
				contentType: 'text/html',
				content: html,
			}
		],
		attachments: [
			{ filename: "test.dat",
				content: JSON.stringify(testfile, null, 2),
				contentType: "application/octet-stream",
				contentDisposition: "attachment"
			},
			{ filename: 'htmlimage.png',
				path: './htmlimage.png',
				cid: 'htmlimage.png',
				contentDisposition: "inline"
			}
```

Here's a snippet of what the raw message looks like on the other side:

```
Content-Type: multipart/mixed;
 boundary="----sinikael-?=_1-14697755017950.06955543075972681"
From: me
To: to
Subject: subject

------sinikael-?=_1-14697755017950.06955543075972681
Content-Type: multipart/alternative;
 boundary="----sinikael-?=_2-14697755017950.06955543075972681"

------sinikael-?=_2-14697755017950.06955543075972681
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable

content
------sinikael-?=_2-14697755017950.06955543075972681
Content-Type: multipart/related; type="text/html";
 boundary="----sinikael-?=_4-14697755017950.06955543075972681"

------sinikael-?=_4-14697755017950.06955543075972681
Content-Type: text/html
Content-Transfer-Encoding: quoted-printable

<HTML>HTML EMAIL</HTML>
------sinikael-?=_4-14697755017950.06955543075972681
Content-Type: image/png; name=htmlimage.png
Content-ID: <htmlimage.png>
Content-Disposition: inline; filename=htmlimage.png
Content-Transfer-Encoding: base64

<SNIP>
------sinikael-?=_4-14697755017950.06955543075972681--

------sinikael-?=_2-14697755017950.06955543075972681--

------sinikael-?=_1-14697755017950.06955543075972681
Content-Type: application/octet-stream; name=testfile
Content-Disposition: attachment; filename=testfile
Content-Transfer-Encoding: base64

<SNIP>
-----sinikael-?=_1-14697755017950.06955543075972681--
```

**Comment by psifertex** [comment]
I think I've got a but more info, looks like I might be running into this bug: 

https://github.com/rails/rails/issues/2686

**Comment by andris9** [comment]
Could you provide a screenshot as well of what happens and what you would expect? When I try this, then the attachment icon appears at the end of the email as expected.

**Comment by psifertex** [comment]
Thanks for the response -- I found the problem was the HTML itself. When I simplified the HTML email that was being sent it successfully showed the attachment, sorry for thinking the problem was with nodemailer!
