### ISSUE TITLE
peer requirements not met

### ISSUE THREAD

**Issue by switheyw** [nodemailer/nodemailer#643]
nodemailer "version": "2.5.0",
Meteor 1.3.1
node --version v0.11.13
OS X 10.11.6

npm ERR! peerinvalid The package eslint@3.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@9.0.1 wants eslint@^2.9.0
npm ERR! peerinvalid Peer eslint-plugin-import@1.10.3 wants eslint@2.x - 3.x
npm ERR! peerinvalid Peer eslint-plugin-jsx-a11y@2.0.1 wants eslint@^2.10.2 || 3.x
npm ERR! peerinvalid Peer eslint-plugin-meteor@3.6.0 wants eslint@>=0.8.0

[npm-debug.txt](https://github.com/nodemailer/nodemailer/files/392537/npm-debug.txt)

Include the following information with your issue:

1) Nodemailer version you are having problems with (eg. v1.3.7)
2) Node.js version you are using (run `node -v` to see it, eg v5.5.0)
3) Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
4) If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)

If you are having problems with Gmail, then make sure you have
read this post before filing your issue: http://nodemailer.com/using-gmail/

**Comment by andris9** [comment]
Use `npm install --production` to skip installing development dependencies like eslint. This is not related to nodemailer but how different packages that you have installed depend on eslint.
