### ISSUE TITLE
 Error: Unsupported configuration, downgrade Nodemailer to v0.7.1 to use it

### ISSUE THREAD

**Issue by gisonyeung** [nodemailer/nodemailer#644]
1) Nodemailer v2.5.0
2) Node.js v4.4.7
3) Windows 10
4) var mailTransport = nodemailer.createTransport('SMTP', {
	host: 'xx',
	auth: {
		user: 'xx',
		pass: 'xx'
	}
});

how should I configure the transport by the object?

If I configure by the way ' smtps://xx%40xx.com:xx@smtp.xx.com', it will success.

**Comment by andris9** [comment]
Drop the 'SMTP' option
