### ISSUE TITLE
Context Value in external template 

### ISSUE THREAD

**Issue by robinpoulose1** [nodemailer/nodemailer#648]
How can i include or get the values of context i.e user name and password on my external templates . 
It works fine for internal buildin

{
    username: 'Node Mailer',
    password: '!"\'<>&some-thing'
}

Include the following information with your issue:

1) Nodemailer version you are having problems with (eg. v1.3.7)
2) Node.js version you are using (run `node -v` to see it, eg v5.5.0)
3) Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
4) If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)

If you are having problems with Gmail, then make sure you have
read this post before filing your issue: http://nodemailer.com/using-gmail/

**Comment by andris9** [comment]
I don't really get it, could you explain a little bit more what you are expecting

**Comment by dennify** [comment]
I have the same Problem in my external template I have `{{some_key}}` in my html and my txt, but it would not replaced.

The code:
`html.html:`
```
Bla blub <strong>{{some_key}}</strong>
```

`text.txt:`
```
Bla blub **{{some_key}}**
```

Mail function:
```
transporter.templateSender(new template('templates/some_template'), {
  from: '"THE SENDER" <sender@example.org>',
})({
  to: 'reciever@example.org',
  subject: 'Some subject'
}, {
  some_key: 'some_value'
}, function(error, info) {
  if(error) {
    return console.log(error);
  }
  console.log('Message sent: ' + info.response);
});
```

The output is:
```
Bla blub <strong>{{some_key}}</strong>
```
not

```
Bla blub <strong>some_value</strong>
```

**Comment by dennify** [comment]
After look through a lot of lines of code from different dependencies I found my solution.
html and text needs ejs as file extension. And you must replace the `{{` and `}}` with the `<%=` and `%>`. and you must install `ejs` with npm. Then the following code works:
```
new template('templates/some_template').render({
  some_key: 'some_value'
}, function (error, results) {
  if(error) {
    return console.log(error);
  }

  transporter.sendMail({
    from: '"THE SENDER" <sender@example.org>',
    to: 'reciever@example.org',
    subject: 'Some subject',
    html: results.html,
    text: results.text
  }, function(error, info) {
    if(error) {
      return console.log(error);
    }
    console.log('Message sent: ' + info.response);
  });
});
```

`text.ejs`:
```
Bla blub **<%=some_key%>**
```

output:
```
Bla blub **some_value**
```
