### ISSUE TITLE
Remove transports

### ISSUE THREAD

**Issue by marcbachmann** [nodemailer/nodemailer#651]
I'd like to bring down the dependency tree of our application.
What do you think about removing all the transports of this module?

nodemailer-direct-transport
nodemailer-smtp-pool
nodemailer-smtp-transport

**Comment by andris9** [comment]
SMTP support is a core part of Nodemailer. I might incorporate the code from these deps directly into Nodemailer some day but currently it is going to stay as it is

**Comment by marcbachmann** [comment]
I assumed they are rarely used as most people are using either ses, sendgrid, mailgun or mandrill.

**Comment by andris9** [comment]
No, SMTP is still the king and you can also use all these listed services using SMTP. Besides the non-SMTP modules usually do not support the full range of Nodemailer options since the underlying API calls are somewhat limited or too specific.
