### ISSUE TITLE
Cannot log in with Gmail account

### ISSUE THREAD

**Issue by ruddfawcett** [nodemailer/nodemailer#653]
### Issue

I'm sure this is a common problem, but I have played around with a gmail account for almost an hour with no luck:

- Without 2FA, allowed less secure apps, reloaded the captcha.
- Then turned on 2FA, created an app specific password, reloaded the captcha.
- Revoked app specific password, reloaded captcha.

And a few more variations. I was wondering if you had any more suggestions for Gmail users?

### Error
> { Error: Invalid login: 534-5.7.9 Please log in with your web browser and then try again...

1. Nodemailer version: 2.5.0
2. Node.js version: v6.2.2
3. Operation system: OS X

### Reproduction:

```js
var nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport('smtps://user%40gmail.com:pass@smtp.gmail.com');

var mailOptions = {
    from: '"First Last" <first.last@gmail.com>',
    to: 'test@test.com', // changed in mine
    subject: 'Subject',
    text: 'Hello world',
    html: '<b>Hello world</b>'
};

transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    console.log('Message sent: ' + info.response);
});
```

**Comment by andris9** [comment]
It seems you have tried almost everything. You might try to use OAuth2 login as well but it would probably be much easier to just change providers than mess with the OAuth keys and tokens.

**Comment by ruddfawcett** [comment]
@andris9 thanks, sounds good. What have you found works best with your lib?

**Comment by andris9** [comment]
SendGrid, Sparkpost, Mailgun etc all work fine and all these have free tier available so it doesn't even cost anything if your sending volume is low
