### ISSUE TITLE
Clarify documentation for envelope use

### ISSUE THREAD

**Issue by pizzurro** [nodemailer/nodemailer#655]
Nodemailer version: v2.5.0
NodeMailer Smtp Transport v2.6.0
Node.js v4.2.2
Windows 10

When using the smpt transport and configuring a message with an envelope, 'cc' and 'bcc' will be ignored unless they are included in the 'to' property of the envelope.  Simply repeated the 'cc' and 'bcc' in the envelope has no effect though the documentation appears to indicate that this does work. In fact, those fields are ignored by the buildmail module when the envelope is built.  

**This will not work:**
```javascript
var message = {
  from: 'noreply@a.com',
  to: 'person1@a.com',
  cc: 'person2@a.com',
  bcc: 'person3@a.com',
  subject: 'My Subject',
  html: 'My Message',
  envelope: {
    from: 'bouncehere@a.com',
    to: 'person1@a.com',
    cc: 'person2@a.com',
    bcc: 'person3@a.com'
  }
}
```
**This, however, succeeds**
```javascript
var message = {
  from: 'noreply@a.com',
  to: 'person1@a.com',
  cc: 'person2@a.com',
  bcc: 'person3@a.com',
  subject: 'My Subject',
  html: 'My Message',
  envelope: {
    from: 'bouncehere@a.com',
    to: ['person1@a.com', 'person2@a.com', 'person3@a.com']
  }
}
```

**Comment by andris9** [comment]
Fixed in v2.6.0. This was a bug in the code, the documentation was correct
