### ISSUE TITLE
Problem when send masive mails [Error: Connection timeout] code: 'ETIMEDOUT', command: 'CONN'

### ISSUE THREAD

**Issue by j0n4s** [nodemailer/nodemailer#656]
Include the following information with your issue:

1) Nodemailer version you are having problems with 2.5
2) Node.js version you are using v4.4.7
3) Your operating system Ubuntu 14.04

I sending many emails and have this error [Error: Connection timeout] code: 'ETIMEDOUT', command: 'CONN' , my code is for example

arrar[with 1800 elements].each(function(individual_email) {
sendmail_with_nodemailer(individual_email)
})

my problem is that sends 500 emails and then gives me this error

**Comment by andris9** [comment]
You are trying to send too many messages at once and your MTA is not able to handle these requests. Use pooled connections and wait for the ['idle'](https://github.com/nodemailer/nodemailer#eventidle) event to fire before passing the next batch of messages

**Comment by j0n4s** [comment]
Thanks, I 've already solved the problem

**Comment by Michel0305** [comment]
can you share how do you solved the problem?
