### ISSUE TITLE
Empty Attachments

### ISSUE THREAD

**Issue by lokenx** [nodemailer/nodemailer#657]
**Nodemailer:** 2.5.0
**Node:** 6.4.0
**Electron:** 1.3.5
**OS**: Mac OS X 10.11.6

I'm having issues with sending attachments--they should be CSV but plain text is also failing. A code snippet is below. The email sends successfully and a correctly named attachment, however it is 0KB. I've tried with Zoho and Gmail SMTP. The only thing different is that it's an Electron app but not sure how that impacts things.

https://gist.github.com/lokenx/c762850446b6f4cada23b3cbe64e60f1

**Comment by andris9** [comment]
Use 'content' instead of 'contents'

**Comment by lokenx** [comment]
Ah shit, that's why you drink coffee in the morning. Thanks man!
