### ISSUE TITLE
stream as content with start offset

### ISSUE THREAD

**Issue by lujan99** [nodemailer/nodemailer#658]
node 4.2.3 / nomailer 2.6 .0 / Win7

I use as content:  fs.createReadStream('test.txt' , {start:2000})
but always send all file, I want text from position 2000

function email(body)
{
var transporter = nodemailer.createTransport('smtps://...');

var mailOptions = {
    from: '...'
    to: '...'
    subject: 'Hello test', 
    text:  body 
};

transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    console.log('Message sent: ' + info.response);
});
}

email( fs.createReadStream('test.txt' , {start:2000}))

/*
Always send the entire file as content.
file size is: 2700 bytes (is a text file, a log file)
*/

**Comment by andris9** [comment]
Nodemailer doesn't do anything specific with the input stream, it pipes it to the encoder as it is and thats it. Check if your stream actually starts from 2000 or not

**Comment by lujan99** [comment]
I test with the same stream constructor and I get text after 2000 position:

```
var readable=fs.createReadStream(fn , {start:2000});
readable.on('readable', function() {
    console.log('READ: %s',readable.read())
    readable.close();
    });
```
