### ISSUE TITLE
Using Gmail, account gets suspended

### ISSUE THREAD

**Issue by nvbach91** [nodemailer/nodemailer#659]
Hi, I'm having some issue with Gmail. The account gets suspended over time and I don't know why.
For more details pls see stackoverflow
http://stackoverflow.com/questions/39334899

I'm using:
Nodemailer v2.3.2
Node.js v 6.2.2
Windows Server 2012 64-bit

Thanks for helping me

**Comment by andris9** [comment]
If you need to send more than occasional email then you should consider signing up for a dedicated SMTP relay service like SendGrid or Mailgun or SparkPost etc. Gmail expects that a real person sends email and if it detects anomalies then it starts blocking the messages and the'res not much to do in this case
