### ISSUE TITLE
Is it possible to configure nodemailer to return after RCPT TO?

### ISSUE THREAD

**Issue by jahlives** [nodemailer/nodemailer#660]
I get a little bit stuck with nodemailer :-) I want to make a script with nodemailer that returns after sending the RCPT TO and receiving the server's answer. Something similar to swaks -q option TO
I do not need to send a mail, just want to verify if the server accepts msg for given RCPT.
Is there any switch in nodemailer which could help to achive this? First I thought that [verify](https://github.com/nodemailer/nodemailer#verify-smtp-connection-configuration) might help, but this just seems to check the configuration parameters

**Comment by andris9** [comment]
There is no such method in Nodemailer and the underlying smtp-connection module also abstracts the envelope passing away. I guess that your best bet for now would be to use a single recipient address that triggers an error by the MTA and try to send something to such address. Once you get back the error response you could check which command triggered it, was it MAIL FROM or RCPT TO. In the long term it obviously isn't a great solution as some server would accept almost anything for RCPT TO
