### ISSUE TITLE
Sending html template with attachments and template data

### ISSUE THREAD

**Issue by NMandapaty** [nodemailer/nodemailer#661]
1) Nodemailer version = 2.6.0
2) Node.js version = 6.5.0
3) Mac OS X 10.11.6

Here's my code:

```
var EmailTemplate = require('email-templates').EmailTemplate;
var template = new EmailTemplate('templates/welcome');
  template.render({}, function(err, results) {
    var send = transporter.templateSender({
      from: '<ouremail@gmail.com>',
      html: results.html,
      attachments: [{
        filename: 'file1.png',
        path: 'templates/file1.png',
        cid: 'file1'
      }, {
        filename: 'file2.png',
        path: 'templates/file2.png',
        cid: 'file2'
      }]
    });

    send({
      to: String(user.emailAddress),
      subject: 'Welcome to the Our Site!'
    }, {name: user.firstName}, callback);
```

The problem I ran into is that I can only send an email with attachments OR template data, but I haven't found a way to send both. If I do it the way shown above, the `name` template variable renders, but the attachments don't show up. If I instead do

```
var send = transporter.templateSender(template, {...
```

then the attachments render, and not the template variable. 

Any help would be appreciated. 
Thanks!

**Comment by sashakirichek** [comment]
I have a problem that also connected to sending attachments. 
Try to use alternatives:[] instead of attachments:[]. 
It can have no logic. But I am still in progress of testing this stuff. 

Sorry if it doesn't help.

**Comment by YohanBT** [comment]
I also have same problem, but use of 'alternatives:[]' didn't solve it!
