### ISSUE TITLE
Array of sendMail()'s "to" works, but shows incorrectly within

### ISSUE THREAD

**Issue by dylanh724** [nodemailer/nodemailer#664]
I have an array of emails:

`var adminEmails = ["email1@gmail.com", "email2@gmail.com"];`

Both users will receive the email, yet the "to" actually says ONLY email1@gmail.com, as if BCC'd (instead of displaying both of them). Are these actually sending TWO **INDIVIDUAL** emails, or is this a bug?

---

1) Nodemailer version you are having problems with (eg. v1.3.7)
**Latest - got it today**

2) Node.js version you are using (run `node -v` to see it, eg v5.5.0)
**v6.2.2**

3) Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
**Ubuntu16**

4) If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)

```
 transporter.sendMail({
        from: '"Imperium42" <noreply@imperium42.com>',
        to: adminEmails, // []
        subject: `[MC] +1 Subscriber($(email))!`,
        text: 'Rock on, i42!',
        html: '<span style="font-weight:bold;">Rock on, i42!</span>'
    }, (err, info) => {
    .....................
```

**Comment by andris9** [comment]
Could you provide an example script that is self contained so I could verify this behavior by running the example script. I would also need the headers for such a received message.
