### ISSUE TITLE
Invalid Login

### ISSUE THREAD

**Issue by tegarkurniawan** [nodemailer/nodemailer#666]
{ [Error: Invalid login: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbtI
534-5.7.14 ZXK5mJzbAU9348YxNFohBrtKeWWaIUpYojuLP8egRxU18sj_E9GNq2dPXMNHAzYpSg5haY
534-5.7.14 RptZW9JtUNngzTV5h2n5Z_u5bOn_zhP6iNkvMJsxxjvxS8alE-AYO9WjkjdITylp0-ZUkY
534-5.7.14 ethYs-i1cum88jvnH2XVmj3e9gOas9TMbWt23bxLbRsHLbL5cymz3DDwEo_aKjaBaTbIZU
534-5.7.14 BgAvy-WOELxTPVu4P0lc94s3VhK9E> Please log in via your web browser and
534-5.7.14 then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 x66sm8290934pfb.86 - gsmtp]
  code: 'EAUTH',
  response: '534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbtI\n534-5.7.14 ZXK5mJzbAU9348YxNFohBrtKeWWaIUpYojuLP8egRxU18sj_E9GNq2dPXMNHAzYpSg5haY\n534-5.7.14 RptZW9JtUNngzTV5h2n5Z_u5bOn_zhP6iNkvMJsxxjvxS8alE-AYO9WjkjdITylp0-ZUkY\n534-5.7.14 ethYs-i1cum88jvnH2XVmj3e9gOas9TMbWt23bxLbRsHLbL5cymz3DDwEo_aKjaBaTbIZU\n534-5.7.14 BgAvy-WOELxTPVu4P0lc94s3VhK9E> Please log in via your web browser and\n534-5.7.14 then try again.\n534-5.7.14  Learn more at\n534 5.7.14  https://support.google.com/mail/answer/78754 x66sm8290934pfb.86 - gsmtp',
  responseCode: 534,
  command: 'AUTH PLAIN' }

**Comment by andris9** [comment]
See [this post](https://nodemailer.com/using-gmail/) about using Gmail. if it works then it's great, if it doesn't then you most probably should look into using some other provider like Mailgun or SparkPost or Sendgrid etc.

**Comment by protoEvangelion** [comment]
@andris9 link is down

**Comment by rpuls** [comment]
@andris9 sendgrid sucks big time..... haven't been able to ever receive one single email sent from sendgrid used in node.js. It always says "Delivered" on sendgrids dashboard, but has a status 250, which means the mail carrier has received the mail from sendgrid but is holding it back and not giving it to the recipient. Sendgrids answer to that is that it is a configuration issue on the receivers mail account. which in my case makes their service completely useless, nobody can ask of their customers to configure their email account to receive post. ALL OTHER services just deliver the mail when you sign up for a mailing list etc.
