### ISSUE TITLE
how to catch wrong email address

### ISSUE THREAD

**Issue by soonfy** [nodemailer/nodemailer#670]
nodemailer, v2.5.0
node, v6.2.0
os, ubuntu16.04

why i send email to wrong email addr, dont throw error, return success info message "250 Data Ok: queued as freedom ###envid=82863209967" ?
how to catch this wrong email addr ?

**Comment by otonii** [comment]
Try this

`transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    else {
      console.log(info.rejected) // Invalid emails will be here.
      console.log(info.rejectedErrors) // Information about them (Error code, response...)
    }
    transporter.close();
});`
