### ISSUE TITLE
Multiple pools

### ISSUE THREAD

**Issue by ricardopolo** [nodemailer/nodemailer#673]
Hi.
Are there a way to have multiple nodemailer "instances" running at the same time?
Like.... a nodemailer pool for some emails and another for other emails etc.

We want a group of emails having a pool and another having another pool, two different  pool and doing EHLO separately. But both pools will connect to the same server.

Thanks :)

**Comment by andris9** [comment]
Every 'createTransport' call gives you a new pool.
