### ISSUE TITLE
mails are not received by google or yahoo acounts

### ISSUE THREAD

**Issue by bojannyc** [nodemailer/nodemailer#677]
hello,

nodemailer works fine when I sent emails to accounts other than google or yahoo. However, email sent to google or yahoo accounts has not being received. nodmailer does not return any error. I am using bluehost as smtp, node v. 4.6.0. and nodemailer 2.6.4 on windows 10. Below is the code.

`var smtpConfig = {
   host: 'boxxxx.bluehost.com',
   port: 465,
   secure: true, // use SSL
   auth: {
       user: 'xxx@xxxx.com',
       pass: 'xxxxx'
        },
   tls: {
      rejectUnauthorized: false
    }
    };
    // create reusable transporter object using the default SMTP transport
    var transporter = nodemailer.createTransport(smtpTransport(smtpConfig));

```
// setup e-mail data with unicode symbols
var mailOptions = {
    from: '"GlobalDataStore" <xxxx@globaldatastore.com>', // sender address
    to: 'xxxx@yahoo.com,xxxx@globaldatastore.com', // list of receivers
    subject: 'Product Info', // Subject line
    text: 'Hello world ?', // plaintext body
    html: '<b>Hello world ?</b>' // html body
};

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log('greska:' + error)
        return next(error);
    } else {
     console.log('Message sent: ' + info.response);
     res.json(info.response);
    }
});`
```

**Comment by soonfy** [comment]
I've seen this behavior before. 
you send email successfully, but the email is rejected by the email address, the nodemailer dont catch the error.
you send some times, maybe the nodemailer can catch the error.

**Comment by MikeLighthouse** [comment]
We had this same issue with sending emails to gmail inboxes, they'd work when sending to other providers but gmail was returning a "relay access denied" error. This started happening after we updated from 0.7.1 to 2.6.4 (a pretty big jump, this was an inherited system that previously hardcoded a lot of pretty out of date version numbers). For now we've reverted it, reverted the api changes that we had to make to get 2.6.4 working in the first place like the below and for now it appears to be working.

        var transporter = nodemailer.createTransport(transport(exports.feedbackOptions));

to

        var transporter = nodemailer.createTransport("SMTP", exports.feedbackOptions);

Be interested to see if there's a fix or a workaround

**Comment by rawiki** [comment]
I'm having the same issue, again using Bluehost as SMTP. Nodemailer messages will fail to be delivered to Gmail and certain other domains. Using Nodemailer 2.6.0 and Nodemailer-smtp-transport 2.7.2

**Comment by andris9** [comment]
Deliverability issues are usually caused by bad/untrusted IP addresses or address ranges that might have a history of sending spam. Nodemailer can't do anything about it. You should consider changing your SMTP provider

**Comment by rawiki** [comment]
Yea but smtp mail sent via an email client works fine which means it must be a Nodemailer issue.

**Comment by MikeLighthouse** [comment]
Sending via older versions of Nodemailer also works perfectly consistently for us which makes me pretty sure that it isn't exclusively our end

**Comment by andris9** [comment]
What kind of configuration do you use for sending? Upgrading from 0.7 to 1+ changed a lot of option names etc.

**Comment by ChiweenieDijon** [comment]
FYI In case it helps anyone:
I'm using v1.11.0 of nodemailer, and was experiencing the problem described in this issue.  I'm using an SMTP server set up with "Mail in a box" (https://mailinabox.email/), and was finding messages I was sending via Thunderbird were making it thru to a gmail account, but ones sent via nodemailer were disappearing.  (however, they were making it to my address hosted on namecheap's email servers)

Silly me: my I wasn't including a "from" in the options I passed to transporter.sendMail().  Once I added that, the messages were making it thru to the gmail account too.

Lesson: Gmail doesn't like messages that don't have a sender!!!

**Comment by aissaghouti** [comment]
We had the same problem using v2.7.2.
We solved the problem by adding the "name" option to smtpTransport:
```
var transporter = nodemailer.createTransport(smtpTransport({
    name: serverName,
    host: host,
    port: port,
    secure: true,
    auth: {
        user: user,
        pass: pass
    }
}));
```

**Comment by HassanAzzam** [comment]
I did like @aissaghouti said and got an info with code 250 and OK status, but the email hasn't been received by Gmail.

**Comment by hedi-lahouar** [comment]
same problem , any solution ?

**Comment by Shiigehiro** [comment]
Same problem here too.
Working when sending to 2 different Gmail address, but don't work if i send it to only 1 email

**Comment by cometofsky** [comment]
@aissaghouti for that name field?! And I was being crazy for hours!!!! Thanks! that helped a loooot!

**Comment by wavesailor** [comment]
@aissaghouti - Thank, that worked perfectly.

This was difficult to resolve/debug as Gmail, Yahoo and Hotmail don't bounce the emails - they just disappear.

The documentation states the following
> **name** – optional hostname of the client, used for identifying to the server, defaults to hostname of the machine

But this is **not** true as it just puts '**127.0.0.1**' as the default name.

**Comment by jprivillaso** [comment]
Adding the name solves the problem. Just to be more clear for anyone else with this problem, you should put your **domain name**. Like this
```
var transporter = nodemailer.createTransport(smtpTransport({
    name: 'www.yourdomain.com',
    host:'smtp.host.com',
    port: port,
    secure: true,
    auth: {
        user: user,
        pass: pass
    }
}));
```

**Comment by EthanThatOneKid** [comment]
@jprivillaso what version did that work on? I am using the most recent version and I am still getting the same problem.

**Comment by hbendix** [comment]
@aissaghouti @jprivillaso does not work for me (version 6.3.0)

**Comment by v1b3m** [comment]
Not working for me either.

**Comment by adahox** [comment]
> We had the same problem using v2.7.2.
> We solved the problem by adding the "name" option to smtpTransport:
> 
> ```
> var transporter = nodemailer.createTransport(smtpTransport({
>     name: serverName,
>     host: host,
>     port: port,
>     secure: true,
>     auth: {
>         user: user,
>         pass: pass
>     }
> }));
> ```

it was amazing. works fine to me. thanks very very much. 2 days lost with this problem <3

**Comment by ebdulrasheed** [comment]
@aissaghouti It took me about 7-8 hours until I found this thread. It worked like a charm. Thank you very much :)

**Comment by NateZimmer** [comment]
Yeah... took me about 4 hours to figure this out :( . I could send with firebird, python but not nodemailer.  Please add `name` to the examples else gmail rejects it.

**Comment by andyford** [comment]
My emails to gmail and yahoo accounts were disappearing and the tip from @aissaghouti to add the `name` field ((with the domain as @jprivillaso suggested) worked for sending to gmail accounts but not yahoo accounts

when sending to either gmail or yahoo accounts I get a response like:
```
{
    accepted: [ 'example@yahoo.com' ],
    rejected: [],
    envelopeTime: 408,
    messageTime: 271,
    messageSize: 331,
    response: '250 OK id=1ipK7j-003YAU-KS',
    envelope: { from: 'notifications@email.example.com', to: [Array] },
    messageId: '<795f56f6-9548-5f5e-485e-1ee0de1472cc@email.example.com>'
  }
```

I'm using https://github.com/adonisjs/adonis-mail / https://adonisjs.com/docs/4.0/mail which uses nodemailer under the hood

now that I've added `name`, sending to gmail accounts works, but sending to yahoo accounts still does not ... anyone seen/solved this problem?
```
{
        driver: "smtp",
        port: 465,
        host: "jamayla.asoshared.com",
        secure: true,
        auth: {
            user: "notifications@email.example.com",
            pass: "example"
        },
        name: "email.example.com"
 }
```

**Comment by webshastra** [comment]
> We had the same problem using v2.7.2.
> We solved the problem by adding the "name" option to smtpTransport:
> 
> ```
> var transporter = nodemailer.createTransport(smtpTransport({
>     name: serverName,
>     host: host,
>     port: port,
>     secure: true,
>     auth: {
>         user: user,
>         pass: pass
>     }
> }));
> ```

lost my 3 hours to this stupid issue , thanks a lot buddy

**Comment by outranker** [comment]
> Adding the name solves the problem. Just to be more clear for anyone else with this problem, you should put your **domain name**. Like this
> 
> ```
> var transporter = nodemailer.createTransport(smtpTransport({
>     name: 'www.yourdomain.com',
>     host:'smtp.host.com',
>     port: port,
>     secure: true,
>     auth: {
>         user: user,
>         pass: pass
>     }
> }));
> ```

Thank you very much. That solved my problem as well!

**Comment by Mozoee** [comment]
Hi Everyone,

I am using bluehost to send out emails. Using  "nodemailer": "^6.4.6", tried all sorts of option mentioned here and few from SO but nothing seems to be working for me.. Below is the code 

```let transporter = nodemailer.createTransport({
            name: 'www.domain.com',
            host: 'box***.bluehost.com',
            port: 465,
            secure: true,
            auth: {
                user: 'accounts@domain.com',
                pass: 'password',
            },
            tls: {
                rejectUnauthorized: false,
            },
            debug: true,
        })
        let mailOptions = {
            from: '"Sender name" <accounts@domain.com>',
            to: 'some@gmail.com',
            subject: 'Confirm your account',
            html: 'Please Click here to confirm your email address.',
        }
        transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
                console.log(
                    `errorFromNodeMailer: ${JSON.stringify(error, null, 4)}`
                )
                return Error('Something went wrong while sending email.')
            }
            console.log(`emailSent: ${info.messageId}`)
        })

I also tried 

host: 'box***.bluehost.com',
            port: 587, // I also tried port : 26  as in email client config on                 bluehost I found supported port for outgoing is 26  
            secure: false,
            auth: {
                user: 'accounts@domain.com',
                pass: 'password',
            },
            tls: {
                rejectUnauthorized: false,
            },


Nothing worked so far. Everytime I am getting


{
    "code": "EAUTH",
    "response": "535 Incorrect authentication data",
    "responseCode": 535,
    "command": "AUTH PLAIN"
}


Any assistance in this matter would be highly appreciated. 

**Comment by agheda11** [comment]
> We had the same problem using v2.7.2.
> We solved the problem by adding the "name" option to smtpTransport:
> 
> ```
> var transporter = nodemailer.createTransport(smtpTransport({
>     name: serverName,
>     host: host,
>     port: port,
>     secure: true,
>     auth: {
>         user: user,
>         pass: pass
>     }
> }));
> ```

### Thank you so much it worked for me... .

**Comment by uttaravadina** [comment]
@Mozoee you should try this config:


```
const nm = require('nodemailer')
const smtpTransport = require('nodemailer/lib/smtp-transport')

let t = nm.createTransport( new smtpTransport({
  name: '***',
  pool: true,
  host: "***",
  port: 465,
  secure: true, // use TLS
  auth: {
    user: "****",
    pass: "***"
  },
  tls: {
    ciphers:'SSLv3'
  },  
  connectionTimeout: 5000,
  socketTimeout: 5000,
  greetingTimeout: 5000,
}));
```

**Comment by batica81** [comment]
Works with "name" parameter on hostgator mailer! This should be in the main tutorial! Mails do go out without it (to mailtrap) but with omitted headers like spf and dkim they do not get far.

**Comment by bsbilal** [comment]
same problem with 

```
`let transporter = nodemailer.createTransport(new smtpTransport({
        name: "Games Inc.",
        host: "***.***.com",
        port: 465,
        pool: true,
        secure: true,
        auth: {
            user: "noreply@****games.com",
            pass: "******",
        },
        tls: {
            ciphers:'SSLv3'
        },
        connectionTimeout: 5000,
        socketTimeout: 5000,
        greetingTimeout: 5000
    }));
```

**Comment by andris9** [comment]
`name` is not your company name or anything but the PTR hostname of your outbound IP address.

**Comment by digital230** [comment]
i want to add my 50 cents also. y case was the subject string was bit longer when i provide short subject gmail start receiving emails.

**Comment by gaalvarez** [comment]
For me the solution was set name whit provider's name. In my case name: 'hostgator'. Thansk to @TrejoCode

**Comment by hassaaneforte** [comment]
> We had the same problem using v2.7.2.
> We solved the problem by adding the "name" option to smtpTransport:
> 
> ```
> var transporter = nodemailer.createTransport(smtpTransport({
>     name: serverName,
>     host: host,
>     port: port,
>     secure: true,
>     auth: {
>         user: user,
>         pass: pass
>     }
> }));
> ```

Thankyou so much. Worked like a charm for me

**Comment by ahertlcode** [comment]
The advice to add name to the transporter constructor works but some e-mail services may not still acccept the incoming mail until you whitelist the e-mail address you are sending the mail with. i.e. add the e-mail address as a contact. That way all the rejected mail get delivered in my case.

**Comment by BABA1995** [comment]
In My case is still not working after adding name. 
const nodemailer = require('nodemailer');
let transport = nodemailer.createTransport(
    {
        
       name:"www.pagegap.com",
  
        host: "mail.pagegap.com",
        port: 587,
        secure: false,
        auth:{
            user:'testing@pagegap.com',
            pass:'testing2021'
        },
        tls:{
            rejectUnauthorized: false
        }
       
}
)

///send out email
var mailOptions = {
    from:'"pagegap" <testing@pagegap.com>',
    to:'fakruddinbaba16@gmail.com',
    subject:'Hello world this is a test mail',
    text:'This is the body of the mail'
}

transport.sendMail(mailOptions, function(error,info){
    if(error){
        console.log(error)
    }else{
        console.log("Email sent" + info.response)
    }
})

**Comment by ahertlcode** [comment]
> In My case is still not working after adding name.
> const nodemailer = require('nodemailer');
> let transport = nodemailer.createTransport(
> {
> 
> ```
>    name:"www.pagegap.com",
> 
>     host: "mail.pagegap.com",
>     port: 587,
>     secure: false,
>     auth:{
>         user:'testing@pagegap.com',
>         pass:'********'
>     },
>     tls:{
>         rejectUnauthorized: false
>     }
> ```
> 
> }
> )
> 
> ///send out email
> var mailOptions = {
> from:'"pagegap" [testing@pagegap.com](mailto:testing@pagegap.com)',
> to:'[fakruddinbaba16@gmail.com](mailto:fakruddinbaba16@gmail.com)',
> subject:'Hello world this is a test mail',
> text:'This is the body of the mail'
> }
> 
> transport.sendMail(mailOptions, function(error,info){
> if(error){
> console.log(error)
> }else{
> console.log("Email sent" + info.response)
> }
> })

See a sample working code for me
`var nodemailer = require('nodemailer');
const pug = require('pug');

var transporter = nodemailer.createTransport({
    name: process.env.MAIL_SERVER_NAME,
    host: process.env.MAIL_HOST,
    port: process.env.MAIL_PORT,
    secure: process.env.MAIL_SECURE,
    auth: {
      user: process.env.MAIL_ADDRESS,
      pass: process.env.MAIL_PASSWORD
    }
});


.env file seeting for sending mails
MAIL_SERVER_NAME= i quoted my domain name but not sure its neccesary
MAIL_HOST=email host
MAIL_PORT=465
MAIL_SECURE=true
MAIL_ADDRESS=a valid existing email address.
MAIL_PASSWORD=email password`

remember I mentioned that some e-mail services may not still accept the sent mail until you add the sending e-mail address to contact. In my case gmail delivered after adding name to transporter but yahoo and hotmail did not but adding the sending e-mail to contact in both cases worked.

**Comment by BABA1995** [comment]
I did as you told facing an error "Error: connect ECONNREFUSED 127.0.0.1:465".
const nodemailer = require('nodemailer');
nodemailer.createTransport({ sendmail: true });
MAIL_SERVER_NAME= "www.pagegap.com";
MAIL_HOST="mail.pagegap.com"
MAIL_PORT=465;
MAIL_SECURE=true;
MAIL_ADDRESS='testing@pagegap.com';
MAIL_PASSWORD='testing2021';
let transport = nodemailer.createTransport(
    {
        
       name:process.env.MAIL_SERVER_NAME,
        host: process.env.MAIL_HOST,
        port: process.env.MAIL_PORT,
        secure: process.env.MAIL_SECURE,
        auth:{
            user:process.env.MAIL_ADDRESS,
            pass:process.env.MAIL_PASSWORD
        },
        tls:{
            rejectUnauthorized: true
        }
       
}
)

///send out email
var mailOptions = {
    from:'"pagegap" <testing@pagegap.com>',
    to:'fakruddinbaba16@gmail.com',
    subject:'Hello world this is a test mail',
    text:'This is the body of the mail'
}

transport.sendMail(mailOptions, function(error,info){
    if(error){
        console.log(error)
    }else{
        console.log("Email sent" + info.response)
    }
});

**Comment by ahertlcode** [comment]
> I did as you told facing an error "Error: connect ECONNREFUSED 127.0.0.1:465".
> const nodemailer = require('nodemailer');
> nodemailer.createTransport({ sendmail: true });
> MAIL_SERVER_NAME= "www.pagegap.com";
> MAIL_HOST="mail.pagegap.com"
> MAIL_PORT=465;
> MAIL_SECURE=true;
> MAIL_ADDRESS='[testing@pagegap.com](mailto:testing@pagegap.com)';
> MAIL_PASSWORD="***********';
> let transport = nodemailer.createTransport(
> {
> 
> ```
>    name:process.env.MAIL_SERVER_NAME,
>     host: process.env.MAIL_HOST,
>     port: process.env.MAIL_PORT,
>     secure: process.env.MAIL_SECURE,
>     auth:{
>         user:process.env.MAIL_ADDRESS,
>         pass:process.env.MAIL_PASSWORD
>     },
>     tls:{
>         rejectUnauthorized: true
>     }
> ```
> 
> }
> )
> 
> ///send out email
> var mailOptions = {
> from:'"pagegap" [testing@pagegap.com](mailto:testing@pagegap.com)',
> to:'[fakruddinbaba16@gmail.com](mailto:fakruddinbaba16@gmail.com)',
> subject:'Hello world this is a test mail',
> text:'This is the body of the mail'
> }
> 
> transport.sendMail(mailOptions, function(error,info){
> if(error){
> console.log(error)
> }else{
> console.log("Email sent" + info.response)
> }
> });

is www.pagegap.com a vaild hosted domain? which backend js framework are you using? 
You will need to get the e-mail server settings from you hosting account. you need to add this: require('dotenv').config(); to your entry js file before creating the starting the nodejs server.

**Comment by BABA1995** [comment]
Yes, It's valid hosted domain. I'm using node as backend.
What Kind of settings need to get from hosting account..?
Can we have zoom call..?

**Comment by ahertlcode** [comment]
> Yes, It's valid hosted domain. I'm using node as backend.
> What Kind of settings need to get from hosting account..?
> Can we have zoom call..?

create the zoom meeting send me the link.

**Comment by vallemar** [comment]
I have the same error, I cannot send an email to gmail. I have tried everything that comes in this thread, I am not very clear about a valid value for `name`

**Comment by Flakster** [comment]
> We had the same problem using v2.7.2.
> We solved the problem by adding the "name" option to smtpTransport:
> 
> ```
> var transporter = nodemailer.createTransport(smtpTransport({
>     name: serverName,
>     host: host,
>     port: port,
>     secure: true,
>     auth: {
>         user: user,
>         pass: pass
>     }
> }));
> ```

Thank you. This was really useful from me!!!
🙏😀🙏😀🙏😀

**Comment by Flakster** [comment]
> I have the same error, I cannot send an email to gmail. I have tried everything that comes in this thread, I am not very clear about a valid value for `name`

I used the same HOST value

**Comment by luizxsoto** [comment]
> We had the same problem using v2.7.2. We solved the problem by adding the "name" option to smtpTransport:
> 
> ```
> var transporter = nodemailer.createTransport(smtpTransport({
>     name: serverName,
>     host: host,
>     port: port,
>     secure: true,
>     auth: {
>         user: user,
>         pass: pass
>     }
> }));
> ```

YOU SAVED MY JOB MAN! THANK YOU SO MUTCH! 🙌

**Comment by IQisMySenpai** [comment]
I had this problem yesterday and the `name` field fix didn't work for me.

**My Problem/Solution:**
For any future people having this problem, where the name field isn't solving the issue, also check that you TXT spf entry of your domain is correct.
