### ISSUE TITLE
Nodemailer Error (getaddrinfo)

### ISSUE THREAD

**Issue by gwishart** [nodemailer/nodemailer#679]
Nodemailer version: v1.11.0
Node.js version:  v4.2.3
OS: Ubuntu 14.04

I am running nodemailer to send emails through an exchange server. It was working entirely fine up until about a week ago. The odd thing is that none of the code has been changed so I'm trying to figure out what is going on. I am using a STMP setup which I have listed the code for below:

`var smtpTransport = require('nodemailer-smtp-transport');
var transporter = nodemailer.createTransport(smtpTransport({
    host: 'west.exch032.serverdata.net',
    port: 587,
    secureConnection: false,
    auth: {
        user: 'SENDER_ADDRESS@EMAIL.COM',
        pass: '****'
    },
    tls: {
        ciphers:'SSLv3'
    }
}));`

`transporter.sendMail({
                from: 'SENDER_ADDRESS@EMAIL.COM',
                to: 'RECEIVING_ADDRESS@EMAIL.COM',
                subject: 'New User Registration',
                html: notifyEmail
            }, function(err) {
                err && console.warn(err)
                done()
            });`

The error that I am getting is:
`{ [Error: getaddrinfo EAI_AGAIN west.exch032.serverdata.net:587]
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'west.exch032.serverdata.net',
  host: 'west.exch032.serverdata.net',
  port: 587 }`

Can someone help with decoding what this error means?

**Comment by andris9** [comment]
EAI_AGAIN means that DNS lookup timed out. Can you resolve the same name from the command line of the same machine like this:

    dig A west.exch032.serverdata.net

**Comment by gwishart** [comment]
I tried using the that within the command line and it returned with an error saying:
`; <<>> DiG 9.9.5-3ubuntu0.9-Ubuntu <<>> A west.exch032.serverdata.net
;; global options: +cmd
;; connection timed out; no servers could be reached`

**Comment by gwishart** [comment]
Issue has been fixed, this can be closed.
