### ISSUE TITLE
Transport API documentation? 

### ISSUE THREAD

**Issue by wzup** [nodemailer/nodemailer#681]
You didn't provide a link here https://nodemailer.com/2-0-0-beta/setup-transporter/

Where may I find the resource?

**Comment by davesag** [comment]
I have been trying to write a very simple Transporter but am finding the lack of documentation of the `message` object to be a challenge.  I've [written up a question on StackOverflow](http://stackoverflow.com/questions/41011223/nodemailer-transporter-how-do-i-access-standard-mail-fields).  Maybe someone here can point me in the right direction.
