### ISSUE TITLE
Some attachments are causing exchange server create useless attachments (like "ATT00001.htm")

### ISSUE THREAD

**Issue by GroovyQA** [nodemailer/nodemailer#682]
Some attachments are causing exchange server to generate ATT...bin files (such as .mht attachments)
Seems like the solution is to put the attachments at the end of a message, after text/html etc.

See this article: http://kb.mit.edu/confluence/pages/viewpage.action?pageId=4981187

Details and screenshot:
-Nodemailer-smtp-transport "version": "2.7.2"
-Node.js version v4.5.0
-Windows 7 (git bash)
![screenshot](https://cloud.githubusercontent.com/assets/21066593/19736742/6be6d530-9b65-11e6-8243-065c79996a56.JPG)

**Comment by andris9** [comment]
MHT is an embedded message so I guess that what happens is that the ATT* files are part of the mht attachments. Nodemailer puts text parts before attachment parts.
