### ISSUE TITLE
issue with ubuntu 16.04?

### ISSUE THREAD

**Issue by matthewepler** [nodemailer/nodemailer#683]
using nodemailer v. 2.6.4
using node v. 4.6
OS = ubuntu 16.4 LTS

I've run the same code on a machine with Ubuntu, and in OSX. Runs fine in OSX, but timesout in Ubuntu 16.04. Are there any known issues with the module in Linux? I know there shouldn't be if the environment is the same - but it's the only thing that I can see is different, stumped. 

Here's a gist with my code:
https://gist.github.com/matthewepler/d272d70ae486eb969cf36e8450f03ba3

**Comment by andris9** [comment]
Timeouts are usually caused by firewall configuration

**Comment by matthewepler** [comment]
You were correct. I was connected to a VPN (Private Internet Access) and as soon as I disconnected everything worked fine. Thanks for the quick response.
