### ISSUE TITLE
Remove not needed Headers

### ISSUE THREAD

**Issue by zain-creation** [nodemailer/nodemailer#684]
Hi thank you for this great work,
i want to delete not needed Headers like 
Message-ID: <87ed40a9-2148-8626-dc32-7349f3ec04ba@gmail.com>
X-Mailer: nodemailer (2.6.4; +https://nodemailer.com/;
 SMTP/2.7.2[client:2.12.0])
Content-Transfer-Encoding: 7bit
Date: Thu, 27 Oct 2016 19:18:18 +0000

thnks for :+1:

**Comment by andris9** [comment]
What makes you think that these headers (besides X-Mailer) are not needed?

**Comment by uiteoi** [comment]
Lacking a valid Message-ID may increase spam score. You can provide your own by setting option "messageId".
