### ISSUE TITLE
Ineffective option `secure`

### ISSUE THREAD

**Issue by a-ludi** [nodemailer/nodemailer#686]
The option `secure` is evidently without effect. In fact, the string `secure` cannot be found anywhere in the sources. If my point of view seems correct it would be nice to remove the corresponding docs.

**Comment by andris9** [comment]
If `secure` is true, then connection against SMTP server is started using TLS, so this option is very important

**Comment by a-ludi** [comment]
I absolutely think that it is an important option. But the option seems to have NO EFFECT. To make this point clearer: it had no effect on an TLS related issue.

**Comment by andris9** [comment]
`secure` propagates down to [here](https://github.com/nodemailer/smtp-connection/blob/master/lib/smtp-connection.js#L56). What was the TLS issue?

**Comment by a-ludi** [comment]
Yeah, I've tracked that line, too. The issue was with self-signed certificates being rejected by `TLSSocket`. I guessed that setting `secure: false` would solve my problem but it did not. What helped were both `ignoreTLS: true` and `tls: { rejectUnauthorized: true }`.
