### ISSUE TITLE
smtpConfig works in dev, not in production in docker container

### ISSUE THREAD

**Issue by mycompassspins** [nodemailer/nodemailer#689]
Hey there,

I've got nodemailer working great in dev, however, I haven't been able to get it to work in a production environment inside a docker container. 

I'm on nodemailer 2.6.4 and nodemailer-smtp-transport 2.7.2. I'm on Node 7.0.0 and OSX Sierra in dev and debian inside the docker container. 

Here's my smptConfig:

```
smtpConfig: {
    host: 'smtp.mydomain.com',
    port: 587,
    auth: {
        user: 'me@mydomain.com',
        pass: "myPassword123"
    },
    tls: { rejectUnauthorized: false }
}
```

The above config works fine in dev, but produces a "certificate is expired" error in the docker container. I've tried various other options on the above config object, all with the same result, with the exception of `tls: { rejectUnauthorized: false, ciphers: 'SSLv3' }`, which produces an ssl version error. Any ideas on this? I must've rebuilt this container a hundred times by now with a slightly different configuration each time with no luck. 

# Update

If I toggle `process.env.NODE_TLS_REJECT_UNAUTHORIZED` in the sendMail method, I get this error:

```
140463779485504:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
```

**Comment by mycompassspins** [comment]
This was an issue with the way I was using environment variables in my docker-compose.yml, I believe. In my prod config I had this:

```
smtpConfig: {
    host: process.env.SMTP_HOST || 'smtp.mydomain.com'
    // etc . . .
}
```
And in my docker-compose.yml:

```
environment:
  - SMTP_HOST=smtp.mydomain.com
  # etc . . .
```
I still don't know why that didn't work properly, but I know that hard-coding the `smtpConfig` solved it.

**Comment by mikamboo** [comment]
Hello @mycompassspins, I have the same probleme ... I try to dockerize my nodejs app but send mail not working on production server. On my local machine it's works even in docker container.

This is my config

````
let transporter = nodemailer.createTransport({
    type: 'smtp',
	host: 'smtp.mydomain.com',
	port: 465,
	secure: true,
	tls: {
		rejectUnauthorized: false
	},
    auth: {
        user: 'user@mydomain.com',
        pass: '`xxxx'
    }
});
```
The log display sucess message : 

```
Message <d304096c-2a95-f05e-4ff9-66b530ad0cf6@blurdybloop.com> sent: 250 2.0.0 Ok: queued as E40E842008C
```

I try to set ENV like u but not success
