### ISSUE TITLE
Nodemailer on ubuntu

### ISSUE THREAD

**Issue by tamaker** [nodemailer/nodemailer#690]
Include the following information with your issue:

1) Nodemailer version 2.5.0
2) Node.js version 6.4.0
3) Your operating system Ubuntu Server 14.04

I'm trying to integrate nodemailer into my Node.js Application and DONT want to use gmail, but instead use the PHP-based mail functionality of the machine.  (i.e. I'm able to send mail from PHP just fine).... or do I have to instead skip nodemailer alltogether and just do a curl or post to a PHP script / function to send my email out from my application?  I'd love to use nodemailer if possible.

Is this possible?

**Comment by andris9** [comment]
PHP pipes all emails to the `sendmail` command. If you want to have the same behavior then you can either use the [nodemailer-sendmail-transport](https://github.com/andris9/nodemailer-sendmail-transport) plugin or (assuming you have Postfix or similar running) use the default SMTP transport to connect to localhost port 25. You can read about the difference of PHP and Nodemailer [here](https://nodemailer.com/2-0-0-beta/setup-smtp/smtp-say-what/)
