### ISSUE TITLE
Greeting Never Received Hotmail or Office 365

### ISSUE THREAD

**Issue by tjchaplin** [nodemailer/nodemailer#691]
Trying to connect to Hotmail or Office 365 returns error:
{ [Error: Greeting never received] code: 'ETIMEDOUT', command: 'CONN' } 

```js
Transporter configuration:
var transporter = nodemailer.createTransport({
    host: "smtp-mail.outlook.com",
    secureConnection: false,
    port: 587,
    tls: {
       ciphers:'SSLv3'
    },
    auth: {
        user: '****',
        pass: '****'
    }
});
```

Include the following information with your issue:

1) Nodemailer version you are having problems with (eg. v1.3.7)
2.6.4
2) Node.js version you are using (run `node -v` to see it, eg v5.5.0)
4.6.1
3) Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
Windows 7
4) If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)

```js
var nodemailer = require('nodemailer');

var transporter = nodemailer.createTransport({
    host: "smtp-mail.outlook.com",
    secureConnection: false,
    port: 587,
    tls: {
       ciphers:'SSLv3'
    },
    auth: {
        user: '****',
        pass: '****'
    }
});


var mailOptions = {
    from: 'xxxx*****',
    to: 'xxxx*****',
    subject: 'Hello ',
    text: 'Hello world ',
    html: '<b>Hello world </b><br> This is the first email sent with Nodemailer in Node.js'
};

transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }

    console.log('Message sent: ' + info.response);
});
```

If you are having problems with Gmail, then make sure you have
read this post before filing your issue: http://nodemailer.com/using-gmail/

**Comment by andris9** [comment]
I can't reproduce it. Could there be some kind of an antivirus or firewall in your computer that messes up SMTP connections?

**Comment by tjchaplin** [comment]
Yes, you're correct this ended up being a firewall issue.

Thank you for the quick response and solution.

**Comment by stpa81** [comment]
Could you explain that firewall issue, because i'm having the same problem?

**Comment by andris9** [comment]
If your firewall interferes or blocks the SMTP port you want to use, then you get a timeout. Firewall issues are most common in desktop computers where antivirus applications mess around with the network connections and in systems like Google Cloud where email ports are blocked by default.
