### ISSUE TITLE
Remove MIME-Version ?

### ISSUE THREAD

**Issue by marcosgouvea** [nodemailer/nodemailer#692]
how do i remove MIME-Version from the Header ? 

- node 6.6
- nodemailer 2.6

**Comment by andris9** [comment]
Why would you want to do that?

**Comment by marcosgouvea** [comment]
just to dont be filtered from mail server.
i would like to remove the mime-version from my header

**Comment by andris9** [comment]
MIME-Version is a required header by [rfc2045](https://tools.ietf.org/html/rfc2045#section-4)

> Messages composed in accordance with this document MUST include such
   a header field

If you want to generate messages with custom headers, then you need a more lower level module like [buildmail](https://github.com/nodemailer/buildmail) which is also used by Nodemailer.
