### ISSUE TITLE
Error upgrading connection with STARTTLS: 500 5.0.0 'XXXXXXXX': command not understood.

### ISSUE THREAD

**Issue by harishanchu** [nodemailer/nodemailer#694]
1) Nodemailer version - 2.6.4
2) Node.js version -  6.9.1
3) Operating system -  Ubuntu 16.04

I got this error when I tried following:

```
var nodemailer = require('nodemailer');

var transporter = nodemailer.createTransport({
    auth: {
        user:    "xxxxxxxxxx",
        pass:"xxxxxxxxxxx"
    },
    host:    "xxxxxxxxxx",
    port:    25,
    requireTLS:     true
});

transporter.verify(function(e) {console.log(e)})
```

Error stack:
```
{ Error: Error upgrading connection with STARTTLS: 500 5.0.0 'XXXXXXXX': command not understood.
       at SMTPConnection._actionSTARTTLS (/home/queue-worker/node_modules/smtp-connection/lib/smtp-connection.js:1033:23)
       at SMTPConnection._processResponse (/home/queue-worker/node_modules/smtp-connection/lib/smtp-connection.js:669:16)
       at SMTPConnection._onData (/home/queue-worker/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:548:20)
     code: 'ETLS',
     response: '500 5.0.0 \'XXXXXXXX\': command not understood.',
     responseCode: 500,
     command: 'STARTTLS' }
```

Any suggestion on why this is happening?

**Comment by surajwy** [comment]
Your port number is 25. For starttls, it should be 587.

**Comment by andris9** [comment]
Port nr 25 is probably correct. `requireTLS:true` forces the client to use STARTTLS even if the server does not advertise it. This is needed if you know your server provides STARTTLS support and you want to avoid downgrade attack. If you are talking to an unknown server then you should probably set requireTLS to false.

**Comment by andris9** [comment]
From the error message it seems you are actually being attacked. You try to send STARTTLS but the command is converted by someone to XXXXXXX. This is known to happen in some mobile networks and in some states as well.

**Comment by harishanchu** [comment]
I'm able to send mail using Java with same configuration.

Here is the debug response from smtp server when I tried to send an email from NodeJS:

```
connecting: <host:port>
connected: <host:port>
220 ***********************

ehlo <host-name>

250-Hello <host-name>
250-AUTH LOGIN
250-ENHANCEDSTATUSCODES
250-SIZE 0
250-XXXXXXXA
250 8BITMIME

starttls

500 5.0.0 'XXXXXXXX': command not understood.
```

Is there anything to be done to fix this from my side?

**Comment by andris9** [comment]
Set `requireTLS` to `false` to "fix" it. This might be a firewall issue as well (see [this](http://www.cisco.com/c/en/us/support/docs/security/email-security-appliance/118550-qa-esa-00.html))

**Comment by harishanchu** [comment]
If I set `requireTLS` to `false` then it fails during authentication.

```
{ Error: Invalid login: 535 5.7.0 Authentication Failed
       at SMTPConnection._formatError (/home/job-queue/queue-worker/node_modules/smtp-connection/lib/smtp-connection.js:528:15)
       at SMTPConnection._actionAUTHComplete (/home/job-queue/queue-worker/node_modules/smtp-connection/lib/smtp-connection.js:1231:30)
       at SMTPConnection.<anonymous> (/home/job-queue/queue-worker/node_modules/smtp-connection/lib/smtp-connection.js:1199:14)
       at SMTPConnection._processResponse (/home/job-queue/queue-worker/node_modules/smtp-connection/lib/smtp-connection.js:669:16)
       at SMTPConnection._onData (/home/job-queue/queue-worker/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:548:20)
     code: 'EAUTH',
     response: '535 5.7.0 Authentication Failed',
     responseCode: 535,
     command: 'AUTH LOGIN' }
```

I don't think it is caused by firewall, since I was able to send mail from java using same smtp credentials.

**Comment by andris9** [comment]
Could you compare your java app and nodemailer app with wireshark or tcpdump to see what they are actually doing differently. As you can't use TLS then everything should be in cleartext and fully readable.

BTW. do you have some kind of antivirus in your machine? does disabling it make a difference?

**Comment by harishanchu** [comment]
Hi @andris9 ,

I appreciate your help, I will get back to you with more information.

BTW I'm using Ubuntu 16.04, I don't have any antivirus running on my machine. My email server is running on a VPN and my machine is connected to the same.

**Comment by pratikagrawal01** [comment]
Just came across this post. Add this in your transport and it should work. 

ignoreTLS : true, 
secure: false

**Comment by ShekharSahu** [comment]
Hi @harishanchu it's been over 4 years. How did you resolve this? Same as you, this configuration worked for me on java, but gives the same error on node.

**Comment by xlucvvs** [comment]
> Hi @harishanchu it's been over 4 years. How did you resolve this? Same as you, this configuration worked for me on java, but gives the same error on node.

@ShekharSahu did you resolve this?

**Comment by andris9** [comment]
Seeing things like XXXXXXX in the EHLO response usually means that ISP (probably mobile network) is actively suppressing TLS on email connections.

**Comment by ShekharSahu** [comment]
> > Hi @harishanchu it's been over 4 years. How did you resolve this? Same as you, this configuration worked for me on java, but gives the same error on node.
> 
> @ShekharSahu did you resolve this?

Didn't work. Later we were given a different mail relay server, it was anonymous, which worked on node.
