### ISSUE TITLE
recipient issue

### ISSUE THREAD

**Issue by zebasyed** [nodemailer/nodemailer#697]
nodemailer code is as follows:

sendMail : function(to_mail_id, subject, mailContent) {
      var nodemailer = require("nodemailer");
      var funcname = 'sendMail';
      sails.log.debug(funcname + ' to: ' + to_mail_id + ' subject: ' + subject);
      var smtpTransport = nodemailer.createTransport("SMTP",{
         host: "mail.smtp2go.com",
         port: 2525, 
         auth: {
                    user: 'user',
                    pass: 'password'
                }
      });
      var messageContent = {
        "html": mailContent,
        "text": "Example text content",
        "subject": subject,
        "from_email": "donotreply@tagmobile.com",
        "from_name": "Support",
        "to":  to_mail_id
      };
      sails.log.debug(funcname + ' to: ' + to_mail_id + ' message content is: ' + messageContent);
      smtpTransport.sendMail(messageContent, function(error, response){
          if(error){
              console.log(error);
          }else{
              console.log("Message sent: " + response.message);
          }
       });
    },

But i am getting the following error::: 

{ [RecipientError: Can't send mail - all recipients were rejected]
  name: 'RecipientError',
  data: '550-Verification failed for <anonymous@cnode1.devion.intelliverse.com>\r\n550-Unrouteable address\r\n550 unable to verify sender address',
  stage: 'rcpt' }

**Comment by andris9** [comment]
You seem to use a very old API that was removed more than 2 years ago. See https://nodemailer.com/ for actual field names and values.

**Comment by zebasyed** [comment]
when i hardcode the values i.e when i hardcode the to address i am able to send the mail. How is that possible then??
