### ISSUE TITLE
Too many connection 

### ISSUE THREAD

**Issue by Space69** [nodemailer/nodemailer#699]
I have an issue with using nodemailer on my highschool SMTP server. 

It says I am doing "too many connection". Could you help me by giving me a crystal example with 10 emails. I think this issue come from a bad use of the pool. May I have a crystal clear example of a use with 10 emails thanks to nodemailer and a pool. I retrieve it for 4 yours in Google...
Thanks in advance.

**Comment by andris9** [comment]
Use `poolt:true` with `maxConnections` option

```javascript
var transporter = nodemailer.createTransport({
    pool: true,
    maxConnections: 1,
    host: xxx,
    port: xxx,
    ...
});
```

also make sure that you reuse the same `transporter` object when sending out messages, this means that you should call `nodemailer.createTransport()` only once and not every time you need to send a message.

**Comment by Space69** [comment]
Thanks for this fast answer. Could you give me an example please? As a matter if fact I am not certain about the way to store my list of email...
