### ISSUE TITLE
Email retry sending logic confusion

### ISSUE THREAD

**Issue by shivanshu3** [nodemailer/nodemailer#701]
Hi,

I'm trying to implement email sending retry logic in my app using a persistent queue. I'm using direct transport to send emails from my server, by creating a transporter using the following line of code:

```
var transporter = nodemailer.createTransport('direct:?name=example.com');
```

I'm using the following function to send emails:

```
transporter.sendMail(data, function(err, info){...})
```

I'm not quite sure when I should retry sending emails. My understanding is that email sending should be retried when either:

1) The `err` object is not null. Or,
2) When `info.rejected` or `info.pending` arrays are non empty.

In the first case, I would simply resend the exact same mail object after some time.

And in the second case, I would merge the arrays `info.rejected` and `info.pending`, create a new mail object with these recipients only, and try sending an email after some time.

Do you think this logic is correct? I just want to verify the behavior of this function and that I'm following the best practices for using your wonderful software :)

Thanks.

**Comment by andris9** [comment]
If you get an error in response then the message failed completely and should be retried. If you have some addresses in the rejected array then you should try to retry to these addresses only. If you have addresses in the pending array then there's not much other to do than wait, this usually means that the recipient server greylisted your message and Nodemailer tries to deliver it again after a while.

In general I would not suggest you to use the direct transport for anything significant as it is in-memory only which means that all messages are loaded fully into memory before delivery and if you restart the process then the queue gets lost. I would suggest switching to [zone-mta](https://github.com/zone-eu/zone-mta) which is loosely based on the nodemailer direct transport module but runs as a separate application, handles all the retries automatically and has a permanent store for the queues.

**Comment by shivanshu3** [comment]
I see. I'm basically running my own SMTP server in the same Node process and can't use an external SMTP service to send emails. I also have a persistent queue set up as I mentioned before which should make direct transport reliable. Is there a way to disable the retrying of pending messages by Nodemailer using the in-memory queue? I'd like to be able to take over that retrying process using my own persistent queue.

**Comment by andris9** [comment]
If you want to handle everything from your single node process then you should consider creating your own queue handler for this and not use direct or pooled transport. Instead create a new "normal" (eg non-pooled, non-direct) nodemailer transport for every message (or for every separate destination), group messages by destination (eg. if you have a single message for multiple recipients in different domains, then for every domain you need a separate copy for the same message), send these messages and check the response code from the recipient server.

You can consult [nodemailer-direct-transport](https://github.com/nodemailer/nodemailer-direct-transport/) source code to see how it handles everything. You can't really apply your own queue system as that module is a complete solution.

**Comment by shivanshu3** [comment]
Thank you very much! I think I'll fork the `nodemailer-direct-transport` repo and swap out the message queue you are using with a wrapper over my persistent message queue.
