### ISSUE TITLE
nodemailer attachment is not encoded as ascii

### ISSUE THREAD

**Issue by simllll** [nodemailer/nodemailer#706]
node v4.6.0, nodemailer 2.6.4, ubuntu 16.04

I try to send an attachment with nodemailer like this:

```
attachments = [{
   filename: 'file.wfi',
   content: output,
   encoding: 'ascii'
}];
```

output is a string. It looks fine, and actually works, but the file needs to be ascii and not utf-8 encoded. Is there something wrong or do I need to specify something else? The file attached to the mail is still utf-8 encoded.
Question is now is this a bug or am I missing something?

$ file -bi file.wfi
text/plain; charset=utf-8

thanks
simon

**Comment by andris9** [comment]
Is there a reason the output needs to be an unencoded string? What do you actually need to accomplish?

**Comment by simllll** [comment]
it's basically a csv file. It's generated on the fly and should then be sent by mail in the right encoding (otherwise the remote system cant handle it correctly).

**Comment by andris9** [comment]
If you need to fully control how the output of the attachment looks like then you can use the `raw` property to define attachment contents. This property must also include full headers. Here's an example of how to do it:

```javascript
var rawHeaders =
    'Content-Type: text/csv\n' +
    'Content-Disposition: attachment; filename=attachment.csv\n' +
    'Content-Transfer-Encoding: 7bit';

var csv = 'a,b,c,d';

var message = {
    from: 'sender@example.com',
    to: 'recipient@example.com',
    subject: 'Test message',
    html: '<p>Hello world!</p>',
    text: 'Hello world!',
    attachments: [{
        raw: rawHeaders + '\n\n' + csv
    }]
};
```

**Comment by simllll** [comment]
Thanks for pointing me in the right direction!

**Comment by Alex1100** [comment]
This doesn't work. Here is my code that fails.

```js
const mailOptions = {
        from: '"crmcc@iu.edi" <crmcc@iu.edu>', // sender address (who sends)
        to: 'alex1100.software@gmail.com',
        subject: 'Uploaded File',
        html: '<b>Please see file attached below.</b>',
        text: 'Please see file attached below.',
        attatchments: [
          {
            raw: `
              Content-Type: text/csv\n
              Content-Disposition: attachment; filename=test.csv\n
              Content-Transfer-Encoding: 7bit\n\n
              a,b,c,d`,
          }
        ],
};

```

Message gets sent without attachment.

**Comment by andris9** [comment]
You have an extra linebreak in the beginning of the string
