### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by ekwon86** [nodemailer/nodemailer#710]
1) Nodemailer v1.0.2
2) Node v6.9.2
3) Windows 7 
4) [Gist Link](https://gist.github.com/ekwon86/b05d40c33a3938e94face3c900d5364b)

Hello, I am receiving the following error when attempting to send an email through Outlook:

> { Error: connect ECONNREFUSED `65.55.163.152:587`
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '65.55.163.152',
  port: 587 }

Please advise.

**Comment by raghu64** [comment]
Hi @ekwon86. I was getting the same error. Did you find out solution for this one?

**Comment by ekwon86** [comment]
Hey @raghu64. I tinkered around with the config for a bit. The following worked for me: [Link to Gist](https://gist.github.com/ekwon86/86310a57105c3d8f94ea753028d614f0)
