### ISSUE TITLE
mailgun - nodemailer - pls check below and share solution

### ISSUE THREAD

**Issue by suriyaJaay** [nodemailer/nodemailer#711]
could anyone tell me how to resolve this with below code? codes get from official page 

initially it gave me the below error  for following code:

**Error: Error: No transport method defined nodemailer mailgun**

var express = require('express');
var nodemailer = require("nodemailer");
var mg = require('nodemailer-mailgun-transport');
var app = express();

var auth = {
    auth: {
        api_key: 'my-mailgun-api here',
        domain: 'myDomain.in'
    }
}

var nodemailerMailgun = nodemailer.createTransport(mg(auth));

app.get('/send', function(req, res) {
    nodemailerMailgun.sendMail({
        from: 'myId@mypersonal.in',
         cc: 'second@domain.com',  
        subject: req.query.subject,'h:Reply-To': 'rmshmaudlin@gmail.com',
        html: '<b>Wow Big powerful letters</b>',
        text: req.query.text,
    }, function(err, info) {
        if (err) {
            console.log('Error: ' + err);
        } else {
            console.log('Response: ' + info);
        }
    });
});

then i have got the following response as below from my cmd 

**Response: [object Object]**

**Comment by expertsa** [comment]
Just log the info object: `console.log(info);`
