### ISSUE TITLE
eml file in attchments recieved in outlook as outlook item file

### ISSUE THREAD

**Issue by dudilugasi** [nodemailer/nodemailer#714]
1. nodemailer version v2.7.0
2. v4.4.7
3. windows 10

when i am sending an eml file as attachment with node mailer i see it in my outlook inbox as an outlook item file and the content is different from the original attachment. its weights less then the original. if i am trying to send the same attachment regular from the outlook it is received ok. 

code example : 
var nodemailer = require("nodemailer");
var transporter = nodemailer.createTransport({
	 host: "smtp.office365.com", // hostname
        secureConnection: false, // TLS requires secureConnection to be false
        port: 587, // port for secure SMTP
        tls: {
            ciphers: 'SSLv3'
        },
        auth: {
            user: "test@outlook.com",
            pass:  "password"
        }
});
var mailOptions = {
    from: 'test@outlook.com', // sender address
    to: 'test@outlook.com', // list of receivers
    subject: 'Hello ?', // Subject line
    text: 'Hello world ??', // plaintext body
    html: '<b>Hello world ??</b>', // html body
	attachments : [{   // encoded string as an attachment
            filename: 'emlfile.eml',
            path : "C:/Users/user/Desktop/emlfile.eml",
            encoding: 'base64'
        }]
};
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    console.log('Message sent: ' + info.response);
});

**Comment by IntraMail** [comment]
I have exactly the same issue with nodemailer. Does anybody found how to make it work ?

**Comment by mat33470** [comment]
Hi, I know it's been a long time but did anybody found a solution to this issue ?

**Comment by ShahswatJha** [comment]
Hi , Did anyone still find a solution? @dudilugasi  @mat33470  @andris9

**Comment by mat33470** [comment]
Hi, 
I added ```contentType: 'application/xml'``` to all .eml attachments description. It seems to work, honestly it's been a long time so I don't really recall if this is what did the trick. 
Good luck !

**Comment by mercmobily** [comment]
A little late but... this is my solution.

 contentTransferEncoding: filename.endsWith('.eml') ? '7bit' : false

This way the attached file will be displayed properly in Outlook
