### ISSUE TITLE
How to create ical event in nodemailer

### ISSUE THREAD

**Issue by chetanmekha** [nodemailer/nodemailer#716]
Include the following information with your issue:

1) Nodemailer version i am using is 2.7.0.
2) Node.js version i am using v4.4.7)
3) Operating system - windows 10

How can I create icalEvent in nodemailer?

**Comment by andris9** [comment]
Nodemailer v3 has updated iCal support. See the docs [here](https://nodemailer.com/message/calendar-events/)
