### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by cyberjoac** [nodemailer/nodemailer#717]
Hi, how would you go for integration testing with nodemailer? 
I'm trying to see if a mail was sent as part of internal business logic of our app (not from an API call).

Is there a way to keep a buffer of sent mails on the object somehow ? 
Do you know of any alternative that could do just that ? 

Thanks

**Comment by andris9** [comment]
I guess that using a custom transport or mocking would be the best way for it. See for example this module: https://github.com/bcoe/nodemailer-mock-transport
