### ISSUE TITLE
nodemailer@3 does not run in Node@4 which is still in active LTS

### ISSUE THREAD

**Issue by gr2m** [nodemailer/nodemailer#720]
See a failing build here:
https://travis-ci.org/hoodiehq/hoodie-account-server/builds/196892793#L190

I just wonder if that was intentional? If yes, could you maybe amend the [changelog](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md) saying that you dropped support for Node 4? Were there any other breaking changes?

**Comment by kyrylkov** [comment]
@gr2m Yes it was.  See `package.json` 

    "engines": {
      "node": ">=6.0.0"
    }

**Comment by andris9** [comment]
I updated the [CHANGELOG](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md#v300-2017-01-31) to reflect the changes in v3. Node.js v4 is mostly not supported because of missing support or `Array.includes` and also the spread operator, probably some other things as well.
