### ISSUE TITLE
Incompatible with GPL code

### ISSUE THREAD

**Issue by spinda** [nodemailer/nodemailer#721]
I understand the switch to copyleft, but the EU's own website explicitly lists GPL licenses as incompatible, despite what the README on this project says:

https://joinup.ec.europa.eu/software/page/eupl/eupl-compatible-open-source-licences

Dual-licensing under the EUPL and GPL, with the option to choose either, would be helpful. Otherwise Nodemailer is incompatible with the majority of other copyleft code. 

I've seen language like this used to do dual-licensing in other projects:

> Licensed under either of
>
> - European Union Public License 1.1 (LICENSE-EUPL or http://ec.europa.eu/idabc/eupl.html)
> - GNU General Public License, version 2 (LICENSE-GPL or https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)
>
> at your option.

(note: not a lawyer, this is not "legal advice", blah blah)

*(Nodemailer Version: v3.0.0, Node.js Version: Any, Operating System: Any, Nodemailer Configuration Settings: Any)*

**Comment by andris9** [comment]
EUPL is one-way compatible with GPLv2. Eg. you can't include GPL code in an EUPL project (that's what the matrix is about in your link) though you can include EUPL code in a GPL project (this is covered by article 5 of EUPL). Nodemailer does not include any GPL licensed code so it should be OK

**Comment by spinda** [comment]
What about GPLv3?

> The GPLv3 is NOT included in the EUPL downstream compatibility list (Appendix of the EUPL). However, it is "legally possible" (without prejudice of a need for it, or not!) to distribute a larger work integrating components covered by the EUPL and by the GPLv3. For this, you may use the "CeCILL roundabout":
> 1) publish your own specific contribution under CeCILL, or find convenient code covered by CeCILL;
> 2) combine with the EUPL component and publish the larger work under CeCILL;
> 3) add the needed GPLv3 components and publish the larger work under the GPLv3.

Having to include some random code licensed under the CeCILL just for legal reasons isn't great. As the chart mentions, a published "exception list" including the GPLv3 (and AGPL?) would also work here.

**Comment by andris9** [comment]
OK, supporting GPLv3 and AGPL seems reasonable, so I added a [FLOSS_EXCEPTIONS](https://github.com/nodemailer/nodemailer/blob/master/FLOSS_EXCEPTIONS.md) file to cover these licenses.

**Comment by spinda** [comment]
Thank you!
