### ISSUE TITLE
Documentation update - use strict and proper callback

### ISSUE THREAD

**Issue by JamesWClark** [nodemailer/nodemailer#724]
There is a code example on [the about page](https://nodemailer.com/about/) that does not include `"use strict";` but is written in strict mode. 

More importantly, the demo code has an improperly written callback function. It should be corrected to the following where the `function` keyword was missing.

	// send mail with defined transport object
	transporter.sendMail(mailOptions, function(error, info) {
		if (error) {
			return console.log(error);
		}
		console.log('Message %s sent: %s', info.messageId, info.response);
	});

**Comment by andris9** [comment]
Thanks! Somehow missed the invalid function call

**Comment by JamesWClark** [comment]
I am looking at the page right now and I don't see the fix. Maybe you will build it later on a build schedule.

https://nodemailer.com/about/

**Comment by andris9** [comment]
It should be fixed. I didn't use the `function(){}` syntax but `() => {}` syntax. If you don't see it, then refresh the page.

**Comment by JamesWClark** [comment]
Oops - my bad-  you totally did. Thanks for your work on Nodemailer. I find it useful.
