### ISSUE TITLE
what's email severs be support ?

### ISSUE THREAD

**Issue by kennyNing** [nodemailer/nodemailer#725]
i'm in china can i use it ?

and when i install  is error :  npm WARN node-js-getting-started@1.0.0 No repository field.  why?

**Comment by andris9** [comment]
In general Nodemailer should work with any SMTP server. I have tested Nodemailer previously with QQ SMTP and it worked. I can't test it anymore as my test account seems to have SMTP turned off and I'm not able to verify the account again

**Comment by kennyNing** [comment]
and when i install is error : npm WARN node-js-getting-started@1.0.0 No repository field. why?

**Comment by andris9** [comment]
Nothing to do with nodemailer. Your package.json does not have repository field set

**Comment by kennyNing** [comment]
You mean I can use  nodemailer now? the error is just for  field set package.json?

**Comment by andris9** [comment]
Yes, these warning are not related to Nodemailer in any way. You can use the latest Nodemailer if you have Nodejs v6+. For older Node.js versions (down to 0.10) use an older version of Nodemailer like this

    npm install nodemailer@2.7.2

**Comment by kennyNing** [comment]
![image](https://cloud.githubusercontent.com/assets/12521884/22643200/74d7929a-ec98-11e6-94cf-cd0fc2954aea.png)

can‘t pass strict mode

**Comment by andris9** [comment]
Are you using nodejs6 or later? See my last comment

**Comment by kennyNing** [comment]
my nodejs is v6.9.1

**Comment by andris9** [comment]
This error only happens in Nodejs 0.10 and 0.12. Double check how you start your app

**Comment by kennyNing** [comment]
![image](https://cloud.githubusercontent.com/assets/12521884/22677678/806a6a64-ed2f-11e6-9a8f-7164eeb807c1.png)

some where is wrong?

my code
![image](https://cloud.githubusercontent.com/assets/12521884/22677703/b0df5e5c-ed2f-11e6-9ec4-540f3ff84ebc.png)

**Comment by kennyNing** [comment]
is ok ths!
