### ISSUE TITLE
Nodemailer Defaults AUTH mechanism to 'PLAIN', impossible to connect to open SMTP relay with no AUTH mechanism

### ISSUE THREAD

**Issue by tsexton6689** [nodemailer/nodemailer#726]
Include the following information with your issue:

1. Nodemailer version: 3.0.2
2. Node 6.0
3. Ubuntu (built on docker node image)
4. I tried a lot of different config settings and used the following transport     "transports": [{
      "host": "custom-smtp-host",
      "port": 25,
      "secure":false
    }]
5. This would only be possible to verify if you set up a custom SMTP server with no AUTH mechanism and then tried to connect, it should error every time.  (I am able to use gmail but not this custom server so I have verified that my setup is correct from that standpoint)

**Comment by andris9** [comment]
Could you try to check what is the output of this test script and paste it here:

```javascript
'use strict'
const nodemailer = require('nodemailer');
let transporter = nodemailer.createTransport({
    host: 'custom-smtp-host',
    port: 25,
    logger: true,
    debug: true
});
transporter.sendMail({
    from: 'from@address',
    to: 'to@address',
    subject: 'test message',
    text: 'test body'
});
```

Modify the options to reflect your own confuguration. The script should print full SMTP transaction to console, this should show what is going on.

**Comment by tsexton6689** [comment]
Found out it was a server setup issue, this wasn't a nodemailer issue; thanks for responding so quickly.  This works as designed and doesn't require Auth when it is not set.
