### ISSUE TITLE
Attachments not working with Mandrill Transport

### ISSUE THREAD

**Issue by kevincolten** [nodemailer/nodemailer#727]
There is a [known issue](https://github.com/Rebelmail/nodemailer-mandrill-transport/issues/35) with a fix apparently in the works, but attachments will not send if just using https://github.com/Rebelmail/nodemailer-mandrill-transport. You can switch to the SMTP method for now
```js
var nodemailer = require('nodemailer');
var transport = nodemailer.createTransport({
  service: 'Mandrill',
  auth: {
    user: process.env.MANDRILL_API_USER,
    pass: process.env.MANDRILL_API_KEY
  }
});
transport.sendMail({
  from: 'example@hello.com',
  to: 'example@hello.com',
  subject: 'Some Subject',
  attachments: [ { path: 'path/to/file' } ]
}, (err, response) => {
  console.log(err, response);
});
```

**Comment by andris9** [comment]
Good to know. I'll close this issue though as it does not seem to require anything from Nodemailers side
