### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by gduggirala** [nodemailer/nodemailer#729]
Include the following information with your issue:

1. Nodemailer version you are having problems with (eg. v1.3.7): 3.0.2
2. Node.js version you are using (run `node -v` to see it, eg v5.5.0) 4.6.2
3. Your operating system (eg. Windows 10, Ubuntu 14.04 etc.) Linux Mint
4. Nodemailer configuration settings: Using AWS SES
5. If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)
Tried using it with Meteor 1.2.1. Following is the code.
var nodemailer = Npm.require('nodemailer');
var ses = Npm.require('nodemailer-ses-transport');

If you are having problems with Gmail, then make sure you have read this post before filing your issue: <https://nodemailer.com/usage/using-gmail/>

**Comment by andris9** [comment]
Nodemailer v3 requires at least Nodejs v6.0.0. For older versions of Node use the legacy version of Nodemailer, see docs and installation instructions [here](https://community.nodemailer.com/).
