### ISSUE TITLE
Allow default logging without bunyan-like styling

### ISSUE THREAD

**Issue by nboxhallburnett** [nodemailer/nodemailer#730]
In a project I am working on which makes use of nodemailer, we use a custom logger (other than bunyan) which overrides console[log/warn/error/etc], and the default logging with nodemailer effectively doubles the width of the status section of the logs making it much harder to read.

It would therefore be useful if there were an option to allow logging directly to the standard console without the bunyan-like formatting, specifically the data stored in `message` here, before the split:
https://github.com/nodemailer/nodemailer/blob/ef202df0fcdd3b12736e4200cc18394f05eb07d0/lib/shared/index.js#L366

Env:
Nodemailer version: 3.1.3
Node.js version: 6.9.5
OS: Mac OS X 10.12.2

**Comment by andris9** [comment]
You can create your own custom logging wrapper the same way [createDefaultLogger](https://github.com/nodemailer/nodemailer/blob/ef202df0fcdd3b12736e4200cc18394f05eb07d0/lib/shared/index.js#L330-L381) works and pass it to Nodemailer as the logger instance. Nodemailer follows the bunyan formatting but that's where the relation ends.
