### ISSUE TITLE
Latest version gives an error at compile time.

### ISSUE THREAD

**Issue by samaystops4no1** [nodemailer/nodemailer#731]
The latest version of nodemailer does not run and throws an error at compile time. 
The code crashes at the require statement for nodemailer. I am attaching the screenshot of the error.

Node mailer version= 3.1.3
Node.js version =4.5.0
Operating system= windows 10

![error](https://cloud.githubusercontent.com/assets/16047986/23213015/5710145a-f92f-11e6-89c3-86647a133d71.png)

**Comment by andris9** [comment]
Nodemailer starting from v3.0.0 requires at least Node.js v6.0.0. For older versions of Node use the legacy version of Nodemailer, v2.7.2
