### ISSUE TITLE
Support online.net as a "well-known" service

### ISSUE THREAD

**Issue by Clotoo** [nodemailer/nodemailer#733]
Hello,

could you add support for Online.net as a "well-known" service in your module ?
docs: [https://documentation.online.net/en/web/web-hosting/email-management/consult-email](https://documentation.online.net/en/web/web-hosting/email-management/consult-email)

I got it working with two different sets of parameters :
```
{
	host: 'smtp.online.net',
	port: 465,
	secure: true,
	auth: { user: process.env.ONLINE_MAIL_LOGIN, pass: process.env.ONLINE_MAIL_PASS },
}
```
or
```
{
	host: 'smtp.online.net',
	port: 587,
	secure: false,
	auth: { user: process.env.ONLINE_MAIL_LOGIN, pass: process.env.ONLINE_MAIL_PASS },
}
```

Thanks

**Comment by andris9** [comment]
To add a new service, create a pull request against [nodemailer-wellknown](https://github.com/nodemailer/nodemailer-wellknown) repository with the update.
