### ISSUE TITLE
Tls.connect is not function 

### ISSUE THREAD

**Issue by amir-ardalanuk** [nodemailer/nodemailer#738]
we try to send email with this package but get this error in console
node Version : v6.10.0

**Comment by andris9** [comment]
These kind of issues are usually related to your environment. If you think this is a bug in Nodemailer then try to come up with a minimal standalone testcase, try it out in different servers and if it really is a bug, then make an issue for it here. For now I don't believe this has anything to do with Nodemailer.

**Comment by amir-ardalanuk** [comment]
we check in localhost and real server but have error again 
TypeError: tls.connect is not a function
    at SMTPConnection.connect (bundle.js:39808)
    at getSocket (bundle.js:42132)
    at setImmediate (bundle.js:41872)
    at run (bundle.js:43100)
    at runIfPresent (bundle.js:43129)
    at onGlobalMessage (bundle.js:43169)
bundle.js:31060 Error occurred
bundle.js:31061 tls.connect is not a function

**Comment by andris9** [comment]
You are running Nodemailer from some kind of a bundler. This does not seem correct usage. Nodemailer should be used standalone and server side

**Comment by amir-ardalanuk** [comment]
i use browserify for require have error

**Comment by andris9** [comment]
Nodemailer is a server-side component, you can't use it in front-end environment. This is why Tls.connect gives you an error – there is no tls module in front-end.
