### ISSUE TITLE
typos in the the SES transport documentation

### ISSUE THREAD

**Issue by midnightcodr** [nodemailer/nodemailer#739]
I can't find a place to report the problem with the documentation on https://nodemailer.com/transports/ses/ so I came here. In the code example,
```
// Push next messages to Nodemailer
transport.on('idle', () => {
    while (transport.isIdle()) {
        transports.sendMail(...);
    }
});
```

should really be

```
// Push next messages to Nodemailer
transporter.on('idle', () => {
    while (transporter.isIdle()) {
        transporter.sendMail(...);
    }
});
```

Please update the doc so fewer people are confused. Thanks.

Include the following information with your issue:

1. Nodemailer version you are having problems with (eg. v1.3.7)
@3.1.4
2. Node.js version you are using (run `node -v` to see it, eg v5.5.0)
v6.9.2
3. Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
Mac OSX El Capitan
4. Nodemailer configuration settings
5. If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)

If you are having problems with Gmail, then make sure you have read this post before filing your issue: <https://nodemailer.com/usage/using-gmail/>

**Comment by andris9** [comment]
Thanks for pointing this out. I updated the text on SES docs.
