### ISSUE TITLE
nodemailer error 

### ISSUE THREAD

**Issue by tddamith** [nodemailer/nodemailer#740]
Include the following information with a issue: Run in my nod js APP

path\node_modules\nodemailer\lib\mailer\index.js:31
            compile: [(...args) => this._convertDataImages(...args)]..

index.js

  this._defaultPlugins = {
            compile: [(...args) => this._convertDataImages(...args)],
            stream: []
        };

**Comment by andris9** [comment]
So whats the error? Code seems ok to me

**Comment by tddamith** [comment]
error occur in this line 
compile: [(...args) => this._convertDataImages(...args)]

**Comment by andris9** [comment]
what error is it? the line seems OK

**Comment by andris9** [comment]
Most probably you having issues with unsupported Nodejs version. You should have at least Node js v6.0.0
