### ISSUE TITLE
Can you provide an example using NTLM (with SASL) for the 3.0+ versions?

### ISSUE THREAD

**Issue by navarroaxel** [nodemailer/nodemailer#747]
Can you provide an example using NTLM (with SASL) for the 3.0+ versions? I made some research but I can't find something useful. Thanks in advance.

1. Nodemailer version you are having problems with (eg. v1.3.7)
3.1.7
2. Node.js version you are using (run `node -v` to see it, eg v5.5.0)
6.10.0
3. Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
N/A
4. Nodemailer configuration settings
name, host, user and pass (works on 2.7.2)

**Comment by andris9** [comment]
NTLM is not supported by Nodemailer v3, see [migration guide](https://nodemailer.com/about/migrate/). So far I have decided that if commercial customers require this, then I would re-add support, otherwise it would not be worth the effort.

**Comment by navarroaxel** [comment]
I read the docs before send this issue. But I can't find a good example about how to plug the SASL interface in my own code.
