### ISSUE TITLE
Nodemailer ETIMEDOUT when trying to send mail (OUTLOOK) 

### ISSUE THREAD

**Issue by cathalgrant** [nodemailer/nodemailer#749]
1) Nodemailer version: 3.1.7
2) Node.js version: 7.1.0
3) OS: OSX 10.11.6 
4) Nodemailer configuration: 

```
var transporter = nodemailer.createTransport({

    host: "smtp-mail.outlook.com", // hostname
    secureConnection: false, // TLS requires secureConnection to be false
    port: 587, // port for secure SMTP
    auth: {
        user: 'myuser@outlook.com',
        pass: 'mypass'
    },
    tls: {
        ciphers:'SSLv3'
    },
    logger: true,
    debug: true
});

var mailOptions = {
    from: 'myuser@outlook.com', // sender address
    to: 'anotheruser@hotmail.co.uk', // list of receivers
    subject: 'Test Email', // Subject line
    text: 'Hello world ?' // plain text body
};

transporter.sendMail(mailOptions, function(error, info) {

    if(error){
        console.log('error sending email: ' + error);
    } else {
        console.log('email sent' + info.response);
    }
});
```
I have also tried configuring the transporter using only `service: "hotmail"` and the above 'auth' configuration (removing secureConnection, port and tls), however I receive the same error.

Here is the debug/log:

```
[2017-03-19 21:01:29] DEBUG Creating transport: nodemailer (3.1.7; +https://nodemailer.com/; SMTP/3.1.7[client:3.1.7])
[2017-03-19 21:01:34] DEBUG Sending mail using SMTP/3.1.7[client:3.1.7]
[2017-03-19 21:01:38] DEBUG Sending mail using SMTP/3.1.7[client:3.1.7]
[2017-03-19 21:02:57] ERROR [idfiQwoN5xM] connect ETIMEDOUT 65.55.163.152:587
[2017-03-19 21:02:57] DEBUG [idfiQwoN5xM] Closing connection to the server using "destroy"
[2017-03-19 21:02:57] ERROR Send Error: connect ETIMEDOUT 65.55.163.152:587
error sending email: Error: connect ETIMEDOUT 65.55.163.152:587
[2017-03-19 21:03:00] ERROR [1cpzp3ys2wI] connect ETIMEDOUT 65.55.163.152:587
[2017-03-19 21:03:00] DEBUG [1cpzp3ys2wI] Closing connection to the server using "destroy"
[2017-03-19 21:03:00] ERROR Send Error: connect ETIMEDOUT 65.55.163.152:587
error sending email: Error: connect ETIMEDOUT 65.55.163.152:587
```

Also I should add that I tried `openssl s_client -crlf -connect smtp.outlook.com:587` from the terminal and received the following:

```
connect: Operation timed out
connect:errno=60
```

However I was able to ping smtp.outlook.com no problem.

Any ideas what the issue could be? 

Cheers!

**Comment by andris9** [comment]
This is most commonly a firewall issue where you can't make connections to port 587. Check your firewall settings.

**Comment by cathalgrant** [comment]
Thank you for the reply!

However I don't believe this to be the issue as my firewall is disabled and I am still receiving the error. Are there any other reasons for receiving this error?

Thanks

**Comment by gvzq** [comment]
@cathalgrant  I believe this is in part from Microsoft as they usually try to validate the login with a text nowadays. @andris9  Do you have any work around that?

**Comment by andris9** [comment]
If you get timeout errors when connecting to specific port then it's a firewall issue in 99,99% of cases. There might not be a firewall in yout machine but there might be one in your network. For example it is not possible to use port 587 from Google Cloud Engine.

**Comment by evroza** [comment]
I've got the same error. My firewall is disabled

**Comment by AlphaRipo** [comment]
var transporter = nodemailer.createTransport({
            host: "smtp-mail.outlook.com", // hostname
            secureConnection: false, // TLS requires secureConnection to be false
            port: 587, // port for secure SMTP
            tls: {
               ciphers:'SSLv3'
            },
            requireTLS:true,//this parameter solved problem for me
            auth: {
                user: 'yourmail@outlook.com',
                pass: 'yourpassword'
            }
        });

**Comment by aruna-h** [comment]
Error: connect ETIMEDOUT 40.101.92.18:587
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ESOCKET',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '40.101.92.18',
  port: 587,
  command: 'CONN' }

**Comment by Anwar0902** [comment]
I am getting the same error, again and again, please help.
{ Error: connect ETIMEDOUT 74.125.200.109:465
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ETIMEDOUT',
  code: 'ESOCKET',
  syscall: 'connect',
  address: '74.125.200.109',
  port: 465,
  command: 'CONN' }

**Comment by indikatiron** [comment]
This may be firewall problem. I faced similar problem in Ubuntu (Digital Ocean server). Tried to fix the issue for 3 days, tried using auth2 also, tried with inactive firewall using ufw inactive command, but no luck. Finally I checked Digital Ocean admin panel and created firewall for the droplet. Problem solved by enabling TCP inbound and outbound in firewall settings.

**Comment by vigneshsivamani2206** [comment]
see nodemailer's official guide:
https://community.nodemailer.com/using-gmail/

it worked for me too:
https://www.google.com/settings/security/lesssecureapps
go to the above link and enable less secure apps

https://accounts.google.com/b/0/displayunlockcaptcha
go to the above link to disable captcha temporarily for new device signin

**Comment by trinityimma** [comment]
> Error: connect ETIMEDOUT 40.101.92.18:587
> at Object._errnoException (util.js:1022:11)
> at _exceptionWithHostPort (util.js:1044:20)
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
> code: 'ESOCKET',
> errno: 'ETIMEDOUT',
> syscall: 'connect',
> address: '40.101.92.18',
> port: 587,
> command: 'CONN' }
> hi i am getting it during nodemailer testing so how can i resolve this


Hi @aruna-h  and @Anwar0902 
This is due to the fact that you are trying to send it from the localhost.

Add  the following line of code after auth option 
 tls:{
            rejectUnauthorized:false
        }

**Comment by rakeshtt92** [comment]
I've got the same error, **This works for me**

try {
        var transporter = nodemailer.createTransport({
            service: 'gmail',
            port:465,
            secure: true, // true for 465, false for other ports
            logger: true,
            debug: true,
            secureConnection: false,
            auth: {
                user: 'example@gmail.com', // generated ethereal user
                pass: '*******', // generated ethereal password
            },
            tls:{
                rejectUnAuthorized:true
            }
        });

        var info = await transporter.sendMail({
            from: 'test@gmail.com', // sender address
            to: "test1@gmail.com", // list of receivers
            subject: "Registration Successful", // Subject line
            text: "Registration Successful", // plain text body
            html: output, // html body
    });
    }
   catch(error) {
            console.log(error)
   }

**Comment by developerdesigner18** [comment]
> This may be firewall problem. I faced similar problem in Ubuntu (Digital Ocean server). Tried to fix the issue for 3 days, tried using auth2 also, tried with inactive firewall using ufw inactive command, but no luck. Finally I checked Digital Ocean admin panel and created firewall for the droplet. Problem solved by enabling TCP inbound and outbound in firewall settings.

What did you set in inbound and outbound?

**Comment by f-w** [comment]
@andris9, my smtp host resolves to multiple ip addresses. If one ip gave ETIMEDOUT error (or any TCP/IP socket level error for that matter), does nodemailer retry on another ip - a feature known as [client-retry](https://blog.engelke.com/tag/browser-retry/), which is supported by many browsers for HTTP requests?

**Comment by Rinku2002** [comment]
I'm getting same error even after I tried all the above

**Comment by Riaz5687** [comment]
i have tried all the above solution, but unfortunately did not work with me any of them. i am getting the following debug info

[2023-02-22 06:33:51] DEBUG Creating transport: nodemailer (6.9.1; +https://nodemailer.com/; SMTP/6.9.1[client:6.9.1])
[2023-02-22 06:33:51] DEBUG Sending mail using SMTP/6.9.1[client:6.9.1]
[2023-02-22 06:34:22] DEBUG [Fpu6xenDf3Y] Resolved smtp.office365.com as 52.98.95.210 [cache miss]
[2023-02-22 06:35:37] ERROR [Fpu6xenDf3Y] connect ETIMEDOUT 52.98.95.210:587
[2023-02-22 06:35:37] DEBUG [Fpu6xenDf3Y] Closing connection to the server using "destroy"
[2023-02-22 06:35:37] ERROR Send Error: connect ETIMEDOUT 52.98.95.210:587

i am using "nodemailer": "^6.9.1",
nodejs v16.15.1

and outlook 365 for sending email

**Comment by Sagacious247** [comment]
i have tried the above solutions but is not working for me.
this is the result am getting.

Error: connect ETIMEDOUT 95.216.108.161:587
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -4039,
  code: 'ESOCKET',
  syscall: 'connect',
  address: '95.216.108.161',
  port: 587,
  command: 'CONN'

**Comment by rishi-bathija** [comment]
const nodemailer = require("nodemailer");
const mailSender = async (email, title, body) => {
    try {
        let transporter = nodemailer.createTransport({
            host: 'smtp.gmail.com',
            port: 587,
            secure: false,
            auth: {
                user: 'hardcoded-email',
                pass: 'hardcoded-password',
            }
        })

        let info = await transporter.sendMail({
            from: 'StudyNotion',
            to: `${email}`,
            subject: `${title}`,
            html: `${body}`,
        })
        console.log("Info", info);
        return info;
    } catch (error) {
        console.log(error.message);
        throw error;
    }
}

module.exports = mailSender;

Error: connect ETIMEDOUT 142.251.12.109:587
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -4039,
  code: 'ESOCKET',
  syscall: 'connect',
  address: '142.251.12.109',
  port: 587,
  command: 'CONN'
}

I am also getting the same error. Tried so many things to get resolve it but can't get rid of it. Someone please provide any solution to this.

**Comment by muratkorkmazz** [comment]
> I am getting the same error, again and again, please help. { Error: connect ETIMEDOUT 74.125.200.109:465 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14) errno: 'ETIMEDOUT', code: 'ESOCKET', syscall: 'connect', address: '74.125.200.109', port: 465, command: 'CONN' }
> 
> I also disabled my windows firewall and also allow the less protected app in my google account but didn't work. pls help

Could you solve it ? I have been getting same error and need help...

**Comment by coderomm** [comment]
I am doing following this , tried all different smtps, sandboxes, pinged everthing, It stopss working when i make a post req to below. 

Pls help: Its been 1 week now


const express = require('express');
const bodyParser = require('body-parser');
const nodemailer = require('nodemailer');

const app = express();
const PORT = process.env.PORT || 5000;

app.use(bodyParser.json());

app.post('/send-email', async (req, res) => {
    try {
        const transport = nodemailer.createTransport({
            service: 'gmail',
            port: 587,
            secure: false,
            auth: {
                user: 'mail.coderom11@gmail.com',
                pass: 'xxxx zzzz cccc vvvv',
            },
            tls: {
                rejectUnauthorized: false
            },
            logger: true,
            debug: true,
        });
        const mailOptions = {
            from: 'mail.coderom11@gmail.com',
            to: 'omopyt2020@gmail.com',
            subject: 'Test Email',
            text: 'This is a test email sent from our Node.js app using the Gmail API.',
        };

        const result = await transport.sendMail(mailOptions);
        console.log('result:', result)
        res.status(200).send(result);
    } catch (error) {
        res.status(500).send(error.toString());
    }
});

app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});

**Comment by kluivstar** [comment]
> I am doing following this , tried all different smtps, sandboxes, pinged everthing, It stopss working when i make a post req to below.
> 
> Pls help: Its been 1 week now
> 
> const express = require('express'); const bodyParser = require('body-parser'); const nodemailer = require('nodemailer');
> 
> const app = express(); const PORT = process.env.PORT || 5000;
> 
> app.use(bodyParser.json());
> 
> app.post('/send-email', async (req, res) => { try { const transport = nodemailer.createTransport({ service: 'gmail', port: 587, secure: false, auth: { user: '[mail.coderom11@gmail.com](mailto:mail.coderom11@gmail.com)', pass: 'xxxx zzzz cccc vvvv', }, tls: { rejectUnauthorized: false }, logger: true, debug: true, }); const mailOptions = { from: '[mail.coderom11@gmail.com](mailto:mail.coderom11@gmail.com)', to: '[omopyt2020@gmail.com](mailto:omopyt2020@gmail.com)', subject: 'Test Email', text: 'This is a test email sent from our Node.js app using the Gmail API.', };
> 
> ```
>     const result = await transport.sendMail(mailOptions);
>     console.log('result:', result)
>     res.status(200).send(result);
> } catch (error) {
>     res.status(500).send(error.toString());
> }
> ```
> 
> });
> 
> app.listen(PORT, () => { console.log(`Server running on port ${PORT}`); });

Any luck?

**Comment by chandrashekhar-patil** [comment]
You can try third party software using nodemailer mailtrap and is working.

**Comment by coderomm** [comment]
> > I am doing following this , tried all different smtps, sandboxes, pinged everthing, It stopss working when i make a post req to below.
> > Pls help: Its been 1 week now
> > const express = require('express'); const bodyParser = require('body-parser'); const nodemailer = require('nodemailer');
> > const app = express(); const PORT = process.env.PORT || 5000;
> > app.use(bodyParser.json());
> > app.post('/send-email', async (req, res) => { try { const transport = nodemailer.createTransport({ service: 'gmail', port: 587, secure: false, auth: { user: '[mail.coderom11@gmail.com](mailto:mail.coderom11@gmail.com)', pass: 'xxxx zzzz cccc vvvv', }, tls: { rejectUnauthorized: false }, logger: true, debug: true, }); const mailOptions = { from: '[mail.coderom11@gmail.com](mailto:mail.coderom11@gmail.com)', to: '[omopyt2020@gmail.com](mailto:omopyt2020@gmail.com)', subject: 'Test Email', text: 'This is a test email sent from our Node.js app using the Gmail API.', };
> > ```
> >     const result = await transport.sendMail(mailOptions);
> >     console.log('result:', result)
> >     res.status(200).send(result);
> > } catch (error) {
> >     res.status(500).send(error.toString());
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > });
> > app.listen(PORT, () => { console.log(`Server running on port ${PORT}`); });
> 
> Any luck?

Then I decided to push this and check in production, there its working asf

**Comment by Nandita-Kumari** [comment]
> I've got the same error, **This works for me**
> 
> try { var transporter = nodemailer.createTransport ({ service: 'gmail', port:465, secure: true, // true for 465, false for other ports logger: true, debug: true, secureConnection: false, auth: { user: '[example@gmail.com](mailto:example@gmail.com)', // generated ethereal user pass: '*******', // generated ethereal password }, tls: { rejectUnAuthorized:true } });
> 
> ```
>     var info = await transporter.sendMail ({
>         from: 'test@gmail.com', // sender address
>         to: "test1@gmail.com", // list of receivers
>         subject: "Registration Successful", // Subject line
>         text: "Registration Successful", // plain text body
>         html: output, // html body
>      });
> }
> ```
> 
> catch(error) { console.log(error) }

Thanks, its also works for me.
