### ISSUE TITLE
List-Unsubscribe

### ISSUE THREAD

**Issue by marcosgouvea** [nodemailer/nodemailer#750]
1. Nodemailer version  3.0.1,
2. Node.js version 6.6.0
3. Your operating system (eg. Windows 10)

im having an issue with List-Unsubscribe header
i'm attaching it all the ways i can but on the receiver e-mail it dosn't show

here is my code on header
https://gist.github.com/marcosgouvea/748626403607d871ab728486a8d28c67

here is netflix email
![netflix](https://cloud.githubusercontent.com/assets/12238079/24107573/dfc7927a-0d69-11e7-9fc5-1c301515c0a4.jpg)

this is my email test
![nodemailer](https://cloud.githubusercontent.com/assets/12238079/24107571/dfb8ed56-0d69-11e7-83e8-da477e6f76e4.jpg)

**Comment by andris9** [comment]
I don't think this feature is enabled for everybody, you need to be a sender with good reputation. http://stackoverflow.com/questions/28497332/gmail-unsubscribe-link-does-not-appear

**Comment by jmbarbier** [comment]
true for gmail/unsubscribe/reputation, but for other providers it can't work neither, list-unsubscribe headers are missing : https://github.com/nodemailer/nodemailer/issues/751
