### ISSUE TITLE
not working for bluehost webmail

### ISSUE THREAD

**Issue by cisrakesh** [nodemailer/nodemailer#756]
Include the following information with your issue:

1. Nodemailer version 3.1.4,
2. Node.js version v6.2.2
3. operating system Ubuntu 14.04
4. Nodemailer configuration settings
var transporter = nodemailer.createTransport(smtpTransport({
              host: 'box6082.bluehost.com',
              port: 465,
              secure: true,
              auth: {
                user: 'info@mydomain.com',
                pass: 'mypass'
              }
}));

 I am using nodemailer to send email. When i use my gmail credentials , it works great. But when i switch back to bluehost webemail details it doesn't works. Also it is not giving any error in that case.

With same details i have setuped phpmailer and it works there . had already contacted to bluehost and confirmed the host value.

**Comment by andris9** [comment]
Upgrade to latest version of Nodemailer

**Comment by cisrakesh** [comment]
What was the problem ?
