### ISSUE TITLE
Syntax error while requiring Nodemailer

### ISSUE THREAD

**Issue by RaimoJohanson** [nodemailer/nodemailer#757]
OS: Ubuntu 14.04.5 LTS (Cloud9 IDE)
Node: v6.10.1
NPM: 3.10.10
Nodemailer: 3.1.8

I'm having a syntax error while trying to require Nodemailer module.

`const nodemailer = require('nodemailer');`

console:
```
/home/ubuntu/workspace/node_modules/nodemailer/lib/mailer/index.js:31
compile: [(...args) => this._convertDataImages(...args)],
                       ^^^
SyntaxError: Unexpected token ...
```
Any suggestions?

**Comment by andris9** [comment]
See https://github.com/nodemailer/nodemailer/issues/754
