### ISSUE TITLE
Event( notification ) when a email message is marked as spam

### ISSUE THREAD

**Issue by sergordienko** [nodemailer/nodemailer#758]
Hello, great work, thank you very much! I wanted to ask a question, can I get an event when the recipient marked an email as spam? I saw how they do it, but I do not understand how it happens.

**Comment by andris9** [comment]
This is out of scope for Nodemailer. Instead see how [Feedback loops](https://en.wikipedia.org/wiki/Feedback_loop_(email)) work.
