### ISSUE TITLE
Website code sample error

### ISSUE THREAD

**Issue by moltar** [nodemailer/nodemailer#760]
Sorry, can't find a repo for the website, so I am adding an issue here.

On this page: https://nodemailer.com/smtp/well-known/

Example is:

```js
let transporter = nodemailer.createTransport({
     service: 'SendPulse', // no need to set host or port etc.
     auth: {
         user: 'account.email@example.com',
         password: 'smtp-password'
     }
});
```
But it should be `pass` not `password`.

**Comment by andris9** [comment]
Dang, no idea how this slipped through :S Fixed now.

**Comment by moltar** [comment]
Dang, that must have been the fastest solved issue in history of GitHub. Thanks.
