### ISSUE TITLE
Type definitions would be appreciated

### ISSUE THREAD

**Issue by bogacg** [nodemailer/nodemailer#761]
Typings seems not to exist for this project. Since Javascript tooling and IDE support gets better everyday and Typescript is a popular choice now, type definitions are huge help for developers.

**Comment by marvinhagemeister** [comment]
As a workaround there is `@types/nodemailer` available for us.

**Comment by andris9** [comment]
Yes, use @types/nodemailer. It is supported by someone else but it is as official as there is going to be

**Comment by marek-benes** [comment]
Do you plan to add TypeScript typing definitions into the package to avoid using external type definitions?

**Comment by andris9** [comment]
@marek-benes No, there are no plans for any kind of TypeScript support.
