### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by edemaine** [nodemailer/nodemailer#763]
I prepared a small fork of [nodemailer](https://github.com/edemaine/node4mailer) and [smtp-server](https://github.com/edemaine/smtp-server-node4) that work on Node 4.  Basically, I replaced the use of spread (`...`) operators with messier use of `arguments` (which often required switching from `=>` notation to `function`), and the use of `Array.includes` with a polyfill ([array-includes](https://www.npmjs.com/package/array-includes)).

The code is substantially messier, so I'm guessing this doesn't interest you, but if you'd like to support Node 4 in the main project, I'd be happy to submit a PR.  Just let me know.

**Comment by andris9** [comment]
The v2.x and previous versions of Nodemailer used Node v0.10 compatible code and I'm really glad I don't need to mess with *apply* and such for basic operations anymore :)

It took a lot of effort to clean everything up when  I did the v3 code for Nodemailer and I don't want to revert it. If you need support for older versions of Node, then use older version of Nodemailer

    npm install nodemailer@2.7.2
