### ISSUE TITLE
Zoho as well-known Services bug

### ISSUE THREAD

**Issue by elmeerr** [nodemailer/nodemailer#764]
I didn't put any of the pre-defined information because the issue is quite simple...You've created Zoho as well-know service but you're considering just `smtp.zoho.com` as SMTP. I noticed that because I was trying to use and I was only getting auth failed error. So I just set up manually: `host`, `port`, etc and everything works. 

The thing is, Zoho has at least two SMTP according to the source of your account. Mine, for example was created as an European account because I'm Belgium so my SMTP is `smtp.zoho.eu` and using `service: Zoho` doesn't work.

I didn't read the code but I think that you can use `verify` function to check all possible SMTP from Zoho if you want to keep it as well-know service or just add this information saying the `service: Zoho` only works with accounts `.com`

Kind regards.

**Comment by andris9** [comment]
There have been similar issues with other providers as well (AWS, GoDaddy). I'm rather thinking of removing such services that have multiple options available from the list and let the user themselves figure it out.
