### ISSUE TITLE
sudden ECONNRESET error (I have researched solutions, no luck).

### ISSUE THREAD

**Issue by Lahpman7** [nodemailer/nodemailer#765]
I am having an issue with NodeMailer, I began to get ECONNRESET errors (seemingly out of nowhere). I am using **gmail**, I have followed the gmail instructions, less secure etc. , but haven't had issues with it before, emails used to send out fine. Anyway, I was hoping someone could see something that I am not. Yes, I have searched and found pretty old posts with the same errors, but their solutions haven't helped. Thanks in advance! 

P.S I have tried without TLS option, and also tried a different smtp host (**easy-smtp** and **Send-Pulse via well-known services** ), same result. Here are my specs and my code below: (stack trace to follow)

**My Specs**:
Nodemailer 3.1.7
Node 7.20
Windows 10

**My Code:**
```
let transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASS
        },
        tls: {
            rejectUnauthorized: false
        }
    });

    let mailOptions = {
        from: '"Admin" <fakemail@gmail.com>', // sender address
        to: email, // list of receivers
        subject: 'Welcome !', // Subject line
        text: 'Welcome!', // plain text body
        html: modifiedHtml // html body
    };

    // send mail with defined transport object
    transporter.sendMail(mailOptions, (error, info) => {
        if (error) {
            console.trace();
            return console.log('mailer error: ' + error);
        }
        console.log('Message %s sent: %s', info.messageId, info.response);
    });
}
```
```

Trace
    at transporter.sendMail (E:\Neo4jNode\db_operations\db.js:213:21)
    at transporter.send (E:\Neo4jNode\node_modules\nodemailer\lib\mailer\index.js:187:21)
    at SMTPConnection.connection.once.err (E:\Neo4jNode\node_modules\nodemailer\lib\smtp-transport\index.js:169:24)
    at SMTPConnection.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at SMTPConnection.emit (events.js:188:7)
    at SMTPConnection._onError (E:\Neo4jNode\node_modules\nodemailer\lib\smtp-connection\index.js:547:14)
    at TLSSocket._socket.on.err (E:\Neo4jNode\node_modules\nodemailer\lib\smtp-connection\index.js:252:18)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
mailer error: Error: read ECONNRESET
```

**Comment by andris9** [comment]
This seems to be a home connection. Usually the reason is an antivirus application messing with SMTP connections as it suspects there might be a spam sending trojan in the machine.

**Comment by Lahpman7** [comment]
Thanks for the tip!
Turns out it was the connection provided by my school blocking it, had to switch to another connection.
