### ISSUE TITLE
`SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by igorkazakovaes** [nodemailer/nodemailer#766]
I  know you mentioned this is normally a version issue but I have updated everything and only have one version of node installed.

Nodemailer 3.1.8
Node.js 6.10.2
npm 3.10.10
Windows 10

package.json has dependency ("nodemailer": "^3.1.8",)

Everything works locally but upon pushing to Bluemix:

compile: [(...args) => this._convertDataImages(...args)],
at exports.runInThisContext (vm.js:53:16)
at Object.Module._extensions..js (module.js:416:10)
SyntaxError: Unexpected token ...
at Module.load (module.js:343:32)
at Object.Module._extensions..js (module.js:416:10)
at Module.require (module.js:353:17)
home/vcap/app/node_modules/nodemailer/lib/mailer/index.js:31
at require (internal/module.js:12:17)

Code:

`var nodemailer = require('nodemailer');`
`var smtpTransport = nodemailer.createTransport({`
`    service: 'gmail',`
`    auth: {`
`        user: 'USER',`
`        pass: 'PASS'`
`    }`
`});`
`var mail = {
    from: '"NAME" <EMAIL>',
    to: 'EMAIL',
    subject: 'SUBJECT',
    text: 'Text',
    html: 'Text'
};`
`smtpTransport.sendMail(mail, (error, info) => {
			if (error) {
				return console.log(error);
			}
			console.log('Message %s sent: %s', info.messageId, info.response);
		});`

Any ideas? Thanks!

**Comment by andris9** [comment]
See previous issues for the same error, ie. this one: https://github.com/nodemailer/nodemailer/issues/754

**Comment by igorkazakovaes** [comment]
Thanks andris! Had already checked that and output of process.versions is

```
{ http_parser: '2.7.0',
  node: '6.10.2',
  v8: '5.1.281.98',
  uv: '1.9.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
```

Would it be worth updating to node 7.9?

**Comment by andris9** [comment]
The only way to have syntax error for ... is when you run an older versions of Node than 6. Node 6.10.2 never throws an exception for this syntax. Recheck the versioning.
