### ISSUE TITLE
Pool rateLimit not shared across connections?

### ISSUE THREAD

**Issue by TuckerWhitehouse** [nodemailer/nodemailer#768]
Nodemailer version: 4.0.1
Node.js version: 6.3.1
Operating system: macOS 10.12.4

I cloned the existing pool test, and updated the configuration to use a longer `rateDelta` (10 seconds), a lower `rateLimit` (2) and a severely reduced number of messages (6).

The expectations was that sending would take at least `20 seconds` but the test fails and all messages are sent in about `148 ms`.

If I reduce the number of `maxConnections` to 1, the test passes.
From the documentation "This limit is shared between connections, so if one connection uses up the limit, then other connections are paused as well".

This may be by design, but my interpretation was that the number of messages sent would not exceed `rateLimit` in `rateDelta` regardless of how many connections there are.

test/smtp-pool-test.js - should send multiple mails with rate limit
https://gist.github.com/TuckerWhitehouse/5a6deabe237f18049e6a9a1640e70445

**Comment by andris9** [comment]
Rate limiting is checked _after_ a message has been sent so in your case what happens is that you have a lot more connections available than there are messages which means that before rate limiting kicks in all the messages have been already sent. If you have a lot of connections available and you insert messages to the queue simultaneously then the first batch can get over the limit. it is only after the first message has been delivered when rate limiting starts working.

**Comment by bertho-zero** [comment]
I have the same problem, on a sending of more than 2000 mails the rateLimit is respected only if the maxConnections is 1.

This config works:
```js
transport: {
  pool: true,
  host: '127.0.0.1',
  port: '1025', // Mailcatcher port
  maxMessages: Infinity,
  maxConnections: 1,
  rateLimit: 14, // 14 emails/second max
  rateDelta: 1000
}
```

And this config does not work:
```js
transport: {
  pool: true,
  host: '127.0.0.1',
  port: '1025', // Mailcatcher port
  maxMessages: Infinity,
  maxConnections: 20,
  rateLimit: 14, // 14 emails/second max
  rateDelta: 1000
}
```

**Comment by ripone07** [comment]
With all due respect, shouldn't this be documented somewhere?
Is it a bug or not?
In my opinion, this should be, at least, documented as a warning, because package users expect the limits to be respected no matter what.
I had the same issue and by chance did not release the changes in production.
[(Please see this ticket too)](https://github.com/nodemailer/nodemailer/issues/827)
