### ISSUE TITLE
Unsure of how to use transferRate

### ISSUE THREAD

**Issue by jpike88** [nodemailer/nodemailer#771]
`transporter = require('nodemailer').createTransport({
        SES: new AWS.SES({
            apiVersion: '2010-12-01'
        }),
        sendingRate: 5
    });
    `

`    transporter.on('idle', () => {
        while (transporter.isIdle()) {
            transporter.sendMail(...);
        }
    });`

What goes in sendMail? If they've been passed to the transporter, what's the point of that second block of code?

**Comment by andris9** [comment]
`createTransport` gives you an object to send mail (this is where you put authentication and connection info etc.). `transporter.sendMail` sends a single email message, this is where you put the email options (from, to, subject etc.)

**Comment by jpike88** [comment]
I don't think I was clear enough. I know how to use sendMail, but in the code examples for using the sendingRate, it includes this code snippet.

`transporter.on('idle', () => { while (transporter.isIdle()) { transporter.sendMail(...); } });`

Is this necessary for the sendingRate to kick in properly?

**Comment by andris9** [comment]
You don't need it, `isIdle` helps you to pull messages when needed instead of flooding Nodemailer (and memory), you can just as well ignore it.

**Comment by jpike88** [comment]
Documentation may need to be tweaked, the way it's presented it implies that those two code snippets go hand in hand.

Thanks for clarifying though
