### ISSUE TITLE
Attachment encoding

### ISSUE THREAD

**Issue by djlatscho** [nodemailer/nodemailer#773]
Hi,
I want to send a pdf document as attachment. When I send this attachment, I lose the encoding for the german special characters like 'ö', 'ä', 'ß' etc. When I check my document with the debugger before I send it, the characters are all fine. But in the received e-mail, the characters are wrong. The text in the `message` is correct, but the text in the document.pdf is wrong.

I am using angular 4 universal with serverside rendering.

Server-Code:
```
app.use('/sendMail', jsonParser, (req, res) => {
    console.time('sendMail');
    console.log(req);
    mailer.sendDev(<string>req.body.subject, <string>req.body.message, <string>req.body.html, req.body.attachment, true);
    console.timeEnd('sendMail');
    res.status(200);
   res.send();
});
```
Mailer-Code:
```
send(subject: string, message: string, html: string, from: string, to: string, transporter: any, attachment: any) {
        const mailOptions = {
            from: from,
            to: to,
            subject: subject,
            text: message,
            html: html,
            attachments: [{
                filename: 'document.pdf',
                content: attachment,
                contentType: 'application/pdf; charset=ISO-8859-1'
            }]
        };
        transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
                return console.log(error);
            }
            console.log('Message %s sent: %s', info.messageId, info.response);
        });
    }
```
This is my console log:

![bildschirmfoto 2017-05-05 um 11 51 33](https://cloud.githubusercontent.com/assets/5719156/25741019/3cf25c4e-3189-11e7-84ed-54e7a2ad6d5e.png)

Ad this is the screenshot from the received e-mail:

![bildschirmfoto 2017-05-05 um 11 52 40](https://cloud.githubusercontent.com/assets/5719156/25741078/733f53ba-3189-11e7-8215-079ec6d60770.png)
The first line ist the `message` and the second line is the preview from document.pdf

I am using the following versions:

1. Nodemailer version 4.1.0
2. Node.js v7.8.0
3. MacOS Sierra, Version 10.12.4
4. angular-cli 1.0.1

**Comment by andris9** [comment]
You are probably using unicode strings for the attachment payload. Use a Buffer instead, don't use unicode strings for binary data.

**Comment by djlatscho** [comment]
Thanks for your quick response. 
I changed my code like this:
`content: new Buffer(attachment, 'utf-8')`
But this doesn't solve the problem.

**Comment by andris9** [comment]
The content probably gets corrupt already before. Nodemailer passes on attachments exactly the way these are provided, no modifications are done with any of the bytes.

**Comment by djlatscho** [comment]
Thanks. I am going to continue testing on monday.
I am creating my pdf with [jsPDF](https://parall.ax/products/jspdf). Do you have any experience with sending emails with jsPDF and nodemailer?

**Comment by omeriko** [comment]
me_too :-(
https://github.com/nodemailer/nodemailer/issues/773#issuecomment-299437394
