### ISSUE TITLE
I can't send a email 

### ISSUE THREAD

**Issue by djom20** [nodemailer/nodemailer#775]
Include the following information with your issue:

1. Nodemailer version 4.0.1
2. Node.js version 6.9.1
3. Mac Sierra
4. Nodemailer configuration are the basic like in the example

I always get a login error with any account and password that I created in gmail. I have the code in [runkit](https://runkit.com/djom20/590cac3c67f45a00121c51d4) 

These are my common errors:

`Error: Invalid login: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbv0 534-5.7.14 srZ4_ZYl9EWGO8W_aqtsDyGxd6ugLVx4b92_pCcgNNOMOAB11e97uqTpM4gvKmvTv-Tmav 534-5.7.14 m98eoGO2q2AZViOA-EfeLzyyIiL1sJiZSY4cifu4egw0aZWq6uIUu3A1-g4Qrq08RcTzOq 534-5.7.14 rKziEUCkxSKbgchu_U21EMNd5ej3DRLdzTuxtfXwccbbYKcboHrJtJT8un86mLoTfdmzfu 534-5.7.14 EX7HeMQcio0MQ7R3MC616-CfHvyXA> Please log in via your web browser and 534-5.7.14 then try again. 534-5.7.14 Learn more at 534 5.7.14 https://support.google.com/mail/answer/78754 p13sm10951911pfl.4 - gsmtp`

Or 

`Error: Invalid sender "testsnodemailer@gmail.com>"`

**Comment by panorart** [comment]
ME TOO. It used to work couple month ago

**Comment by panorart** [comment]
@djom20 I just find out where's the problem. please visit : https://nodemailer.com/usage/using-gmail/ , there is a “Captcha Enable” challenge mentioned on the page that you need to complete. And after that, it works like a charm. Also make sure to enable "less secure" app

**Comment by djom20** [comment]
Hi,

I found the solution with this code:

`nodemailer.createTransport('smtps://username%40gmail.password$@smtp.gmail.com');`

And thanks @panorart for your comment.
