### ISSUE TITLE
AWS SES mail regard as spam but not test mail

### ISSUE THREAD

**Issue by EasonWang01** [nodemailer/nodemailer#778]
```
const nodemailer = require('nodemailer');
var ses = require('nodemailer-ses-transport');
exports.sendMail = (data) => {
    var transporter = nodemailer.createTransport(ses({
    accessKeyId: '.....',
    secretAccessKey: '...',
    region: 'us-west-2',
    amazone:'email.us-west-2.amazonaws.com'
}));
```

When I click the Send test mail button to send mail on AWS SES website it works good , but if I send mail using nodemailer it will regard as spam.(same From and To)

I have set the SPF and DKIM,what will cause this problem?

**Comment by andris9** [comment]
Spam detection is specific to every recipient. For example, the recipient MX might check the Received: headers in the message and finds your server IP suspicious etc. There's nothing Nodemailer or any other mail sending library can do to help, you have to find out the cause yourself.
