### ISSUE TITLE
How to: 2LO authentication

### ISSUE THREAD

**Issue by mrceperka** [nodemailer/nodemailer#779]
Hello,
I have followed an guide at https://nodemailer.com/smtp/oauth2/#oauth-2lo.
I have created service account at Google and obtained `.json` file with credentials.

My setup looks like this:
```js
  const nodemailer = require("nodemailer");
  const pk = require("./pk.json");
  const mailer =  {
    service: "gmail",
    auth: {
      type: "OAuth2",
      user: pk.client_email,
      serviceClient: pk.client_id,
      privateKey: pk.private_key
    }
  }

const transporter = nodemailer.createTransport(mailer);
transporter.sendMail({/* something */});
```
When I try to send email, I got following error: 
```
535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials
```

Could you point me to the right direction? What am I missing here?

Thanks

**Comment by andris9** [comment]
In most cases this means you have not granted Gmail scope to your OAuth application. SMTP requirest full Gmail access, not just a sending scope or something more granular.

**Comment by jrogozen** [comment]
I can't figure out how to grant Gmail scope for a service account. The service account has full owner permissions and the gmail api is enabled in the api control center. All the related scope access seems to be catered towards non service account keys.

**Comment by wdetac** [comment]
I have grant all scope but still face the same problem. Please include some documents for how to grant those scope if you think I am wrong.

**Comment by ayushnawani** [comment]
@mrceperka  did you get the solution for this?

**Comment by mrceperka** [comment]
@ayushnawani I think I did not. I've probably used some "less secure" method. But It was some time ago, I am not really sure. Sorry :(
