### ISSUE TITLE
How to send mail from default instead of SMTP

### ISSUE THREAD

**Issue by ashrafmangalore** [nodemailer/nodemailer#796]
Hi, I am using nodemailer for node.js express app.
In my nodemailer code:
        
    const transporter = nodemailer.createTransport({
           service: 'gmail',
           host: 'smtp.gmail.com',
           auth: {
                     user: 'myemail',
                     pass: 'mypassword'
           }
    });

here instead above configuration I want to send from default server. I mean I dont want to send from my email. like something default i want send.. I want to send like **noreply@mail.com**. 
Can you please tell me how can I do.

**Comment by andris9** [comment]
Use the [sendmail transport](https://nodemailer.com/transports/sendmail/). This works exactly the same way as the `mail()` command in PHP works, it generates an email and passes it to sendmail for delivery.

**Comment by ashrafmangalore** [comment]
I am using AWS server. will that option work in aws server also?
