### ISSUE TITLE
Build with Babel

### ISSUE THREAD

**Issue by Phyks** [nodemailer/nodemailer#797]
Hi,

In [a project](https://framagit.org/bnjbvr/kresus/) we are using `nodemailer` to make the backend emails to the user. Recently, `nodemailer` required Node >= 6.0, by using the spread operator, and deprecated all previous versions.

We are then reviewing upgrading to the latest `nodemailer` version. Our problem is that a vast majority of our userbase is running Debian stable, which is only offering [Node 4](https://packages.debian.org/stretch/nodejs). It seems that this version is going to stick in Debian for a while, as Node 6 is only available in `unstable` (Sid).

I know there are many ways to get a more up to date version of Node in Debian, by using other sources or package repositories, but most of these solutions can be either complicated or not working on any hardware (typically ARM for a Raspberry Pi). Then, being able to run `nodemailer` directly out of the box with the Node version available in Debian stable would be super useful, in my humble opinion.

As the dependency on Node >= 6 only rely on the use of the spread operator, it seems quite easy to run the codebase through Babel, to make it compatible with Node 4 as well, which would be truly awesome. This is even more useful as it is quite difficult to do in a clean way on the project side.

I am aware of at least [one fork out there which implemented it](https://github.com/reactioncommerce/nodemailer) but this one is a few versions off for the moment, and is not really official.

Thanks a lot for all the work you are putting in `nodemailer`!

**Comment by andris9** [comment]
deprecating older versions of Nodemailer means that I do not support these anymore. This doesn't mean that you could not use these or that these would be broken. I think the latest MIT licensed version of Nodemailer that supported Node v4 was nodemailer@2.7.2

**Comment by Phyks** [comment]
Hi,

> This doesn't mean that you could not use these or that these would be broken.

I beg to disagree on this. It also means missing quite a bunch of new features (sendmail for instance), bug fixes as well as (most important) security updates. Especially since the mail stack is a particularly sensitive one. 



Concerning the support of Node v4, it seems the only compatibility breaking throughout the code is the use of the spread operator, which is basically syntactic sugar. I totally get why you would want to use it, but it seems to me that compiling code with Babel would allow using such syntactic sugar and supporting older Node version as well. As far as I understood, there is actually not really a need for any polyfills. 

Additionally, Node v4 is still supported as a LTS, and is not already deprecated on the Node side. 

Thanks,

**Comment by andris9** [comment]
The current Nodemailer does not give too many features compared to the v2 branch. It's more like a rewrite, not a feature update. You can see the old docs [here](https://community.nodemailer.com/), there is sendmail support for Nodemailer v2 via an additional plugin.

During the past 6 or 7 years of Nodemailer there has not been a single security incident or update. There have been some horrendous bugs surely but v2 has been stable for a long time.

Regarding Node v4 vs v6 there are more differences than the spread operator. For example the `Array.includes()` method use and so on.

Regarding Babel and stuff, I do not want to add a build-step or anything into the codebase. If Babel really works for you then you can create your own wrapper module that fetches the latest version of Nodemailer and rebuilds it for Node v4.

**Comment by Phyks** [comment]
Ok, I think I'll go for the wrapper module. Thanks
