### ISSUE TITLE
JSONTransport has wrong name

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#798]
https://github.com/nodemailer/nodemailer/blob/940f6e9a2178ed4861757b389257a22e72885b1c/lib/json-transport/index.js#L24

Should this not be `JSONTransport` instead?

**Comment by andris9** [comment]
Oh, yeah, it's invalid

**Comment by niftylettuce** [comment]
@andris9 please ping me when you do a version bump on npm, thanks!
