### ISSUE TITLE
nodemailer.createTransporter is not a function

### ISSUE THREAD

**Issue by abobakr11** [nodemailer/nodemailer#800]
that error appear  when i try to send email messages, from the local server to gmail service
here is the package.json
`{
  "name": "express-website",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.17.1",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.3",
    "express": "~4.15.2",
    "jade": "~1.11.0",
    "morgan": "~1.8.1",
    "serve-favicon": "~2.4.2",
    "nodemailer" : "*" 
  }
}

`
contact.jade file
`extends layout

block content
	.container
		form(method='post', action='contact/send')
			h1 Contact
			.form-group
				label Name
				input.form-control(type='text',name='name', placeholder='Enter Your Name here!')
			.form-group
				label Email
				input.form-control(type='email',name='email' placeholder='Email')
			.form-group
				label Message
				textarea.form-control(name='message',placeholder='Enter Message')
			button.btn.btn-default(type='submit') Submit	`
and contact.js file
`var express = require('express');
var router = express.Router();
var nodemailer = require('nodemailer');

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('contact', { title: 'Contact' });
});

router.post('/send',function(req, res, next){
 var transporter = nodemailer.createTransport({
  service : 'Gmail',
  auth: {
  	user: 'abubakr8911@gmail.com',
  	pass:'123'
  }
 });

 var mailOptions = {
 	from:'John Doe <johndoe@outlook.com>',
 	to:'abubakr8911@gmail.com',
 	subject:'WebsiteSubmission',
 	text:'You have A new submission with the following details...Name: '+req.body.name+ 'Email' + req.body.email +'Message:' +req.body.message,
   html:'<p> You got A new submission with the following details ..</p><ul><li>Name: +"req.body.name"</li><li>Email: +"req.body.email</li><li>Message:+"req.body.message"</li></ul>'
  };

  transporter.sendMail(mailOptions, function(error, info){
  	if(error){
  		console.log(error);
  		req.redirect('/');
  	}else{
  		console.log('Message Sent: ' + info.response);
  		req.redirect('/');
  	};
  });
});

module.exports = router;
`

**Comment by andris9** [comment]
the method is `createTransport`, see [example](https://nodemailer.com/about/#example)
