### ISSUE TITLE
Allow Promise in smtp-connection

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#803]
Per <https://github.com/nodemailer/nodemailer/blob/master/lib/smtp-connection/index.js> it'd be nice if we could use a Promise instead of a callback (e.g. `await connection.connect()` and `await connection.send(info)`.

**Comment by andris9** [comment]
What is the context for that? I can't use async/await in Nodemailer as I want to keep supporting Node v6 for the foreseeable future. Or do you want to use it somewhere else? So far I've been reluctant to using promises as i don't understand these 100%, don't know all the edge cases and such.
