### ISSUE TITLE
Docs: options.transport dropped in 3+?

### ISSUE THREAD

**Issue by eddieajau** [nodemailer/nodemailer#810]
Complete the following form to have your issue reviewed

### 1. Is this a bug in Nodemailer?
  - [x] Yes ... sort of

### 2. Is this related to Gmail / Hotmail / Yahoo?
- [x] No
 
### 3. Is your issue related to SSL/TLS errors?
 - [x] No

### 4. Is your issue related to connection timeouts
 - [x] No

### 5. Do you get SyntaxError when using Nodemailer?
 - [x] No

### 6. Nodemailer version you are having problems with (eg. v1.3.7)
4.2.0

### 7. Node.js version you are using (run `node -v` to see it, eg v5.5.0)
8.1.3

### 8. Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
OSX

### 9. Nodemailer configuration settings (if applicable)
```js
{
  transport: 'stub'
}
```
### 10. If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)

N/A

I've upgraded an older service on Nodemailer 2 and looking at the new `createTransport`, it appears that the old `transport` property has been dropped from the configuration options.

Is that correct?

If so, should this been included in the backward compatible changes notes because it's taken me quite a while to work out what's been going wrong if that's the case?

Thanks in advance.

**Comment by andris9** [comment]
The upgrade docs are probably incomplete. No time to update these though, sorry
