### ISSUE TITLE
Question  related to the use of pool and transporter.close()

### ISSUE THREAD

**Issue by MatthieuHPP** [nodemailer/nodemailer#814]
Hello,

I am using pool to limit the rate of email sent via Nodemailer (latest version / node 6.11 / Debian 8) and would like to close the pooling connection once emails are sent.

For example, to send 120 emails at a rate of 1 per second, the time required to send the amount of emails is 2 minutes. **How to close the connection with transporter.close(), once all the emails are send, while being able to send some new emails some minutes latter ?**

The following configuration allows me to send emails and close the connection once with the mail server once all are sent.

However, I can not send any email if I call the same routine form the front-end.
I can use the routine dedicated to email sending many time if i do not call the method .close()

```
let transporter = nodemailer.createTransport({pool: true,...})

for (i_email = 0; i_email < N ; i_email++){
transporter.sendMail({
              from: 'domain <no-reply@domain.com>',
              to: email[i_email],
              subject: 'test',
              text: 'hello world'
                 }, function(err, reply) {
                   if(err){return next(err)}
                   if(i_email === N-1){transporter.close()}
                })
}

```

Many thanks

**Comment by andris9** [comment]
Don’t call the transport.close() method. Let Nodemailer to handle the connections. If a connection has idled long enough it gets closed automatically and reopened once there’s more mail to send. The close() method is mostly for cleanup.

**Comment by MatthieuHPP** [comment]
Many thanks

**Comment by pubmikeb** [comment]
@andris9, back to what your words:

> Don’t call the `transport.close()` method. Let Nodemailer to handle the connections. If a connection has idled long enough it gets closed automatically and reopened once there’s more mail to send. The `close()` method is mostly for cleanup.

When should I then call the `close()`? I'm regular that any connection I opened at the end should be either returned to the pool or closed, otherwise it will lead to memory leak. Could you please, provide some real-life examples when when `close()` is mandatory?

**Comment by unkn0wn3rr0r** [comment]
As @pubmikeb said, it would be nice to have a _real-life example_ on that, because at the moment it sounds like that it's one of those things that are nice to have, but do we ever get the chance of using it.
