### ISSUE TITLE
Sendmail transporter isn`t working

### ISSUE THREAD

**Issue by StephenLynx** [nodemailer/nodemailer#816]
Complete the following form to have your issue reviewed

### 1. Is this a bug in Nodemailer?
 
 - [X ] Yes
 - [ ] No

### 2. Is this related to Gmail / Hotmail / Yahoo?

 - [ ] Yes
 - [X ] No
 
### 3. Is your issue related to SSL/TLS errors?

 - [ ] Yes
 - [ X] No
 
### 4. Is your issue related to connection timeouts

 - [ ] Yes
 - [X ] No

### 5. Do you get SyntaxError when using Nodemailer?

 - [ ] Yes
 - [X ] No

### 6. Nodemailer version you are having problems with (eg. v1.3.7)
4.4.0

### 7. Node.js version you are using (run `node -v` to see it, eg v5.5.0)
8.9.1

### 8. Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
Centos 7.4

### 10. If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)

Create a transport using 
var mailer = require('nodemailer').createTransport({sendmail:true});

Send an e-mail to a gmail address using 
 mailer.sendMail({
    from : "some random e-mail that doesn't actually exist",
    to : "the gmail recipient",
    subject : "some text",
    html : "some html"
  }, function emailSent(error) {
    //check if there is an error
  });

There will be no error and no e-mail will arrive at the recipient.

The issue isn't present on version 2.7.2.
If I change the transport to just 
var mailer = require('nodemailer').createTransport();
and consequently use the direct transporter, the e-mail arrives, even if it's on the spam folder.

which sendmail returns "/usr/sbin/sendmail", btw.

**Comment by andris9** [comment]
Check sendmail queue. You only get an error if Nodemailer fails to pass the message to sendmail. What happens next to the message is up to sendmail and Nodemailer does not get any feedback about it.

**Comment by StephenLynx** [comment]
>postqueue: fatal: Queue report unavailable - mail system is down
Ok, so I have to have a whole daemon running? How do I send e-mails without anything but my own software like I did with the direct transport? You didn't gut that feature and didn't replace with anything, did you?
