### ISSUE TITLE
mail receiving at spam folder 

### ISSUE THREAD

**Issue by nameisvick** [nodemailer/nodemailer#819]
Hello can any one tell why using node mailer makes the mail receive in spam  by default ....
this is my logic 
var mail = require("nodemailer").mail;
mail({
               from: "xyz@asas.com", // sender address
          to: User.email, // list of receivers
         subject: "Hello ", // Subject line
         text: "Hello world ", // plaintext body
   });

i have used nodemailerversion 0.7.1  Thanks in advance

**Comment by andris9** [comment]
Your sending IP is not trusted. Try to build reputation to it by sending larger amount of valid, non-spammy emails, or alternatively send your messages through some service that handles reputation issues by itself
