### ISSUE TITLE
DKIM Failure / SPF Failure

### ISSUE THREAD

**Issue by Eksapsy** [nodemailer/nodemailer#821]
Complete the following form to have your issue reviewed

### 1-5. Issue Pre-Made Questions
 
 - [ ] Yes
 - [x] No

### 6. Nodemailer version you are having problems with (eg. v1.3.7)

Nodemailer Version: 4.1.0

### 7. Node.js version you are using (run `node -v` to see it, eg v5.5.0)

Node.js version: v8.4.0

### 9-10. Code
https://gist.github.com/Eksapsy/81b3eea07f21cf2a2b83009056bb3211

## Issue
My issue, that I wish you can help, is that although the email is sent very nicely in almost all Web servers (Gmail and other ones), there is one particular server of my client's associates that does not accept very nicely the email ... **due to, as their server says, DKIM Failure**. 

&rarr; Which means that **the body is not sent, it's altered**, and **the only thing sent is the attachment**.

Although, **Gmail does not complain about it.**

So I tested it on [Email-Tester](http://www.mail-tester.com/), and I got a very bad rating. 

### Email Tester Rating: **> 2/10**

**-3 points** &rarr; **Due to SPF Failure.**
**-3 points** &rarr; **And Sender-ID** which I think it's the same problem 
**-2 points** &rarr; Some other little things

So, since I'm new in **Sending Emails via Server** thing, could anyone explain me ...
- Should I add the **IP** of my **Heroku App** in the Original Domain's **SPF records**? 
- Why Gmail and other servers treat nicely the email while this one seems to have high secutity issues with mine
### And most importantly
- **Can I do anything directly via Code to solve this?**

Thanks!

**Comment by andris9** [comment]
Configuring proper sending environment is out of scope for Nodemailer, I don’t think there’s much you can do in code besides using valud From address etc. I’d suggest you to use a sending service like Sendgrid or Mailgun and follow their setup guide of which SPF settings etc to use.

**Comment by kingworm** [comment]
I think you should setup SPF/DKIM/DMARC.

even if you set up already, then you should also consider reverse DNS lookup.
