### ISSUE TITLE
Attachment cid expected as a String, previous Meteor-Email version I passed an integer/Number

### ISSUE THREAD

**Issue by 999chris** [nodemailer/nodemailer#823]
### 1. Is this a bug in Nodemailer?
 
 - [X] Yes
 - [ ] No
 
Hi, I've been using Meteor and the "Email" module of which nodemailer is now part of, since upgrading.

Apart from a couple of changes in field names for attachments (fileName/**filename** * filePath/**path**) the Meteor-Email (https://docs.meteor.com/api/email.html) upgrade is fine, however: I was previously using a millisecond epoch value as my "cid" when creating embedded attachments, with nodemailer this throws an error as the "cid" is expected as a string.

Can I suggest creating an empty string and concatenating the given cid value to that, instead of passing the raw "cid" value given?

**Comment by andris9** [comment]
cid format is "uniqueid@hostname" so using a number is not a valid approach
