### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by narutojone1218** [nodemailer/nodemailer#824]
host: 'smtp.ethereal.email',
ssl: true,
port: 465,
secure: true,
tls: { rejectUnauthorized: false,
         secureProtocol: "TLSv1_method"},
auth: {
	user: 't6o2x4a7tfhgnix4@ethereal.email',
	pass: '6QSqyXQnGAa7f6XDbr'
}

I tried to send email with this setting, but faced this error.

Error: read ECONNRESET
code:"ECONNECTION"
command:"CONN"
errno:"ECONNRESET"
message:"read ECONNRESET"
stack:"Error: read ECONNRESET\n    at exports._errnoException (util.js:1022:11)\n    at TLSWrap.onread (net.js:610:25)"
syscall:"read"

I don't have any idea to fix this. Please support me.
Thanks in advance.

**Comment by andris9** [comment]
Happens when https://ethereal.email is down. There are some RAM issues on heavy load.
