### ISSUE TITLE
Usability website BUG!!!

### ISSUE THREAD

**Issue by monbro** [nodemailer/nodemailer#834]
Come one guys, when I am going on https://nodemailer.com/about/ and selecting any code in your codeboxes, the highlighting is black on black? Are you kidding? Please have some thoughts on this.. -.-

**Comment by 2932486040lch** [comment]
水水水水

**Comment by andris9** [comment]
The design is based on a template. I don't have the skill for front-end coding nor do I have any finances to pay for it. The website is as it is and until someone does not make a better one it is going to stay like this.

**Comment by monbro** [comment]
Fair point! :) Don't get me wrong, just trying to point out a improvement for the website. As a web developer it just hit my eyes. BTW: the template seemed to me self made.
