### ISSUE TITLE
Mention plugins that are an alternative to CID and support fonts

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#841]
At <https://nodemailer.com/plugins/> can we mention these two?

* <https://github.com/ladjs/nodemailer-base64-to-s3>
* <https://github.com/ladjs/font-awesome-assets>

**Comment by andris9** [comment]
I made the sources for nodemailer webpage public, so you can make a PR against this file: https://github.com/nodemailer/nodemailer-web/blob/master/content/plugins/index.md
