### ISSUE TITLE
Can't send mail to only 1 address

### ISSUE THREAD

**Issue by Shiigehiro** [nodemailer/nodemailer#842]
### 2. Is this related to Gmail / Hotmail / Yahoo?
 - [X] Yes

### 6. Nodemailer version you are having problems with (eg. v1.3.7)
v4.4.2

### 7. Node.js version you are using (run `node -v` to see it, eg v5.5.0)
v7.6.0

### 8. Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
Ubuntu server 14.04

### 9. Nodemailer configuration settings (if applicable)
let transporter = nodemailer.createTransport({
  host: 'SSL0.OVH.NET',
  port: 465,
  secure: true,
  auth: {
      user: "mailaddress@domain.com",
      pass: "mailpassword" 
  }
});

Problem:

Sending email to 2 different email address work
Sending email to 2 gmail email address work too
But sending email to only 1 gmail email address don't work, i receive any error, but the mail is never received

Error: 
`{ accepted: [ 'hide@gmail.com' ],
rejected: [],
envelopeTime: 1163,
messageTime: 95,
messageSize: 3776,
response: '250 2.0.0 Ok: queued as 229508007E',
envelope: 
{ from: 'no-reply@hide.xyz',
to: [ 'hide@gmail.com' ] },
messageId: '<3e0d443e-6549-8f91-f92e-37badc12f98e@hide.xyz>' }`

**Comment by andris9** [comment]
The server responds that message was accepted for delivery. What happens next with it is out of hands for Nodemailer.

**Comment by Shiigehiro** [comment]
This is maybe a problem between nodemailer and Gmail but not a problem with gmail and not with my mail address because it work with emailjs and old version of nodemailer.

Then i think it's a problem of nodemailer, and this is why i made a issue here and not on the support of Gmail
