### ISSUE TITLE
Help please! Mails sent from nodeMailer do not display properly in email clients when attachments are added

### ISSUE THREAD

**Issue by AbominableIntelligence** [nodemailer/nodemailer#848]
Hi all,

I am using node.js v7.6.0 on Ubuntu 14.04, connecting to a MailEnable SMTP server (with MxScan security plugin) running on Windows Server. nodeMailer is v2.6.0

Mails get delivered just fine, 250 across the board, but no attachments are shown on the email client side, nor is the body text displayed.

- In Outlook, the raw message is displayed including headers instead of parsed body text and separate attachments.

- In Thunderbird, the message/preview is empty, but viewing the message source shows the base64-encoded attachment. No attachments are shown separately. Also, as the messages are busy downloading from the server, the attachment icon shows but rapidly disappears.

- In Gmail's online viewer, the message is also displayed raw.

When I do not add any attachments, the mails display fine and I can see the body text as expected.

Here is my code:

``` JavaScript
var FS = require('fs');
var nodemailer = require('nodemailer');
var smtpTransport = require('nodemailer-smtp-transport');
var transporter = nodemailer.createTransport(
        smtpTransport({
          host: 'mySMTPServer',
          port: 25,
          auth: {
              user: 'dayhum',
              pass: 'skippy'
          }
        })
      );

var MailOptions = {
      from: 'sender@test.com',
      to: 'recipient@test.com',
      subject: 'Test Email',
      text: 'PLAIN TEXT BODY',
      attachments:  [
        {
          contentType: 'application/pdf',
          contentDisposition: 'attachment',
          filename: 'test.pdf', 
          content: FS.createReadStream('test.pdf')
        }
      ]
};

// NOTE: The behaviour is the same regardless of the attachment type or streaming method used per attachment.

transporter.sendMail(MailOptions, function afterSend(Err, Info){
                          if (Err)
                              console.log('SendMail Err:', Err, Info);
                          else
                              console.log('SendMail OK:', Info);
                      });
```

This is what the message source looks like (copied verbatim from Thunderbird's view source window):

```
From - Tue Feb 27 13:32:12 2018
X-Account-Key: account1
X-UIDL: E4F37F2C4FFD466492A1939BB39B82F9
X-Mozilla-Status: 0001
X-Mozilla-Status2: 00000000
X-Mozilla-Keys:                                                                                 
Received: from ([127.0.0.1]) with MailEnable ESMTP; Tue, 27 Feb 2018 13:31:07 +0200
Content-Type: multipart/mixed; boundary*0="----sinikael-?=_1-Tue Feb 27
 2018 13:31:37 GMT+020"; boundary*1="0 (SAST)0.0166145037891805"
From: sender@test.com
To: recipient@test.com
Subject: Test Email
Message-ID: <b5d89044-2717-3dd2-0eac-1ea61a6ea9ab@test.com>
X-Mailer: nodemailer (2.6.0; +http://nodemailer.com/;
 SMTP/2.7.2[client:2.12.0])
Date: Tue, 27 Feb 2018 11:31:37 +0000
MIME-Version: 1.0
X-MXScan-Scan: Scanned by MxScan 2.5.100.0 for XXXXX
X-MXScan-Msgid: B2D3293AA1054067BAAC5143700F38F8_
X-MXScan-License: {Unregistered Version} Only for personal and non-commercial use. Commercial use is PROHIBITED and requires a license.
X-MXScan-Country-Sequence: Localhost->Destination
X-MXScan-AntiVirus: ClamAV 0.96.5/23960/Tue Oct 17 22:02:46 2017 [Disabled for SMTP-OUT(1)]
X-MXScan-AntiSpam: KEYWORD [Pass], RDNSBL [NA], URLBL [Pass], SPAMASSASSIN [1.1 (HTML_MESSAGE,MIME_HTML_ONLY,MIME_QP_LONG_LINE,TVD_SPACE_RATIO,TVD_SPACE_RATIO_MINFP,UNPARSEABLE_RELAY)], DCC_CHECK [NA]
X-MXScan-SpamScore: 1.1
X-MXScan-ProcessingTime: 1.531 sec(s)
Return-Path: <sender@test.com>

------sinikael-?=_1-Tue Feb 27 2018 13:31:37 GMT+0200 (SAST)0.0166145037891805
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

PLAIN TEXT BODY
------sinikael-?=_1-Tue Feb 27 2018 13:31:37 GMT+0200 (SAST)0.0166145037891805
Content-Type: application/pdf; name=test.pdf
Content-Disposition: attachment; filename=test.pdf
Content-Transfer-Encoding: base64

JVBERi0xLjMKJf////8KMTAgMCBvYmoKPDwKL1R5cGUgL0V4dEdTdGF0ZQovY2EgMQo+PgplbmRv
YmoKMTEgMCBvYmoKPDwKL1MgL1VSSQovVVJJIChbb2JqZWN0IE9iamVjdF0pCj4+CmVuZG9iagox
MiAwIG9iago8PAovU3VidHlwZSAvTGluawovQSAxMSAwIFIKL1R5cGUgL0Fubm90Ci9SZWN0IFs5
.
[snip]
.
MyAzMi4yMzA5OTk5OTk5OTk5OTUgMTc4LjEyIDM5LjQzMTAwMDAwMDAwMDA0XQovQm9yZGVyIFCi9JbmZvIDE0IDAgUgo+PgpzdGFydHhyZWYKMTM0OTAKJSVFT0YK
------sinikael-?=_1-Tue Feb 27 2018 13:31:37 GMT+0200 (SAST)0.0166145037891805

-------------------------------------------------------------------------------------
This email has been scanned by the MxScan Email Security System.
-------------------------------------------------------------------------------------
```

You will note that the MxScan engine adds a bunch of headers and a footer, but other mails also have this and there is no problem.

You will also note that the sinikael multipart/mixed boundary definition is split in two, and the first part is interrupted by a linebreak.

I have no idea what's wrong and have been struggling with this for two days now.

Any pointers would be MASSIVELY appreciated!
Thanks in advance,
Rhianne

**Comment by andris9** [comment]
Nodemailer uses Date.now() output as part of the mime boundary in order to guarantee uniqueness. You are most probably using some additional date library that messes with the native Date object and breaks Date.now() to return a date string instead of numeric timestamp.

This is how a boundary should look like:

    ------sinikael-?=_1-1519737215845.0166145037891805

and this is how you have it:

    ------sinikael-?=_1-Tue Feb 27 2018 13:31:37 GMT+0200 (SAST)0.0166145037891805

**Comment by AbominableIntelligence** [comment]
Hooo yer a genius! (Well I hope so!) Let me go have a dig at my date libraries and see what I come up with. Thank You!

**Comment by AbominableIntelligence** [comment]
Well, yer a genius! I'm using the www.datejs.com library - and that's breaking Date.now() as you suspected.

It now works, but I have a LOT of regression testing to do now because it has its tentacles everywhere.

Thanks again!
