### ISSUE TITLE
Error in sponsor links on nodemailer.com

### ISSUE THREAD

**Issue by monkeywithacupcake** [nodemailer/nodemailer#849]
![screen shot 2018-02-28 at 07 10 47](https://user-images.githubusercontent.com/7316730/36758173-f6cadd54-1c56-11e8-9375-3775987c4a32.png)

**Comment by andris9** [comment]
There's the standard script tag on the page, do you have any suggestions how to get it working. It used to work fine previously

```html
<script src="https://opencollective.com/nodemailer/banner.js"></script>
```

**Comment by monkeywithacupcake** [comment]
I am surprised. I'm forwarding the question to engineering at Open Collective, and I'll get back to you. I see that the guidance from https://opencollective.com/widgets is still to add that script
```<script src="https://opencollective.com/:collectiveSlug/banner.js"></script>```

**Comment by monkeywithacupcake** [comment]
I submitted an issue on the opencollective API - you can follow here: https://github.com/opencollective/opencollective-api/issues/1165

**Comment by andris9** [comment]
Thanks. I guess I can close this issue then. If there's anything I still need to do then please re-open it or create a new issue.
