### ISSUE TITLE
nodemailer auth not working if i am using @ in my password

### ISSUE THREAD

**Issue by osamabari** [nodemailer/nodemailer#864]
It's a huge bug in nodemailer. if I am using @ symbol in my password then it's says _Invalid login: 504 Unrecognized authentication type_
here is the full log

Credentials obtained, sending message...
[2018-04-05 06:05:06] DEBUG Creating transport: nodemailer (4.6.4; +https://nodemailer.com/; SMTP/4.6.4[client:4.6.4])
[2018-04-05 06:05:06] DEBUG Sending mail using SMTP/4.6.4[client:4.6.4]
[2018-04-05 06:05:06] INFO  [GNQufuVAxQY] Connection established to 83.111.193.113:25
[2018-04-05 06:05:06] DEBUG [GNQufuVAxQY] S: 220 barracuda.domain.com ESMTP (76808e657550c1ed76d7204e863d8299)
[2018-04-05 06:05:06] DEBUG [GNQufuVAxQY] C: EHLO Osamas-MacBook-Air.local
[2018-04-05 06:05:06] DEBUG [GNQufuVAxQY] S: 250-barracuda.domain.com Hello Osamas-MacBook-Air.local [94.200.187.126], pleased to meet you
[2018-04-05 06:05:06] DEBUG [GNQufuVAxQY] S: 250-SIZE 25000000
[2018-04-05 06:05:06] DEBUG [GNQufuVAxQY] S: 250-8BITMIME
[2018-04-05 06:05:06] DEBUG [GNQufuVAxQY] S: 250 HELP
[2018-04-05 06:05:06] DEBUG [GNQufuVAxQY] SMTP handshake finished
[2018-04-05 06:05:06] DEBUG [GNQufuVAxQY] C: AUTH PLAIN AGVwcGNvZGVsaXZlcnlzeXN0ZW1AdHJpc3Rhci1ncm91cC5jbwB0cmlAc3RhciQ=
[2018-04-05 06:05:06] DEBUG [GNQufuVAxQY] S: 504 Unrecognized authentication type
[2018-04-05 06:05:06] INFO  [GNQufuVAxQY] User "smtpuser@domain.com" failed to authenticate
[2018-04-05 06:05:06] DEBUG [GNQufuVAxQY] Closing connection to the server using "end"
[2018-04-05 06:05:06] ERROR Send Error: Invalid login: 504 Unrecognized authentication type
Error occurred
Invalid login: 504 Unrecognized authentication type

Guys, please fix it

**Comment by andris9** [comment]
This seems to be a MX server, it does not accept authentication, no matter what password you use. You should change port to 587.

**Comment by osamabari** [comment]
Everything is good, I've tested with java and got success response .
250-SIZE 25000000
250-PIPELINING
250-8BITMIME
250 HELP
DEBUG SMTP: Found extension "SIZE", arg "25000000"
DEBUG SMTP: Found extension "PIPELINING", arg ""
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "HELP", arg ""
DEBUG SMTP: use8bit false
DEBUG SMTP: Verified Addresses
DATA
354 Start mail input; end with <CRLF>.<CRLF>

Message-ID: <2046562095.01522837556568.JavaMail.anupg@DESKTOP-EQJQPTT>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

This is a test 2
.
250 Ok: queued as EF67818C0089
QUIT

**Comment by andris9** [comment]
If you do not want to use authentication and the server does not require it, then set `auth` option to `false`

**Comment by osamabari** [comment]
but I want to use authentication it's required.
this java code is working fine 

`
import java.util.Properties;

import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class SimpleMail {

	private static final String SMTP_HOST_NAME = "mail.domain.com";  // 8.8.8.8   0501077895
	private static final String SMTP_AUTH_USER = "smtpuser@domain.co";
	private static final String SMTP_AUTH_PWD = "Tech@123";

	public static void main(String[] args) throws Exception {
		new SimpleMail().test();
	}

	public void test() throws Exception {
		Properties props = new Properties();
		props.put("mail.transport.protocol", "smtp");
		props.put("mail.smtp.host", SMTP_HOST_NAME);
		props.put("mail.smtp.port", "25");
		props.put("mail.smtp.auth", "true");

		Authenticator auth = new SMTPAuthenticator();
		Session mailSession = Session.getDefaultInstance(props, auth);
		mailSession.setDebug(true);
		Transport transport = mailSession.getTransport();

		MimeMessage message = new MimeMessage(mailSession);
		message.setContent("This is a test 2", "text/plain");
		message.setFrom(new InternetAddress("smtpuser@domain.co"));
		message.addRecipient(Message.RecipientType.TO, new InternetAddress("smtpuser@domain.co")); // irfan.sharif@domain.com
		 // irfan.sharif@domain.com smtpuser@domain.co

		transport.connect();
		transport.sendMessage(message, message.getRecipients(Message.RecipientType.TO));
		transport.close();

		System.out.println("Sent");
	}

	private class SMTPAuthenticator extends javax.mail.Authenticator {
		public PasswordAuthentication getPasswordAuthentication() {
			String username = SMTP_AUTH_USER;
			String password = SMTP_AUTH_PWD;
			return new PasswordAuthentication(username, password);
		}
	}

}`

**Comment by osamabari** [comment]
you can check above code, it's working fine for me but the same config in nodemailer not working.
 here is nodejs code.
```

/* eslint no-console: 0 */

'use strict';

const nodemailer = require('nodemailer');


// Generate SMTP service account from ethereal.email
nodemailer.createTestAccount((err, account) => {
    if (err) {
        console.error('Failed to create a testing account');
        console.error(err);
        return process.exit(1);
    }

    console.log('Credentials obtained, sending message...');

    // NB! Store the account object values somewhere if you want
    // to re-use the same account for future mail deliveries

    // Create a SMTP transporter object
    let transporter = nodemailer.createTransport(
        {
            host: "mail.domain.com",
            port: 25,
            secure: false,
            auth: {
    user: "smtpuser@domain.co",
    pass:"Tech@123",
            },
            logger: true,
            debug: true // include SMTP traffic in the logs
        },
        {
            // default message fields

            // sender info
            from: 'smtpuser@domain.co',
            'Content-Type': 'text/plain; charset="utf-8"'
            
        }
    );

    // Message object
    let message = {
        // Comma separated list of recipients
        to: 'irfan.sharif@domain.com',

        // Subject of the message
        subject: 'Test Order 232647249',

        // plaintext body
        text: 'Hello, this is test mail 3',

        
    };

    transporter.sendMail(message, (error, info) => {
        if (error) {
            console.log('Error occurred');
            console.log(error.message);
            return process.exit(1);
        }
        console.log(info)
        console.log('Message sent successfully!');
        console.log(nodemailer.getTestMessageUrl(info));

        // only needed when using pooled connections
       // transporter.close();
    });
});
```

**Comment by osamabari** [comment]
please accept your issue and fix the problem

**Comment by Keyurkd** [comment]
I am also facing the same problem. Kindly update.

**Comment by andris9** [comment]
Your server does not support authentication. Your Java code does not attempt authentication at all and thus the message is accepted. Nodemailer forces authentication if it is enabled even if the server does not advertise support for auth and as the server does not support auth then you get an error in response.

**Comment by osamabari** [comment]
thanks @andris9

**Comment by tratch** [comment]
@andris9 's solution worked for us too. Removing the auth params fixed our problem.

**Comment by ravinayag** [comment]
@andris9 ,  I disabling auth and ended up other issue. 

  //auth: {
    user: this.email_user,
    pass: this.email_password
  //}

>>> Error:

       code: 'EENVELOPE',
       response:
        '554 5.7.1 <mydomain and ip]>: Client host rejected: Access denied',
       responseCode: 554,
       command: 'RCPT TO',
       recipient: 'user@gmail.com'

**Comment by WarBuggy** [comment]
As of 2021/07/09, using nodemailer as old as 6.1.1, password can have special character in it (letter @, for example) and still things still work properly.
