### ISSUE TITLE
icalEvent outlook

### ISSUE THREAD

**Issue by GianlucaDaur** [nodemailer/nodemailer#866]
should be like this, right?
https://files.slack.com/files-pri/T8W3V6YBZ-FA1SYPMMH/como_deveria.png
but it's like this
https://files.slack.com/files-pri/T8W3V6YBZ-FA1DW5NU9/como_t__.png
can you tell me what i'm doing wrong?

**Comment by andris9** [comment]
These links are password protected

**Comment by GianlucaDaur** [comment]
sorry
https://i.imgur.com/JRKbzH8.png
https://i.imgur.com/mS1J4rp.png
respectively
