### ISSUE TITLE
How to set MIME messages in nodemailer options object?

### ISSUE THREAD

**Issue by Gunner17** [nodemailer/nodemailer#868]
It's more of a help that I need with nodemailer (than an issue). I tried asking in stackoverflow without any response so far. Could not help but ask it here since this needed an urgent solution. 

I have generated a MIME message using mimemessage package of node js [(https://www.npmjs.com/package/mimemessage)](https://www.npmjs.com/package/mimemessage) . 

Here is the code I have used to do it :
```
var htmlEntity, plainEntity, pngEntity;
// Build the top-level multipart MIME message. 
var msg = mimemessage.factory({
    contentType: 'multipart/mixed',
    body: []
});
// Build the multipart/alternate MIME entity containing both the HTML and plain text entities.
var alternateEntity = mimemessage.factory({
    contentType: 'multipart/alternative',//alternate
    body: []
});
// Build the HTML MIME entity. 
var htmlEntity = mimemessage.factory({
    contentType: 'text/html;charset=utf-8',
    body: mailcontent
});  
// Build the plain text MIME entity.        
var plainEntity = mimemessage.factory({
    body: ''
});
// Add both the HTML and plain text entities to the multipart/alternate entity. 
alternateEntity.body.push(htmlEntity);
alternateEntity.body.push(plainEntity);
// Add the multipart/alternate entity to the top-level MIME message. 
msg.body.push(alternateEntity);    
```

Now if I want to send the above MIME content using nodemailer [(https://nodemailer.com/about/)](https://nodemailer.com/about/) email, where exactly do I need to set the MIME content in my nodemailer options object?

The following does not seem to work, as the MIME message headers and boundaries are showing
up in the actual email content if I do this..  
```
mailOptions["html"] = msg.toString();
//mailOptions is nodemailer options object
//msg is the top level MIME message
```
Please help me to set this MIME message as node mailer content or let me know if there is any other approach available.

**Comment by andris9** [comment]
Use the `raw` property as described [here](https://nodemailer.com/message/custom-source/)
