### ISSUE TITLE
Treated as spam

### ISSUE THREAD

**Issue by Grigore147** [nodemailer/nodemailer#87]
Hi Andris, thanks for great module.

So when i'm sending a email with sender only email "Shogun147@gmail.com" all is ok, but when i set a formatted field from "Shogun &lt;Shogun147@gmail.com&gt;" the message is going to spam folder only but not to incoming.

There is something with nodemailer module or Gmail trade this email like spam?

Thanks.

**Comment by andrewphanpuspo2000** [comment]
Hi Andris,
I am also having same issue. the message stored as spam. Also, when I use nodemailer, I have to assigned secure as false and tls rejectauth as false as well otherwise it would not work. do you have any advice regarding this issue?
