### ISSUE TITLE
Nodemailer wont add icalEvent

### ISSUE THREAD

**Issue by Cnnamon** [nodemailer/nodemailer#872]
icalEvent string generated: // Changed some of the values to test, please fill your own

```
NAME:Test Events
X-WR-CALNAME:Test Events
BEGIN:VEVENT
UID:ko96@test.com
SEQUENCE:0
DTSTAMP:20180430T083653Z
DTSTART;TZID=US/Central:20180430T000000
DTEND;TZID=US/Central:20180430T083653
SUMMARY:Test
DESCRIPTION:Test
ORGANIZER;CN="Name LastName":mailto:Test-your-email@change-to-your-company.com
ATTENDEE;ROLE=REQ-PARTICIPANT;CN="Test test":MAILTO:Test-your-email@change-to-your-company.com
URL;VALUE=URI:any-url
END:VEVENT
END:VCALENDAR
```

sending like this: 
`icalEvent: {
     filename: 'invitation.ics',
     method: 'request',
     content: event
}`

Expected result: I see the event in Gmail when i open the email i sent
Actual result: There is no event

**Comment by andris9** [comment]
Doesn't seem like well formatted calendar event., ie. no BEGIN:VCALENDAR. Nodemailer passes to Gmail what you have provided, so if Gmail does not like the event file then there's nothing to do on the Nodemailer side.
