### ISSUE TITLE
connection timeout on zoho email account

### ISSUE THREAD

**Issue by Filliposniper** [nodemailer/nodemailer#876]
I have created a zoho email account for my domain, and it works well in my zoho mail account dashboard,
but i want to use it with nodemailer to send mails to my users all I get is connection timeout after sometime. i have really done some research on this problem and asked questions but i have not figured out a way to solve this.

```
nodemailer-version: 4.6.4
node-version: 6+

var transporter = nodemailer.createTransport({
            host: 'smtp.zoho.com',
            port: 465,
            secure: true, 
            auth: {
                user: 'mymail@domain.com',
                pass: 'mypassword'
             },  
        });
    
        var mailOptions = {
            from: 'mymail@domain.com',
            to: somebody@gmail.com',  
            subject: 'Hello ✔', 
            text: 'Hello world?',
            html: '<b>Hello world?</b>'
        };
       
        transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
                return console.log(error);
            }
            console.log('message sent');
        });
}

```
The error am getting from my command line console

```
{ Error: Connection timeout
    at SMTPConnection._formatError (/home/ubuntu/workspace/bitcoin.1/main/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
    at SMTPConnection._onError (/home/ubuntu/workspace/bitcoin.1/main/node_modules/nodemailer/lib/smtp-connection/index.js:579:20)
    at Timeout._connectionTimeout.setTimeout (/home/ubuntu/workspace/bitcoin.1/main/node_modules/nodemailer/lib/smtp-connection/index.js:261:18)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'ETIMEDOUT', command: 'CONN' }

```

**Comment by andris9** [comment]
Connection timeouts are usually network issues or configuration issues or firewall issues.

**Comment by nir-jas** [comment]
@andris9 What's the ideal solution for this? Should I increase socketTimeout. Because When I am using locally it's working fine.

**Comment by andriyfm** [comment]
i have some issue @nir-jas

**Comment by kevinnascimento** [comment]
> @andris9 What's the ideal solution for this? Should I increase socketTimeout. Because When I am using locally it's working fine. It's creating a problem for Production Environment.

Did you solve it? I have the same issue just in Production Environment and all ports are open.
