### ISSUE TITLE
TLS check fails with Let's encrypt DNS certificate

### ISSUE THREAD

**Issue by somanos** [nodemailer/nodemailer#879]
Hi
I'm using SSL certificates granted by Let's Encrypt over DNS challenge (Acme V2)
with tls.rejectUnauthorized set to true Igot the message 
Error: Hostname/IP doesn't match certificate's altnames: "Host: mail.drumee.com. is not in the cert's altnames: DNS:mail.drumee.net"

I suppose the matching is comparing the string "mail.drumee.com" to  "DNS:mail.drumee.net" 
Maybe is it Let's Encrypt' issue... 
Regards
Somanos

**Comment by andris9** [comment]
Nodemailer uses standard TLS handling of Node.js, so there's nothing to fix or change in Nodemailer regarding this issue.

**Comment by aral** [comment]
I’m also seeing this. Do you know if there’s an upstream bug about this?
