### ISSUE TITLE
Question about GDPR

### ISSUE THREAD

**Issue by valeriosillari** [nodemailer/nodemailer#880]
Maybe it's a dummy question but I would like to ask.

In a couple of days the new European Privacy Law ([GDPR](https://www.smashingmagazine.com/2018/02/gdpr-for-web-developers/)) will be official, and many people are talking how to inform users how they collect, use and aggregate personal data.

One big topic is also about contact forms.

Now I am using Node Mailer on some projects.
My form required a name, a email and a message.

So I don't save any personal data in any DB, but just using the mailer to create a mail and send all the info of the user as mail to a Gmail Account.

I am wondering:

1) Do I have to set a checkbox for asking permission to use the data (name and email especially)? I think so. But which text should use?

2) I don't technically save any info in a private DB, but all the info are stored in a Gmail Account. Should I have to inform/explain this to the user? How?

Please let me know if somebody has the same questions or if you solve it :)

**Comment by nachtwerk** [comment]
Though this is not a issue that nodemailer will or should solve for you, having dealt with this in person for our company:

1: Yes, you should ask always for consent for using personal details, and create a record(in any way) that a data subject has consented.
2: In what way you store or process data is not of interest, only that you can and will comply whenever, for instance, a data subject request his data to be deleted.

**Comment by andris9** [comment]
Not really related to Nodemailer, feel free to keep the conversation up in this thread if you like though
