### ISSUE TITLE
send once and receive duplicates

### ISSUE THREAD

**Issue by JCBsystem** [nodemailer/nodemailer#884]
running this code once 
then i resive 3 emails 

var transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'xxxx@gmail.com',
        pass: 'xxxx'
    }
});
// setup e-mail data with unicode symbols
var mailOptions = {
    from: '"Fred Foo ?" <foo@blurdybloop.com>', // sender address
    to: 'xxxx@gmail.com', // list of receivers
    subject: 'Hello ✔', // Subject line
    text: 'Hello world ?', // plaintext body
    html: '<b>Hello world ?</b>' // html body
};

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }
    console.log('Message sent: ' + info.response);
});

any advice ?

**Comment by andris9** [comment]
Depends on the context, make sure you do not call this from a loop or from a code that could be called multiple times (eg. respongid for a http request and browser makes several requests like fetching favicon.ico etc.)

**Comment by JCBsystem** [comment]
Hi thanks for a fast answer 
it is only rund once and not called from the web 
its just a blank node app

**Comment by JCBsystem** [comment]
It was old nodemon prosses runing in the background :(
