### ISSUE TITLE
How to config the webmail email to nodemailer

### ISSUE THREAD

**Issue by AmitAKB** [nodemailer/nodemailer#887]
error
{ Error: getaddrinfo ENOTFOUND mail.xxx.net mail.xxx.net:465
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'mail.xxx.net',
  host: 'mail.xxx.net',
  port: 465,
  stage: 'init' }

host: 'mail.xxx.net',
    'port': 465,
    'secure': true,
    'auth': {
      'user': 'info@xxx.net',
      'pass': 'xxxxxxxxx'
    }

**Comment by andris9** [comment]
This is DNS error, check that the hostname is correct
