### ISSUE TITLE
email subject encoding issue

### ISSUE THREAD

**Issue by lmichelin** [nodemailer/nodemailer#888]
Hello,

I don't know why nodemailer encodes the french subject ___Alerte de sécurité critique___ like that :

`Alerte de =?UTF-8?Q?s=C3=A9curit=C3=A9?= critique`

On some email clients it appears like that : __Alerte desécuritécritique__.

I think the correct encoding should be this one, like _Gmail_ does :

`=?UTF-8?Q?Alerte_de_s=C3=A9curit=C3=A9_critique?=`

Thanks for your feedback!

**Comment by andris9** [comment]
Nodemailer handles this correctly by the spec. Unfortunately not all email clients respect email specs and rather expect values always to be in certain format.

Could you provide some examples of clients that misbehave like this?

**Comment by lmichelin** [comment]
The issue occurs on ___Zimbra___ webmail for example.

**Comment by andris9** [comment]
Added an exception even though it is against the spec but I guess it is easier to change the encoding behavior in Nodemailer than in Zimbra. Fixed in v4.6.6

**Comment by lmichelin** [comment]
Thanks a lot! It works perfectly!
