### ISSUE TITLE
connection refused error while sending mails through gmail SMTP

### ISSUE THREAD

**Issue by AshishkrGoyal** [nodemailer/nodemailer#889]
My code in server.js as given below : 

**app.post('/contact/send', function (req, res) {
 const transporter = nodemailer.createTransport({
    service: 'smtp.gmail.com',
      port: 465,
      secure: false,
    auth: {
      user: '15103140ashish@gmail.com',
      pass: 'xyz'
    }
  });
const mailOptions = {
from: '15103140ashish@gmail.com',
to: 'myfriend@yahoo.com',
subject: 'website error sending ',
text: 'it is working!!'
};
transporter.sendMail(mailOptions, function(error, info){
    if (error) {
      console.log(error);
      res.redirect('/');
    } else {
      console.log('Email sent: ' + info.response);
    }
  });
})**

when i hit the submit button i got the following error in console: 

`{ Error: connect ECONNREFUSED 127.0.0.1:465
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNECTION',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 465,
  command: 'CONN' }`

I have done a lot of searching for it but unable to find the same!

Anykind of help is appreciated !

Thanks

**Comment by andris9** [comment]
Use:

```
host: 'smtp.gmail.com',
port: 465,
secure: true,
```

**Comment by AshishkrGoyal** [comment]
now my code look like it: 

**app.post('/contact/send', function (req, res) {
const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
      port: 465,
      secure: true,
    auth: {
      user: '15103140ashish@gmail.com',
      pass: 'ashish2@jiit'
    }
  });
const mailOptions = {
    from: '15103140ashish@gmail.com',
    to: 'myfriend@yahoo.com',
    subject: 'Sending Email using Node.js',
    text: 'That was easy!'
  };
transporter.sendMail(mailOptions, function(error, info){
    if (error) {
      console.log(error);
      res.redirect('/');
    } else {
      console.log('Email sent: ' + info.response);
    }
  });
})**




and getting the error : 

`{ Error: connect ETIMEDOUT 74.125.24.108:465
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNECTION',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '74.125.24.108',
  port: 465,
  command: 'CONN' }`

**Comment by AshishkrGoyal** [comment]
now my code look like it: 

**app.post('/contact/send', function (req, res) {
const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
      port: 465,
      secure: true,
    auth: {
      user: '15103140ashish@gmail.com',
      pass: 'xyz'
    }
  });
const mailOptions = {
    from: '15103140ashish@gmail.com',
    to: 'myfriend@yahoo.com',
    subject: 'Sending Email using Node.js',
    text: 'That was easy!'
  };
transporter.sendMail(mailOptions, function(error, info){
    if (error) {
      console.log(error);
      res.redirect('/');
    } else {
      console.log('Email sent: ' + info.response);
    }
  });
})**




and getting the error : 

`{ Error: connect ETIMEDOUT 74.125.24.108:465
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNECTION',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '74.125.24.108',
  port: 465,
  command: 'CONN' }`

**Comment by AshishkrGoyal** [comment]
@andris9 now i am getting timeout err message

**Comment by dalmatele** [comment]
@AshishkrGoyal  can you telnet to 465 port like this:
`openssl s_client -starttls smtp -crlf -connect smpt.gmail.com:465`

**Comment by poetanol** [comment]
Resolvio su problema???? Estoy igual...

**Comment by ervishu83** [comment]
Not resolved yet.
getting below error:

`{ Error: queryA EREFUSED smtp.gmail.com
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:199:19)
  errno: 'EREFUSED',
  code: 'EDNS',
  syscall: 'queryA',
  hostname: 'smtp.gmail.com',
  command: 'CONN' }`

**Comment by frastlin** [comment]
I am getting this error as well.
	{ Error: connect ECONNREFUSED 74.125.69.108:465
	    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:14)
	  errno: 'ECONNREFUSED',
	  code: 'ESOCKET',
	  syscall: 'connect',
	  address: '74.125.69.108',
	  port: 465,
	  command: 'CONN' }

any ideas?

**Comment by dhruvgajwa** [comment]
This happens due to installed firewall too.  port 465 is generally blocked. check your firewall setting and try again!
Hope it helps!

**Comment by sinclas** [comment]
I am still getting this error out in AWS.  Works locally.  Is that a firewall issue?

**Comment by frastlin** [comment]
My host blocked all messages that were not sent from their host email servers.

**Comment by sinclas** [comment]
So this error just started.  It was running fine for over a month with no issues.  Did something change?

**Comment by bb-art** [comment]
same problem here
resolved it by using IP address as host, see https://nodemailer.com/smtp/#general-options

**Comment by zuyao88** [comment]
Working locally but not in the server.
should be the SMTP-ses setting? or the remote-server-firewall settings?

**Comment by coolprinze** [comment]
Facing same issue, working locally but not online

**Comment by divanvb** [comment]
The same issue when deployed to firebase functions.

> Error: connect ECONNREFUSED 127.0.0.1:465
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

```typescript
const transporter = createTransport({
	service: 'smtp.gmail.com',
	port: 587,
	secure: true,
	auth: {
		type: "OAuth2",
		user: config().gmail.email,
		clientId: config().gmail.id,
		clientSecret: config().gmail.secret,
		accessToken: config().gmail.accesstoken,
		refreshToken: config().gmail.refreshtoken,
	}
});

export const sendVerificationEmail = functionAuth.user().onCreate(async (user: functionAuth.UserRecord) => {
	const verificationLink: string = await adminAuth().generateEmailVerificationLink(user.email as string);

	return await transporter.sendMail({
		from: '"Mail Name" <no-reply@mailname.com>',
		to: user.email,
		subject: 'Email verification',
		text: `${ verificationLink }`,
		html: `${ verificationLink }`
	});
});
```

**Comment by divanvb** [comment]
I might have found my issue. A misconfiguration on my part. Instead of service, I need to use host.

**Comment by OPTIMUS004** [comment]
This worked for me:

```
const nodemailer = require('nodemailer');

const transporter = createTransport({
                           service: "gmail.com",
                           auth: {
                          user: "<your mail>",
                          pass: "<your password>"
    }
});

const mailOption = {
            from: `yourmail@gmail.com`,
            to: 'receiver's mail',
            subject: "Subject of mail",
            html: "<h1>Hello there</h1>"
        };
        transporter.sendMail(mailOption, (error, info) => {
                if (error) {
                    return console.log(error);
                } else{
                    console.log('Email has been sent');
                    res.send(info);
                }
            });
    });

```

**Comment by razorcell** [comment]
In my case i had to **downgrade to version 4.7**. problem solved !

`npm install nodemailer@4.7.0`

`msg = queryA EREFUSED smtp.gmail.com`

https://stackoverflow.com/questions/54385031/nodemailer-fails-with-connection-refused-using-known-good-smtp-server

**Comment by rishabbahal9** [comment]
For mails to be sent from smtp.gmail.com make sure you have followed these 2 steps:

1. In your google account make sure you have **2-Step Verification** enabled.
2. Then go to [https://security.google.com/settings/security/apppasswords](https://security.google.com/settings/security/apppasswords). Click **Select app** and choose **Other (custom name)** from the dropdown and **click Generate**. You will get a **16 digit code**, _this code should be used as password in email configuration and user remains as your email. Also, make sure {secure: true}_

Here is my configuration:
```
transport: {
        host: 'smtp.gmail.com',
        port: 465,
        secure: true,
        auth: {
          user: '<myemail>',
          pass: '<16 digit code generated in step 2 above>',         
        },
```

**Comment by byteAr** [comment]
> En mi caso, tuve que **cambiar a la versión 4.7** . problema resuelto !
> 
> `npm install nodemailer@4.7.0`
> 
> `msg = queryA EREFUSED smtp.gmail.com`
> 
> https://stackoverflow.com/questions/54385031/nodemailer-fails-with-connection-refused-using-known-good-smtp-server

Esta respuesta resolvio mi porblema. Gracias

**Comment by Shoaib-Naseer** [comment]
> npm install nodemailer@4.7.0

solved issue

**Comment by tylerdgenius** [comment]
`npm install nodemailer@4.7.0`

This absolutely solved my problem

**Comment by klu-2100031674** [comment]
app.post("/forgot-password", async (req, res) => {
  const { email } = req.body;
  console.log({ email });
  try {
    const oldUser = await col.findOne({ email });
    if (oldUser === null) {
      return res.json({ status: "User Not Exists!!" });
    }
    const secret = JWT_SECRET + oldUser.password;
    const token = jwt.sign({ email: oldUser.email, id: oldUser._id }, secret, {
      expiresIn: "5m",
    });
    const link = `http://localhost:5000/reset-password/${oldUser._id}/${token}`;
    var transporter = nodemailer.createTransport({
      service: 'smtp.gmail.com',
      port: 465,
      secure: true,
      auth: {
        user: "mattajithendra07@gmail.com",
        pass: "qefzpilhvpfwxqid ",
      },
    });

    var mailOptions = {
      from: "mattajithendra07@gmail.com",
      to: email, // Use email provided in the request instead of hardcoded value
      subject: "Password Reset",
      text: link,
    };

    transporter.sendMail(mailOptions, function (error, info) {
      if (error) {
        console.log(error);
      } else {
        console.log("Email sent: " + info.response);
        return res.json({status:'Password reset link set to your gmail account'})
      }
    });
    console.log(link);
  } catch (error) {}
});


Error: connect ECONNREFUSED ::1:465
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {      
  errno: -4078,
  code: 'ECONNECTION',
  syscall: 'connect',
  address: '::1',
  port: 465,
  command: 'CONN'
}

**Comment by bluecomet1994** [comment]
Is there any updated features in the current version of the module?
All of the above solutions didn't worked for me now.

`
const transporter: nodemailer.Transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true,
    auth: {
        user: process.env.EMAIL_FROM,
        pass: process.env.EMAIL_PASSWORD
    }
});

const mailOptions = {
    from: process.env.EMAIL_FROM,
    to: process.env.EMAIL_TO,
    subject: "From BLUECOMET Administrator",
    html: `<h1>${message.name} sent you a message.</h1>
        <h3>${message.email}</h3>
        <p>Regarding the ${message.service} service...</p>
        <p>${message.message}</p>`
};

transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
        console.log(error);
    } else {
        res.status(200).json({
            success: true,
            email: info.response
        });
    }
});
`

**Comment by MbaliPuso** [comment]
I also need help. Here's my error below:
Error sending email: Error: connect ECONNREFUSED ::1:587
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -4078,
  code: 'ESOCKET',
  syscall: 'connect',
  address: '::1',
  port: 587,
  command: 'CONN'
}

My code:
// Create a transporter for sending emails
const transporter = nodemailer.createTransport({
  service: "smtp.gmail.com", // You can use any email service, like Gmail, Yahoo, etc.
  port: 587, // TLS port
  secure: false,
  auth: {
    user: "mbalipuso@gmail.com", // Replace with your email address
    pass: "pass", // Use environment variable for security
  },
  tls: {
    rejectUnautorized: false, // Allows self-signed certificates
  }
});
