### ISSUE TITLE
Timeout error while sending mails via gmail smtp

### ISSUE THREAD

**Issue by AshishkrGoyal** [nodemailer/nodemailer#890]
now my code look like it: 

**app.post('/contact/send', function (req, res) {
const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
      port: 465,
      secure: true,
    auth: {
      user: '15103140ashish@gmail.com',
      pass: 'ashish2@jiit'
    }
  });
const mailOptions = {
    from: '15103140ashish@gmail.com',
    to: 'myfriend@yahoo.com',
    subject: 'Sending Email using Node.js',
    text: 'That was easy!'
  };
transporter.sendMail(mailOptions, function(error, info){
    if (error) {
      console.log(error);
      res.redirect('/');
    } else {
      console.log('Email sent: ' + info.response);
    }
  });
})**

and getting the error : 

`{ Error: connect ETIMEDOUT 74.125.24.108:465
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNECTION',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '74.125.24.108',
  port: 465,
  command: 'CONN' }`

Anykind  of help is appreciated !
Thanks !

**Comment by AshishkrGoyal** [comment]
@andris9 please help in this issue:

complete code for nodemailer is hosted at : 
`https://github.com/AshishkrGoyal/nodemailer-err/`

and the server.js file is at : 
`https://github.com/AshishkrGoyal/nodemailer-err/blob/master/server.js/`

**Comment by andris9** [comment]
Timeouts are usually firewall issues. Check that you can connect to gmail from your machine

**Comment by Anwar0902** [comment]
Yes, that is the problem of the network firewall.  I was facing the same problem but when I switched my network to (jio network) it was working fine.

**Comment by pragsjain** [comment]
restart the node server , it worked for me. !

**Comment by Rehan-05** [comment]
@pragsjain  By stopping the node server, facing the same error.
