### ISSUE TITLE
Mail clients can't process event invitation mail

### ISSUE THREAD

**Issue by timojokinen** [nodemailer/nodemailer#894]
I'm trying to send an calendar event invitation via email. I followed the documentation step by step.
This is what my code looks like:

```
const smtpConfig = {
  host: 'smtp.office365.com',
  port: 587,
  secure: false,
  auth: {
    user: '....',
    pass: '....'
  },
};

const event = {
  title: 'Dinner',
  description: 'Nightly thing I do',
  start: [2018, 1, 15, 6, 30],
  duration: {
    minutes: 50
  },
  attendees: [{
    name: '....',
    email: '....'
  }]
}


ics.createEvent(event, (error, value) => {
  if (error) {
    console.log(error)
  }

  const transport = nodemailer.createTransport(smtpConfig);

  const message = {
    from: '....',
    to: ['.....'],
    subject: 'Dinner',
    text: 'Nightly thing I do',
    icalEvent: {
      content: value,
      method: 'request'
    }
  };

  transport.sendMail(message, (err, message) => {
    console.log(err, message);
  });
})
```

I double checked the ics string - it is valid. The email is sent but in the macOS mail client it is displayed as empty with no sender and no content.
In outlook mail client the email is displayed very weird, can't really describe it. It looks like a draft to create an event invitation and if the receiver answers to it an invitation is sent. But the initial Mail is not an invitation.
When I remove the icalEvent property on my message object the email is displayed correctly in every mail client.

If the ics is valid and my code is according to the docs what else can be the issue?

**Comment by andris9** [comment]
This is Office365 specific. For whatever reason the server reformats the message form a mime email into some weird calendar event. No idea why it does it. Works everywhere else though, no problems with Gmail for example.

**Comment by timojokinen** [comment]
I have the same problem with gmail. I actually tried it first with gmail and then tested with outlook.com to see if it is gmail specific.

**Comment by andris9** [comment]
If I use your example script and send through Office365 to Gmail, then this is what I see:

![screen shot 2018-06-14 at 15 54 03](https://user-images.githubusercontent.com/132242/41413277-4873a158-6feb-11e8-8cfe-ff25a00b8e69.png)

**Comment by andris9** [comment]
If I send the same message to Office365, then the message content looks like this:

(it is clearly rewritten and does not resemble the original ICAL event)

![screen shot 2018-06-14 at 15 56 10](https://user-images.githubusercontent.com/132242/41413345-7b07e3e0-6feb-11e8-909e-3febbd3a76ad.png)

**Comment by timojokinen** [comment]
Oh okay thanks. Is there any way to bypass this or do I have to send the ics as attachment?

**Comment by ganjisivaprakash** [comment]
The icalEvent method 'PUBLISH' is directly push the calendar events to calender or not.
