### ISSUE TITLE
Bcc header on mails to Bcc recipients

### ISSUE THREAD

**Issue by mark-langer** [nodemailer/nodemailer#898]
Hi team, nodemailer is a great framework. Thanks for maintaining such a great piece of software!

Issue:
Setting the To and Bcc recipients sends an e-mail to each person. However, the Bcc recipient's e-mail does not include a proper Bcc header. This header is present in e-mail sent by commonly-used mail clients, such as Gmail. The problem with this is that the Bcc recipient cannot see through what e-mail address he received that e-mail.

Example mail options:
```
const mailOptionsTo = {
            from        : mark@example.org,
            to            : brad@example.org,
            bcc           : lucy@example.org,
            subject     : 'My Subject',
            text          : 'Hello World'
        };
```

I would expect brad@example.org to receive an e-mail without a Bcc header, and lucy@example.org to receive an e-mail with To and Bcc headers, with Bcc being set to her own address. However, both the "To" and the "Bcc" recipient receive an e-mail without the "Bcc" header.

We're using transporter options in this shape:

```
const transporterOptions        = {
    host   : 'myhost.com',
    port   : 465,
    secure : true,
    auth   : {
        user : 'user@myhost.com',
        pass : 'password1234'
    }
};
```

node version: 8.9.4
nodemailer version: 4.6.7

Would this be possible to fix? I saw that there are some keepBcc properties in the code but that option does not seem to affect the standard transporter.

**Comment by andris9** [comment]
That is not how bcc header works. When sending to multiple recipients you provide a single rfc822 formatted message and a list of recipients to the SMTP server. There is no way of setting different headers per recipient, other than sending multiple copies (instead of sending 1 email to brad@example.org and lucy@example.org you'd send 1 custom email that does not include the bcc field to brad@example.org and 1 custom email that includes the bcc header to lucy@example.org).

If you want to know to which address a bcc message was sent, look for the Delivered-To header in the email, this line is inserted by your MX server.

**Comment by mark-langer** [comment]
Thanks for the quick reply!

We tried sending a separate copy but nodemailer does not seem to set a Bcc header at all. Even with a value in the Bcc field of the `mailOptions` object a Bcc header is not set. To stick with the example, it seems impossible to send a Bcc email to lucy@example.org that actually has a Bcc header containing her email address.

According to [the docs](https://nodemailer.com/message/),  the `header` property of the `mailOptions` object is reserved for custom headers, as opposed to standard headers like Bcc.

This is an excerpt from the email logged by nodemailer's standard debugging option based on the mailOptions object posted above, including the Bcc property 'lucy@example.org':

```
...
debug: { component: 'smtp-connection',
  sid: 'L0nZuTdHxxx',
  tnx: 'message' }
'Content-Type: multipart/alternative;\r\n boundary="--_XXX-1ac78008284x111x-Part_1"
From: mark@example.org
To: lucy@example.org
Reply-To: info@example.org
Subject: =?UTF-8?Q?My_Subject?=
Message-ID: <316c2a0d-11xx-89e8-82c0-072e416bfb20@example.org>
Date: Thu, 21 Jun 2018 11:09:33 +0000
MIME-Version: 1.0'
...
```

Shouldn't there be a Bcc header like `Bcc: lucy@example.org` present now?

**Comment by andris9** [comment]
Basically there is an internal option called `keepBcc` that if set to true keeps the Bcc header but this option is not exposed publicly. I'm busy with other things so you might want to take a look, make the option public and create a pull request for the changes. Just grep the code for `keepBcc` to see how and where it is used.
