### ISSUE TITLE
Error: certificate expired while using ethereal email

### ISSUE THREAD

**Issue by pselden** [nodemailer/nodemailer#903]
I'm trying to send to the ethereal email smtp as shown in the example (exact copy/paste). However I get the following error:

```
{ Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1046:34)
    at TLSSocket.emit (events.js:180:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'ESOCKET', command: 'CONN' }
```
Is this some configuration on my end that needs to be changed?

**Comment by andris9** [comment]
Should be fixed now

**Comment by nr2019** [comment]
Hi. How do you resolve this problem?
I have the same problem. 
I need send a mail from my angular project. The angular project works fine, but when i compile my node code ( almost copy paste from node documentation ) with nodemon, the certificate error don't let me copile the node code.
Thanks.

**Comment by leoderigo** [comment]
Having this problem right now. Any results on this?
