### ISSUE TITLE
Set Custome Headers

### ISSUE THREAD

**Issue by z1000zhihe** [nodemailer/nodemailer#904]
I'm now intergrated with a third party service which could send email by SMTP, and they supoort custome headers, but headers must prefix with "SC-Customer-**", when set those header with nodemailer, they are converetd to "Sc_Customer-xx", then they could not recognize those headers now.

I want to keep those headers without convert, how could I do this?

**Comment by andris9** [comment]
See this example for using your own custom normalizer for message header
keys:
https://github.com/nodemailer/nodemailer/blob/3e3ba4f30ad5a73f037f45d3e36a9361ca43a318/examples/custom-headers.js#L13-L14

**Comment by llwslc** [comment]
Only have attachments is valid?
