### ISSUE TITLE
MailOptions: From is not populating

### ISSUE THREAD

**Issue by christopherbecker** [nodemailer/nodemailer#906]
I've followed the online example and in my `mailOptions` I've added a no-reply email, however upon receiving the email it is showing my smtp logged in email as the sender.

So in short. `Auth user email` is being shown in sent email and not the prescribed `from` in the `mailOptions`.

**Comment by andris9** [comment]
This happens with servers like Gmail that do not allow to send mail from non.verified addresses

**Comment by minotaurrr** [comment]
@andris9 is there a workaround or settings in gmail i can mess with to make this work?
