### ISSUE TITLE
Support less permissive scopes for gmail

### ISSUE THREAD

**Issue by Palisand** [nodemailer/nodemailer#907]
The `https://mail.google.com/` scope should not be required if all you want to do is send email on behalf of an authenticated user.

The `https://mail.google.com/` scope grants:
> Full access to the account, including permanent deletion of threads and messages. This scope should only be requested if your application needs to immediately and permanently delete threads and messages, bypassing Trash; all other actions can be performed with less permissive scopes.

[Source](https://developers.google.com/gmail/api/auth/scopes)

**My attempts to use the much safer `https://www.googleapis.com/auth/gmail.send` scope with Nodemailer have failed.**

Suppose an attacker gets a hold of the access token. Sure, it's short lived, but the attacker still has a small window during which he can **delete messages** rather than being limited to sending them!

**Comment by andris9** [comment]
Gmail has granular scope access only for the HTTP API. For SMTP, IMAP, POP3 etc. there's only a single scope, the general mail access scope.

**Comment by Palisand** [comment]
Got it, thanks. I have to say, you've got some fast response time. It's no wonder this repo is usually free of issues.
