### ISSUE TITLE
Publish separate packages again

### ISSUE THREAD

**Issue by gabegorelick** [nodemailer/nodemailer#908]
I understand the desire to switch to a monorepo to ease maintenance. However, with tools like [Lerna](https://github.com/lerna/lerna) you can have a monorepo and still publish separate npm packages. Would you consider using something like? 

(Apologies that this is not a real bug).

**Comment by andris9** [comment]
Not really. If you need some specific parts from the package that are not exposed on the main level you can use these like this:

    var addressparser = require(‘nodemailer/lib/addressparser’);
