### ISSUE TITLE
Have such a problem : Unable to resolve module 'net'

### ISSUE THREAD

**Issue by cx5168** [nodemailer/nodemailer#911]
installed: nodemailer: "^4.6.7"
Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.0 => 16.3.0
  react-native: 0.54.4 => 0.54.4

bundling failed: Error: Unable to resolve module `net` from `..\node_modules\nodemailer\lib\mailer\index.js`: Module does not exist in the module map

How to solve it?

**Comment by andris9** [comment]
Nodemailer works in server only, not in a front end app
