### ISSUE TITLE
Interrupt Nodemailer OnClick?

### ISSUE THREAD

**Issue by prometeomcclellan** [nodemailer/nodemailer#912]
Is it possible to interrupt bulk when click on button from template?

I have tried by closing the transporter when I click the button, but nothing!

**Comment by andris9** [comment]
You can not abort a message once you have passed it to the sendMail method

**Comment by Codmnk** [comment]
In worst case scenario, you may try to restart the server.

**Comment by prometeomcclellan** [comment]
Thanks for your answer.
