### ISSUE TITLE
Nodemailer attachment is corrupting attached file

### ISSUE THREAD

**Issue by charlysnife** [nodemailer/nodemailer#913]
I am send an attached word document to an email using nodemailer. In the email the file displays as a non-word document. Making it not to open after been downloaded. I don't knw what is causing this issue. I tried attaching an image. The image cannot be opened after been downloaded. 

Please i need an assistance on this.

**Comment by andris9** [comment]
usually it means that the file is already corrupted when you provide it. for example if there is a race condition where you generate file later than you send the message

**Comment by charlysnife** [comment]
The file is not corrupted before sending it. After sending it when i entered the file path on my browser it prompted a download dialogue for me to download it. 

![image](https://user-images.githubusercontent.com/16558094/43097320-a69bba04-8eb3-11e8-8e5b-7082656f13ba.png)

That is an image i attached to an email. When the image is click for download. It is no longer showing as an image file.

**Comment by Codmnk** [comment]
Are you attaching file from buffer or disk memory? Try to debug if the file is you are attaching is completely uploaded/saved on buffer/disk memory and it is readable. And also, Can you check if you have a correct file extension.
