### ISSUE TITLE
nodemailer smtp request on one.com server

### ISSUE THREAD

**Issue by Gitikaj9** [nodemailer/nodemailer#914]
Error:
{ Error: connect ECONNREFUSED 127.0.0.1:465
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNECTION',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 465,
  command: 'CONN' }

Here is my code.
var transporter = nodemailer.createTransport(smtpTransport({
	service: 'send.one.com',
	port: 465,
	secure: true,
	auth: {
		user: '', // my mail
		pass: ''
	}
}));

**Comment by andris9** [comment]
use

```
var transporter = nodemailer.createTransport(smtpTransport({
	service: 'One',
	auth: {
		user: '', // my mail
		pass: ''
	}
}));
```

**Comment by Gitikaj9** [comment]
@andris9

Got this issue solved as.
In nodemailer transport, Instead of service : 'send.one.com'
Replace as "host: 'send.one.com'"

This works for me.
