### ISSUE TITLE
Authentication issues when sending via SMTP

### ISSUE THREAD

**Issue by guypaskar** [nodemailer/nodemailer#916]
Hello,

I am getting this error when trying to use SMTP transport - I've been debugging this for hours without luck - what are your recommendations?
![image](https://user-images.githubusercontent.com/1195952/43207090-bf464a88-9016-11e8-859a-b8eb239192ac.png)

**Comment by guypaskar** [comment]
With debug = true
![image](https://user-images.githubusercontent.com/1195952/43208360-c5866542-9019-11e8-87fe-a00aef369a6f.png)

**Comment by andris9** [comment]
Seems like a very old version of Nodemailer that is not supported anymore. Other than that the logs seem correct so your credentials are not accepted by the server.

**Comment by guypaskar** [comment]
Ok, thank you. I will try to update.
