### ISSUE TITLE
Working nodemailer to a proxy with a host server

### ISSUE THREAD

**Issue by mondemon** [nodemailer/nodemailer#917]
I was trying to send an email thru nodemailer but i always get this error.

{ Error: Greeting never received                                                    at SMTPConnection._formatError (C:\Users\c89149\Desktop\workspace\ePolicy\svc-despatch\node_modules\nodemailer\lib\smtp-connection\index.js:606:19)             at SMTPConnection._onError (C:\Users\c89149\Desktop\workspace\ePolicy\svc-despatch\node_modules\nodemailer\lib\smtp-connection\index.js:579:20)                 at Timeout._greetingTimeout.setTimeout (C:\Users\c89149\Desktop\workspace\ePolicy\svc-despatch\node_modules\nodemailer\lib\smtp-connection\index.js:520:22)     at ontimeout (timers.js:386:11)                                                 at tryOnTimeout (timers.js:250:5)                                               at Timer.listOnTimeout (timers.js:214:5) code: 'ETIMEDOUT', command: 'CONN' }      

Tried searching for ehlo commands in node but can't come up with an idea of how it works/and how am i gonna use it.

This is my code.

const nodemailer = require('nodemailer');
	nodemailer.createTestAccount((err, account) => {
		    // create reusable transporter object using the default SMTP transport
		    	 let transporter = nodemailer.createTransport({
			        host: 'ip.address.of.server',
			        port: 25, 
			        debug: true,
			        secure: false,
			        proxy: 'http://ip.address.proxy.here:8080/',
			        
			       
			    });

			    
			    	// setup email data with unicode symbols
			    let mailOptions = {
			        from: '"name of sender" <email.address.from@email.com>', // sender address
			        to: 'name of recipient, email.address.to@email.com', // list of receivers
			        subject: 'Hello', // Subject line
			        text: 'Hello world?', // plain text body
			        html: '<b>Hello world?</b>' // html body
			    };

		       
		    // send mail with defined transport object
		    transporter.sendMail(mailOptions, (error, info) => {
		        if (error) {
		            return console.log(error);
		        } 
		        console.log('Message sent: %s', info.messageId);

		    });
		});
                                  

Thanks in advance!!!!

**Comment by andris9** [comment]
In order of this to work
* your proxy must support CONNECT protocol
* your proxy software must allow port 25
* firewall in your proxy must allow port 25

Not all HTTP proxies support this

**Comment by iosifnicolae2** [comment]
@andris9 could you please recommend a proxy that is compatible with nodemailer? 

Thank you!
