### ISSUE TITLE
Redirect all emails in development environments

### ISSUE THREAD

**Issue by avrelaun** [nodemailer/nodemailer#919]
Would it be possible to redirect all emails sent via the transporter.sendMail method to an email specified in the config of the related transporter ?

Using nodemailer createTransport defaults while preventing the recipient from being overridden for example, while adding the original email address to the body of the message.

This could be enabled for development and integration purposes, and left disabled in production environments.

**Comment by andris9** [comment]
This is usually handled by multiple transport setups - if you're in production then use Sendgrid etc to set up Nodemailer, if you're in dev, then use [Ethereal.email](https://ethereal.email/) or Mailtrap or any other similar service.
