### ISSUE TITLE
NodeMailer SMTP email issue. Invalid login: 535 5.7.3 Authentication unsuccessful

### ISSUE THREAD

**Issue by sravaniduggirala** [nodemailer/nodemailer#920]
I am using Node 8.11.3 to write an email client.This piece of code works with gmail but I am facing the following error when trying to configure my company's mail server.I tried logging into outlook web with my credentials (sane as in the code) and I am able to login without any issues.

`POST /send-email 200 5133.373 ms - 26
{ Error: Invalid login: 535 5.7.3 Authentication unsuccessful
    at SMTPConnection._formatError (C:\HomeSite\email-service\node_modules\smtp-connection\lib\smtp-connection.js:528:15)
    at SMTPConnection._actionAUTHComplete (C:\HomeSite\email-service\node_modules\smtp-connection\lib\smtp-connection.js:1231:30)
    at SMTPConnection.<anonymous> (C:\HomeSite\email-service\node_modules\smtp-connection\lib\smtp-connection.js:1199:14)
    at SMTPConnection._processResponse (C:\HomeSite\email-service\node_modules\smtp-connection\lib\smtp-connection.js:669:16)
    at SMTPConnection._onData (C:\HomeSite\email-service\node_modules\smtp-connection\lib\smtp-connection.js:493:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
  code: 'EAUTH',
  response: '535 5.7.3 Authentication unsuccessful',
  responseCode: 535,
  command: 'AUTH LOGIN' }
`

Below is my piece of code:
`var nodeMailer = require('nodemailer');
var smtpTransport = require('nodemailer-smtp-transport');
var bodyParser = require('body-parser');
app.post('/send-email', function (req, res) {
    console.log('Received form info');
    var transporter = nodeMailer.createTransport(smtpTransport({
        host: 'hsboscas.camelot.local',
         auth: {
            user: 'user.name',
            pass: '123'
        },
        secureConnection: false

    }));
    console.log("To object: "+req.body.to);
    var mailOptions = {
        from: 'user.name@abcompany.com', // sender address
        to: req.body.to, // list of receivers
        subject: req.body.subject, // Subject line
        //text: req.body.body, // plain text body
        html: '<b>Yohoo...first mail!!!</b>' // html body

    };

    transporter.verify(function(error, success) {
        if (error) {
            console.log(error);
        } else {
            console.log('Server is ready to take our messages');
        }
    });

    transporter.sendMail(mailOptions, function(error, info) {
        if (error)
            console.log("Error: "+error);
        else
            console.log("Email sent successfully. "+info);

        //console.log('Message %s sent: %s', info.messageId, JSON.stringify(info));
        res.send('Email operation attempted.');
    });
});
`

**Comment by andris9** [comment]
This means that your server does not accept your credentials. Some servers expect special configuration in order to allow clients using SMTP to prevent spam.

**Comment by Alex1233456** [comment]
@sravaniduggirala  hello , i am having the same issue now. Could you please tell me how did you fixed your problem? i am using the same code and having the same error. I would be very thankful for each help. this is how my code looks like `var nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport({
    host: "smtp.office365.com", // hostname
    proxy:"Proxy of the company",
    secureConnection: false, 
    port: 587, 
    tls: {
       ciphers:'SSLv3'
    },
    auth: {
        user: 'MYEMAIL@COMPANYNAME.com',
        pass: 'MYPASS'
    }
});

// setup e-mail data, even with unicode symbols
var mailOptions = {
    from: 'MYEMAIL@COMPANYNAME.com', // sender address (who sends)
    to: 'MYEMAIL@COMPANYNAME.com', // list of receivers (who receives)
    subject: 'Hello ', // Subject line
    text: 'Hello world ', // plaintext body
    html: '<b>Hello world </b><br> This is the first email sent with Nodemailer in Node.js' // html body
};

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }

    console.log('Message sent: ' + info.response);
});
`

**Comment by kishoreaoe** [comment]
@Alex1233456 , Yes, Me too has the same issue. could not able to figure out. With the same credentials i could able to connect in java too.

**Comment by Dass987** [comment]
I think gmail has to give us a some kind of permission, I'm having the same issue, the same 535 response code.

This is my code: 

`var nodemailer = require('nodemailer');

var transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: 'mail1@gmail.com',
    pass: 'mail123'
  }
});

var mailOptions = {
  from: 'mail1@gmail.com',
  to: 'mail2@gmail.com, mail3@gmail.com, mail4@gmail.com',
  subject: 'Sending Email using Node.js',
  text: '<h1>That was easy!</h1><br><p>It is not working!!!</p>'
};

transporter.sendMail(mailOptions, function(error, info){
  if (error) {
    console.log(error);
  } else {
    console.log('Email sent: ' + info.response);
  }
});`

**Comment by AayushiGK** [comment]
@kishoreaoe  had any luck with the code on nodeside

**Comment by siege-nnn** [comment]
I had a similar issue and like all of you, using the password elsewhere worked.

I did however find out that removing special characters from the password worked for me.

So from a complex password similar to H*(ya8sdYDHa5$Dr6 , I had to settle with combination of characters / numbers only.

I hope it helps someone else:)

**Comment by y-sumanth** [comment]
I had same problem. Spent a lot of time on it. Stupidly, its a typo at auth.user. Please check username and password.

**Comment by ngaffa** [comment]
First you should verify your credentials
Second : if you send your email via cloud function you should add your credit card with google cloud because external connection is not allowed (i has the same issue)
You just subscribe your credit card and you still with free plan

**Comment by deadkEEper1** [comment]
Special symbols caused a problem. Solution is application password

**Comment by Ddevon** [comment]
same problem.. Looks like the "-" (hyphen) caused the issue in the email address.

**Comment by OnnoGabriel** [comment]
@Ddevon, did you solve this? Can the hyphen be escaped or something?

**Comment by druskacik** [comment]
I had the same problem and the issue was this:

I was using credentials provided by my hosting provider. The default setting was that the credentials were secured with GEO security, meaning the credentials wouldn't work outside my country. I was deploying on Heroku whose servers are abroad. That's why I could send emails from localhost but not from deployed app.

After I disabled the GEO security everything worked as it should.

**Comment by realronchi** [comment]
Hello @druskacik, How do I disable GEO security settings?

**Comment by druskacik** [comment]
@realronchi 

What credentials are you using? I used SMTP credentials I got with the hosting I own, and the GEO security settings were on the website of my hosting provider.

**Comment by Ceredavide** [comment]
Hello,
I am still have this problem with nodemailer and outlook.
`        host: "smtp-mail.outlook.com", // hostname
        secureConnection: false, // TLS requires secureConnection to be false
        port: 587, // port for secure SMTP
        auth: {
            user: process.env.EMAIL,
            pass: process.env.PASSWORD
        },
        tls: {
            ciphers:'SSLv3'
        }`
When I try to send an email it gives me the following error:
`Error: Invalid login: 535 5.7.3 Authentication unsuccessful [ZR0P278CA0011.CHEP278.PROD.OUTLOOK.COM]
    at SMTPConnection._formatError (/Users/ceredavide/Documents/GitHub/LiLo-App/backend/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionAUTHComplete (/Users/ceredavide/Documents/GitHub/LiLo-App/backend/node_modules/nodemailer/lib/smtp-connection/index.js:1523:34)
    at SMTPConnection.<anonymous> (/Users/ceredavide/Documents/GitHub/LiLo-App/backend/node_modules/nodemailer/lib/smtp-connection/index.js:1481:18)
    at SMTPConnection._processResponse (/Users/ceredavide/Documents/GitHub/LiLo-App/backend/node_modules/nodemailer/lib/smtp-connection/index.js:942:20)
    at SMTPConnection._onData (/Users/ceredavide/Documents/GitHub/LiLo-App/backend/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/Users/ceredavide/Documents/GitHub/LiLo-App/backend/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  code: 'EAUTH',
  response: '535 5.7.3 Authentication unsuccessful [ZR0P278CA0011.CHEP278.PROD.OUTLOOK.COM]',
  responseCode: 535,
  command: 'AUTH LOGIN'
}`
I contected my email provider and I have smtp activated.
My password contains special characters, and with the email policies, my password must contain at least one special character....
Some help?

**Comment by ketan-mehta1304** [comment]
https://myaccount.google.com/u/3/lesssecureapps go to this link and do on the less secure app on

**Comment by bryanakitchen** [comment]
A colleague had this same issue using a gmail account - removing the special characters from the password did the trick!

**Comment by AlessioToniolo** [comment]
Hello, I am also having this problem with outlook. I have an exchange online (plan 1) with Microsoft, and I enabled SMTP authentication, but I have the same 535 authentication unsuccessful. My nodemailer transporter host uses 'smtp.office365.com', which I am not sure is associated with exchange online or not, but I verified that my email and password works. Any help is appreciated.

**Comment by Piyush-FSD** [comment]
> I had same problem. Spent a lot of time on it. Stupidly, its a typo at auth.user. Please check username and password.

Same here. When I copied the email and password from my testAccount object, it auto-populated the key at the end of the both values. 

user: testemail.email.user (.user NOT needed)
pass: testpass.pass (.pass NOT needed)

**Comment by CHENG-Alvin** [comment]
> I had same problem. Spent a lot of time on it. Stupidly, its a typo at auth.user. Please check username and password.

Use Typescript👍

**Comment by SMEETT** [comment]
> I had a similar issue and like all of you, using the password elsewhere worked.
> 
> I did however find out that removing special characters from the password worked for me.
> 
> So from a complex password similar to H*(ya8sdYDHa5$Dr6 , I had to settle with combination of characters / numbers only.
> 
> I hope it helps someone else:)

This is still an issue and it's still solved by removing special characters from the password.

**Comment by kyung-lee-official** [comment]
> Hi @andris9 I am able to use the same configuration and credentials and send out an email using Java or .Net successfully.

Use the same .env file, pulled from the same git repo, works on my Windows computer, but reports `535 5.7.3 Authentication unsuccessful` on my server.
