### ISSUE TITLE
NodeMailer SMTP email issue. Invalid login: 535 5.7.3 Authentication unsuccessful

### ISSUE THREAD

**Issue by sravaniduggirala** [nodemailer/nodemailer#922]
I am using Node 8.11.3 to write an email client.This piece of code works with gmail but I am facing the following error when trying to configure my company's mail server.I tried logging into outlook web with my credentials (same as in the code) and I am able to login without any issues.

`POST /send-email 200 5133.373 ms - 26 { Error: Invalid login: 535 5.7.3 Authentication unsuccessful at SMTPConnection._formatError (C:\HomeSite\email-service\node_modules\smtp-connection\lib\smtp-connection.js:528:15) at SMTPConnection._actionAUTHComplete (C:\HomeSite\email-service\node_modules\smtp-connection\lib\smtp-connection.js:1231:30) at SMTPConnection.<anonymous> (C:\HomeSite\email-service\node_modules\smtp-connection\lib\smtp-connection.js:1199:14) at SMTPConnection._processResponse (C:\HomeSite\email-service\node_modules\smtp-connection\lib\smtp-connection.js:669:16) at SMTPConnection._onData (C:\HomeSite\email-service\node_modules\smtp-connection\lib\smtp-connection.js:493:10) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) at readableAddChunk (_stream_readable.js:250:11) at Socket.Readable.push (_stream_readable.js:208:10) code: 'EAUTH', response: '535 5.7.3 Authentication unsuccessful', responseCode: 535, command: 'AUTH LOGIN' }`

Below is my piece of code:
```
var nodeMailer = require('nodemailer');
var smtpTransport = require('nodemailer-smtp-transport');
var bodyParser = require('body-parser');
app.post('/send-email', function (req, res) {
console.log('Received form info');
var transporter = nodeMailer.createTransport(smtpTransport({
host: <company host>',
auth: {
user: 'user.name',
pass: '123'
},
secureConnection: false
}));
console.log("To object: "+req.body.to);
var mailOptions = {
    from: 'user.name@company.com', // sender address
    to: req.body.to, // list of receivers
    subject: req.body.subject, // Subject line
    html: '<b>Yohoo...first mail!!!</b>' // html body
};
transporter.sendMail(mailOptions, function(error, info) {
    if (error)
        console.log("Error: "+error);
    else
        console.log("Email sent successfully. "+info);

    res.send('Email operation attempted.');
});
});
```

The exact credentials or the configuration info for the email server and authentication works with a Java email client.

**Comment by andris9** [comment]
This error means that Nodemailer is unable to authenticate itself to the server using the credentials you provided. There might be many different reasons why it is so, I suggest checking the server side logs to see why it did not accept the authentication attempt.
