### ISSUE TITLE
lib/addressparser should use `punycode.toASCII` to properly parse encoded characters

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#923]
<https://github.com/bestiejs/punycode.js/#punycodetoasciiinput>

**Comment by andris9** [comment]
Why? If anything I’d rather normalize the other way, eg decoding punycode and mime-words into unicode.

**Comment by andris9** [comment]
Internally Nodemailer does [apply punycode.toASCII](https://github.com/nodemailer/nodemailer/blob/bc2b52082186fdf8712b8a4737abe88e46061c3e/lib/mime-node/index.js#L1141-L1164) for the addresses in envelope object, this is needed for SMTP transport (SMTP servers usually do not accept unicode domain names).

**Comment by andris9** [comment]
Just realized that I need the address parser output as similar to the original as possible in my other modules that depend on it. Btw when doing dns resolutions you should always validate the encoding and format of the domain at place anyway as the dns functions might throw exceptions (not returning an error with callback but actually throwing exceptions) with other stuff besides unicode.

**Comment by niftylettuce** [comment]
np, thanks @andris9 for the explanation.  makes sense w/your other modules for consistency.  if you have suggestions on how to rewrite this please lmk https://github.com/niftylettuce/forward-email/commit/c9a48c2979a32c065d5257ec42be512ae8caf25a!
