### ISSUE TITLE
Nodemailer Help

### ISSUE THREAD

**Issue by tomwilson454** [nodemailer/nodemailer#925]
Please how i can i set up nodemailer to automatically grab %Email% while sending mails to multiple emails.
Example : Hello %Email%

I expect the %Email% code  to auto grab the receivers emails.

Will appreciate your help.

**Comment by andris9** [comment]
You should probably look into [this module](https://github.com/niftylettuce/email-templates)

**Comment by tomwilson454** [comment]
I really dont understand how that module works...dont know much about coding,i just use nodemailer for sending normal emails,can you please help detail out how to get this done.
