### ISSUE TITLE
Database Error for ethereal.email 

### ISSUE THREAD

**Issue by Kikobeats** [nodemailer/nodemailer#926]
Hello,

I'm getting the following error from the code when I want to send a message using a previous declared ethereal account:

```
Error: Invalid login: 535 Topology was destroyed
```

Also on the web, if you try to create a new user, you get a Database Error: https://ethereal.email/create

Looks like something is wrong in the database connection, hope all would be restored.

I tried to send an email to `info@ethereal.email` but it was not reachabled

```
550 I cannot deliver mail for <info@ethereal.email>
```

**Comment by andris9** [comment]
Should work now, server was out of memory, so I restarted it.

**Comment by Kikobeats** [comment]
Yes, thanks! 🙂
