### ISSUE TITLE
Sending With %Email%

### ISSUE THREAD

**Issue by tomwilson454** [nodemailer/nodemailer#927]
I really dont understand how the [module](https://github.com/niftylettuce/email-templates) works...dont know much about coding,i just use nodemailer for sending normal emails,can you please help detail out how to get this done...need sending mail to multiple users using the %Email% .

**Comment by andris9** [comment]
Sorry, too busy, please ask your support questions regarding Nodemailer usage or anything else in [StackOverflow](https://stackoverflow.com/search?q=nodemailer), there are tons of people who would like to help
