### ISSUE TITLE
Support promises for MailComposer build()

### ISSUE THREAD

**Issue by BrendanBall** [nodemailer/nodemailer#929]
Hi

This project looks really awesome and easy to use so far, really straightforward. I'm needing to use it just to build a raw email using the MailComposer. Given you have docs for this at https://nodemailer.com/extras/mailcomposer/ , I assume this is an official feature that I can use. It would be awesome if the `build` function can support promises, just as you've added promise support to a few of the more used apis.

Thanks

**Comment by andris9** [comment]
Added promise support to master branch, this gets released with the next version of Nodemailer, whenever that happens. See example: https://github.com/nodemailer/nodemailer/blob/master/examples/mailcomposer.js
