### ISSUE TITLE
Unable to get access token from Google

### ISSUE THREAD

**Issue by wdetac** [nodemailer/nodemailer#931]
After setting up the SMTP `transporter`, I called `transporter.verify()` and the following is the error response:

    {   Error: Invalid status code 400
        at ClientRequest.req.on.res (xx/node_modules/nodemailer/lib/fetch/index.js:221:23)
        at ClientRequest.emit (events.js:160:13)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:548:21)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
        at TLSSocket.socketOnData (_http_client.js:439:20)
        at TLSSocket.emit (events.js:160:13)
        at addChunk (_stream_readable.js:269:12)
        at readableAddChunk (_stream_readable.js:256:11)
        at TLSSocket.Readable.push (_stream_readable.js:213:10)
        at TLSWrap.onread (net.js:599:20)
        type: 'FETCH',
        sourceUrl: 'https://accounts.google.com/o/oauth2/token' }

I then extract the JWT from nodemailer module and make a direct `POST` request externally to `https://accounts.google.com/o/oauth2/token` with that JWT,
google return a correct access token to me. If I use that access token, everything works well and email can be sent successfully. nodemailer just cannot receive access token correctly.

**Comment by andris9** [comment]
Could you somehow check what Nodemailer sends to Google, eg the headers and POST body? Does it look valid?

**Comment by wdetac** [comment]
I have checked the variable passed to `fetch`, looks valid.

**Comment by wdetac** [comment]
I am using latest v4.6.8 if it matters

**Comment by andris9** [comment]
Error 400 should mean an invalid request. Is there something different beween your manual request and the one Nodemailer makes? Maybe something with headers? When using curl you can use "--trace-ascii output.filename" option to see what was actually sent to the server

**Comment by wdetac** [comment]
The reason for this issue because my system time is different from the real time. `hwclock -s -u` set my clock from hardware clock fix this issue. Since the underlay error message `Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.` not throw by nodemailer, it is difficult to figure out. I suggest throwing the entire original error object instead.
