### ISSUE TITLE
no callback on mongoose save

### ISSUE THREAD

**Issue by leanpilar** [nodemailer/nodemailer#935]
I was trying to send a new email after new order placed.

In the others route, my nodemailer works fine with page render and attachments after creating pdf files.

so for test I move my function in the same route file where it works, and now it has the same transporter, same mailOptions,
and  same

```
transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
        return console.log(error);
    }
    console.log('Message sent: %s', info.messageId);
});
```
in the function after save no callback is called but in the findByIdAndUpdate works fine

all variable tested, and was tested with hardcoded values.

I use app.render to get html code from hbs engine in both case
this is the main difference

```
newSchema.save( (err, model) => {
    myfunctionSendMail(model);
})
Model.findByIdAndUpdate( id, newObject, (err, model) => {
    myOthersfunctionSendMail(model);
})
```

After testing the same code commenting out the mongoose save funcion, the mail was sent like it suppose to....
Is there a workaround for this??

"nodemailer": "4.6.8",
node v10.7.0

**Comment by andris9** [comment]
I don't believe this is a Nodemailer issue. Check your code logic.
