### ISSUE TITLE
TypeError: this.mailcomposer.setMessageOption is not a function

### ISSUE THREAD

**Issue by muhammad-dev** [nodemailer/nodemailer#936]
I'm getting this Error anyone can help?

 TypeError: this.mailcomposer.setMessageOption is not a function
0|app      |     at Nodemailer.setGeneralOptions (/root/node/node-structure/node_modules/express-mailer/node_modules/nodemailer/lib/nodemailer.js:269:23)
0|app      |     at Nodemailer.generateMailObject (/root/node/node-structure/node_modules/express-mailer/node_modules/nodemailer/lib/nodemailer.js:219:10)
0|app      |     at Nodemailer.sendMail (/root/node/node-structure/node_modules/express-mailer/node_modules/nodemailer/lib/nodemailer.js:207:10)
0|app      |     at /root/node/node-structure/node_modules/express-mailer/node_modules/nodemailer/lib/nodemailer.js:68:20
0|app      |     at /root/node/node-structure/node_modules/express-mailer/node_modules/nodemailer/lib/nodemailer.js:195:9
0|app      |     at _combinedTickCallback (internal/process/next_tick.js:95:7)
0|app      |     at process._tickDomainCallback (internal/process/next_tick.js:198:9)

**Comment by andris9** [comment]
How did you end up with that error? Which Nodemailer version are you using and how?
