### ISSUE TITLE
transporter.verify() leaking server ip

### ISSUE THREAD

**Issue by ceo** [nodemailer/nodemailer#938]
Hello folks! 

Im having this issue here..

transporter.verify() is leaking my real server IP instead of using the proxy on the options

I am creating the transporter with :

```
TransportOptions = {
        name: options.hostname ? options.hostname : 'localhost',
        secure: config.ssl || false, // use SSL
        host: config.host,
        port: config.port,
        proxy: 'socks5://82.196.3.21:10080', 
        auth: {
          user: user,
          pass: password
        },
        pool: true,
        tls: {
          rejectUnauthorized: false
        },
        logger: true,
        debug: true
      }

      transporter = nodemailer.createTransport(TransportOptions)
      transporter.set('proxy_socks_module', require('socks'))
 

// The leak starts here 
await transporter
        .verify()
        .then(() => {
          console.log(`[SMTP] Logged in OK (${user}:${password})`)
          return true
        })
        .catch(() => {
          console.log(`[SMTP] Cannot connect with this SMTP config`)
          return false
        })
```

But `verify()` is ignoring my `TransportOptions.proxy` and showing my real IP to the SMTP server..

How is this possible ?

Thanks!

**Comment by LuKks** [comment]
https://github.com/nodemailer/nodemailer/blob/v2.3/examples/proxy/socks-proxy.js
The example doesn't use transporter.set and try removing the pool and tls config (temporally).
How you know that showing your real IP?

Anyway, your code seems ok, so try connect the proxy to browser and check if works fine.
