### ISSUE TITLE
Update documentation to reflect #814

### ISSUE THREAD

**Issue by caitlinmckown** [nodemailer/nodemailer#942]
Hello! I apologize if this is the wrong place to add this, but it would be helpful to update the documentation (and possibly examples) to reflect the answer to issue #814.  #814 recommends letting Nodemailer handle connections as opposed to using transporter.close().

Currently, the [documentation ](https://nodemailer.com/smtp/pooled/) for transporter.close() reads: 

> If transporter uses pooling then connections are kept open even if there is nothing to be sent. To close all pending connections you can use the close() method

It wasn't clear to me if I needed to use transporter.close() to prevent connections from being open and idling forever. It might be helpful to include information about the use case, along the lines of:

> If transporter uses pooling then connections are kept open even if there is nothing to be sent. Connections that idle for longer than the socketTimeout will be closed automatically and reopened once there's more mail to send. You can also use transporter.close() to clean up all connections.

**Comment by andris9** [comment]
Thanks, updated the docs to use the proposed wording [here](https://nodemailer.com/smtp/pooled/#transporter-close)
