### ISSUE TITLE
nodemailer.com down

### ISSUE THREAD

**Issue by gilesbutler** [nodemailer/nodemailer#945]
Hey guys,

Wasn't sure where to report this so feel free to close.

Looks like [nodemailer.com](https://downforeveryoneorjustme.com/nodemailer.com) is down and the documentation isn't accessible.

Thanks

**Comment by Paul52Games** [comment]
For me nodemailer.com is up

**Comment by gilesbutler** [comment]
It seemed to come back an hour or so later.
