### ISSUE TITLE
sendMail via SES not returning info.accepted

### ISSUE THREAD

**Issue by James2516** [nodemailer/nodemailer#948]
I'm using SES with nodemailer:
```
let nodemailer = require('nodemailer');
let aws = require('aws-sdk');

aws.config.loadFromPath('config.json');

let transporter = nodemailer.createTransport({
    SES: new aws.SES({
        apiVersion: '2010-12-01'
    })
});

transporter.sendMail({
    from: 'sender@example.com',
    to: 'recipient@example.com',
    subject: 'Message',
    text: 'I hope this message gets sent!',
    ses: { // optional extra arguments for SendRawEmail
        Tags: [{
            Name: 'tag name',
            Value: 'tag value'
        }]
    }
}, (err, info) => {
    console.log(info);
});
```

The `info.response` string returned was:
> '010001668cbaf1d3-7fadface-8253-49c5-ba34-dbb320d8a770-000000'
How should I decode this?

The returned result does not contain `info.accepted`, `info.rejected` etc as mentioned at https://nodemailer.com/usage/.

How would I find out if the email is successfully sent out?

**Comment by andris9** [comment]
Documentation in [usage](https://nodemailer.com/usage/) applies to the default SMTP transport. Other transports have different return values, you can find the SES values [here](https://nodemailer.com/transports/ses/#response). Basically if you do not get an error but you have the response (or actually messageId) property, then the message was accepted for delivery by SES. What happens next to it (is it really delivered to destination?) is out of control for Nodemailer.
