### ISSUE TITLE
attachment with authorization token header

### ISSUE THREAD

**Issue by davidk85** [nodemailer/nodemailer#959]
Hey,

i found the headers in attachments but this doenst work for me.

https://community.nodemailer.com/using-attachments/

i tried to send the bearer token (checked and is valid through an rest call test).

 "attachments": [
                {
                    "filename": "testfile.pdf",
                    "path": "http://localhost/mydoc/blub",
                    "headers": {
                        "Authorization": "Bearer XXX"
                    },
                }
            ]

Is there something wrong?

Nodemailer  4.6.8 / 4.7.0

Without authentication it works.

**Comment by andris9** [comment]
The built in attachment URL handler handles only simple GET urls. If you need to use special auth etc. then download the attachment first and add it to the mail object as regular file instead of the download link
