### ISSUE TITLE
Connection issue related to UV_THREADPOOL_SIZE

### ISSUE THREAD

**Issue by xapasnon** [nodemailer/nodemailer#963]
I've spent way too many hours debugging this:
- Simple "standalone" example of nodemailer - works fine.
- When the same code is executed from within an event handler of a kafka data stream - Error: Connection timeout

Repeatable on windows, mac and linux. I.e. I know that it's not a firewall or smtp provider issue.

Debug led to that the actual DNS lookup call on net.connect (nodemailer\lib\smtp-connection\index.js line 260) never returns. 

After reading the docs of Node https://nodejs.org/api/dns.html this comment caught my attention: "Though the call to dns.lookup() will be asynchronous from JavaScript's perspective, it is implemented as a synchronous call to getaddrinfo(3) that runs on libuv's threadpool."

Changing the UV_THREADPOOL_SIZE from default 4 to 8 and tada: it works.

The whole UV_THREADPOOL_SIZE discussion is quite complex it seems (with a rather nice summary of ideas here https://github.com/libuv/libuv/issues/1959) and we can of course opt to just change the ENV var for now.

But my question here is: wouldn't it make sense to allow i.e. dns.resolve* to be used in nodemailer to avoid this issue all together? 

In the simplest form, allowing opts to pass on the "lookup" parameter. 

Since the format of the lookup is non-trivial, maybe the preferred way would be some kind of config that bascially sets the lookup properly to use dns.resolve instead of dns.lookup

Thanks in advance for all and any input on this =)

**Comment by andris9** [comment]
Yeah, dropping getaddrinfo would make sense. Though it would raise the question of caching DNS responses etc. If you run a high performace sender, then you probably want to handle DNS yourself, for example here's the SMTP connection options for smtp.gmail.com (tls.servername is needed to pass TLS certificate check):

    let options = {
        host: "173.194.73.108",
        port: 465,
        secure: true,
        tls: {
            servername: "smtp.gmail.com"
        }
    };

**Comment by andris9** [comment]
Nodemailer v5.0.0 uses dns resolving for SMTP hostnames by default which should help on your case
