### ISSUE TITLE
550 I cannot deliver mail for ...

### ISSUE THREAD

**Issue by zerok78** [nodemailer/nodemailer#964]
Hello,

I'm getting the following error when I send a message using a previous created ethereal account (tested using _gmail_ and _sendgrid_):

`550 I cannot deliver mail for <...>`

Same code worked several days ago.

**Comment by andris9** [comment]
ethereal.email runs in a small VPS and it breaks often due to being low on memory

**Comment by armmmo** [comment]
having the same problem running on haraka, getting error Error: Message failed: 550 I cannot deliver mail for ...
