### ISSUE TITLE
Deep links are not working with node mailed

### ISSUE THREAD

**Issue by rahulraykor** [nodemailer/nodemailer#965]
I am using node mailer to send emails. But facing issues when my html mail is having **deep link** as href to anchor tag.
It seems that **anchor tag is filtering out href** if it is not having "http" as starting string.
As I am using **deep link** for word my link always has **"ms-word:ofe|u|"** in start so that it directly opens in MS Word Application.
Below is the sample html 

`<p><a href="ms-word:ofe|u|https://github.com/nodemailer/nodemailer/issues/" target="blank">Click</a> to open the document for editing</p>`

**Comment by andris9** [comment]
Links are parsed on the client side. I doub't any email client allows to use such non-standard links. Nodemailer sends the HTML exactly as you have provided it.
