### ISSUE TITLE
No matching version found for flatmap-stream@0.1.1

### ISSUE THREAD

**Issue by sachithkadamba** [nodemailer/nodemailer#969]
On trying install nodemailer getting below error 

Command: npm install nodemailer --save
Node v10.10.0
npm 6.4.1
----------------------------
npm ERR! code ETARGET
npm ERR! notarget No matching version found for flatmap-stream@0.1.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'event-stream'
npm ERR! notarget

**Comment by andris9** [comment]
This is not an issue of Nodemailer. Your package.json somehow references to the malicious event-stream package that was deleted from the NPM registry. Nodemailer itself does not have any dependencies.
