### ISSUE TITLE
Sporadic ENOENT errors

### ISSUE THREAD

**Issue by MacroMan** [nodemailer/nodemailer#970]
I occasionally get the following error in my logs from nodemailer:
```
{ Error: spawn sendmail ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
      at onErrorNT (internal/child_process.js:362:16)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)
    errno: 'ENOENT',
    code: 'ENOENT',
    syscall: 'spawn sendmail',
    path: 'sendmail',
    spawnargs:
     [ '-i',
       '-f',
       'sender@example.com',
       'recieptient.name@example.com' ] }
```

I am using Ubuntu 18.04 running NodeJS v8.15.0 and nodemailer v4.6.3
All works fine, but only sometimes does this error occur. I've not put my finger on the cause yet.
Here is my code: https://gist.github.com/MacroMan/289df556e3623df8083af9b8972e758f
My code is all pretty simple, but I'm really struggling to pinpoint this problem.

**Comment by andris9** [comment]
You might need to set the `path` option for the transport (see [docs](https://nodemailer.com/transports/sendmail/)). If path is not provided then Nodemailer uses $PATH to find the sendmail executable. In any case the error means that Nodemailer tries to invoke "sendmail" but the executable is not there for whatever reason.
