### ISSUE TITLE
SES throttling documentation causes infinite email sending loop

### ISSUE THREAD

**Issue by ricick** [nodemailer/nodemailer#972]
The documentation for the SES transport gives an example on how to wait for throttling to send emails:

transporter.on('idle', () => {
    while (transporter.isIdle()) {
        transporter.sendMail(...);
    }
});

However this creates an infinite loop if it is hit quickly in succession. The correct code should be:

transporter.once('idle', () => {
    while (transporter.isIdle()) {
        transporter.sendMail(...);
    }
});

Had a disaster with a live system over the weekend because of this :(

**Comment by haydeng21** [comment]
Trying to setup email throttling for a live system of mine as well. 

Is it confirmed that the below code works correctly and won't cause infinite loop?

```
transporter.once('idle', () => {
while (transporter.isIdle()) {
transporter.sendMail(...);
}
});
```

**Comment by ricick** [comment]
It's what worked for me, but it'd be good to get some confirmation from somebody else

**Comment by haydeng21** [comment]
Yeah I agree. Where did you find the trasnporter.once('idle' code?

**Comment by ricick** [comment]
> Yeah I agree. Where did you find the trasnporter.once('idle' code?

It was in the docs for the event dispatcher that nodemailer is using.

**Comment by andreyrd** [comment]
This is still not fixed.

**Comment by RoosterH** [comment]
Tried with transporter.once but not working for me.

**Comment by DaveOrDead** [comment]
`transporter.once` also caused an infinite loop for me, however, I got it working by changing the `while` loop to an `if` statement. Not sure if this would have other undesired side effects, but so far seems to be working

```
transporter.once('idle', () => {
  if (transporter.isIdle()) {
    transporter.sendMail(...);
  }
});
```

**Comment by jacoblukewood** [comment]
This is not fixed.
