### ISSUE TITLE
Nice to have: verify method for jsonTransport - for consistency

### ISSUE THREAD

**Issue by ieugen** [nodemailer/nodemailer#980]
Hi,

I'm writing a readiness probe for nodemailer and I use the verify() call. During local testing I don't use a real server and I use the JsonTransport and I get the following error:

It would be nice to have a consistent interface and have an empty verify that returns always true.

Thanks,

```
node:31546) UnhandledPromiseRejectionWarning: TypeError: transport.verify(...).then is not a function
```

**Comment by andris9** [comment]
Verify methods only exist for SMTP transports.
