### ISSUE TITLE
A simple CSS declaration to greatly improvement to readability on the website

### ISSUE THREAD

**Issue by guylepage3** [nodemailer/nodemailer#982]
Hi, love what you're doing. Could you please add this one simple CSS declaration to your `code` tag on your website to  improve readability?

```
code {
  line-height: 1.5rem;
}
```

Here's an example of how much better and easier it it to read the code blocks with this simple declaration is applied to your html `code` tag.

<img width="1216" alt="screenshot 2019-02-23 09 51 12" src="https://user-images.githubusercontent.com/1711854/53288035-db24a000-3751-11e9-9f57-e73dab644a73.png">

Thanks.

**Comment by guylepage3** [comment]
It currently looks like this and is much more difficult to read. Thank you again.

<img width="1239" alt="screenshot 2019-02-23 10 02 52" src="https://user-images.githubusercontent.com/1711854/53288066-41a9be00-3752-11e9-82aa-d93ec244d18d.png">

**Comment by andris9** [comment]
Should be fixed now. Might require refreshing the page if cached.

**Comment by guylepage3** [comment]
Much better sir. 👍
