### ISSUE TITLE
Subject and body not sending

### ISSUE THREAD

**Issue by natestarner** [nodemailer/nodemailer#983]
When sending an basic email via sendmail, I receive the email, with the correct sender, but there is no subject or body:
`var transporter = nodemailer.createTransport({
    sendmail: true,
    path: '/usr/sbin/sendmail'
});

transporter.sendMail({
    from: 'sender@example.com',
    to: 'myaccount@hotmail.com',
    subject: 'The crypto',
    text: 'I hope this message gets delivered!'
}, (err, info) => {
    console.log(info.envelope);
    console.log(info.messageId);
});`

**Comment by andris9** [comment]
Sendmail support is as is. There might be something in sendmail that breaks the email
