### ISSUE TITLE
(Memory Leak) Attachment content as buffer

### ISSUE THREAD

**Issue by xr0master** [nodemailer/nodemailer#986]
Hey.
I am sending an email with the attachment, where the content is Buffer.
The size of the file is 290kb.

When I create the heap snapshot, we can see this memory leak:
![Screen Shot 2019-03-13 at 6 23 44 PM](https://user-images.githubusercontent.com/8962340/54297901-6b6f3b80-45c0-11e9-927d-9812951990db.png)

Thanks.

Nodemailer 5.1.1
Node 10.14.1

**Comment by xr0master** [comment]
@kjarmicki I know it is not your problems, but did you use the attachments? If yes, then how? This leak finishes my memory in a few days...
Probably as the workaround to use stream instead of buffer.

**Comment by krystianjarmicki-silvair** [comment]
@xr0master I did not, the messages I sent were a couple of kbs (html + inlined css), but it was enough to bring the service down just about every other day.

**Comment by kjarmicki** [comment]
@xr0master I did not, the messages I sent were a couple of kbs of html + inlined css, but it was enough to bring the service down just about every other day.

**Comment by xr0master** [comment]
Same reason:
https://github.com/nodemailer/nodemailer/issues/979
