### ISSUE TITLE
MessageTime and envelopeTime

### ISSUE THREAD

**Issue by crashbdx** [nodemailer/nodemailer#988]
Hello, what are envelopeTime and messageTime refering too exactly ? is it a timestamp ?
In the sendMail response i don't see any timestamp, is there a way to have the exact one when the message was sent ?

Thank you.

**Comment by andris9** [comment]
`envelopeTime` refers to the time SMTP envelope was sent to TCP socket. `messageTime` indicates the time message was fully written to TCP socket. Your callback fires immediately after the SMTP server has accepted the message. There might be delays between these times and it is for debugging purposes only.

**Comment by crashbdx** [comment]
Thanks for the infos.

**Comment by faizbyp** [comment]
does nodemailer have any documentation on this? currently I'm having trouble receiving email sent through nodemailer. it has large delay time so I want to debug and see where the problem exist.
