### ISSUE TITLE
Alternative for document.write to print/show the javascript result is not present 

### ISSUE THREAD

**Issue by TSSumanth** [nodemailer/nodemailer#991]
Code:
Object.js file:
function tryMe(arg) {
    document.write(arg);
}

HTML file:
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src='object.js'> </script>
    <title>abc</title><meta charset="utf-8"/>
</head>
<body>
    <script>
    tryMe('This is me  signing in');
    </script>
</body>
</html>

 await readHTMLFile(__dirname + '/document3.html', function(err:any, html:any) {
        var template = handlebars.compile(html);
        var replacements = {
        };
        htmlToSend= template(replacements);
       var mailOptions = {
          from: 'from email',
          to: 'to email',
          subject: 'Testing Node Mailer Configuration',
          text: "test",
          html: htmlToSend
        };
      transporter.sendMail(mailOptions, function(error:any, info:any){
          if (error) {
            console.log("Error :");
            console.log(error);
          } else {
            console.log('Email sent: ' + info.response);
          }
        });   
      });

In the email i am not able to see the content in document.write. Do i need to use any alternative.??
Please help.

**Comment by andris9** [comment]
Email HTML does not support javascript
