### ISSUE TITLE
Nodemailer - ETIMEDOUTT at TCPConnectWrap.afterConnect

### ISSUE THREAD

**Issue by damosull** [nodemailer/nodemailer#992]
I am trying to use Nodemailer to send an email from a Gmail account.
On my Gmail account, I have updated my security to allow for "less secure" apps.

Below is my code:

`console.log("EMAIL DETAILS: " + output);
  try {
    var transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: "myemail@mail.com",
        pass: "mypassword"
      },
      tls: {
        rejectUnauthorized: false
      }
    });
  } catch (err) {
    console.log(err.message);
  }

  const mailOptions = {
    from: "myemail@mail.com", // sender address
    to: "myemail@mail.com", // list of receivers
    subject: "Test email", // Subject line
    html: output // plain text body
  };

  let info = await transporter.sendMail(mailOptions);

  console.log("Message sent: %s", info.messageId);
  console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));`

When I click the Submit button on my form, the email details are logged to the console initially, so I know that the **output** variable is being populated correctly.

But instead of sending the email, I get the below error in the console:

> (node:8376) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 173.194.175.108:465
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
(node:8376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Can someone please tell me what may be causing this issue? Thanks a lot in advance!

**Comment by andris9** [comment]
`connect ETIMEDOUT` is usually firewall issue. Might be either side.
