### ISSUE TITLE
DKIM not working for me

### ISSUE THREAD

**Issue by rodrigoarancibiapla** [nodemailer/nodemailer#995]
I have this code using nodemailer v6.0.0 with node v11.4.0

I am testing the sign of the message. But I can't see that it works. I made a certificate using:

openssl genrsa -des3 -out private.pem 2048

i have this code:

    "use strict";
    const nodemailer = require("nodemailer");
    const fs= require("fs");
    async function main(){
      let account = await nodemailer.createTestAccount();
      let transporter = nodemailer.createTransport({
        host: "smtp.ethereal.email",
        port: 587,
        secure: false, // true for 465, false for other ports
        auth: {
          user: account.user, // generated ethereal user
          pass: account.pass // generated ethereal password
        },
        tls: {
            rejectUnauthorized: false
        },
        debug:true,
        logger: true
       });

      let mailOptions = {
          envelope: {
          'from': 'MB_TEST.1.23.455@example.com',
          'to': "bar@example.com"
        },
        from: '<foo@example.com>', // sender address
        to: "bar@example.com, baz@example.com", // list of receivers
        subject: "Hello ✔", // Subject line
        text: "Hello world?", // plain text body
        html: "<b>Hello world?</b>", // html body
        dkim: {
                      domainName: "ethereal.email",
                      keySelector: "2017",
                      privateKey: fs.readFileSync("private.pem","utf8")
                    }
      };

      let info = await transporter.sendMail(mailOptions)
      console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
    }

    main().catch(console.error);

Inside, the log shows this:

DEBUG Signing outgoing message with 1 keys

When I saw the result in ethereal, it did not sign the message, the result is here:

Return-Path: <mb_test.1.23.455@example.com>
Content-Type: multipart/alternative;
 boundary="--_NmP-93fa030ec2a12784-Part_1"
From: =?UTF-8?Q?Fred_Foo_=F0=9F=91=BB?= <foo@example.com>
To: bar@example.com, baz@example.com
Subject: =?UTF-8?Q?Hello_=E2=9C=94?=
Message-ID: <c76c545b-56b8-e5f3-40b0-370d3629870f@example.com>
Date: Fri, 05 Apr 2019 13:26:55 +0000
MIME-Version: 1.0

----_NmP-93fa030ec2a12784-Part_1
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

Hello world?
----_NmP-93fa030ec2a12784-Part_1
Content-Type: text/html
Content-Transfer-Encoding: 7bit

<b>Hello world?</b>
----_NmP-93fa030ec2a12784-Part_1--

does anyone know why?

**Comment by andris9** [comment]
This usually happens when Nodemailer is not able to use the provided private key (invalid or unsupported format). Configuration seems to be correct.
