### ISSUE TITLE
SMTP transport failed on v5.0.0 and superior

### ISSUE THREAD

**Issue by jfroffice** [nodemailer/nodemailer#997]
When using the v4.7.0 it works but on version > it breaks

I am using this fake SMTP server from mailtrap.io
```
{
        host: 'smtp.mailtrap.io',
        port: 2525,
        auth: {
            user: '6ffdbaa506d98d',
            pass: '48c99d0fd25d01',
        },
}
```

Thank you in advance for your help

**Comment by andris9** [comment]
Breaks in what way?

**Comment by jfroffice** [comment]
The send is going in timeout.

There are no error, no callback, no catch nothing... 

Even when I use
```
debug: true,
logger: true
```

**Comment by jfroffice** [comment]
I am finally getting this log
```
{ Error: queryA ETIMEOUT smtp.mailtrap.io
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:213:19)
  errno: 'ETIMEOUT',
  code: 'EDNS',
  syscall: 'queryA',
  hostname: 'smtp.mailtrap.io',
  command: 'CONN' }
```

**Comment by andris9** [comment]
Nodemailer is not able to use the DNS resolver of your system. Use hard coded IP address as the host

```
{
        host: '52.44.212.96',
        port: 2525,
        auth: {
            user: '6ffdbaa506d98d',
            pass: '48c99d0fd25d01',
        },
        tls: {
            servername: 'smtp.mailtrap.io'
        }
}
```

**Comment by j1348** [comment]
I disagree for the usage of the DNS as it works on previous version.

So this sounds like a real issue.

**Comment by andris9** [comment]
The breaking change in v5 was how DNS is resolved, this is why the major version was bumped from v4 - it is not compatible with all previously supported platforms/systems

**Comment by SaiPravesh** [comment]
I have also faced exactly same issue and it's resolved when using IP address instead of hostname in-spite of having a host-file entry, so it appears it does not even look at the host-file.

**Comment by junlouiegonzales** [comment]
Hello, 

I have a similar problem and I'm using SendGrid as my email provider.

I just want to ask where did you get the IP address?

It's my machine IP address? because I'm just testing it locally. 

or the IP address of the SMTP server? (smtp.sendgrid.net)

![image](https://user-images.githubusercontent.com/20350350/95012847-64aa8c80-066e-11eb-8488-60e1e6e008f5.png)

Sorry for the noob question.

Thank you.

**Comment by SaiPravesh** [comment]
@junlouiegonzales its the IP of the SMTP server

**Comment by junlouiegonzales** [comment]
I get the SMTP server IP address using mxtoolbox.com

And changed my mail URL from this

`smtps://<username>:<password>@smtp.sendgrid.net:465`

to this

`smtps://<username>:<password>@<ipaddress>:465`

My problem solved. 

Thank you.

**Comment by chozhanrr** [comment]
Please check whether you have restarted the server after you have made changes to the env. variables.
