### ISSUE TITLE
What's the breaking change in version 6?

### ISSUE THREAD

**Issue by everhardt** [nodemailer/nodemailer#999]
I'm updating my packages and see that nodemailer has reached version 6.

I can't find what's breaking though: in the README.md I only see "Why version bump to 5?", the releases do not contain any notes, I can't find a changelog in the docs and the commit messages also do not help (without really diving in). 

So basically my request: could you please state somewhere what the breaking changes are? Many thanks!

**Comment by andris9** [comment]
There is a change in socket event handling ([CHANGELOG](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md#600-2019-03-25)). It may or may not work with all supported versions of node and platforms, not tested well enough.

**Comment by chichilatte** [comment]
We have a project on version 2.7.0. Would love to upgrade, but like the OP said, each major release has no changelog, not even a list of breaking changes. I'll give it a go upgrading, see what breaks. I just wanted to mention that it's super useful to have a list of breaking changes for major releases.
